/**
 * JAMB/UTME 2009 — PRINCIPLES OF ACCOUNTS
 * From the 2009 question paper (questions 1–50); answers from the JAMB/UTME Accounts answer key 2001–2020,
 * each checked independently. Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2009;
  const SRC = 'JAMB UTME 2009';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const TB = "Use the following information: \nCapital ... ₦2,375,000\nDebtors ... ₦495,000\nMotor vehicles ... ₦870,000\nCreditors ... ₦245,000\nPrepayments ... ₦500,000\nBills receivable ... ₦505,000\nFurniture ... ₦150,000\n\n";
  const LIST = "Use the following information: \nI. Operating machines; II. Furniture; III. Fixtures and fittings; IV. Loans from friends; V. Creditors\n\n";
  const PETTY = "Use the following information: \nPeriod 1:\nCash to petty cashier ... ₦1,000\nPetty cashier pays out ... ₦780\nPeriod 2:\nPetty cashier pays out ... ₦840\n\n";
  const BANK = "Use the following information: \nBalance as per cash book ... ₦20,000\nUnpresented cheques ... ₦5,200\nDirect credit to the bank ... ₦1,000\nDirect debit from the bank ... ₦1,000\nCredit in the cash book ... ₦500\n\n";
  const ADODO = "Use the following information: \nAdodo Enterprises Profit and Loss Account [Extract]\nOpening stock ... ₦5,000\nPurchases ... ₦90,600\n(Subtotal ... ₦95,600)\nLess closing stock ... ₦5,600\nCost of goods sold ... ₦90,000\nGross profit ... ₦10,000\nTotal ... ₦100,000\nSales ... ₦100,000\n\n";
  const BAL = "Use the following information: \nTotal current assets ... ₦2,000\nTotal fixed assets ... ₦4,000\nCurrent liabilities ... ₦1,200\nDrawings ... ₦200\nLong-term loan ... ₦2,000\n\n";
  const STK = "Use the following information: \nJan. 1 ... Received 1,000 units at ₦10 each\nJan. 2 ... Received 2,000 units at ₦12 each\nJan. 3 ... Issued 1,500 units\nJan. 4 ... Received 1,000 units at ₦11 each\nJan. 5 ... Issued 1,000 units\n\n";
  const ACCR = "Use the following information: \n... 30/9/06 ... 30/9/07\nAccrued rent income ... ₦600 ... ₦710\nPrepaid insurance premium ... ₦490 ... ₦630\nThe cash book includes ₦1,850 and ₦2,100 in respect of insurance premium and rent income respectively.\n\n";
  const MFG = "Use the following information: \nWork-in-progress 1/1 ... ₦1,000\nWork-in-progress 31/12 ... ₦2,000\nProduction cost of goods manufactured ... ₦20,000\nSales ... ₦50,000\nStock of finished goods 1/1 ... ₦4,000\nStock of finished goods 31/12 ... ₦5,000\nSelling and distribution expenses ... ₦2,000\nAdministrative expenses ... ₦1,000\n\n";
  const CLUB = "Use the following information: \nFurniture and fittings ... ₦20,000\nEquipment ... ₦15,000\nBank overdrafts ... ₦6,500\nBar creditors ... ₦4,800\nSubscription in arrears ... ₦4,700\nSubscription in advance ... ₦650\n\n";
  const DEPT = "Use the following information: \nDepartments ... P ... Q ... R\nSales value ... ? ... ₦23,400 ... ?\nSelling expenses ... ₦1,100 ... ₦1,400 ... ₦1,280\nAdministrative expenses ... ₦1,400 ... ₦1,000 ... ₦1,020\nCost of sales ... ₦6,900 ... ₦6,700 ... ₦5,500\nSales value of department Q is double that of P, which is 1/3 of R. Depreciation, which amounts to ₦1,800, is to be apportioned among the three departments in the ratio 3:5:7 respectively.\n\n";
  const MK = "Use the following information: \nNet profit b/d ... ₦10,000\nInterest on capital: M ... ₦2,000\nInterest on capital: K ... ₦1,000\nPartners' salary: K ... ₦800\nInterest on drawings: M ... ₦500\nProfit sharing ratio, M and K ... 3:2\n\n";
  const PK = "Use the following information: \nCapital balance b/d: P ... ₦20,000\nCapital balance b/d: K ... ₦10,000\nDrawings: P ... ₦2,000\nDrawings: K ... ₦1,000\nShare of profits: P ... ₦4,000\nShare of profits: K ... ₦2,000\nSalary: P ... ₦1,000\nInterest on drawings: P ... ₦100\nInterest on drawings: K ... ₦20\n\n";
  const SHARES = "Use the following information: \nA company advertised and issued ₦750,000, 12% preference shares of ₦1 each to be issued at ₦1.50 per share. Applications for 1,370,000 shares were received at 30k per share. 70k per share (including premium) was due on allotment, while 25k per share was due on each of the remaining two calls. All amounts due were received. Application money for 120,000 shares was refunded to unsuccessful applicants and the remaining applicants were allotted shares on a pro-rata basis.\n\n";

  QUESTION_BANK.accounting = QUESTION_BANK.accounting.concat([
    // paper 1–10
    q("Which of the following branches of accounting was first developed?",
      ["Cost accounting", "Financial accounting", "Management accounting", "Petroleum accounting"], B,
      "Financial accounting, built on double entry (described by Luca Pacioli in 1494), came first; cost and management accounting grew later with industry."),
    q("The accounting convention which states that the performance of a business should be determined by matching all expenses against all revenue is",
      ["accruals", "materiality", "objectivity", "periodicity"], A,
      "The accruals (matching) concept matches the expenses of a period with the revenue they helped to earn, whether or not cash has moved."),
    q("The process of bookkeeping includes records produced from",
      ["ledgers", "source documents", "minutes of meetings", "intuitive reasoning"], B,
      "Bookkeeping starts from source documents such as invoices, receipts and credit notes, which are entered in the books of original entry."),
    q("Musa, a prepaid customer of XYZ and KLM, bought ₦1,500 recharge card from XYZ and ₦2,000 recharge card from KLM for business calls. The entry to record these transactions is debit",
      ["telephone ₦3,500, credit XYZ and KLM ₦3,500", "telephone ₦3,500, credit cash ₦3,500", "sundries ₦3,500, credit KLM ₦3,500", "sundries ₦3,500, credit telephone ₦3,500"], B,
      "Prepaid recharge cards are bought and paid for at once, so telephone expense is debited ₦3,500 and cash is credited ₦3,500."),
    q(TB + "What is the total debit for the trial balance?",
      ["₦4,690,000", "₦262,000", "₦2,520,000", "₦1,565,000"], C,
      "Debit balances are the assets: ₦495,000 + ₦870,000 + ₦500,000 + ₦505,000 + ₦150,000 = ₦2,520,000. Capital and creditors are credits."),
    q("If Odukoya takes money out of the business bank account for his own private use, the effect of the transaction is",
      ["increase in assets and increase in capital", "increase in assets and decrease in capital", "decrease in capital and increase in assets", "decrease in capital and decrease in assets"], D,
      "Drawings of cash reduce the bank balance (an asset) and reduce the owner's capital by the same amount."),
    q(LIST + "What are the current liabilities?",
      ["I and II", "IV and V", "III and V", "II and IV"], B,
      "Creditors and loans from friends are amounts the business owes; machines, furniture and fixtures are fixed assets."),
    q(LIST + "Find the fixed assets.",
      ["I, II and V", "I, II and IV", "I, II and III", "III, IV and V"], C,
      "Operating machines, furniture, and fixtures and fittings are long-term assets used in the business, so they are fixed assets."),
    q(PETTY + "If the float is increased to ₦1,200, how much should the petty cashier receive after period 2?",
      ["₦160", "₦840", "₦1,000", "₦1,040"], D,
      "After period 2 the cashier holds ₦1,000 − ₦840 = ₦160. To bring the float up to the new ₦1,200 he must receive ₦1,200 − ₦160 = ₦1,040 (₦840 spent + ₦200 increase).",
      { bookletKey: 'B', bookletNote: "₦840 would only restore the old float of ₦1,000. The float is being raised to ₦1,200, so the cashier needs the ₦840 spent plus the ₦200 increase: ₦1,200 − ₦160 in hand = ₦1,040." }),
    q(PETTY + "What is the balance of cash with the petty cashier at the end of period 1?",
      ["₦220", "₦780", "₦980", "₦1,780"], A,
      "Balance = cash received ₦1,000 − payments ₦780 = ₦220."),
    // paper 11–20
    q("Cash discounts are often recorded on",
      ["the debit side of the cash book", "the credit side of the cash book", "the folio column of the cash book", "both credit and debit side of the cash book"], D,
      "Discount allowed is entered on the debit (receipts) side and discount received on the credit (payments) side of a three-column cash book."),
    q("The standing order is a payment instrument given by a",
      ["customer to the bank", "bank to a customer", "bank to an employee", "customer to a fellow customer"], A,
      "A standing order is a customer's written instruction to his bank to pay a fixed amount to someone at regular intervals."),
    q("Which of the following should not be added or subtracted from the cash book balance to determine the adjusted cash balance?",
      ["Error by the bank", "Undercasting of the cash book", "Overcasting of the cash book", "Bank service charges"], A,
      "An error made by the bank is corrected on the bank statement side; it does not change the cash book. Casting errors and bank charges are adjusted in the cash book."),
    q(BANK + "Calculate the balance as per bank statement at the end of the year",
      ["₦24,700", "₦25,200", "₦26,200", "₦27,700"], A,
      "The direct credit (+₦1,000) and direct debit (−₦1,000) cancel, leaving the adjusted cash book at ₦20,000. Then add unpresented cheques ₦5,200 and deduct the ₦500 entered in the cash book but not yet on the statement: ₦24,700."),
    q(ADODO + "If the gross profit margin is 10%, what is the value of the cost of goods sold?",
      ["₦10,000", "₦90,000", "₦105,600", "₦110,000"], B,
      "Gross profit = 10% × ₦100,000 = ₦10,000, so cost of goods sold = ₦100,000 − ₦10,000 = ₦90,000."),
    q(ADODO + "If the opening stock is 5% of sales, calculate the purchases",
      ["₦95,600", "₦95,000", "₦90,600", "₦85,000"], C,
      "Opening stock = 5% × ₦100,000 = ₦5,000. Purchases = cost of goods sold ₦90,000 + closing stock ₦5,600 − opening stock ₦5,000 = ₦90,600."),
    q(BAL + "Determine the capital of the business",
      ["₦9,400", "₦6,000", "₦3,400", "₦2,600"], D,
      "Net assets = ₦2,000 + ₦4,000 − ₦1,200 − ₦2,000 = ₦2,800. The answer given, ₦2,600, deducts drawings a second time.",
      { keyVerdict: 'none', keyAnswer: 'D', answerNote: "Capital = total assets − liabilities = ₦6,000 − ₦1,200 − ₦2,000 = ₦2,800, and drawings have already reduced those assets (before drawings the capital would be ₦3,000). ₦2,600 deducts the ₦200 drawings again, so no option is fully correct; D is kept as the answer usually given." }),
    q(BAL + "What is the net working capital?",
      ["₦2,600", "₦1,800", "₦800", "₦600"], C,
      "Net working capital = current assets ₦2,000 − current liabilities ₦1,200 = ₦800."),
    q("Which of the following items are current assets?",
      ["Stock, bills receivable, cash and debtors", "Stock, bad debt, bill receivable and cash", "Stock, bad debt, bills receivable and cash", "Stock, work-in-progress, cash and bills payable"], A,
      "Stock, bills receivable, cash and debtors are all short-term assets. A bad debt is an expense, and bills payable are a liability."),
    q(STK + "Using FIFO method, what is the value of closing stock?",
      ["₦34,000", "₦29,000", "₦65,000", "₦12,000"], C,
      "Under FIFO the closing 1,500 units are the latest: 500 × ₦12 + 1,000 × ₦11 = ₦17,000, which is not among the options.",
      { keyVerdict: 'none', keyAnswer: 'C', answerNote: "FIFO issues the oldest units first. Jan 3 issue: 1,000 at ₦10 + 500 at ₦12, leaving 1,500 at ₦12. Jan 5 issue: 1,000 at ₦12, leaving 500 at ₦12 + 1,000 at ₦11 = ₦17,000. None of the options shows ₦17,000; C is kept only as the answer usually given." }),
    // paper 21–30
    q(STK + "What is the value of closing stock using simple average?",
      ["₦11,500", "₦17,000", "₦17,500", "₦28,500"], B,
      "Jan 3 issue at (₦10 + ₦12) ÷ 2 = ₦11: ₦16,500. Jan 5 issue at (₦12 + ₦11) ÷ 2 = ₦11.50: ₦11,500. Closing stock = ₦45,000 − ₦16,500 − ₦11,500 = ₦17,000.",
      { bookletKey: 'D', bookletNote: "₦28,500 is the stock value on Jan 4, before the last issue (₦34,000 − ₦16,500 + ₦11,000). After issuing 1,000 units at ₦11.50 (₦11,500), the closing stock is ₦28,500 − ₦11,500 = ₦17,000." }),
    q("Which of the following methods gives a conservative closing stock value during a period of rising prices?",
      ["LIFO", "FIFO", "Simple average", "Periodic simple average"], A,
      "When prices rise, LIFO issues the newest (dearest) units, so closing stock is valued at the oldest, lowest prices. IAS 2 no longer allows LIFO today."),
    q("Apart from the common control accounts, a control account can also be opened for",
      ["sales account", "purchases account", "cash account", "wages account"], D,
      "Besides the sales and purchases ledger control accounts, a wages (payroll) control account is often kept to check wages and deductions."),
    q("Which of the following is a debit item in the purchases ledger control account?",
      ["Balance b/d", "Cheque dishonoured", "Purchases", "Balance c/d"], D,
      "The purchases ledger control account normally has a credit balance, so the closing balance c/d is entered on the debit side. Balance b/d, purchases and our dishonoured cheques are credits.",
      { bookletKey: 'B', bookletNote: "When a cheque we paid to a supplier is dishonoured, we owe the supplier again, so the purchases ledger control account is credited, not debited. The debit item listed is balance c/d." }),
    q("Which of the following is an item in the debit side of the sales ledger control account?",
      ["Interest charged to customers", "Bills receivable honoured", "Transfer of credit balances from credit control account", "Transfer of debit balances from creditors control account"], A,
      "Interest charged to customers on overdue accounts increases what debtors owe, so it is debited to the sales ledger control account."),
    q(ACCR + "The insurance premium to be taken to the profit and loss account would be",
      ["₦1,340", "₦1,850", "₦1,990", "₦1,710"], D,
      "Insurance paid ₦1,850 + prepaid at the start ₦490 − prepaid at the end ₦630 = ₦1,710."),
    q(ACCR + "What amount is to be credited to the profit and loss account in respect of rent income?",
      ["₦2,210", "₦1,760", "₦2,000", "₦2,240"], A,
      "Rent received ₦2,100 − accrued at the start ₦600 + accrued at the end ₦710 = ₦2,210."),
    q("The costs incurred by departments that support the production department with such activities as maintenance, production control and storage are called",
      ["autonomous costs", "service costs", "supporting costs", "subsidiary costs"], C,
      "Departments such as maintenance and stores support the production departments; their costs are called support (supporting) or service department costs.",
      { keyVerdict: 'multiple', alsoAccept: [B], keyAnswer: 'C', answerNote: "Both names are used: British texts call these service (department) costs, while many others call them support (supporting) department costs. B and C are both accepted." }),
    q(MFG + "Determine the gross profit",
      ["₦49,000", "₦48,000", "₦31,000", "₦27,000"], C,
      "Cost of sales = ₦4,000 + ₦20,000 − ₦5,000 = ₦19,000; gross profit = ₦50,000 − ₦19,000 = ₦31,000."),
    q(MFG + "What is the net profit?",
      ["₦46,000", "₦45,000", "₦28,000", "₦27,000"], C,
      "Net profit = gross profit ₦31,000 − selling and distribution ₦2,000 − administrative ₦1,000 = ₦28,000."),
    // paper 31–40
    q("Receipts and payments account is a summary of the",
      ["budget", "trading account", "cash book", "profit and loss account"], C,
      "A receipts and payments account summarises the cash book of a club or society: all cash received and paid in the period."),
    q(CLUB + "What is the accumulated fund?",
      ["₦23,700", "₦27,750", "₦29,650", "₦51,650"], B,
      "Assets ₦20,000 + ₦15,000 + ₦4,700 = ₦39,700; liabilities ₦6,500 + ₦4,800 + ₦650 = ₦11,950; accumulated fund = ₦27,750."),
    q("I. Space occupied by each department; II. Average value of stock held by each department; III. Departmental turnover; IV. Number of articles sold by each department\nFrom the information above, the two most logical bases for apportioning expenses that are common to departments are",
      ["I and II", "I and III", "II and III", "III and IV"], B,
      "Floor space is the usual basis for rent, rates and lighting, and turnover (sales) for selling and general expenses."),
    q(DEPT + "What is the sales value of department R?",
      ["₦7,800", "₦11,700", "₦23,400", "₦35,100"], D,
      "Q (₦23,400) is double P, so P = ₦11,700; P is 1/3 of R, so R = ₦11,700 × 3 = ₦35,100.",
      { bookletKey: 'B', bookletNote: "₦11,700 is the sales value of department P (₦23,400 ÷ 2). R is three times P: ₦11,700 × 3 = ₦35,100." }),
    q(DEPT + "Determine the total expenses of department P.",
      ["₦9,760", "₦9,400", "₦2,860", "₦2,500"], C,
      "P's expenses = selling ₦1,100 + administrative ₦1,400 + depreciation 3/15 × ₦1,800 = ₦360, a total of ₦2,860.",
      { bookletKey: 'D', bookletNote: "₦2,500 leaves out P's share of depreciation, which the question says must be apportioned: 3/15 × ₦1,800 = ₦360, so total expenses = ₦1,100 + ₦1,400 + ₦360 = ₦2,860." }),
    q("One of the purposes of maintaining the account of a branch at the head office is to",
      ["record charges in shareholdings", "record charges in liabilities", "check the excesses of customers", "check the excesses of members of staff"], D,
      "Branch accounts kept at head office let head office control the branch and check fraud or waste by branch staff."),
    q("Which of the following is a common cause of a discrepancy between head office and branch trial balance?",
      ["Debtors and cash in transit", "Creditors and cash in transit", "Stock and cash in transit", "Stock and prepayments"], C,
      "Goods (stock) and cash sent between head office and branch but not yet received at the year end make the two sets of books disagree.",
      { bookletKey: 'A', bookletNote: "Debtors are not sent between head office and the branch, so they are not 'in transit'. The usual items in transit are goods (stock) and cash." }),
    q("Sule and Ahmed are in partnership sharing profits and losses equally. If Khadija is admitted as a new partner to take 1/5 as her share, what is the new profit or loss sharing ratio?",
      ["Sule 1/3, Ahmad 1/3, and Khadija 1/3", "Sule 1/5, Ahmad 1/5, and Khadija 3/5", "Sule 2/5, Ahmad 2/5, and Khadija 1/5", "Sule 2/5, Ahmad 1/5, and Khadija 2/5"], C,
      "Khadija takes 1/5, leaving 4/5 for the old partners in their equal ratio: 2/5 each."),
    q(MK + "Determine M's share of profit",
      ["₦6,280", "₦4,020", "₦2,820", "₦2,280"], B,
      "₦10,000 + interest on drawings ₦500 − interest on capital ₦3,000 − salary ₦800 = ₦6,700 to share; M gets 3/5 × ₦6,700 = ₦4,020."),
    q(PK + "Assuming that the partnership maintains a fixed capital, what is P's closing capital?",
      ["₦25,000", "₦24,900", "₦22,900", "₦20,000"], D,
      "With fixed capitals, drawings, profit shares, salary and interest go to the current account, so P's capital stays at ₦20,000."),
    // paper 41–50
    q(PK + "If the capital of the partnership is unfixed, what is K's current account?",
      ["₦11,950", "₦10,980", "₦20,000", "Nil"], D,
      "With fluctuating (unfixed) capitals, no current accounts are kept: every item goes to the capital account, so K's current account is nil.",
      { keyVerdict: 'corrected', keyAnswer: 'B', answerNote: "₦10,980 is K's capital account balance under fluctuating capitals (₦10,000 − ₦1,000 + ₦2,000 − ₦20). The question asks for the current account, and when capitals are not fixed no current account is kept, so the answer is nil (D)." }),
    q("In partnership account, conversion of non-cash assets into cash is referred to as",
      ["realization", "disposal", "dissolution", "revaluation"], A,
      "Turning the assets into cash is realisation, recorded in the realisation account when a partnership is dissolved."),
    q(SHARES + "The share premium account would be",
      ["credited with application and allotment ₦187,500", "debited with application and allotment ₦375,000", "credited with application and allotment ₦375,000", "debited with application and allotment ₦187,500"], C,
      "The premium is 50k on each of the 750,000 shares (₦1.50 − ₦1), included in the allotment money: ₦375,000 credited to share premium."),
    q(SHARES + "The second and final call account was debited with",
      ["ordinary share capital account ₦187,500", "12% preference share capital ₦375,000", "bank account ₦187,500", "12% preference share capital account ₦187,500"], D,
      "When the call is made: debit second and final call account, credit 12% preference share capital, 25k × 750,000 = ₦187,500.",
      { bookletKey: 'A', bookletNote: "The shares being called up are 12% preference shares, not ordinary shares, so the call account is debited against 12% preference share capital account: 25k × 750,000 = ₦187,500." }),
    q("Provision for bad and doubtful debts in companies final accounts is treated in",
      ["trading account", "profit and loss account", "fund flow statement", "cash flow statement"], B,
      "An increase in the provision for doubtful debts is an expense charged to the profit and loss account (and the provision is deducted from debtors in the balance sheet)."),
    q("The book value per share is obtained by dividing",
      ["shareholders equity by outstanding shares", "total assets by outstanding shares", "gross profit by outstanding shares", "net profit by outstanding shares"], A,
      "Book value per share = shareholders' equity (net assets) ÷ number of shares outstanding."),
    q("Expenditure incurred on consumables and goods for resale is",
      ["revenue expenditure", "capital expenditure", "sunk cost", "miscellaneous expenses"], A,
      "Consumables and goods bought for resale are used up within the year to earn revenue, so they are revenue expenditure."),
    q("Replacement and renewal of fixed assets are",
      ["revenue receipt", "capital receipt", "capital expenditure", "revenue expenditure"], C,
      "Spending to replace or renew fixed assets gives the business assets that last for years, so it is capital expenditure."),
    q("Which of the following is credited to the consolidated revenue fund?",
      ["Recurrent expenditure", "Capital expenditure", "Transfers to revenue fund", "Internal revenue"], D,
      "All revenues of government, such as taxes and other internally generated revenue, are paid into (credited to) the Consolidated Revenue Fund.",
      { bookletKey: 'A', bookletNote: "Recurrent expenditure is paid out of (debited to) the Consolidated Revenue Fund. What is credited to the fund is revenue, such as internally generated revenue." }),
    q("One of the reasons for the existence of the public sector is to",
      ["take adequate care of the needy", "supplement the commercial sector", "provide cheap services to all citizens", "correct perceived inequalities"], C,
      "The public sector exists mainly to provide essential services (water, roads, health, education, security) to all citizens at low cost, which profit-seeking firms would not supply cheaply."),
  ]);
})();
