/**
 * JAMB/UTME 2011 — PRINCIPLES OF ACCOUNTS
 * From the 2011 question paper (questions 2–50; Q1 only asked for the paper type); answers from the
 * JAMB/UTME Accounts answer key 2001–2020, each checked independently. Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2011;
  const SRC = 'JAMB UTME 2011';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const DISC = "Use the following information: \nAdamu Stores bought accessories from Mu'azu Beverages for ₦400 on credit. A trade discount of 10% and a cash discount of 15% were provided.\n\n";
  const LIST = "Use the following information: \nI. Stock of goods\nII. Furniture\nIII. Creditors\nIV. Cash at bank\nV. Loan from the bank\n\n";
  const STK = "Use the following information: \nJune 30 Closing stock 100 units at ₦90.\nJuly 8 Purchased 200 units at ₦95.\nJuly 10 Sold 160 units.\nJuly 17 Returned 80 faulty units purchased at ₦95.\nJuly 18 Purchased 200 units at ₦105.\nJuly 20 Sold 180 units.\nJuly 28 Purchased 200 units at ₦110.\nJuly 29 Sold 120 units.\nJuly 30 Sold 100 units.\n\n";
  const INC = "Use the following information: \nIncomplete Record (Extract)\nSales ... ₦10,600\nRent ... ₦200\nDepreciation of vehicle (cost ₦5,000) ... 10%\nGross profit margin is 20%.\n\n";
  const TRD = "Use the following information: \nTrading account for the year ended 31st December 2009\nOpening stock ... ₦32,000\nPurchases ... ₦40,000\nCarriage inwards ... ₦1,000\n(Subtotal ... ₦41,000)\nLess returns ... ₦2,000\n(Net purchases ... ₦39,000)\nCost of goods available for sale ... ??\nLess closing stock ... ₦9,000\nCost of goods sold ... ??\nSales ... ₦4,800\nLess returns ... ₦2,000\n\n";
  const PART = "Use the following information: \nKeme and Kemi are in partnership sharing profits and losses in the ratio 3:2.\nCapital – Keme ... ₦20,000\nCapital – Kemi ... ₦10,000\nDrawings – Keme ... ₦20,000\nDrawings – Kemi ... ₦3,000\nProfit ... ₦6,000\nInterest on capital ... 5%\nInterest on drawings ... 10%\n\n";

  QUESTION_BANK.accounting = QUESTION_BANK.accounting.concat([
    // paper 2–10
    q("The historical development of accounting reveals that it",
      ["deals with debit and credit terms", "is a product of financial development", "is a product of its own environment", "is an ideal subject for financial development"], C,
      "Accounting grew up to meet the needs of each society and age (trade, partnerships, companies, taxation, regulation), so its history shows it is a product of its own environment.",
      { bookletKey: 'A', bookletNote: "The booklet answer A (deals with debit and credit terms) describes a feature of double entry, not what the history of accounting shows. Accounting changed as trade, business forms and laws changed around it, so it is a product of its own environment (C)." }),
    q("In a trial balance, income and liabilities are",
      ["debited and credited respectively", "credited", "credited and debited respectively", "debited"], B,
      "Income (gains) and liabilities both have credit balances, so both appear in the credit column of the trial balance."),
    q("The principle of double entry system ensures",
      ["mathematical accuracy in trial balance", "balance at the bank", "increases in the assets and liabilities", "balance of cash account"], A,
      "Because every debit has an equal credit, total debits equal total credits, so the trial balance agrees and the arithmetic of the books is proved."),
    q("I. Deduct the smaller side figure from the bigger side figure\nII. Add up both sides\nIII. Take the difference to the smaller side and add to the smaller figure\n\nThe correct procedure for balancing an account is",
      ["II, I and III", "I, III and II", "II, III and I", "I, II and III"], A,
      "First add up both sides (II), then find the difference by deducting the smaller total from the bigger (I), then enter the difference on the smaller side as the balance c/d (III)."),
    q("Given:\nLight expenses ... ₦400\nPurchases ... ₦3,000\nSales ... ₦1,200\nCreditors ... ₦2,250\nDebtors ... ₦50\n\nCalculate the total of the trial balance.",
      ["₦4,250", "₦3,500", "₦4,300", "₦3,450"], D,
      "Debits: light expenses ₦400 + purchases ₦3,000 + debtors ₦50 = ₦3,450; credits: sales ₦1,200 + creditors ₦2,250 = ₦3,450."),
    q("The major feature of a journal is that it has",
      ["six columns, date, particulars, folio, amount, debit and credit", "five columns, date, particulars, folio, debit and credit", "three columns, date, particulars, folio and amount", "four columns, date, particulars, folio and amount"], B,
      "The journal (proper) has five columns: date, particulars (with narration), folio, debit amount and credit amount."),
    q("The medium of correcting errors whose difference are shown in the trial balance is by the use of",
      ["debtors' account", "creditors' account", "suspense account", "ledger account"], C,
      "When the trial balance does not agree, the difference is put in a suspense account, which is cleared as each error that affects the totals is found and corrected."),
    q(DISC + "Find the total amount paid.",
      ["₦260", "₦300", "₦200", "₦380"], B,
      "JAMB's answer takes both discounts on the full ₦400 (₦400 − ₦40 − ₦60 = ₦300); correctly the amount paid is ₦306, which is not offered.",
      { keyVerdict: 'none', keyAnswer: 'B', answerNote: "Trade discount comes off first: ₦400 − 10% (₦40) = ₦360 invoice price. The cash discount is then worked on ₦360: 15% × ₦360 = ₦54, so the amount paid is ₦360 − ₦54 = ₦306, which is not among the options. ₦300 results only if the 15% is wrongly taken on the full ₦400." }),
    q(DISC + "Calculate the cash discount.",
      ["₦60", "₦90", "₦40", "₦100"], C,
      "Correctly the cash discount is 15% of the net invoice price of ₦360, which is ₦54 and not among the options; JAMB's answer is ₦40.",
      { keyVerdict: 'none', keyAnswer: 'C', answerNote: "The cash discount is worked on the price after trade discount: 15% × (₦400 − ₦40) = 15% × ₦360 = ₦54, which is not offered. JAMB's ₦40 is 10% of ₦400, which is the trade discount; ₦60 would be 15% of the full ₦400, also not correct." }),
    q("In bank reconciliation process, discrepancies caused by timing arise as a result of",
      ["cash book and bank statement", "bank statement only", "cash book, bank statement and other incidental records", "cash book only"], A,
      "Timing differences, such as unpresented cheques and uncredited lodgements, arise because the cash book and the bank statement record the same items on different dates."),
    // paper 12–20
    q("The process of reconciling cheques between banks is termed cheque",
      ["clearing", "truncation", "holding", "confirmation"], A,
      "Cheque clearing is the process by which banks exchange and settle the cheques drawn on one another, usually through a clearing house."),
    q("In a bank reconciliation statement, interest charged for overdrawn balances should be added to the",
      ["balance as per bank statement", "bank balance as per adjusted cash book", "aggregate balance as per cash book", "bank balance as per cash book"], A,
      "Interest charged by the bank has already reduced the bank statement balance but not the cash book, so when reconciling from the bank statement to the cash book it is added back to the balance as per bank statement."),
    q(LIST + "Determine the current liabilities.",
      ["III and V", "II and III", "IV and V", "I and II"], A,
      "Creditors (III) and the loan from the bank (V), treated here as a short-term loan, are amounts owed by the business; stock, furniture and cash at bank are assets."),
    q(LIST + "Find the current assets.",
      ["III and V", "II and I", "IV and V", "I and IV"], D,
      "Stock of goods (I) and cash at bank (IV) are current assets; furniture is a fixed asset, and creditors and the bank loan are liabilities."),
    q("The type of expense charged against the administration of a firm is",
      ["repairs on building", "interest paid on loan", "discount allowed", "tax expense"], A,
      "Repairs on (office) buildings are an administrative expense; interest paid is a finance cost, discount allowed a selling/finance cost, and tax is charged on profit, not as an administrative expense."),
    q("In a period of declining price, which of the following methods would result in higher profit?",
      ["FIFO", "Simple average", "LIFO", "Weighted average"], C,
      "When prices fall, LIFO charges the latest (cheapest) costs to cost of sales, so cost of sales is lowest and profit highest; FIFO charges the older, dearer costs and gives the lowest profit.",
      { bookletKey: 'A', bookletNote: "The booklet answer A (FIFO) gives higher profit when prices are RISING. When prices are falling, FIFO charges the older, dearer units to cost of sales, so profit is lowest; LIFO charges the newer, cheaper units, so profit is highest (C)." }),
    q("The item on the credit side of the trading account is the",
      ["returns outwards", "carriage on sales", "sales", "purchases"], C,
      "Sales (less returns inwards) are credited to the trading account; purchases, returns outwards (deducted from purchases) and carriage inwards are on the debit side, and carriage on sales goes to profit and loss."),
    q(STK + "How many units were at hand as at July 30?",
      ["80", "100", "60", "160"], C,
      "100 + 200 − 160 − 80 + 200 − 180 + 200 − 120 − 100 = 60 units."),
    q(STK + "What is the value of stock as at the end of July 10 using FIFO?",
      ["₦14,400", "₦13,300", "₦15,200", "₦12,600"], B,
      "Under FIFO the 160 units sold are the 100 at ₦90 and 60 at ₦95, leaving 140 units at ₦95 = ₦13,300."),
    q("A typical example of a real account is",
      ["prepayment", "expenses", "plant", "income"], C,
      "Real accounts record tangible assets such as plant, machinery, land and buildings; expenses and income are nominal accounts."),
    // paper 22–30
    q("The control account can be used in",
      ["recording all business transactions of the enterprise", "keeping records of all direct deposits in the bank account", "monitoring the books of original entry", "monitoring the efficiency of bookkeeping by accountants"], D,
      "Control accounts check the arithmetical accuracy of each ledger, help locate errors and act as an internal check on the work of the ledger clerks."),
    q(INC + "What is the cost of goods sold?",
      ["₦4,800", "₦8,480", "₦2,320", "₦9,900"], B,
      "A gross profit margin of 20% means gross profit is 20% of sales: ₦2,120, so cost of goods sold = ₦10,600 − ₦2,120 = ₦8,480."),
    q(INC + "Calculate the net profit.",
      ["₦1,620", "₦1,920", "₦1,420", "₦2,120"], C,
      "Gross profit ₦2,120 − rent ₦200 − depreciation (10% × ₦5,000) ₦500 = ₦1,420."),
    q(TRD + "Find the average stock for the period.",
      ["₦27,000", "₦23,000", "₦28,000", "₦20,500"], D,
      "Average stock = (opening stock + closing stock) ÷ 2 = (₦32,000 + ₦9,000) ÷ 2 = ₦20,500."),
    q(TRD + "Calculate the cost of goods sold.",
      ["₦61,000", "₦58,000", "₦62,000", "₦57,000"], C,
      "Cost of goods available = ₦32,000 + ₦39,000 = ₦71,000; less closing stock ₦9,000 gives cost of goods sold of ₦62,000."),
    q("The costs that are directly traceable to the goods being produced is",
      ["partly manufactured goods", "overhead cost", "total factory expenses", "prime cost"], D,
      "Prime cost is the total of direct costs: direct materials, direct labour and direct expenses, all traceable to the goods produced."),
    q("The production cost that does not form part of the product but is incidental to production and facilitates the production activities is the",
      ["prime cost", "indirect cost", "total cost", "direct cost"], B,
      "Indirect costs (factory overheads) such as factory rent, power and supervisors' wages support production without being traceable to particular units."),
    q("Work-in-progress is the",
      ["value of partly finished goods", "value of finished goods on hand", "sales less cost of goods sold", "value of goods produced"], A,
      "Work-in-progress is goods that have started but not completed the production process, valued at the cost incurred so far."),
    q("The major feature of the not-for-profit-making organization is that they are formed",
      ["to use accumulated fund to describe the net amount owed to members", "mainly to improve the welfare of her members", "to engage in trading activities to sponsor its activities", "in order to compute the receipts and payments account"], B,
      "Clubs and societies exist mainly to provide services and improve the welfare of their members, not to make profit."),
    // paper 31–40
    q("The subscription paid in advance is treated in the balance sheet of a club as",
      ["a surplus", "a liability", "a deficit", "an asset"], B,
      "Subscriptions received in advance belong to a future year; the club owes members that service, so they are a current liability (in the statement of financial position, as the balance sheet is called today)."),
    q("The capital of a not-for-profit-making organization is referred to as",
      ["entity fund", "capital owned", "accumulated fund", "capital employed"], C,
      "In clubs and societies the excess of assets over liabilities is called the accumulated fund; it grows by any surplus of income over expenditure."),
    q("The major objective of departmental accounts is to ascertain the",
      ["contribution of each department to profit", "materials sold in each department", "insurance premium payable on employees", "number of employees in each department"], A,
      "Departmental accounts show the gross and net profit of each department, so management can see how much each contributes to the profit of the whole business."),
    q("The transactions relating to liquidation in partnership account is drawn by using",
      ["current account", "cash account", "capital account", "realization account"], D,
      "On dissolution, assets are transferred to a realisation account, which records their sale, the payment of liabilities and expenses, and the profit or loss on realisation.",
      { bookletKey: 'C', bookletNote: "The booklet answer C (capital account) only receives each partner's share of the result and is closed at the end. The dissolution transactions themselves (sale of assets, payment of liabilities and expenses) are recorded in the realisation account (D)." }),
    q("The cost method of charging goods to branch is used where",
      ["a branch stock adjustment account is in use", "the retention of branch trading account is in addition to the cost of goods sold", "goods are sent without invoice or any documents", "goods are of a perishable nature on which a pre-determined price is inapplicable"], D,
      "Goods are charged to a branch at cost when a fixed selling price cannot be set in advance, as with perishable goods whose prices change; the selling-price method needs fixed prices.",
      { bookletKey: 'A', bookletNote: "The booklet answer A goes with the other method: a branch stock adjustment account holds the mark-up when goods are invoiced to the branch at selling price. Charging at cost is used when a selling price cannot be fixed in advance, as with perishable goods (D)." }),
    q("The correct entries to record goods transferred to branch from head office is to debit",
      ["branch stock account and credit goods sent to branch account", "branch supplies account and credit branch stock account", "branch stock account and credit purchases account", "goods sent to branch account and credit branch stock account"], A,
      "Head office debits branch stock account (the branch now holds the goods) and credits goods sent to branches account."),
    q("The two accounts that are normally opened in the head office when goods are transferred to a branch are",
      ["branch supplies and branch receipts", "branch stock and goods sent to branch accounts", "goods sent to branch account and branch receipt account", "goods sent to branch account and branch supplies"], B,
      "The transfer is recorded in the branch stock account (debit) and the goods sent to branches account (credit)."),
    q("Goods invoiced to a branch can be sent using",
      ["cost price, selling price and fixed percentage on selling price", "cost price, selling price and fixed percentage on cost price", "cost price and fixed percentage on cost price", "cost price and fixed percentage on selling price"], B,
      "Goods may be invoiced to a branch at cost price, at selling price, or at cost plus a fixed percentage (mark-up on cost)."),
    q("The major point of agreement carried by the partnership deed is",
      ["5% interest per annum on any loan", "an oral agreement among the partners", "method of inheritance by the partners' children", "the profit and loss sharing ratio of the partners"], D,
      "The partnership deed is a written agreement whose most important term is the ratio in which partners share profits and losses; 5% interest on loans is the Partnership Act rule used when there is no deed."),
    q(PART + "The interest on Kemi's capital is",
      ["₦1,000", "₦2,000", "₦500", "₦3,000"], C,
      "Interest on capital = 5% × ₦10,000 = ₦500."),
    // paper 41–50
    q(PART + "The interest on Keme's drawings is calculated as",
      ["₦2,000", "₦150", "₦300", "₦100"], A,
      "Interest on drawings = 10% × ₦20,000 = ₦2,000."),
    q("Which of the following can be used on admission of a new partnership?",
      ["Revaluation account", "Profit and loss account", "Capital account", "Trading account"], A,
      "When a new partner is admitted, assets and liabilities are revalued through a revaluation account so the old partners get the gains or losses up to the date of admission."),
    q("Goodwill is determined using",
      ["capital contribution of old partners", "number of partners admitted", "the business and customer relations", "number of active partners"], C,
      "Goodwill is the value of a business's reputation and customer connections, the ability to earn more than normal profits; it rests on business and customer relations.",
      { bookletKey: 'B', bookletNote: "The booklet answer B (number of partners admitted) has nothing to do with the value of goodwill. Goodwill is the value of the business's reputation and customer connections, so it rests on the business and customer relations (C)." }),
    q("The founders of a company are",
      ["promoters", "shareholders", "canvassers", "stakeholders"], A,
      "Promoters are the people who conceive the idea of a company and take the steps to form and register it."),
    q("The fund in which all government receipts are paid is",
      ["consolidated revenue fund", "development fund", "trust fund", "contingency fund"], A,
      "All revenues and other money raised by government are paid into the Consolidated Revenue Fund, except those a law directs elsewhere."),
    q("Which of the following accounts for the highest revenue to Nigeria?",
      ["Import duties", "Personal income tax", "Petroleum income tax", "Company tax"], C,
      "Oil revenue, collected mainly as petroleum profits tax, was Nigeria's largest source of government revenue when the paper was set; non-oil taxes such as company income tax and VAT have grown a great deal since."),
    q("If Aboki Holdings Limited issued 120,000 ordinary shares of ₦2.00 each at a market value of ₦5.50 each, the share premium would be",
      ["₦500,000", "₦450,000", "₦550,000", "₦420,000"], D,
      "Share premium = (₦5.50 − ₦2.00) × 120,000 = ₦3.50 × 120,000 = ₦420,000."),
    q("Which of the following is a signatory to federal government account?",
      ["Auditor-General", "Governor of Central Bank", "Accountant-General", "President"], C,
      "The Accountant-General of the Federation controls and operates the federal government's accounts and is a signatory to them."),
    q("The chief accounting officer of a local government is the",
      ["Chairman", "Treasurer", "Director of personnel", "Auditor"], A,
      "Under the Financial Memoranda the Chairman is the chief executive and chief accounting officer of the local government; the Treasurer heads the finance department."),
    q("Which of the following signs general warrant for the release of money from the consolidated revenue fund?",
      ["Minister of Finance", "Chairman, Economic Advisory Committee", "Permanent secretary", "Minister of Economic Planning"], A,
      "After the Appropriation Act is passed, the Minister of Finance signs the general warrant authorising the Accountant-General to release money from the Consolidated Revenue Fund."),
  ]);
})();
