/**
 * JAMB/UTME 2005 — PRINCIPLES OF ACCOUNTS
 * From the 2005 question paper (questions 1–50); answers from the JAMB/UTME Accounts answer key 2001–2020,
 * each checked independently. Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2005;
  const SRC = 'JAMB UTME 2005';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const DEP = "Use the following information: \nA piece of equipment costing ₦120,000 was purchased on 1/1/1996. Depreciation was provided at 20% per annum on a straight-line basis. It was sold on 30/6/1999 for ₦31,500.\n\n";
  const MUSA = "Use the following information: \nMusa Merchants Trading and Profit and Loss Account for the year ended Dec. 31st 2003\nStock (1/1/2003) ... ₦60,000\nPurchases ... ₦90,000\nCost of goods available for sale ... ₦150,000\nStock (31/12/2003) ... ?\nCost of goods sold ... ?\nGross profit ... ₦180,000\nTotal ... ₦290,000\nSales ... ₦290,000\n\n";
  const STK = "Use the following information: \nDate ... Particulars ... Quantity (units) ... Unit price (₦)\nJan. ... Received ... 100 ... 2.00\nFeb. ... Received ... 110 ... 2.50\nMarch ... Issued ... 80\nApril ... Received ... 200 ... 3.00\nMay ... Issued ... 100\n\n";
  const SOLE = "Use the following information: \nA sole trader provided the following balances for the financial year ended 30th June, 2003.\nCapital ... ₦8,400\nNet profit ... ₦1,500\n(Subtotal ... ₦9,900)\nDrawings ... ₦900\n(Subtotal ... ₦9,000)\nCreditors ... ₦2,500\nAccruals ... ₦1,500\nTotal ... ₦13,000\nLand and Building ... ₦4,500\nFurniture ... ₦3,400\nStock ... ₦2,800\nDebtors ... ₦2,200\nCash ... ₦100\nTotal ... ₦13,000\n\n";
  const BS = "Use the following information: \nBalance Sheet (Extract)\nCapital ... ₦40,000\nNet profit ... ₦12,000\n(Subtotal ... ₦52,000)\nCreditors ... ₦8,000\nWages owed ... ₦4,000\nRent owed ... ₦3,000\nTotal ... ₦67,000\nBuilding ... ₦25,000\nEquipment ... ₦12,000\nStock ... ₦10,000\nDebtors ... ₦15,000\nCash ... ₦5,000\nTotal ... ₦67,000\n\n";
  const PART = "Use the following information: \nJide and Haruna contribute ₦12,000 each as capital and share profit equally. Jide draws ₦1,500 and Haruna ₦1,700 half-yearly. The profit for the year is ₦10,000. Jide receives a salary of ₦2,000.\n\n";
  const PETTY = "Use the following information: \nFive hundred naira monthly is allowed on an imprest system. The following transactions took place.\nPeriod 1:\nCash advanced to petty cashier ... ₦500\nPetty cashier paid out: Stamp ... ₦200\nNewspaper ... ₦250\nPeriod 2:\nCash to petty cashier ... ₦450\nCashier paid for writing materials ... ₦350\n\n";
  const CLUB = "Use the following information: \nSubscription ... ₦5,240\nCanopy rent ... ₦400\nWages ... ₦1,100\nPostages ... ₦300\nLoss from bar ... ₦160\nPurchase of new furniture ... ₦120\nPremises ... ₦4,000\nFurniture at the beginning ... ₦1,120\n\n";
  const MFG1 = "Use the following information: \nDirect labour ... ₦50,000\nBeginning work-in-progress ... ₦4,000\nRaw materials used ... ₦18,000\nIndirect labour ... ₦4,000\nEnding finished goods ... ₦16,000\nEnding work-in-progress ... ₦9,000\nFactory supply used ... ₦7,000\nSelling expenses ... ₦25,000\nBeginning finished goods ... ₦21,000\nOther factory overheads ... ₦19,000\n\n";
  const ZAZ = "Use the following information: \nZazzau Company\nCash in hand ... ₦50\nCash in bank ... ₦1,250\nStock ... ₦4,880\nBuilding ... ₦5,500\nDebtors ... ₦1,750\nCreditors ... ₦2,150\nFurniture ... ₦960\nDrawings of ₦125 were made by the shareholders of the company.\n\n";
  const MFG2 = "Use the following information: \nPurchases: Raw materials ... ₦15,000\nFinished goods ... ₦11,400\nStock (1/7/01): Raw materials ... ₦2,250\nWork-in-progress ... ₦1,875\nWages: Direct ... ₦17,100\nIndirect ... ₦5,400\nStock (30/06/02): Raw materials ... ₦3,000\nWork-in-progress ... ₦3,375\n\n";

  QUESTION_BANK.accounting = QUESTION_BANK.accounting.concat([
    // paper 1–10
    q("The items that are contained in the bought ledger control account are",
      ["dishonoured cheques, returns inwards and sales", "returns outwards, bad debts and purchases", "discount received, returns outwards and purchases", "discount allowed, bad debts and purchases"], C,
      "The bought (purchases) ledger control account summarises dealings with suppliers: credit purchases on the credit side, and payments, discount received and returns outwards on the debit side."),
    q("A rent received by a trader for sub-letting part of his business premises should be added to the",
      ["total revenue", "net profit", "total profit", "gross profit"], D,
      "Rent received is non-trading income, so it is added to gross profit in the profit and loss account before expenses are deducted to arrive at net profit."),
    q(DEP + "The accumulated depreciation provision at the time of sale was",
      ["₦72,000", "₦84,000", "₦60,000", "₦12,000"], B,
      "Annual depreciation = 20% × ₦120,000 = ₦24,000; from 1/1/1996 to 30/6/1999 is 3½ years, so ₦24,000 × 3.5 = ₦84,000."),
    q(DEP + "The net book value of the piece of equipment at the time of sale was",
      ["₦24,000", "₦96,000", "₦48,000", "₦36,000"], D,
      "Net book value = cost − accumulated depreciation = ₦120,000 − ₦84,000 = ₦36,000."),
    q("Use the following information: \nPurchases ledger balance ... ₦4,000\nPurchases for the period ... ₦50,000\nCash refunded by suppliers ... ₦290\nCheques paid to suppliers ... ₦42,300\nReturns outwards ... ₦2,000\nDiscount received from suppliers ... ₦400\n\nThe balance of the purchases ledger control account is",
      ["₦9,590", "₦9,010", "₦10,390", "₦9,990"], A,
      "Credit side: ₦4,000 + ₦50,000 + ₦290 refund = ₦54,290; debit side: ₦42,300 + ₦2,000 + ₦400 = ₦44,700; balance = ₦9,590 credit."),
    q(MUSA + "Determine the closing stock",
      ["₦50,000", "₦20,000", "₦30,000", "₦40,000"], D,
      "Cost of goods sold = sales − gross profit = ₦290,000 − ₦180,000 = ₦110,000, so closing stock = ₦150,000 − ₦110,000 = ₦40,000."),
    q("Use the following information: \n... Jan. 2003 ... Dec. 2003\nProvision for bad debt ... ₦1,000 ... –\nDebtors ... – ... ₦20,000\nBad debts to be written off ... – ... ₦2,000\n\nThe provision for bad debt stands at 10% of debtors. How much is to be charged to profit and loss account as provision for bad debt?",
      ["₦1,000", "₦1,800", "₦2,000", "₦800"], D,
      "The new provision is 10% of debtors after writing off bad debts: 10% × (₦20,000 − ₦2,000) = ₦1,800. Only the increase over the old ₦1,000 is charged: ₦800."),
    q(STK + "Determine the closing stock under LIFO method",
      ["₦375", "₦575", "₦275", "₦500"], B,
      "Under LIFO the March issue of 80 comes from February's ₦2.50 units and the May issue of 100 from April's ₦3.00 units, leaving 100 × ₦2 + 30 × ₦2.50 + 100 × ₦3 = ₦575."),
    q(STK + "Calculate the closing stock under FIFO method.",
      ["₦300", "₦600", "₦875", "₦675"], D,
      "Under FIFO the 180 units issued are the oldest (100 at ₦2 and 80 at ₦2.50), leaving 30 × ₦2.50 + 200 × ₦3 = ₦75 + ₦600 = ₦675."),
    q("Which of the following items is found on the credit side of the sales ledger control account?",
      ["dishonoured cheques", "credit sales", "bills receivable", "discount received"], C,
      "Bills receivable accepted by customers reduce what debtors owe, so they are credited to the sales ledger control account; dishonoured cheques and credit sales are debits, and discount received belongs to the purchases side."),
    // paper 11–20
    q(SOLE + "The capital employed is",
      ["₦9,900", "₦9,000", "₦8,400", "₦13,000"], B,
      "Capital employed (the owner's capital at the end of the year) = ₦8,400 + ₦1,500 − ₦900 = ₦9,000, which equals total assets ₦13,000 less current liabilities ₦4,000."),
    q("Goods withdrawn from business for private use is credited to",
      ["sales", "capital", "purchases", "drawings"], C,
      "Goods taken by the owner are recorded by debiting drawings and crediting purchases (at cost), because those goods will not be sold."),
    q("The head office of Emeka Stores maintains the financial accounts of all its branches. The branch stock account in the head office serves as the branch",
      ["trading account", "debtor's account", "cash account", "expenses account"], A,
      "When head office keeps the branch books, the branch stock account records goods sent, sales and closing stock, and its balancing figure is the branch gross profit, so it works as the branch trading account."),
    q(BS + "The quick ratio is",
      ["1.7:1", "3:1", "1:2", "1.3:1"], D,
      "Quick ratio = (current assets − stock) ÷ current liabilities = (₦15,000 + ₦5,000) ÷ (₦8,000 + ₦4,000 + ₦3,000) = ₦20,000 ÷ ₦15,000 ≈ 1.3:1."),
    q(BS + "The current ratio is",
      ["3.5:1", "1:1", "2:1", "2.8:1"], C,
      "Current ratio = current assets ÷ current liabilities = (₦10,000 + ₦15,000 + ₦5,000) ÷ ₦15,000 = ₦30,000 ÷ ₦15,000 = 2:1."),
    q("The tier of government that uses financial memorandum is the",
      ["local government", "federal government", "municipal government", "state government"], A,
      "In Nigeria the Financial Memoranda are the rules that govern the financial administration of local governments; the federal government uses the Financial Regulations and states use Financial Instructions."),
    q("The movement of goods from head office to a branch is treated in the head office accounts as",
      ["requisition", "purchases", "issue", "sale"], C,
      "Goods sent to a branch are not a sale (the business still owns them); head office records them as goods issued (sent) to the branch, debiting the branch and crediting goods sent to branch."),
    q("A company paid cash in redemption of ₦10,000 debentures. The accounting entry to record this will be to debit",
      ["debenture and credit cash", "capital and debit cash", "cash and credit debenture", "cash and credit capital"], A,
      "Redeeming (repaying) debentures reduces the liability and the cash: debit debentures account, credit cash."),
    q("Profit or loss in a partnership is usually arrived at after deducting from gross profit all expenses including",
      ["partners' drawings", "interest on loans", "interest on capital", "partners' salaries"], B,
      "Interest on loans (including a partner's loan) is a charge against profit in the profit and loss account; drawings, interest on capital and partners' salaries are dealt with in the appropriation and current accounts."),
    q("Earnings per share is a measure of",
      ["leverage", "liquidity", "profitability", "solvency"], C,
      "Earnings per share = profit after tax (and preference dividend) ÷ number of ordinary shares, so it measures profitability per share."),
    // paper 21–30
    q("In reconciling the branch and head office accounts, remittance in transit in the branch books is treated as a",
      ["contra entry", "debit entry", "reversal entry", "credit entry"], B,
      "When the branch sends cash to head office it debits the head office current account, so in the branch books a remittance in transit is a debit entry; the adjustment for it is made in the head office books.",
      { keyVerdict: 'corrected', keyAnswer: 'C', answerNote: "JAMB's key gives C (reversal entry), but nothing is reversed: the branch records a remittance by debiting the head office account, and in reconciling, head office adds the cash in transit on its side. B (debit entry) describes how the branch books show it." }),
    q("When assets are realized during a partnership dissolution, the entries for the proceeds are to debit",
      ["asset account and credit cash account", "realisation account and credit cash account", "asset account and credit realisation account", "cash account and credit realisation account"], D,
      "Cash received from selling the assets is debited to cash (or bank) and credited to the realisation account, where it is set against the book value of the assets transferred there."),
    q("The accounting method that reports incomes when earned and expenses when incurred is called",
      ["accrual accounting", "fund accounting", "cash accounting", "commitment accounting"], A,
      "Accrual accounting records income when it is earned and expenses when they are incurred, whether or not cash has been received or paid."),
    q(PART + "Calculate the profit available for appropriation",
      ["₦7,000", "₦12,000", "₦10,000", "₦8,000"], D,
      "Jide's salary of ₦2,000 is taken first, leaving ₦10,000 − ₦2,000 = ₦8,000 to be shared equally between the partners.",
      { keyVerdict: 'multiple', alsoAccept: [C], keyAnswer: 'D',
        answerNote: "Option C is also correct. A partner's salary is itself an appropriation of profit, so strictly the whole net profit of ₦10,000 is available for appropriation (C); ₦8,000 (D) is what remains to be shared in the profit-sharing ratio after the salary. Both readings are common, so both are accepted." }),
    q(PART + "The balances of current account of Jide and Haruna are respectively",
      ["₦4,000 and ₦4,000", "₦6,000 and ₦5,000", "₦3,000 and ₦600", "₦3,000 and ₦3,400"], C,
      "Each gets ₦4,000 profit share; Jide: ₦2,000 salary + ₦4,000 − drawings ₦3,000 = ₦3,000; Haruna: ₦4,000 − drawings ₦3,400 = ₦600."),
    q("The concept that has much influence over asset valuation and income determination is",
      ["matching", "conservatism", "entity", "realisation"], B,
      "Conservatism (prudence) says assets should not be overstated and profits should not be anticipated, so it shapes both how assets are valued and how income is measured."),
    q("Use the following information: \nRent ... ₦10,000\nRates ... ₦5,000\nCapital ... ₦50,000\nSalaries ... ₦14,000\nCash ... ₦26,000\nCreditors ... ₦5,000\n\nThe total trial balance is",
      ["₦55,000", "₦45,000", "₦65,000", "₦110,000"], A,
      "Debits: rent ₦10,000 + rates ₦5,000 + salaries ₦14,000 + cash ₦26,000 = ₦55,000; credits: capital ₦50,000 + creditors ₦5,000 = ₦55,000."),
    q("Yahya's bank account shows a credit balance of ₦1,500,000. He paid ₦1,700,000 into the bank. What is his expected balance?",
      ["debit balance of ₦3,200,000", "credit balance of ₦3,200,000", "credit balance of ₦200,000", "debit balance of ₦200,000"], B,
      "In the bank's records a credit balance is money the bank owes the customer, so a deposit adds to it: ₦1,500,000 + ₦1,700,000 = ₦3,200,000 credit."),
    q("The double entry principle of accounting was developed by",
      ["Luca Pacioli", "Frank Wood", "William Pickles", "Akintola Williams"], A,
      "Luca Pacioli, an Italian friar and mathematician, described double-entry bookkeeping in his book Summa (1494), and is called the father of accounting."),
    q("What are the appropriate recording procedures for entries in the trial balance?",
      ["cash account, ledgers and trial balance", "source documents, ledgers and trial balance", "ledgers, trial balance and source documents", "ledgers, source documents and trial balance"], B,
      "Transactions start on source documents, are posted (through the books of original entry) to the ledgers, and the ledger balances are then listed in the trial balance."),
    // paper 31–40
    q(PETTY + "How much should the petty cashier receive after period 2?",
      ["₦350", "₦500", "₦150", "₦250"], A,
      "Under the imprest system the petty cashier is reimbursed exactly what was spent; in period 2 ₦350 was spent, so ₦350 restores the ₦500 float."),
    q(PETTY + "What was the balance of cash with the petty cashier at the end of period 1?",
      ["₦200", "₦450", "₦50", "₦30"], C,
      "₦500 advanced − (₦200 stamps + ₦250 newspapers) = ₦500 − ₦450 = ₦50."),
    q("Use the following information: \nLiabilities ... ₦23,700\nCurrent assets ... ₦20,300\nFixed assets ... ₦64,500\n\nWhat is the capital introduced by the proprietor?",
      ["₦88,200", "₦40,800", "₦108,500", "₦61,100"], D,
      "Capital = assets − liabilities = (₦64,500 + ₦20,300) − ₦23,700 = ₦84,800 − ₦23,700 = ₦61,100."),
    q("Mr. Bassey purchased a motor vehicle for use in his business and debited the purchases account with the same value. This is an error of",
      ["principle", "omission", "original entry", "commission"], A,
      "A fixed asset (capital expenditure) was posted to purchases, a revenue account of a different class: that is an error of principle."),
    q("In a three-column cash book, the discount allowed is shown on the",
      ["credit side", "memorandum column", "debit side", "folio column"], C,
      "Discount allowed is given to customers when they pay, so it sits in the discount column on the debit (receipts) side of the cash book."),
    q("The journal entries for the purchase of stock on credit are to debit",
      ["suspense account and cash account", "purchase account and credit liability account", "stock account and credit cash account", "stock account and credit liability account"], B,
      "Goods bought for resale on credit are debited to purchases account and credited to the supplier (a liability, creditor) account."),
    q(CLUB + "What is the cash balance in the receipts and payments account?",
      ["₦4,120", "₦2,520", "₦2,600", "₦3,000"], A,
      "Receipts ₦5,240 + ₦400 = ₦5,640; cash payments ₦1,100 + ₦300 + ₦120 = ₦1,520; balance ₦4,120. The loss from bar is not a cash payment."),
    q(CLUB + "Determine the accumulated fund value.",
      ["₦6,320", "₦4,200", "₦3,000", "₦9,360"], D,
      "With no liabilities, the accumulated fund equals the club's assets at the end: cash ₦4,120 + premises ₦4,000 + furniture ₦1,120 + new furniture ₦120 = ₦9,360."),
    q("Gamji Memorial Club carried out an activity which yielded a profit of ₦10,000. This amount is to be transferred to the",
      ["credit side of its profit and loss account", "debit side of its profit and loss account", "credit side of its income and expenditure account", "debit side of its income and expenditure account"], C,
      "A club prepares an income and expenditure account, not a profit and loss account; a profit from an activity is income, so it goes on the credit side."),
    q(MFG1 + "What is the cost of goods manufactured?",
      ["₦97,000", "₦117,000", "₦93,000", "₦104,000"], C,
      "Prime cost ₦18,000 + ₦50,000 = ₦68,000; add factory overheads ₦4,000 + ₦7,000 + ₦19,000 = ₦30,000 and opening WIP ₦4,000, less closing WIP ₦9,000: ₦93,000."),
    // paper 41–50
    q(MFG1 + "Calculate the prime cost.",
      ["₦75,000", "₦70,000", "₦50,000", "₦68,000"], D,
      "Prime cost = direct materials + direct labour = ₦18,000 + ₦50,000 = ₦68,000."),
    q("If the assets and liabilities of a firm were valued at ₦17,200 and ₦5,120 respectively, the capital of the firm would be",
      ["₦5,120", "₦12,080", "₦17,200", "₦22,320"], B,
      "Capital = assets − liabilities = ₦17,200 − ₦5,120 = ₦12,080."),
    q("A company incurred ₦21,000 in running its four departments, namely J, K, L and M with a corresponding number of employees as 1500, 2000, 3000 and 500 respectively. What is the share of department K?",
      ["₦6,000", "₦1,500", "₦9,000", "₦4,500"], A,
      "Total employees = 7,000; K's share = 2,000/7,000 × ₦21,000 = ₦6,000."),
    q("The not-for-profit-making organisations generate their income mainly from",
      ["pools", "bar sales", "subscriptions", "rent"], C,
      "Clubs and societies get most of their income from members' subscriptions."),
    q(ZAZ + "The capital of the company stands at",
      ["₦2,510", "₦2,150", "₦12,115", "₦12,240"], D,
      "Capital = assets − liabilities = (₦50 + ₦1,250 + ₦4,880 + ₦5,500 + ₦1,750 + ₦960) − ₦2,150 = ₦14,390 − ₦2,150 = ₦12,240; the drawings already made are reflected in these balances."),
    q(ZAZ + "The company's net current assets amount to",
      ["₦5,870", "₦6,580", "₦7,930", "₦5,780"], D,
      "Current assets = ₦50 + ₦1,250 + ₦4,880 + ₦1,750 = ₦7,930; net current assets = ₦7,930 − creditors ₦2,150 = ₦5,780."),
    q("Departmental accounts are prepared to aid the comparison of the",
      ["daily profits", "previous year's transactions", "management performances", "workers performances"], D,
      "Departmental accounts show the results of each department separately, so the performance of the staff in each department can be compared and rewarded."),
    q("A component of an overhead manufacturing cost is",
      ["labour", "rent", "cost of work-in-progress", "cost of finished goods"], B,
      "Factory rent is an indirect cost of production, so it is part of factory (manufacturing) overheads; work-in-progress and finished goods are stocks, not overheads."),
    q(MFG2 + "What is the cost of manufactured goods?",
      ["₦48,750", "₦49,125", "₦35,250", "₦37,625"], C,
      "Materials used ₦14,250 + direct wages ₦17,100 = prime cost ₦31,350; + indirect wages ₦5,400 + opening WIP ₦1,875 − closing WIP ₦3,375 = ₦35,250."),
    q(MFG2 + "The cost of raw materials consumed is",
      ["₦15,000", "₦14,250", "₦15,750", "₦17,250"], B,
      "Raw materials consumed = opening stock ₦2,250 + purchases ₦15,000 − closing stock ₦3,000 = ₦14,250."),
  ]);
})();
