/**
 * JAMB/UTME 2001 — PRINCIPLES OF ACCOUNTS
 * From the 2001 question paper (questions 1–50); answers from the JAMB/UTME Accounts answer key 2001–2020,
 * each checked independently. Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2001;
  const SRC = 'JAMB UTME 2001';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const D56 = "Use the following information: \nFixed assets ... ₦85,600\nSales ... ₦197,000\nStock ... ₦34,300\nSalaries and wages ... ₦37,000\nPurchases ... ₦127,700\nShare capital ... ₦120,000\nCreditors ... ₦16,050\nMotor expenses ... ₦10,500\nDebtors ... ₦25,000\n\n";
  const D1415 = "Use the following information: \nPalaju Enterprises had fixed assets of ₦3,100,000 at the end of the year. Fixed assets costing ₦900,000 with provision for depreciation of ₦150,000 were disposed of during the period. Fixed assets of ₦100,000 were added during the year. Provision for depreciation was ₦350,000 at the beginning of the year and ₦300,000 at the end of the year.\n\n";
  const D1718 = "Use the following information: \nStock Control Account [Extract] as at January, 2000\nJan. 1 ... Receipts 100 units @ ₦5.00 = ₦500.00 ... Balance ₦500.00\nJan. 5 ... Receipts 50 units @ ₦6.00 = ₦300.00 ... Balance ₦800.00\nJan. 7 ... Issues 40 units @ ₦6.00 = ₦240.00 ... Balance ₦560.00\nJan. 10 ... Receipts 50 units @ ₦4.00 = ₦200.00 ... Balance ₦760.00\nJan. 15 ... Issues 50 units @ ₦4.00 = ₦200.00 ... Balance ₦560.00\nJan. 20 ... Issues 10 units @ X = Y ... Balance Z\n\n";
  const D1920 = "Use the following information: \nPurchases ledger opening balances ... ₦4,000\nSales ledger opening balance ... ₦6,000\nCredit purchases during the year ... ₦25,000\nDiscounts allowed ... ₦1,000\nReturns inwards ... ₦2,000\nCredit sales during the year ... ₦10,000\nReturns outwards ... ₦6,000\n\n";
  const D2223 = "Use the following information: \n(31/12/98 ... 31/12/99)\nAssets:\nPlant & Machinery ... ₦1,500 ... ₦1,200\nFixtures ... ₦700 ... ₦520\nStock ... ₦500 ... ₦600\nDebtors ... ₦900 ... ₦400\nCash ... ₦200 ... ₦300\nLiabilities:\nCreditors ... ₦500 ... ₦600\nLoan ... ₦600 ... ₦400\n\n";
  const D2526 = "Use the following information: \nBar opening stock ... ₦10,000\nAmount owed to bar suppliers at the beginning of the year ... ₦10,000\nBar sales ... ₦50,000\nBar credit purchases ... ₦40,000\nPayment to suppliers ... ₦30,000\nBar expenses ... ₦1,000\nBar closing stock ... ₦15,000\n\n";
  const D2829 = "Use the following information: \nSubscriptions received during the year ... ₦30,000\nSubscription owed last year ... ₦4,000\nSubscription received for next year ... ₦6,000\n\n";
  const D4142 = "Use the following information: \nAuthorized capital:\n100,000 ordinary shares of ₦1 each\nIssued and fully paid:\n50,000 ordinary shares of ₦1 each ... ₦50,000\n10,000 8% preference shares of ₦1 each ... ₦10,000\nReserves ... ₦25,000\nCreditors ... ₦15,000\nDebtors ... ₦13,000\nCash in hand ... ₦5,000\n\n";
  const D4950 = "Use the following information: \nPTF Trial Balance [Extract] as at 31 December 1999 (Dr / Cr, ₦'000)\nCash ... Dr 2,000\nInvestments ... Dr 3,000\nAccounts receivable ... Dr 6,000\nFund balance ... Cr 11,000\nTotals ... 11,000 ... 11,000\n\n";

  QUESTION_BANK.accounting = QUESTION_BANK.accounting.concat([
    // paper 1–10
    q("The current growth in the volume of trading and financial dealings in Nigeria is helped by",
      ["increased financial activities", "government intervention", "credit as a factor in business", "paying for goods in cash"], C,
      "Trade grows when buyers can take goods now and pay later; credit lets businesses deal in far larger volumes than cash alone allows, and it is credit dealings that make careful record-keeping necessary.",
      { keyVerdict: 'corrected', keyAnswer: 'A',
        answerNote: "JAMB's answer is A, but \"increased financial activities\" only repeats the question (growth in financial dealings). The factor that drives the growth is the use of credit in business, option C." }),
    q("Cost accounting entails provision of information",
      ["for investment purpose", "for decision making", "to shareholders", "to stockholders"], B,
      "Cost accounting records and analyses costs so that management can plan, control and make decisions such as pricing and choosing between products."),
    q("The main objective of accounting report is to provide information about",
      ["a company's shareholding", "an entity's management", "the efficacy of assets", "a company's economic resources"], D,
      "Financial reports exist to tell users about an entity's economic resources, the claims against them and how they have changed, so that users can make economic decisions.",
      { keyVerdict: 'corrected', keyAnswer: 'B',
        answerNote: "JAMB's answer is B. Reports do help users judge how well management has looked after the resources (stewardship), but what they report on is the entity's economic resources, claims and performance, so D is the better answer." }),
    q("If liabilities amounted to ₦12,045, other assets ₦36,800 and equity ₦26,896, the cash at hand would be",
      ["₦2,241", "₦2,214", "₦2,141", "₦2,114"], C,
      "Total assets = liabilities + equity = ₦12,045 + ₦26,896 = ₦38,941; cash = ₦38,941 − ₦36,800 = ₦2,141."),
    q(D56 + "What is the cash balance?",
      ["₦12,095", "₦12,590", "₦12,950", "₦21,800"], C,
      "Credits total ₦333,050 (sales, share capital, creditors); debits other than cash total ₦320,100, so cash (a debit) must be ₦333,050 − ₦320,100 = ₦12,950."),
    q(D56 + "Determine the total of the trial balance.",
      ["₦335,050", "₦333,050", "₦323,050", "₦230,550"], B,
      "The credit side is complete: sales ₦197,000 + share capital ₦120,000 + creditors ₦16,050 = ₦333,050, and the debit side (with cash) must equal it."),
    q("The accuracy of journalizing is checked by",
      ["ensuring that debit totals equal credit totals", "posting all journal entries to ledger accounts", "adding all figures in the debit column", "comparing accounts in the ledger against the journals"], A,
      "Every journal entry must have equal debits and credits, so the journal is proved by checking that its debit total equals its credit total.",
      { keyVerdict: 'corrected', keyAnswer: 'D',
        answerNote: "JAMB's answer is D, but comparing ledger accounts with the journal checks the posting, not the journalizing. The journal itself is checked by making sure its debit and credit totals agree, option A." }),
    q("Hauwa Ltd bought 10 bags of rice for ₦500 each. The company was given 5% and 12% trade and cash discounts respectively. What will be recorded as discount received in the company's book?",
      ["₦250", "₦570", "₦600", "₦850"], B,
      "Trade discount is never entered in the books: ₦5,000 − 5% (₦250) = ₦4,750; the cash discount received is 12% × ₦4,750 = ₦570."),
    q("A cash book had opening balance of ₦15,200, closing balance ₦18,400 and total cash received during the period ₦36,000. What was the amount of cash paid out during the same period?",
      ["₦17,800", "₦19,600", "₦29,200", "₦32,800"], D,
      "Opening ₦15,200 + receipts ₦36,000 = ₦51,200 available; payments = ₦51,200 − closing ₦18,400 = ₦32,800."),
    q("In a petty cash book, the closing balance was ₦235, imprest ₦1,250, while the stationery expenses were ₦655. How much was paid for other general expenses?",
      ["₦360", "₦355", "₦350", "₦305"], A,
      "Total spent = imprest ₦1,250 − closing balance ₦235 = ₦1,015; other expenses = ₦1,015 − ₦655 = ₦360."),
    // paper 11–20
    q("When a bill is negotiated to a bank, it is said to be",
      ["surrendered", "cashed", "discounted", "accepted"], C,
      "A holder who sells a bill to a bank before it matures receives its value less a charge (discount), so the bill is said to be discounted."),
    q("Given that the balance as per cash book after necessary adjustments was ₦4,315, unpresented cheques were ₦1,688 and the bank statement balance was ₦4,791, what was the balance of the uncredited cheques?",
      ["₦1,223", "₦1,212", "₦1,202", "₦1,115"], B,
      "Bank statement = cash book + unpresented cheques − uncredited cheques, so ₦4,791 = ₦4,315 + ₦1,688 − x, giving x = ₦6,003 − ₦4,791 = ₦1,212."),
    q("If a property developing company sells a completed building to an interested third party, this sale can be treated in the books of the company as",
      ["capital receipt", "revenue receipt", "windfall receipt", "miscellaneous receipt"], B,
      "Building and selling property is the company's normal trade, so the building is its stock-in-trade and the sale proceeds are a revenue receipt."),
    q(D1415 + "What was the value of fixed assets at the beginning of the year?",
      ["₦2,900,000", "₦3,800,000", "₦3,900,000", "₦4,000,000"], C,
      "Opening + additions − disposals = closing, so opening = ₦3,100,000 + ₦900,000 − ₦100,000 = ₦3,900,000."),
    q(D1415 + "The depreciation expense charged for the year is",
      ["₦450,000", "₦250,000", "₦150,000", "₦100,000"], D,
      "Provision: opening ₦350,000 − ₦150,000 removed on disposal = ₦200,000; to close at ₦300,000 the year's charge must be ₦100,000."),
    q("A reduction in the catalogue price of an article given by a wholesaler to a retailer is called a",
      ["bad debt", "trade discount", "premium", "cash discount"], B,
      "Trade discount is a reduction off the list (catalogue) price given to traders in the same line of business; it is not recorded in the books."),
    q(D1718 + "What is the stock valuation method used?",
      ["Last In First Out", "First In First Out", "Average cost", "Weighted average"], A,
      "Each issue is priced at the most recent purchase price (Jan. 7 at ₦6.00 after the Jan. 5 receipt; Jan. 15 at ₦4.00 after the Jan. 10 receipt), which is Last In First Out."),
    q(D1718 + "The value of X is",
      ["₦4.00", "₦5.00", "₦5.50", "₦6.00"], D,
      "After Jan. 15 the stock left is 100 units at ₦5.00 and 10 units at ₦6.00; under LIFO the latest of these, the ₦6.00 units, are issued on Jan. 20, so X = ₦6.00."),
    q(D1920 + "Calculate the sales ledger balance.",
      ["₦3,000", "₦6,000", "₦10,000", "₦13,000"], D,
      "Sales ledger control: opening ₦6,000 + credit sales ₦10,000 − discounts allowed ₦1,000 − returns inwards ₦2,000 = ₦13,000."),
    q(D1920 + "What is the purchases ledger balance?",
      ["₦4,000", "₦23,000", "₦24,000", "₦29,000"], B,
      "Purchases ledger control: opening ₦4,000 + credit purchases ₦25,000 − returns outwards ₦6,000 = ₦23,000."),
    // paper 21–30
    q("For an incomplete record to provide necessary information, it must be converted to",
      ["complete records", "double entry records", "statement of affairs", "single entry"], B,
      "Single-entry (incomplete) records are converted to double entry so that full final accounts (trading, profit and loss and balance sheet) can be prepared."),
    q(D2223 + "Determine the total fixed asset from the opening balance sheet.",
      ["₦2,200", "₦2,020", "₦1,720", "₦1,270"], A,
      "The opening balance sheet is at 31/12/98: plant and machinery ₦1,500 + fixtures ₦700 = ₦2,200."),
    q(D2223 + "What is the capital from the opening balance sheet?",
      ["₦3,600", "₦2,700", "₦2,070", "₦1,520"], B,
      "Assets at 31/12/98 = ₦1,500 + ₦700 + ₦500 + ₦900 + ₦200 = ₦3,800; liabilities = ₦500 + ₦600 = ₦1,100; capital = ₦2,700."),
    q("Given:\nDirect material ... ₦2,500\nDirect labour ... ₦5,000\nDirect expenses ... ₦1,000\nOverhead expenses ... ₦1,500\n\nFrom the data above, compute the prime cost.",
      ["₦8,500", "₦7,500", "₦6,500", "₦6,000"], A,
      "Prime cost is the total of all direct costs: ₦2,500 + ₦5,000 + ₦1,000 = ₦8,500; overheads are added later to reach production cost."),
    q(D2526 + "What is the bar profit?",
      ["₦20,000", "₦15,000", "₦14,000", "₦10,000"], C,
      "Cost of sales = ₦10,000 + ₦40,000 − ₦15,000 = ₦35,000; gross bar profit = ₦50,000 − ₦35,000 = ₦15,000; less bar expenses ₦1,000 = ₦14,000.",
      { keyVerdict: 'corrected', keyAnswer: 'B',
        answerNote: "JAMB's answer is B (₦15,000), which is only the gross profit. A bar trading account also charges the bar's own expenses, so the bar profit transferred to the income and expenditure account is ₦15,000 − ₦1,000 = ₦14,000." }),
    q(D2526 + "How much is owed to suppliers?",
      ["₦50,000", "₦40,000", "₦30,000", "₦20,000"], D,
      "Owed at start ₦10,000 + credit purchases ₦40,000 − payments ₦30,000 = ₦20,000 still owed at the end."),
    q("Lubricating oil and spare parts of machinery are examples of",
      ["direct material", "indirect materials", "indirect expenses", "direct expenses"], B,
      "Lubricants and spare parts are materials used in the factory that cannot be traced to particular units of output, so they are indirect materials (part of factory overheads)."),
    q(D2829 + "The ₦6,000 subscription received is",
      ["current asset", "current liability", "fixed asset", "capital"], B,
      "Subscriptions received in advance for next year are owed to members as a service still to be given, so they are a current liability."),
    q(D2829 + "What is the subscription to be charged to income and expenditure account?",
      ["₦36,000", "₦34,000", "₦30,000", "₦20,000"], D,
      "Cash received ₦30,000 − arrears for last year ₦4,000 − advance for next year ₦6,000 = ₦20,000 belonging to this year."),
    q("A club received rent ₦10,000 and donation ₦30,000. It paid ₦6,000 for entertainment and is still owing ₦16,000. The balance of the receipts and payment account is",
      ["₦24,000", "₦22,000", "₦14,000", "₦18,000"], D,
      "JAMB's answer deducts both the ₦6,000 paid and the ₦16,000 owed from receipts of ₦40,000, giving ₦18,000.",
      { keyVerdict: 'none', keyAnswer: 'D',
        answerNote: "A receipts and payments account records only cash actually received and paid, so the amount still owing is left out and the balance is ₦40,000 − ₦6,000 = ₦34,000, which is not among the options. JAMB's ₦18,000 treats the ₦16,000 owed as if it had been paid." }),
    // paper 31–40
    q("Given:\nClub trading profit ... ₦12,000\nMembers' subscription ... ₦15,000\nProfit on sale of fixed assets ... ₦2,500\nLoss on sale of investment ... ₦1,000\nWages ... ₦16,000\nOther expenses ... ₦10,000\n\nDetermine the club's excess of income over expenditure.",
      ["₦500", "₦1,500", "₦2,000", "₦2,500"], D,
      "Income = ₦12,000 + ₦15,000 + ₦2,500 = ₦29,500; expenditure = ₦1,000 + ₦16,000 + ₦10,000 = ₦27,000; excess = ₦2,500."),
    q("The excess of income over expenditure is usually transferred to the",
      ["accumulated fund", "profit and loss account", "current assets in the balance sheet", "current liabilities in the balance sheet"], A,
      "A club's surplus is added to its accumulated fund, the non-profit body's equivalent of capital."),
    q("Partner's salaries and drawings are usually posted to the",
      ["trading account", "current account", "capital account", "partners' account"], B,
      "Where capital accounts are kept fixed, partners' salaries, interest and profit shares are credited, and drawings debited, to their current accounts."),
    q("Marmuhu and Yusuf are in partnership sharing profits and losses in the ratio 2 : 1. On 31/3/2000, the partnership decided to admit Idris who is to take ¼ of future profits without changing the ratio of Marmuhu and Yusuf. What is the new profit-sharing ratio of Marmuhu and Yusuf?",
      ["50% : 25%", "50% : 20%", "25% : 50%", "25% : 25%"], A,
      "The old partners share the remaining ¾ in 2 : 1: Marmuhu ⅔ × ¾ = ½ (50%) and Yusuf ⅓ × ¾ = ¼ (25%)."),
    q("If a partner pays a premium of ₦500 for 1/5 share of profit, then the total value of goodwill is",
      ["₦500", "₦2,000", "₦2,500", "₦3,000"], C,
      "The premium pays for the incoming partner's share of goodwill: ₦500 ÷ 1/5 = ₦2,500 for the whole business."),
    q("On the dissolution of a partnership business, the net book value of the assets is transferred to",
      ["debit of realization account", "credit of realization account", "debit of bank account", "credit of bank account"], A,
      "On dissolution the assets are closed off by crediting the asset accounts and debiting the realisation account with their book values."),
    q("Bala Ltd acquired the business of Bello Ltd and caused the separate existence of the latter company to terminate. This situation is best described as",
      ["absorption", "merger", "conversion", "dissolution"], A,
      "When an existing company takes over another and the acquired company ceases to exist, the combination is an absorption."),
    q("Where a company acquires controlling shares of another and the consideration is paid in cash, the entries in the books of the purchasers are debit",
      ["investment and credit cash", "investment and credit shares", "purchases and credit cash", "purchases and credit shares"], A,
      "The shares bought are an asset of the buying company, so it debits Investment (in subsidiary) and, having paid cash, credits Cash.",
      { keyVerdict: 'corrected', keyAnswer: 'C',
        answerNote: "JAMB's answer is C. Buying a controlling shareholding is an investment, not a purchase of goods, so the buyer debits Investment account and credits Cash, option A. (Some older texts use a \"purchase of business\" account, but that is for buying a business's assets, not its shares.)" }),
    q("Given:\nCapital ... ₦200,000\nLiabilities ... ₦10,000\nTotal ... ₦210,000\nTotal assets ... ₦210,000\n\nIf the business is purchased at a price including a goodwill of ₦20,000, what must have been the purchase price?",
      ["₦190,000", "₦210,000", "₦220,000", "₦230,000"], C,
      "Net assets = ₦210,000 − ₦10,000 = ₦200,000; purchase price = net assets + goodwill = ₦200,000 + ₦20,000 = ₦220,000."),
    q("The main difference between the ordinary and preference shareholders is that",
      ["the former receive dividends while the latter do not", "the latter are not members of the company while the former are", "in the case of winding up, the former are paid first before the latter", "the former have voting rights while the latter do not"], D,
      "Ordinary shareholders own and control the company and vote at meetings; preference shareholders get a fixed dividend and prior repayment but normally have no vote."),
    // paper 41–50
    q(D4142 + "Determine the net current assets.",
      ["₦43,000", "₦28,000", "₦13,000", "₦3,000"], D,
      "Current assets = debtors ₦13,000 + cash ₦5,000 = ₦18,000; less creditors ₦15,000 = ₦3,000."),
    q(D4142 + "Calculate the shareholder's fund.",
      ["₦60,000", "₦75,000", "₦85,000", "₦185,000"], C,
      "Shareholders' funds = issued share capital (ordinary ₦50,000 + preference ₦10,000) + reserves ₦25,000 = ₦85,000.",
      { keyVerdict: 'corrected', keyAnswer: 'B',
        answerNote: "JAMB's answer is B (₦75,000), which is the ordinary (equity) shareholders' fund only. The question asks for the shareholders' fund, which also includes the ₦10,000 preference share capital: ₦85,000." }),
    q("The law that currently regulates the registration of companies in Nigeria is the",
      ["Constitution of the Federal Republic of Nigeria, 1999", "Nigerian Enterprises Promotion Decree, 1972", "Companies and Allied Matters Decree, 1990", "Companies Decree, 1968"], C,
      "In 2001 company registration was governed by the Companies and Allied Matters Decree (Act) 1990, administered by the Corporate Affairs Commission; today it is the Companies and Allied Matters Act 2020."),
    q("X and Y are two departments that are to share 50% of all joint costs equally and the balance in the ratio 2 : 1. If a sum of ₦150,000 is incurred jointly, what will be the portion attributable to X?",
      ["₦37,500", "₦62,500", "₦87,500", "₦75,000"], C,
      "Half (₦75,000) is shared equally, so X gets ₦37,500; the other ₦75,000 is shared 2 : 1, so X gets ₦50,000; X's total is ₦87,500."),
    q("Department F transferred some goods to department G at a selling price. The goods were not sold at the end of the accounting period. Which account is affected at the time of preparing a combined balance sheet?",
      ["Creditors", "Debtors", "Stock", "Suspense"], C,
      "The unsold goods sit in G's stock at F's selling price, so the unrealised profit must be removed from stock in the combined balance sheet."),
    q("The correct entry to reflect the receipt of cash sent by a branch to a head office is",
      ["debit cash and credit branch current account", "debit branch current account and credit cash", "credit branch debtors and debit cash", "credit branch current account and debit branch debtors"], A,
      "In head office books, cash coming in is debited to Cash and the branch, which now owes less, is credited in the branch current account."),
    q("To account for expenses paid by head office on behalf of the branch, the branch should",
      ["debit head office account and credit cash", "debit profit and loss account and credit head office account", "credit cash and debit profit and loss account", "credit profit and loss account and debit head office account"], B,
      "The branch bears the expense (debit profit and loss/expense) but did not pay cash; it owes head office, so it credits the head office account."),
    q("The officer responsible for ascertaining whether all public expenditure and appropriation are in line with approved guidelines is the",
      ["Accountant General", "Auditor General", "Finance Minister", "Permanent Secretary"], B,
      "The Auditor-General audits public accounts and reports to the legislature on whether money was spent as appropriated and according to the rules."),
    q(D4950 + "Assuming all the investments realized is ₦4m, what will be the ending fund balance?",
      ["₦8m", "₦11m", "₦12m", "₦16m"], C,
      "Investments of ₦3m sold for ₦4m give a gain of ₦1m, which is added to the fund: ₦11m + ₦1m = ₦12m."),
    q(D4950 + "If only 1/3 of the investment is sold for ₦2m and ₦5m realized from the accounts receivable, what will be the balance of the fund?",
      ["₦9m", "₦11m", "₦13m", "₦16m"], B,
      "One-third of the investments (₦1m) sold for ₦2m gives a ₦1m gain; receivables of ₦6m yield only ₦5m, a ₦1m loss; fund = ₦11m + ₦1m − ₦1m = ₦11m.")
  ]);
})();
