/**
 * JAMB/UTME 2012 — PRINCIPLES OF ACCOUNTS
 * From the 2012 question paper (questions 2–50; Q1 asked only for the question paper type);
 * answers from the JAMB/UTME Accounts answer key 2001–2020, each checked independently.
 * Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2012;
  const SRC = 'JAMB UTME 2012';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const SUGAR = "Use the following information: \nIbrahim, a microbusiness operator, sold 10 bags of sugar to Jide at a total cost of ₦12,000.\n\n";
  const TRAD = "Use the following information: \nStock 1/1 ... ₦20,000\nAdd purchases ... ₦250,000\nCost of goods available for sale ... ₦270,000\nLess stock 31/12 ... ₦40,000\nRent expenses ... ₦35,000\nNet sales ... ₦370,000\nCost of goods sold ... ₦230,000\n\n";
  const ADJ = "Use the following information: \nAt the end of a financial period, the trading, profit and loss account of a sole trader shows a profit of ₦180,000. It is however discovered that revenue of ₦15,000 was recorded as expenses while expenses of ₦4,000 were recorded as revenue.\n\n";
  const MILK = "Use the following information: \n1/5/07 Purchased 100 bags of milk at ₦10.00 each\n3/5/07 Purchased 60 bags of milk at ₦11.50 each\n8/5/07 Issued 85 bags of milk\n15/5/07 Purchased 180 bags of milk at ₦12.80 each\n22/5/07 Issued 145 bags of milk\n\n";
  const MFG = "Use the following information: \nTotal production cost ... ₦360,000\nFactory overhead cost ... ₦56,000\nSelling price per unit ... ₦120\nProduction volume ... 4,000 units\n\n";
  const PART = "Use the following information: \nThe partners' capitals are: Modibbo ₦60,000 and Jakata ₦90,000. The partners share profits and losses in the ratio of their capital contributions. The net profit for the year is ₦120,000.\n\n";
  const RAT = "Use the following information: \nPurchases ... ₦44,880\nSales ... ₦85,850\nTrade creditors ... ₦12,250\nTrade debtors ... ₦24,000\nAccrued expenses ... ₦350\nPrepaid expenses ... ₦700\nStock 1/1/2006 ... ₦25,120\nStock 31/12/2006 ... ₦27,840\n\n";

  QUESTION_BANK.accounting = QUESTION_BANK.accounting.concat([
    // paper 2–11
    q("The basis upon which assets of an organization are valued is the",
      ["historical cost concept", "business entity concept", "periodicity concept", "materiality concept"], A,
      "Under the historical cost concept, assets are recorded and valued at what they cost when acquired."),
    q("An accountant must not only be interested in record keeping but also in",
      ["the application of professional competency", "the accuracy of postings", "the casting of financial figures", "effective preparation of balance sheet"], A,
      "Beyond keeping records, an accountant must apply professional competence and judgement; accurate posting, casting and preparing statements are all part of record keeping itself."),
    q("The correct posting in the double entry system of account when there is an increase in assets, expenses, capital or liabilities is to debit",
      ["capital and credit liabilities", "liabilities and credit assets", "assets and credit capital", "capital and credit assets"], C,
      "Increases in assets and expenses are debited; increases in capital and liabilities are credited, so the entry is debit assets and credit capital."),
    q("The capital of a sole trader can be increased by",
      ["debiting the capital account", "crediting the capital account", "debiting the cash account", "crediting the cash account"], B,
      "Capital is a credit balance, so it increases when the capital account is credited (for example with new capital introduced or net profit).",
      { bookletKey: 'C', bookletNote: "The booklet answer C (debiting the cash account) only describes the other half of a cash entry, and debiting cash also happens for cash sales or loans, which do not increase capital. Capital is a credit balance, so it is increased by crediting the capital account (B)." }),
    q("Akirika bought a motor van for his business by cash. The entries are to debit",
      ["motor van and credit Akirika", "sales and credit Akirika", "motor van and credit cash", "cash and credit motor van"], C,
      "The van (an asset) comes in, so motor van account is debited; cash goes out, so cash account is credited."),
    q(SUGAR + "In the books of Ibrahim, the entry to record the transaction would be to debit",
      ["sugar account ₦12,000 and credit Jide ₦12,000", "Jide ₦12,000 and credit sales account ₦12,000", "Ibrahim ₦12,000 and credit Jide ₦12,000", "sugar account ₦12,000 and credit Ibrahim ₦12,000"], B,
      "For the seller, Jide becomes a debtor (debit Jide) and the goods sold are credited to sales account."),
    q(SUGAR + "The record in Jide's books would be to debit",
      ["purchases ₦12,000 and credit Ibrahim ₦12,000", "purchases ₦12,000 and credit sugar account ₦12,000", "Jide ₦12,000 and credit purchases ₦12,000", "Ibrahim ₦12,000 and credit sugar account ₦12,000"], A,
      "For the buyer, the goods are debited to purchases account and Ibrahim, the supplier (creditor), is credited."),
    q("Given the following Cash Book: \nDebit side: Capital ... ₦2,600\nSales ... ₦18,200\nCredit side: Purchases ... ₦5,000\nRent ... ₦1,250\nMotor vehicle ... ₦7,600\n\nDetermine the bank balance.",
      ["₦6,950 credit", "₦6,950 debit", "₦6,000 credit", "₦6,000 debit"], B,
      "Receipts ₦20,800 exceed payments ₦13,850 by ₦6,950, so the balance is ₦6,950 debit (money in the bank)."),
    q("In a three-column cash book, dishonoured cheques will be shown on the",
      ["bank column (debit)", "bank column (credit)", "cash column (debit)", "cash column (credit)"], B,
      "A dishonoured cheque reduces the money in the bank, so it is entered on the credit side in the bank column."),
    q("Use the following information: \nDate ... Particulars ... Folio ... Details ... Total\n1/6/02 ... 2 bags of maize ... SL ... ₦1,800 ... ₦1,800\n12/6/02 ... 3 bags of salt less 5% discount ... ₦7,000 ... ₦7,000\nTotal ... ₦8,800\n\nThe 5% discount shown above indicates",
      ["trade discount", "cash discount", "discount allowed", "discount received"], A,
      "A discount deducted on the invoice in the sales day book is a trade discount; cash discount is given only for prompt payment and is recorded in the cash book."),
    // paper 12–21
    q("Cash can be drawn from the bank using all the following except",
      ["withdrawal slip", "debit card", "a recharge card", "ATM card"], C,
      "A recharge card buys phone airtime; it cannot be used to withdraw cash from a bank account."),
    q("In a modern day banking system, cash transfer cannot be made where the transferor",
      ["has no sufficient cash with the bank", "has no account with the bank", "does not reside in the bank's country", "does not possess the domestic currency"], A,
      "A bank transfer moves money out of the transferor's account, so it cannot be made when there are insufficient funds in it."),
    q("Use the following information: \nCash book balance ... ₦5,000\nDishonoured cheque ... ₦1,000\nDirect credit ... ₦800\nDirect debit ... ₦500\n\nThe adjusted cash book balance is",
      ["₦6,300", "₦4,300", "₦3,700", "₦2,700"], B,
      "₦5,000 − ₦1,000 (dishonoured cheque) + ₦800 (direct credit) − ₦500 (direct debit) = ₦4,300."),
    q(TRAD + "Find the gross profit.",
      ["₦370,000", "₦230,000", "₦150,000", "₦140,000"], D,
      "Gross profit = net sales − cost of goods sold = ₦370,000 − ₦230,000 = ₦140,000."),
    q(TRAD + "Calculate the net profit.",
      ["₦35,000", "₦40,000", "₦105,000", "₦115,000"], C,
      "Net profit = gross profit ₦140,000 − rent expenses ₦35,000 = ₦105,000."),
    q(ADJ + "Determine the adjusted net profit.",
      ["₦210,000", "₦202,000", "₦195,000", "₦184,000"], B,
      "Profit was understated by 2 × ₦15,000 = ₦30,000 and overstated by 2 × ₦4,000 = ₦8,000: ₦180,000 + ₦30,000 − ₦8,000 = ₦202,000."),
    q(ADJ + "The revenue to be added as an adjustment is",
      ["₦34,000", "₦30,000", "₦15,000", "₦4,000"], B,
      "Moving the ₦15,000 out of expenses and into revenue raises profit by ₦15,000 + ₦15,000 = ₦30,000."),
    q("Which of the following is an item of special assets?",
      ["Fixed assets", "Current assets", "Trademark", "Gratuity"], C,
      "A trademark is a special (intangible) asset: it has value to the business but no physical form."),
    q(MILK + "Using FIFO method, what would be the value of stock as at 9/5/07?",
      ["₦862.50", "₦840.00", "₦806.25", "₦750.00"], B,
      "FIFO issues the oldest stock first: the 85 bags come from the ₦10.00 lot, leaving 15 × ₦10.00 + 60 × ₦11.50 = ₦840.00.",
      { bookletKey: 'D', bookletNote: "The booklet answer ₦750.00 (D) is the LIFO value: issuing the 60 newest bags at ₦11.50 first leaves 75 × ₦10.00 = ₦750. FIFO issues the oldest first, leaving 15 × ₦10.00 + 60 × ₦11.50 = ₦150 + ₦690 = ₦840.00 (B)." }),
    q(MILK + "Using simple average method, calculate the value of stock after 22/5/07.",
      ["₦1,198.00", "₦1,218.38", "₦1,257.67", "₦1,408.00"], C,
      "Closing stock is 340 − 230 = 110 bags; the simple average of the prices in stock is (₦10.00 + ₦11.50 + ₦12.80) ÷ 3 = ₦11.4333, and 110 × ₦11.4333 = ₦1,257.67.",
      { bookletKey: 'D', bookletNote: "The booklet answer ₦1,408.00 (D) is the FIFO value (110 bags × ₦12.80). The question asks for simple average: (₦10.00 + ₦11.50 + ₦12.80) ÷ 3 = ₦11.4333 per bag, and 110 × ₦11.4333 = ₦1,257.67 (C)." }),
    // paper 22–31
    q("The LIFO method has an advantage over FIFO in that stocks are valued at",
      ["previous prices", "current prices", "average rates", "flat rates"], B,
      "Under LIFO the stock issued (charged to cost of sales) is priced at the most recent, current prices, so cost of sales is close to replacement cost."),
    q("In sales ledger control account, returns inwards is usually",
      ["debited and debtors credited", "credited and sales returns debited", "debited and cash credited", "credited and bank credited"], B,
      "Returns inwards reduce what customers owe, so they are credited in the sales ledger control account, with the sales returns (returns inwards) account debited."),
    q("Purchases ledger control account can also be referred to as",
      ["sales day book", "purchases day book", "creditors ledger", "debtors ledger"], C,
      "The purchases ledger control account summarises the creditors' (bought) ledger, so it is also called the creditors ledger control account."),
    q("Which of the following is a debit item in the sales ledger control account?",
      ["Cheque receipts", "Dishonoured cheques", "Discount allowed", "Bills receivable"], B,
      "A dishonoured cheque restores the debt the customer owes, so it is debited; cheques received, discount allowed and bills receivable are credits."),
    q("Use the following information: \nCash Book (Extract)\nBalance b/f ... ₦2,200\nReceipts from customer ... ₦16,400\nSundry expenses ... ₦16,800\nDrawings ... ₦4,700\nSuppliers ... ₦7,300\nDebtors opening and closing balances amount to ₦6,500 and ₦7,600 respectively.\n\nWhat is the sales value?",
      ["₦15,300", "₦17,500", "₦28,400", "₦31,600"], B,
      "Credit sales = receipts from customers + closing debtors − opening debtors = ₦16,400 + ₦7,600 − ₦6,500 = ₦17,500."),
    q("Use the following information: \nFixtures ... ₦30,000\nDebtors ... ₦7,000\nStock ... ₦8,000\nCreditors ... ₦3,000\nGoodwill ... ₦10,000\n\nDetermine the capital.",
      ["₦10,000", "₦42,000", "₦45,000", "₦52,000"], D,
      "Capital = assets − liabilities = (₦30,000 + ₦7,000 + ₦8,000 + ₦10,000) − ₦3,000 = ₦52,000; goodwill is an (intangible) asset."),
    q("In manufacturing accounts, finance expenses are charged to the",
      ["departmental account", "trading account", "profit and loss account", "balance sheet"], C,
      "Finance expenses (such as interest and bank charges) are not costs of production or of buying goods, so they go to the profit and loss account."),
    q(MFG + "What is the total manufacturing profit?",
      ["₦64,000", "₦120,000", "₦360,000", "₦480,000"], B,
      "Market value of goods produced = 4,000 × ₦120 = ₦480,000; manufacturing profit = ₦480,000 − ₦360,000 = ₦120,000."),
    q(MFG + "Determine the value of prime cost.",
      ["₦416,000", "₦304,000", "₦240,000", "₦184,000"], B,
      "Prime cost = total production cost − factory overheads = ₦360,000 − ₦56,000 = ₦304,000."),
    q("The excess of revenue over expenditure is charged to",
      ["profit and loss", "revenue account", "accumulated fund", "income and expenditure account"], C,
      "In a not-for-profit body, the surplus (excess of income over expenditure) is added to the accumulated fund."),
    // paper 32–41
    q("Use the following information: \nReceipts and Payments Account (Extract)\nReceipts:\n1/9 Balance b/f ... ₦210,000\n5/9 Subscriptions ... ₦80,000\n30/9 Donations ... ₦60,000\nPayments:\n10/9 Salary ... ₦20,000\n15/9 Wages ... ₦15,000\n20/9 Donations ... ₦40,000\n20/9 Transportation ... ₦10,000\n30/9 Entertainment ... ₦50,000\n\nDetermine the balance.",
      ["₦415,000 debit", "₦215,000 credit", "₦215,000 debit", "₦315,000 credit"], C,
      "Receipts ₦350,000 − payments ₦135,000 = ₦215,000, a debit balance (cash in hand)."),
    q("The main advantage of a departmental account is that its",
      ["expenses are shared", "gross profit is computed", "net profit is computed", "balance sheet is obtained"], A,
      "In departmental accounts the common expenses are shared (apportioned) among the departments, so the result of each department can be seen."),
    q("Use the following information: \nTrading, Profit and Loss Account (Extract), Dept. X\nNet sales ... ₦3,000\nLess cost of goods sold:\nStock 1/1 ... ₦200\nPurchases ... ₦1,000\nCost of goods available for sale ... ₦1,200\nLess stock 31/12 ... ₦400\nCost of goods sold ... ₦800\n\nFrom the above information, the gross profit for department X is",
      ["₦3,800", "₦2,300", "₦2,200", "₦2,000"], C,
      "Gross profit = net sales − cost of goods sold = ₦3,000 − ₦800 = ₦2,200."),
    q("In the head office ledger, the value of goods sent to the branch is",
      ["debited to the head office current account", "debited to the branch current account", "credited to the head office current account", "credited to the branch current account"], B,
      "Head office treats the branch as owing it for the goods, so it debits the branch current account (and credits goods sent to branch)."),
    q("Which of the following methods of invoicing goods to branches facilitates easy checks on the activities of branches?",
      ["Cost price", "Fixed percentage on cost", "Selling price", "Invoice price"], C,
      "When goods are sent at selling price, head office knows exactly what the branch should have in cash and stock, so shortages are easily detected.",
      { keyVerdict: 'corrected', keyAnswer: 'A', answerNote: "JAMB's key gives A (cost price). Cost price is the simplest method, but the method that makes branch activities easy to check is selling price: head office then knows what the branch should hold in stock and cash, so any shortage shows up at once." }),
    q(PART + "Find Modibbo's share of the profit.",
      ["₦62,000", "₦48,000", "₦44,000", "₦43,000"], B,
      "Modibbo's share = 60,000/150,000 × ₦120,000 = 2/5 × ₦120,000 = ₦48,000."),
    q(PART + "What is Jakata's profit sharing ratio?",
      ["3:5", "1:2", "2:5", "1:5"], A,
      "Jakata contributed ₦90,000 of ₦150,000 total capital, so his share is 90:150 = 3:5."),
    q("In what way can goodwill be written off in a partnership business?",
      ["Using the partners' profit and loss sharing ratio", "By neglecting the ratio of partners' capital contributions", "By sharing it unequally among the partners where no agreement exists", "By sharing it among the active partners only"], A,
      "Goodwill is written off by debiting the partners' capital accounts in their profit and loss sharing ratio."),
    q("Ngozi and Musa with a capital of ₦30,000 each decide to admit Mary into the partnership business with a capital of ₦20,000 and goodwill of ₦15,000. If the profits and losses are to be shared equally, the journal entries to record goodwill are",
      ["debit goodwill ₦15,000, cash ₦20,000 and credit Mary's capital ₦35,000", "credit goodwill ₦15,000, cash ₦20,000 and debit Mary's capital ₦35,000", "debit goodwill ₦15,000, credit cash ₦20,000 and credit Mary's capital ₦20,000", "debit old partners' capital ₦15,000, credit cash ₦20,000 and Mary's capital ₦35,000"], A,
      "Mary brings cash ₦20,000 and goodwill ₦15,000: debit cash and goodwill, and credit her capital account with the total ₦35,000."),
    q("In converting a partnership into a limited liability company, the necessary accounts to be opened in the books of the company are",
      ["business purchase account and ordinary share capital account", "business purchase account, vendor account and ordinary share capital account", "business purchase account and vendor account", "ordinary share capital account, vendor account and unpaid share capital account"], B,
      "The company opens a business purchase account (assets and liabilities taken over), a vendor account (amount owed to the partners) and the ordinary share capital account (shares issued to settle it)."),
    // paper 42–50
    q("Given: \nI. The Memorandum of Association of the Company\nII. The Articles of Association of the Company\nIII. The incorporation documents\n\nFrom the above, which of the following is delivered to the Registrar of Companies for incorporation?",
      ["I and II", "I, II and III", "I and III", "II and III"], A,
      "The Memorandum and Articles of Association are the key documents delivered to the Registrar of Companies (the Corporate Affairs Commission in Nigeria) for incorporation."),
    q("When shares are oversubscribed and money returned to unsuccessful applicants, the entry to record such money is to debit",
      ["application and allotment account and credit unsubscribed shares", "application and allotment account and credit cash", "oversubscribed shares and credit allotment account", "cash and credit application and allotment account"], B,
      "Refunding application money reverses the receipt: debit application and allotment account and credit cash (bank)."),
    q("Investment at cost of a company is to be disclosed under",
      ["trading accounts", "profit and loss account", "balance sheet", "source and application of fund"], C,
      "An investment is an asset, so it is shown (at cost) in the balance sheet, today called the statement of financial position."),
    q(RAT + "Calculate the acid test ratio.",
      ["1.94:1", "1.96:1", "1:1.94", "1:1.96"], B,
      "Quick assets (debtors ₦24,000 + prepaid ₦700 = ₦24,700) ÷ current liabilities (creditors ₦12,250 + accrued ₦350 = ₦12,600) = 1.96:1."),
    q(RAT + "Determine the number of times stock was turned over during the period to the nearest figure.",
      ["1", "2", "3", "4"], B,
      "Cost of sales = ₦25,120 + ₦44,880 − ₦27,840 = ₦42,160; average stock = ₦26,480; ₦42,160 ÷ ₦26,480 = 1.59, about 2 times."),
    q("Which of the following is a source of revenue to the federation account?",
      ["Market fees", "Bicycle licences", "Tariffs", "Property rates"], C,
      "Tariffs (customs and excise duties) are collected federally and paid into the federation account; market fees, bicycle licences and property rates are local government revenues."),
    q("The book into which all types of a ministry's expenditure are recorded is the",
      ["ledger book", "payment book", "vote book", "expenditure book"], C,
      "The vote book records every commitment and payment against each vote (budget head) of a ministry, to stop overspending."),
    q("The Petroleum Technology Development Fund is under the",
      ["general fund", "contingency fund", "trust fund", "capital fund"], C,
      "The PTDF holds money from the oil industry for a specific purpose (training and technology development), so it is a trust (special) fund.",
      { keyVerdict: 'corrected', keyAnswer: 'D', answerNote: "JAMB's key gives D (capital fund). The PTDF is money set aside by law for one specific purpose, which is what a trust fund is; Nigerian public sector texts list it with the old Petroleum Trust Fund and Education Tax Fund as trust funds. The capital (development) fund finances general capital projects in the budget." }),
    q("The power to appoint the Auditor General of the Federation is vested in the",
      ["National Assembly", "President", "Judicial Service Commission", "Civil Service Commission"], B,
      "Under section 86 of the 1999 Constitution, the President appoints the Auditor-General for the Federation on the recommendation of the Federal Civil Service Commission, subject to Senate confirmation."),
  ]);
})();
