/**
 * JAMB/UTME 2020 — PRINCIPLES OF ACCOUNTS
 * From the 2020 question paper (questions 1–40);
 * answers from the JAMB/UTME Accounts answer key 2001–2020, each checked independently.
 * Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2020;
  const SRC = 'JAMB UTME 2020';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const DISC = "Use the following information: \nAdamu Stores bought accessories from Mu'azu Beverages for ₦400 on credit. A trade discount of 10% and a cash discount of 15% were provided.\n\n";
  const MACH = "Use the following information: \nA machine bought for ₦35,000 was estimated to have a life span of 5 years with a scrap value of ₦9,000.\n\n";
  const SOA = "Use the following information: \nMotor van ... 10,000\nFixtures ... 5,000\nCash ... 2,500\nCreditors ... 7,000\nLoan ... ?\nLoan is 30% of creditors.\n\n";
  const CB = "Given: Cash Book\nCapital ... ₦65,000 | Purchases ... ₦12,250\nSales ... ₦30,000 | Rent ... ₦9,100\n | Motor vehicle ... ₦2,400\n\n";
  const STK = "Use the following information: \nFeb. 1 ... Purchased 400 units at ₦1.00 each\nFeb. 5 ... Purchased 200 units at ₦2.00 each\nFeb. 10 ... Purchased 200 units at ₦3.00 each\nFeb. 15 ... Issued 320 units\nFeb. 20 ... Purchased 200 units at ₦3.00 each\nFeb. 25 ... Issued 120 units\n\n";

  QUESTION_BANK.accounting = QUESTION_BANK.accounting.concat([
    // paper 1–10
    q("One of the differences between bookkeeping and accounting is that the former",
      ["records data while the latter interprets", "is regarded as the language of the business while the latter ascertains its strength", "interprets data while the latter records it", "summarizes information while the latter communicates it"], A,
      "Bookkeeping is the recording stage; accounting goes further to classify, summarise, interpret and communicate the recorded data."),
    q("The costs of acquiring fixed assets and bringing them into the firm is a",
      ["general expenses", "recurrent expenditure", "revenue expenditure", "capital expenditure"], D,
      "Spending to buy a fixed asset and get it ready for use (including carriage and installation) is capital expenditure."),
    q("The standing order is a payment instrument given by a",
      ["customer to the bank", "bank to a customer", "bank to an employee", "customer to a fellow customer"], A,
      "A standing order is the customer's written instruction to his bank to pay a fixed amount to a named payee at regular intervals."),
    q("Which of the following is a debit item in the sales ledger control account?",
      ["Cheque receipts", "Dishonoured cheques", "Discount allowed", "Bills receivable"], B,
      "A dishonoured cheque puts the debt back on the customer, so it is debited in the sales ledger control account; the other three reduce debtors and are credits."),
    q("The amount paid by the new partner on admission as a compensation for the reputation built up by old partners is a",
      ["Bonus", "Good will", "Premium", "Commission"], B,
      "Goodwill is the value of the reputation and customer connections built up by the old partners, for which an incoming partner pays."),
    q(DISC + "Find the total amount paid.",
      ["₦260", "₦300", "₦200", "₦380"], B,
      "JAMB's answer takes both discounts on the full ₦400 (₦400 − ₦40 − ₦60 = ₦300); correctly the amount paid is ₦306, which is not offered.",
      { keyVerdict: 'none', keyAnswer: 'B', answerNote: "Trade discount comes off first: ₦400 − 10% (₦40) = ₦360 invoice price. The cash discount is then worked on ₦360: 15% × ₦360 = ₦54, so the amount paid is ₦360 − ₦54 = ₦306, which is not among the options. ₦300 results only if the 15% is wrongly taken on the full ₦400." }),
    q(DISC + "Calculate the cash discount.",
      ["₦60", "₦90", "₦40", "₦100"], C,
      "Correctly the cash discount is 15% of the net invoice price of ₦360, which is ₦54 and not among the options; JAMB's answer is ₦40.",
      { keyVerdict: 'none', keyAnswer: 'C', answerNote: "The cash discount is worked on the price after trade discount: 15% × (₦400 − ₦40) = 15% × ₦360 = ₦54, which is not offered. JAMB's ₦40 is 10% of ₦400, which is the trade discount; ₦60 would be 15% of the full ₦400, also not correct." }),
    q("Upon the dissolution of a partnership, the Partnership Act provides that the amount realized should be",
      ["Used to pay all taxes due to government", "Used to start a new partnership business by members who are willing", "Shared equally by the existing partners", "Used in paying the debts and liabilities of the firm to persons who are not partners."], D,
      "On dissolution the money realised is applied first to pay the firm's debts to outsiders, then partners' loans, then partners' capitals."),
    q(MACH + "If the scrap value is now ₦15,000, what will be the yearly depreciation using the straight-line method?",
      ["₦11,000", "₦7,000", "₦4,000", "₦24,000"], C,
      "Straight-line depreciation = (cost − scrap value) ÷ life = (₦35,000 − ₦15,000) ÷ 5 = ₦4,000 a year."),
    q("Given that the balance as per cash book after adjustment was ₦6,315, unpresented cheques ₦1,000 and the bank statement balance ₦3,240, what was the balance of the uncredited cheques?",
      ["₦4,075", "₦4,240", "₦3,315", "₦3,075"], A,
      "Bank statement + uncredited cheques − unpresented cheques = adjusted cash book: ₦3,240 + X − ₦1,000 = ₦6,315, so X = ₦4,075."),
    // paper 11–20
    q("The imprest account is subsidiary to the",
      ["ledger account", "Bank account", "Cash book", "Petty cash"], C,
      "The imprest (petty cash) account is kept in the petty cash book, a subsidiary book of the main cash book, which reimburses it."),
    q("The three-column cash book differs from the two-column cash book in",
      ["Cash column", "Discount column", "Bank column", "Folio column"], B,
      "The two-column cash book has cash and bank columns; the three-column cash book adds a discount column on each side."),
    q("The federal government approved ₦140m to local governments W, X, Y and Z. The amount is to be shared on the basis of 40% equality, 30% population and 25% internal revenue generation. Calculate the share of local government W on equality.",
      ["35m", "14m", "56m", "28m"], B,
      "The equality share is 40% × ₦140m = ₦56m, split equally among the four councils: ₦56m ÷ 4 = ₦14m for W.",
      { bookletKey: 'C', bookletNote: "The booklet answer 56m is the whole equality pool for all four councils (40% × ₦140m). Shared equally, W gets ₦56m ÷ 4 = ₦14m (B)." }),
    q("If an organization maintains a periodic stock system, the stock quantities are",
      ["updated at the end of the accounting year", "not considered in the updating process", "updated continuously", "updated at the beginning of the accounting year."], A,
      "Under the periodic system stock is counted and updated only at the end of the period; continuous updating is the perpetual system.",
      { bookletKey: 'C', bookletNote: "The booklet answer C (updated continuously) describes the perpetual stock system. Under the periodic system stock is counted and updated at the end of the accounting year, option A." }),
    q("Stock valuation is useful because it informs the sales department on the",
      ["prices of the competing goods", "prices that will affect profitability", "number of goods to produce", "number of goods to sell"], B,
      "The value placed on stock fixes cost of sales and so gross profit; knowing the cost of stock helps the sales department set prices that keep the business profitable."),
    q(SOA + "What is the capital balance?",
      ["8,400", "6,900", "10,500", "15,000"], A,
      "Assets 10,000 + 5,000 + 2,500 = 17,500; liabilities: creditors 7,000 + loan (30% × 7,000 = 2,100) = 9,100; capital = 17,500 − 9,100 = 8,400."),
    q(SOA + "The amount of the loan is",
      ["1,000", "2,100", "900", "1,200"], B,
      "Loan = 30% of creditors = 30% × 7,000 = 2,100."),
    q("A component of an overhead manufacturing cost is",
      ["labour", "rent", "cost of work-in-progress", "cost of finished goods"], B,
      "Factory overheads are indirect production costs such as factory rent, rates and power; direct labour is part of prime cost, and work in progress and finished goods are stocks, not overheads.",
      { bookletKey: 'C', bookletNote: "The booklet answer C (cost of work-in-progress) is a stock adjustment made after overheads are added, not an overhead itself. Factory rent is an indirect cost of production, so it is a factory overhead: option B." }),
    q("The imprest account is subsidiary to the",
      ["ledger account", "Bank account", "Cash book", "Petty cash"], C,
      "Under the imprest system the petty cash book is a subsidiary of the main cash book, from which the petty cashier is reimbursed."),
    q("In the public sector, the method of accounting that reports revenues and expenditures in the period in which they are received and paid is called",
      ["Fund accounting", "Commitment accounting", "Cash accounting", "Accrual accounting"], C,
      "Cash basis accounting records revenue when cash is received and expenditure when cash is paid, the traditional basis of government accounts."),
    // paper 21–30
    q("A double entry for a transaction that offsets one amount against another on both sides of the cashbook is a",
      ["original entry", "contra entry", "prime entry", "contract entry"], B,
      "A contra entry appears on both sides of the cash book, as when office cash is paid into the bank (debit bank column, credit cash column)."),
    q("The rent expense for Trendy store is ₦3500. Trendy store has three departments; jewelry, hair dressing, and clothing. The floor spaces occupied by the departments are 3:2:5 respectively. What is the rent allocated to clothing department?",
      ["₦700", "₦1050", "₦1750", "₦3500"], C,
      "Total ratio 3 + 2 + 5 = 10; clothing's share = 5/10 × ₦3,500 = ₦1,750."),
    q("The principle of double entry developed from the axioms of accounting equation is given as",
      ["Assets + Liability = Equity", "Assets + Equity = Liabilities", "Liabilities + Equity = Asset", "Liabilities + Equity = Net assets"], C,
      "The accounting equation is Assets = Capital (equity) + Liabilities, which is the same as Liabilities + Equity = Assets."),
    q("Balance as per cashbook ₦2,970; Bank charges ₦220; Unpresented cheques ₦3,950; Uncredited cheques ₦4,178; Direct debit by bank ₦1,000. Determine the balance as per bank statement.",
      ["₦1,978", "₦1,962", "₦1,522", "₦2,522"], C,
      "Adjusted cash book = ₦2,970 − ₦220 − ₦1,000 = ₦1,750; bank statement = ₦1,750 + unpresented ₦3,950 − uncredited ₦4,178 = ₦1,522."),
    q("A sale for ₦2,570 was recorded in the sales day book as ₦2,750. The error committed was",
      ["error of principle", "error of commission", "error of original entry", "compensating error"], C,
      "The wrong amount was written in the book of original entry and posted with that same wrong amount on both sides, so it is an error of original entry."),
    q(MACH + "The yearly depreciation using the straight line method would be",
      ["₦8,800", "₦6,500", "₦5,200", "₦4,400"], C,
      "Straight-line depreciation = (₦35,000 − ₦9,000) ÷ 5 = ₦26,000 ÷ 5 = ₦5,200 a year."),
    q(MACH + "If the scrap value is presently ₦15,000, what will be the yearly depreciation using straight line method?",
      ["₦4,000", "₦7,000", "₦11,000", "₦24,000"], A,
      "With the new scrap value, depreciation = (₦35,000 − ₦15,000) ÷ 5 = ₦20,000 ÷ 5 = ₦4,000 a year."),
    q("The accounting entries to record a cheque issued by a business is to",
      ["debit cash book and credit drawer", "credit cash book and debit drawer", "debit cash book and credit suspense account", "credit cash book and debit suspense account"], B,
      "A cheque issued is a payment: the bank column of the cash book is credited and the account of the person paid is debited. B has the right sides, though that person is strictly the payee.",
      { keyVerdict: 'none', keyAnswer: 'B', answerNote: "The correct entry is credit the cash book (bank column) and debit the account of the person the cheque is paid to, the payee. B has the right sides, but strictly the drawer of a cheque issued by the business is the business itself, so no option is worded fully correctly. B is the intended answer." }),
    q("In sales ledger control account, returns inwards is usually",
      ["debited and debtors credited", "credited and sales returns debited", "debited and cash credited", "credited and bank credited"], B,
      "Returns inwards reduce what debtors owe, so they are credited in the sales ledger control account; the double entry is a debit to the sales returns (returns inwards) account."),
    q("In bank reconciliation process, discrepancies caused by timing arise as a result of",
      ["cash book and bank statement", "bank statement only", "cash book, bank statement and other incidental records", "cash book only"], A,
      "Timing differences (unpresented and uncredited cheques) arise because the cash book and the bank statement record the same items on different dates."),
    // paper 31–40
    q("If a company values its stocks in the period of rising prices using LIFO method, there is a tendency for it to",
      ["have a higher cost of goods sold", "have a higher gross profit", "pay higher income tax", "have a higher value for closing stock."], A,
      "LIFO charges the latest, dearer purchases to cost of sales when prices rise, so cost of goods sold is higher and profit, tax and closing stock are lower.",
      { bookletKey: 'B', bookletNote: "The booklet answer B (higher gross profit) is what FIFO gives when prices rise. LIFO issues the latest, dearer goods first, so cost of goods sold is higher and gross profit is lower: option A." }),
    q("John, a prepaid customer of XYZ and KLM, bought ₦1,500 recharge card from XYZ and ₦2000 recharge card from KLM for business calls. The entry to record these transactions is debit",
      ["telephone ₦3500, credit XYZ and KLM ₦3500", "telephone ₦3500, credit cash ₦3500", "sundries ₦3500, credit KLM ₦3500", "sundries ₦3500, credit telephone ₦3,500"], B,
      "Prepaid recharge cards are bought and paid for at once, so telephone expense is debited ₦3,500 and cash is credited ₦3,500."),
    q(CB + "Find the bank balance",
      ["₦71,250 credit", "₦71,250 debit", "₦95,000 credit", "₦95,000 debit"], B,
      "Receipts ₦65,000 + ₦30,000 = ₦95,000; payments ₦12,250 + ₦9,100 + ₦2,400 = ₦23,750; balance = ₦71,250, a debit balance (money in the bank)."),
    q("The three-column cash book differs from the two-column cash book in",
      ["Cash column", "Discount column", "Bank column", "Folio column"], B,
      "A three-column cash book has discount, cash and bank columns; the extra discount column is what sets it apart from the two-column (cash and bank) cash book."),
    q(STK + "Calculate the price per unit of closing stock using the periodic weighted average method.",
      ["₦3.20", "₦3.00", "₦2.20", "₦2.00"], D,
      "Total purchases cost ₦400 + ₦400 + ₦600 + ₦600 = ₦2,000 for 1,000 units, so the periodic weighted average price is ₦2,000 ÷ 1,000 = ₦2.00 a unit."),
    q(STK + "Using the periodic simple average method, the cost per unit is",
      ["₦4.25", "₦3.25", "₦2.25", "₦1.25"], C,
      "The periodic simple average is the plain average of the purchase prices, ignoring quantities: (₦1 + ₦2 + ₦3 + ₦3) ÷ 4 = ₦9 ÷ 4 = ₦2.25."),
    q("Departmental accounts are prepared to aid the comparison of the",
      ["daily profits", "previous year's transactions", "management performances", "workers performances"], C,
      "Departmental accounts show the result of each department, so the performance of each department and its manager can be compared.",
      { keyVerdict: 'corrected', keyAnswer: 'D', answerNote: "JAMB's answer is D (workers performances). Departmental accounts measure the gross and net profit of each department as a whole; they are used to compare how departments, and the managers in charge of them, have performed. They do not measure the performance of individual workers, so C fits better." }),
    q("The salary of a partner is usually debited to the",
      ["sundry debtors' account", "appropriation account", "profit and loss account", "sundry current account"], B,
      "A partner's salary is a share of profit agreed in the partnership deed, so it is debited to the profit and loss appropriation account (and credited to his current account)."),
    q("The book of account in which information from the source documents are recorded consists of",
      ["debit and credit notes", "ledger and subsidiary books", "prepayments and accruals", "profit and loss and balance sheet"], B,
      "Information from source documents is entered in the subsidiary books (books of original entry) and then posted to the ledger."),
    q("Purchases ledger control account can also be referred to as",
      ["sales day book", "purchases day book", "creditors ledger", "debtors ledger"], C,
      "The purchases ledger control account summarises all the creditors' accounts, so it is also called the creditors ledger (control) account; the debtors' version is the sales ledger control account."),
  ]);
})();
