/**
 * JAMB/UTME 2019 — PRINCIPLES OF ACCOUNTS
 * From the 2019 question paper (questions 1–40, all imported);
 * answers from the JAMB/UTME Accounts answer key 2001–2020, each checked independently.
 */
(function () {
  const Y = 2019;
  const SRC = 'JAMB UTME 2019';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const CRED = "Use the information to answer this question: \nPayment to creditors ₦12,250\nCreditors at start ₦550\nCreditors at end ₦830\n\n";

  QUESTION_BANK.accounting = QUESTION_BANK.accounting.concat([
    // paper 1–10
    q("Transactions are recorded or posted to the ledger in line with",
      ["Accounting Concept", "Source document", "Double Entry Principle", "Data collection"], C,
      "Ledger postings follow the double entry principle: every transaction is debited to one account and credited to another with the same amount."),
    q("The two recognized accounting bases are",
      ["cash and credit", "personal and impersonal", "Accrual and Cash", "Drawings and Private"], C,
      "Accounts are kept either on the cash basis (record money when received or paid) or on the accrual basis (record income and expenses when earned or incurred)."),
    q("Given:\nAdditional capital ... ₦4,000\nCapital ... ₦8,000\nClosing capital ... ₦12,000\nNet profit ... ₦1,500\n\nThe drawings for the period stand at",
      ["₦1,500", "₦3,000", "₦12,000", "₦10,500"], A,
      "Drawings = opening capital + additional capital + net profit − closing capital = ₦8,000 + ₦4,000 + ₦1,500 − ₦12,000 = ₦1,500."),
    q("The importance of bank statement is all except",
      ["verifies the accuracy of balances of cash book and cheque book", "helps to detect and rectify any error", "helps to debit an account", "helps to update the cash book"], C,
      "A bank statement is used to check and update the cash book and to find errors through bank reconciliation; it is not a means of debiting an account."),
    q("Accounting standards are issued at the International level by the",
      ["Standards Advisory Council", "International Accounting Standards Board", "Nigerian Accounting Standards Board", "Standing Interpretations Committee"], B,
      "International standards (IAS/IFRS) are issued by the International Accounting Standards Board (IASB); in Nigeria, the Financial Reporting Council has replaced the old Nigerian Accounting Standards Board."),
    q("The method of stock valuation in which the issue price is obtained by dividing the value of stock in hand by unit of stock in hand is",
      ["FIFO", "LIFO", "SAP", "WAP"], D,
      "Under the weighted average price (WAP) method, the issue price is the total value of stock in hand divided by the number of units in hand, recalculated after each receipt."),
    q("One of these is not a similarity between Joint Venture and Partnership.",
      ["AIM is profit making", "It is for a specific venture", "involves two or more people", "have rights and duties"], B,
      "A joint venture is formed for one specific venture and ends when it is completed, while a partnership is a continuing business; so 'for a specific venture' is not shared."),
    q("Majority of commercial transactions are termed credit transactions, which means",
      ["The buyers pay immediately for goods bought", "Settlement is deferred to a future date", "No account will be opened", "Item of expenditure increases"], B,
      "In a credit transaction goods or services are supplied now and payment is made later, so settlement is deferred."),
    q("Bought motor vehicle ₦60 paying by cheque. The effect of the transaction will be",
      ["Increase in assets of motor vehicle account", "Decrease in assets of motor vehicle account", "Increase in assets of bank account", "Increase in liabilities of bank account"], A,
      "The motor vehicle account (an asset) is debited and increases, while the bank account is credited and decreases."),
    q("A proprietor withdraws cash from the business for private use, he",
      ["credits cash account and debits bank account", "credits cash account and debits drawing A/C", "debits cash account and credits drawings account", "debits bank account and credits drawings account"], B,
      "Cash taken out for private use reduces cash (credit cash) and is charged to the owner (debit drawings)."),
    // paper 11–20
    q("The rules of double entry states that",
      ["for every debit entry, there must be a corresponding debit entry", "for every credit entry, there must be a corresponding credit entry", "all transactions must be recorded in two accounts; one account is debited and another is credited", "all transaction must be credited"], C,
      "Double entry records every transaction twice: a debit in one account and an equal credit in another."),
    q("The difference between double entry and single entry is",
      ["double entry is based on the dual concept while single entry is not", "double entry is an account while single entry is not an account", "double entry keeps personal account while single does not", "double entry is useful for business enterprise while single entry is not"], A,
      "Double entry rests on the dual aspect concept (every transaction has two sides recorded); single entry records only one side, usually cash and personal accounts."),
    q("A rent of ₦50,000 was paid by Samson to his landlady by cheque. The double entry in Samson's book is",
      ["Debit rent account, Credit bank account", "Debit Rent account, Credit Samson's account", "Debit Bank account, Credit Rent account", "Debit Samson's account, Credit Rent account"], A,
      "In Samson's own books rent is an expense (debit rent account) and the cheque reduces his bank balance (credit bank account).",
      { bookletKey: 'B', bookletNote: "The booklet answer B credits Samson's own account, but these are Samson's books: he does not keep an account for himself, and the money left his bank. Paying rent by cheque is debit rent ₦50,000, credit bank ₦50,000, which is A." }),
    q("The purpose of profit and loss account is to ascertain",
      ["Gross profit", "Capital", "Expenses", "Net profit"], D,
      "The trading account finds gross profit; the profit and loss account deducts expenses (and adds other income) to find net profit."),
    q("Discount received is charged to",
      ["current account", "profit and loss", "trading account", "balance sheet"], B,
      "Discount received is a gain, so it is credited (added as income) in the profit and loss account."),
    q("An ordinary share of ₦100 was issued at ₦80. The share was issued at",
      ["premium", "par", "discount", "loss"], C,
      "Issuing a share below its nominal (par) value, here ₦80 for a ₦100 share, is an issue at a discount of ₦20."),
    q("Shares that are offered to existing shareholders at a price is called",
      ["par", "premium", "right issue", "bonus issue"], C,
      "A rights issue offers new shares to existing shareholders, in proportion to their holdings, for payment; a bonus issue is free."),
    q("Use the following information to answer this question:\nYear ... Profit\n1991 ... ₦14,000\n1992 ... ₦24,000\n1993 ... ₦10,000\n1994 ... ₦16,000\n\nIt has been decided to value goodwill at 2 years purchase of average profit for the past 4 years. The value of goodwill is",
      ["₦32,000", "₦16,000", "₦30,000", "₦64,000"], A,
      "Average profit = (₦14,000 + ₦24,000 + ₦10,000 + ₦16,000) ÷ 4 = ₦16,000; goodwill = 2 × ₦16,000 = ₦32,000."),
    q("Where there is no agreement made by the partners, the following provisions takes place except",
      ["No salary for partners acting in the business", "There is interest on capital", "No interest to be charged on drawings", "Profit and loss are to be shared equally"], B,
      "Under the Partnership Act 1890, with no agreement there is no interest on capital, no salaries, no interest on drawings, and profits and losses are shared equally."),
    q("In the absence of partnership agreement, a loan by a partner attracts interest at",
      ["20%", "5%", "10%", "15%"], B,
      "The Partnership Act 1890 gives a partner 5% per annum interest on a loan he makes to the firm when there is no agreement."),
    // paper 21–30
    q("In a non-profit making organization, the excess of Assets over liabilities equals",
      ["capital", "capital employed", "capital owned", "accumulated funds"], D,
      "A club or society has no owner's capital; the excess of its assets over its liabilities is called the accumulated fund."),
    q("The similarities between Receipts and payments and income and expenditure account include the following except",
      ["Both accounts follow the principle of double entry", "They are used to determine the financial position of the concern", "Both include capital items", "Both are prepared by non-profit making concern"], C,
      "The receipts and payments account includes capital receipts and payments, but the income and expenditure account excludes capital items, so 'both include capital items' is not a similarity."),
    q("Given:\nEquipment ... ₦10,000\nMotor Vehicle ... ₦15,000\nLoan ... ₦4,500\nCreditors ... ₦3,000\nSub in advance ... ₦150\nSub in arrears ... ₦3,500\n\nWhat is the accumulated fund?",
      ["₦14,150", "₦20,850", "₦21,850", "₦14,200"], B,
      "Assets: ₦10,000 + ₦15,000 + subscriptions in arrears ₦3,500 = ₦28,500. Liabilities: ₦4,500 + ₦3,000 + subscriptions in advance ₦150 = ₦7,650. Accumulated fund = ₦28,500 − ₦7,650 = ₦20,850.",
      { bookletKey: 'A', bookletNote: "The booklet answer A (₦14,150) treats subscriptions in arrears as a liability and subscriptions in advance as an asset, the wrong way round. Arrears are owed to the club (an asset) and advance subscriptions are owed by it (a liability): (₦10,000 + ₦15,000 + ₦3,500) − (₦4,500 + ₦3,000 + ₦150) = ₦28,500 − ₦7,650 = ₦20,850, which is B." }),
    q(CRED + "What is the amount of purchase?",
      ["₦11,970", "₦11,000", "₦1,250", "₦12,530"], D,
      "Credit purchases = payments to creditors + closing creditors − opening creditors = ₦12,250 + ₦830 − ₦550 = ₦12,530."),
    q(CRED + "What is the creditors amount in the balance sheet?",
      ["₦550", "₦12,250", "₦12,530", "₦830"], D,
      "The balance sheet shows what is still owed at the end of the period, so creditors appear at the closing figure of ₦830.",
      { bookletKey: 'C', bookletNote: "The booklet answer C (₦12,530) is the purchases figure from the creditors account, not the creditors balance. The balance sheet shows the amount still owed at the end, creditors at end ₦830, which is D." }),
    q("In the preparation of statement of profit, if the opening capital is greater than closing capital, there will be",
      ["profit", "capital", "loss", "cash"], C,
      "When profit is found by comparing capitals, a fall in capital from the start to the end of the period (with no drawings or new capital to adjust for) shows a loss."),
    q("The manufacturing account is prepared to ascertain",
      ["cost of goods sold", "cost of production", "Gross profit", "Finished goods"], B,
      "The manufacturing account adds prime cost and factory overheads, adjusted for work in progress, to find the cost of production of goods completed."),
    q("Which of the following is not charged to manufacturing account?",
      ["Direct expenses", "Factory wages", "Distribution expenses", "Raw materials"], C,
      "Distribution (selling) expenses arise after production and are charged to the profit and loss account, not the manufacturing account."),
    q("Which of the following cannot depreciate?",
      ["plant and machinery", "motor van", "premises", "land"], D,
      "Land has an unlimited useful life and is normally not depreciated, unlike plant, vehicles and buildings."),
    q("A machine cost ₦12,500 it will be kept for 4 years and then sold at a scrap value of ₦5,120. Using the diminishing balance method, what is the amount of depreciation for second year if depreciation is charged at 20% per annum?",
      ["₦5,120", "₦6,400", "₦2,000", "₦12,500"], C,
      "Year 1: 20% × ₦12,500 = ₦2,500, leaving ₦10,000. Year 2: 20% × ₦10,000 = ₦2,000."),
    // paper 31–40
    q("An officer that is charged with the responsibility of carrying out investigations on the book of accounts to show the true and fair view is",
      ["Ministry of Finance", "Accountant General", "Revenue office", "Auditor General"], D,
      "The Auditor-General audits government accounts and reports whether they show a true and fair view."),
    q("The instrument issued by the Minister who authorized an officer to incur expenditure is a/an",
      ["warrant", "budget", "imprest", "consolidated fund"], A,
      "A warrant, issued under the authority of the Minister of Finance, empowers accounting officers to incur expenditure approved in the budget."),
    q("One of the objectives of maintaining the account of a branch at the head office is to",
      ["assess the performance of the branches", "check the excesses of customers", "record charges in shareholdings", "record charges in liabilities"], A,
      "Head office keeps branch accounts mainly to find each branch's profit and so assess its performance."),
    q("A company goods sent to branch at invoiced price is ₦30,870 at cost plus 25%. The mark-up is",
      ["₦20,000", "₦6,000", "₦6,174", "₦10,000"], C,
      "At cost plus 25%, invoice price = 125% of cost, so mark-up = 25/125 × ₦30,870 = ₦6,174."),
    q("The objective of departmentalization is to",
      ["ensure that departmental managers are adequately monitored", "record transactions for each department for better documentation", "tackle any recording problem as a result of expansion", "evaluate the profit of different departments"], D,
      "Departmental accounts show the gross and net profit of each department so that their results can be compared and evaluated."),
    q("Discount received is apportioned to each department on the basis of",
      ["Floor area", "Turnover", "Purchases", "Horse power"], C,
      "Discount received arises from paying for purchases, so it is shared among departments in the ratio of their purchases."),
    q("Given:\nFixed assets ... ₦55,000\nLiabilities ... ₦20,000\nCurrent assets ... ₦13,000\n\nWhat is the capital?",
      ["₦88,000", "₦48,000", "₦62,000", "₦55,000"], B,
      "Capital = total assets − liabilities = (₦55,000 + ₦13,000) − ₦20,000 = ₦48,000."),
    q("Capital at start was ₦250,000, while capital at the end of the year was ₦400,000. Drawings during the year amounted to ₦15,000. What is the profit?",
      ["₦165,000", "₦635,000", "₦600,000", "₦156,000"], A,
      "Profit = closing capital − opening capital + drawings = ₦400,000 − ₦250,000 + ₦15,000 = ₦165,000."),
    q("In the preparation of account, the owners of the business and the business concerned are treated as",
      ["partners", "joint venture", "the same person", "separate legal entities"], D,
      "By the business entity concept, the business is accounted for separately from its owners."),
    q("From the following, determine the value of closing stock using the FIFO method:\nFeb 1 purchased 200 units @ ₦2.00 each\nFeb 3 purchased 100 units @ ₦1.00 each\nFeb 4 issued 120 units @ ₦5.00 each\nFeb 5 purchased 50 units @ ₦3.00 each\nFeb 6 issued 100 units @ ₦4.00 each",
      ["₦330", "₦420", "₦230", "₦320"], C,
      "Under FIFO the 130 units left are the latest bought: 50 @ ₦3.00 = ₦150 and 80 @ ₦1.00 = ₦80, total ₦230."),
  ]);
})();
