/**
 * JAMB/UTME 2017 — PRINCIPLES OF ACCOUNTS
 * From the 2017 question paper (questions 1–40; Q26 left out because its statements I–IV were not printed);
 * answers from the JAMB/UTME Accounts answer key 2001–2020, each checked independently.
 * Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2017;
  const SRC = 'JAMB UTME 2017';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  QUESTION_BANK.accounting = QUESTION_BANK.accounting.concat([
    // paper 1–10
    q("The use of a three-column cash book is determined by",
      ["cash discounts", "trade discounts", "cash transactions", "bank transactions"], A,
      "The third column (discount) is added to the two-column cash book because the business gives and receives cash discounts; trade discounts are never entered in the books."),
    q("The tier of government that uses financial memorandum is the",
      ["federal government", "state government", "local government", "municipal government"], C,
      "The Financial Memoranda are the rules that govern the financial administration of local governments in Nigeria, as Financial Regulations do for the federal and state governments."),
    q("Which of the following is used to service all operations of government?",
      ["Consolidated Revenue Fund", "Consolidated Reserve Fund", "Special Operational Fund", "General Reserve Fund"], A,
      "All revenues of government are paid into the Consolidated Revenue Fund, and the recurrent and other operations of government are financed from it."),
    q("What is the effect of the transaction when cash is paid into the bank?",
      ["Bank balance decreases and cash balance increases", "Bank balance decreases and cash balance decreases", "Cash balance increases and bank balance increases", "Cash balance decreases and bank balance increases"], D,
      "Paying cash into the bank moves money from the cash column to the bank column: cash goes down and the bank balance goes up (a contra entry)."),
    q("The principle of double entry developed from the axioms of the accounting equation is given as",
      ["Assets + Liabilities = Equity", "Assets + Equity = Liabilities", "Liabilities + Equity = Assets", "Liabilities + Equity = Net assets"], C,
      "Every asset is financed either by outsiders (liabilities) or by the owner (equity), so Liabilities + Equity = Assets, and every transaction keeps both sides equal."),
    q("The correct expression of the accounting equation is",
      ["Assets = Liabilities + Equity", "Net assets = Liabilities + Equity", "Assets + Liabilities = Equity", "Assets = Equity - Liabilities"], A,
      "The accounting equation states that the resources of a business (assets) equal the claims on them: Assets = Liabilities + Equity."),
    q("Subscription in advance is treated in the balance sheet as a",
      ["current asset", "current liability", "fixed asset", "long term liability"], B,
      "Subscriptions received in advance belong to next year; the club owes members that period of membership, so it is a current liability. Today the balance sheet is called the statement of financial position."),
    q("Which of these is a content of a master file?",
      ["All records relevant to the organization", "Records of assets of the organization", "A collection of data items", "All records relating to employees"], A,
      "A master file holds the main, relatively permanent records the organisation needs (customers, suppliers, staff, stock and so on), which are kept up to date from transaction files."),
    q("An evidence of payment issued to a government ministry by a revenue collector is",
      ["treasury receipt", "receipt voucher", "payment voucher", "treasury card"], B,
      "When a revenue collector pays in the money collected, the receipt voucher is the document that evidences the payment and supports the revenue entry in the ministry's cash book."),
    q("A part of a public company's profits belonging to the shareholders is",
      ["public issue", "bonus", "right issue", "dividends"], D,
      "Dividends are the share of a company's profit paid out to its shareholders."),
    // paper 11–20
    q("When expenses are paid on behalf of the venture, the accounting entries is to debit",
      ["bank account and credit joint venture account", "expenses account and credit bank account", "joint venture account and credit expenses account", "joint venture account and credit bank account"], D,
      "Expenses paid for a joint venture are charged to the joint venture account (debit), and the money leaves the bank (credit bank)."),
    q("The movement of goods from head office to a branch is treated in the head office accounts as",
      ["sales", "issue", "purchase", "requisition"], C,
      "Goods sent to a branch are not a sale; head office credits them to a goods sent to branch account, which is taken out of purchases in the head office trading account, so they are dealt with through purchases."),
    q("One of the options below has the same features as the profit and loss account in a non-profit organization",
      ["Income and expenditure account", "Profit and loss account", "Receipts and payments account", "Nonprofit account"], A,
      "The income and expenditure account of a club is prepared on the accruals basis like a profit and loss account, but shows a surplus or deficit instead of a profit or loss."),
    q("An advantage of the FIFO method of stock valuation is that",
      ["it serves as a control during inflation", "it is calculated at the end of the year", "it is progressive in nature", "its flow of cost is in sequence with the flow of stock"], D,
      "Under FIFO the oldest goods are assumed to be issued first, which follows the way goods physically move in most businesses, so the cost flow matches the stock flow."),
    q("Discount allowed is enjoyed by",
      ["managers", "customers", "suppliers", "staff of the company"], B,
      "Discount allowed is the cash discount a business gives its customers (debtors) for paying promptly, so the customers enjoy it."),
    q("The accounting entries for goods stolen in a branch will be to debit",
      ["branch debtors account and credit branch stock account", "branch stock account and credit branch adjustment account", "branch adjustment account and credit profit and loss account", "branch adjustment account and credit branch stock account"], D,
      "Goods stolen are a loss: they are removed from the branch stock account (credit) and charged to the branch adjustment account (debit), which then carries the loss to profit and loss."),
    q("The following appear in the trading account except",
      ["sales", "carriage outward", "carriage inward", "opening stock"], B,
      "Carriage outwards is a selling and distribution expense charged in the profit and loss account; sales, carriage inwards and opening stock all belong in the trading account."),
    q("Goodwill can be created in the books of a partnership firm when",
      ["the partnership experiences super profit", "a new member is admitted", "the business is being expanded", "the business suffers high loss"], B,
      "Goodwill is normally brought into a partnership's books when there is a change in the partnership, such as the admission of a new partner, so that the old partners are credited for the value they built."),
    q("Given: \nI. Settlement of debts\nII. Cessation of business\nIII. Introduction of assets\nIV. Disposal of assets\n\nWhich of these constitutes dissolution of partnership?",
      ["II and IV only", "I, II and IV only", "I, II and III only", "II, III and IV only"], B,
      "On dissolution the business stops (II), its assets are sold off (IV) and its debts are paid (I); no new assets are introduced."),
    q("The discount column on the left-hand side of the cash book represents a discount",
      ["received from a creditor", "allowed to a debtor", "received from a debtor", "allowed to a creditor"], B,
      "The left (debit) side of the cash book records money received, so its discount column shows discounts allowed to debtors who paid."),
    // paper 21–30
    q("To which of these accounts are dissolution expenses debited?",
      ["Partners' capital account", "Revaluation account", "Partners' current account", "Realisation account"], D,
      "Dissolution (realisation) expenses reduce what the partners get from winding up, so they are debited to the realisation account and credited to cash or bank."),
    q("Capital for a profit-making organization is generated through",
      ["subscription", "shares", "donation", "gift"], B,
      "A company raises its capital by issuing shares; subscriptions, donations and gifts are sources of funds for non-profit organisations."),
    q("The account where the profit is distributed to the partners in their profit sharing ratio in a partnership is the",
      ["trading account", "appropriation account", "balance sheet", "profit and loss account"], B,
      "The profit and loss appropriation account shows how the net profit is shared: interest on capital, salaries, and the balance in the profit sharing ratio."),
    q("In manufacturing accounts, depreciation of office machine is charged to",
      ["trading account", "appropriation account", "balance sheet", "profit and loss account"], D,
      "An office machine is used in administration, not production, so its depreciation is an administrative expense charged to the profit and loss account; only factory depreciation goes into the manufacturing account."),
    q("Which of the following is not an item on the debit side of the sales ledger control account?",
      ["Cash refunds", "Debit note issued", "Dishonoured cheque", "Purchases"], D,
      "Purchases have nothing to do with debtors; they belong to the purchases ledger. Cash refunded to customers, debit notes issued to them and dishonoured cheques all increase what debtors owe and are debited."),
    q("Given:\nI. Cash refunds\nII. Debit note issued\nIII. Dishonoured cheque\nIV. Purchases\n\nThe items on the credit side of the purchases ledger control account include",
      ["I, II and III only", "I and II only", "III and IV only", "I, III and IV only"], D,
      "The purchases ledger control account is credited with whatever increases the amount owed to suppliers: credit purchases, cheques we paid that were dishonoured, and cash refunds received from suppliers. A debit note issued (returns outwards) reduces what we owe, so it goes on the debit side."),
    q("You add the following when starting with the balance as per cash book when preparing the bank reconciliation statement except",
      ["unpresented cheque", "dividend", "uncredited cheque", "credit transfer"], C,
      "Starting from a debit cash book balance, unpresented cheques, and dividends or credit transfers received by the bank but not yet in the cash book, are added; uncredited cheques (lodgements not yet credited) are deducted.",
      { bookletKey: 'A', bookletNote: "The booklet answer A (unpresented cheque) is one of the items that IS added: those cheques are already deducted in the cash book but not yet by the bank, so adding them back moves the cash book figure towards the bank figure. The item that is deducted, not added, is the uncredited cheque, which is C." }),
    q("Which fund is used to meet unforeseen or urgent expenditure?",
      ["General reserve fund", "Consolidated Reserve Fund", "Contingencies fund", "Special fund"], C,
      "The Contingencies Fund is set aside to meet urgent and unforeseen government expenditure for which no provision was made in the budget."),
    q("In a period of rising prices, which method of stock valuation is most appropriate?",
      ["Last in First Out", "Weighted average", "First in First Out", "Simple average"], A,
      "When prices are rising, LIFO charges the latest (higher) costs to cost of sales, so profit is not overstated by old, cheap costs. Today IAS 2 does not allow LIFO in published accounts."),
    q("Which of these is the subsidiary book for return inwards?",
      ["Sales day book", "Sales return journal", "Purchases day journal", "Cash book"], B,
      "Returns inwards are goods returned by customers, and they are first recorded in the sales returns journal (returns inwards book) from credit notes issued."),
    // paper 31–40
    q("A double entry for a transaction that offsets one amount against another on both sides of the cash book is a",
      ["original entry", "contra entry", "prime entry", "contract entry"], B,
      "A contra entry appears on both sides of the cash book, for example cash paid into the bank (debit bank column, credit cash column)."),
    q("What is the main purpose of a transaction file?",
      ["To record assets and liabilities", "To update income and expenses", "To update master files", "To make organization decisions"], C,
      "A transaction file holds the day's or period's movements, and its main use is to update the master file so that the permanent records stay current."),
    q("Processed data is only useful to the user if it is",
      ["complex", "quantitative", "relevant", "qualitative"], C,
      "Information is useful only when it is relevant: it bears on the decision the user has to make."),
    q("Changes can occur in partnership when: \nI. partnership is dissolved\nII. there is amalgamation of partnership\nIII. there is a change in the profit or loss sharing ratio\nIV. intangible asset increases\n\nThe correct options are",
      ["I, II and IV", "I and III", "I, II and III", "I, III and IV"], C,
      "Dissolution, amalgamation with another firm and a change in the profit-sharing ratio all change the partnership agreement; a rise in an intangible asset is not a change in the partnership."),
    q("The authority warrant issued prior to the approval of the appropriation bill at the beginning of the year is",
      ["provisional general warrant", "annual general warrant", "reserved expenditure warrant", "contingencies"], A,
      "If the Appropriation Bill has not been passed when the year starts, a provisional general warrant authorises spending for a limited period until the annual general warrant is issued."),
    q("One of the options below is not a source of income for a non-profit organization",
      ["Entrance fees", "Subscription/dues", "Ordinary shares", "Donations"], C,
      "Clubs and societies earn income from entrance fees, subscriptions and donations; ordinary shares are issued by companies to raise capital."),
    q("When starting with the cash book balance in preparing the bank reconciliation statement, the following are added",
      ["Unpresented cheque", "Dividend", "Uncredited cheque", "Credit transfer"], A,
      "Starting from a debit cash book balance, unpresented cheques are added back; dividends and credit transfers received direct by the bank but not yet in the cash book are added too.",
      { keyVerdict: 'multiple', alsoAccept: [B, D], keyAnswer: 'A', answerNote: "The question says \"the following are added\", and when you start from the cash book balance before it is updated, dividends (B) and credit transfers (D) received by the bank are added as well as unpresented cheques (A). Only the uncredited cheque (C) is deducted. A, B and D are all accepted." }),
    q("Which of these is the main source document for recording cash paid into the bank?",
      ["Invoice", "Cheque book", "Credit note", "Pay-in-slip"], D,
      "The pay-in slip (deposit slip) is filled in when cash or cheques are paid into the bank, and its counterfoil is the evidence for the entry."),
    q("Given: \nI. It records subscription in arrears\nII. Payments of liabilities are affected\nIII. The account does not show if cash payment is revenue or capital expenditure\nIV. It performs the same function as the cash book\n\nThe features of a receipts and payments account include",
      ["I, II and IV", "II, III and IV", "III and IV", "I, II and III"], B,
      "A receipts and payments account is a summary of the cash book (IV): it shows all cash paid, including payments of liabilities (II), and mixes capital and revenue items (III); it does not show subscriptions in arrears (owing)."),
    q("The following are the importance of branch accounts except",
      ["it enables the organization to determine the branch that is making either profit or loss", "it allows proper control over the branch by the head office", "it assists the organization to determine the performance of a branch manager", "it allows fraud and wastage of resources"], D,
      "Branch accounts help find each branch's profit, control the branch and judge its manager; they are meant to prevent fraud and waste, not allow it.")
  ]);
})();
