/**
 * JAMB/UTME 2015 — PRINCIPLES OF ACCOUNTS
 * From the 2015 question paper (questions 1–50; this paper has no question-paper-type item);
 * answers from the JAMB/UTME Accounts answer key 2001–2020, each checked independently.
 * Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2015;
  const SRC = 'JAMB UTME 2015';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  QUESTION_BANK.accounting = QUESTION_BANK.accounting.concat([
    // paper 1–10
    q("Determine wage expenses from the given information: \nWages outstanding at the beginning ... ₦1,000\nWages paid during the period ... ₦15,000\nWages outstanding at the end of the period ... ₦2,000",
      ["₦16,000", "₦17,000", "₦13,000", "₦14,000"], A,
      "Wages expense = wages paid ₦15,000 − opening wages outstanding ₦1,000 (which belongs to last period) + closing wages outstanding ₦2,000 = ₦16,000."),
    q("Which method of pricing can be used satisfactorily in either rising or falling price situation?",
      ["Market price", "Average method", "FIFO", "Standard price"], B,
      "The average method smooths out price changes, so issues and closing stock are neither too high nor too low whether prices are rising or falling."),
    q("Use the following information: \nClub building ... ₦400,000\nSubscription in arrears ... ₦32,000\nEquipment ... ₦150,000\nCreditor ... ₦85,000\nSubscription prepaid ... ₦3,000\n\nWhat is the club's accumulated fund?",
      ["₦699,000", "₦494,000", "₦462,000", "₦605,000"], B,
      "Accumulated fund = assets (₦400,000 + ₦32,000 + ₦150,000 = ₦582,000) − liabilities (₦85,000 + ₦3,000 = ₦88,000) = ₦494,000."),
    q("What is the amount invested by a subscriber who purchases 50,000 units of ordinary shares at ₦1.50 each?",
      ["₦75,000", "₦35,000", "₦100,000", "₦90,000"], A,
      "Amount invested = 50,000 shares × ₦1.50 = ₦75,000."),
    q("Use the following information: \nBuhari and Osibanjo are in partnership with the following partnership agreement:\nItem ... Buhari ... Osibanjo\nCapital ... ₦40,000 ... ₦70,000\nSalary ... ₦10,000 ... ₦15,000\nInterest on capital ... 5% ... 5%\nProfit/loss sharing ratio ... 40 ... 60\nThe net profit for the year ended is ₦80,000.\nDrawings are ₦80,000 and ₦12,000 for Buhari and Osibanjo respectively.\n\nWhat is Osibanjo's share of profit?",
      ["₦19,800", "₦49,500", "₦48,000", "₦29,700"], D,
      "Residual profit = ₦80,000 − salaries ₦25,000 − interest on capital (₦2,000 + ₦3,500) = ₦49,500; Osibanjo's 60% share = ₦29,700."),
    q("The major distinguishing element between the final account of a partnership and that of a sole trader is the",
      ["drawing A/C", "capital A/C", "creditor A/C", "appropriation A/C"], D,
      "A partnership adds a profit and loss appropriation account to share the net profit among the partners (salaries, interest, profit shares); a sole trader keeps all the profit and needs none."),
    q("Prime cost is one of the following",
      ["expenses which can be identified with and allocated to cost centers", "aggregate direct material cost, direct labour cost and variable direct expenses", "the cost taken into account in the production process whether direct or indirect", "the cost of commodities supplied to an undertaking"], B,
      "Prime cost is the total of the direct costs of production: direct materials, direct labour and direct expenses."),
    q("The accounting concept that allows the cost of kitchen cutlery to be expensed, though it can be used for more than one year is",
      ["materiality", "accrual", "going concern", "business entity"], A,
      "Materiality allows items too small to matter, such as cutlery, to be written off as expenses at once instead of being capitalised and depreciated."),
    q("When the invoice of a customer is overcast, the supplier will send to him a",
      ["debit note", "cheque", "credit note", "payment voucher"], C,
      "An overcast invoice overcharges the customer, so the supplier sends a credit note to reduce the amount the customer owes."),
    q("The ledger entries to be made if cash sales is banked is debit",
      ["cash, credit sales", "sales, credit cash", "bank, credit cash", "bank, credit sales"], D,
      "When the takings from cash sales are paid straight into the bank, the bank account is debited and the sales account credited."),
    // paper 11–20
    q("In a bank reconciliation statement, dishonoured cheques is added to",
      ["unpresented cheques", "uncredited cheques", "statement of account", "aggregate balance as per cash book"], B,
      "Starting from the bank statement balance, a dishonoured cheque is added together with uncredited cheques, because both are sums the cash book shows as received but the bank balance does not include."),
    q("Which of the following is a debit entry in debtors control account?",
      ["Discount allowed", "Return inwards", "Credit sales", "Cash from debtors"], C,
      "Credit sales increase what debtors owe, so they are debited to the debtors (sales ledger) control account; discount allowed, returns inwards and cash received are credits."),
    q("Which of the following is not a proper form of the accounting equation?",
      ["fixed assets + current assets − liabilities = capital", "fixed assets + current assets + liabilities = capital", "fixed assets − liabilities + current assets = capital", "fixed assets + current assets − capital = liabilities"], B,
      "Capital = assets − liabilities, so liabilities must be deducted from assets, not added to them; B is the only wrong form."),
    q("The accounting convention that states that stock should be valued at the lower of cost and net realisable value is ------------- convention",
      ["matching", "consistency", "realization", "prudency"], D,
      "Prudence (conservatism) does not anticipate profits but provides for all known losses, so stock is valued at the lower of cost and net realisable value (as IAS 2 still requires for inventory)."),
    q("What does liquidity ratio measure?",
      ["measures operating efficiency of a company", "measures the ability of a company to meet its current obligations", "measures the value of investments of a company", "measures the financial leverage of a company"], B,
      "Liquidity ratios (current ratio, quick ratio) compare current assets with current liabilities to show whether a company can pay its short-term debts."),
    q("The following accounting entries are made when bad debt is recovered",
      ["debit bad debts account and credit bad debt recovered account", "debit debtors account and credit bad debts recovered account", "debit bad debts recovered account and credit bad debts account", "debit bad debts account and credit profit and loss account"], B,
      "The debt is first reinstated (debit the debtor, credit bad debts recovered), then the cash received is recorded (debit cash, credit the debtor)."),
    q("A sale for ₦2,570 was recorded in the sales day book as ₦2,750. The error committed was",
      ["error of principle", "error of commission", "error of original entry", "compensating error"], C,
      "The wrong figure was entered in the book of original entry and then posted on both sides, so it is an error of original entry; the trial balance still agrees."),
    q("Keeping records under single entry system has the advantage of",
      ["quality in terms of records", "simplicity in terms of operation", "accuracy in terms of operation", "completeness in terms of records"], B,
      "Single entry is simple and cheap to operate, which suits small traders; it is incomplete and not arithmetically checked, so it lacks accuracy and completeness."),
    q("Which of the following is true in public sector accounting? Cost of assets is",
      ["depreciated on straight line method", "expensed in the year of purchase", "charged to federation account", "depreciated on reducing balance method"], B,
      "Under the cash-basis government accounting used when the paper was set, capital spending was charged as expenditure in the year it was paid; Nigeria has since moved to accrual IPSAS, under which assets are capitalised and depreciated."),
    q("Which of the following accounts is debited when a delivery van is sold for cash?",
      ["sales account", "delivery van account", "cash account", "profit and loss account"], C,
      "Cash comes in, so the cash account is debited; the proceeds are credited to the delivery van (or disposal) account, not to sales."),
    // paper 21–30
    q("Goods stolen at the branch is debited to",
      ["branch stock account", "defalcations account", "branch debtors account", "branch adjustment account"], D,
      "Under the branch stock and adjustment method, a stock loss is credited to branch stock account at selling price and debited to branch adjustment account, so the loss reduces the branch gross profit."),
    q("Specific principles, bases, conventions, rules and practices adopted by an enterprise in preparing and presenting financial statements are known as ----------",
      ["financial accounting", "accounting policies", "cost accounting", "accounting conventions"], B,
      "This is the standard definition of accounting policies (IAS 8 today): the specific principles, bases, conventions, rules and practices an entity chooses for its financial statements."),
    q("Which of the following cannot be realized?",
      ["creditors", "debtors", "motor vehicles", "goodwill"], D,
      "Goodwill is an intangible asset that cannot be sold separately from the business, so it cannot be realised on its own; debtors and vehicles can be turned into cash."),
    q("If a trial balance is in agreement, one of the statements is untrue",
      ["the accounting system is error free", "equal debit entries and credit entries were recorded for each transaction", "the debit and credit from the journal were posted to the accounts", "account balances were correctly computed"], A,
      "An agreed trial balance proves only arithmetical accuracy; errors such as omission, commission, principle, original entry and compensating errors can still exist."),
    q("Use the following information: \nClub building ... ₦400,000\nSubscription prepaid ... ₦3,000\nSport kits ... ₦150,000\nBar creditors ... ₦85,000\nSubscription owing ... ₦32,000\n\nWhat is the club's total liabilities?",
      ["₦11,700", "₦26,700", "₦88,000", "₦85,000"], C,
      "Liabilities = bar creditors ₦85,000 + subscriptions paid in advance ₦3,000 = ₦88,000; subscriptions owing by members are an asset."),
    q("If sales return is understated, it implies that ----- is overstated",
      ["return inward", "sales figure", "cost of sales", "return outward"], B,
      "Net sales = sales − returns inwards, so if returns inwards are understated, the net sales figure is overstated."),
    q("An advantage of using accounting ratios is that they",
      ["can be easily calculated", "show errors and frauds", "facilitate decision making", "are stipulated by law"], C,
      "Ratios turn the figures in the accounts into comparable measures of profitability, liquidity and efficiency, which helps users make decisions."),
    q("The loss made by a nonprofit making organization is called",
      ["deficit", "surplus", "discount", "shortage"], A,
      "In an income and expenditure account an excess of expenditure over income is a deficit; an excess of income is a surplus."),
    q("If rent account is debited instead of rate account, the error committed is that of",
      ["omission", "commission", "principle", "original entry"], B,
      "Rent and rates are accounts of the same class (both expenses), so posting to the wrong one is an error of commission; an error of principle puts an item in the wrong class of account.",
      { bookletKey: 'A', bookletNote: "The booklet answer A (error of omission) would mean the transaction was left out of the books completely, but here it was recorded, only in the wrong account. Rent and rates are both expense accounts, so debiting rent instead of rates is an error of commission, B." }),
    q("Use the following information: \nProvision for bad debts ... ₦1,500\nAdditional information:\nI. Bad debts written off amount to ₦3,000.\nII. Debtors balance as at the end of the year is ₦28,000.\nIII. Provision for bad debts stands at 10%.\n\nHow much is to be charged to profit and loss account as provision for bad debts?",
      ["₦2,800", "₦1,000", "₦2,500", "₦3,000"], B,
      "Good debtors = ₦28,000 − ₦3,000 written off = ₦25,000; new provision = 10% × ₦25,000 = ₦2,500; the charge is the increase, ₦2,500 − ₦1,500 = ₦1,000."),
    // paper 31–40
    q("Use the following information: \nA limited liability company has an authorized share capital of ₦50 million split into 100 million shares. 80 million shares are offered for subscription at 60k per share in full on application. These have been fully subscribed on issue.\n\nWhat is the nominal value of each share?",
      ["₦2", "₦0.80", "₦0.60", "₦0.50"], D,
      "Nominal value = authorised capital ÷ number of shares = ₦50 million ÷ 100 million = ₦0.50; the 60k is the issue price (₦0.10 premium)."),
    q("The imprest of a petty cashier is ₦2,450. Expenses: \nPrinting ... ₦420\nCleaning ... ₦250\nStamp and postage ... ₦175\n\nHow much was received to maintain the imprest at the end of the month?",
      ["₦1,605", "₦845", "₦2,450", "₦1,300"], B,
      "Under the imprest system the petty cashier is reimbursed with what was spent: ₦420 + ₦250 + ₦175 = ₦845."),
    q("The wear and tear of a fixed asset of a company which is chargeable to the company's financial statement is called ----",
      ["appreciation", "amortization", "provisions", "depreciation"], D,
      "Depreciation is the part of a tangible fixed asset's cost used up through wear and tear, charged to profit and loss each year; amortisation is the equivalent word for intangible assets."),
    q("Sai Baba made sales of ₦10,000 having computed his gross profit % to sales to be 20. His opening stock was ₦250 and ending stock is ₦200. Calculate his purchases.",
      ["₦7,950", "₦8,050", "₦7,050", "₦8,950"], A,
      "Cost of sales = ₦10,000 − 20% gross profit (₦2,000) = ₦8,000; purchases = ₦8,000 − opening stock ₦250 + closing stock ₦200 = ₦7,950."),
    q("Use the following information: \nJejelaye Plc stock records for 2009 were given below:\nJan 1 ... received 100 units at ₦1.00\nJan 8 ... received 260 units at ₦1.05\nJan 20 ... issued 300 units at .........\nFeb 3 ... received 400 units at ₦1.15\n\nWhat will be the issue price of the units issued on Jan 20, using simple average method?",
      ["₦1.183", "₦1.025", "₦1.00", "₦1.05"], B,
      "Simple average uses the unit prices of the batches in stock at the date of issue, ignoring quantities: (₦1.00 + ₦1.05) ÷ 2 = ₦1.025; the Feb 3 batch has not yet arrived."),
    q("Which of the following is not a feature of accounting information?",
      ["timeliness", "accuracy", "completeness", "affordability"], D,
      "Useful accounting information should be timely, accurate (reliable) and complete; affordability is not one of its qualities."),
    q("The accounting concept which assumes that a business will continue to be in existence into the foreseeable future is",
      ["periodicity", "business entity", "dual aspect", "going concern"], D,
      "The going concern concept assumes the business will continue operating for the foreseeable future, which is why assets are shown at cost less depreciation rather than at break-up value."),
    q("The purpose of a trading account is to ascertain",
      ["sales", "carriage outwards", "gross profit or loss", "net profit or loss"], C,
      "The trading account compares net sales with the cost of goods sold to find the gross profit or loss; net profit is found in the profit and loss account."),
    q("The document setting out the regulations regarding shares, meetings and internal organization of a company is known as",
      ["memorandum of association", "article of association", "prospectus", "company law"], B,
      "The articles of association are the internal rules of a company: shares, meetings, directors and management; the memorandum governs the company's dealings with the outside world."),
    q("An entry in a subsidiary book which does not form part of the double entry system is a",
      ["contra entry", "journal entry", "single entry", "memorandum entry"], D,
      "A memorandum entry is recorded for information only and is not part of the double entry, for example the discount columns of the cash book."),
    // paper 41–50
    q("Income and expenditure account is more informative than receipts and payments account because it discloses",
      ["cash", "cheques", "debtors", "stocks"], C,
      "The income and expenditure account is prepared on the accruals basis, so it includes amounts owing to the club, such as subscriptions in arrears (debtors), which a receipts and payments account ignores.",
      { bookletKey: 'B', bookletNote: "The booklet answer B (cheques) cannot be right: cheques are just a way of receiving or paying money and appear in both accounts. The income and expenditure account is more informative because, on the accruals basis, it includes amounts owing such as subscriptions in arrears (debtors), C." }),
    q("Use the following information: \nDangote acquired Dantata's business for ₦350,000. The total asset worth was ₦820,000 and liabilities amounted to ₦640,000.\n\nThe double entry to record the goodwill in the books is debit",
      ["purchase of business account and credit cash account", "goodwill account and credit purchase of business account", "cash account and credit goodwill account", "goodwill account and credit cash account"], B,
      "Goodwill = ₦350,000 − net assets (₦820,000 − ₦640,000 = ₦180,000) = ₦170,000; it is recorded by debiting goodwill account and crediting purchase of business account."),
    q("Sales ledger control account contains the total amount in respect of",
      ["creditors", "debtors", "investors", "shareholders"], B,
      "The sales ledger holds the customers' (debtors') accounts, so its control account summarises the total amounts owed by debtors."),
    q("One of the differences between bookkeeping and accounting is that the former ____.",
      ["records data while the latter interprets", "is regarded as the language of the business while the latter ascertains its strength", "interprets data while the latter records it", "summarizes information while the latter communicates it"], A,
      "Bookkeeping is the recording stage; accounting goes further to summarise, analyse and interpret the recorded data for users."),
    q("A book of account that possesses the features of both day book and ledger is ____.",
      ["sales day book", "cash book", "purchases day book", "returns day book"], B,
      "The cash book is a book of original entry for cash and bank transactions and also serves as the cash and bank accounts of the ledger."),
    q("Cash discounts are often recorded on",
      ["the debit side of the cash book", "the credit side of the cash book", "the folio column of the cash book", "both credit and debit side of the cash book"], D,
      "In a three-column cash book, discount allowed is recorded on the debit side (with receipts) and discount received on the credit side (with payments)."),
    q("The federal government approved ₦140m to local governments W, X, Y and Z. The amount is to be shared on the basis of 40% equality, 30% population and 25% internal revenue generation. Calculate the share of local government W on equality.",
      ["35m", "14m", "56m", "28m"], B,
      "Equality pool = 40% × ₦140m = ₦56m, shared equally among four local governments: ₦56m ÷ 4 = ₦14m.",
      { bookletKey: 'C', bookletNote: "The booklet answer C (56m) is the whole equality pool for all four local governments (40% × ₦140m). Shared equally among W, X, Y and Z, W's share is ₦56m ÷ 4 = ₦14m, B." }),
    q("Commission-on-turnover is charged on",
      ["current accounts only", "savings accounts only", "fixed deposit accounts only", "all bank accounts"], A,
      "Commission on turnover was a bank charge on the debit turnover of current accounts; savings and fixed deposit accounts do not attract it (it has since been replaced by an account maintenance fee)."),
    q("The movement of goods from head office to a branch is treated in the head office accounts as",
      ["requisition", "purchases", "issue", "sale"], C,
      "Goods sent to a branch are an internal transfer (issue) recorded in a goods sent to branch account, not a sale, because the business still owns them."),
    q("When assets are realized during a partnership dissolution, the entries for the proceeds are to debit",
      ["asset account and credit cash account", "realisation account and credit cash account", "asset account and credit realisation account", "cash account and credit realisation account"], D,
      "On dissolution the assets are first transferred to the realisation account; the cash received on selling them is debited to cash and credited to the realisation account."),
  ]);
})();
