/**
 * JAMB/UTME 2007 — PRINCIPLES OF ACCOUNTS
 * From the 2007 question paper (questions 1–50); answers from the JAMB/UTME Accounts answer key 2001–2020,
 * each checked independently. Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2007;
  const SRC = 'JAMB UTME 2007';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const CLUB = "Use the following information: \nEntrance fees ... ₦1,200\nSubscriptions (including ₦850 arrears) ... ₦4,310\nDonations received ... ₦1,500\nProceeds from sales ... ₦2,300\nTotal payments ... ₦8,200\nDepreciation ... ₦2,100\nClosing cash balance ... ₦1,110\nThe club deposited 200% of the closing cash balance in the bank during the period.\n\n";
  const BRANCH = "Use the following information: \nStock (1/1/02) at selling price ... ₦2,000\nGoods sent to branch (selling price) ... ?\nSales by branch (selling price) ... ₦4,500\nStock (31/12/02) ... ?\nOpening stock is ¼ of goods sent to branch.\n\n";
  const SHARES = "Use the following information: \nA company's authorized share capital was one million ordinary shares at ₦1 each. It issued 80% of its shares at ₦1.10 per share. 70k was payable on application, 25k on allotment, 10k due on first call and the balance on second call.\n\n";
  const APPORT = "Use the following information: \nLighting ... ₦2,925\nRent ... ₦2,640\nSalary ... ₦4,050\nThe expenses are for three different products: Zema, Zeta and Zera. They are apportioned on the basis of production. 4500 units of the products are produced, out of which 1260 and 2060 units are for Zema and Zeta respectively.\n\n";
  const ASSET = "Use the following information: \nAn asset was purchased for ₦343m in 2003. The estimated life of the asset was 3 years with a residual value of ₦28m.\n\n";
  const CAP = "Use the following information: \n... 1/7/2005 ... 30/6/2006\nDrawings ... — ... ₦3,000\nCapital ... ₦25,000 ... ₦42,500\nFurniture and fittings ... ₦6,500 ... ₦10,200\nAdditional capital during the year amounts to 300% of the drawings.\n\n";
  const PROV = "Use the following information: \nDebtors ... ₦20,000\nProvision for bad debts ... 10%\nProvision for discount on debtors ... 5%\n\n";
  const LOSS = "Use the following information: \nNet loss ... ₦2,300\nCapital ... ₦10,500\nLiability ... ₦7,200\n\n";
  const BANK = "Use the following information: \nBalance as per cash book ... ₦13,600\nUnpresented cheques ... ₦5,120\nUncredited lodgements ... ₦2,300\nDividend received not entered in the cash book ... ₦2,000\nBank charges ... ₦280\nStanding order payments ... ₦600\nBalance as per bank statement ... ?\n\n";
  const TB = "Use the following information: \nReturns inwards ... ₦1,500\nCash ... ₦1,550\nDiscount received ... ₦2,850\nCapital ... ₦3,800\nDebtors ... ₦900\nSundry expenses ... ?\nThe value of sundry expenses is 150% of returns inwards plus 50% of debtors.\n\n";

  QUESTION_BANK.accounting = QUESTION_BANK.accounting.concat([
    // paper 1–10
    q("A company has departments X, Y and Z. Department X occupies a space twice that of Y while Z occupies half the space of Y. If the company pays ₦70,000 on rent, what is the amount of rent that should be allocated to Y?",
      ["₦30,000", "₦40,000", "₦20,000", "₦10,000"], C,
      "Taking Y's space as 1, X is 2 and Z is ½, a total of 3½ parts; Y's rent = ₦70,000 ÷ 3.5 = ₦20,000."),
    q(CLUB + "Calculate the total figure for the receipts and payments account",
      ["₦11,410", "₦13,630", "₦9,310", "₦11,530"], D,
      "Total payments ₦8,200 + bank deposit (200% × ₦1,110 = ₦2,220) + closing cash ₦1,110 = ₦11,530; depreciation is not a cash item."),
    q(CLUB + "Determine the opening cash balance of the club",
      ["₦3,070", "₦2,220", "₦5,710", "₦4,320"], B,
      "Receipts are ₦1,200 + ₦4,310 + ₦1,500 + ₦2,300 = ₦9,310, so opening cash = ₦11,530 − ₦9,310 = ₦2,220."),
    q("Given: \nStock at start:\nRaw materials ... ₦57,000\nWork-in-progress ... ₦42,000\nFinished goods ... ₦71,000\nPurchases of raw materials amount to ₦81,000, direct labour is ₦38,000 and factory overhead ₦29,000.\n\nCalculate the prime cost",
      ["₦176,000", "₦170,000", "₦167,000", "₦156,000"], A,
      "Prime cost = raw materials used (₦57,000 + ₦81,000 = ₦138,000, no closing stock given) + direct labour ₦38,000 = ₦176,000; factory overhead and work-in-progress come after prime cost."),
    q("I. Profits and losses will be shared unequally. II. Interest is not allowed on capital. III. Salaries are not allowed. IV. Interest is charged on drawings. From the above, which of the following would apply where there is no agreement during partnership formation?",
      ["I only", "I, II and III", "I, II and IV", "II and III"], D,
      "Under the Partnership Act 1890, with no agreement profits and losses are shared equally, and there is no interest on capital, no salaries and no interest on drawings; only II and III apply.",
      { bookletKey: 'C', bookletNote: "The booklet answer C includes I and IV, but with no agreement the Partnership Act 1890 says profits are shared equally (not unequally) and no interest is charged on drawings. Only II (no interest on capital) and III (no salaries) apply, so D is right." }),
    q(BRANCH + "The value of goods sent to branch is",
      ["₦4,000", "₦6,000", "₦8,000", "₦2,000"], C,
      "Opening stock ₦2,000 is ¼ of goods sent, so goods sent = ₦2,000 × 4 = ₦8,000."),
    q(BRANCH + "Determine the closing stock",
      ["₦5,500", "₦66,500", "₦2,500", "₦4,500"], A,
      "Closing stock = opening stock ₦2,000 + goods sent ₦8,000 − sales ₦4,500 = ₦5,500 (all at selling price)."),
    q("Expenses paid during the conversion of partnership to a company are",
      ["debited to a company account", "debited to the partner's capital account", "debited to the cash account", "credited to the realization account"], D,
      "Expenses of converting (realising) a partnership are charged to the realisation account: debit realisation account, credit cash.",
      { keyVerdict: 'none', keyAnswer: 'D', answerNote: "JAMB's answer is D, but it is not fully correct: realisation expenses are DEBITED to the realisation account (and credited to cash), not credited. D is the only option that names the right account; none of the options gives the right entry as printed." }),
    q("Given: Receipts and payments Account\nBal. b/f ... ₦1,000 | Salaries ... ₦5,000\nDonations ... ₦5,000 | Secretariat (Expenses) ... ₦5,000\nSubscriptions ... ₦7,000 | Dance expenses ... ₦5,000\nSales of refreshment ... ₦11,000 | Refreshment ... ₦15,000\nEntertainment ... ₦21,000 | Bal. c/d ... ₦15,000\nTotal ... ₦45,000 | Total ... ₦45,000\n\nCalculate the surplus income.",
      ["₦45,000", "₦44,000", "₦30,000", "₦14,000"], D,
      "Income ₦5,000 + ₦7,000 + ₦11,000 + ₦21,000 = ₦44,000 less expenditure ₦5,000 + ₦5,000 + ₦5,000 + ₦15,000 = ₦30,000 gives a surplus of ₦14,000; the cash balances are not income."),
    q("In the trading and profit and loss account of a manufacturing organisation, purchases is",
      ["always the same amount as the total factory overhead cost", "given separately", "equivalent to the total cost of goods manufactured", "always the same as the prime cost"], C,
      "In a manufacturer's trading account the cost of goods manufactured (production cost) from the manufacturing account takes the place of purchases.",
      { keyVerdict: 'corrected', keyAnswer: 'B', answerNote: "JAMB's key gives B (given separately). In a manufacturing business, raw material purchases go into the manufacturing account, and the trading account uses the cost of goods manufactured where a trader would show purchases, so C is the standard answer. B could only fit if finished goods were also bought in and shown separately, which the question does not say." }),
    // paper 11–20
    q("Goods worth ₦50,000 were sent at different times from head office to the branch during the year. By the end of the period, only ₦40,000 worth of goods had arrived at the branch. Which of the following is correct about the treatment of this transaction?",
      ["Branch should debit goods received from head office with ₦50,000", "Head office should debit goods sent to branch account with ₦10,000", "Head office should debit goods sent to branch account with ₦50,000", "Branch should debit goods received from head office with ₦10,000"], D,
      "Head office has already recorded all ₦50,000 sent; the ₦10,000 in transit is adjusted in the branch books by debiting goods received from head office (goods in transit) with ₦10,000 and crediting the head office account.",
      { keyVerdict: 'corrected', keyAnswer: 'B', answerNote: "JAMB's key gives B, but head office has correctly recorded all ₦50,000 of goods sent, so it has nothing to reverse. The goods in transit are brought into the branch books: the branch debits goods received from head office (goods in transit) with the missing ₦10,000 and credits head office, so the two sets of books agree. That is D." }),
    q("An accounting ratio that considers only quick assets to determine the short-term safety margin of a firm is the",
      ["fixed assets ratio", "capital gearing ratio", "current assets ratio", "acid test ratio"], D,
      "The acid test (quick) ratio compares quick assets (current assets less stock) with current liabilities."),
    q(SHARES + "What would be the total amount received on second call?",
      ["₦240,000", "₦280,000", "₦40,000", "₦56,000"], C,
      "800,000 shares were issued at ₦1.10; 70k + 25k + 10k = ₦1.05 is called before, leaving 5k on second call: 800,000 × ₦0.05 = ₦40,000."),
    q(SHARES + "The total amount of money received on application was",
      ["₦560,000", "₦200,000", "₦40,000", "₦56,000"], A,
      "80% of 1,000,000 = 800,000 shares; 800,000 × 70k = ₦560,000."),
    q("Given: Shaku Company Ltd.\nStock ... ₦3,600,000\nCash at hand ... ₦800,000\nCash in bank ... ₦2,400,000\nDebtors ... ₦580,000\nTrade creditors ... ₦920,000\nBank overdraft ... ₦200,000\nTax liability ... ₦600,000\nSalary owed to staff ... ₦180,000\n\nDetermine the working capital.",
      ["₦7,380,000", "₦8,480,000", "₦5,480,000", "₦6,480,000"], C,
      "Current assets ₦7,380,000 less current liabilities ₦1,900,000 = ₦5,480,000."),
    q("The receipts and payments account of a not-for-profit-making organization plays a similar role in a profit-making organization as",
      ["a cash account", "a balance sheet", "an income account", "an expenses account"], A,
      "A receipts and payments account is a summary of the cash book, so it does the job of a cash account."),
    q("Osei and Yabo were in partnership sharing profits and losses in the ratio of 3:2. On admitting Takwa, the profit and loss sharing ratio was changed to 1:1:1. Suppose Takwa paid ₦30,000 for goodwill, this amount would be",
      ["credited to Takwa's current account", "debited to goodwill account", "shared to all the partners' capital account", "credited to the old partners' capital account"], D,
      "Cash paid in by a new partner for goodwill is debited to cash and credited to the old partners' capital accounts in the ratio in which they give up their shares (sacrificing ratio).",
      { bookletKey: 'B', bookletNote: "The booklet answer B would be right only if a goodwill account were being opened. Here Takwa pays cash for goodwill, so the entry is debit cash ₦30,000 and credit the old partners' capital accounts (Osei ₦24,000 and Yabo ₦6,000, in the sacrificing ratio 4:1), which is D." }),
    q("The amount of subscriptions accrued is reported in the balance sheet under",
      ["fixed asset", "long-term liability", "current asset", "current liability"], C,
      "Subscriptions accrued (in arrears) are income earned but not yet received, money owed to the club by members, so they are a current asset.",
      { bookletKey: 'D', bookletNote: "The booklet answer, current liability, fits subscriptions paid in advance. Subscriptions accrued (in arrears) are owed to the club by members, like debtors, so they are a current asset (C)." }),
    q(APPORT + "The lighting charge to be apportioned to Zema is",
      ["₦891", "₦819", "₦927", "₦975"], B,
      "₦2,925 × 1,260 ÷ 4,500 = ₦819."),
    q(APPORT + "Find the salary charged to Zera product",
      ["₦1,854", "₦1,845", "₦1,062", "₦1,134"], C,
      "Zera produced 4,500 − 1,260 − 2,060 = 1,180 units; ₦4,050 × 1,180 ÷ 4,500 = ₦1,062."),
    // paper 21–30
    q("The gross profit disclosed in the branch stock adjustment account represents",
      ["head office profit", "unrealized profit", "estimated profit", "branch profit"], D,
      "The branch stock adjustment (mark-up) account collects the loading on goods sent; after removing the unrealised loading on closing stock, its balance is the branch gross profit."),
    q("Partners' share of profit is credited to",
      ["a partner's current account", "a partner's capital account", "the profit and loss account", "the profit and loss appropriation account"], A,
      "Each partner's share of profit is credited to his current account (capital accounts are kept fixed)."),
    q("A pension granted to any past president or vice-president shall be charged to the",
      ["consolidated revenue fund", "special pension fund", "contingency fund", "development fund"], A,
      "The 1999 Constitution (section 84) makes pensions granted to former Presidents and Vice-Presidents a charge on the Consolidated Revenue Fund of the Federation.",
      { bookletKey: 'B', bookletNote: "The booklet answer, special pension fund, is not what the law says. Section 84 of the 1999 Constitution makes any pension granted to a former President or Vice-President a charge on the Consolidated Revenue Fund (A)." }),
    q("The federal government approved ₦140m to local governments W, X, Y and Z. The amount is to be shared on the basis of 40% equality, 30% population and 25% internal revenue generation. Calculate the share of local government W on equality.",
      ["₦35m", "₦14m", "₦56m", "₦28m"], B,
      "The equality share is 40% × ₦140m = ₦56m, split equally among the four councils: ₦56m ÷ 4 = ₦14m for W.",
      { bookletKey: 'C', bookletNote: "The booklet answer ₦56m is the whole equality pool for all four councils (40% × ₦140m). Shared equally, W gets ₦56m ÷ 4 = ₦14m (B)." }),
    q("Stock valuation is useful because it informs the sales department on the",
      ["prices of the competing goods", "prices that will affect profitability", "number of goods to produce", "number of goods to sell"], B,
      "Knowing what the stock cost helps the sales department set selling prices that cover cost and give a profit."),
    q("Use the following information: \nSales Ledger Control Account (Extract)\nBal. b/d ... ₦18,400 | Bad debt written off ... ₦1,500\nSales ... ? | Discount allowed ... ₦500\n | Cheque received from debtors ... ₦25,000\n | Cash received from debtors ... ₦10,000\n | Bal. c/d ... ?\n\nIf the discount allowed is 2.5% of sales, calculate the closing balance in the sales ledger account.",
      ["₦1,400", "₦6,600", "₦16,600", "₦18,600"], A,
      "Sales = ₦500 ÷ 2.5% = ₦20,000; debits ₦18,400 + ₦20,000 = ₦38,400 less credits ₦1,500 + ₦500 + ₦25,000 + ₦10,000 = ₦37,000 leaves ₦1,400."),
    q(ASSET + "Using the straight-line method, the depreciation of the asset in the first year was",
      ["₦210m", "₦343m", "₦105m", "₦270m"], C,
      "Annual depreciation = (₦343m − ₦28m) ÷ 3 = ₦105m."),
    q(ASSET + "What was the asset value at the beginning of the third year?",
      ["₦63m", "₦133m", "₦36m", "₦28m"], B,
      "At the start of year 3 two years' depreciation has been charged: ₦343m − (2 × ₦105m) = ₦133m.",
      { bookletKey: 'D', bookletNote: "The booklet answer ₦28m is the residual value, which the asset reaches only at the END of the third year. At the beginning of the third year two years' depreciation has been charged: ₦343m − 2 × ₦105m = ₦133m (B)." }),
    q("Given: \nOpening capital ... ₦7,000\nAdditional capital ... ₦3,500\nNet profit ... ₦2,500\nClosing capital ... ₦10,250\n\nThe drawings for the period stand at?",
      ["₦2,750", "₦3,750", "₦2,500", "₦2,570"], A,
      "Drawings = ₦7,000 + ₦3,500 + ₦2,500 − ₦10,250 = ₦2,750."),
    q(CAP + "Calculate the net profit or loss made during the year.",
      ["₦15,100 profit", "₦15,100 loss", "₦11,500 profit", "₦11,500 loss"], C,
      "Profit = closing capital ₦42,500 − opening ₦25,000 − additional capital ₦9,000 + drawings ₦3,000 = ₦11,500; it is positive, so it is a profit.",
      { bookletKey: 'D', bookletNote: "The booklet answer is ₦11,500 loss, but the figure comes out positive: ₦42,500 − ₦25,000 − ₦9,000 + ₦3,000 = +₦11,500. Capital grew by more than the new capital paid in less drawings, so the business made a profit (C)." }),
    // paper 31–40
    q(CAP + "What is the amount of the additional capital?",
      ["₦900", "₦900,000", "₦90,000", "₦9,000"], D,
      "Additional capital = 300% × drawings ₦3,000 = ₦9,000."),
    q("I. Facilitating the preparation of final account; II. Making the existence of error easy to detect III. Checking the accuracy of posting periodically. From the above, which of the followings are among the use of control accounts?",
      ["I, II and III", "I and III", "II and III", "I and II"], A,
      "Control accounts check the arithmetical accuracy of the ledgers, help locate errors, and give the total debtors and creditors quickly for the trial balance and final accounts; all three are uses.",
      { keyVerdict: 'corrected', keyAnswer: 'C', answerNote: "JAMB's key gives C (II and III). Standard textbooks also list giving the total of debtors and creditors quickly, so that the trial balance and final accounts can be prepared without adding every personal account, as a use of control accounts, so statement I is true as well and A (I, II and III) is the better answer." }),
    q(PROV + "Determine the amount provided for discount allowed on debtors",
      ["₦1,000", "₦3,000", "₦900", "₦1,500"], C,
      "The discount provision is worked on debtors after the bad debts provision: 5% × (₦20,000 − ₦2,000) = ₦900.",
      { bookletKey: 'A', bookletNote: "The booklet answer ₦1,000 takes 5% of the full ₦20,000. Debtors expected to go bad will pay nothing and earn no discount, so the provision for discount is worked on ₦20,000 − ₦2,000 = ₦18,000: 5% × ₦18,000 = ₦900 (C)." }),
    q(PROV + "The provision for bad debts is",
      ["₦2,000", "₦800", "₦3,000", "₦1,900"], A,
      "10% × ₦20,000 = ₦2,000."),
    q("Given: \nPrepaid b/f ... ₦10,000\nCash paid during the year ... ₦20,000\nPrepaid c/f ... ₦5,000\n\nThe amount to be charged to the profit and loss account is",
      ["₦30,000", "₦25,000", "₦5,000", "₦20,000"], B,
      "Charge = prepaid brought forward ₦10,000 + cash paid ₦20,000 − prepaid carried forward ₦5,000 = ₦25,000."),
    q("The purchases ledger control account showed a credit balance of ₦525,000 on April 30, 2006. This amount shows",
      ["what the debtors of a business enterprise owed the business", "the total amount which each debtor owed the business", "what a business enterprise owed its creditors", "the total amount which a business enterprise owed each creditor"], C,
      "The credit balance on the purchases ledger control account is the total owed to all creditors (suppliers) at that date."),
    q(LOSS + "Find the value of the total assets?",
      ["₦17,700", "₦10,500", "₦20,000", "₦15,400"], D,
      "Capital after the loss = ₦10,500 − ₦2,300 = ₦8,200; assets = capital + liabilities = ₦8,200 + ₦7,200 = ₦15,400."),
    q(LOSS + "What will be the equity of the business?",
      ["₦12,800", "₦4,900", "₦8,200", "₦9,500"], C,
      "Equity = capital ₦10,500 less the net loss ₦2,300 = ₦8,200."),
    q("Journal proper is used in recording",
      ["transactions that are not regular", "returns from customers", "credit sales", "the receipt and payment of money"], A,
      "The journal proper records unusual entries that no other book of original entry covers: opening entries, corrections, credit purchase of fixed assets, write-offs."),
    q("The process whereby a cheque received by one person is given to another for payment is known as",
      ["cheque crossing", "payment in cheque", "cheque transfer", "cheque endorsement"], D,
      "Endorsement is signing the back of a cheque so that it can be passed on to another person, who can then receive payment.",
      { bookletKey: 'C', bookletNote: "'Cheque transfer' is not the name of the process. A cheque is passed on to another person by endorsing it (signing on the back), so the answer is cheque endorsement (D)." }),
    // paper 41–50
    q(BANK + "Calculate the balance in the bank statement.",
      ["₦10,740", "₦11,860", "₦17,540", "₦16,380"], C,
      "Adjusted cash book ₦14,720 + unpresented cheques ₦5,120 − uncredited lodgements ₦2,300 = ₦17,540."),
    q(BANK + "What is the adjusted cash book balance?",
      ["₦14,720", "₦15,560", "₦16,440", "₦17,000"], A,
      "₦13,600 + dividend ₦2,000 − bank charges ₦280 − standing order ₦600 = ₦14,720."),
    q("Given: Sales Ledger\nBal. b/d ... ₦20,000 | Sales return ... ₦10,000\nSales ... ₦40,000 | Discount allowed ... ₦1,000\n | Bal. c/d ... ?\n\nIf cheques of ₦40,000 were received but a cheque of ₦8,000 was dishonoured, the amount owed was",
      ["₦9,000", "₦20,000", "₦1,000", "₦17,000"], D,
      "Balance = ₦20,000 + ₦40,000 − ₦10,000 − ₦1,000 = ₦49,000; less cheques ₦40,000 plus the dishonoured ₦8,000 = ₦17,000."),
    q("The fourth stage of the accounting information system is",
      ["recording", "interpreting", "summarising", "classifying"], C,
      "The accounting process runs: identifying (collecting) transactions, recording, classifying, summarising, then interpreting and communicating; summarising is the fourth."),
    q(TB + "How much is sundry expenses?",
      ["₦2,700", "₦2,250", "₦1,550", "₦2,000"], A,
      "150% × ₦1,500 + 50% × ₦900 = ₦2,250 + ₦450 = ₦2,700."),
    q(TB + "The total of the trial balance is",
      ["₦6,600", "₦6,650", "₦5,600", "₦5,900"], B,
      "Debits: ₦1,500 + ₦1,550 + ₦900 + ₦2,700 = ₦6,650; credits: discount received ₦2,850 + capital ₦3,800 = ₦6,650."),
    q("If Mr. Ajasin paid his creditors ₦5,000 out of ₦20,000 owed, what would be the effect of this transaction on the accounting equation?",
      ["A decrease in the total liabilities and assets by ₦5,000", "An increase in total liabilities and owner's equity by ₦15,000", "An increase in the total assets by ₦15,000", "A decrease in owners' equity by ₦5,000"], A,
      "Paying a creditor reduces cash (an asset) and creditors (a liability) by the same ₦5,000; capital is unchanged."),
    q("One of the benefits of book-keeping records is that they",
      ["give prospective investors accurate and direct information for decision-making", "provide the public and creditors with details of the operations of an entity", "give legal backing to all the transactions undertaken by a business entity", "provide information without which the task of management would be difficult"], A,
      "Proper records give reliable information for decisions by investors and by management.",
      { keyVerdict: 'multiple', alsoAccept: [D], keyAnswer: 'A', answerNote: "Option D is also correct. Book-keeping records are the main source of the information managers use to plan and control the business, so D is as much a benefit as A. Both are accepted." }),
    q("Given: \nBank overdraft ... ₦2,000\nCash ... ₦2,000\nFurniture ... ₦4,000\n\nCalculate the total amount on the credit side of the trial balance.",
      ["₦4,000", "₦2,000", "₦6,000", "₦8,000"], B,
      "Of the balances given, only the bank overdraft (money owed to the bank) is a credit balance, ₦2,000; cash and furniture are assets and go on the debit side."),
    q("A sole trader purchased goods in cash worth ₦2,000 at 2% discount and made a cash sale of ₦1,000 at the same rate of discount. Determine the amount of discount allowed.",
      ["₦20", "₦40", "₦400", "₦200"], A,
      "Discount allowed is the discount given to the customer on the ₦1,000 sale: 2% × ₦1,000 = ₦20; the ₦40 on purchases is discount received."),
  ]);
})();
