/**
 * JAMB/UTME 2006 — PRINCIPLES OF ACCOUNTS
 * From the 2006 question paper (questions 1–50); answers from the JAMB/UTME Accounts answer key
 * 2001–2020, each checked independently. Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2006;
  const SRC = 'JAMB UTME 2006';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const MACHINE = "Use the following information: \nOn January 1, 2005, a machine was bought for ₦56,000 to last for 5 years with a residual value of ₦1,000.\n\n";
  const BAL = "Use the following information: \nCapital ... ₦?\nProfit and loss ... ₦3,500\nCurrent assets ... ₦?\nCurrent liabilities ... ₦2,000\nFixed assets ... ₦11,000\nThe company maintains a current ratio of 3:1.\n\n";
  const STOCK = "Use the following information: \nDate ... Stock ... Qty (units) ... Cost/Price (₦)\nJul. ... Bal. b/d ... 2,000 ... 2.00\nAug. ... Purchases ... 10,000 ... 2.50\nSept. ... Purchases ... 20,000 ... 3.00\nOct. ... Sales ... 8,000 ... 3.50\nNov. ... Sales ... 23,000 ... 4.00\n\n";
  const APPROP = "Use the following information: \nTurnover ... ₦120,000\nNet profit before tax ... ₦40,000\nNet profit b/f ... ₦68,000\nProposed dividends:\n  Ordinary shares ... ₦8,000\n  Preference shares ... ₦6,000\nGeneral reserves ... ₦10,000\nCorporate tax is 50%\n\n";
  const BANKST = "Use the following information: \nS. Danbuzu's Bank Statement\nDate ... Particulars ... Debit ... Credit ... Balance\nJan. 1 ... Opening balance ... – ... – ... 10,000\nJan. 3 ... Bashir A. K. ... 1,000 ... – ... 9,000\nJan. 10 ... Usman A. D. ... 1,500 ... – ... 7,500\nJan. 12 ... Sule A. S. ... 500 ... – ... 7,000\nJan. 20 ... Aliyu A. K. ... – ... 3,000 ... 10,000\nJan. 30 ... X ... 1,500 ... – ... Y\n\n";
  const CASHBK = "Use the following information: \nKhalifa's Cash Book\nDebit side (Date ... Particulars ... Cash ... Bank ... Discount):\n1/1 ... Bal. b/d ... 4,000 ... 5,000 ... –\n1/3 ... Khadijah ... – ... 3,000 ... –\n1/10 ... Sales ... 1,000 ... 1,500 ... 400\n1/29 ... Sales ... 800 ... – ... –\nCredit side (Date ... Particulars ... Cash ... Bank ... Discount):\n1/11 ... A. Lilisco ... 200 ... – ... –\n1/15 ... NEPA bill ... 500 ... – ... –\n1/28 ... Purchases ... 1,500 ... – ... 200\nOn January 30th, Khalifa withdrew ₦2,500 from the bank for office use.\n\n";
  const TB = "Use the following information: \nCapital ... ₦60,000\nBank ... ₦12,500\nGeneral expenses ... ₦5,250\nCreditors ... ₦8,025\nStock ... ₦17,150\nSales ... ₦98,500\nFixed assets ... ₦42,800\nInsurance and rates ... ₦18,500\nPurchases ... ₦63,850\n\n";
  const DEPT = "Use the following information: \n... Stationery Dept. ... Video Dept.\nSales ... ₦10,600 ... ₦15,175\nCost of goods sold ... ₦5,247 ... ₦6,704\nThe expenses incurred were rent ₦4,500, motor repairs ₦1,200 and telephone ₦900. The basis of cost apportionment is stationery 2/3 and video 1/3.\n\n";
  const OVH = "Use the following information: \nPrime cost ... ₦12,100\nLighting ... ₦10,000\nHeating ... ₦15,000\nFactory overhead ... ?\nThe production department share of factory overhead is 1/4 and 1/5 of lighting and heating respectively.\n\n";
  const LOAN = "Use the following information: \nMotor van ... ₦10,000\nFixtures ... ₦5,000\nCash ... ₦2,500\nCreditors ... ₦7,000\nLoan ... ?\nLoan is 30% of creditors.\n\n";
  const RP = "Use the following information: \nReceipts and Payments Account\nReceipts: Balance b/d ... ?\nSubscriptions received ... ?\nGate-fee collections ... ₦50,000\nPayments: Rent and rates ... ₦30,000\nGeneral expenses ... ₦100,000\nElectricity ... ₦20,000\nInsurance ... ₦150,000\nBalance c/d ... ?\nThe subscriptions received represent 80% of total payments and the opening balance is 30% of gate-fee collections.\n\n";

  QUESTION_BANK.accounting = QUESTION_BANK.accounting.concat([
    // paper 1–10
    q("Fatima withdraws goods from the business for personal use. The accounting treatment is to debit",
      ["stock account and credit profit and loss account", "drawings account and credit stock account", "profit and loss account and credit drawings account", "stock account and credit drawings account"], B,
      "Goods taken by the owner reduce the business's capital, so drawings is debited, and the goods leave the business, so stock (or purchases) is credited."),
    q(MACHINE + "Calculate the yearly depreciation expense using the straight line method.",
      ["11,000", "11,200", "11,400", "11,300"], A,
      "Straight line depreciation = (cost − residual value) ÷ useful life = (₦56,000 − ₦1,000) ÷ 5 = ₦11,000 a year."),
    q(MACHINE + "The rate of the yearly depreciation expense would be",
      ["50%", "40%", "30%", "20%"], D,
      "A 5-year life written off equally means 1/5 of the depreciable amount each year: ₦11,000 ÷ ₦55,000 = 20%."),
    q("The objective of the purchases ledger control account is to establish the",
      ["credit purchases", "net profit", "total purchases", "gross profit"], A,
      "The purchases ledger control account summarises dealings with credit suppliers, so it shows total credit purchases and the total owed to creditors; cash purchases never pass through it.",
      { keyVerdict: 'corrected', keyAnswer: 'C', answerNote: "The answer key gives 'total purchases', but the purchases ledger control account records only credit purchases (and payments, returns and discounts with credit suppliers). Cash purchases never enter it, so it cannot show total purchases; 'credit purchases' is the better answer." }),
    q("The objective of a trading account is to establish the",
      ["cost of goods sold", "gross profit", "manufacturing profit", "net profit"], B,
      "The trading account compares sales with the cost of goods sold to find the gross profit (or loss) on trading."),
    q("A seller of vegetables and fruits should be encouraged to value his stock at the end of the period using the",
      ["weighted average method", "simple average method", "FIFO method", "LIFO method"], C,
      "Perishable goods are sold in the order they are bought, so First In, First Out matches the physical flow and leaves the freshest (latest) goods in closing stock (now called inventory under IFRS)."),
    q(BAL + "The capital balance is",
      ["₦9,500", "₦12,500", "₦11,500", "₦10,000"], C,
      "Current assets = 3 × ₦2,000 = ₦6,000; net assets = ₦11,000 + ₦6,000 − ₦2,000 = ₦15,000 = capital + profit ₦3,500, so capital = ₦11,500."),
    q(BAL + "Determine the current assets.",
      ["₦7,000", "₦6,000", "₦8,000", "₦9,000"], B,
      "Current ratio = current assets ÷ current liabilities = 3, so current assets = 3 × ₦2,000 = ₦6,000."),
    q("The difference in the sales ledger control account is transferred to the",
      ["profit and loss account", "sales account", "balance sheet", "trading account"], C,
      "The balance (difference between the two sides) of the sales ledger control account is the total owed by debtors, which is shown as a current asset in the balance sheet (today called the statement of financial position)."),
    q("Tunde purchased goods from Femi by cash worth ₦1,000 with 10% cash discount. Tunde's purchases ledger control account is to be",
      ["debited by ₦100", "credited by ₦100", "credited by ₦1,000", "debited by ₦1,000"], A,
      "The 10% cash discount (₦100) is discount received; it reduces what is owed to the supplier, so it is debited to the purchases ledger control account.",
      { keyVerdict: 'none', keyAnswer: 'A',
        answerNote: "Strictly, a cash purchase never passes through the purchases ledger control account, because no creditor is created, so no option is fully correct. The question treats the ₦100 cash discount as discount received on a supplier's account, which is debited to the control account; on that reading A is right." }),
    // paper 11–20
    q(STOCK + "Assuming the closing stock was valued at ₦19,000 at the end of November, what was the gross profit?",
      ["₦30,000", "₦50,000", "₦70,000", "₦100,000"], B,
      "Sales = 8,000 × ₦3.50 + 23,000 × ₦4 = ₦120,000; cost of sales = ₦4,000 + ₦85,000 − ₦19,000 = ₦70,000; gross profit = ₦50,000."),
    q(STOCK + "Determine the value of closing stock using the LIFO method.",
      ["₦2,000", "₦2,500", "₦4,000", "₦3,500"], A,
      "32,000 units were available and 31,000 sold, leaving 1,000 units; under LIFO the units left are the earliest ones, the opening stock at ₦2.00, so closing stock = ₦2,000. Today IAS 2 (used in Nigeria under IFRS) no longer allows LIFO for inventory."),
    q("After receiving the financial statement, the Auditor-General of the Federation must submit a report to the National Assembly within",
      ["60 days", "30 days", "120 days", "90 days"], D,
      "Section 85(5) of the 1999 Constitution requires the Auditor-General to submit his report to each House of the National Assembly within 90 days of receiving the Accountant-General's financial statements."),
    q("Use the following information: \nGross earnings ... ₦950,000\nCurrent liabilities ... ₦100,000\nOperating expenses ... ₦350,000\n10% debentures ... ₦400,000\nShareholders' funds ... ₦1,300,000\nCorporate tax is 30%\n\nFrom the data above, calculate the returns on equity.",
      ["33%", "35%", "20%", "30%"], D,
      "Profit before tax = ₦950,000 − ₦350,000 − debenture interest ₦40,000 = ₦560,000; after 30% tax = ₦392,000; ₦392,000 ÷ ₦1,300,000 ≈ 30%."),
    q(APPROP + "The undistributed profit carried forward is",
      ["₦68,000", "₦20,000", "₦74,000", "₦34,000"], A,
      "Profit after 50% tax is ₦20,000; adding ₦68,000 brought forward gives ₦88,000, and deducting dividends ₦14,000 and the ₦10,000 transfer to general reserve leaves ₦64,000, which is not among the options.",
      { keyVerdict: 'none', keyAnswer: 'A', answerNote: "JAMB's answer is ₦68,000, but that is only the profit brought forward. Working it out: ₦40,000 − tax ₦20,000 = ₦20,000; + ₦68,000 b/f = ₦88,000; − dividends ₦14,000 − general reserve ₦10,000 = ₦64,000. No option shows ₦64,000 (₦74,000 would result only if the general reserve were not a transfer this year)." }),
    q(APPROP + "What is the tax charged to profit and loss account?",
      ["₦14,000", "₦60,000", "₦34,000", "₦20,000"], D,
      "Corporate tax is charged on the net profit before tax: 50% × ₦40,000 = ₦20,000."),
    q("Accrual accounting differs from cash accounting because it recognizes",
      ["cash and creditors", "debtors and creditors", "cash receipts and cash payments", "prepayment and cash"], B,
      "Under the accrual basis income and expenses are recorded when earned or incurred, not when cash moves, so amounts owed by debtors and to creditors are recognised."),
    q("A private company is different from a public company because",
      ["it does not restrict the right to transfer its shares", "it cannot invite members of the public to subscribe for its shares", "its shares are owned by one person", "it can only offer its shares to members of the public for subscription"], B,
      "A private company is forbidden to invite the public to subscribe for its shares or debentures, and it restricts the transfer of its shares; a public company may offer shares to the public. CAMA 2020 now also lets a private company have a single member, but that is allowed, not what makes it private."),
    q("The use of a three-column cash book is determined by",
      ["cash discounts", "trade discounts", "cash transactions", "bank transactions"], A,
      "The third (discount) column is added to the cash and bank columns to record cash discounts allowed and received; trade discounts are never entered in the books."),
    q("A major factor that enhanced the early development of accounting is the",
      ["Industrial Revolution", "growth of trade and commerce", "development of arithmetic", "invention of writing"], B,
      "As trade and commerce grew, merchants needed records of goods, debts and partners' shares, which led to bookkeeping and, in 1494, Pacioli's description of double entry."),
    // paper 21–30
    q(BANKST + "The value of Y is",
      ["₦11,500", "₦8,500", "₦13,000", "₦10,000"], B,
      "On a bank statement a debit reduces the customer's balance: ₦10,000 − ₦1,500 = ₦8,500."),
    q(BANKST + "X represents",
      ["bank charges", "an unpresented cheque", "dividends", "an uncredited cheque"], A,
      "X is a debit (deduction) made by the bank without a payee's name, which is typical of bank charges; dividends would be a credit, and unpresented or uncredited cheques do not yet appear on the statement."),
    q("Which of the following is a source document for the preparation of debtors' ledger control account?",
      ["Debit note", "General journal", "Purchases invoice", "Sales invoice"], D,
      "Credit sales recorded from sales invoices (through the sales day book) are the main debit entries in the debtors' (sales) ledger control account."),
    q(CASHBK + "The cash balance at the end of the month was",
      ["₦1,600", "₦4,100", "₦6,600", "₦6,100"], D,
      "Cash received ₦5,800 (₦4,000 + ₦1,000 + ₦800) less cash paid ₦2,200 (₦200 + ₦500 + ₦1,500) = ₦3,600, plus ₦2,500 withdrawn from the bank = ₦6,100."),
    q(CASHBK + "What was the bank balance at the end of the month?",
      ["₦7,000", "₦6,500", "₦7,500", "₦9,000"], A,
      "Bank receipts ₦9,500 (₦5,000 + ₦3,000 + ₦1,500) less the ₦2,500 withdrawn for office use = ₦7,000."),
    q("Stationery which will be used over a long period of time is usually recorded as an expense instead of an asset. This concept is called",
      ["entity", "materiality", "realization", "accrual"], B,
      "Under the materiality concept, items of small value are written off as expenses, because treating them as assets would cost more effort than the information is worth."),
    q("Adaobi mistakenly entered ₦7,000 as credit sales in Abba's account instead of Baba's account. This is",
      ["an error of principle", "a compensating error", "an error of commission", "an error of omission"], C,
      "Posting to the wrong personal account of the same class (one debtor instead of another) is an error of commission; it does not affect the trial balance."),
    q(TB + "What is the cash balance on the debit side if it is the only item omitted?",
      ["6,745", "6,754", "6,475", "6,574"], C,
      "Credits total ₦166,525 (capital, creditors, sales) and debits total ₦160,050, so the missing debit cash balance is ₦166,525 − ₦160,050 = ₦6,475."),
    q(TB + "Determine the total of the trial balance.",
      ["123,325", "160,050", "166,525", "326,575"], C,
      "The credit side is ₦60,000 + ₦8,025 + ₦98,500 = ₦166,525, and the debit side equals it once the cash balance of ₦6,475 is added."),
    q("Which of the following is a journal as well as a ledger?",
      ["Nominal ledger", "Sales day book", "General ledger", "Cash book"], D,
      "The cash book is a book of original entry (transactions are first recorded in it) and also the ledger account for cash and bank, so it is both a journal and a ledger."),
    // paper 31–40
    q("Use the following information: \nStock of raw materials 1/1/04 ... ₦11,150\nPurchases of raw materials ... ₦112,550\nRaw materials returned ... ₦31,150\nCarriage on raw materials ... ₦1,150\nStock of raw materials 31/12/04 ... ₦27,150\n\nCalculate the cost of raw materials consumed.",
      ["156,000", "38,300", "183,150", "66,550"], D,
      "Raw materials consumed = ₦11,150 + ₦112,550 − ₦31,150 + ₦1,150 − ₦27,150 = ₦66,550."),
    q(DEPT + "Determine the net profit of the business.",
      ["6,600", "6,271", "5,353", "7,224"], D,
      "Gross profit = (₦10,600 − ₦5,247) + (₦15,175 − ₦6,704) = ₦5,353 + ₦8,471 = ₦13,824; less expenses ₦6,600 = net profit ₦7,224."),
    q(DEPT + "Find the total expenses allocated to the stationery department.",
      ["3,600", "1,400", "4,400", "3,800"], C,
      "Total expenses = ₦4,500 + ₦1,200 + ₦900 = ₦6,600; the stationery share is 2/3 × ₦6,600 = ₦4,400."),
    q("Use the following information: \nStock 1/1/2002 ... ₦40,000\nGoods received from head office ... ₦800,000\nGoods returned to head office ... ₦34,000\nSales ... ₦916,000\nStock 31/12/2002 ... ₦72,000\n\nFrom the data above, determine the cost of goods credited to the head office trading account.",
      ["766,000", "840,000", "734,000", "806,000"], A,
      "The goods sent to branch account (₦800,000 less returns ₦34,000 = ₦766,000) is closed by crediting the head office trading account with the net goods sent.",
      { keyVerdict: 'corrected', keyAnswer: 'C', answerNote: "The answer key gives 734,000, which is the branch's cost of goods sold (₦40,000 + ₦766,000 − ₦72,000). The amount credited to the head office trading account is the net goods sent to the branch: ₦800,000 − ₦34,000 = ₦766,000." }),
    q(OVH + "The factory overhead is",
      ["5,050", "7,250", "2,750", "5,500"], D,
      "Factory share = 1/4 × ₦10,000 + 1/5 × ₦15,000 = ₦2,500 + ₦3,000 = ₦5,500."),
    q(OVH + "Determine the amount of office lighting and heating.",
      ["19,500", "25,000", "7,500", "12,000"], A,
      "The office bears the rest: 3/4 × ₦10,000 + 4/5 × ₦15,000 = ₦7,500 + ₦12,000 = ₦19,500."),
    q("Interest on the drawings of partners is treated in the",
      ["profit and loss appropriation account", "goodwill account", "profit and loss account", "trading account"], A,
      "Interest on drawings is a charge on partners, not a business income, so it is added to net profit in the profit and loss appropriation account (and debited to the partners' current accounts)."),
    q("Departmentalisation of accounts is useful because it shows the",
      ["overall performance of a firm", "price per unit of a product", "cost per unit of a product", "overall performance of a division"], D,
      "Departmental accounts show the gross and net profit of each department (division), so management can see which sections are doing well or badly."),
    q("When goodwill is not retained in the business, the entries in the new partner's books will be to debit",
      ["goodwill account and credit partner's capital account", "partners' capital account and credit goodwill account", "cash account and credit goodwill account", "goodwill account and credit cash account"], B,
      "When goodwill is not to remain in the books it is written off by debiting the partners' capital accounts (in the new profit-sharing ratio) and crediting goodwill account."),
    q("Use the following information: \n... January ... December\nAssets ... ₦28,320 ... ₦25,320\nCreditors ... ₦5,620 ... ₦10,320\nThe proprietor made drawings of ₦755 per month for personal use.\n\nThe profit for the period is",
      ["₦3,000", "₦1,360", "₦9,060", "₦7,700"], B,
      "Capital fell from ₦22,700 to ₦15,000 (a decrease of ₦7,700); adding back drawings of ₦755 × 12 = ₦9,060 gives profit of ₦1,360."),
    // paper 41–50
    q("Use the following information: \nSubscriptions received ... ₦200,000\nSubscriptions owed ... ₦10,000\nSubscriptions in advance ... ₦25,000\n\nCalculate the subscriptions in the income and expenditure account.",
      ["₦200,000", "₦235,000", "₦185,000", "₦225,000"], C,
      "Subscriptions for the year = cash received ₦200,000 + owing at year end ₦10,000 − paid in advance for next year ₦25,000 = ₦185,000."),
    q("Boro Limited apportions 1/6 of its rent for factory and 10% of the balance for warehouse. If rent paid is ₦48,600, how much is paid for warehouse?",
      ["₦8,150", "₦4,860", "₦4,100", "₦4,050"], D,
      "Factory = 1/6 × ₦48,600 = ₦8,100; balance = ₦40,500; warehouse = 10% × ₦40,500 = ₦4,050."),
    q("Head office sends goods to its branch at cost plus mark-up of 25%. A debit of 40,000 to the branch stock account in the head office books will indicate that the head office has sent goods with a profit of",
      ["4,000", "6,000", "10,000", "8,000"], D,
      "A 25% mark-up on cost is 25/125 = 1/5 of the selling price, so the profit loading in ₦40,000 is ₦8,000 (cost ₦32,000)."),
    q(LOAN + "What is the capital balance?",
      ["8,400", "6,900", "10,500", "15,000"], A,
      "Loan = 30% × ₦7,000 = ₦2,100; capital = assets ₦17,500 − liabilities (₦7,000 + ₦2,100) = ₦8,400."),
    q(LOAN + "The amount of the loan is",
      ["1,000", "2,100", "900", "1,200"], B,
      "The loan is 30% of creditors: 30% × ₦7,000 = ₦2,100."),
    q("A company has departments S, T and U. The sales are ₦20,000, ₦40,000 and ₦60,000 respectively. If the sales commission paid is ₦12,000, how much is T's share?",
      ["₦8,000", "₦2,000", "₦4,000", "₦6,000"], C,
      "Sales commission is apportioned in the ratio of sales, 20:40:60; T's share = 40/120 × ₦12,000 = ₦4,000."),
    q("MPOBA Club's annual donations from members amount to 112% of its internally generated revenue from the following:\nSale of drinks ... ₦212,500\nAccrual dues ... ₦112,000\n\nHow much is the total receipts of the club?",
      ["563,440", "687,940", "363,440", "524,500"], B,
      "Internally generated revenue = ₦212,500 + ₦112,000 = ₦324,500; donations = 112% × ₦324,500 = ₦363,440; total receipts = ₦324,500 + ₦363,440 = ₦687,940."),
    q("In converting a partnership to a company, the loss on asset revaluation is",
      ["debited to the revaluation account", "debited to the profit and loss account", "credited to the revaluation account", "credited to the profit and loss account"], A,
      "A fall in the value of an asset is a loss, so it is debited to the revaluation (realisation) account; the net result is then shared among the partners' capital accounts."),
    q(RP + "What is the closing cash balance?",
      ["₦35,000", "₦211,100", "₦5,000", "₦10,000"], C,
      "Payments = ₦300,000; subscriptions = 80% × ₦300,000 = ₦240,000; opening balance = 30% × ₦50,000 = ₦15,000; closing balance = ₦15,000 + ₦240,000 + ₦50,000 − ₦300,000 = ₦5,000."),
    q(RP + "The subscriptions received would be",
      ["₦200,000", "₦240,000", "₦300,000", "₦24,000"], B,
      "Total payments = ₦30,000 + ₦100,000 + ₦20,000 + ₦150,000 = ₦300,000, and subscriptions are 80% of that: ₦240,000."),
  ]);
})();
