/**
 * JAMB/UTME 2002 — PRINCIPLES OF ACCOUNTS
 * From the 2002 question paper (questions 1–50); answers from the JAMB/UTME Accounts answer key
 * 2001–2020, each checked independently. Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2002;
  const SRC = 'JAMB UTME 2002';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const UDO = "Use the following information: \nThe assets and liabilities of Udo Co. Ltd as at 31st December, 2000:\nCreditors ... ₦50,000\nDebtors ... ₦46,000\nLoan ... ₦100,000\nStock ... ₦20,000\nMotor vehicle ... ₦120,000\nBuilding ... ₦70,000\nAccrued wages ... ₦30,000\nBank ... ₦25,000\n\n";
  const SAL = "Use the following information: \nStatement of Assets and Liabilities as at 31st December, 2001 (₦m):\nShareholders' interest ... 240\nCurrent liabilities ... 20\nCurrent assets ... 110\nFixed assets ... 140\n\n";
  const ERERO = "Use the following information: \nErero's Trading Account for the month ended 31/05/2001:\nOpening stock ... ₦45,000\nPurchases ₦110,000 less returns ₦6,000 ... ₦104,000\n(Opening stock + net purchases ... ₦149,000)\nLess closing stock ... ???\nCost of sales ... ???\nGross profit ... ???\nTotal ... ₦157,000\nSales ₦161,000 less returns ₦4,000 ... ₦157,000\nThe gross profit ratio for the company is 25%.\n\n";
  const MANU = "Use the following information: \nStock of raw materials (1st January) ... ₦3,000\nDirect wages ... ₦2,500\nDirect expenses ... ₦1,000\nFactory overheads ... ₦2,000\nCost of raw materials used ... ₦5,500\nStock of finished goods (31st December) ... ₦2,000\n\n";
  const ADEX = "Use the following information: \nAdex Ltd issues stock to its retail branch at cost price. The following particulars relate to Ede branch:\nStock at branch 1st January at cost ... ₦400\nGoods sent to branch at cost ... ₦8,000\nReturns to head office ... ₦340\nCash sales ... ₦9,160\nStock at branch 31st December at cost ... ₦720\n\n";
  const RP = "Use the following information: \nReceipts and Payments Account [Extract]\nReceipts: Balance b/d ₦4,000; Subscriptions received ?; Donations received ₦6,000; Refreshment sales ₦10,000\nPayments: Motor vehicle expenses ₦12,000; Insurance ₦3,000; Ambulance expenses ₦12,500; Electricity ₦1,000; Balance c/d ?\nSubscriptions received are always put at 125% of the total donations received and refreshment sales.\n\n";
  const DEPT = "Use the following information: \n(Total / Dept. P / Dept. Q)\nSales ... ₦10,000 / ₦6,000 / ₦4,000\nPurchases ... ₦4,000 / ₦1,000 / ₦3,000\nDiscount received ... ₦1,000 / ? / -\nDiscounts allowed ... ₦2,000 / - / ?\nDiscounts (allowed and received) are apportioned to the two departments on the basis of departmental sales and purchases.\n\n";
  const IE = "Use the following information: \nIncome and Expenditure Account\nExpenditure: Wages ₦12,000; Electricity ₦5,000; Depreciation: Furniture ₦1,000; Other expenses ?; Excess of income over expenditure ?; Total ₦35,000\nIncome: Subscriptions received ₦20,000; Donations received ₦10,000; Profit on sale of investment ₦5,000; Total ₦35,000\nIt is the tradition of the club to write off an amount equal to 25% of the subscriptions received as other expenses.\n\n";
  const STK = "Use the following information: \nReceipts: January 2nd, 500 units at ₦25 = ₦12,500; March 7th, 250 units at ₦28 = ₦7,000\nIssues were made as follows: January 9th, 200 units; February 14th, 200 units; March 11th, 200 units\n\n";
  const PART = "Use the following information: \nThe partnership agreement between Abba, Baba and Kaka contains the following provisions: (i) 5% interest to be paid on capital and no interest to be charged on drawings; (ii) profits and losses to be shared in the ratio 3:2:1 respectively; (iii) net profit for the year to 31/12/95 ₦2,250.\n(Abba / Baba / Kaka)\nCapital ... ₦5,000 / ₦4,000 / ₦3,000\nCurrent account ... ₦250 / ₦100 / ₦175\nSalary ... ₦300 / ₦300 / -\nDrawings ... ₦600 / ₦500 / ₦250\n\n";

  QUESTION_BANK.accounting = QUESTION_BANK.accounting.concat([
    // paper 1–10
    q("In preparing the final account, the bad debt account is closed by a transfer to the",
      ["Balance sheet", "Provision for bad debt", "Profit and loss account", "Trading account"], C,
      "Bad debts are a loss (an expense) of the business, so at the end of the year the bad debts account is closed by debiting the profit and loss account."),
    q("Given: \nStock (1/4/94) ... ₦800\nPurchases of flour ... ₦2,450\nSales ... ₦4,745\nWages of bakery staff ... ₦675\nCarriage outwards ... ₦50\nSalary of administrative staff ... ₦225\nStock (31/3/95) ... ₦940\nCapital ... ₦1,540\n\nDetermine the cost of goods sold.",
      ["₦2,575", "₦2,985", "₦3,250", "₦3,925"], B,
      "Cost of goods sold = opening stock ₦800 + purchases ₦2,450 + bakery wages ₦675 (a direct cost of producing the bread) − closing stock ₦940 = ₦2,985."),
    q("In a petty cash book the imprest is ₦1,380.\nExpenses:\nStationery ... ₦350\nCleaning material ... ₦335\nGeneral expenses ... ₦265\n\nHow much was received to maintain the imprest at the end of the month?",
      ["₦950", "₦970", "₦430", "₦380"], A,
      "Under the imprest system the petty cashier is reimbursed exactly what was spent: ₦350 + ₦335 + ₦265 = ₦950, which restores the float to ₦1,380."),
    q("Income statement for the year ended June 30, 2001:\nOffice rent ... ₦20,000\nNEPA (light) ... ₦15,000\nSalary of staff ... ₦120,000\nMiscellaneous expenses ... ?\nNet income ... ?\nRevenue ... ₦820,000\nMiscellaneous expenses is 10% of revenue.\n\nCalculate the net income.",
      ["₦583,000", "₦563,000", "₦483,000", "₦683,000"], A,
      "Miscellaneous expenses = 10% × ₦820,000 = ₦82,000; total expenses = ₦20,000 + ₦15,000 + ₦120,000 + ₦82,000 = ₦237,000; net income = ₦820,000 − ₦237,000 = ₦583,000."),
    q("An entry in a subsidiary book which does not form part of the double entry system is a",
      ["contra entry", "journal entry", "single entry", "memorandum entry"], D,
      "A memorandum entry is made for information only (for example, a trade discount noted on an invoice) and is not posted to the ledger, so it is not part of the double entry."),
    q("In an incomplete record, the preparation of the bank reconciliation ensures that",
      ["all cash takings are banked", "the cash book is correct", "there are no overdrafts", "there are no hidden loans"], A,
      "When records are incomplete, the bank statement is matched against the trader's record of takings and payments; the reconciliation shows whether all cash takings have been banked and traces those that were not."),
    q("I. Fixtures account; II. Machinery account; III. Wages account; IV. Rent account. Which of the above are nominal accounts?",
      ["III and IV", "I and II", "I and III", "II and III"], A,
      "Nominal accounts record expenses, losses, incomes and gains; wages and rent are expenses, while fixtures and machinery are real (asset) accounts."),
    q("NAFARA & SONS balance sheet items as at 31st December, 1987:\nCapital ... ₦74,480\nCreditors ... ₦15,875\nPrepaid expenses ... ₦580\nMotor vehicles ... ₦34,750\nFurniture ... ₦35,850\nAccrued expenses ... ₦645\nStock ... ₦8,100\nCash balances ... ₦9,911\nDebtors ... ₦1,809\n\nCompute the value of current assets.",
      ["₦20,400", "₦20,465", "₦35,695", "₦19,820"], A,
      "Current assets = prepaid expenses ₦580 + stock ₦8,100 + cash ₦9,911 + debtors ₦1,809 = ₦20,400; accrued expenses and creditors are current liabilities."),
    q(UDO + "The value of capital invested by the owners is",
      ["₦110,000", "₦105,000", "₦101,000", "₦100,000"], C,
      "Total assets = ₦46,000 + ₦20,000 + ₦120,000 + ₦70,000 + ₦25,000 = ₦281,000; liabilities = ₦50,000 + ₦100,000 + ₦30,000 = ₦180,000; capital = ₦281,000 − ₦180,000 = ₦101,000."),
    q(UDO + "The liabilities of Udo Co. Ltd is",
      ["₦180,000", "₦181,000", "₦177,000", "₦110,000"], A,
      "Liabilities are the amounts owed to outsiders: creditors ₦50,000 + loan ₦100,000 + accrued wages ₦30,000 = ₦180,000."),
    // paper 11–20
    q("The normal accounting entry to record the dishonour of a cheque by a businessman is to",
      ["debit cash book and credit suspense account", "debit cash book and credit drawer", "credit cash book and debit suspense account", "credit cash book and debit drawer"], D,
      "When a cheque received is dishonoured the money never arrives, so the bank column of the cash book is credited and the drawer (the customer) is debited again because he still owes the amount."),
    q(SAL + "What is the net working capital?",
      ["₦90m", "₦70m", "₦100m", "₦80m"], A,
      "Net working capital = current assets ₦110m − current liabilities ₦20m = ₦90m."),
    q(SAL + "Determine the value of the trade investment.",
      ["₦8m", "₦10m", "₦15m", "₦20m"], B,
      "Total sources = shareholders' interest ₦240m + current liabilities ₦20m = ₦260m; fixed assets ₦140m + current assets ₦110m = ₦250m, so the missing asset, the trade investment, is ₦10m."),
    q("The concise statement used to explain entries in the general journal is known as",
      ["narration", "summary", "information", "commentary"], A,
      "Each journal entry is followed by a short explanation of the transaction called the narration."),
    q(ERERO + "If the total expenses is ₦20,845, what will be the net profit for the company during the month?",
      ["₦19,149", "₦16,168", "₦21,655", "₦18,405"], D,
      "Gross profit = 25% × net sales ₦157,000 = ₦39,250; net profit = ₦39,250 − ₦20,845 = ₦18,405."),
    q(ERERO + "The closing stock for this company is",
      ["₦72,000", "₦45,000", "₦42,500", "₦31,250"], D,
      "Gross profit = 25% × ₦157,000 = ₦39,250, so cost of sales = ₦157,000 − ₦39,250 = ₦117,750; closing stock = ₦149,000 − ₦117,750 = ₦31,250."),
    q("In a departmental accounting system, which of the following expenses will most likely be apportioned on the basis of turnover?",
      ["Carriage outwards", "Carriage inwards", "Discounts received", "Returns outwards"], A,
      "Carriage outwards is a cost of delivering goods sold, so it rises with sales and is shared among departments in the ratio of their turnover (sales)."),
    q(MANU + "Determine the prime cost.",
      ["₦7,500", "₦6,500", "₦9,000", "₦8,000"], C,
      "Prime cost = direct materials used ₦5,500 + direct wages ₦2,500 + direct expenses ₦1,000 = ₦9,000."),
    q(MANU + "The cost of goods manufactured is",
      ["₦11,000", "₦12,000", "₦14,000", "₦9,000"], A,
      "Cost of goods manufactured (production cost) = prime cost ₦9,000 + factory overheads ₦2,000 = ₦11,000."),
    q("I. Orientation; II. Entity; III. Legal status; IV. Finance. Which of the characteristics above distinguishes a profit-making from a not-for-profit-making organization?",
      ["I, II, III and IV", "I, II and III", "II and III", "I and II"], B,
      "A profit-making business differs from a club or society in its orientation (profit versus service to members), the kind of entity it is, and its legal status (sole trader, partnership or company versus association or trust)."),
    // paper 21–30
    q(ADEX + "What is the gross profit carried to the profit and loss account?",
      ["₦1,820", "₦1,640", "₦1,530", "₦1,870"], A,
      "Cost of goods sold = ₦400 + (₦8,000 − ₦340) − ₦720 = ₦7,340; gross profit = cash sales ₦9,160 − ₦7,340 = ₦1,820."),
    q(ADEX + "Calculate the cost of goods credited to the head office trading account.",
      ["₦7,660", "₦7,500", "₦7,460", "₦7,200"], A,
      "Goods sent to branch less returns from branch: ₦8,000 − ₦340 = ₦7,660 is credited to (deducted from purchases in) the head office trading account."),
    q("Nasara Manufacturing Plc has three direct labour employees that work 40 hours each a week for 50 weeks a year. Factory overhead costs of ₦60,000 is distributed on the basis of direct labour hours. Compute the overhead rate.",
      ["₦12 per hour", "₦16 per hour", "₦10 per hour", "₦15 per hour"], C,
      "Direct labour hours = 3 × 40 × 50 = 6,000 hours; overhead rate = ₦60,000 ÷ 6,000 = ₦10 per hour."),
    q(RP + "What is the closing cash balance?",
      ["₦11,500", "₦12,000", "₦13,000", "₦13,500"], A,
      "Subscriptions = 125% × (₦6,000 + ₦10,000) = ₦20,000; receipts = ₦4,000 + ₦20,000 + ₦6,000 + ₦10,000 = ₦40,000; payments = ₦12,000 + ₦3,000 + ₦12,500 + ₦1,000 = ₦28,500; balance c/d = ₦11,500."),
    q(RP + "Compute the subscriptions received.",
      ["₦30,000", "₦28,000", "₦24,000", "₦20,000"], D,
      "Subscriptions = 125% × (donations ₦6,000 + refreshment sales ₦10,000) = 1.25 × ₦16,000 = ₦20,000."),
    q(DEPT + "Department P's share of discount received is",
      ["₦750", "₦1,000", "₦250", "₦500"], C,
      "Discount received is shared on purchases: P's share = ₦1,000/₦4,000 × ₦1,000 = ₦250."),
    q(DEPT + "What is Department Q's share of discount allowed?",
      ["₦2,000", "₦1,500", "₦800", "₦1,200"], C,
      "Discount allowed is shared on sales: Q's share = ₦4,000/₦10,000 × ₦2,000 = ₦800."),
    q(IE + "What is the amount to be written off as other expenses?",
      ["₦4,500", "₦6,000", "₦4,000", "₦5,000"], D,
      "Other expenses = 25% × subscriptions ₦20,000 = ₦5,000."),
    q(IE + "Determine the club's excess of income over expenditure.",
      ["₦12,000", "₦15,000", "₦10,000", "₦14,500"], A,
      "Expenditure = ₦12,000 + ₦5,000 + ₦1,000 + ₦5,000 = ₦23,000; excess of income over expenditure = ₦35,000 − ₦23,000 = ₦12,000."),
    q("The gross profit on manufactured goods is the difference between the cost of goods manufactured and the",
      ["market value of goods produced", "prime cost of production", "indirect cost of production", "goods produced"], A,
      "When finished goods are transferred to the trading account at market (transfer) value, the excess of that market value over the cost of production is the manufacturing (gross) profit."),
    // paper 31–40
    q("Given that 1/3 of the ₦6,000 stock held by a branch is purchased from outsiders. If goods are invoiced to the branch at 25% on cost, the provision for unrealised profit is",
      ["₦1,000.00", "₦333.33", "₦666.66", "₦800.00"], D,
      "Only the 2/3 from head office (₦4,000 at invoice price) contains head office profit; at 25% on cost the profit is 25/125 of invoice price: ₦4,000 × 25/125 = ₦800."),
    q("A.S.D Club Balance Sheet [Extract]\nAccumulated fund ₦6,000 add surplus income ₦1,000 ... ₦7,000\nCreditors for supplies ... ₦1,000\nSubscriptions in advance ... ₦2,000\nTotal ... ₦10,000\nMotor van ... ₦4,000\nStock ... ₦3,500\nDebtors for subscriptions ... ₦1,000\nBank ... ₦1,500\nTotal ... ₦10,000\n\nThe working capital of the club is",
      ["₦5,000", "₦4,000", "₦3,000", "₦7,000"], C,
      "Current assets = stock ₦3,500 + subscriptions owing ₦1,000 + bank ₦1,500 = ₦6,000; current liabilities = creditors ₦1,000 + subscriptions in advance ₦2,000 = ₦3,000; working capital = ₦3,000."),
    q("Costs that vary in proportion to the level of production in a manufacturing environment are known as",
      ["control costs", "overheads", "direct costs", "indirect costs"], C,
      "Direct costs (direct materials, direct labour, direct expenses) rise and fall in step with the number of units produced, while overheads are largely fixed."),
    q("A company operating a chain of retail provision stores invoices goods to the branches at cost plus a mark-up of 25%. What is the mark-up percentage on selling price?",
      ["35%", "30%", "20%", "15%"], C,
      "A 25% mark-up on cost means cost ₦100 and selling price ₦125; the profit of ₦25 as a fraction of selling price is 25/125 = 20%."),
    q("Given: \nCash purchases ... ₦25,000\nTrade creditors ... ₦45,000\nOpening balance of trade creditors ... ₦35,000\n\nCalculate the purchases for the period.",
      ["₦80,000", "₦35,000", "₦105,000", "₦55,000"], B,
      "Credit purchases = closing creditors ₦45,000 − opening creditors ₦35,000 = ₦10,000 (no payments are given); total purchases = cash ₦25,000 + credit ₦10,000 = ₦35,000."),
    q("Which method of pricing can be used satisfactorily in either a rising or falling price situation?",
      ["Standard price", "Market price", "FIFO", "Average method"], D,
      "The average cost method smooths out price changes, so it gives reasonable issue prices and stock values whether prices are rising or falling."),
    q("Given: \nCapital at start ... ₦3,250\nCapital at close ... ₦6,250\nAdditional capital during the period ... ₦1,000\n\nCalculate the profit or loss.",
      ["₦8,500 loss", "₦2,000 loss", "₦2,000 profit", "₦8,500 profit"], C,
      "Profit = closing capital ₦6,250 − opening capital ₦3,250 − additional capital ₦1,000 = ₦2,000 profit."),
    q("In a control account, discount received is found on the",
      ["debit side of the purchases ledger control account", "debit side of the sales ledger control account", "credit side of the purchases ledger control account", "credit side of the sales ledger control account"], A,
      "Discount received reduces what the business owes its suppliers, so it is debited in the purchases ledger control account."),
    q("In an incomplete record system, a trading account cannot be prepared until the",
      ["day book has been balanced", "amount of personal drawings has been established", "cash book has been balanced", "amount of sales and purchases has been established"], D,
      "A trading account compares sales with the cost of goods sold, so sales and purchases must first be worked out (from cash records and debtors/creditors control accounts)."),
    q(STK + "The closing stock on March 11th by LIFO valuation is",
      ["₦4,200", "₦2,700", "₦4,500", "₦3,900"], D,
      "After the January and February issues 100 units at ₦25 remain; 250 units at ₦28 arrive on 7 March; the 11 March issue of 200 takes the latest units at ₦28, leaving 50 × ₦28 + 100 × ₦25 = ₦3,900. LIFO is no longer allowed under IAS 2 (Inventories)."),
    // paper 41–50
    q(STK + "The value of closing stock as at February 14th by simple average method is",
      ["₦3,900", "₦2,500", "₦4,100", "₦2,700"], B,
      "By 14 February only the January batch at ₦25 has been received, so the simple average price is ₦25; stock left = 500 − 200 − 200 = 100 units × ₦25 = ₦2,500."),
    q("Given an incomplete record without sufficient information to determine profit, the necessary thing to do is to",
      ["draw up the statement of affairs", "draw up a T-account to establish the amount", "compare the journal entries with the cash book", "cross-check the cash book for further information"], A,
      "When there is not enough information to prepare a trading and profit and loss account, profit is found by drawing up statements of affairs at the start and end and comparing the capitals."),
    q("Control accounts help to verify the arithmetic accuracy of the postings from the",
      ["subsidiary books into the trial balance", "ledgers into the trial balance", "journals into the ledgers", "subsidiary books into the ledgers"], D,
      "A control account is built from the totals in the subsidiary books; agreeing it with the total of the individual ledger balances checks the postings from those books into the ledgers."),
    q("Keeping records under the single entry system has the advantage of",
      ["duality in terms of records", "completeness in terms of records", "accuracy in terms of operation", "simplicity in terms of operation"], D,
      "Single entry is simple and cheap to keep, which is its main advantage; it lacks the duality, completeness and arithmetic check of double entry."),
    q("Given: \nSales ... ₦195,200\nStock 1st January ... ₦34,000\nPurchases ... ₦126,000\nSales returns ... ₦1,200\nPurchases returns ... ₦2,000\n\nIf the gross profit is ₦66,000, what is the value of stock at 31st December?",
      ["₦30,000", "₦40,000", "₦50,000", "₦20,000"], A,
      "Net sales ₦194,000 − gross profit ₦66,000 = cost of sales ₦128,000; stock + net purchases = ₦34,000 + ₦124,000 = ₦158,000; closing stock = ₦158,000 − ₦128,000 = ₦30,000."),
    q("Given (₦m): \nBalance at 31st December ... 14,744\nTreasury Bills issued Jan – Dec ... 7,124\nRevenue for the year ... 6,387\nExpenditure ... 8,767\n\nWhat is the opening balance on the consolidated revenue fund account?",
      ["₦10,000m", "₦12,000m", "₦9,000m", "₦11,000m"], A,
      "Opening balance + treasury bills + revenue − expenditure = closing balance, so opening = ₦14,744m − ₦7,124m − ₦6,387m + ₦8,767m = ₦10,000m."),
    q(PART + "Abba's capital balance at the end of the year will be",
      ["₦5,475", "₦5,725", "₦4,400", "₦5,000"], D,
      "The partners keep current accounts, so capitals are fixed: interest, salary, profit share and drawings go to the current accounts and Abba's capital stays at ₦5,000."),
    q(PART + "Current account balance of Kaka at the end of the year will be",
      ["₦250", "₦350", "₦175", "₦325"], A,
      "Residual profit = ₦2,250 − interest ₦600 − salaries ₦600 = ₦1,050; Kaka's current account = ₦175 + interest ₦150 + 1/6 × ₦1,050 (₦175) − drawings ₦250 = ₦250."),
    q("Upon the dissolution of a partnership, the Partnership Act provides that the amount realised should be",
      ["used to pay all taxes due to government", "used to start a new partnership business by members who are willing", "shared equally by the existing partners", "used in paying the debts and liabilities of the firm to persons who are not partners"], D,
      "Under the Partnership Act 1890 (section 44) the proceeds are applied first to pay the firm's debts to outsiders, then partners' loans, then partners' capitals, with any surplus shared in the profit-sharing ratio."),
    q("In the public sector, the method of accounting that reports revenues and expenditures in the period in which they are received and paid is called",
      ["fund accounting", "commitment accounting", "cash accounting", "accrual accounting"], C,
      "The cash basis records revenue when cash is received and expenditure when cash is paid. Nigeria's public sector has since moved to IPSAS accrual accounting (adopted from 2016)."),
  ]);
})();
