/**
 * JAMB/UTME 2003 — PRINCIPLES OF ACCOUNTS
 * From the 2003 question paper (questions 1–50); answers from the JAMB/UTME Accounts answer key
 * 2001–2020, each checked independently. Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2003;
  const SRC = 'JAMB UTME 2003';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const TB45 = "Use the following information:\nCapital ... ₦2,000\nBank ... ₦1,200\nPurchases ... ₦2,500\nSales ... ₦6,700\nStock ... ₦1,300\nCreditors ... ₦1,000\nFixed assets ... ₦3,700\nDrawings ... ?\nDrawings are always estimated at 50% of capital.\n\n";
  const EZ = "Use the following information:\nEzekiel Malgwi is a retailer. He recorded sales representing 95% cash and 5% credit. He took the total cash sales of ₦19,000 from the business tray and banked it.\n\n";
  const MV = "Use the following information:\nMotor Vehicle Account as at 31st December, 2001\nDebit:\nJan. 1, Cost ... ₦1,950,000\nDec. 31, Addition ... ₦400,000\nCredit:\nJan. 1, Depreciation ... ₦1,360,000\nJune 30, Sales proceeds ... ₦700,000\nThe vehicle sold was purchased on January 1, 1998 at a cost of ₦1,000,000 and had depreciated at 25% on cost.\n\n";
  const TB1516 = "Use the following information:\nCapital ... Cr ₦24,000\nLand and building ... Dr ₦18,470\nMortgage on premises ... Cr ₦11,090\nDrawings ... Dr ₦3,000\nProfit and loss ... Cr ₦3,600\nFurniture and fittings ... Dr ₦5,120\nMotor vehicles ... Dr ₦3,462\nClosing stock ... Dr ₦3,000\nDebtors ... Dr ₦11,474\nCreditors ... Cr ₦7,354\nCash ... Dr ₦1,518\nTotals ... Dr ₦46,044 ... Cr ₦46,044\n\n";
  const STK = "Use the following information:\nFeb. 1 ... Purchased 400 units at ₦1.00 each\nFeb. 5 ... Purchased 200 units at ₦2.00 each\nFeb. 10 ... Purchased 200 units at ₦3.00 each\nFeb. 15 ... Issued 320 units\nFeb. 20 ... Purchased 200 units at ₦3.00 each\nFeb. 25 ... Issued 120 units\n\n";
  const PLC = "Use the following information:\nPurchases ledger control account\nDebit side:\nDiscount received ... ₦1,000\nBills payable ... ₦1,500\nCash paid to suppliers ... ₦8,000\nReturns outwards ... ₦3,000\nBalance c/d ... ?\nCredit side:\nBalance b/d ... ₦2,900\nCredit purchases ... ?\nBills payable dishonoured ... ₦1,600\nDishonoured cheques ... ₦2,000\nCredit purchases are always put at 150% of the total cash paid to suppliers.\n\n";
  const PQ = "Use the following information:\nPQ Manufacturing Company\nRaw materials (1/1/2001) ... ₦3,500\nRaw materials (31/12/2001) ... ₦4,900\nPurchase of raw materials ... ₦56,000\nSalary ... ₦63,000\nWages ... ₦148,050\nFactory lighting ... ₦3,080\nPlant depreciation ... ₦2,800\nFactory insurance ... ₦2,170\n\n";
  const CLUB = "Use the following information:\nTotal sales of tickets ... ₦300,000\nAmount received from the sales ... ₦260,000\nCash purchase of the club house ... ₦100,000\nCredit purchase of equipment ... ₦60,000\nElectricity bill paid ... ₦5,000\nSalaries owed ... ₦2,000\n\n";
  const EMEKA = "Use the following information:\nEmeka Enterprises: Statement of Affairs at start\nAssets:\nCash ... ₦70,000\nInventory ... ₦58,000\nMachines ... ₦100,000\nLiabilities:\nCreditors ... ₦85,000\nBank loan ... ₦60,000\n\n";
  const BR = "Use the following information:\nGoods from head office ... ₦13,400\nReturns to head office ... ₦118\nRates and insurance paid ... ₦188\nWages paid ... ₦913\nCash remitted to head office ... ₦16,625\nStock at 1/1/2000 ... ₦1,875\nRent paid ... ₦325\nStock at 31/12/2000 ... ₦1,975\nSundry expenses ... ₦200\n\n";
  const ZEB = "Use the following information:\nZEBRA PLC: Balance sheet as at 31st March, 2002\nCapital ... ₦100,000\nCurrent liabilities:\nCreditors ... ₦30,000\nTotal ... ₦130,000\nFixed assets:\nLand and buildings ... ₦50,000\nFurniture ... ₦10,000 ... ₦60,000\nCurrent assets:\nStock ... ₦30,000\nDebtors ... ₦30,000\nCash ... ₦10,000 ... ₦70,000\nTotal ... ₦130,000\nThe business was acquired on 1st April, 2002 at a purchase consideration of ₦120,000 by SOZ. All assets and liabilities were taken over except the cash. To open the new firm's bank account, additional ₦20,000 was paid into the bank.\n\n";

  QUESTION_BANK.accounting = QUESTION_BANK.accounting.concat([
    // paper 1–10
    q("Which of the following is used to update the cash book in bank reconciliation?",
      ["Interest received and unpresented cheques", "Commission and debit note", "Unpresented cheques and direct credit", "Interest received and direct credit"], D,
      "Items the bank has already recorded but the business has not (interest received, direct credits, bank charges, standing orders) are entered in the cash book; unpresented cheques are already in the cash book and only go in the reconciliation statement."),
    q("The two legally recognized professional accounting bodies in Nigeria are the",
      ["Institute of Certified Public Accountants of Nigeria and the Institute of Cost and Management Accountants of Nigeria", "Association of Accountants of Nigeria and the Institute of Management Accountants of Nigeria", "Institute of Chartered Accountants of Nigeria and the Association of National Accountants of Nigeria", "Nigeria Accounting Association and the Executive Cost and Management Accountants of Nigeria"], C,
      "ICAN was set up by Act No. 15 of 1965 and ANAN by Decree No. 76 of 1993; they are the two accountancy bodies established by Nigerian law, and this is still true today."),
    q("Verifiability in accounting is only possible when there are",
      ["minutes of meetings", "payment vouchers", "source documents", "audit certificates"], C,
      "Figures can be checked (verified) only if each entry is backed by a source document such as an invoice, receipt or voucher; this is the objectivity or verifiability idea."),
    q(TB45 + "The trial balance total is",
      ["₦9,700", "₦8,700", "₦7,900", "₦7,800"], A,
      "Drawings = 50% × ₦2,000 = ₦1,000. Debits: 1,200 + 2,500 + 1,300 + 3,700 + 1,000 = ₦9,700; credits: 2,000 + 6,700 + 1,000 = ₦9,700."),
    q(TB45 + "Compute the amount withdrawn",
      ["₦2,000", "₦1,500", "₦1,200", "₦1,000"], D,
      "Drawings are 50% of capital: 50% × ₦2,000 = ₦1,000."),
    q(EZ + "The credit sales for the period would be",
      ["₦5,000", "₦1,900", "₦1,000", "₦950"], C,
      "Cash sales of ₦19,000 are 95% of total sales, so total sales = 19,000 ÷ 0.95 = ₦20,000 and credit sales = 5% × 20,000 = ₦1,000."),
    q(EZ + "The transaction would be recorded in the cash book as debit",
      ["cash and credit bank", "bank and credit cash", "cash and credit cash", "bank and credit bank"], B,
      "Paying office cash into the bank is a contra entry: the bank column receives (debit bank) and the cash column gives (credit cash)."),
    q("Which accounting concept supports the assertion that economic reality takes precedence over legal issues?",
      ["Realization concept", "Substance over form", "Conservatism", "Measurement concept"], B,
      "Substance over form says transactions are recorded according to their economic reality rather than their legal form, e.g. an asset on hire purchase is shown as an asset before legal ownership passes. Under IFRS this idea is now part of faithful representation."),
    q("The transaction that completes its double entry in the same ledger account appears in",
      ["cash account and personal account", "bank account and general ledger", "discount received and discount allowed", "cash account and bank account"], D,
      "A contra entry between cash and bank (e.g. cash paid into bank) has both its debit and credit inside the same book, the two-column cash book."),
    q("Given:\nCapital ... ₦1,000\nLiabilities ... ₦500\nAssets ... ₦1,500\n\nThe accounting equation can be expressed as",
      ["₦1,000 + ₦500 + ₦1,500 = ₦3,000", "₦1,000 − ₦500 + ₦1,500 = ₦2,000", "₦1,000 + ₦500 = ₦1,500", "₦1,500 + ₦500 = ₦2,000"], C,
      "The accounting equation is Capital + Liabilities = Assets: ₦1,000 + ₦500 = ₦1,500."),
    // paper 11–20
    q("The recording phase of accounting is known as",
      ["bookkeeping", "trial balancing", "ledger accounting", "final accounting"], A,
      "Bookkeeping is the recording stage: entering transactions in the books of original entry and the ledger; accounting goes further to summarise, analyse and interpret them."),
    q(MV + "Assuming that depreciation is charged on the addition of the year at the rate of 15% on reducing balance, what should be the net book value of the vehicle as at 31st December, 2003?",
      ["₦111,000", "₦289,000", "₦250,000", "₦340,000"], B,
      "The addition of ₦400,000 was bought on 31 December 2001, so the first charge is for 2002: 15% × 400,000 = ₦60,000 (NBV ₦340,000); 2003: 15% × 340,000 = ₦51,000, so NBV at 31 December 2003 = ₦289,000."),
    q(MV + "What is the actual profit or loss arising from the vehicle disposed of?",
      ["₦250,000 loss", "₦50,000 loss", "₦450,000 profit", "₦575,000 profit"], D,
      "Depreciation is 25% × ₦1,000,000 = ₦250,000 a year; from 1 Jan 1998 to 30 June 2001 is 3½ years = ₦875,000, so NBV = ₦125,000 and profit = 700,000 − 125,000 = ₦575,000."),
    q("Given: I. Order of permanence; II. Order of liquidity; III. Vertical order; IV. Horizontal order. The orders in which balance sheet assets are arranged are",
      ["I and II", "I and IV", "II and III", "III and IV"], A,
      "Balance sheet assets are listed either in order of permanence (fixed assets first) or in order of liquidity (cash first); vertical and horizontal are layouts, not orders. Today the balance sheet is called the statement of financial position."),
    q(TB1516 + "What is the capital employed?",
      ["₦44,600", "₦43,052", "₦43,044", "₦38,600"], C,
      "Here capital employed is taken as total assets: 18,470 + 5,120 + 3,462 + 3,000 + 11,474 + 1,518 = ₦43,044."),
    q(TB1516 + "Calculate the value of fixed assets",
      ["₦15,992", "₦18,470", "₦27,000", "₦27,052"], D,
      "Fixed assets = land and building ₦18,470 + furniture and fittings ₦5,120 + motor vehicles ₦3,462 = ₦27,052."),
    q("Provision for discount allowed can be recorded as a debit to",
      ["the profit and loss account and a credit to provision for discount allowed", "provision for discount allowed and a credit to the profit and loss account", "discount allowed and a credit to the profit and loss account", "expenses and a credit to customers' account"], A,
      "Creating a provision for discount allowed is an expense of the period: debit profit and loss account, credit provision for discount allowed (which is then deducted from debtors)."),
    q(STK + "Calculate the price per unit of closing stock using the periodic weighted average method.",
      ["₦3.20", "₦3.00", "₦2.20", "₦2.00"], D,
      "Periodic weighted average = total cost ÷ total units = (400 + 400 + 600 + 600) ÷ 1,000 = ₦2,000 ÷ 1,000 = ₦2.00 per unit. Stock is now called inventory."),
    q(STK + "Using the periodic simple average method, the cost per unit is",
      ["₦4.25", "₦3.25", "₦2.25", "₦1.25"], C,
      "Simple average = sum of the unit prices ÷ number of prices = (1 + 2 + 3 + 3) ÷ 4 = ₦9 ÷ 4 = ₦2.25, ignoring the quantities."),
    q(PLC + "Calculate the closing balance of the ledger account",
      ["₦6,900", "₦6,400", "₦5,000", "₦4,000"], C,
      "Credit purchases = 150% × 8,000 = ₦12,000. Credit side = 2,900 + 12,000 + 1,600 + 2,000 = ₦18,500; debit side = 1,000 + 1,500 + 8,000 + 3,000 = ₦13,500; balance c/d = ₦5,000."),
    // paper 21–30
    q(PLC + "Determine the credit purchases",
      ["₦15,500", "₦13,500", "₦13,400", "₦12,000"], D,
      "Credit purchases are 150% of cash paid to suppliers: 1.5 × ₦8,000 = ₦12,000."),
    q("In a control account, provision for bad debts is found on the",
      ["debit side of the purchases ledger control account", "debit side of the sales ledger control account", "credit side of the purchases ledger control account", "credit side of the sales ledger control account"], D,
      "Provision for bad debts relates to debtors and reduces them, so where it is shown it goes on the credit side of the sales ledger control account. In practice it is usually kept in a separate provision account."),
    q("The stock valuation data is important because it enables management to",
      ["separate debtors from creditors", "determine the cost of stock at the end of business", "determine the cost of stock at the beginning of business", "determine the total cost of goods purchased"], B,
      "Stock valuation (FIFO, LIFO, average) is used to put a cost on the stock left at the end of the trading period, which then gives cost of sales and profit. The cost of goods purchased comes from purchase invoices. Stock is now called inventory."),
    q("During the year ended 31st December 2001, Nuju Enterprises paid rent as follows:\nJan. 20 ₦24,000 for a period of 4 months\nMay 16 ₦30,000 for a period of 5 months\nOct. 15 ₦36,000 for a period of 6 months\nWhat is the overpaid portion of the rent?",
      ["₦36,000", "₦18,000", "₦12,000", "₦6,000"], B,
      "The payments cover 4 + 5 + 6 = 15 months but only 12 fall in 2001, so 3 months of the last payment are prepaid: 3 × (36,000 ÷ 6) = ₦18,000."),
    q("Advertising expenses incurred on a product in a business organization should be charged to",
      ["production department", "sales department", "administration department", "purchases department"], B,
      "Advertising helps to sell the product, so it is a selling expense charged to the sales department."),
    q("Four broad classifications of overheads are",
      ["production, selling, distribution and material", "production, selling, distribution and administration", "selling, distribution, production and wages", "distribution, selling, administration and material"], B,
      "Overheads are indirect costs, grouped by function as production (factory), selling, distribution and administration overheads; materials and wages are direct (prime) costs."),
    q("Given:\nCost of raw material issued to production ... ₦37,000\nOpening stock of raw material ... ₦2,000\nPurchases of raw material ... ₦38,000\nWages ... ₦5,000\n\nWhat is the closing stock of raw material?",
      ["₦4,000", "₦3,000", "₦2,000", "₦1,000"], B,
      "Closing stock = opening stock + purchases − issues = 2,000 + 38,000 − 37,000 = ₦3,000; wages do not affect raw material stock."),
    q(PQ + "The overhead cost is",
      ["₦71,050", "₦68,250", "₦67,970", "₦66,080"], A,
      "Wages are direct labour; the overheads are salary 63,000 + factory lighting 3,080 + plant depreciation 2,800 + factory insurance 2,170 = ₦71,050."),
    q(PQ + "The company consumed raw materials worth",
      ["₦54,600", "₦56,000", "₦57,400", "₦59,500"], A,
      "Raw materials consumed = opening stock + purchases − closing stock = 3,500 + 56,000 − 4,900 = ₦54,600."),
    q("Income and expenditure account is more informative than receipts and payments account because it discloses",
      ["cash", "cheques", "debtors", "stocks"], C,
      "The income and expenditure account is prepared on the accruals basis, so it brings in amounts owed to the club such as subscriptions in arrears (debtors), which a receipts and payments (cash) account ignores."),
    // paper 31–40
    q("A company has two departments X and Y. Y transferred goods to X at a profit margin of 25%. ₦10,000 worth of goods was not sold at the end of the accounting period. How much is the unrealized profit?",
      ["₦2,000", "₦2,500", "₦12,000", "₦12,500"], B,
      "A margin is profit as a percentage of the selling (transfer) price, so the profit inside ₦10,000 of unsold goods is 25% × 10,000 = ₦2,500.",
      { keyVerdict: 'corrected', keyAnswer: 'A', answerNote: "JAMB's answer, ₦2,000, treats the 25% as a mark-up on cost (10,000 × 25/125). A profit margin is measured on the selling price, so the unrealised profit is 25% × ₦10,000 = ₦2,500." }),
    q("Given:\nRich Social Club\nCash ... ₦100,000\nLoan ... ₦30,000\nSubscription in arrears ... ₦5,000\nSubscription in advance ... ₦15,000\n\nWhat is the accumulated fund?",
      ["₦60,000", "₦80,000", "₦90,000", "₦110,000"], A,
      "Accumulated fund = assets − liabilities = (100,000 + 5,000) − (30,000 + 15,000) = ₦60,000; subscriptions in arrears are an asset and in advance a liability."),
    q("A company has departments M and N. The expense incurred wholly in M is ₦5,000. General expenses incurred amount to ₦25,000. Expenses are apportioned in the ratio 2:3 for departments M and N respectively. What is N's share of the expenses?",
      ["₦10,000", "₦15,000", "₦18,000", "₦20,000"], B,
      "Only the general expenses are shared: N gets 3/5 × ₦25,000 = ₦15,000; the ₦5,000 incurred wholly in M is charged to M alone."),
    q(CLUB + "What is the receipts and payments account balance?",
      ["₦260,000", "₦233,000", "₦155,000", "₦100,000"], C,
      "Only cash counts: receipts ₦260,000 less payments (club house 100,000 + electricity 5,000 = 105,000) = ₦155,000."),
    q(CLUB + "What is the balance of the income and expenditure account?",
      ["₦300,000", "₦293,000", "₦193,000", "₦133,000"], B,
      "On the accruals basis income is all ticket sales ₦300,000; revenue expenditure is electricity 5,000 + salaries owed 2,000 = ₦7,000; surplus = ₦293,000. The club house and equipment are capital items."),
    q("The first step in converting a single entry to a double entry system of bookkeeping is to prepare a",
      ["suspense account", "statement of affairs", "realization account", "trial balance"], B,
      "Conversion starts with an opening statement of affairs listing assets and liabilities to find the opening capital, from which the double-entry accounts are opened."),
    q(EMEKA + "What is the capital at start?",
      ["₦53,000", "₦63,000", "₦73,000", "₦83,000"], D,
      "Capital = assets − liabilities = (70,000 + 58,000 + 100,000) − (85,000 + 60,000) = 228,000 − 145,000 = ₦83,000."),
    q("Receipts and payments account is the summary of",
      ["income and expenditure", "cash book", "balance sheet", "profit and loss"], B,
      "A receipts and payments account is a summary of a club's cash book: all cash and bank received and paid, of either a capital or revenue nature."),
    q("Given:\nTotal debtors b/d 31/12/99 ... ₦25,000\nCheques received from debtors ... ₦255,000\nTotal debtors c/d 31/12/00 ... ₦15,000\n\nDetermine the sales figure.",
      ["₦295,000", "₦265,000", "₦245,000", "₦215,000"], C,
      "Credit sales = cash received + closing debtors − opening debtors = 255,000 + 15,000 − 25,000 = ₦245,000."),
    q("Which of these is a capital expenditure warrant?",
      ["Provisional general warrant", "Development fund general warrant", "Reserved expenditure general warrant", "Supplementary warrant"], B,
      "In Nigerian government accounting, capital spending is from the Development Fund and is released by a development fund general warrant; the others authorise recurrent spending."),
    // paper 41–50
    q("For the purpose of conversion of a partnership to a company, a total purchase consideration of ₦3.6m was paid. If 30% of the purchase consideration was in cash and the rest by 50k shares, how many shares were issued?",
      ["1,080,000", "2,160,000", "3,600,000", "5,040,000"], D,
      "Shares part = 70% × ₦3,600,000 = ₦2,520,000; at 50k (₦0.50) each that is 2,520,000 ÷ 0.50 = 5,040,000 shares."),
    q("Given: I. The consolidated revenue fund balance b/d ₦650,000; II. Issues from contingency fund amounted to ₦240,000; III. Amount transferred to contingency fund is ₦210,000. What is the consolidated revenue fund balance?",
      ["₦1,100,000", "₦680,000", "₦440,000", "₦410,000"], C,
      "Only the transfer to the Contingencies Fund leaves the CRF: 650,000 − 210,000 = ₦440,000. Issues from the Contingencies Fund are spent on urgent needs and are not paid into the CRF.",
      { keyVerdict: 'corrected', keyAnswer: 'B', answerNote: "JAMB's answer, ₦680,000, adds the ₦240,000 issued from the contingency fund to the CRF. Money issued from the Contingencies Fund is spent on urgent expenditure, not paid into the CRF, so the balance is 650,000 − 210,000 = ₦440,000." }),
    q(BR + "The profit realized from the trade is",
      ["₦5,069", "₦1,817", "₦1,440", "₦1,328"], A,
      "Taking the expenses as paid out of branch takings, sales = 16,625 + 1,626 = ₦18,251; cost of sales = 1,875 + 13,400 − 118 − 1,975 = ₦13,182; trading (gross) profit = ₦5,069."),
    q(BR + "What is the total expenses?",
      ["₦1,875", "₦1,764", "₦1,626", "₦1,426"], C,
      "Expenses = rates and insurance 188 + wages 913 + rent 325 + sundry 200 = ₦1,626; stocks, goods and remittances are not expenses."),
    q("The necessary accounts to be opened on the issue of ordinary share capital are",
      ["preference share capital, cash and allotment accounts", "bank and ordinary share capital accounts", "cash and ordinary share capital accounts", "nominal value and ordinary share capital accounts"], B,
      "Money for shares is received through the company's bankers, so the entries are debit bank and credit ordinary share capital (with application and allotment accounts where shares are paid in instalments)."),
    q("The amount of each invoiced goods sent to the branch is debited to",
      ["branch expense account and credited to branch debtors' account", "branch stock account and credited to the goods sent to branch account", "branch debtors' account and credited to branch expense account", "goods sent to branch account and credited to branch expense account"], B,
      "Goods sent to a branch: debit branch stock account, credit goods sent to branch account."),
    q(ZEB + "The goodwill on purchase is",
      ["₦90,000", "₦30,000", "₦19,000", "₦18,000"], B,
      "Net assets taken over = (50,000 + 10,000 + 30,000 + 30,000) − 30,000 creditors = ₦90,000; goodwill = 120,000 − 90,000 = ₦30,000."),
    q(ZEB + "Calculate the net worth of the business",
      ["₦120,000", "₦90,000", "₦80,000", "₦100,000"], D,
      "Net worth = total assets − liabilities = 130,000 − 30,000 = ₦100,000, which equals ZEBRA's capital."),
    q("Gross profit in the branch adjustment account is transferred to the branch",
      ["trading account", "receipts and payments account", "profit and loss account", "income and expenditure account"], C,
      "The branch adjustment (mark-up) account holds the loading on goods; the realised gross profit in it is transferred to the branch profit and loss account."),
    q("Mamza Nigeria Limited issued 20,000 ordinary shares of ₦1.50 per share on 2nd July, 2002. 1,500 ordinary shares were fully subscribed for and their monies received as below:\nOn application ... ₦0.40\nOn allotment ... ₦0.20\nFirst call (including premium of ₦0.50) ... ₦0.70\nThe last and final call was yet to be made. What is the balance of the ordinary share capital account after the first call was received?",
      ["₦300", "₦1,050", "₦1,200", "₦1,950"], C,
      "Received per share = 0.40 + 0.20 + 0.70 = ₦1.30, of which ₦0.50 is premium, so ₦0.80 goes to share capital: 1,500 × 0.80 = ₦1,200."),
  ]);
})();
