/**
 * JAMB/UTME 2008 — PRINCIPLES OF ACCOUNTS
 * From the 2008 question paper (questions 1–50); answers from the JAMB/UTME Accounts answer key 2001–2020,
 * each checked independently. Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2008;
  const SRC = 'JAMB UTME 2008';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const ITEMS = "Use the following information: \nI. Cash at bank\nII. Cash in hand\nIII. Premises\nIV. Land\nV. Creditors\nVI. Loan from friends/bank\n\n";
  const TRAD = "Use the following information: \nTrading Account (Extract)\nOpening stock ... ₦19,500\nAdd purchases ... ₦68,700\n(Subtotal ... ₦88,200)\nLess closing stock ... ?\nCost of goods sold ... ?\nGross profit c/d ... ?\nTotal ... ?\nSales ... ₦96,000\nTotal ... ?\nThe gross profit margin is 20%.\n\n";
  const OWNER = "Use the following information: \nCapital ... ₦12,700\nDebtors ... ₦4,000\nSales ... ₦2,400\nPurchases ... ₦7,100\nStationery ... ₦1,900\nWages ... ₦1,230\nThe owner wishes to maintain an account equal to ¾ of capital as drawings.\n\n";
  const STK = "Use the following information: \nAug. 1 ... Received 20 units at ₦60 each\nAug. 6 ... Received 20 units at ₦68 each\nAug. 10 ... Issued 16 units\nAug. 20 ... Received 40 units at ₦80 each\nAug. 31 ... Issued 48 units\n\n";
  const NETA = "Use the following information: \nItem ... 31 Dec. 05 ... 31 Dec. 06\nTotal fixed assets ... ₦7,800 ... ₦6,600\nTotal current assets ... ₦12,100 ... ₦17,800\nTotal current liabilities ... ₦4,700 ... ₦3,800\nDrawings for 2006 is ₦5,200.\n\n";
  const MFG = "Use the following information: \nStock of materials 1/1 ... ₦10,000\nPurchase of raw materials ... ₦160,000\nManufacturing wages ... ₦420,000\nRoyalties ... ₦3,000\nStock of raw materials 31/12 ... ₦14,000\n\n";
  const DEPT = "Use the following information: \nDepartmental Trading Account (Extract)\nItem ... Total ... P ... Q\nStock ... ₦3,000 ... ₦2,000 ... ₦1,000\nPurchases ... ₦4,000 ... ₦2,500 ... ₦1,500\nSales ... ₦10,000 ... ₦6,000 ... ₦4,000\nClosing stock ... ₦2,000 ... ₦1,500 ... ₦500\nGoods worth ₦300 were transferred from department Q to P. Similarly, P's total expenses for the period were ₦200.\n\n";
  const UJU = "Use the following information: \nUju Nig. Ltd. Balance Sheet (Extract)\nCapital ... ₦200,000\nNet profit ... ₦50,000\n5% debenture ... ₦100,000\nCreditors ... ₦80,000\nTotal ... ₦430,000\nLand and building ... ₦250,000\nStock ... ₦120,000\nDebtors ... ₦50,000\nBank ... ₦10,000\nTotal ... ₦430,000\n\n";

  QUESTION_BANK.accounting = QUESTION_BANK.accounting.concat([
    // paper 1–10
    q("One of the major features of book keeping is that it",
      ["provides permanent records for all financial transactions", "is futuristic in nature", "accepts responsibility for all wrong postings", "does not give room for double entry procedure"], A,
      "Bookkeeping is the systematic recording of financial transactions, so it gives a permanent record of every transaction; it records the past, not the future, and it is built on double entry."),
    q("Which of the following accounting conventions suggests that accountants should use a method of valuation that understates rather than overstates results?",
      ["Conservatism", "Historical", "Monetary", "Cost"], A,
      "Conservatism (prudence) says: anticipate no profit but provide for all possible losses, so when in doubt, choose the lower figure for profit and assets."),
    q("A financial analyst needs accounting information to",
      ["maintain the production section of the business", "know why transactions cause increases and decreases in assets", "advise on how to manage the business", "know how to record transactions in T account"], C,
      "A financial analyst studies the accounts in order to interpret them and advise on how the business should be run and financed."),
    q("One basic assumption of the double entry theory is that it allows",
      ["two credit entries at the same time", "two debit entries at the same time", "debit and credit entries in the same account", "debit and credit entries in corresponding accounts"], D,
      "Double entry records every transaction twice: a debit in one account and a matching credit in a corresponding (other) account."),
    q("Use the following information: \nSales ... ₦4,000\nLight expenses ... ₦2,900\nRent ... ₦15,000\nPurchases ... ₦7,500\nDebtors ... ₦6,000\nCreditors ... ₦29,325\nDrawings ... ₦25\nBank ... ₦400\nGeneral expenses ... ₦1,500\n\nCalculate the total of the trial balance.",
      ["₦64,300", "₦46,825", "₦41,850", "₦33,325"], D,
      "Credits: sales ₦4,000 + creditors ₦29,325 = ₦33,325. Debits: ₦2,900 + ₦15,000 + ₦7,500 + ₦6,000 + ₦25 + ₦400 + ₦1,500 = ₦33,325, so each side totals ₦33,325."),
    q("Bariga, a stock broker, bought stationery for ₦12,000 by cash. To record this transaction, debit",
      ["cash and credit stationery", "purchases and credit stationery", "stationery and credit cash", "stationery and credit purchases"], C,
      "Stationery is an expense for a stock broker, not goods for resale, so the stationery account is debited and the cash account (which gives value) is credited."),
    q(ITEMS + "Determine the fixed assets.",
      ["I and V", "II and IV", "II and VI", "III and IV"], D,
      "Fixed assets are long-term assets held for use in the business: premises (III) and land (IV)."),
    q(ITEMS + "What are the current assets?",
      ["I and II", "I and IV", "II and IV", "III and V"], A,
      "Current assets are cash or items soon turned into cash: cash at bank (I) and cash in hand (II). Creditors and loans are liabilities."),
    q("Use the following information: \nCash Book\nDebit side: Capital ... ₦65,000\nSales ... ₦30,000\nCredit side: Purchases ... ₦12,250\nRent ... ₦9,100\nMotor vehicle ... ₦2,400\n\nFind the bank balance.",
      ["₦71,250 credit", "₦71,250 debit", "₦95,000 credit", "₦95,000 debit"], B,
      "Receipts ₦65,000 + ₦30,000 = ₦95,000; payments ₦12,250 + ₦9,100 + ₦2,400 = ₦23,750; balance ₦95,000 − ₦23,750 = ₦71,250, a debit balance (money in the bank)."),
    q("An entry made in the bank and cash columns of the cash book to record movement of cash between the office and the bank is the",
      ["real entry", "special entry", "direct entry", "contra entry"], D,
      "When cash is paid into the bank or withdrawn for office use, both sides of the entry are in the same cash book (cash column and bank column); this is a contra entry, marked 'C'."),

    // paper 11–20
    q("Abba offered 5% cash discount on goods worth ₦10,000. The discount allowed account is to be",
      ["debited with ₦10,000", "credited with ₦10,000", "debited with ₦500", "credited with ₦500"], C,
      "Discount allowed = 5% × ₦10,000 = ₦500. It is an expense (a loss) to the seller, so the discount allowed account is debited with ₦500."),
    q("Commission-on-turnover is charged on",
      ["current accounts only", "savings accounts only", "fixed deposit accounts only", "all bank accounts"], A,
      "Commission on turnover (COT) is a bank charge on the value of withdrawals from current accounts, the accounts operated by cheque."),
    q("The medium that enables the ATM to read the account details and process transactions directly with the account held in the bank is the",
      ["smart card", "communication network", "magnetic strip", "computerised account"], A,
      "The customer's ATM (smart) card carries the account details, which the machine reads before processing the transaction against the account in the bank."),
    q("Given that the balance as per cash book after adjustment was ₦6,315, unpresented cheques ₦1,000 and the bank statement balance ₦3,240, what was the balance of the uncredited cheques?",
      ["₦4,075", "₦4,240", "₦3,315", "₦3,075"], A,
      "Bank statement + uncredited cheques − unpresented cheques = adjusted cash book: ₦3,240 + X − ₦1,000 = ₦6,315, so X = ₦4,075."),
    q(TRAD + "What is the gross profit?",
      ["₦19,200", "₦12,900", "₦88,200", "₦76,800"], A,
      "Gross profit margin is gross profit as a percentage of sales: 20% × ₦96,000 = ₦19,200."),
    q(TRAD + "Determine the closing stock.",
      ["₦76,800", "₦67,800", "₦14,100", "₦11,400"], D,
      "Cost of goods sold = ₦96,000 − ₦19,200 = ₦76,800; closing stock = ₦88,200 − ₦76,800 = ₦11,400."),
    q(OWNER + "What is the amount withdrawn?",
      ["₦9,525", "₦9,000", "₦7,100", "₦6,400"], A,
      "Drawings = ¾ × ₦12,700 = ₦9,525."),
    q(OWNER + "Determine the closing balance of the cash book.",
      ["₦655 credit", "₦655 debit", "₦130 credit", "₦4,870 debit"], D,
      "Cash received: capital ₦12,700 + sales ₦2,400 = ₦15,100; cash paid: purchases ₦7,100 + stationery ₦1,900 + wages ₦1,230 = ₦10,230; balance = ₦4,870 debit. Debtors are not cash, and the ¾ drawings is only what the owner wishes to set aside."),
    q("The factors that determine the periodic depreciation charge are",
      ["asset cost, market value and useful life", "asset cost, market value and residual value", "asset value, cash value and useful life", "asset cost, salvage and useful life"], D,
      "Depreciation spreads cost less salvage (residual) value over the useful life, e.g. straight line = (cost − salvage) ÷ useful life."),
    q(STK + "Using the simple average method, what is the cost per unit of the closing stock?",
      ["₦80", "₦74", "₦64", "₦60"], A,
      "Batches are used up in date order: Aug 10 takes 16 of the ₦60 units; Aug 31 takes the last 4 at ₦60, all 20 at ₦68 and 24 at ₦80. The 16 units left are all from the ₦80 batch, so the simple average of the prices still in stock is ₦80.",
      { keyVerdict: 'corrected', keyAnswer: 'B', answerNote: "JAMB's key gives ₦74, the average of ₦68 and ₦80. But on 31 August the ₦60 batch was still in stock (4 units) and is used up by that issue, together with all the ₦68 units and 24 of the ₦80 units. The 16 units left all come from the ₦80 batch, so the closing stock is ₦80 a unit." }),

    // paper 21–30
    q(STK + "Using the FIFO method, what is the value of the closing stock?",
      ["₦1,280", "₦1,184", "₦1,024", "₦960"], A,
      "Units left = 80 received − 64 issued = 16. Under FIFO the oldest go out first, so the 16 left are from the latest batch at ₦80: 16 × ₦80 = ₦1,280."),
    q("In a period of inflation, which of the following methods normally gives a closing stock value very close to the market value?",
      ["FIFO", "LIFO", "Simple average", "Periodic simple average"], A,
      "FIFO issues the oldest (cheapest) units first, so the closing stock is made up of the latest purchases at the most recent prices, close to current market value."),
    q("The main purpose of control account is to",
      ["detect errors and irregularities", "assist purchases", "assist sales", "check management incompetence"], A,
      "A control account totals a whole ledger, so comparing it with the list of individual balances helps to find errors and discourage fraud."),
    q("Which of the following is a credit item in creditors ledger control account?",
      ["Purchases returns", "Bills payable", "Purchases", "Cash receipts"], C,
      "Credit purchases increase what is owed to suppliers, so they go on the credit side; returns outwards, bills payable and payments go on the debit side."),
    q("Discount allowed as represented in the control account appears on the",
      ["credit side of the purchases control account", "debit side of the purchases control account", "credit side of the sales control account", "debit side of the sales control account"], C,
      "Discount allowed reduces what customers owe, so it is credited to the sales ledger (debtors) control account."),
    q(NETA + "Determine the capital balance as at Dec. 31, 2005.",
      ["₦20,600", "₦15,200", "₦13,800", "₦11,600"], B,
      "Capital = net assets = ₦7,800 + ₦12,100 − ₦4,700 = ₦15,200."),
    q(NETA + "What is the closing capital for 2006?",
      ["₦15,400", "₦16,000", "₦12,600", "₦10,600"], A,
      "JAMB's answer is ₦15,400 (net assets ₦20,600 less drawings ₦5,200), but closing capital equals closing net assets, ₦6,600 + ₦17,800 − ₦3,800 = ₦20,600, which is not among the options.",
      { keyVerdict: 'none', keyAnswer: 'A', answerNote: "Closing capital equals closing net assets: ₦6,600 + ₦17,800 − ₦3,800 = ₦20,600, which is not offered. ₦15,400 deducts the ₦5,200 drawings a second time, although the drawings have already reduced the 2006 assets. (₦10,600 in D is the profit for 2006: ₦20,600 − ₦15,200 + ₦5,200.)" }),
    q("The floor space occupied by manufacturing and administrative departments in a company is 200 sqm and 300 sqm respectively. ₦20,000 rent incurred is shared using floor space occupied. How much is the rent chargeable to manufacturing?",
      ["₦8,000", "₦10,000", "₦12,000", "₦18,000"], A,
      "Manufacturing share = 200 ÷ (200 + 300) × ₦20,000 = ⅖ × ₦20,000 = ₦8,000."),
    q(MFG + "What is the cost of raw materials consumed?",
      ["₦173,000", "₦170,000", "₦160,000", "₦156,000"], D,
      "Raw materials consumed = opening stock ₦10,000 + purchases ₦160,000 − closing stock ₦14,000 = ₦156,000."),
    q(MFG + "Calculate the prime cost.",
      ["₦597,000", "₦579,000", "₦576,000", "₦567,000"], B,
      "Prime cost = materials consumed ₦156,000 + manufacturing wages ₦420,000 + royalties ₦3,000 = ₦579,000."),

    // paper 31–40
    q("Receipts and payments account discloses",
      ["debtors", "creditors", "prepayment", "cash balances for a period"], D,
      "A receipts and payments account is a summary of the cash book of a club, so it shows the opening and closing cash and bank balances, not debtors, creditors or prepayments."),
    q("Use the following information: \nSubscription in arrears 01/01/06 ... ₦2,000\nSubscription in advance 01/01/06 ... ₦1,500\nSubscription paid during the year ... ₦7,000\nSubscription in arrears 31/12/06 ... ₦3,000\n\nDetermine the amount of subscription included in the income and expenditure account for the year.",
      ["₦3,500", "₦7,000", "₦9,500", "₦13,500"], C,
      "₦7,000 received − ₦2,000 arrears for last year + ₦1,500 paid in advance last year for this year + ₦3,000 still owing for this year = ₦9,500."),
    q("The main reason for adopting a departmental account is to",
      ["record transactions for each department for better documentation", "tackle any recording problem as a result of expansion", "continuously evaluate the profitability of different departments", "ensure the departmental managers are adequately monitored"], C,
      "Departmental accounts show the gross and net profit of each department, so management can judge which departments are profitable."),
    q(DEPT + "What was department Q's gross profit?",
      ["₦2,500", "₦2,300", "₦2,200", "₦1,700"], B,
      "Q's cost of goods sold = ₦1,000 + ₦1,500 − ₦300 transferred out − ₦500 = ₦1,700; gross profit = ₦4,000 − ₦1,700 = ₦2,300."),
    q(DEPT + "Department P's net profit was",
      ["₦5,200", "₦3,000", "₦2,800", "₦2,500"], D,
      "P's cost of goods sold = ₦2,000 + ₦2,500 + ₦300 transferred in − ₦1,500 = ₦3,300; gross profit = ₦6,000 − ₦3,300 = ₦2,700; net profit = ₦2,700 − ₦200 = ₦2,500."),
    q("Given: \nI. Cost price\nII. Selling price\nIII. Cost plus fixed percentage\nIV. Price above cost and selling price\n\nFrom the information above, the prices used in charging goods to the branches are",
      ["I and II", "I, II and III", "I, II, III and IV", "III and IV"], B,
      "Head office may invoice goods to a branch at cost, at selling price, or at cost plus a fixed percentage; a price above the selling price is not used."),
    q("If a GSM operator based in Lagos supplies recharge cards to its branch in Akure, the head office can charge the goods at",
      ["selling price", "Akure price", "company price", "Lagos price"], A,
      "Recharge cards have a fixed selling price everywhere, so head office can invoice them to the branch at selling price and control the branch by stock and cash."),
    q("Use the following information: \nCapital: G ... ₦5,000\nT ... ₦8,000\nDrawings: G ... ₦2,000\nT ... ₦1,000\nInterest on capital 10%\nInterest on drawings 5%\n\nFind the interest on drawings of G.",
      ["₦50", "₦100", "₦200", "₦250"], B,
      "Interest on G's drawings = 5% × ₦2,000 = ₦100."),
    q("The entry in the partnership books of accounts for interest on drawings is to",
      ["credit partners capital account", "debit partners capital account", "credit drawings account", "debit drawings account"], B,
      "Interest on drawings is a charge to the partner: debit the partner's capital (or current) account and credit the profit and loss appropriation account."),
    q("In partnership dissolution, an asset taken over by a partner is debited to",
      ["partners capital account and credited to realization account", "partners capital account and credited to asset account", "assets account and credited to realization account", "realization account and credited to capital account"], A,
      "The partner receives the asset instead of cash, so his capital account is debited and the realisation account is credited with the agreed value."),

    // paper 41–50
    q("Goodwill can be in the balance sheet as",
      ["fixed tangible asset", "current asset", "fictitious asset", "liquid asset"], C,
      "Goodwill has no physical form and cannot be turned into cash on its own, so older texts list it with fictitious assets; today it is reported as an intangible asset."),
    q("Given: \nI. Ascertainment of the particulars of the proposed company\nII. Preparation of the incorporation documents\nIII. Filing of the documents\nIV. Registration of the company\n\nFrom the information above, the stages involved in the formation of a company are",
      ["I, II and III", "I, II, III and IV", "I, II and IV", "II, III and IV"], D,
      "Legal formation (incorporation) runs from preparing the incorporation documents, through filing them with the registrar, to registration of the company."),
    q("Cash received from the subscribed shares is recorded by debiting",
      ["application, allotment and crediting cash", "allotment and crediting cash", "cash and crediting subscribed shares", "cash, crediting application and allotment account"], D,
      "Money received on application and allotment is debited to cash (bank) and credited to the application and allotment account."),
    q("Ordinary shareholders received dividend before",
      ["creditors", "debtors", "preference shareholders", "deferred shareholders"], D,
      "Ordinary shareholders are paid after preference shareholders but before deferred (founders') shareholders, who come last."),
    q(UJU + "The debt ratio is approximately",
      ["43%", "42%", "41%", "23%"], B,
      "Debt ratio = total liabilities ÷ total assets = (₦100,000 + ₦80,000) ÷ ₦430,000 = 41.9%, about 42%.",
      { keyVerdict: 'corrected', keyAnswer: 'D', answerNote: "JAMB's key gives 23%, which is the debentures alone over total assets (₦100,000 ÷ ₦430,000). The debt ratio uses all the debts: (₦100,000 debentures + ₦80,000 creditors) ÷ ₦430,000 = 41.9%, about 42%; the options 43%, 42% and 41% are clearly built around this figure." }),
    q(UJU + "Which of the following is true of Uju Nig. Ltd?",
      ["It is a highly geared company", "It has no liquidity problem in the short term", "It is adequately secured in fixed assets", "Its working capital is zero"], B,
      "Current assets ₦180,000 (stock, debtors, bank) against creditors ₦80,000 give a current ratio of 2.25:1 and working capital of ₦100,000, so short-term debts can be met."),
    q("A source of revenue that is compulsory payment without any derivable benefit is",
      ["fees", "taxes", "fines", "royalties"], B,
      "A tax is a compulsory levy by government for which the taxpayer gets no direct benefit in return; fees and royalties buy a service or a right, and a fine is a penalty for an offence.",
      { bookletKey: 'C', bookletNote: "The booklet answer C (fines) describes a penalty for breaking a law, not a regular source of revenue paid by everyone. The standard definition of a tax is a compulsory payment to government without any direct benefit in return, so B (taxes) is right." }),
    q("Which of the following is among the categories of government cash book?",
      ["Receipts cash book", "Payment cash book", "Petty cash book", "Treasury cash book"], D,
      "Government keeps a treasury (main) cash book at the treasury and sub-treasuries, recording all receipts and payments of public funds."),
    q("The salary of the Chief Justice of the Federation is paid from the",
      ["consolidated revenue fund", "development fund", "contingency fund", "special fund"], A,
      "Under the Constitution, the salaries of the Chief Justice and other independent office holders are a direct charge on the Consolidated Revenue Fund, so they do not depend on yearly appropriation."),
    q("The Auditor-General of the Federation can be removed by the",
      ["National Assembly", "Chief Justice", "President", "Head of service"], C,
      "The President removes the Auditor-General of the Federation, acting on an address supported by two-thirds of the Senate (1999 Constitution, section 87)."),
  ]);
})();
