/**
 * JAMB/UTME 2018 — PRINCIPLES OF ACCOUNTS
 * From the 2018 question paper (questions 1–40);
 * answers from the JAMB/UTME Accounts answer key 2001–2020, each checked independently.
 * Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2018;
  const SRC = 'JAMB UTME 2018';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const DEPRIMUS = "Use the following information: \nDeprimus Education Consult had\nEarnings per share ... 47k\nDividends per share ... 30k\nPar value of each share ... ₦1.20\nMarket price per share ... ₦1.50\n\n";

  QUESTION_BANK.accounting = QUESTION_BANK.accounting.concat([
    // paper 1–10
    q("The amount paid by the new partner on admission as a compensation for the reputation built up by old partners is a",
      ["Bonus", "Goodwill", "Premium", "Commission"], B,
      "Goodwill is the value of a firm's reputation and customer connection; a new partner pays for a share of the goodwill the old partners built up."),
    q("Which of the following methods of invoicing goods to branches facilitates easy checks on the activities of branches?",
      ["Selling price", "Fixed percentage on cost", "Cost price", "Invoice price"], A,
      "When goods are invoiced to a branch at selling price, head office knows exactly how much cash or stock the branch should account for, so shortages are easy to detect.",
      { bookletKey: 'C', bookletNote: "The booklet answer C (cost price) gives head office no ready check, because the branch's sales cannot be compared with what it received. Invoicing at selling price does: goods sent at selling price minus sales should equal stock left at selling price, so any shortage shows up at once; that is A." }),
    q("When goods are sent to branch at cost plus mark up, it means that the branch should sell at",
      ["Price above or below the stipulated price", "Any price but not below the transfer price", "Cost price", "A price that is equal to the mark up"], A,
      "Under cost plus mark-up invoicing the head office does not fix the branch's selling price, so the branch is free to sell above or below the suggested price to suit its market."),
    q("In departmental accounting, which is not a transfer pricing?",
      ["cost based transfer price", "market-based transfer pricing", "Dual pricing system", "peak pricing"], D,
      "Goods passed between departments are priced at cost, at market price, or under a dual pricing system; peak pricing is a selling-price policy for times of high demand, not a transfer price."),
    q("What generally includes completing unfinished partnership business, collecting and paying debts, collecting partnership assets to be turned into cash and taking inventory?",
      ["Formation", "dissolution", "winding up", "termination"], B,
      "On dissolution of a partnership the firm completes unfinished business, realises its assets, collects and pays debts and settles with the partners through the realisation account."),
    q("Using the following: Balance as per cash book (overdraft) is ₦4,000, uncredited cheque is ₦2,300, bank charges ₦300, unpresented cheque ₦5,000. What is the adjusted cash book balance?",
      ["₦4,000", "₦300", "₦4,300", "₦5,000"], C,
      "Only bank charges are corrected in the cash book: an overdraft of ₦4,000 plus charges of ₦300 gives an adjusted overdraft of ₦4,300; uncredited and unpresented cheques go in the reconciliation statement."),
    q("Branch stock adjustment account is prepared at?",
      ["Cost price", "new price", "invoice price", "normal price"], C,
      "A branch stock adjustment (mark-up) account is needed when goods are sent to the branch at invoice (selling) price; it holds the profit loading so that branch stock can be shown at cost."),
    q("The excess of sales over cost of goods sold is?",
      ["gross sales", "gross profit", "net profit", "net sales"], B,
      "Gross profit = Sales − Cost of goods sold; net profit is what remains after expenses are also deducted."),
    q("The cost price method is applicable when",
      ["Goods are sold at specific prices", "goods are perishable", "goods attract different gross profit percentage", "to disclose gross profit or loss"], B,
      "Perishable goods often have to be sold below the planned price, so a fixed selling price cannot be set in advance and goods are sent to the branch at cost."),
    q("In dealing with incomplete record, fixed assets are posted to",
      ["Profit and loss account as brought forward figure", "Closing balance sheet as carried forward figure", "Closing balance sheet as brought forward figure", "Profit and loss as carried forward figure"], C,
      "Fixed assets are not income or expenses, so they never go to the profit and loss account; in incomplete records they are brought into the closing balance sheet (statement of financial position)."),
    // paper 11–20
    q("Which of the following should not be adjusted for in the profit and loss account?",
      ["Accruals", "inventory", "subscription", "depreciation"], C,
      "Accruals and depreciation are standard adjustments to a trader's final accounts, and inventory is adjusted in the trading section; subscriptions are the income of clubs, adjusted in the income and expenditure account."),
    q("In the absence of a partnership deed, the act stipulates that",
      ["an amount should be fixed as salaries for partners", "profits and losses should not be shared equally", "Interest on partner's loan should be 25%", "Interest should not be allowed on partners drawings"], D,
      "Under the Partnership Act 1890, without a deed, profits and losses are shared equally, no salaries or interest on capital are paid, no interest is charged on drawings, and loans earn 5%."),
    q("A cash book had an opening balance of ₦15,200, closing balance of ₦18,400 and total cash received during the period of ₦36,000. What was the amount of cash paid out during the same period?",
      ["₦29,200", "₦17,800", "₦32,800", "₦19,600"], C,
      "Payments = Opening balance + Receipts − Closing balance = ₦15,200 + ₦36,000 − ₦18,400 = ₦32,800."),
    q("Sule and Ahmed are in partnership sharing profit and losses equally. If Khadija is admitted as a new partner to take 1/5th as her share, what is the new profit or loss sharing?",
      ["Sule 1/3, Ahmed 1/3, Khadija 1/3", "Sule 1/2, Ahmed 1/2, Khadija 1/5", "Sule 1/5, Ahmed 1/5, Khadija 3/5", "Sule 2/5, Ahmed 2/5, Khadija 1/5"], D,
      "Khadija takes 1/5, leaving 4/5 for the old partners to share equally: 2/5 each."),
    q("Transfers from the head office to branches are best carried out at",
      ["Cost price", "Cost plus mark up", "Selling price", "Market price"], B,
      "Invoicing at cost plus a mark-up keeps the true cost from branch staff while covering head office's costs, and the loading can be removed later to show branch stock at cost."),
    q("Which of the following is a common cause of a discrepancy between head office and branch trial balances?",
      ["Stock and repayment", "Creditors and cash in transit", "Stock and cash in transit", "Debtors and cash in transit"], C,
      "Goods (stock) and cash sent by one office but not yet received and recorded by the other are the usual reasons why the head office and branch current accounts do not agree."),
    q("In the head office ledger, the value of goods sent to the branch are",
      ["Debited to the branch current account", "Debited to the head office current account", "Credited to the head office current account", "Credited to the branch current account"], A,
      "Head office keeps a branch current account, which is debited with goods sent because the branch now owes head office for them; the head office current account is kept in the branch's books.",
      { bookletKey: 'B', bookletNote: "The booklet answer B (debit the head office current account) describes an account that is kept in the branch's books, not the head office ledger. In the head office ledger the entry is debit branch current account, credit goods sent to branch, which is A." }),
    q("If the purchase price exceeds the net assets of a company, the excess amount is debited to",
      ["Cash account", "purchase account", "goodwill account", "sales account"], C,
      "Paying more for a business than the value of its net assets means paying for goodwill, so the excess is debited to goodwill account."),
    q("Gross profit in the branch adjustment account is transferred to the branch",
      ["Income and expenditure account", "profit and loss account", "receipt and payment account", "trading account"], B,
      "The balance on the branch stock adjustment account, after removing the loading on closing stock, is the branch gross profit, which is credited to the branch profit and loss account."),
    q("Ade, Tony, Rose share profit and losses in the ratio of 3 : 2 : 1 respectively. Ade retires and the remaining partners decide to take Ade's share in the existing ratio. What is the new ratio?",
      ["1 : 1", "3 : 6", "2 : 1", "2 : 6"], C,
      "If Tony and Rose absorb Ade's share in their existing ratio of 2 : 1, their new ratio stays 2 : 1 (2/3 and 1/3)."),
    // paper 21–30
    q("Calls in advance are treated in the balance sheet as",
      ["Current asset", "Fixed asset", "Current liability", "Fixed liability"], C,
      "Calls in advance are money received from shareholders before the call is due; the company owes it to them until the call is made, so it is shown as a liability, not as share capital."),
    q("Why are adjustments in the profit and loss account necessary?",
      ["To cover some expenses of the following year", "To show the provisions made during the year", "To show the total expenses paid and income received during the year", "To ascertain the actual expenses incurred and income earned during the year"], D,
      "Under the accruals concept, adjustments for accruals and prepayments make the profit and loss account show the expenses incurred and income earned in the year, not just the cash paid and received."),
    q("In reconciling the branch and head office accounts, remittance in transit in the branch books is treated as a",
      ["Debit entry", "Credit entry", "Reversal entry", "Contra entry"], A,
      "When the branch sends cash it debits the head office current account and credits cash; the remittance is a debit entry in the branch books that head office has not yet matched."),
    q("Profit or loss in a partnership is usually arrived at after deducting from gross profit all expenses including",
      ["Partners salaries", "Interest on capital", "Interest on loans", "Partners drawings"], C,
      "Interest on a partner's loan is a charge against profit, deducted in the profit and loss account; partners' salaries and interest on capital are appropriations, and drawings are not expenses."),
    q("Departmentalization of accounts is useful because it shows the",
      ["Overall performance of a division", "Cost per unit of a profit", "Price per unit of a product", "Overall performance of a firm"], A,
      "Departmental accounts show the results of each department (division) separately, so management can see which ones are doing well or badly."),
    q("Why should a new partner contribute towards goodwill on his admission?",
      ["It is a norm", "to ensure new partner also have a stake in the business", "the firm into which he is entering already has some goodwill in the market", "to purchase the business"], C,
      "The old partners built up the firm's reputation and customers; a new partner who will share future profits from that goodwill pays the old partners for it."),
    q("The rent expense for Trendy store is ₦3,500. Trendy store has three departments: jewelry, hair dressing, and clothing. The floor spaces occupied by the departments are 3:2:5 respectively. What is the rent allocated to clothing department?",
      ["₦700", "₦1,050", "₦1,750", "₦3,500"], C,
      "Rent is shared by floor area: total parts = 3 + 2 + 5 = 10; clothing = 5/10 × ₦3,500 = ₦1,750."),
    q(DEPRIMUS + "The company's earnings yield is?",
      ["20.00%", "25.00%", "31.33%", "39.17%"], C,
      "Earnings yield = Earnings per share ÷ Market price per share × 100 = 47k ÷ ₦1.50 × 100 = 31.33%."),
    q(DEPRIMUS + "What will be the price earnings ratio of the company?",
      ["3.91", "3.19", "2.95", "2.55"], B,
      "P/E ratio = Market price per share ÷ Earnings per share = ₦1.50 ÷ ₦0.47 = 3.19 times.",
      { bookletKey: 'D', bookletNote: "The booklet answer D (2.55) divides the par value by the earnings per share (₦1.20 ÷ ₦0.47 = 2.55). The price earnings ratio uses the market price: ₦1.50 ÷ ₦0.47 = 3.19, which is B." }),
    q("To account for expenses paid by head office on behalf of the branch, the branch should",
      ["Debit profit and loss account and credit head office account", "Debit head office account and credit cash", "Credit cash and debit profit and loss account", "Credit profit and loss account and debit head office account"], A,
      "The branch did not pay cash; it records the expense (debit profit and loss or the expense account) and the amount it now owes head office (credit head office current account)."),
    // paper 31–40
    q("Use the following information: \nItem ... ₦\nBalance as per cash book ... 13,560\nUnpresented cheques ... 5,120\nDividend received ... 2,000\nUncredited cheque ... 2,300\nBank charges ... 280\nStanding order ... 600\nBalance as per bank statement ... ?\n\nCalculate the balance in the bank statement.",
      ["₦10,740", "₦11,860", "₦16,380", "₦17,500"], D,
      "Adjusted cash book = ₦13,560 + ₦2,000 − ₦280 − ₦600 = ₦14,680; bank statement = ₦14,680 + ₦5,120 unpresented − ₦2,300 uncredited = ₦17,500."),
    q("Which of the following is not an inventory costing method?",
      ["FIFO", "LIFO", "Average cost method", "LILA"], D,
      "FIFO, LIFO and average cost are recognised stock valuation methods; LILA is not a method at all."),
    q("The major source of document which enables employer to calculate the employee wages is the",
      ["nominal roll of employees", "records of number of hours worked", "effort of the employee", "Record of dependants per employee"], B,
      "Wages are worked out from time records (clock cards or time sheets) showing hours worked, multiplied by the rate per hour."),
    q("The total credit sales for a period can be extracted from the",
      ["Cash book", "Sales day book", "Petty cash book", "Returns inwards"], B,
      "All credit sales of goods are first entered in the sales day book (sales journal), whose total for the period is posted to the sales account."),
    q("A machine bought for ₦35,000 was estimated to have a life span of 5 years with a scrap value of ₦9,000. If the scrap value is presently ₦15,000, what will be the yearly depreciation using the straight-line method?",
      ["₦4,000", "₦7,000", "₦11,000", "₦24,000"], A,
      "Using the revised scrap value: (₦35,000 − ₦15,000) ÷ 5 = ₦20,000 ÷ 5 = ₦4,000 a year."),
    q("A machine bought for ₦35,000 was estimated to have a life span of 5 years with a scrap value of ₦9,000. The yearly depreciation using the straight-line method would be",
      ["₦8,800", "₦6,500", "₦5,200", "₦4,400"], C,
      "Straight-line depreciation = (Cost − Scrap value) ÷ Life = (₦35,000 − ₦9,000) ÷ 5 = ₦26,000 ÷ 5 = ₦5,200."),
    q("The accounting entries used to record a cheque issued to a business are to",
      ["debit cash book and credit drawer", "credit cash book and debit drawer", "debit cash book and credit suspense account", "credit cash book and debit suspense account"], A,
      "A cheque received from a customer brings money into the bank, so the bank column of the cash book is debited and the drawer (the customer who wrote it) is credited."),
    q("In government accounting, the method used which records on the basis of financial entity with self-balancing books instead of entity of proprietorship is",
      ["virement", "fund accounting", "consolidated fund", "financial regulation"], B,
      "Government accounts are kept by funds: each fund is a separate financial entity with its own self-balancing set of books, rather than one proprietor's business."),
    q("Which of the following affects the accuracy and authenticity of trial balance?",
      ["error of omission", "error of commission", "error of transposition", "error of original entry"], C,
      "Errors of omission, commission and original entry leave debits equal to credits; a transposition (e.g. ₦369 posted as ₦396 on one side only) makes the trial balance disagree."),
    q("The major advantage of an imprest system is that it",
      ["ensures a proper accountability for every expenditure", "trains the young accountants in the preparation for greater responsibility", "relieves the chief cashier of the numerous petty cash payments", "serves as an analysis column for every expense"], A,
      "Under the imprest system the petty cashier is reimbursed only for what has been spent and vouchered, so every payment must be accounted for before the float is restored.")
  ]);
})();
