/**
 * JAMB/UTME 2004 — PRINCIPLES OF ACCOUNTS
 * From the 2004 question paper (questions 1–50, question 24 left out); answers from the JAMB/UTME
 * Accounts answer key 2001–2020, each checked independently. Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2004;
  const SRC = 'JAMB UTME 2004';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const CB = "Use the following information: \nCash Book\nCapital ... ₦6,600 | Purchases ... ₦3,500\nSales ... ₦3,000 | Stationery ... ₦1,300\nDebtors ... ₦2,500 | Wages ... ₦2,700\nThe owner wishes to maintain an amount equal to 1/3 of capital as drawings.\n\n";
  const ST = "Use the following information: \nDate ... Receipt (units) ... Issued (units)\nMay 2 ... 80 @ ₦3.00 ... -\nMay 10 ... 50 @ ₦3.20 ... -\nMay 17 ... - ... 20\nMay 25 ... - ... 60\nMay 31 ... 20 @ ₦2.90 ... -\n\n";
  const PL = "Use the following information: \nOpening balance ... ₦10,640\nPurchases ... ₦26,912\nReturns inwards ... ₦492\nReturns outwards ... ₦810\nCash discount received ... ₦1,348\nCash discount allowed ... ₦1,560\nCash paid to suppliers ... ₦20,808\nAt the year-end, the purchases ledger showed a debit balance of ₦108.\n\n";
  const INV = "Use the following information: \nBeginning inventory ... ?\nPurchases ... ?\nEnding inventory ... ₦4,800\nSales ... ₦12,800\nWages ... ₦1,040\nGross profit ... ₦5,900\nThe beginning inventory was estimated at 80% of sales.\n\n";
  const MF = "Use the following information: \nMaterials consumed ... ₦16,600\nDirect cost ... ₦5,400\nFactory rent ... ₦2,300\nFactory lighting ... ₦1,200\nCost of production to be transferred at cost plus 20% mark-up.\n\n";
  const CL = "Use the following information: \nOn January 1, 2000, a club's assets and liabilities were as follows:\nClub house ... ₦8,000\nSubscription in arrears ... ₦300\nCash ... ₦1,000\nWages owed ... ₦100\nThe club has 50 members and annual subscription is ₦100 per member. Subscription received is ₦4,000 and this includes 1999 arrears of ₦200.\n\n";
  const DP = "Use the following information: \nItem ... Dept. S ... Dept. T ... Total\nGross profit b/d ... ₦6,000 ... ₦4,000 ... ₦10,000\nLess: Salaries & wages ... ₦1,800 ... ₦1,200 ... ₦3,000\nElectricity ... ? ... ? ... ₦2,000\nDepreciation ... ₦600 ... ? ... ₦1,000\nNet profit c/d ... ? ... ₦1,600 ... ₦4,000\nIt is the tradition of the organization to apportion expenses in the proportion 60% : 40% for S and T respectively.\n\n";
  const PT = "Use the following information: \nJumoke and Kunle have an original investment of ₦25,000 and ₦15,000 respectively in a partnership. The articles of partnership provide 3% interest on capital and salaries of ₦1,500 and ₦1,000 respectively for the partners. The profit and loss are to be shared in the ratio 3:2. Miscellaneous expenses of ₦2,500 were incurred with gross profit of ₦6,500 during the financial year.\n\n";
  const SC = "Use the following information: \nShare capital ... Issued\n600,000 10% preference shares of ₦0.50 each ... -\n600,000 ordinary shares of ₦1 each ... ₦500,000\nCapital reserves ... ₦250,000\nRevenue reserves ... ₦207,000\nLong-term liabilities ... ₦400,000\nTotal ... ₦1,357,000\n\n";

  QUESTION_BANK.accounting = QUESTION_BANK.accounting.concat([
    // paper 1–10
    q("The accounting principle that is applied to check arbitrary actions on the part of accountants is",
      ["Consistency", "Materiality", "Objectivity", "Realization"], C,
      "The objectivity concept requires accounting records to be based on verifiable evidence, not on personal opinion, so it stops accountants from acting arbitrarily."),
    q("The loss of equipment in a fire disaster results in",
      ["a decrease in current asset", "an increase in liabilities and assets", "a decrease in assets and capital", "an increase in liabilities and a decrease in assets"], C,
      "Equipment destroyed by fire reduces fixed assets, and the loss is charged against profit, which reduces the owner's capital, so both sides of the equation fall."),
    q("A source document is used for verifying the",
      ["Amount due to creditors", "Actual cost of an asset", "Selling price of goods", "Amount due from debtors"], C,
      "Source documents such as the sales invoice are the first written evidence of a transaction; the invoice states the price at which goods were sold, so it is used to verify the selling price."),
    q("The rule of accounting equation requires that accounts payable should be placed under",
      ["Liabilities", "Equities", "Assets", "Capital"], A,
      "Accounts payable are amounts the business owes its suppliers, so in Assets = Capital + Liabilities they are liabilities."),
    q(CB + "The amount withdrawn is",
      ["₦2,100", "₦2,200", "₦4,400", "₦6,400"], B,
      "Drawings = 1/3 of capital = 1/3 × ₦6,600 = ₦2,200."),
    q(CB + "The cash book closing balance will be",
      ["₦900", "₦2,400", "₦4,200", "₦4,600"], B,
      "Receipts ₦6,600 + ₦3,000 + ₦2,500 = ₦12,100; payments ₦3,500 + ₦1,300 + ₦2,700 + drawings ₦2,200 = ₦9,700; balance ₦12,100 − ₦9,700 = ₦2,400."),
    q("A debit in the suspense account will appear in the balance sheet as",
      ["a current asset", "a current liability", "capital", "drawings"], A,
      "If a suspense account still has a debit balance when the balance sheet is drawn up, it is shown with the current assets until the errors are found."),
    q("The recipient whose name appears on cheque is called a",
      ["Payer", "Drawer", "Drawee", "Payee"], D,
      "The payee is the person named on the cheque to receive the money; the drawer writes the cheque and the drawee is the bank that pays it."),
    q("The imprest account is subsidiary to the",
      ["ledger account", "bank account", "cash book", "petty cash"], C,
      "Under the imprest system the petty cash book records small payments and is a subsidiary of the main cash book, from which the petty cashier's float is restored."),
    q("The three-column cash book differs from the two-column cash book in",
      ["Cash column", "Discount column", "Bank column", "Folio column"], B,
      "A two-column cash book has cash and bank columns; the three-column cash book adds a discount column on each side for discounts allowed and received."),
    // paper 11–20
    q("Zakari started business in January 2000. He bought a shop costing ₦54,000 and stock worth ₦7,600. Profit for the year amounted to ₦22,100. His closing capital was ₦73,800. Zakari's personal drawings amounted to",
      ["₦2,300", "₦9,900", "₦17,100", "₦19,500"], B,
      "Opening capital = ₦54,000 + ₦7,600 = ₦61,600; add profit ₦22,100 = ₦83,700; drawings = ₦83,700 − ₦73,800 = ₦9,900."),
    q("The balance on the provision for depreciation account is",
      ["added to fixed assets on the balance sheet", "deducted from fixed assets on the balance sheet", "deducted from the profit and loss account", "added to the current liabilities of the account"], B,
      "The accumulated depreciation is deducted from the cost of the fixed assets in the balance sheet to give their net book value."),
    q("Given: \nRates paid during the year amounted to ₦2,250 at ₦125 per month and ₦1,035 was paid for electricity in the same period at ₦115 per month. Determine the amount of prepaid rates.",
      ["₦345", "₦750", "₦1,380", "₦1,500"], B,
      "₦2,250 ÷ ₦125 = 18 months paid, but only 12 belong to the year, so 6 months are prepaid: 6 × ₦125 = ₦750."),
    q(ST + "What is the value of raw materials issued on May 17 based on the LIFO method?",
      ["₦60", "₦61", "₦62", "₦64"], D,
      "Under LIFO the latest receipts are issued first, so the 20 units on May 17 come from the May 10 batch: 20 × ₦3.20 = ₦64."),
    q(ST + "Based on the FIFO method of valuation, the total cost of raw materials issued is",
      ["₦150", "₦160", "₦240", "₦250"], C,
      "Under FIFO all 80 units issued (20 + 60) come from the May 2 batch at ₦3.00: 80 × ₦3.00 = ₦240."),
    q("Where closing stock is undervalued, the effect is",
      ["an increase in gross profit", "a decrease in gross profit", "an increase in purchases", "a decrease in purchases"], B,
      "Closing stock is deducted in finding cost of sales; if it is too low, cost of sales is too high and gross profit is understated."),
    q(PL + "The total on the debit side of the purchases ledger control account will be:",
      ["₦22,966", "₦22,156", "₦21,834", "₦21,054"], A,
      "Debit items: cash paid ₦20,808 + returns outwards ₦810 + discount received ₦1,348 = ₦22,966 (returns inwards and discount allowed belong to the sales ledger)."),
    q(PL + "The balancing figure in the purchases ledger control account is",
      ["₦15,828", "₦15,720", "₦14,940", "₦14,694"], D,
      "Credit side: ₦10,640 + ₦26,912 + debit balance c/d ₦108 = ₦37,660; less debit items ₦22,966 gives the closing credit balance of ₦14,694."),
    q("In a sales ledger, contra entry is found on the",
      ["debit side of the debtors' control account", "debit side of the creditors' control account", "credit side of the debtors' control account", "credit side of the creditors' control account"], C,
      "A contra (set-off) between a customer's and supplier's account reduces the amount owed by debtors, so it is credited in the sales ledger (debtors') control account."),
    q("The beginning and ending accounts receivable balances were ₦20,000 and ₦30,000 respectively. The collection from customers during the period was ₦70,000. What was the total sales on account?",
      ["₦20,000", "₦60,000", "₦80,000", "₦120,000"], C,
      "Credit sales = collections ₦70,000 + closing debtors ₦30,000 − opening debtors ₦20,000 = ₦80,000."),
    // paper 21–30 (24 left out)
    q("Given: \nGeneral expenses account\nPaid by cheque ... ₦671\nPaid by cash ... ₦70\nAccrued b/f ... ₦65\nAccrued c/f ... ₦115\n\nDetermine how much to be charged to profit and loss account.",
      ["₦606", "₦786", "₦791", "₦856"], C,
      "Charge = paid ₦671 + ₦70 − accrued b/f ₦65 + accrued c/f ₦115 = ₦791."),
    q("In converting single entry to final account, the balancing figures on the income and expenses accounts are transferred to the",
      ["revenue and expenditure account", "receipts and payments account", "profit and loss appropriation account", "profit and loss account"], D,
      "When incomplete records are converted, each income and expense account is balanced and the figure belonging to the year is transferred to the profit and loss account."),
    q(INV + "Determine the amount for the beginning inventory.",
      ["₦20,140", "₦10,240", "₦8,140", "₦7,240"], B,
      "Beginning inventory = 80% × sales ₦12,800 = ₦10,240."),
    q("Cost classification in relation to charges is determined by the level of",
      ["raw materials", "labour", "activity", "profitability"], C,
      "Costs are classified as fixed, variable or semi-variable according to how they behave as the level of activity (output) changes."),
    q(MF + "The gross profit on manufacture is",
      ["₦6,120", "₦6,100", "₦5,100", "₦5,000"], C,
      "Cost of production = ₦16,600 + ₦5,400 + ₦2,300 + ₦1,200 = ₦25,500; manufacturing profit = 20% × ₦25,500 = ₦5,100."),
    q(MF + "The market value of goods produced is",
      ["₦30,500", "₦30,600", "₦31,600", "₦31,620"], B,
      "Transfer value = cost of production ₦25,500 + 20% mark-up ₦5,100 = ₦30,600."),
    q(CL + "The accumulated fund is",
      ["₦9,400", "₦9,300", "₦9,200", "₦9,100"], C,
      "Accumulated fund = assets (₦8,000 + ₦300 + ₦1,000 = ₦9,300) − liabilities (wages owed ₦100) = ₦9,200."),
    q(CL + "In the balance sheet, the subscription in arrears will be",
      ["₦200", "₦300", "₦1,200", "₦1,300"], D,
      "Current year due 50 × ₦100 = ₦5,000, received ₦4,000 − ₦200 = ₦3,800, so ₦1,200 is unpaid; ₦100 of the old ₦300 arrears is also still unpaid: ₦1,200 + ₦100 = ₦1,300."),
    q("Where the debit side of the income and expenditure account is higher than the credit side, the difference is a",
      ["Deficit", "surplus", "Gain", "loss"], A,
      "When expenditure (debit) exceeds income (credit) in a not-for-profit body's income and expenditure account, the difference is called a deficit."),
    // paper 31–40
    q("In the balance sheet of a not-for-profit making organization, subscription paid in advance is regarded as a",
      ["current asset", "current liability", "capital", "reserve"], B,
      "Subscriptions received in advance are owed to members as future services, so they are shown as a current liability."),
    q("A rapidly growing business organization with multiple units that is interested in comparing the performances and weakness of each unit should adopt",
      ["manufacturing accounts", "consolidated accounts", "departmental accounts", "joint venture accounts"], C,
      "Departmental accounts show the trading results of each unit separately, so management can compare their performance and spot weak units."),
    q(DP + "What is the net profit by department S?",
      ["₦3,600", "₦3,000", "₦2,400", "₦2,000"], C,
      "S's electricity = 60% × ₦2,000 = ₦1,200; net profit = ₦6,000 − ₦1,800 − ₦1,200 − ₦600 = ₦2,400."),
    q(DP + "The depreciation to be charged to department T is",
      ["₦300", "₦400", "₦500", "₦600"], B,
      "Total depreciation ₦1,000 − S's ₦600 = ₦400, which is also 40% × ₦1,000."),
    q("How are credit sales by a department treated?",
      ["the same way as normal debtors' transactions", "in a different way from normal debtors' transactions", "as an addition to the sales manager's account", "as an addition to the production manager's account"], A,
      "A department's credit sales are recorded like any other credit sales: debit the customer (debtors) and credit that department's sales."),
    q("Discounts granted to branch customers are treated as a debit to branch",
      ["stock account and a credit to branch debtors' account", "discount account and a credit to branch bank account", "stock account and a credit to branch bank account", "discount account and a credit to branch debtors' account"], D,
      "A discount allowed to a branch customer is an expense of the branch and reduces what the customer owes: debit branch discount account, credit branch debtors' account."),
    q("Transfers from the head office to branches are best carried out at",
      ["cost price", "selling price", "cost plus mark-up", "market price"], C,
      "Goods are usually sent to branches at cost plus a mark-up (invoice price), which lets head office control branch stock and hides the true cost from branch staff."),
    q("On dissolution, the final distribution of cash to partners is based on",
      ["partnership agreement", "articles of association", "goodwill", "capital balances"], D,
      "After assets are realised and liabilities paid, the remaining cash is paid to partners according to the final balances on their capital accounts."),
    q(PT + "The balance of profit and loss account will be",
      ["₦4,000", "₦2,800", "₦1,500", "₦300"], A,
      "Net profit = gross profit ₦6,500 − miscellaneous expenses ₦2,500 = ₦4,000, the balance carried to the appropriation account."),
    q(PT + "What is Kunle's share of the profit?",
      ["₦600", "₦300", "₦180", "₦120"], D,
      "₦4,000 − interest on capital (₦750 + ₦450) − salaries (₦1,500 + ₦1,000) = ₦300 residual profit; Kunle's 2/5 × ₦300 = ₦120."),
    // paper 41–50
    q("When a new partner is admitted to a partnership there is a need to revalue the",
      ["capital of the business", "capital and liabilities of the business", "assets and capital of the business", "assets and liabilities of the business"], D,
      "On admission, assets and liabilities are revalued so that gains or losses up to that date go to the old partners in their old profit-sharing ratio."),
    q("The accounting entry to record the premium on goodwill is to debit",
      ["cash and credit old partners' capital", "goodwill and credit revaluation", "assets and credit capital", "capital and credit assets"], A,
      "A premium is cash the new partner pays for a share of goodwill; it is debited to cash and credited to the old partners' capital accounts in their sacrificing ratio."),
    q("The expenses incurred in promoting a company are:",
      ["promoters' expenses", "floating expenses", "preliminary expenses", "the board's expenses"], C,
      "Costs of forming a company (legal fees, registration fees, stamp duties, printing of documents) are called preliminary or formation expenses."),
    q("Debentures can be redeemed out of",
      ["existing share capital reserve", "existing general reserve", "proceeds from new issue of shares", "withholding tax"], B,
      "Debentures may be redeemed out of profits, by using the general reserve (often through a debenture redemption reserve), so funds kept in the business from profits pay off the loan.",
      { keyVerdict: 'multiple', alsoAccept: [C], keyAnswer: 'B',
        answerNote: "C is also accepted. Textbooks give two main sources for redeeming debentures: out of profits (such as the general reserve) and out of the proceeds of a new issue of shares or debentures, so both B and C are correct." }),
    q(SC + "What is the value of the authorized share capital?",
      ["₦500,000", "₦600,000", "₦750,000", "₦900,000"], D,
      "Authorised capital = preference 600,000 × ₦0.50 = ₦300,000 + ordinary 600,000 × ₦1 = ₦600,000, total ₦900,000."),
    q(SC + "The value of the owner's equity is",
      ["₦400,000", "₦600,000", "₦957,000", "₦1,357,000"], C,
      "Owners' equity = issued share capital ₦500,000 + capital reserves ₦250,000 + revenue reserves ₦207,000 = ₦957,000; long-term liabilities are not equity."),
    q("Share premium is an example of",
      ["revenue reserves", "capital reserves", "general reserves", "loan capital"], B,
      "Share premium arises from issuing shares above nominal value, not from trading, so it is a capital reserve that cannot be paid out as dividend."),
    q("According to the provisions of the 1999 constitution, all revenue generated by the Federal Government must be paid into the",
      ["Consolidated Revenue Fund", "Federation Account", "Revenue Mobilization Allocation and Fiscal Commission's account", "Equalization Fund"], A,
      "Section 80 of the 1999 Constitution says all revenues or other moneys raised or received by the Federation must be paid into one Consolidated Revenue Fund of the Federation, unless a law directs them to a special fund."),
    q("The budget statement presented to the legislature by the Chief Executive is called",
      ["an appropriation act", "a budget bill", "an appropriation bill", "a budget proposal"], C,
      "The President or Governor presents the budget to the legislature as an Appropriation Bill; once passed and signed it becomes the Appropriation Act."),
    q("The statement of assets and liabilities in the public sector can be described as the",
      ["income and expenditure account of government", "appropriation account of government", "balance sheet of government", "funds flow statement of government"], C,
      "A statement of assets and liabilities is a balance sheet; under IPSAS, which Nigeria's governments now use, it is called the statement of financial position."),
  ]);
})();
