/**
 * JAMB/UTME 2014 — PRINCIPLES OF ACCOUNTS
 * From the 2014 question paper (questions 2–50; Q1, the question-paper-type item, left out);
 * answers from the JAMB/UTME Accounts answer key 2001–2020, each checked independently.
 * Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2014;
  const SRC = 'JAMB UTME 2014';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const BS = "Use the following information: \nBalance sheet (Extract)\nCreditors ... ₦7,940\nPrepaid expenses ... ₦290\nAccrual expenses ... ₦323\nStock ... ₦4,500\nCash balance ... ₦4,956\nDebtors ... ₦905\n\n";
  const BOOKS = "Use the following information: \n2/3 Purchases 900 books at ₦1,000 each\n4/3 Purchases 590 books at ₦950 each\n15/3 Sales 300 books at ₦900 each\n\n";
  const SUBS = "Use the following information: \nSocial Club Subscription (Extract)\n31/12/2009 Subscription accrued ... ₦18,900\nSubscription received in advance ... ₦16,400\nSubscription received during the year 2009 ... ₦38,570\n\n";
  const IE = "Use the following information: \nIncome and Expenditure (Extract)\nBal. b/d ... ₦390\nSales of tickets ... ₦4,000\nDonations ... ₦3,000\nSubscriptions ... ₦6,500\nExpenses on cleaning ... ₦300\nNew tool ... ₦510\nRepairs ... ₦400\nElectricity ... ₦350\n\n";
  const HUS = "Use the following information: \nHussaina Enterprises sent goods worth ₦800,000 at cost plus mark-up of 25% to its branch.\n\n";
  const OIL = "Use the following information: \nOil and Buns issued to the public 1,300,000 ordinary shares of 75k at a price of ₦1.50. Application and allotment were received for 900,000 shares at 25k each.\n\n";

  QUESTION_BANK.accounting = QUESTION_BANK.accounting.concat([
    // paper 2–10 (paper Q1, the question-paper-type item, is left out)
    q("One of the differences between bookkeeping and accounting is that the former",
      ["records data while the latter interprets", "is regarded as the language of the business while the latter ascertains its strength", "interprets data while the latter records it", "summarizes information while the latter communicates it"], A,
      "Bookkeeping is the recording stage; accounting goes further to summarise, analyse and interpret the recorded data for users."),
    q("The concept which states that revenue should be recognized at the point when the sale is deemed to have been made is",
      ["matching", "consistency", "realization", "going concern"], C,
      "The realisation concept says revenue is earned (recognised) when the sale takes place, normally when goods pass to the buyer, not when cash is received."),
    q("A cheque of ₦5,000 paid to Suleiman had been correctly entered in the cash book but had not been entered in Suleiman's account. To correct this error, debit Suleiman's account and credit",
      ["cash account", "bank account", "suspense account", "purchases account"], C,
      "Only one side (the credit in the cash book) was recorded, so the trial balance difference went to suspense; the correction is debit Suleiman ₦5,000, credit suspense ₦5,000.",
      { bookletKey: 'B', bookletNote: "The booklet answer B (bank account) would credit the bank a second time, although the cash book entry was already correct. Only Suleiman's debit was missing, so the ₦5,000 difference sat in suspense: debit Suleiman ₦5,000, credit suspense ₦5,000, which is C." }),
    q("Aduke Motors bought three Toyota Hilux vans on cash at the cost of ₦6,000,000. On debiting the vehicle account, the corresponding credit for the purchase will appear in the",
      ["sales day book", "purchases day book", "sales subsidiary book", "cash book"], D,
      "A cash purchase of a fixed asset is paid out of cash, so the credit entry is made in the cash book."),
    q("Which of the following affects the accuracy and authenticity of the trial balance?",
      ["Error of omission", "Error of commission", "Error of transposition", "Error of original entry"], C,
      "A transposition (digits reversed, e.g. ₦54 posted as ₦45) on one side only makes the trial balance totals disagree; the other three errors leave the trial balance agreeing."),
    q("A ledger is classified into",
      ["private, sales and purchases", "personal, general and private", "general, private and sales", "sales, purchases and general"], B,
      "The ledger is commonly divided into the personal ledger (debtors and creditors), the general (nominal) ledger and the private ledger for the owner's confidential accounts."),
    q("The book of account in which information from the source documents are recorded consists of",
      ["debit and credit notes", "ledger and subsidiary books", "prepayments and accruals", "profit and loss and balance sheet"], B,
      "Source documents are first recorded in the subsidiary books (books of original entry) and then posted to the ledger."),
    q("The accounting entries to record a cheque issued by a business is to",
      ["debit cash book and credit drawer", "credit cash book and debit drawer", "debit cash book and credit suspense account", "credit cash book and debit suspense account"], B,
      "Money paid out by cheque is credited in the bank column of the cash book and debited to the account of the person paid."),
    q("Given: If Emenike Enterprises settles its suppliers for goods purchased within 7 days, it can earn a cash discount of 12½%. Assuming ₦22,800 worth of goods were purchased and settled within 5 days, what will be the amount to be credited in the cash column of the company's cash book?",
      ["₦25,650", "₦22,800", "₦19,950", "₦18,240"], C,
      "Discount = 12½% × ₦22,800 = ₦2,850, so the cash paid and credited is ₦22,800 − ₦2,850 = ₦19,950."),
    // paper 11–20
    q("The major advantage of an imprest system is that it",
      ["ensures a proper accountability for every expenditure", "trains the young accountants in preparation for greater responsibilities", "relieves the chief cashier of the numerous petty cash payments", "serves as an analysis column for every expense"], C,
      "With an imprest float the petty cashier handles the many small payments, freeing the chief cashier and keeping the main cash book free of petty items."),
    q("Petty cash book records transactions on",
      ["the debit side only", "the credit side only", "both credit and debit sides", "reversed entry"], C,
      "The petty cash book is a ledger account: money received (the float) is on the debit side and petty payments on the credit side."),
    q("A major way by which the headquarters guard against fraud in branches on cash remittance is through the introduction of",
      ["imprest system only", "direct purchase by branch", "separate accountant for the branch", "credit sales by only the headquarters"], D,
      "When only head office can approve and record credit sales, the branch handles only cash sales, which must be remitted in full, so cash takings are easier to control."),
    q("I. Cash sales; II. Cash purchases; III. Cash discount allowed; IV. Cash payment; V. Cash receipts\nWhich of the following are recorded on the debit side of the cash book?",
      ["I and II", "I and III", "I and V", "I and IV"], C,
      "The debit side of the cash book records money coming in: cash sales and other cash receipts."),
    q("An item credited in the bank statement but yet to be recorded in the firm's cash book is",
      ["bank loan", "contract payment", "standing order", "direct deposit"], D,
      "A direct deposit (credit transfer) is paid straight into the bank by a customer, so it appears on the bank statement before the firm enters it in its cash book."),
    q("The formula for calculating depreciation using straight line method is",
      ["(Scrap value + Sales) ÷ Useful life", "(Cost − Scrap value) ÷ Useful life", "(Sales − Scrap value) ÷ Useful life", "(Sales − Purchases + Sales) ÷ Useful life"], B,
      "Straight-line depreciation spreads the cost less the scrap (residual) value evenly over the useful life."),
    q("The major focus of the trading account is to show",
      ["net profit", "gross margin", "total purchases", "total sales"], B,
      "The trading account compares sales with the cost of goods sold to show the gross profit (gross margin); net profit is found in the profit and loss account."),
    q("If goods were bought from Tanko at a cost price of ₦9,000 with a cash discount of 5%, how much will be paid assuming prompt payment was made?",
      ["₦4,500", "₦8,550", "₦9,000", "₦9,450"], B,
      "Discount = 5% × ₦9,000 = ₦450, so prompt payment is ₦9,000 − ₦450 = ₦8,550."),
    q("If machine X cost ₦600,000 with anticipated life span of five years and estimated scrap value of ₦50,000, using straight line method, depreciation charged for two years will be",
      ["₦700,000", "₦240,000", "₦220,000", "₦202,000"], C,
      "Yearly depreciation = (₦600,000 − ₦50,000) ÷ 5 = ₦110,000, so two years = ₦220,000."),
    q(BS + "The value of the current assets will be",
      ["₦10,361", "₦10,651", "₦17,396", "₦17,848"], B,
      "Current assets = prepaid expenses ₦290 + stock ₦4,500 + cash ₦4,956 + debtors ₦905 = ₦10,651."),
    // paper 21–30
    q(BS + "Determine the current liabilities.",
      ["₦8,553", "₦8,263", "₦7,940", "₦1,228"], B,
      "Current liabilities = creditors ₦7,940 + accrued expenses ₦323 = ₦8,263."),
    q("The excess of sales over cost of goods sold is",
      ["gross sales", "gross profit", "net profit", "net sales"], B,
      "Sales minus cost of goods sold gives gross profit."),
    q(BOOKS + "Determine the cost of goods sold using FIFO.",
      ["₦285,000", "₦300,000", "₦570,000", "₦600,000"], B,
      "Under FIFO the 300 books sold come from the first batch bought at ₦1,000, so cost of goods sold = 300 × ₦1,000 = ₦300,000."),
    q(BOOKS + "Calculate the value of closing stock using LIFO.",
      ["₦801,000", "₦1,100,500", "₦1,160,500", "₦1,175,500"], D,
      "Under LIFO the 300 sold come from the latest batch (₦950), leaving 290 × ₦950 = ₦275,500 plus 900 × ₦1,000 = ₦900,000: closing stock ₦1,175,500."),
    q("The control account is used in facilitating",
      ["the location of errors in the various accounts", "up to date bank transactions", "the payment of debts and liabilities of the firm", "assets distribution with respect to income"], A,
      "Control accounts check the accuracy of each ledger separately, so an error can be traced to the particular ledger that does not agree."),
    q("A book of account that possesses the features of both day book and ledger is",
      ["sales day book", "cash book", "purchases day book", "returns day book"], B,
      "The cash book is a book of original entry (day book) and also the cash and bank accounts of the ledger."),
    q("The value of the sales ledger control account is derived from the summation of",
      ["the total debtors' account", "the total creditors' account", "all day books", "both the debtors' and creditors' accounts"], A,
      "The sales ledger control account is a total debtors account: its balance equals the sum of the individual debtors' balances."),
    q("Subscription in arrears is treated in the balance sheet of a club as",
      ["current asset", "current liability", "fixed asset", "intangible asset"], A,
      "Subscriptions in arrears are amounts members still owe the club, so they are a current asset (like debtors).",
      { bookletKey: 'B', bookletNote: "The booklet answer B (current liability) describes subscriptions received in advance, which the club owes back in service to members. Subscriptions in arrears are money members still owe the club, so they are a current asset: A." }),
    q("Use the following information: \nMaina Merchants Trading and Profit and Loss Account (Extract)\nStock (1/1/2010) ... ₦80,000\nPurchases ... ₦90,000\nCost of goods available for sale ... ₦170,000\nStock (31/12/2010) ... ?\nCost of goods sold ... ?\nGross profit ... ₦150,000\nSales ... ₦300,000\nLess returns inwards ... ₦30,000 ... ₦270,000\n\nDetermine the closing stock.",
      ["₦30,000", "₦40,000", "₦50,000", "₦60,000"], C,
      "Cost of goods sold = net sales ₦270,000 − gross profit ₦150,000 = ₦120,000; closing stock = ₦170,000 − ₦120,000 = ₦50,000."),
    q(SUBS + "Determine the amount of subscription for the year.",
      ["₦57,470", "₦41,070", "₦40,210", "₦35,300"], B,
      "Subscription income = received ₦38,570 + accrued (in arrears) at year end ₦18,900 − received in advance for next year ₦16,400 = ₦41,070.",
      { bookletKey: 'A', bookletNote: "The booklet answer A (₦57,470) is ₦38,570 + ₦18,900 and forgets that the ₦16,400 received in advance belongs to next year. Correct working: ₦38,570 + ₦18,900 − ₦16,400 = ₦41,070, which is B." }),
    // paper 31–40
    q(SUBS + "What is the amount of subscription to be shown as liability in the balance sheet as at December 2009?",
      ["₦14,200", "₦16,400", "₦18,900", "₦20,500"], B,
      "Subscriptions received in advance (₦16,400) are owed to members as next year's membership, so they are a current liability; subscriptions accrued are an asset.",
      { bookletKey: 'C', bookletNote: "The booklet answer C (₦18,900) is the subscription accrued, i.e. money members still owe the club, which is a current asset. The liability is the ₦16,400 received in advance, which the club owes members as next year's membership: B." }),
    q(IE + "What is the total income for the period?",
      ["₦13,890", "₦13,500", "₦10,500", "₦9,500"], B,
      "Income = sales of tickets ₦4,000 + donations ₦3,000 + subscriptions ₦6,500 = ₦13,500; the ₦390 balance b/d is cash brought forward, not income.",
      { bookletKey: 'A', bookletNote: "The booklet answer A (₦13,890) adds the ₦390 balance b/d, but an opening balance is cash left over from last period, not income earned in this one. Income = ₦4,000 + ₦3,000 + ₦6,500 = ₦13,500, which is B." }),
    q(IE + "What is the balance carried down?",
      ["₦11,680", "₦11,930", "₦12,330", "₦13,430"], C,
      "Total receipts including the balance b/d = ₦13,890; payments = ₦300 + ₦510 + ₦400 + ₦350 = ₦1,560; balance c/d = ₦13,890 − ₦1,560 = ₦12,330."),
    q("Given:\nSales ... ₦180,000\nStock 1/1 ... ₦25,000\nPurchases ... ₦110,000\nSales returns ... ₦1,000\nPurchases returns ... ₦1,500\nGross profit ... ₦58,000\n\nDetermine the value of stock as at 31st December.",
      ["₦8,000", "₦9,500", "₦12,500", "₦15,500"], C,
      "Net sales ₦179,000 − gross profit ₦58,000 = cost of goods sold ₦121,000; goods available = ₦25,000 + ₦110,000 − ₦1,500 = ₦133,500; closing stock = ₦133,500 − ₦121,000 = ₦12,500."),
    q("In a departmental account, where no basis of apportionment exist, apportionment is",
      ["on profit basis", "according to employee decision", "according to material available", "on equal basis"], D,
      "When there is no sensible basis (such as floor area or sales) for sharing an expense, it is shared equally among the departments."),
    q("In a departmental account, the expenses to be apportioned on the basis of turnover is",
      ["carriage inwards", "returns outwards", "discount received", "carriage outwards"], D,
      "Carriage outwards is a cost of delivering goods sold, so it varies with sales and is shared in the ratio of each department's turnover.",
      { bookletKey: 'A', bookletNote: "The booklet answer A (carriage inwards) is a cost of buying goods, so it is shared in the ratio of purchases. Carriage outwards is a cost of delivering sales, so it is the expense shared on the basis of turnover: D." }),
    q("If goods are sent to branch at 25% on cost, what will be the cost of goods sent to the branch at a selling price of ₦100,000?",
      ["₦130,000", "₦125,000", "₦80,000", "₦75,000"], C,
      "With a 25% mark-up on cost, selling price = 125% of cost, so cost = ₦100,000 × 100/125 = ₦80,000.",
      { bookletKey: 'D', bookletNote: "The booklet answer D (₦75,000) takes 25% off the selling price, but the 25% is on cost, not on selling price. Cost = ₦100,000 × 100/125 = ₦80,000 (check: ₦80,000 + 25% = ₦100,000), which is C." }),
    q(HUS + "What is the cost price of the goods sent to the branch?",
      ["₦600,000", "₦620,000", "₦640,000", "₦700,000"], C,
      "The ₦800,000 includes a 25% mark-up on cost, so cost = ₦800,000 × 100/125 = ₦640,000.",
      { bookletKey: 'B', bookletNote: "The booklet answer B (₦620,000) does not come from any correct working. ₦800,000 is cost plus 25% of cost, so cost = ₦800,000 × 100/125 = ₦640,000 (check: ₦640,000 + ₦160,000 = ₦800,000), which is C." }),
    q(HUS + "Determine the profit on the goods sent to the branch at profit margin of 25% mark-up.",
      ["₦150,000", "₦160,000", "₦170,000", "₦180,000"], B,
      "Profit (mark-up) = ₦800,000 − cost ₦640,000 = ₦160,000, i.e. 25% of ₦640,000.",
      { bookletKey: 'D', bookletNote: "The booklet answer D (₦180,000) does not match the figures. Cost = ₦800,000 × 100/125 = ₦640,000, so the mark-up is ₦800,000 − ₦640,000 = ₦160,000 (25% of ₦640,000), which is B." }),
    q("In the absence of a partnership deed, the act stipulates that",
      ["an amount should be fixed as salary for partners", "interest on partners loan should be 25%", "interest should not be allowed on partners drawings", "profits and losses should not be shared equally"], C,
      "Under the Partnership Act 1890, without a deed no interest is charged on drawings, no salaries or interest on capital are paid, loans earn 5%, and profits and losses are shared equally.",
      { bookletKey: 'D', bookletNote: "The booklet answer D says profits and losses should NOT be shared equally, which is the opposite of the Partnership Act 1890 rule (they are shared equally). Of the options as printed, only C is a rule of the Act: no interest is charged on partners' drawings." }),
    // paper 41–50
    q("The profit of a branch is usually credited to the",
      ["adjustment account", "branch office goods accounts", "head office goods account", "head office current account"], D,
      "In the branch's own books the net profit is transferred to the head office current account (debit profit and loss, credit head office current account), because the profit belongs to head office.",
      { bookletKey: 'B', bookletNote: "The booklet answer B (branch office goods account) only records goods passing between head office and branch, never profit. The branch closes its profit to head office: debit profit and loss, credit head office current account, which is D." }),
    q("Where partnership is converted into a limited liability company, current account balances of partners are transferred to a",
      ["realization account", "savings account", "share capital account", "capital account"], D,
      "On conversion or dissolution, each partner's current account balance is transferred to his capital account, which is then settled with shares or cash.",
      { bookletKey: 'A', bookletNote: "The booklet answer A (realisation account) receives the firm's assets and liabilities and the purchase price, not the partners' current accounts. Each partner's current account balance is closed to his capital account: D." }),
    q("The expenses incurred in purchasing a vehicle is a",
      ["revenue expenditure", "capital expenditure", "recurrent expenditure", "concurrent expenditure"], B,
      "Costs of acquiring a fixed asset and getting it ready for use form part of its cost, so they are capital expenditure."),
    q("Payment for shares in excess of amount offered gives rise to",
      ["subscription in advance", "revenue reserves", "capital reserves", "calls-in-advance"], C,
      "An amount paid for shares above their nominal value is share premium, which is a capital reserve."),
    q("The details of the share capital which a company is authorized to issue is contained in the",
      ["Articles of Association", "Companies and Allied Matters Act", "Memorandum of Association", "Share capital certificate"], C,
      "The capital clause of the Memorandum of Association states the authorised share capital and how it is divided into shares. Under CAMA 2020, authorised share capital was replaced by a minimum issued share capital, still stated in the memorandum."),
    q("₦800,000 worth of ordinary shares of 50k were issued at ₦1 each, payable in full on application. The entry in the cash book would be to",
      ["credit ₦1,600,000", "debit ₦1,600,000", "credit ₦800,000", "debit ₦800,000"], B,
      "₦800,000 of 50k shares = 1,600,000 shares; at ₦1 each the cash received is ₦1,600,000, debited in the cash book.",
      { bookletKey: 'D', bookletNote: "The booklet answer D (₦800,000) is only the nominal value of the shares. ₦800,000 ÷ 50k = 1,600,000 shares, and each was paid for at ₦1, so cash received = ₦1,600,000, debited in the cash book: B." }),
    q(OIL + "Determine the amount received on application and allotment.",
      ["₦224,950", "₦225,000", "₦324,950", "₦325,000"], B,
      "Application and allotment money = 900,000 shares × 25k = ₦225,000."),
    q(OIL + "The book value of issued share capital is",
      ["₦675,000", "₦975,000", "₦1,350,000", "₦1,950,000"], B,
      "Share capital is recorded at nominal value: 1,300,000 × 75k = ₦975,000; the 75k premium per share goes to the share premium account.",
      { bookletKey: 'D', bookletNote: "The booklet answer D (₦1,950,000 = 1,300,000 × ₦1.50) includes the share premium, which is kept in a separate share premium account, not in share capital. Issued share capital = 1,300,000 × 75k = ₦975,000, which is B." }),
    q("The account of government into which all monies are received and from which all expenditures are disbursed is the",
      ["Federation account", "Petroleum Technology Development Fund", "Central Bank Account", "Development fund"], A,
      "The Federation Account receives all revenues collected by the Federation, and from it money is distributed to the federal, state and local governments to spend."),
    q("In government accounting, the method used which records on the basis of financial entity with self-balancing books instead of entity of proprietorship is",
      ["virement", "fund accounting", "consolidated fund", "financial regulation"], B,
      "Fund accounting treats each fund as a separate accounting entity with its own self-balancing set of books, instead of the proprietorship entity of business accounting.",
      { bookletKey: 'D', bookletNote: "The booklet answer D (financial regulation) is the set of rules governing how public money is handled, not a method of recording. Keeping self-balancing books for each fund as a separate entity is fund accounting: B." })
  ]);
})();
