/**
 * JAMB/UTME 2010 — PRINCIPLES OF ACCOUNTS
 * From the 2010 question paper (questions 2–50; Q1, the paper-type item, is left out); answers from the
 * JAMB/UTME Accounts answer key 2001–2020, each checked independently. Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2010;
  const SRC = 'JAMB UTME 2010';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const CB = "Use the following information: \nThree Column Cash Book (Extract)\nDebit side (Date ... Particulars ... Cash ... Bank)\n1 ... Bal. b/d ... ₦3,000 ... ₦4,000\n2 ... Cash sales ... ₦1,000 ... –\n3 ... Fatima ... ₦2,000 ... –\n4 ... Baffa ... ₦200 ... ₦300\nCredit side (Date ... Particulars ... Cash ... Bank)\n5 ... Electricity ... ₦200 ... ₦300\n6 ... Purchases ... ₦3,000 ... –\n7 ... Ahmad ... – ... ₦500\n8 ... Khadija ... ₦200 ... –\n\n";
  const TRD = "Use the following information: \nSales ... ₦10,900\nStock 1/1 ... ₦1,000\nStock 31/12 ... ₦2,000\nPurchases ... ₦4,000\nReturn outwards ... ₦800\nReturn inwards ... ₦600\nCarriage outwards ... ₦300\nCarriage inwards ... ₦200\n\n";
  const PBD = "Use the following information: \nSundry debtor ... ₦20,000\nProvision for bad debts ... ₦500\nProvision for bad debt at 4% of sundry debtors.\n\n";
  const SLC = "Use the following information: \nSales Ledger Control Account\nDebit side:\nBalance b/d ... ₦87,000\nCredit sales ... ?\nBills receivable dishonoured ... ₦58,000\nCheques ... ₦50,000\nCredit side:\nDiscount allowed ... ₦40,000\nBills receivable ... ₦50,000\nCash received ... ₦280,000\nReturns inwards ... ₦30,000\nBalance c/d ... ?\nCredit sales is given at 160% of cash received.\n\n";
  const RW = "Use the following information: \nItem ... 31/12/07 ... 31/12/08\nStocks ... ₦4,200 ... ₦3,900\nRates in advance ... ₦1,000 ... ₦1,500\nAccrued wages ... ₦1,150 ... ₦1,350\nCost of goods sold was valued at ₦6,000.\nCash paid for rates and wages during the year was ₦1,300 and ₦2,200 respectively.\n\n";
  const SA = "Use the following information: \nItem ... 31/12/08 ... 31/12/09\nFurniture and fittings ... ₦21,000 ... ₦28,000\nOffice equipment ... ₦9,800 ... ₦13,000\nDebtors ... ₦6,800 ... ₦5,200\nCreditors ... ₦4,900 ... ₦5,100\nCash at bank ... ₦7,000 ... ₦4,600\nAccrued electricity bills ... – ... ₦1,200\nMonthly drawings averaged ₦330.\n\n";
  const ABG = "Use the following information: \nAbingo Limited has three departments K, L and M.\n(i) Rent for the year ₦3,000\n(ii) Selling and distribution expenses ₦1,800\nDepartment ... Turnover ... Floor space (square metres)\nK ... ₦40,000 ... 120\nL ... ₦60,000 ... 80\nM ... ₦89,000 ... 100\n\n";

  QUESTION_BANK.accounting = QUESTION_BANK.accounting.concat([
    // paper 2–11
    q("The major function of accounting bodies in Nigeria is to",
      ["provide proper financial management of businesses", "provide good remuneration to the members", "promote the ethics of the profession", "show the dynamic nature of the profession"], C,
      "Professional bodies such as ICAN and ANAN regulate their members and set and enforce the profession's code of ethics and standards of conduct."),
    q("Ledger account is mainly classified into",
      ["nominal, real and personal accounts", "fixed and current accounts", "management, financial and public sector accounting", "bank and cash accounts"], A,
      "Ledger accounts are classified as personal accounts (people and firms), real accounts (assets) and nominal accounts (incomes and expenses)."),
    q("If salary account is debited instead of stationery account, the error committed is that of",
      ["commission", "omission", "principle", "compensation"], A,
      "Salary and stationery are both expense (nominal) accounts, so posting to the wrong account of the same class is an error of commission."),
    q("If stationery bought for ₦200 has been entered as ₦2,000, to correct this error",
      ["debit stationery with ₦2,200", "credit stationery with ₦1,800", "debit stationery with ₦1,800", "credit stationery with ₦2,200"], B,
      "Stationery was over-debited by ₦2,000 − ₦200 = ₦1,800, so the correction credits stationery account with ₦1,800."),
    q("The account which refers to the tangible assets of a company that is of permanent nature is the",
      ["personal account", "real account", "nominal account", "cash account"], B,
      "Real accounts record property and assets such as land, buildings, machinery and furniture."),
    q("The major feature of an invoice is that, it",
      ["passes information through the sales day book", "has cash and bank column", "specifies the particulars of goods bought", "indicates only the cash sales"], C,
      "An invoice is the source document for a credit sale; it lists the goods supplied, quantities, prices, terms and the total due."),
    q("The source documents include",
      ["cash book", "petty cash book", "general ledger", "credit notes"], D,
      "A credit note is a source document; the cash book, petty cash book and general ledger are books of account written up from source documents."),
    q(CB + "If Fatima was granted a discount of 2%, what will be the discount allowed?",
      ["₦20", "₦40", "₦60", "₦4"], B,
      "Discount allowed = 2% × ₦2,000 = ₦40."),
    q(CB + "Calculate the cash balance after the discount.",
      ["₦2,760", "₦4,300", "₦6,200", "₦2,400"], A,
      "Cash received: ₦3,000 + ₦1,000 + (₦2,000 − ₦40 discount) + ₦200 = ₦6,160; cash paid: ₦200 + ₦3,000 + ₦200 = ₦3,400; balance = ₦6,160 − ₦3,400 = ₦2,760."),
    q("A major cause of the discrepancy between bank statement and the cash book that overstates the bank statement balance is the",
      ["commission paid", "interest received", "direct payment", "direct withdrawal"], C,
      "A direct payment by a customer into the trader's bank account (a credit transfer) raises the bank statement balance before the trader records it in the cash book.",
      { keyVerdict: 'multiple', alsoAccept: [B], keyAnswer: 'C', answerNote: "Both direct payments by customers into the account (C) and interest received that the bank credits (B) raise the bank statement balance above the cash book until the trader records them, so both are accepted. Commission paid and direct withdrawals lower the bank statement balance." }),
    // paper 12–21
    q("The bank charges levied on a current account holder is the charges on",
      ["transaction", "turnover", "transfer", "cash received"], B,
      "Banks charge current account holders commission on turnover (COT), a charge based on the total value of withdrawals passing through the account.",
      { bookletKey: 'C', bookletNote: "The booklet answer C (transfer) is not the name of the charge. The charge on a current account is commission on turnover (COT), which is option B." }),
    q("The cause of discrepancies between the bank statement and the cash book that overstates the cash book is the",
      ["dividend received", "uncredited expenses", "uncredited cheques", "interest on lodgement"], C,
      "Uncredited cheques (lodgements) are already debited in the cash book but not yet credited by the bank, so the cash book shows more than the bank statement."),
    q(TRD + "Find the gross profit.",
      ["₦7,800", "₦7,900", "₦9,700", "₦5,700"], B,
      "Net sales ₦10,900 − ₦600 = ₦10,300; cost of sales ₦1,000 + ₦4,000 − ₦800 + ₦200 − ₦2,000 = ₦2,400; gross profit = ₦10,300 − ₦2,400 = ₦7,900."),
    q(TRD + "The cost of goods available for sale is",
      ["₦4,600", "₦5,000", "₦6,400", "₦4,400"], D,
      "Cost of goods available for sale = opening stock ₦1,000 + purchases ₦4,000 − returns outwards ₦800 + carriage inwards ₦200 = ₦4,400."),
    q(PBD + "Determine the provision for bad debts to profit and loss account.",
      ["₦500", "₦820", "₦1,300", "₦300"], D,
      "New provision 4% × ₦20,000 = ₦800; only the increase over the old ₦500, i.e. ₦300, is charged to profit and loss."),
    q(PBD + "Calculate the provision to be taken to the balance sheet.",
      ["₦780", "₦800", "₦1,200", "₦200"], B,
      "The balance sheet shows the full new provision, 4% × ₦20,000 = ₦800, deducted from debtors."),
    q("Benefits enjoyed for which payments have not been made are",
      ["accruals", "prepayments", "acquisitions", "provisions"], A,
      "Accruals (accrued expenses) are services already received but not yet paid for at the end of the period."),
    q("If an organization maintains a periodic stock system, the stock quantities are",
      ["updated at the end of the accounting year", "not considered in the updating process", "updated continuously", "updated at the beginning of the accounting year"], A,
      "Under the periodic system stock is counted and updated only at the end of the period; continuous updating is the perpetual system.",
      { bookletKey: 'C', bookletNote: "The booklet answer C (updated continuously) describes the perpetual stock system. Under the periodic system stock is counted and updated at the end of the accounting year, option A." }),
    q("If a company values its stocks in the period of rising prices using LIFO method, there is a tendency for it to",
      ["have a higher cost of goods sold", "have a higher gross profit", "pay higher income tax", "have a higher value for closing stock"], A,
      "LIFO charges the latest, dearer purchases to cost of sales when prices rise, so cost of goods sold is higher and profit, tax and closing stock are lower.",
      { bookletKey: 'B', bookletNote: "The booklet answer B (higher gross profit) is what FIFO gives when prices rise. LIFO issues the latest, dearer goods first, so cost of goods sold is higher and gross profit is lower: option A." }),
    q(SLC + "What is the balance c/d?",
      ["₦333,000", "₦234,000", "₦343,000", "₦243,000"], D,
      "Credit sales = 160% × ₦280,000 = ₦448,000; debits ₦87,000 + ₦448,000 + ₦58,000 + ₦50,000 = ₦643,000; credits ₦400,000; balance c/d = ₦243,000."),
    // paper 22–31
    q(SLC + "Calculate the value of credit sales.",
      ["₦558,000", "₦484,000", "₦448,000", "₦584,000"], C,
      "Credit sales = 160% × cash received ₦280,000 = ₦448,000."),
    q(RW + "What is the value of purchases for the year 2008?",
      ["₦6,000", "₦9,900", "₦14,100", "₦5,700"], D,
      "Purchases = cost of goods sold + closing stock − opening stock = ₦6,000 + ₦3,900 − ₦4,200 = ₦5,700."),
    q(RW + "Determine the total expenses to be charged to profit and loss account.",
      ["₦2,350", "₦1,600", "₦800", "₦3,150"], D,
      "Rates = ₦1,000 + ₦1,300 − ₦1,500 = ₦800; wages = ₦2,200 − ₦1,150 + ₦1,350 = ₦2,400; total = ₦3,200, which is not among the options.",
      { keyVerdict: 'none', keyAnswer: 'D', answerNote: "With the figures given, rates are ₦1,000 + ₦1,300 − ₦1,500 = ₦800 and wages are ₦2,200 − ₦1,150 + ₦1,350 = ₦2,400, so the total is ₦3,200, which is not an option. D (₦3,150) is the intended answer: it treats wages as ₦2,350 (option A) plus rates ₦800 (option C)." }),
    q(SA + "Find the opening capital.",
      ["₦39,700", "₦35,900", "₦35,740", "₦43,660"], A,
      "Opening capital = assets (₦21,000 + ₦9,800 + ₦6,800 + ₦7,000 = ₦44,600) − creditors ₦4,900 = ₦39,700."),
    q(SA + "Determine the net profit.",
      ["₦15,000", "₦3,960", "₦1,040", "₦8,960"], D,
      "Closing capital = ₦50,800 − ₦6,300 = ₦44,500; increase ₦4,800 + drawings ₦3,960 = net profit ₦8,760, which is not among the options.",
      { keyVerdict: 'none', keyAnswer: 'D', answerNote: "Closing assets are ₦28,000 + ₦13,000 + ₦5,200 + ₦4,600 = ₦50,800 and closing liabilities ₦5,100 + ₦1,200 = ₦6,300, so closing capital is ₦44,500. Net profit = ₦44,500 − ₦39,700 + drawings ₦3,960 = ₦8,760, not an option. D (₦8,960) comes from using the opening creditors (₦4,900) instead of the closing ₦5,100." }),
    q("The gross loss on manufacturing is always transferred to the",
      ["credit side of balance sheet", "debit side of profit and loss account", "credit side of profit and loss account", "debit side of balance sheet"], B,
      "A gross loss is a loss, so it is carried down to the debit side of the profit and loss account, where it adds to the expenses."),
    q("The depreciation on a motor vehicle that is being used for manufacturing and administration is charged to the",
      ["debit side of manufacturing and profit and loss account", "debit side of profit and loss account only", "credit side of profit and loss account only", "debit side of manufacturing and balance sheet"], A,
      "The charge is shared: the factory part is debited to the manufacturing account and the office part to the profit and loss account."),
    q("The prime cost is the total of the",
      ["production cost + selling expenses", "direct material + direct labour + direct expenses", "direct materials + work overhead expenses", "administrative expenses + selling + distribution expenses"], B,
      "Prime cost is the total of direct costs: direct materials, direct labour and direct expenses."),
    q("In the not-for-profit-making organization, the excess of income over expenditure is",
      ["deducted from the capital", "added to the accumulated fund", "added to the capital", "deducted from the accumulated fund"], B,
      "A club's surplus (excess of income over expenditure) is added to its accumulated fund, which takes the place of capital."),
    q("The equivalent of a club's receipts and payment account is the",
      ["trading account", "revenue account", "cash account", "suspense account"], C,
      "A receipts and payments account is a summary of the club's cash book, so it is the club's cash account."),
    // paper 32–41
    q("The summary of receipt and payments account represents",
      ["cash at hand", "journal proper", "general journal", "ledger accounts"], A,
      "The receipts and payments account summarises cash and bank transactions, and its closing balance is the cash at hand (and in bank)."),
    q(ABG + "How much rent is apportioned to department K?",
      ["₦1,200", "₦1,800", "₦2,000", "₦750"], A,
      "Rent is shared by floor space: K = 120/300 × ₦3,000 = ₦1,200."),
    q(ABG + "How much selling and distribution expenses is apportioned to department M?",
      ["₦800", "₦600", "₦400", "₦1,800"], B,
      "Selling and distribution expenses are normally shared by turnover: M = 89,000/189,000 × ₦1,800 ≈ ₦848, which is not among the options.",
      { keyVerdict: 'none', keyAnswer: 'B', answerNote: "Selling and distribution expenses are normally shared in the ratio of turnover: M = ₦89,000/₦189,000 × ₦1,800 ≈ ₦848, which is not an option. B (₦600) is what you get by sharing them by floor space, 100/300 × ₦1,800, which is not the usual basis for these expenses." }),
    q("The Akachala Limited has four departments W, X, Y and Z. The profits or loss of the departments were W ₦20,000 loss, X ₦25,000 profit, Y ₦30,000 loss and Z ₦18,000 profit. How much is the net profit or loss of the company?",
      ["₦7,000 loss", "₦5,000 loss", "₦5,000 profit", "₦7,000 profit"], A,
      "Profits ₦25,000 + ₦18,000 = ₦43,000; losses ₦20,000 + ₦30,000 = ₦50,000; net result = ₦7,000 loss."),
    q("If goods were returned to branch by the customers, the correct posting for this transaction is to debit",
      ["branch debtor's account and credit head office account", "head office account and credit branch stock account", "branch stock account and credit branch debtors' account", "branch cash account and credit branch stock account"], C,
      "Returns from branch customers put goods back into branch stock and reduce what branch debtors owe: debit branch stock, credit branch debtors."),
    q("The branch expenses paid by the head office is recorded in the books by debiting branch",
      ["bad debt account and crediting branch debtors' account", "expenses account and crediting bank account", "profit and loss account and crediting branch stock account", "discount allowed account and crediting branch debtors' account"], B,
      "Head office pays out of its bank, so it debits branch expenses account and credits bank account."),
    q("Goods returned to branch by branch customers is recorded in the head office books by debiting",
      ["bank account and crediting branch stock account", "goods sent to branch account and crediting branch debtors' account", "branch stock account and crediting branch debtors' account", "branch debtors' account and crediting cash account"], C,
      "The goods go back into branch stock and the customers owe less, so head office debits branch stock account and credits branch debtors' account.",
      { bookletKey: 'B', bookletNote: "The booklet answer B uses the goods sent to branch account, which records goods moving between head office and the branch, not returns by customers. Customer returns increase branch stock and reduce branch debtors: debit branch stock, credit branch debtors (option C)." }),
    q("Which of the following is mostly used in treating partners' current earnings?",
      ["Savings account", "Current account", "Capital account", "Share capital account"], B,
      "A partner's current account records the share of profit, salary and interest earned, less drawings, keeping the capital account fixed."),
    q("The salary of a partner is usually debited to the",
      ["sundry debtors' account", "appropriation account", "profit and loss account", "sundry current account"], B,
      "A partner's salary is a share of profit, not an expense, so it is debited in the profit and loss appropriation account."),
    q("The rules which govern the internal management of a firm and its financial affairs in a partnership business is a",
      ["memorandum", "bye-law", "deed", "financial regulation"], C,
      "The partnership deed (agreement) sets out capital, profit sharing, salaries, interest and the other rules the partners agree to."),
    // paper 42–50
    q("The interest on partners' loan is",
      ["debited in current account", "credited in profit and loss account", "debited in profit and loss account", "credited in current account"], C,
      "Interest on a partner's loan is an expense of the firm: it is debited in the profit and loss account (not the appropriation account) and credited to the partner's current account.",
      { keyVerdict: 'multiple', alsoAccept: [D], keyAnswer: 'A', bookletKey: 'A', bookletNote: "The answer often given, A (debited in current account), is the entry for drawings. Interest on a partner's loan is a charge against profit: debit profit and loss (C) and credit the partner, usually in the current account (D).", answerNote: "Interest on a partner's loan is a charge against profit, so it is debited in the profit and loss account (C) and credited to the partner, usually in the current account (D); both halves of the entry are correct. A (debited in current account) would reduce what the firm owes the partner, which is the treatment for drawings, not for interest the firm owes." }),
    q("The capital contributed by the partners is treated in the",
      ["current account", "capital account", "trading account", "balance sheet"], B,
      "Each partner's capital contribution is credited to that partner's capital account."),
    q("Given: \n6,000,000 10% preference shares of ₦0.50 each\n6,000,000 ordinary shares of ₦1 each\nCapital reserves ₦2,700,000\nLong-term liabilities ₦4,000,000\n\nFind the value of authorized share capital.",
      ["₦13,000,000", "₦12,000,000", "₦9,000,000", "₦15,700,000"], C,
      "Authorised share capital = 6,000,000 × ₦0.50 + 6,000,000 × ₦1 = ₦3,000,000 + ₦6,000,000 = ₦9,000,000; reserves and long-term liabilities are not share capital."),
    q("The Directors' salaries paid are items of",
      ["current liabilities", "profit and loss account", "trading account", "current assets"], B,
      "Directors' salaries (remuneration) are an expense of the company, charged in the profit and loss account."),
    q("Sundry debtors in the balance sheet of Onoja Bakery and Sons totalled ₦800,000. A provision of 2% was made for discount and 5% provision for bad and doubtful debts. Find the amount for sundry debtors after provision.",
      ["₦760,000", "₦744,800", "₦744,000", "₦784,000"], B,
      "Bad debts provision 5% × ₦800,000 = ₦40,000 leaves ₦760,000; discount provision 2% × ₦760,000 = ₦15,200; net debtors = ₦744,800."),
    q("An ordinary share of ₦80 was issued at ₦96. The share was issued at",
      ["premium", "par", "discount", "loss"], A,
      "Issuing above nominal value (₦96 for a ₦80 share) is an issue at a premium of ₦16."),
    q("The financial plan of the government for a year is contained in the",
      ["budget", "cash analysis book", "vote book", "gazette"], A,
      "The budget (the annual estimates of revenue and expenditure) is the government's financial plan for the year."),
    q("An increase in government expenditure within a year is taken care of by means of",
      ["financial regulations", "virement", "warrant", "supplementary estimate"], D,
      "When approved votes prove too small, extra spending during the year is authorised by a supplementary estimate (supplementary budget)."),
    q("As evidence of payments to a government ministry, the revenue collectors will issue",
      ["treasury receipt", "receipts voucher card", "treasury card", "stores receipt voucher"], A,
      "Government revenue collectors issue an official treasury receipt to anyone who pays money to a ministry."),
  ]);
})();
