/**
 * JAMB/UTME 2013 — PRINCIPLES OF ACCOUNTS
 * From the 2013 question paper (questions 2–50; Q1, the question-paper-type item, left out);
 * answers from the JAMB/UTME Accounts answer key 2001–2020, each checked independently.
 * Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2013;
  const SRC = 'JAMB UTME 2013';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const JULY = "Use the following information: \nJuly 1 - Started business with ₦10,500\nJuly 31 - Paid Agromachinex ₦6,000 owing them\n\n";
  const MACH = "Use the following information: \nA machine bought for ₦35,000 was estimated to have a life span of 5 years with a scrap value of ₦9,000.\n\n";
  const TRAD = "Use the following information: \nSales ... ₦232,000\nOpening stock ... ₦28,000\nPurchases ... ₦128,000\nCarriage inwards ... ₦4,000\nCarriage outwards ... ₦6,000\nClosing stock ... ₦10,000\nDiscount received ... ₦18,000\nExpenses ... ₦20,000\n\n";
  const CAP = "Use the following information: \nItem ... 1/1/2010 ... 31/12/2010\nCreditors ... ₦9,000 ... ₦9,800\nRent owing ... ₦3,800 ... ₦2,500\nRates prepaid ... ₦2,000 ... ₦3,500\nMotor van ... ₦8,000 ... ₦8,000\nPremises ... ₦10,500 ... ₦10,500\n\n";
  const RAW = "Use the following information: \nOpening stock of raw materials ... ₦75,000\nPurchases of raw materials ... ₦330,000\nClosing stock of raw materials ... ₦80,000\nDirect wages ... ₦30,000\nCarriage on raw materials ... ₦10,000\n\n";
  const DEPT = "Use the following information: \nDepartment ... K ... Y\nOpening stock ... ₦2,500 ... ₦800\nPurchases ... ₦120,000 ... ₦100,000\nSales ... ₦180,000 ... ₦200,000\nSalaries ... ₦8,000 ... ₦30,000\nClosing stock ... ₦3,000 ... ₦1,500\nRate expenses of ₦1,500 are apportioned in the ratio 1:2.\n\n";

  QUESTION_BANK.accounting = QUESTION_BANK.accounting.concat([
    // paper 2–10 (paper Q1, the question-paper-type item, is left out)
    q("Accounting information seeks to provide",
      ["permanent records for all transactions", "analysis of accounts to trade debtors", "audited reports on the accounts of a company", "data about the employees of a company"], A,
      "Accounting keeps a permanent, orderly record of every business transaction, from which summaries and reports are produced for users."),
    q("When the debit side total of an account exceeds the credit side total while balancing an account, it means that the account has",
      ["been overdrawn", "been understated", "debit balance", "credit balance"], C,
      "An account whose debit side is larger than its credit side has a debit balance; the balance c/d is entered on the credit side and brought down on the debit side."),
    q(JULY + "The double entry for July 1 would be",
      ["debit capital and credit cash", "credit cash and debit bank", "debit cash and credit capital", "debit purchases and credit cash"], C,
      "Starting business with cash brings cash in (debit cash) and creates the owner's capital (credit capital)."),
    q(JULY + "The double entry for July 31 would be",
      ["debit Agromachinex and credit cash", "debit equipment and credit Agromachinex", "credit capital and debit cash", "credit cash and debit purchase"], A,
      "Paying a creditor reduces what is owed to him (debit Agromachinex) and reduces cash (credit cash)."),
    q("The total credit sales for a period can be extracted from the",
      ["cash book", "sales day book", "petty cash book", "returns inwards"], B,
      "All credit sales of goods are first entered in the sales day book (sales journal), whose total for the period is posted to the sales account."),
    q("The major source document which enables an employer to calculate the employee wages is the",
      ["nominal roll of employees", "record of number of hours worked", "effort of the employee", "record of number of dependents per employee"], B,
      "Wages are worked out from the time records (clock cards or time sheets) showing hours worked, multiplied by the rate per hour."),
    q("Which of the following items is a capital expenditure?",
      ["Maintenance of office machine", "Purchase of office stationery", "Carriage inwards", "Purchase of office machinery"], D,
      "Buying office machinery acquires a fixed asset that will be used for several years, so it is capital expenditure; the others are revenue expenditure."),
    q("The corresponding entry of personal accounts found in the debit side of the cash book is to",
      ["credit real accounts", "debit real accounts", "credit the ledger", "debit the ledger"], C,
      "Money received from a person is debited in the cash book, so the double entry is a credit to that person's account in the ledger."),
    q("Alaka who owed Saka ₦15,000, settled his debt after deducting cash discount of 10%. To record the discount in the book of Saka, debit",
      ["discount received account and credit Alaka's account", "Alaka's account and credit discount received account", "Saka's account and credit discount received account", "discount allowed account and credit Alaka's account"], D,
      "Saka is the creditor who gave the discount, so in his books it is discount allowed (an expense): debit discount allowed ₦1,500 and credit Alaka's account."),
    // paper 11–20
    q("I. The amount of the imprest is the same from one organization to another.\nII. At the end of a fixed period, the petty cashier received a fixed sum of money.\nIII. At the end of a period, the petty cashier is reimbursed with the amount spent in that period.\nIV. The system is a method by which a measure of control is kept on petty cash expenses.\n\nWhich of the above is correct about the imprest system?",
      ["I, II and III", "I, III and IV", "II and IV", "III and IV"], D,
      "Under the imprest system the petty cashier is reimbursed at the end of each period with exactly what was spent (III), which keeps control over petty cash (IV); the imprest amount differs between organisations."),
    q(MACH + "The yearly depreciation using the straight line method would be",
      ["₦8,800", "₦6,500", "₦5,200", "₦4,400"], C,
      "Straight-line depreciation = (cost − scrap value) ÷ life = (₦35,000 − ₦9,000) ÷ 5 = ₦5,200 a year."),
    q(MACH + "If the scrap value is presently ₦15,000 what will be the yearly depreciation using straight line method?",
      ["₦4,000", "₦7,000", "₦11,000", "₦24,000"], A,
      "With a scrap value of ₦15,000, yearly depreciation = (₦35,000 − ₦15,000) ÷ 5 = ₦4,000."),
    q("The purchase of mattresses from Freehold enterprises by cheque amounted to ₦305,150. The correct entries for this transaction in the book of the buyer is to debit",
      ["sales account and credit bank account", "purchases and credit bank account", "cash and credit freehold", "bank and credit freehold"], B,
      "Goods bought for resale and paid for by cheque are debited to purchases and credited to the bank account; Freehold is not involved because it was paid at once."),
    q(TRAD + "Calculate the gross profit.",
      ["₦100,000", "₦86,000", "₦82,000", "₦76,000"], C,
      "Cost of sales = ₦28,000 + ₦128,000 + ₦4,000 carriage inwards − ₦10,000 = ₦150,000; gross profit = ₦232,000 − ₦150,000 = ₦82,000."),
    q(TRAD + "Calculate the expenses debited to the profit and loss account.",
      ["₦17,000", "₦23,000", "₦26,000", "₦30,000"], C,
      "The profit and loss account is debited with carriage outwards ₦6,000 and expenses ₦20,000 = ₦26,000; carriage inwards goes to the trading account and discount received is income."),
    q("Given:\nOpening capital ... ₦1,500\nCapital introduced ... ₦500\nProfit for the year ... ₦800\nCash drawings ... ₦250\n\nCalculate the closing capital.",
      ["₦2,550", "₦2,500", "₦2,350", "₦2,250"], A,
      "Closing capital = opening capital ₦1,500 + capital introduced ₦500 + profit ₦800 − drawings ₦250 = ₦2,550."),
    q("What type of stock valuation would a vegetable seller adopt in valuing its product?",
      ["LIFO", "FIFO", "Simple average", "Weighted average"], B,
      "Vegetables are perishable, so the oldest stock must be sold first; FIFO (first in, first out) matches this physical flow."),
    q("The total cash and cheques received from customers in a control account is derived from the",
      ["purchases day book", "cash book", "income and expenditure account", "sales journal"], B,
      "All cash and cheques received are recorded in the cash book, so its totals supply the receipts figure in the sales ledger control account."),
    q(CAP + "Find the opening capital.",
      ["₦5,700", "₦7,700", "₦9,800", "₦14,900"], B,
      "At 1/1/2010 assets = rates prepaid ₦2,000 + motor van ₦8,000 + premises ₦10,500 = ₦20,500; liabilities = creditors ₦9,000 + rent owing ₦3,800 = ₦12,800; capital = ₦7,700."),
    // paper 21–30
    q(CAP + "Calculate the value of closing capital.",
      ["₦8,700", "₦9,500", "₦9,700", "₦10,700"], C,
      "At 31/12/2010 assets = ₦3,500 + ₦8,000 + ₦10,500 = ₦22,000; liabilities = ₦9,800 + ₦2,500 = ₦12,300; capital = ₦22,000 − ₦12,300 = ₦9,700."),
    q("Given:\nOpening capital ... ₦50,000\nClosing capital ... ₦64,000\nDrawings ... ₦16,000\n\nDetermine the net profit.",
      ["₦2,000", "₦14,000", "₦20,000", "₦30,000"], D,
      "Net profit = closing capital − opening capital + drawings = ₦64,000 − ₦50,000 + ₦16,000 = ₦30,000."),
    q("The estimated profit or loss for a period is calculated by",
      ["closing capital less opening capital add drawings", "opening capital less closing capital add drawings", "opening capital less drawings add closing capital", "opening capital add closing add drawings"], A,
      "Under incomplete records, profit = closing capital − opening capital + drawings (less any new capital introduced)."),
    q("Given:\nDrawings ... ₦3,500\nNet loss ... ₦2,500\nCapital 1/1/2007 ... ₦35,000\nAdditional capital ... ₦10,000\n\nThe adjusted capital as at 31/12/2007 is",
      ["₦35,000", "₦39,000", "₦45,000", "₦46,000"], B,
      "Adjusted capital = ₦35,000 + additional capital ₦10,000 − net loss ₦2,500 − drawings ₦3,500 = ₦39,000.",
      { bookletKey: 'C', bookletNote: "The booklet answer C (₦45,000) only adds the additional capital to the opening capital (₦35,000 + ₦10,000) and forgets that a net loss and drawings both reduce capital. Correct working: ₦45,000 − ₦2,500 − ₦3,500 = ₦39,000, which is B." }),
    q("When goods produced are transferred at cost plus mark-up, the difference between the cost and the transferred price is a",
      ["discount", "sales commission", "manufacturing profit", "factory reserves"], C,
      "When finished goods are transferred to the trading account at cost plus a mark-up, the mark-up is the manufacturing (factory) profit."),
    q("The addition of prime cost, indirect cost and opening work-in-progress less the closing work-in-progress will result in cost of",
      ["goods available for sale", "goods sold", "goods manufactured", "materials put into production"], C,
      "Prime cost + factory overheads (indirect costs) + opening work-in-progress − closing work-in-progress = cost of goods manufactured (production cost)."),
    q(RAW + "Calculate the cost of raw materials used.",
      ["₦495,000", "₦415,000", "₦335,000", "₦305,000"], C,
      "Raw materials used = opening stock ₦75,000 + purchases ₦330,000 + carriage ₦10,000 − closing stock ₦80,000 = ₦335,000."),
    q(RAW + "Determine the prime cost.",
      ["₦525,000", "₦515,000", "₦465,000", "₦365,000"], D,
      "Prime cost = raw materials used ₦335,000 + direct wages ₦30,000 = ₦365,000."),
    q("In manufacturing account, the work-in-progress at the end of the year is",
      ["deducted from the cost of goods completed during this year", "added to the cost of goods completed", "stated in the profit and loss account", "stated in the prime cost section"], A,
      "Closing work-in-progress is not yet finished, so it is deducted in the manufacturing account in arriving at the cost of goods completed in the year."),
    q("Which of the following is accounted for in receipts and payment account?",
      ["Subscriptions received in advance", "Subscriptions due not yet received", "Accrued expenses on annual dances", "Depreciation of the club house"], A,
      "A receipts and payments account records only actual cash received and paid; subscriptions received in advance have been received in cash, while the others involve no cash movement."),
    // paper 31–40
    q("Which of the following expenses relates to the profit and loss account of a manufacturing firm?",
      ["Direct materials", "Direct labour", "Administrative overhead", "Work-in-progress"], C,
      "Administrative overheads are charged in the profit and loss account; direct materials, direct labour and work-in-progress belong to the manufacturing account."),
    q("I. Direct materials; II. Direct labour; III. Direct expenses; IV. Factory expenses.\n\nPrime cost consists of",
      ["I, II and III", "I, II and IV", "I, III and IV", "II, III and IV"], A,
      "Prime cost is the total of direct costs: direct materials, direct labour and direct expenses; factory (indirect) expenses are overheads added after prime cost."),
    q("The amount paid by a new partner on admission as a compensation for the reputation built up by old partners is a",
      ["bonus", "commission", "premium", "goodwill"], D,
      "Goodwill is the value of a firm's reputation and customer connection; a new partner pays for a share of the goodwill built up by the old partners."),
    q("A partnership's internal regulations are set out by",
      ["a deed", "a law", "a constitution", "an article"], A,
      "The partnership deed (agreement) sets out the internal rules: capital, profit-sharing ratio, interest, salaries, drawings and so on."),
    q("In a partnership account, interest on drawings is",
      ["debited to appropriation account", "credited to appropriation account", "treated as an expense in profit and loss account", "recorded in the balance sheet as current assets"], B,
      "Interest on drawings is charged to the partners, so it is credited to the appropriation account (adding to profit to be shared) and debited to their current accounts."),
    q("When a share valued at 50k is issued at ₦1.59, it is said to be issued at",
      ["par", "premium", "discount", "interest"], B,
      "A share issued above its nominal (par) value is issued at a premium; here the premium is ₦1.59 − 50k = ₦1.09 per share."),
    q("The purchase consideration that is lower than the net asset implies that, the buyer has gained the advantage of",
      ["net income", "revenue reserve", "capital reserve", "net loss"], C,
      "When the price paid for a business is less than the value of its net assets, the gain (negative goodwill) is treated as a capital reserve."),
    q("When shares are issued at a discount, entries are to debit",
      ["application allotment account and credit discount account", "discount account and credit application and allotment account", "cash account and credit discount account", "discount account and credit bank account"], B,
      "The discount is a loss to the company: debit discount on shares account and credit application and allotment account, so the shares are still credited to share capital at full nominal value."),
    q("When there is no basis of apportionment in an organization, the expenses should be apportioned based on",
      ["sales", "purchases", "equality", "floor space"], C,
      "Where no fair basis such as floor space, sales or staff numbers applies, a joint expense is shared equally between the departments."),
    q(DEPT + "The gross profit for K is",
      ["₦23,500", "₦60,500", "₦60,700", "₦82,500"], B,
      "Cost of sales for K = ₦2,500 + ₦120,000 − ₦3,000 = ₦119,500; gross profit = ₦180,000 − ₦119,500 = ₦60,500."),
    // paper 41–50
    q(DEPT + "What is the net profit of Y?",
      ["₦52,000", "₦68,300", "₦68,800", "₦69,700"], D,
      "Y's gross profit = ₦200,000 − (₦800 + ₦100,000 − ₦1,500) = ₦100,700; less salaries ₦30,000 and rates ₦1,000 (2/3 of ₦1,500) = ₦69,700."),
    q("The objective of departmental account is to",
      ["ascertain the cost of running the organization", "ascertain the amount of profit or loss for each department", "ascertain the amount of profits or losses for the enterprises", "offset the loss of each treatment"], B,
      "Departmental accounts show the trading results of each department separately, so management can see which department makes a profit or a loss."),
    q("Which of the following is the capital reserve of a company?",
      ["Share premium", "Retained profit", "Accumulated depreciation", "Loss on forfeited shares"], A,
      "Share premium is a capital reserve: it arises from the issue of shares, not from trading, and cannot be paid out as cash dividend."),
    q("Given:\nApplications were invited by the directors of Abiodun PLC for 500,000 ordinary shares of ₦1.00 each at ₦1.10 per share payable as follows:\nOn application ... 46k\nOn allotment ... 20k\n1st Call ... 15k\n2nd Call ... 19k\n\nHow much is to be paid for application?",
      ["₦230,000", "₦280,000", "₦500,000", "₦550,000"], A,
      "Application money = 500,000 shares × 46k = ₦230,000."),
    q("The issued share capital is the number of shares that are",
      ["authorized by share holders", "shared among the directors", "fully subscribed", "in the share certificate"], D,
      "Issued share capital is the part of the authorised capital actually allotted to shareholders, each holding being evidenced by a share certificate."),
    q("The distributable profit available to shareholders at the end of each year is the",
      ["total profit and debtors balance", "general reserve and retained profit", "retained profit and fictitious assets", "total profit less creditors balance"], B,
      "Revenue reserves, that is the general reserve and retained profit (profit and loss account balance), can be distributed as dividends."),
    q("A debenture issued above the nominal value is said to be issued at a",
      ["cost price", "mark-up", "premium", "margin"], C,
      "Any security issued for more than its nominal value is issued at a premium."),
    q("Accountant-General of the federation is responsible for",
      ["the general supervision of all auditing personnel in all the ministries", "the compilation of annual financial statement", "the interpretation of rules and regulations affecting the private sectors", "ensuring the efficient operation of the ministries"], B,
      "The Accountant-General of the Federation keeps the government's accounts and compiles the annual financial statements, which the Auditor-General then audits."),
    q("Given: Assets and Liabilities of a Local Government\nBank balance ... ₦6,484,000\nCash ... ₦900,000\nGeneral revenue balances ... ₦9,774,500\nAccrued salaries ... ₦1,220,000\nInvestment in shares ... ₦1,480,000\nVehicles ... ₦7,620,000\n\nCalculate the liabilities of the local government.",
      ["₦10,994,500", "₦17,394,500", "₦18,774,500", "₦18,874,500"], A,
      "In a government statement of assets and liabilities the general revenue balance sits on the liabilities side with accrued salaries: ₦9,774,500 + ₦1,220,000 = ₦10,994,500."),
    q("An instrument which allows public officers to increase expenditure within a year is",
      ["statutory allocation", "supplementary budget", "virement", "warrant"], B,
      "A supplementary budget (supplementary appropriation) is passed during the year to authorise spending above the amount in the original budget."),
  ]);
})();
