/**
 * JAMB/UTME 2016 — PRINCIPLES OF ACCOUNTS
 * From the 2016 question paper (questions 1–50; there is no question-paper-type item);
 * answers from the JAMB/UTME Accounts answer key 2001–2020, each checked independently.
 * Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2016;
  const SRC = 'JAMB UTME 2016';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  QUESTION_BANK.accounting = QUESTION_BANK.accounting.concat([
    // paper 1–10
    q("Use the following information: \nBalance as per cash book ... ₦2,970\nBank charges ... ₦220\nUnpresented cheques ... ₦3,950\nUncredited cheques ... ₦4,178\nDirect debit by bank ... ₦1,000\n\nDetermine the balance as per bank statement.",
      ["₦1,978", "₦1,962", "₦1,522", "₦2,522"], C,
      "Adjusted cash book = ₦2,970 − ₦220 − ₦1,000 = ₦1,750; bank statement = ₦1,750 + ₦3,950 unpresented − ₦4,178 uncredited = ₦1,522."),
    q("The records of Superstores shows a loan of ₦14,000 from Bala, creditor ₦8,000 and assets ₦190,500. What is the firm's capital?",
      ["₦184,000", "₦196,500", "₦212,000", "₦168,500"], D,
      "Capital = assets − liabilities = ₦190,500 − (₦14,000 + ₦8,000) = ₦168,500."),
    q("The major advantage of the journal proper is that it",
      ["helps in the preparation of the balance sheet", "prevents fraud and theft of item of the business", "serves as a book of instruction to the bookkeeper", "help the banking industry to be efficient"], B,
      "Because every unusual entry must first be written in the journal with a narration and authorised, the journal reduces the chance of fraud and unauthorised entries in the ledger."),
    q("One of the objectives of accounting is that it can be used for",
      ["business decision making", "due process in business", "motivating employees", "determining the work force"], A,
      "Accounting provides financial information that owners, managers and other users rely on to make business decisions."),
    q("The ratio that gives the indication of the efficiency of a firm's sales with respect to cost of goods sold is a",
      ["return on capital employed", "gross profit margin", "net profit margin", "return on equity"], B,
      "Gross profit margin = (sales − cost of goods sold) ÷ sales × 100, so it measures how well sales cover the cost of the goods sold."),
    q("The instrument used in analysis and interpretation of financial statement is the",
      ["accounting ratios", "income and expenditure extract", "balance sheet extract", "fund accounting"], A,
      "Accounting ratios (profitability, liquidity, efficiency and gearing ratios) are the main tools for analysing and interpreting financial statements."),
    q("An item in the balance sheet of a limited liability company is",
      ["accrued expenses", "lighting and heating", "salaries and wages", "general expenses"], A,
      "Accrued expenses are amounts owing at the year end, so they appear in the balance sheet (statement of financial position) as a current liability; the other items are expenses in the profit and loss account."),
    q("The documents that provide instant information to firms on their transactions with banks are",
      ["bank statement and debit note", "cheque book and cashbook", "cheque stub and deposit slip", "payslip and credit invoice"], C,
      "The cheque stub (counterfoil) and the deposit (paying-in) slip are kept by the firm at the moment it pays out or pays in, so they give immediate evidence of its bank transactions.",
      { keyVerdict: 'corrected', keyAnswer: 'A', answerNote: "JAMB's key gives A. A bank statement only reaches the firm periodically (usually monthly), and a debit note is a trading document sent between buyer and seller, not a bank record. The cheque stub and the deposit slip are completed at the time of each payment or lodgement, so they are the documents that give the firm instant information: C." }),
    q("Which of the following is the capital reserve of a company?",
      ["Accumulated depreciation", "Retained profit", "Share premium", "Loss on forfeited shares"], C,
      "Share premium comes from issuing shares above their nominal value; it is a capital reserve that cannot be paid out as dividend.",
      { bookletKey: 'B', bookletNote: "The booklet answer B, retained profit, is a revenue reserve: it comes from trading profits and can be paid out as dividends. Share premium arises from issuing shares above nominal value and is a capital reserve, so the answer is C." }),
    q("The effect of overstating revenue expenditure in the profit and loss account is that the",
      ["opening stock will be increased", "net profit will be understated", "net profit will be overstated", "opening stock will be decreased"], B,
      "Revenue expenditure is charged against profit, so charging too much expense reduces (understates) the net profit."),

    // paper 11–20
    q("Which of the following condition would attract credit and debit notes to be used?",
      ["When goods are received from supplier", "When a trial balance is extracted", "When a buyer is under or over charged", "When goods are sold to a buyer"], C,
      "A credit note corrects an overcharge (or goods returned) and a debit note corrects an undercharge, so they are used when a buyer has been over- or undercharged."),
    q("A receipt is an evidence of",
      ["payments", "stocking", "delivery", "discounts"], A,
      "A receipt is issued by the person who receives money, as proof that payment has been made."),
    q("Use the following information: \nTuraki Youth Club, Income and Expenditure for the year ended 31/12/04\nBal. b/d ... ₦390\nExpenses on cleaning ... ₦300\nSales of new tool ... ₦510\nTickets ... ₦4,000\nRepairs ... ₦400\nDonations ... ₦3,000\nElectricity ... ₦350\nSubscription ... ₦6,500\n\nWhat is the total income for the period?",
      ["₦10,500", "₦13,500", "₦13,890", "₦9,500"], B,
      "Income = tickets ₦4,000 + donations ₦3,000 + subscription ₦6,500 = ₦13,500; the cash balance b/d and the proceeds from the tool are not income, and cleaning, repairs and electricity are expenses.",
      { bookletKey: 'C', bookletNote: "The booklet answer C (₦13,890) adds the balance b/d of ₦390 to the income, but an opening cash balance is money the club already had, not income earned this year. Income is ₦4,000 + ₦3,000 + ₦6,500 = ₦13,500, which is B." }),
    q("An organization which has records of only personal accounts is said to be operating on the basis of",
      ["single entry", "real accounts", "nominal accounts", "double entry"], A,
      "Under single entry (incomplete records) usually only the cash book and personal accounts of debtors and creditors are kept, with no real or nominal accounts."),
    q("A proprietor started business with ₦13,000. Assets and liabilities at the end of the year: fixed assets ₦8,800, stock ₦2,600, debtors ₦1,000, cash ₦3,000 and creditors ₦1,000. Determine the profit for the year.",
      ["₦2,400", "₦3,000", "₦9,800", "₦1,400"], D,
      "Closing capital = ₦8,800 + ₦2,600 + ₦1,000 + ₦3,000 − ₦1,000 = ₦14,400; profit = ₦14,400 − ₦13,000 = ₦1,400."),
    q("Badge Plc issued 450,000 ordinary shares of 50k each at ₦1.50 per share: \nApplication and allotment ... 45k\n1st call ... 50k\n2nd call ... 55k\n\nDetermine the amount received on final call.",
      ["₦225,000", "₦236,250", "₦247,500", "₦202,500"], C,
      "The final (2nd) call is 55k per share: 450,000 × ₦0.55 = ₦247,500."),
    q("When goods are sent to the branch at cost plus mark-up, it means that the branch should sell at",
      ["a price above or below the stipulated price", "any price but not below the transfer price", "cost price", "a price that is equal to the mark-up"], B,
      "The transfer (invoice) price already includes head office's mark-up, so the branch must not sell below it; selling below the transfer price would wipe out the profit the mark-up is meant to secure.",
      { keyVerdict: 'corrected', keyAnswer: 'A', answerNote: "JAMB's key gives A. Goods are charged to a branch at cost plus mark-up so that head office controls the branch's selling price and profit; a branch free to sell above or below that price would defeat the purpose. The branch must sell at least at the transfer price, which is B." }),
    q("The income and expenditure account differ from receipts and payments account because it",
      ["accounts for notional charges", "records transactions that relate to the period on cash basis", "records transactions that relate to the period on accrual basis", "accounts for balance of cash at bank"], C,
      "The income and expenditure account follows the accruals concept (like a profit and loss account), while the receipts and payments account is a summary of cash and bank movements.",
      { bookletKey: 'B', bookletNote: "The booklet answer B says the income and expenditure account is on a cash basis, but that describes the receipts and payments account. The income and expenditure account records income and expenses belonging to the period whether paid or not (accrual basis), so the answer is C." }),
    q("The major sources of revenue for the state and local governments is",
      ["value added tax", "statutory allocation", "taxes and levies", "recurrent revenue"], B,
      "Nigerian state and local governments receive most of their revenue as statutory allocations from the Federation Account."),
    q("When the fixed capital method is used, the partners' share of profits and remunerations are credited to the",
      ["current account", "profit and loss account", "profit and loss appropriation account", "capital account"], A,
      "Under fixed capitals the capital accounts stay unchanged; shares of profit, salaries and interest on capital are credited to the partners' current accounts.",
      { bookletKey: 'D', bookletNote: "The booklet answer D (capital account) describes the fluctuating capital method. Under the fixed capital method the capital accounts do not change, so shares of profit and other remunerations go to the partners' current accounts: A." }),

    // paper 21–30
    q("A discount that is allowed to encourage a debtor to pay off his debt within a period is the",
      ["annual discount", "trade discount", "periodic discount", "cash discount"], D,
      "A cash discount is given for paying within a stated period; trade discount is a reduction from list price given to traders."),
    q("The costs of acquiring fixed assets and bringing them into the firm is a",
      ["general expenses", "recurrent expenditure", "revenue expenditure", "capital expenditure"], D,
      "The cost of buying a fixed asset, plus costs of bringing it into use such as carriage and installation, is capital expenditure."),
    q("Impersonal account is subdivided into",
      ["real and nominal accounts", "nominal and personal accounts", "real and current accounts", "personal and real accounts"], A,
      "Ledger accounts are personal or impersonal; impersonal accounts are real accounts (assets) and nominal accounts (income and expenses)."),
    q("Opening balance of Diks company was ₦12,202, closing balance ₦15,300, total cash received during the period ₦40,000. What was the amount of cash paid during the same period?",
      ["₦36,902", "₦27,502", "₦12,498", "₦43,098"], A,
      "Payments = opening balance + receipts − closing balance = ₦12,202 + ₦40,000 − ₦15,300 = ₦36,902.",
      { bookletKey: 'C', bookletNote: "The booklet answer C (₦12,498) subtracts both balances from the receipts (₦40,000 − ₦12,202 − ₦15,300), but the opening balance is cash available to spend and must be added. Payments = ₦12,202 + ₦40,000 − ₦15,300 = ₦36,902, which is A." }),
    q("The total cash and cheques received from customers in a control account is derived from the",
      ["income and expenditure account", "cashbook", "purchases day book", "sales journal"], B,
      "Cash and cheques received from debtors are recorded in the cash book, which is the source of that figure in the sales ledger control account.",
      { bookletKey: 'D', bookletNote: "The booklet answer D, the sales journal, gives the total credit sales, not the money received. Cash and cheques received from customers are recorded in the cash book, so the answer is B." }),
    q("Which of the following is a credit item in creditors ledger control account?",
      ["Returns outwards", "Discount received", "Bad debts", "Purchases"], D,
      "Credit purchases increase what is owed to suppliers, so they are credited in the creditors (purchases ledger) control account; returns outwards and discount received are debits."),
    q("The trader's capital in a single-entry system is ascertained by preparing",
      ["gross profit", "statement of affairs", "suspense account", "appropriation account"], B,
      "A statement of affairs lists the assets and liabilities at a date; capital = assets − liabilities."),
    q("I. Members subscription\nII. Fines from members\nIII. Donation\nIV. Loan from bank\n\nFrom the information above, sources of income for a not-for-profit-making organization include",
      ["I, III, IV", "I, II, III", "I, II, IV", "I and IV"], B,
      "Subscriptions, fines and donations are income of a club; a bank loan is a liability that must be repaid, not income."),
    q("Clifford pays rent of ₦200 per month for premises. He paid ₦2,800 within the year. Compute the prepayment.",
      ["₦300", "₦400", "₦600", "₦200"], B,
      "Rent due for the year = ₦200 × 12 = ₦2,400; prepayment = ₦2,800 − ₦2,400 = ₦400."),
    q("Purchases can be ascertained through the preparation of a",
      ["stock account", "sales account", "total debtors control account", "total creditors control account"], D,
      "In incomplete records, credit purchases are the balancing figure in the total creditors control account."),

    // paper 31–40
    q("When stock is withdrawn for personal use, the accounting entries is to debit",
      ["stock account credit drawings", "drawing account, credit stock account", "personal account credit cash account", "cash account, credit personal account"], B,
      "Goods taken by the owner are drawings: debit drawings and credit stock (in practice the purchases account)."),
    q("Sundry debtors in the balance sheet of Onoja Bakery and Sons totaled ₦800,000. A provision of ₦100,000 was made for bad and doubtful debts. Find the amount for sundry debtors after provision.",
      ["₦600,000", "₦800,000", "₦41,000", "₦700,000"], D,
      "Net debtors = ₦800,000 − ₦100,000 = ₦700,000."),
    q("Which of the following is accounted for in receipts and payments account?",
      ["Accrued expenses on annual dances", "Subscriptions due but not yet received", "Interest on bank deposit", "Depreciation of the club house"], C,
      "The receipts and payments account records only actual cash and bank movements; interest received on a bank deposit is a cash receipt, while accruals, amounts due and depreciation are not."),
    q("When the purchase consideration is lower than the net asset, the buyer has gained the advantage of",
      ["capital reserve", "revenue reserve", "net income", "net loss"], A,
      "Paying less than the value of the net assets taken over gives a gain (negative goodwill) which is treated as a capital reserve."),
    q("A business organization prepares departmental account in order to",
      ["ascertain the contribution of each department to the organization", "ascertain interdepartmental transfer", "build other branches", "know the number of departments in the organization"], A,
      "Departmental accounts show the result of each department, so management can see how much each contributes to the whole business."),
    q("The objective of departmental account is to",
      ["ascertain the amount of profits or losses for the enterprise", "ascertain the amount of profits or losses for each department", "ascertain the cost of running the organization", "offset the loss of each department"], B,
      "Departmental accounts find the gross and net profit or loss of each department separately."),
    q("The difference between book keeping and accounting is that while",
      ["book keeping interprets data, accounting records it", "book keeping is regarded as the language of the business accounting ascertains its strength and weakness", "book keeping records data accounting interprets it", "book keeping summaries information accounting communicates it"], C,
      "Book keeping is the recording stage; accounting goes on to summarise, analyse and interpret the recorded data."),
    q("Use the following information: \nA machine bought for ₦35,000 was estimated to have a life span of 5 years with a scrap value of ₦9,000.\n\nIf the scrap value is now ₦15,000, what will be the yearly depreciation using the straight-line method?",
      ["₦11,000", "₦7,000", "₦4,000", "₦24,000"], C,
      "Straight-line depreciation = (₦35,000 − ₦15,000) ÷ 5 = ₦4,000 a year."),
    q("Use the following information: \nA machine bought for ₦35,000 was estimated to have a life span of 5 years with a scrap value of ₦9,000.\n\nThe yearly depreciation using the straight-line method would be",
      ["₦5,200", "₦6,500", "₦8,800", "₦4,400"], A,
      "Straight-line depreciation = (₦35,000 − ₦9,000) ÷ 5 = ₦5,200 a year."),
    q("An increase in government expenditure within a year is taken care of by means of",
      ["financial regulations", "virement", "warrant", "supplementary estimate"], D,
      "Extra spending beyond the approved budget during the year is authorised by a supplementary estimate (supplementary appropriation)."),

    // paper 41–50
    q("Alaka who owed Saka ₦15,000, settled his debt after deducting cash discount of 10 percent. To record the discount in the book of Saka, debit",
      ["discount received account and credit Alaka's account", "Alaka's account and credit discount received account", "Saka's account and credit discount received account", "discount allowed account and credit Alaka's account"], D,
      "Saka is the creditor giving the discount (₦1,500), so in his books he debits discount allowed and credits Alaka's account."),
    q("I. The amount of the imprest is the same from one organization to another.\nII. At the end of a fixed period, the petty cashier received a fixed sum of money.\nIII. At the end of a period, the petty cashier is reimbursed with the amount spent in that period.\nIV. The system is a method by which a measure of control is kept on petty cash expenses.\n\nWhich of the above is correct about the imprest system?",
      ["I, II and III", "I, III and IV", "II and IV", "III and IV"], D,
      "Under the imprest system the petty cashier starts with a fixed float and at the end of each period is reimbursed exactly what was spent (III), which keeps control over petty cash (IV).",
      { keyVerdict: 'corrected', keyAnswer: 'C', answerNote: "JAMB's key gives C (II and IV). Statement III, reimbursing the petty cashier with the amount spent, is the heart of the imprest system and must be included. Statement II is wrongly worded: the fixed sum (the float) is given at the start; what is received at the end of the period is the amount spent, which varies. So III and IV, D, is the correct pair." }),
    q("Given: Drawings - ₦3,500; Net loss - ₦2,500; Capital 1/1/2007 - ₦35,000; Additional capital - ₦10,000. The adjusted capital as at 31/12/2007 is",
      ["₦35,000", "₦39,000", "₦45,000", "₦46,000"], B,
      "Closing capital = ₦35,000 + ₦10,000 − ₦2,500 − ₦3,500 = ₦39,000."),
    q("Which of the following expenses relates to the profit and loss account of a manufacturing firm?",
      ["Direct materials", "Direct labour", "Administrative overhead", "Work-in-progress"], C,
      "Administrative overheads are charged in the profit and loss account; direct materials, direct labour and work-in-progress belong in the manufacturing account."),
    q("The main difference between the ordinary and preference shareholders is that",
      ["the former have voting rights while the latter do not", "in the case of winding up, the former are paid first before the latter", "the latter are not members of the company while the former are", "the former receives dividends while the latter do not"], A,
      "Ordinary shareholders normally vote at general meetings; preference shareholders usually have no vote but get a fixed dividend and are repaid before ordinary shareholders on winding up."),
    q("A club received rent ₦10,000 and donation of ₦30,000. It paid ₦6,000 for entertainment and is still owing ₦16,000. The balance of the receipts and payments account is?",
      ["₦14,000", "₦24,000", "₦18,000", "₦42,000"], C,
      "The receipts and payments account shows only cash actually received and paid: ₦10,000 + ₦30,000 − ₦6,000.",
      { keyVerdict: 'none', keyAnswer: 'C', answerNote: "JAMB's answer is C, but it is not fully correct. The receipts and payments account records only cash that has moved, so the ₦16,000 still owing does not go in it: the balance is ₦10,000 + ₦30,000 − ₦6,000 = ₦34,000, which is not an option. ₦18,000 is what you get only if the ₦16,000 is treated as paid." }),
    q("Ledger account is mainly classified into",
      ["nominal, real and personal accounts", "fixed and current accounts", "management, financial and public sector accounting", "bank and cash accounts"], A,
      "Ledger accounts are classified as personal (people and firms), real (assets) and nominal (income and expenses)."),
    q("The prime cost is the total of the",
      ["production cost + selling expenses", "direct material + direct labour + direct expenses", "direct materials + work overhead expenses", "administrative expenses + selling + distribution expenses"], B,
      "Prime cost is the total of all direct costs: direct materials, direct labour and direct expenses."),
    q("The correct posting in the double entry system of account when there is an increase in assets, expenses, capital or liabilities is to debit",
      ["capital and credit liabilities", "liabilities and credit assets", "assets and credit capital", "capital and credit assets"], C,
      "Increases in assets and expenses are debited; increases in capital and liabilities are credited."),
    q("The excess revenue over expenditure is charged to",
      ["profit and loss", "revenue account", "accumulated fund", "income and expenditure account"], C,
      "A surplus of income over expenditure (found in the income and expenditure account) is added to the accumulated fund."),
  ]);
})();
