/**
 * JAMB/UTME 2016 — USE OF ENGLISH
 * From the 2016 question paper; answers from the JAMB/UTME English Language
 * answer key 2001–2020, each checked against the paper. Where the key in
 * circulation is wrong (often a printing error) the question carries
 * keyVerdict + keyAnswer + answerNote (see english-2007.js for the scheme).
 * Q21-35 (set novel, The Last Days at Forcados High School) are left out: no passage in the paper.
 * Loaded after questions.js and before app.js.
 */
(function () {
  const Y = 2016;
  const SRC = 'JAMB UTME 2016';
  const READ = 'Read the passage carefully and answer the questions that follow.';

  const PT0 = "There are many different approaches to conflict management, each of which may have utility in particular circumstances. A great deal of scholarship has been devoted to analysing how and in what situation different approaches can be applied most effectively.\n\nConflict management approaches can be classified into two broad categories: firstly on the basis of the level of escalation which the particular conflict is being managed. In this sense one can distinguish between the peaceful and the 'military' approaches. The trademarks of the peaceful approach are negotiation, verbal persuasion, use of inducements, denial of privileges, and subtle manipulations short of the use of physical forces, while those of the military approach relate to the use of physical coercion. The use of physical force could be by a party to the conflict or a third party to promote one side's interests, impose a settlement or create a situation in which diplomatic negotiations can occur.\n\nSecondly, conflict management approaches can also be classified according to the status of the participants in the bargaining process. For example a conflict could be managed through 'negotiation', that is, direct bargaining by the parties involved in the conflict; or through 'mediation', that is, with the help of a third party.";
  const PT1 = "The logical importance of one's language is evident from the fact that its grammar and vocabulary form the most complete model of logical system that most of us ever learn. It is the very measure of what is intelligible in the world around us. As more developing peoples of the world come to study the modern science and technology, the sharpening of their logical tools becomes a matter of great importance.\n\nFrom one point of view, a culture consists of a vast collection of answers to the typical questions and problems that arise in a society. These answers are couched in the language of that society and gain much of their authority from it. If the young come to despise their father's language the chances are that they will reject their father's wisdom, which is expressed in it. The emotional importance of a language lies in the fact that it contains the voices of all those dear to us. Our deepest emotions and most intimate memories are tightly bound up with our native language.\n\nThe language, native to a society, has likewise a symbolic function in that it stands for the distinctness and individuality of that group as against other groups. The history, traditions and poetry which express the group's self image are expressed in its language. People feel strongly about their language since it embodies and expresses the good, the true and the beautiful.";
  const PT2 = "Before now, students bumped onto career by chance or through the advice and insistence of parents. These parents had pre-conceived notions of ___(11)___ professions and gave little consideration to their children's interest, aptitude, knowledge and skills. Students' career decisions were also ___(12)___ by the type of secondary schools they attended. Before government take-over of schools in 1971, over 80% of elementary and secondary schools were privately owned and competition was ___(13)___ among these schools. Each strived to carve an ___(14)___ for herself by excelling in sports or academics and students often ended up in engineering, medicine, the sciences and law. Junior students tried to ___(15)___ the career choices of their seniors. This spirit of rivalry among mission and private schools ___(16)___ with government take-over of schools.\n\nGovernment involvement in career development is beset with many problems. One such problem is the ___(17)___ shortage of professional career development officers. These few officers are ___(18)___ given the opportunity to practice. If the government of Nigeria has ___(19)___ a guidance and counselling policy, it must be pointed out that emphasis is still at the secondary level of education. This situation ___(20)___ the current view that career development should start at the pre-primary level and continue till adulthood.";

  const P1Q = [
      { question: "From the passage, it can be deduced that", options: ["prevailing circumstances push a warring nation to sue for peace", "all nations prefer the military option", "all nations adopt the peaceful approach", "conflicts are noted for facilitating opportunities"], answer: 3, explanation: "The passage says force can be used to 'create a situation in which diplomatic negotiations can occur', so a conflict can open up an opportunity for a settlement. B and C contradict the passage's 'many different approaches'.", alsoAccept: [0], keyVerdict: 'multiple', keyAnswer: 'D', answerNote: "The key gives D: the use of force can 'create a situation in which diplomatic negotiations can occur', i.e. conflict can facilitate an opportunity for peace talks. A rests on the same sentence (and on approaches having 'utility in particular circumstances'): circumstances such as the use of force can push a warring side to negotiate, i.e. to sue for peace. Both are fair deductions, so both are marked right." },
      { question: "Which of the following statements can be inferred from the passage?", options: ["The approach to employ in conflict management depends on the state of affairs", "There is a general disagreement among scholars on conflict management", "Only one conflict management approach can be applied in all situations", "All conflict management approaches can be applied in all situations"], answer: 0, explanation: "Each approach 'may have utility in particular circumstances', and scholars study 'in what situation different approaches can be applied', so the choice depends on the situation." },
      { question: "The expression 'third party' as used in the passage means", options: ["conformist", "intruder", "politician", "mediator"], answer: 3, explanation: "The passage links the third party with 'mediation', so a third party here is a mediator who helps the two sides." },
      { question: "According to the passage, the different approaches to conflict management are", options: ["misleading", "uniform", "pernicious", "fundamental"], answer: 3, explanation: "The passage presents the approaches as the basic, essential ways of managing conflict, each useful in its own circumstances; they are neither uniform nor harmful." },
      { question: "The word 'utility', as used in the passage, means", options: ["usefulness", "attitude", "difficulty", "management"], answer: 0, explanation: "Each approach 'may have utility in particular circumstances', i.e. may be useful." },
  ];
  const P2Q = [
      { question: "From the passage, one can imply that", options: ["native languages are difficult to use as languages of instruction", "the language of instruction is ideally one's own language", "no society conducts its education in a foreign language", "no foreign language should be taught in any society"], answer: 1, explanation: "One's language is 'the most complete model of logical system' we learn and 'the very measure of what is intelligible', so learning is best done in it." },
      { question: "From the writer's point of view, one can conclude that", options: ["developing people of the world have not developed their languages", "people of the same culture live in the same society", "the only authority a society has is its language", "language and culture are interwoven"], answer: 3, explanation: "A culture's answers to life's questions 'are couched in the language of that society and gain much of their authority from it': language and culture are bound together." },
      { question: "What is the symbolic function of a native language according to the passage?", options: ["It promotes understanding within the group", "It enables the society to understand itself the more", "It alienates progress within the society and beyond", "It distinguishes that society from others"], answer: 3, explanation: "Its symbolic function is that 'it stands for the distinctness and individuality of that group as against other groups'." },
      { question: "The word 'couched' as used in the passage means", options: ["expressed", "arranged", "itemized", "modified"], answer: 0, explanation: "The answers are 'couched in the language of that society', i.e. expressed in it." },
      { question: "Which of the following can be inferred from the passage?", options: ["The world around us is the world of people who speak the same language", "We know more about the world around us if our language is not written", "Our native language is as important as the world around us", "The world is interpreted to us only in our native language"], answer: 3, explanation: "Our language is 'the very measure of what is intelligible in the world around us': we make sense of the world through our native language." },
  ];
  const CLOZE = [
      { question: "Gap 11: These parents had pre-conceived notions of _____ professions.", options: ["prestigious", "insignificant", "inferior", "debased"], answer: 0, explanation: "Parents pushed children towards professions they held in high esteem, i.e. prestigious ones." },
      { question: "Gap 12: Students' career decisions were also _____ by the type of secondary schools they attended.", options: ["hampered", "influenced", "subdue", "rejected"], answer: 1, explanation: "Career decisions were also influenced (shaped) by the type of school attended; 'subdue' is also the wrong form after 'were'." },
      { question: "Gap 13: Competition was _____ among these schools.", options: ["minimal", "high", "low", "carve an"], answer: 1, explanation: "Each school strove to carve an image for itself, which shows that competition was high. (Option D, 'carve an', is a printing slip in the paper.)" },
      { question: "Gap 14: Each strived to carve an _____ for herself by excelling in sports or academics.", options: ["image", "attitude", "effort", "avenue"], answer: 0, explanation: "Schools excelled in sports or academics to carve an image (a reputation) for themselves." },
      { question: "Gap 15: Junior students tried to _____ the career choices of their seniors.", options: ["emulate", "appreciate", "reject", "denounce"], answer: 0, explanation: "Junior students tried to emulate (copy) the career choices of their seniors." },
      { question: "Gap 16: This spirit of rivalry among mission and private schools _____ with government take-over of schools.", options: ["waned", "heightened", "intensified", "increased"], answer: 0, explanation: "Once government took over the schools, the rivalry between mission and private schools waned (died down)." },
      { question: "Gap 17: One such problem is the _____ shortage of professional career development officers.", options: ["acute", "mild", "slow", "average"], answer: 0, explanation: "'These few officers' shows the shortage is acute (severe)." },
      { question: "Gap 18: These few officers are _____ given the opportunity to practice.", options: ["usually", "seldom", "often", "frequently"], answer: 1, explanation: "The sentence lists a problem, so the few officers are seldom (rarely) given the opportunity to practise." },
      { question: "Gap 19: If the government of Nigeria has _____ a guidance and counselling policy, it must be pointed out that emphasis is still at the secondary level of education.", options: ["muffled", "lauded", "mumbled", "enunciated"], answer: 3, explanation: "A government enunciates (states clearly and formally) a policy." },
      { question: "Gap 20: This situation _____ the current view that career development should start at the pre-primary level and continue till adulthood.", options: ["approves", "rejects", "contradicts", "verifies"], answer: 2, explanation: "Emphasis at the secondary level goes against the view that career development should start at pre-primary level: it contradicts it." },
  ];

  const passages = [
    { passageId: 'eng-2016-p1', passageTitle: 'JAMB 2016 — Passage I', year: Y, instruction: READ, passage: PT0, questions: P1Q },
    { passageId: 'eng-2016-p2', passageTitle: 'JAMB 2016 — Passage II', year: Y, instruction: READ, passage: PT1, questions: P2Q },
    { passageId: 'eng-2016-p3', passageTitle: 'JAMB 2016 — Passage III (cloze)', year: Y, instruction: 'The passage has gaps numbered 11 to 20. Choose the most appropriate option for each gap.', passage: PT2, questions: CLOZE },
  ];

  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const GAP = 'Choose the option that best completes the gap(s): ';
  const VOWEL = 'Choose the option that has a DIFFERENT vowel sound from the others.';
  const SAMEV = 'Choose the option that has the same vowel sound as the letter(s) in capitals: ';
  const CONS = 'Choose the option that has the same consonant sound as the letter(s) in capitals: ';
  const DIFFC = 'Choose the option that has a DIFFERENT consonant sound from the others.';
  const DIFF = 'Choose the option that has a DIFFERENT stress pattern from the others.';
  const SAMES = 'Choose the option that has the same stress pattern as the given word (stressed syllable in capitals): ';
  const STRESSOF = 'Choose the appropriate stress pattern for the word (the stressed syllable is in capitals): ';
  const FIRST = 'Choose the option that has the stress on the FIRST syllable.';
  const NEAR = 'Choose the option NEAREST in meaning to the word(s) in capitals: ';
  const MEANS = 'Select the option that best explains the information conveyed in the sentence: ';
  const EMPH = 'The word in capitals has emphatic stress. Choose the option that best fits the expression: ';
  const OPP = 'Choose the option OPPOSITE in meaning to the word(s) in capitals: ';

  const flat = [
    q(MEANS + "Mr. Rufus bore the brunt in the last promotion examination woefully.", ["Mr. Rufus failed the examination woefully", "Mr. Rufus excelled in the examination", "Mr. Rufus was excited about the examination", "Mr. Rufus toyed with the examination"], A, "To bear the brunt of something is to suffer its worst effects; with 'woefully', he did very badly, i.e. failed."),
    q(MEANS + "My friend is well off nowadays.", ["My friend is financially sound", "My friend is well known to people", "My friend is now well", "My friend has lost focus"], A, "To be well off is to be rich or comfortable financially."),
    q(MEANS + "The retired army officer did a yeoman's service to the nation.", ["His activity brought disrepute to the nation", "His service to the nation was not exemplary", "He was showered with the responsibility of the yeoman", "He was very loyal to the nation"], D, "Yeoman's service is excellent, loyal and valuable service."),
    q(MEANS + "He suddenly found himself in the thick of the situation.", ["He did not agree with the situation", "He used his experience to settle the situation", "He saved himself out of the situation", "He found himself deeply involved in the situation"], D, "In the thick of something means in the busiest or most involved part of it."),
    q(MEANS + "Olu and Ado are about to come to blows.", ["They are about to agree with each other", "They are about to accept other people's opinion", "They are about to hit each other", "They are about to disagree with other people's opinion"], C, "To come to blows is to start fighting physically."),
    q(MEANS + "By refusing the offer, he has just cut down his own throat.", ["He had made a big mistake", "He has made the right decision", "He has given up on his idea", "He has used the knife on his throat"], A, "To cut one's own throat is to do something that harms oneself, i.e. to make a big mistake."),
    q(MEANS + "These job cuts are just the thin end of the wedge.", ["Job cuts are very rampant", "Job cuts are inconclusive", "Job cuts are the beginning of unpleasant situations", "Job cuts are the beginning of healthy rivalries"], C, "The thin end of the wedge is a small beginning that will lead to something worse."),
    q(MEANS + "Jumai will do well if she was given a fair crack of the whip.", ["She would do well if she was given a fair whip", "She would excel if she used the whip well", "She would do well if she was given equal opportunity", "She would do well if she was made to cry"], C, "A fair crack of the whip is a fair chance, an equal opportunity."),
    q(MEANS + "Her death was a bolt from the blue to us.", ["Her death bolted us together", "Her death cause confusion", "Her death scaled our hopes", "Her death was unexpected"], D, "A bolt from the blue is a complete surprise."),
    q(MEANS + "The students were nosing around.", ["They were roaming about", "They were searching for information", "They were playing around", "They were disseminating information"], B, "To nose around is to search or pry, looking for information."),
    q(OPP + "It is important not to let mistakes BLIGHT your life.", ["damage", "impart", "improve", "ruin"], C, "To blight is to spoil or damage; the opposite is to improve."),
    q(OPP + "The film was shot in DECREPIT police station.", ["an improved", "a damaged", "an impoverished", "a dilapidated"], A, "Decrepit means old and run-down; the opposite is improved."),
    q(OPP + "Jumoke is fond of CARPING her sister.", ["praising", "joking with", "complaining about", "faulting"], A, "To carp is to find fault or complain constantly; the opposite is to praise."),
    q(OPP + "A cup of coffee INVIGORATED him.", ["destroyed", "energized", "angered", "debilitated"], D, "Invigorated means filled with energy; debilitated means weakened."),
    q(OPP + "It is LUDICROUS to suggest that she was a government agent.", ["odd", "exciting", "farcial", "sensible"], D, "Ludicrous means absurd; the opposite is sensible."),
    q(OPP + "The idea makes me CRINGE.", ["quiver", "tremble", "resolute", "writhe"], C, "To cringe is to shrink back in fear or embarrassment; resolute (firm and fearless) is the opposite attitude."),
    q(OPP + "His book was one of those books that GALVANIZED democracy.", ["stimulated", "encouraged", "dissuaded", "promoted."], C, "To galvanize is to stir into action; to dissuade is to discourage."),
    q(OPP + "He walks in a GAWKY way.", ["suitable", "clumsy", "lumbering", "graceful"], D, "Gawky means awkward and clumsy; the opposite is graceful."),
    q(OPP + "The nation is in a period of economic FLUX.", ["modification", "change", "fluidity", "stability"], D, "Flux is continuous change; the opposite is stability."),
    q(OPP + "Our son was highly active and EXUBERANT.", ["subdued", "fulsome", "lively", "bright"], A, "Exuberant means full of energy and excitement; subdued means quiet and restrained."),
    q(NEAR + "Mr. Ojo has FICKLE character.", ["a genuine", "a stable", "an imperfect", "an unpredictable"], D, "A fickle person changes their mind or loyalty often, i.e. is unpredictable."),
    q(NEAR + "He picked up the phone expecting GRUFF voice.", ["gracious", "musical", "husky", "polite"], C, "A gruff voice is rough and low, i.e. husky."),
    q(NEAR + "It has been a FRAUGHT day.", ["difficult", "pleasant", "wonderful", "solemn"], A, "A fraught day is full of stress and problems, i.e. difficult."),
    q(NEAR + "She SCOWLED furiously at his back as he walked away.", ["whispered", "grimaced", "screeched", "screamed"], B, "To scowl is to frown angrily, a kind of grimace."),
    q(NEAR + "The use of this equipment should OBVIATE the problem.", ["prevent", "improve", "promote", "worsen"], A, "To obviate a problem is to remove or prevent it."),
    q(NEAR + "Olisa HOODWINKED the men into buying and selling.", ["grouped", "lured", "deluded", "drove"], C, "To hoodwink is to deceive, i.e. to delude."),
    q(NEAR + "There was an infectious GAIETY in the children's character.", ["exhilaration", "depression", "moodiness", "desperation"], A, "Gaiety is cheerful liveliness, close to exhilaration."),
    q(NEAR + "The room was filled with the PUNGENT smell of tobacco.", ["placid", "mild", "illegal", "acrid"], D, "A pungent smell is sharp and strong, i.e. acrid."),
    q(NEAR + "He lifted his hand in a LANGUID manner.", ["a sheepish", "a sluggish", "a friendly", "an energetic"], B, "Languid means slow and lacking energy, i.e. sluggish."),
    q(NEAR + "The lawmaker HECKLED the chairman of the panel during their last meeting.", ["cheered up", "applauded", "shouted down", "restrained"], C, "To heckle is to interrupt a speaker with rude shouts, i.e. to shout them down."),
    q(GAP + "The book will sell in _____.", ["hundreds of thousands", "a hundred thousand", "hundreds of thousand", "hundred thousands"], A, "When 'hundreds' and 'thousands' are used as indefinite large numbers, both take -s: hundreds of thousands."),
    q(GAP + "We must be ready to cater for _____.", ["the poors and needy", "poor and needs", "the poor and needy", "poors and needs"], C, "'The poor' and 'the needy' are adjectives used as plural nouns for a group of people; they never take -s."),
    q(GAP + "After a three-day meeting, two presidents issued a _____ calling for peace.", ["bulletin", "memorandum", "communique", "directive"], C, "A communiqué is the official statement issued at the end of a meeting between leaders or governments."),
    q(GAP + "Timi has gone to Lagos and he will be back in _____ time.", ["two's week", "two week's", "two weeks", "two weeks'"], D, "Expressions of time with a plural noun take the apostrophe after the s: two weeks' time."),
    q(GAP + "The students have not come back from the school farm, _____?", ["hadn't they", "have they", "didn't they", "isn't it"], B, "A negative statement takes a positive tag with the same auxiliary: have not ... have they?"),
    q(GAP + "'Do not forget to reply _____' said the teacher.", ["my letter", "for my letter", "of my letter", "to my letter"], D, "We reply to a letter."),
    q(GAP + "You will need _____ to help the investigations.", ["this information", "this informations", "these information", "these informations"], A, "Information is uncountable: no plural -s, and it takes 'this', not 'these'."),
    q(GAP + "Ada did not find _____ in the house.", ["anyone", "some one", "somebody", "someone"], A, "Negative sentences normally take any- words: did not find anyone."),
    q(GAP + "The _____ discouraged me from reading it.", ["story length", "length of the story", "stories length", "story's length"], B, "With things (not people), the 'of' structure is the standard choice: the length of the story."),
    q(GAP + "Ado said that he _____", ["want very much to travel to Lagos", "has been wanting very much to travel to Lagos", "wanted very much to travel to Lagos", "will want very much to travel to Lagos"], C, "In reported speech after a past reporting verb ('said'), the verb moves back to the past: wanted. (The paper labels this option '(d)' by mistake.)"),
    q(GAP + "He take _____ his father both in appearance and his manner.", ["on", "from", "after", "upon"], C, "To take after someone is to resemble a parent or older relative. (The paper prints 'take' for 'takes'.)"),
    q(GAP + "_____ rich has its own problem.", ["Being", "Been", "On being", "On been"], A, "The subject here is a gerund phrase: Being rich has its own problem."),
    q(GAP + "The doctor listened to my heartbeat with a _____.", ["cardiograph", "stethoscope", "chromometer", "microscope"], B, "A stethoscope is the instrument a doctor uses to listen to the heart and chest."),
    q(GAP + "With strong determination, Adamu was able to _____ the problem.", ["surmount", "surpass", "defend", "know"], A, "To surmount a problem is to overcome it."),
    q(GAP + "It is impossible to say whether _____ Ola and her sister will be offered jobs by the firm.", ["both", "either", "each", "neither"], A, "'And' pairs with 'both': both Ola and her sister. Either pairs with or, neither with nor."),
    q(GAP + "He decided to wait for the bus because he had _____.", ["many luggages", "plenty luggages", "a lot of luggage", "too many luggage"], C, "Luggage is uncountable: no -s, and it takes 'a lot of' or 'much', not 'many'."),
    q(GAP + "_____ lawyers enrolled at the Nigerian Bar last year _____ this year.", ["very many/than", "same/as", "more/than", "as/much"], C, "A comparison with 'than' needs a comparative: more ... than."),
    q(GAP + "The officer _____ that he was not supposed to talk to the press on the matter.", ["could have known", "shall know", "should have known", "will know"], C, "'Should have known' criticizes a past failure: he ought to have known."),
    q(GAP + "He said, 'we shouldn't do it _____'.", ["should we", "should be", "didn't we", "said he"], A, "A negative statement with 'shouldn't' takes the positive tag 'should we?'"),
    q(GAP + "After too much exercise, some people suffer from cramp which is caused by the _____ of the muscles.", ["contraction", "restriction", "conscription", "relationship"], A, "A cramp is a sudden, painful contraction (tightening) of a muscle."),
    q(SAMEV + "repriEve", ["rich", "police", "queer", "probity"], B, "The ie (underlined e) in reprieve is the long /iː/, as the i in police."),
    q(SAMEV + "dOOR", ["food", "cough", "sure", "board"], D, "The oor in door is /ɔː/, as the oar in board."),
    q(SAMEV + "famOUS", ["soup", "cook", "pilot", "colonel"], C, "The -ous in famous is the weak vowel /ə/, as the o in pilot."),
    q(CONS + "CHoice", ["schedule", "teach", "leisure", "machine"], B, "The ch in choice is /tʃ/, as in teach."),
    q(CONS + "Yet", ["bury", "way", "vessel", "Europe"], D, "The y in yet is /j/; Europe also begins with /j/ (/ˈjʊərəp/)."),
    q(CONS + "taskED", ["bagged", "floored", "laughed", "shouted"], C, "After the voiceless /k/, -ed is /t/; laughed also ends in /t/ (after /f/)."),
    q("Choose the option that rhymes with the given word: risen", ["prison", "motion", "portion", "rising"], A, "Risen /ˈrɪzn/ rhymes with prison /ˈprɪzn/."),
    q("Choose the option that rhymes with the given word: terror", ["tenor", "warrior", "error", "furrow"], C, "Terror /ˈterə/ rhymes with error /ˈerə/."),
    q("Choose the option that rhymes with the given word: crowd", ["crow", "bard", "aloud", "crawl"], C, "Crowd /kraʊd/ rhymes with aloud /əˈlaʊd/."),
    q(STRESSOF + "inoffensive", ["inOffensive", "inoffenSIVE", "inoFENsive", "INoffensive"], C, "Inoffensive is stressed on the third syllable: in-of-FEN-sive."),
    q(STRESSOF + "obligation", ["obliGAtion", "Obligation", "obligaTION", "obLIgation"], A, "Words ending in -ation are stressed on the syllable before -tion: ob-li-GA-tion."),
    q(STRESSOF + "disagreement", ["disagreement", "disaGREEment", "DISagreement", "disagreeMENT"], B, "Disagreement is stressed on 'gree': dis-a-GREE-ment, like agree."),
    q(EMPH + "The car CRUSHED him.", ["Who did the car crush?", "Did a car crush him?", "What crushed him?", "Did the car injure him?"], D, "Stressing CRUSHED corrects the verb: the car didn't just injure him, it crushed him."),
    q(EMPH + "Lamide is VERY hostile?", ["Is Lamide so hostile?", "Is Lamide friendly", "Was Lamide very hostile?", "Who is hostile?"], A, "Stressing VERY answers a question about degree: is she so (that) hostile?"),
    q(EMPH + "My house is a BUNGALOW.", ["Is my house a terrace?", "Was my house", "Is my house the bungalow", "Is his house a bungalow?"], A, "Stressing BUNGALOW corrects the type of house: not a terrace, a bungalow."),
  ];

  QUESTION_BANK.english = QUESTION_BANK.english.concat(passages, flat);
})();
