/**
 * JAMB/UTME 2002 — USE OF ENGLISH
 * From the 2002 question paper; answers from the JAMB/UTME English Language
 * answer key 2001–2020, each checked against the paper. Where the key in
 * circulation is wrong (often a printing error) the question carries
 * keyVerdict + keyAnswer + answerNote (see english-2007.js for the scheme).
 *
 * Passage III was read by OCR after digitally straightening its curved page.
 *
 * Loaded after questions.js and before app.js.
 */
(function () {
  const Y = 2002;
  const SRC = 'JAMB UTME 2002';
  const READ = 'Read the passage carefully and answer the questions that follow.';

  const P1 = "If our thought is to be clear and we are to succeed in communicating it to other people, we must have some method of fixing the meaning of the words we use. When we use a word whose meaning is not certain, we may well be asked to define it. There is a useful traditional device for doing this by indicating the class to which whatever is indicated by the term belongs, and also the particular property which distinguishes it from all other members of the same class. Thus we may define a whale as a 'marine animal that spouts'. 'Marine animal' in this definition indicates the general class to which the whale belongs, and 'spouts' indicates the particular property that distinguishes whales from other such marine animals as fishes, seals, jellyfish and lobsters. In the same way, we can define an even number as a finite integer divisible by two, or a democracy as a system of government in which the people themselves rule.\n\nThere are other ways, of course, of indicating the meanings of words. We may, for example, find it hard to make a suitable definition of the word 'animal', so we say that an animal is such a thing as a rabbit, dog, fish or goat. Similarly, we may say that religion is such a system as Christianity, Islam, Judaism and Buddhism. This way of indicating the meaning of a term by enumerating examples of what it includes is obviously of limited usefulness. If we indicated our use of the word 'animal' as above, our hearers might, for example, be doubtful whether a sea anemone or a slug was to be included in the class of animals. It is, however, a useful way of supplementing a definition if the definition itself is definite without being easily understandable. Failure of an attempt at definition to serve its purpose may result from giving as distinguishing mark one which either does not belong to all the things the definition is intended to include, or does belong to some members of the same general class which the definition is intended to exclude.";

  const P2 = "Those who have been following the arguments for and against the deregulation of the oil industry in Nigeria may have got the impression that deregulation connotes lack of control or indifference on the part of the Government. But there is nothing so far from official quarters to suggest that deregulation will cause the Government to relinquish its control of the oil industry because the absence of direct control does not mean that it will surrender all its rights to the entrepreneurs who may want to participate in the industry. Yet the opposition expressed so far against deregulation stems from the fear that the Government would leave Nigerians at the mercy of a heartless cartel who would command the heights of the oil industry and cause the pump price of fuel to rise above the means of most Nigerians.\n\nAs a result of such fears, many Nigerians have become resentful of deregulation and, in fact, the Nigeria Labour Congress (NLC) has threatened to 'deregulate' the Government if it should go ahead with the deregulation plan. But Nigerians have not fared any better with the economy totally in Government control. Until recently, the most important sectors of the economy were in the hands of the Government. Today, the deregulation of some of these sectors has broken its monopoly and introduced healthy competition to make things a little easier for Nigerians. A good example is the breaking of the stifling monopoly of Nigeria Airways. Today, the traveler is king at the domestic airports as opposed to the struggle that air travels used to be under Nigeria Airways monopoly. Before, it was almost easier for a camel to pass through the eye of a needle than for travelers to board a plane.\n\nFollowing from this, the apostles of deregulation rightly heap all the blame for the problems associated with petroleum products distribution in this country squarely on the Government, which owns all the refineries and which sells fuel to local consumers through its agency, the Nigerian National Petroleum Corporation (NNPC). In the same way, the Government argues that if the current NNPC monopoly were broken with the introduction of entrepreneurs to the refining and sale of petroleum products in the country, the Nigerian people would be all the better for it. It stands to reason that once the Government continues to fix maximum prices for petroleum products in this country, the deregulation of the oil sector should bring some relief to the people by ensuring that wastage, corruption and inefficiency are reduced to the minimum. Consumers will also have the last laugh because competition will result in the availability of the products at reasonable prices. This appears to be the sense in deregulation.";

  const P4 = "It is the business of the scientist to accumulate knowledge about the universe and all that is in it, and to find, if he is able, the common ___(16)___ which underlie and account for the facts that he knows. He chooses, when he can, the method of the controlled ___(17)___. If he wants to find out the effect of light on growing plants, he takes many plants, as alike as possible. Some he stands in the sun, some in the shade, some in the dark; all the time keeping all other ___(18)___ (temperature, moisture, nourishment) the same. In this way, by keeping other variables ___(19)___ and by varying the light only, the effect of light on plants can be clearly seen. This ___(20)___ of using 'controls' can be applied to a variety of situations, and can be used to find the answers to questions as widely different as 'must moisture be present ___(21)___ is to rust?' and 'which variety of beans gives the greatest yield in one ___(22)___?'. In the course of his ___(23)___, the scientist may find what he thinks is one common explanation for an increasing number of facts. The explanation, if it seems consistently to fit the various facts, is called ___(24)___. If this continues to stand the test of numerous experiments and remains unshaken, it becomes a ___(25)___.";
  const CLOZE = [
      { question: "Gap 16: …to find, if he is able, the common _____ which underlie and account for the facts that he knows.", options: ["approaches", "instruments", "factors", "experiments"], answer: 2, explanation: "Things that 'underlie and account for' facts are causes, i.e. factors. An approach is a way of working; it can't underlie a fact.", keyVerdict: 'corrected', keyAnswer: 'A', answerNote: "'Approaches' are methods the scientist uses; they don't 'underlie and account for the facts'. The common factors (causes) do, so C is correct." },
      { question: "Gap 17: He chooses, when he can, the method of the controlled _____.", options: ["experiment", "respondent", "data", "system"], answer: 0, explanation: "'The controlled experiment' is the scientific method the rest of the passage describes." },
      { question: "Gap 18: …all the time keeping all other _____ (temperature, moisture, nourishment) the same.", options: ["procedures", "conditions", "studies", "objects"], answer: 1, explanation: "Temperature, moisture and nourishment are conditions in which the plants grow." },
      { question: "Gap 19: In this way, by keeping other variables _____ and by varying the light only…", options: ["dark", "constant", "good", "natural"], answer: 1, explanation: "Keeping variables constant (unchanged) is the opposite of 'varying' them, which the sentence contrasts with." },
      { question: "Gap 20: This _____ of using 'controls' can be applied to a variety of situations.", options: ["method", "research", "tool", "rationale"], answer: 0, explanation: "The passage already called it 'the method of the controlled experiment'; using controls is a method." },
      { question: "Gap 21: …'must moisture be present _____ is to rust?'", options: ["bar", "gold", "iron", "an alloy"], answer: 2, explanation: "Iron is the metal that rusts. Gold does not rust, and 'an alloy' or 'bar' is too general." },
      { question: "Gap 22: …'which variety of beans gives the greatest yield in one _____?'", options: ["period", "season", "climate", "weather"], answer: 1, explanation: "Crop yields are measured per growing season." },
      { question: "Gap 23: In the course of his _____, the scientist may find what he thinks is one common explanation for an increasing number of facts.", options: ["inquiries", "findings", "queries", "experiment"], answer: 3, explanation: "The passage is about the scientist's experiments, which build up facts over time ('in the course of')." },
      { question: "Gap 24: The explanation, if it seems consistently to fit the various facts, is called _____.", options: ["a principle", "a thesis", "a hypothesis", "an antithesis"], answer: 2, explanation: "A proposed explanation that fits the facts but is not yet proved is a hypothesis." },
      { question: "Gap 25: If this continues to stand the test of numerous experiments and remains unshaken, it becomes a _____.", options: ["notion", "deduction", "law", "thesis"], answer: 2, explanation: "A hypothesis that survives repeated testing becomes a scientific law." },
  ];

  const P1Q = [
      { question: "The expression 'we may well be asked' as used in the passage means", options: ["it is quite likely that we will be asked", "we cannot escape being asked", "the listener is always justified to ask questions", "it is inconceivable that we will be asked"], answer: 0, explanation: "'May well' means 'quite possibly': when a word's meaning is uncertain, it is quite likely someone will ask us to define it." },
      { question: "From the passage, which of these is a disadvantage of defining by enumeration?", options: ["The words or objects listed may not all share similar characteristics.", "Enumeration may not be all-inclusive.", "It always leaves doubts in the mind of the speaker.", "Many important members of the group may be left out of the enumeration."], answer: 1, explanation: "Listing examples (rabbit, dog, fish, goat) can't cover every member, so hearers may doubt whether a sea anemone or a slug is included. The list is not all-inclusive.", keyVerdict: 'corrected', keyAnswer: 'C', answerNote: "C says the doubt is in the mind of the speaker, but the passage says 'our hearers might... be doubtful'. The speaker knows what they mean. The doubt comes from the list not covering every case, which is B." },
      { question: "One of these summarizes the approaches to definition discussed in the passage.", options: ["Specifying clearly what distinguishes a particular word or object from its traditional groups.", "Indicating the class of a word and mentioning its general property with examples.", "Giving general and specific features followed by examples of what the object or word includes.", "Mentioning the class of a word or object with its specific property."], answer: 2, explanation: "The passage gives two approaches: the class (general) plus the distinguishing property (specific), and then enumerating examples. C covers both." },
      { question: "The writer uses the expression 'fixing the meaning of the words we use' to mean", options: ["getting even with the people who always ask for definitions", "using definitions to help build up their vocabulary", "repairing the damage done by inadequate definition during communication", "using definitions to help people communicate their thoughts and argue logically"], answer: 3, explanation: "The writer says that if our thought is to be clear and communicated, we must fix (settle) the meaning of our words, i.e. use definitions to communicate clearly." },
      { question: "Which of the following statements can be deduced from the passage?", options: ["There are both traditional and modern methods of defining words.", "Definitions aid communication when enumeration is accurately handled.", "Every speaker or writer has a method of defining words.", "Accurate definition is invaluable to communication but difficult to achieve."], answer: 3, explanation: "The passage says clear communication needs fixed meanings, and then shows how definitions can fail (wrong distinguishing mark, limited lists). So accurate definition matters but is hard." },
  ];
  const P2Q = [
      { question: "An appropriate title for this passage is", options: ["The Advantages of a Deregulated Economy", "Highlighting the Dangers of Deregulation", "Making a Case for Deregulation", "The problems of the NNPC"], answer: 2, explanation: "The writer answers the fears about deregulation and argues for it ('This appears to be the sense in deregulation'), so the passage makes a case for it." },
      { question: "Which of the following statements is true according to the passage?", options: ["The opposition to the deregulation of the oil industry is not unanimous.", "The Nigeria Labour Congress has been able to prevent the Government from deregulating the economy.", "The introduction of entrepreneurs to the oil industry will make life easy only for a few Nigerians.", "A better life for all Nigerians is conditional upon the deregulation of the economy."], answer: 0, explanation: "'Many Nigerians' (not all) are resentful, and the 'apostles of deregulation' support it, so the opposition is not unanimous. The NLC only threatened, and the passage does not claim D." },
      { question: "The writer seems to suggest that", options: ["Nigerians do not understand the sense in deregulation", "a deregulated economy will cause the Government to be indifferent to the plight of ordinary Nigerians", "only a heartless cartel will benefit by the deregulation of the oil industry", "the anxiety caused by the deregulation question is groundless"], answer: 3, explanation: "He says nothing suggests the Government will give up control, and that deregulation elsewhere made life easier, so the fears are groundless." },
      { question: "Which of the following conclusions can be reached from the passage?", options: ["Nigerians cannot buy fuel at exorbitant prices.", "The deregulation of the oil industry does not preclude the Government from exerting its influence.", "The deregulation of the economy will solve all the problems of petroleum products distribution.", "The Government is hell-bent on leaving Nigerians at the mercy of a heartless cartel."], answer: 1, explanation: "The passage says 'the absence of direct control does not mean that it will surrender all its rights', and the Government will still fix maximum prices." },
      { question: "Which of these correctly summarizes the arguments adduced by the advocates of deregulation?", options: ["Deregulating the economy will make the NNPC more efficient and less wasteful.", "Competition in the oil industry will be beneficial to several Nigerians.", "Competition should be allowed in the production and distribution of petroleum products.", "The Government should deregulate every aspect of the Nigerian economy."], answer: 1, explanation: "Their argument is that breaking the NNPC monopoly brings competition, which cuts waste and brings fair prices: 'Consumers will also have the last laugh because competition...'" },
  ];

  const P3 = "Recognizing the need for objectivity in their work, the early report writers worked to develop a writing style which would convey this attitude. They reasoned that the source of the subjective quality in a report is the human being. And they reasoned that objectivity is best attained by emphasizing the factual material of a report rather than the personalities involved. So they worked to remove the human being from their writing. Impersonal writing style was the result. By impersonal writing is meant writing in the third person \u2014 without I's, we's or you's.\n\nIn recent years, impersonal writing has been strenuously questioned by many writers. These writers point out that personal writing is more forceful and direct than is impersonal writing. They contend that writing which brings both reader and writer into the picture is more like conversation and therefore more interesting. And they answer to the point on objectivity with a reply that objectivity is an attitude of mind and not a matter of person. A report, they say, can be just as objective when written in personal style as when in impersonal style. Frequently, they counter with the argument that impersonal writing leads to an overuse of passive voice and a generally dull writing style. This last argument, however, lacks substance. Impersonal writing can and should be interesting. Any dullness it may have is wholly the fault of the writer. As proof, one has only to look at the lively styles used by the writers for newspapers, news magazines and journals. Most of this writing is impersonal \u2014 and usually it is not dull.\n\nAs in most cases of controversy, there is some merit to the arguments on both sides. There are situations in which personal writing is best. There are situations in which impersonal writing is best. And there are situations in which either style is appropriate. The writer must decide at the outset of his work which style is best for his own situation. His decision should be based on the circumstances of each report situation. First, he should consider the expectations or desires of those for whom he is preparing the report. More than likely he will find a preference for impersonal style, for, like most human beings, businessmen have been slow to break tradition. Next, the writer should consider the formality of the report situation. If the situation is informal, as when the report is really a personal communication of information between business associates, personal writing is appropriate. But if the situation is formal, as is the case with most reports, the conventional impersonal style is best.";
  const P3Q = [
      { question: "One argument given in support of personal writing is that it", options: ["has informal features which make it more diverting than impersonal writing", "makes writers more focused and less boring", "can be more objective than impersonal writing", "is the style to use in all situations involving businessmen"], answer: 1, alsoAccept: [0], explanation: "Its supporters say personal writing is 'more forceful and direct' and, being 'more like conversation', 'more interesting'.", keyVerdict: 'multiple', keyAnswer: 'B', answerNote: "The key's B (more focused, less boring) matches 'more forceful and direct' and 'more interesting'. A says the same thing in other words: being 'more like conversation' is its informal feature, and 'more interesting' means more diverting. Both are marked right." },
      { question: "Which of the following statements is true according to the passage?", options: ["The impersonal style helps to achieve a measure of objectivity in report writing.", "The impersonal style has been widely acclaimed.", "Most report writing is characterized by the sparing use of the impersonal style.", "Most writers use the impersonal style to achieve objectivity in their reports."], answer: 0, explanation: "Early report writers reasoned that 'objectivity is best attained' by removing the human being from their writing: the impersonal style." },
      { question: "According to the passage, most of the writing in newspapers, news magazines and journals is", options: ["personal and uninteresting", "personal and interesting", "impersonal and interesting", "impersonal and uninteresting"], answer: 2, explanation: "'Most of this writing is impersonal — and usually it is not dull.'" },
      { question: "From the passage, what determines the appropriateness of a style is the", options: ["theme", "reader", "writer", "situation"], answer: 3, explanation: "'His decision should be based on the circumstances of each report situation.'" },
      { question: "Which of the following best describes the writer of the passage?", options: ["He recognizes the need to be critical of report writing.", "He cannot be said to be objective.", "He is being unnecessarily analytic.", "He is completely non-committal."], answer: 0, explanation: "He weighs both sides critically, dismissing one argument as lacking substance, and then gives clear guidance, so he is neither biased nor non-committal." },
  ];
  const passages = [
    { passageId: 'eng-2002-p1', passageTitle: 'JAMB 2002 — Passage I', year: Y, instruction: READ, passage: P1, questions: P1Q },
    { passageId: 'eng-2002-p2', passageTitle: 'JAMB 2002 — Passage II', year: Y, instruction: READ, passage: P2, questions: P2Q },
    { passageId: 'eng-2002-p3', passageTitle: 'JAMB 2002 — Passage III', year: Y, instruction: READ, passage: P3, questions: P3Q },
    { passageId: 'eng-2002-p4', passageTitle: 'JAMB 2002 — Passage IV (cloze)', year: Y, instruction: 'The passage has gaps numbered 16 to 25. Choose the most appropriate option for each gap.', passage: P4, questions: CLOZE },
  ];

  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const GAP = 'Choose the option that best completes the gap(s): ';
  const VOWEL = 'Choose the option that has a DIFFERENT vowel sound from the others.';
  const CONS = 'Choose the option that has the same consonant sound as the letter(s) in capitals: ';
  const DIFF = 'Choose the option that has a DIFFERENT stress pattern from the others.';
  const FIRST = 'Choose the option that has the stress on the FIRST syllable.';
  const NEAR = 'Choose the option NEAREST in meaning to the word(s) in capitals: ';
  const MEANS = 'Select the option that best explains the information conveyed in the sentence: ';
  const EMPH = 'The word in capitals has emphatic stress. Choose the option that best fits the expression: ';
  const OPP = 'Choose the option OPPOSITE in meaning to the word(s) in capitals: ';

  const flat = [
    q(GAP + "_____ any problems, I shall travel to London tomorrow on a business trip.", ["In spite of", "Given", "Barring", "In case of"], C, "'Barring' means 'unless there are': barring any problems, I shall travel. 'In spite of any problems' would mean the problems are certain to happen."),
    q(GAP + "Musa has lived here for five years but he does not seem able to get over the enormously _____ and elaborate rules that govern the society.", ["bizarre", "intricate", "absurd", "fantastic"], B, "Intricate means very detailed and complicated, which pairs with 'elaborate rules' that are hard to get used to."),
    q(GAP + "The match gave the team a chance to show their _____.", ["mettle", "worth", "position", "prowess"], A, "To show one's mettle is a fixed expression: to prove one's courage and ability when tested."),
    q(GAP + "These _____ must have _____ the World Bank officials.", ["analysis/attracted", "analyses/attract", "analyses/attracted", "analysis/attract"], C, "'These' needs the plural 'analyses' (singular: analysis). After 'must have' we need the past participle 'attracted'."),
    q(GAP + "The highly appreciative audience clapped _____ hands and showered _____ on the lecturer.", ["its/encomiums", "its/invectives", "their/encomiums", "their/invectives"], C, "Each member clapped their own hands, so 'their'. An appreciative audience showers praise (encomiums), not abuse (invectives)."),
    q(GAP + "The members elected Baba _____ of the committee.", ["to be a chairman", "chairman", "their chairman", "to become chairman"], B, "After 'elect' the title of a single office takes no article: 'They elected Baba chairman of the committee.'"),
    q(GAP + "The officer described the comment as _____ because it was very amusing.", ["dangerous", "sad", "ludicrous", "libellous"], C, "Ludicrous means so silly that it is laughable, matching 'very amusing'."),
    q(GAP + "The new manager was responsible for the _____ of the organization.", ["uplifting", "lifting", "uplift", "upliftment"], C, "'Uplift' is the standard noun for improvement. 'Upliftment' is used in Nigerian and Indian English but is not standard British English."),
    q(GAP + "He is _____ Kaduna _____ an official assignment.", ["at/in", "at/for", "in/on", "for/in"], C, "We are 'in' a city (in Kaduna) and 'on' an assignment or errand."),
    q(GAP + "The future of the company is _____ though many seem _____ about it.", ["promising/nostalgic", "dicey/unsatisfied", "okay/optimistic", "rosy/pessimistic"], D, "'Though' signals contrast: the future is rosy (bright), though many are pessimistic about it."),
    q(GAP + "The army officer said that more _____ would be needed to prosecute the war.", ["geurrilas", "guerrilas", "geurrillas", "guerrillas"], D, "The correct spelling is guerrillas: g-u-e-r-r-i-l-l-a-s (double r, double l)."),
    q(GAP + "The quality of your questions which _____ always attracted attention _____ never been in doubt.", ["has/have", "have/have", "has/has", "have/has"], D, "'Which' refers to 'questions' (plural), so 'which have always attracted'. The main subject is 'the quality' (singular), so 'has never been in doubt'."),
    q(GAP + "Despite all preparations, the wedding did not _____.", ["come on", "come up", "come along", "come off"], D, "To 'come off' means to take place as planned, so the wedding did not come off. 'Come up' means to arise or be mentioned.", { keyVerdict: 'corrected', keyAnswer: 'B', answerNote: "'Come up' means to arise or be mentioned (a matter comes up at a meeting); it doesn't fit 'despite all preparations'. 'The wedding did not come off' (did not take place) is the idiom the sentence needs, so D is correct." }),
    q(GAP + "Didn't _____ draw your attention to the entry requirements?", ["somebody", "someone", "anyone", "everyone"], C, "In negative questions, 'any-' words are used: 'Didn't anyone draw your attention...?'"),
    q(GAP + "You are free to solicit _____ support from the Board.", ["financial", "by financial", "for financial", "a financial"], A, "'Solicit' takes a direct object: solicit financial support. 'Support' is uncountable here, so no 'a'."),
    q(GAP + "As Election Day draws near, the party looks _____ because many of its members have _____ other parties.", ["cheerless/cross carpeted from", "cheerful/moved to", "vulnerable/defected to", "successful/declared for"], C, "Members leaving makes the party vulnerable, and members 'defect to' another party. 'Cross carpeted from' would mean they left the other parties."),
    q(GAP + "Ali has been cured of his amnesia; he no longer suffers from _____.", ["rounds of anxiety", "bouts of malaria", "pains in his arms", "loss of memory"], D, "Amnesia is loss of memory."),
    q(GAP + "By this time next year, I _____ twenty years old.", ["will have been", "would have been", "could have been", "will be"], D, "A simple future fact about age: 'I will be twenty.' 'Will have been' would need a duration (e.g. will have been here for a year)."),
    q(GAP + "The operations of the bank _____ not _____ cottage and small-scale industries.", ["do/cover", "did/covered", "does/cover", "does/covered"], A, "The subject is 'operations' (plural), so 'do not cover'. After 'do/did' the verb takes its base form."),
    q(GAP + "We did not understand what the magistrate said about _____ and battery.", ["assault", "touching", "acid", "insult"], A, "'Assault and battery' is a fixed legal term for threatening and then attacking someone."),
    q(GAP + "Whenever we have _____, we feel better.", ["together a good long talk", "a long good talk together", "together a long good talk", "a good long talk together"], D, "Opinion adjectives (good) come before size/length (long), and the adverb 'together' goes after the noun phrase."),
    q(GAP + "The members of the other team agree _____ all the terms of the contract.", ["on", "by", "to", "with"], C, "We agree to terms, proposals or conditions; we agree with a person and agree on a decision reached together."),
    q(GAP + "One advantage of the English language in Nigeria is that it puts everyone _____ a common _____.", ["in/advantage", "in/standing", "on/footing", "at/equality"], C, "The idiom is 'on a common (equal) footing': on the same level."),
    q(GAP + "If one perseveres, _____ will surely succeed.", ["she", "they", "one", "he"], C, "Once a sentence starts with the pronoun 'one', it keeps 'one' throughout."),
    q(GAP + "_____ a motor can be harmful _____ your health.", ["To ride/with", "To ride/for", "Riding/to", "Riding/for"], C, "The gerund 'riding' is the natural subject here, and something is harmful 'to' your health."),
    q(VOWEL, ["mere", "weird", "hear", "tear (verb)"], D, "tear (verb, to rip) has /eə/ like 'air'; mere, weird and hear all have /ɪə/ like 'ear'."),
    q(VOWEL, ["does", "son", "flood", "world"], D, "world has the long /ɜː/ sound; does, son and flood all have the short /ʌ/."),
    q(VOWEL, ["cough", "rough", "rot", "dog"], B, "rough has /ʌ/ (it rhymes with 'stuff'); cough, rot and dog all have the short /ɒ/.", { keyVerdict: 'corrected', keyAnswer: 'D', answerNote: "dog has the same short /ɒ/ vowel as cough and rot, so it is not the odd one out. rough is pronounced /rʌf/, rhyming with 'stuff', so B is the word with a different vowel." }),
    q(CONS + "preachED", ["lotion", "castle", "question", "past"], D, "After the voiceless /tʃ/ in 'preach', -ed is pronounced /t/. The t in 'past' is /t/; in castle the t is silent, in lotion it is /ʃ/ and in question /tʃ/."),
    q(CONS + "buSiness", ["eyes", "grace", "rice", "sink"], A, "The s in 'business' is pronounced /z/, like the s in 'eyes'. grace, rice and sink have /s/."),
    q(CONS + "couGH", ["thoroughly", "of", "trophy", "though"], C, "The gh in 'cough' is /f/, like the ph in 'trophy'. It is silent in thoroughly and though, and the f in 'of' is /v/."),
    q(DIFF, ["convenient", "contribute", "embarrass", "madam"], D, "MAdam is stressed on the first syllable; conVEnient, conTRIbute and emBArrass on the second."),
    q(DIFF, ["suffer", "blackboard", "success", "calendar"], C, "sucCESS is stressed on the second syllable; SUFfer, BLACKboard and CAlendar on the first."),
    q(NEAR + "I wonder what will be left of his essay when the EXTRANEOUS material is deleted.", ["main", "relevant", "erroneous", "superfluous"], D, "Extraneous means not relevant, extra and unneeded, i.e. superfluous."),
    q(NEAR + "Tortoises need cool climates and must have places where they can HIBERNATE.", ["sleep deeply", "relax", "reproduce", "hide at night"], A, "To hibernate is to spend the winter in a deep sleep."),
    q(NEAR + "They are considered to be legal LUMINARIES.", ["experts", "practitioners", "directors", "powers"], A, "A luminary is someone famous and highly respected in their field, so legal luminaries are leading legal experts."),
    q(NEAR + "Practising medicine is not as lucrative as many people THINK.", ["know", "assume", "consider", "understand"], B, "Here 'think' means to believe without proof, i.e. to assume. 'Know' would mean it is a fact."),
    q(NEAR + "The manager made DISPARAGING remarks about the retiring officer.", ["parochial", "cynical", "derogatory", "rude"], C, "Disparaging means belittling or showing low opinion, i.e. derogatory."),
    q(NEAR + "The teacher's apparent nonchalant attitude was MISCONSTRUED by his students.", ["condoned", "misquoted", "misinterpreted", "misrepresented"], C, "To misconstrue is to understand something wrongly, i.e. to misinterpret it."),
    q(NEAR + "Let us not indulge in RECRIMINATION.", ["unfounded allegation", "counter-accusation", "accusation", "indictment"], B, "Recrimination is accusing someone in return for their accusation, i.e. counter-accusation."),
    q(NEAR + "Teachers of music believe in its THERAPEUTIC effect.", ["lyrical", "healing", "sound", "rhythmic"], B, "Therapeutic means having a healing effect."),
    q(NEAR + "The man outran his wife when they heard the EERIE sound.", ["hissing", "harsh", "scary", "loud"], C, "Eerie means strange and frightening, i.e. scary."),
    q(NEAR + "His success may be described as a PYRRHIC VICTORY.", ["a deserving victory", "costly", "indecisive", "an easy victory"], B, "A pyrrhic victory is won at such great cost that it is hardly worth it."),
    q(NEAR + "The Executive Secretary has just ASSUMED OFFICE.", ["resumed work", "been sworn in", "started work", "returned"], C, "To assume office is to take up a post and begin its duties, i.e. start work in it. Swearing in is the ceremony that may come before."),
    q(NEAR + "The warring tribes have been told to PARLEY with each other.", ["hold talks", "observe a truce", "suspend hostilities", "sign a treaty"], A, "To parley is to hold talks, especially between enemies."),
    q(NEAR + "He is A STRINGER FOR a newspaper.", ["a financier of", "a reporter for", "an editor of", "a freelancer for"], D, "A stringer is a journalist who is not on the staff but is paid for each piece, i.e. a freelancer."),
    q(NEAR + "Adigun's jokes are always PUERILE.", ["entertaining", "empty", "childish", "amusing"], C, "Puerile means silly and childish."),
    q(NEAR + "I wish the commander were LESS ADAMANT ABOUT his proposed REPRISAL attack on the enemy.", ["unyielding about/retaliatory", "tolerant of/surprise", "sentimental about/rehearsed", "supportive of/retributive"], A, "Adamant means refusing to change one's mind, i.e. unyielding; a reprisal attack is one made in retaliation."),
    q(FIRST, ["comment", "dismiss", "intact", "confuse"], A, "COMment is stressed on the first syllable; disMISS, inTACT and conFUSE on the second."),
    q(FIRST, ["commute", "import (verb)", "intend", "export (noun)"], D, "Two-syllable words used as both noun and verb stress the noun on the first syllable: an EXport, but to imPORT. comMUTE and inTEND stress the second."),
    q(MEANS + "The organization is constantly in a state of flux.", ["The organization is moribund.", "The organization is experiencing good times.", "The organization is facing a difficult period.", "There are periodic changes in the organization."], D, "Flux means continuous change."),
    q(MEANS + "His meteoric rise to fame surprised everyone.", ["People were amazed at his rapid success.", "He rose to the top quite unexpectedly.", "His rise to fame was only temporary.", "He became successful very suddenly."], A, "Meteoric means very rapid, and 'surprised everyone' means people were amazed. Only A carries both parts of the sentence."),
    q(MEANS + "The politician was pilloried by the press for his inflammatory remarks.", ["The politician was closely questioned by the press for his remarks.", "The politician was criticized by the press for his remarks.", "The politician was ridiculed by the press for his remarks.", "The politician was snubbed by the press for his remarks."], B, "To pillory someone is to criticise them severely in public."),
    q(MEANS + "Audu was taken bad in the middle of the night.", ["He was ill", "He was caught.", "He was drunk", "He was robbed."], A, "'Taken bad' (or 'taken ill') means suddenly became ill."),
    q(MEANS + "After the successful operation, he recovered by leaps and bounds.", ["His well-bound wounds aided his recovery.", "He did a lot of keep-fit exercises.", "He used to jog regularly.", "He got well very rapidly."], D, "'By leaps and bounds' means very quickly."),
    q(EMPH + "The university has been TEMPORARILY closed.", ["Has the university been permanently open?", "Has the campus been permanently closed?", "Has the college been temporarily closed?", "Has the university been permanently closed?"], D, "Stressing TEMPORARILY corrects 'permanently': it answers 'Has the university been permanently closed?'"),
    q(EMPH + "The king RAN to the palace.", ["Where did the king run to?", "Did the queen run to the palace?", "Did the king walk to the palace?", "Who ran to the palace?"], C, "Stressing RAN corrects the way he moved: it answers 'Did the king walk to the palace?'"),
    q(EMPH + "He travelled ONLY 20 kilometres before his car stopped.", ["Did he travel only 20 kilometres after his car stopped?", "Did he travel exactly 20 kilometres before his car stopped?", "Did he travel more than 20 kilometres before his car stopped?", "Did you walk only 20 kilometres before the vehicle stopped?"], C, "Stressing ONLY stresses how short the distance was: it answers 'Did he travel more than 20 kilometres?'"),
    q(EMPH + "The man BOUGHT the newspaper.", ["What did the man buy?", "Is this the newspaper which the man bought?", "Who bought the newspaper?", "Did the man read the newspaper?"], D, "Stressing BOUGHT corrects the action: it answers 'Did the man read the newspaper?'"),
    q(EMPH + "My UNCLE retired from the police.", ["Did your brother retire from the police?", "Did your brother resign from the police?", "Did your uncle retire from the army?", "Did your sister resign from the police?"], A, "Stressing UNCLE corrects only the person; everything else (retired, police) stays the same, as in A."),
    q(OPP + "The Governor's visit is AN UNPRECEDENTED event in the history of the social club.", ["an unnecessary", "a momentous", "a perfect", "an insignificant"], D, "An unprecedented event has never happened before and so is remarkable. Of the options, 'insignificant' is the furthest from it; 'momentous' is close to its meaning."),
    q(OPP + "He gave an unsatisfactory excuse but the boss swallowed it HOOK, LINE AND SINKER.", ["completely", "with a pinch of salt", "entirely", "without mincing words"], B, "To swallow something hook, line and sinker is to believe it completely; to take it with a pinch of salt is to doubt it."),
    q(OPP + "The principal took exception to the IGNOBLE role the teacher played in the matter.", ["dishonourable", "extraordinary", "honourable", "embarrassing"], C, "Ignoble means dishonourable, so its opposite is honourable."),
    q(OPP + "The HARDLINE posture of the labour leader has not helped matters.", ["imposing", "difficult", "compromising", "uncompromising"], C, "Hardline means refusing to compromise, so its opposite is compromising."),
    q(OPP + "The high cost of living these days calls for a lot of FRUGALITY.", ["economy", "recklessness", "prudence", "extravagance"], D, "Frugality is careful, sparing use of money; extravagance is spending too much."),
    q(OPP + "The evidence the leader gave was INCONTROVERTIBLE.", ["logical", "indubitable", "practicable", "contestable"], D, "Incontrovertible means impossible to dispute; contestable means open to dispute."),
    q(OPP + "Tunde's reaction UNDERSCORES the point I was making.", ["contradicts", "justifies", "summarizes", "emphasizes"], A, "To underscore a point is to support and emphasise it; to contradict it is to go against it."),
    q(OPP + "Everyone admired the manager's ADROIT handling of the crises in the company.", ["clever", "clumsy", "skilful", "tactless"], B, "Adroit means skilful and clever (with hands or mind), so its opposite is clumsy.", { keyVerdict: 'corrected', keyAnswer: 'D', answerNote: "Adroit means skilful; its direct opposite is clumsy (B), and dictionaries give 'clumsy' or 'maladroit' as its antonym. Tactless is the opposite of 'tactful' or 'diplomatic', a different quality." }),
    q(OPP + "The chairman's conduct REDOUNDS TO the image of the company.", ["contributes to", "detracts from", "assists in", "reflection"], B, "To redound to someone's credit is to add to it; to detract from it is to reduce it."),
    q(OPP + "Her PHLEGMATIC temperament endears her to her friends.", ["cold", "stoic", "lively", "irritable"], C, "Phlegmatic means calm and unemotional, slow to get excited; lively is the opposite."),
    q(OPP + "The President gave another EXTEMPORANEOUS speech last Friday.", ["fascinating", "unfavourable", "unprepared", "planned"], D, "An extemporaneous speech is given without preparation; its opposite is a planned one."),
    q(OPP + "The witness AVERRED that she had seen Dosun at the scene of the crime.", ["confirmed", "argued", "affirmed", "denied"], D, "To aver is to state firmly that something is true; to deny is the opposite."),
    q(OPP + "The workers suddenly became RESTIVE.", ["fidgety", "calm", "disorderly", "submissive"], B, "Restive means restless and hard to control; its opposite is calm."),
    q(OPP + "The athlete has unexpectedly become INDOMITABLE.", ["unruly", "unconquerable", "weak", "disoriented"], C, "Indomitable means impossible to defeat; its opposite is weak."),
    q(OPP + "He is NOTORIOUS for his drunkenness.", ["known", "renowned", "popular", "well known"], B, "Notorious means famous for something bad; renowned means famous for something good, so it is the opposite.", { keyVerdict: 'corrected', keyAnswer: 'D', answerNote: "'Well known' is close to the meaning of notorious, not its opposite: a notorious person is well known for something bad. 'Renowned' (famous for good reasons) is the standard antonym, so B is correct." }),
  ];

  QUESTION_BANK.english = QUESTION_BANK.english.concat(passages, flat);
})();
