/**
 * JAMB/UTME 2013 — USE OF ENGLISH
 * From the 2013 question paper; answers from the JAMB/UTME English Language
 * answer key 2001–2020, each checked against the paper. Where the key in
 * circulation is wrong (often a printing error) the question carries
 * keyVerdict + keyAnswer + answerNote (see english-2007.js for the scheme).
 * Not included: Q1 (paper type) and Q21-35 (questions on the set novels).
 *
 * Loaded after questions.js and before app.js.
 */
(function () {
  const Y = 2013;
  const SRC = 'JAMB UTME 2013';
  const READ = 'Read the passage carefully and answer the questions that follow.';

  const PT0 = "In 1951, the Government decided to start a Pottery Training Centre where new and more advanced technical methods, especially glazing, could be taught. The centre was intended to serve the whole of the defunct Northern Region, and there were several reasons for choosing Abuja. The first was the excellence of the traditional pottery made in the Emirate. Secondly, fire-wood is plentiful; this is a most important consideration, because in the making of glazed pottery, more firewood than clay is required. Thirdly, there are good clays, and good local sources for the raw materials needed for the glazes. Fourthly, water, which is another important raw material, is plentiful. Finally, Abuja is in a central position for the whole region and is a town where learners from many different parts can find a congenial temporary home, and where the Emir and his Council are actively interested in the project.\n\nNearly all the making is done by a process called 'throwing', so called because the lumps of clay are thrown by the potter onto a wheel-head. They are weighed out so that each pot will be roughly the same size; for example, for making pint-sized jugs, the lumps of clay will be one and a half kilogrammes. The potter sits on the saddle of the wheel and spins it by pushing a pedal with his left foot. He has a bowl of water, a loofah, a bamboo knife, a pointed stick or porcupine quill, a wooden smoothing tool which potters call a rib, and a piece of wire-like object that is used for wedging. He makes the wheel-head slightly damp, and throws the lumps into the middle. The first work is to force the lump to the centre, then he presses his thumb into the middle of the lump, using water to keep it slippery. When the bottom is of the right thickness, he begins to draw up the walls until they are of the right height. Then he shapes the belly and shoulder of the pot. He trims off any waste clay. In this way, a small and medium-sized pot can be made more quickly and accurately.";
  const PT1 = "Music plays a vital role in human society. Good music provides entertainment and emotional release, and it accompanies activities ranging from dances to religious ceremonies. Music is heard everywhere; in auditoriums, homes, elevators, schools, sports arenas and on the streets. Recorded performance is a sensational innovation elevation of the twentieth century. Thanks to modern technology like compact disc (CD) digital video disc (DVD) and the MP 3 player, music can now be heard in diverse places. Such places include living rooms and cars, jogging paths can also function as new kinds of concert halls where we can hear what we want as often as we want.\n\nLive performances provide a special excitement. In a live performance artistes put themselves on the line. To avoid embarrassment, the artiste must train beforehand and ensure that technical difficulties are avoided and that the listeners are actively involved. What is performed, how it sounds and how the artist feels that evening exist for a fleeting moment and can never be repeated. An audience responds to the excitement of such a moment and feelings are exchanged between stage and hall.\n\nOur response to a musical performance or an artiste is subjective and rooted in deep feelings. Even professional critics can differ strongly in their evaluations of a performance. There is no one \"Truth\" about what we hear and feel. Does the performance project a concept, an overall idea, or an emotion? Do some sections of a piece, but not others, communicate something to you? Can you figure out why? It is up to us as listeners to evaluate performances of music. Alert and repeated listening will enhance our ability to compare performances and judge music so that we can fully enjoy it. People listen to music in many different ways. For instance, music can be a barely perceived background as in a film or a totally absorbing experience as in a concert.";
  const PT2 = "Whatever may be its wider implications, the explosion of hydrogen bomb is, for the meteorologist, simply another atmospheric disturbance. It should therefore be classified with certain rare natural ___(11)___, such as volcanic ___(12)___. But there are certain features of a man-made disturbance that requires special examination. As with all events on this ___(13)___, it is impossible to describe what happens in details. However we can be reasonably sure of the main effects, and the most impressive of these arises from ___(14)___. The immediate result of the ___(15)___ is that the air surrounding the bomb is raised very rapidly to an enormously high ___(16)___. The hot gases expand violently as great ___(17)___, compressing the air around them into what is called ___(18)___, or blast wave that is responsible for much of terrible destructive power of the weapon.\n\nAnother kind of wave arises because of the weight of the air. The force of the explosion lifts the ___(19)___ around the bomb. The gravity waves can also resemble ordinary ___(20)___ waves. Waves of this type are normally felt by human beings and they have their effect on the weather.";

  const P1Q = [
      { question: "Which of the following is true according to the passage?", options: ["Anyone, with almost no training, can run pots on a wheel.", "Pots can be made quickly and correctly.", "A pot thrown on a wheel is less likely to break.", "The potter does not have to work hard if he uses the wheel."], answer: 1, explanation: "The passage ends: 'In this way, a small and medium-sized pot can be made more quickly and accurately.'" },
      { question: "From the passage, how does a potter make several pots of almost identical size?", options: ["By having the knowledge of different pots.", "By weighing the lumps of clay.", "By having the right tools.", "By knowing what to do from experience."], answer: 1, explanation: "The lumps of clay 'are weighed out so that each pot will be roughly the same size'." },
      { question: "The phrase 'trims off any waste clay', as used in the passage, means to", options: ["cut away unnecessary parts", "force the clay to the centre", "divide the clay into two", "wash away different colours"], answer: 0, explanation: "To trim off is to cut away, and waste clay is the clay the pot does not need." },
      { question: "The word 'congenial', as used in the passage, means", options: ["congested", "precise", "similar", "nice"], answer: 3, explanation: "A congenial home is a pleasant, agreeable one, i.e. nice." },
  ];
  const P2Q = [
      { question: "Which of the following is true according to the passage?", options: ["Music can enhance evaluation performance", "All listeners are music makers", "All artistes are objective in their feelings", "Music influences feelings at different levels"], answer: 0, alsoAccept: [3], explanation: "The passage says 'alert and repeated listening will enhance our ability to compare performances and judge music', which is what A is getting at. D is also supported: our response is 'rooted in deep feelings', and music can be a 'barely perceived background' or 'a totally absorbing experience'.", keyVerdict: 'multiple', keyAnswer: 'A', answerNote: "A (the key's answer) is a loose summary of 'repeated listening will enhance our ability to compare performances and judge music'. D is just as well supported: the passage says our response to music is 'rooted in deep feelings' and that music can be anything from a barely noticed background to a totally absorbing experience. Both are accepted." },
      { question: "The expression '...stage and hall', as used in the passage, means the", options: ["artiste and his music", "artiste and the audience", "producer and the director", "director and the audience"], answer: 1, explanation: "The stage stands for the performer and the hall for the people listening: feelings pass between the artiste and the audience." },
      { question: "From the passage, it can be deduced that music is", options: ["appreciated as the environment dictates", "better appreciated in a crowd", "better appreciated when we are happy", "better appreciated by professional critics"], answer: 0, explanation: "We listen in different ways depending on the setting: as background in a film or with full attention in a concert." },
      { question: "According to the writer, live performances provide a special excitement because they are", options: ["stage-managed", "interactive", "error-free and original", "educative"], answer: 1, explanation: "In a live performance the listeners are 'actively involved' and 'feelings are exchanged between stage and hall'." },
      { question: "According to the passage, music plays a vital role in human society because", options: ["music provides enjoyment and relief", "it is easy to appreciate music", "stage performance is the most popular music opportunity", "everybody can listen to music through the CD, MP3 and DVD"], answer: 0, explanation: "'Good music provides entertainment and emotional release', i.e. enjoyment and relief." },
  ];
  const CLOZE = [
      { question: "Gap 11: It should therefore be classified with certain rare natural _____, such as volcanic…", options: ["programmes", "occurrences", "resources", "laws"], answer: 1, explanation: "A volcanic eruption is a natural event, i.e. a natural occurrence." },
      { question: "Gap 12: …such as volcanic _____.", options: ["insurrection", "exhaustion", "eruption", "expulsion"], answer: 2, explanation: "Volcanoes erupt: 'volcanic eruption' is the fixed collocation." },
      { question: "Gap 13: As with all events on this _____, it is impossible to describe what happens in details.", options: ["scanner", "skate", "snow", "scale"], answer: 3, explanation: "'On this scale' means of this size; huge events are hard to describe in detail." },
      { question: "Gap 14: …and the most impressive of these arises from _____.", options: ["pressure waves", "pressure volume", "pressure air", "pressure gauge"], answer: 0, explanation: "The passage goes on to describe the shock waves, or blast wave, that the explosion produces, so the main effect arises from pressure waves.", keyVerdict: 'corrected', keyAnswer: 'B', answerNote: "'Pressure volume' is not a phrase that makes sense here: nothing 'arises from pressure volume'. The rest of the passage is all about waves (shock waves, blast wave, gravity waves), so the effect arises from pressure waves (A). The key's B is probably a printing slip." },
      { question: "Gap 15: The immediate result of the _____ is that the air surrounding the bomb is raised…", options: ["reduction", "commotion", "detonation", "distortion"], answer: 2, explanation: "A bomb's detonation is its explosion." },
      { question: "Gap 16: …the air surrounding the bomb is raised very rapidly to an enormously high _____.", options: ["way", "temperature", "class", "profile"], answer: 1, explanation: "The next sentence speaks of 'the hot gases', so the air is raised to a very high temperature." },
      { question: "Gap 17: The hot gases expand violently as great _____, compressing the air around them…", options: ["firearms", "fireballs", "fireworks", "firesmokes"], answer: 1, explanation: "A nuclear explosion produces a huge ball of hot, glowing gas: a fireball." },
      { question: "Gap 18: …compressing the air around them into what is called _____, or blast wave…", options: ["shock jocks", "shock therapy", "shock waves", "shock troops"], answer: 2, explanation: "A shock wave is the blast wave of compressed air sent out by an explosion." },
      { question: "Gap 19: The force of the explosion lifts the _____ around the bomb.", options: ["form", "atmosphere", "space", "height"], answer: 1, explanation: "The paragraph is about 'the weight of the air', so the explosion lifts the atmosphere (the air) around the bomb.", keyVerdict: 'corrected', keyAnswer: 'C', answerNote: "Space is emptiness and has no weight to lift. The sentence before says this wave arises 'because of the weight of the air', and the air around the bomb is the atmosphere, so B is correct." },
      { question: "Gap 20: The gravity waves can also resemble ordinary _____ waves.", options: ["stream", "lake", "ocean", "river"], answer: 2, explanation: "Ocean waves are the familiar large waves on water that these air waves resemble." },
  ];

  const passages = [
    { passageId: 'eng-2013-p1', passageTitle: 'JAMB 2013 — Passage I', year: Y, instruction: READ, passage: PT0, questions: P1Q },
    { passageId: 'eng-2013-p2', passageTitle: 'JAMB 2013 — Passage II', year: Y, instruction: READ, passage: PT1, questions: P2Q },
    { passageId: 'eng-2013-p3', passageTitle: 'JAMB 2013 — Passage III (cloze)', year: Y, instruction: 'The passage has gaps numbered 11 to 20. Choose the most appropriate option for each gap.', passage: PT2, questions: CLOZE },
  ];

  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const GAP = 'Choose the option that best completes the gap(s): ';
  const VOWEL = 'Choose the option that has a DIFFERENT vowel sound from the others.';
  const SAMEV = 'Choose the option that has the same vowel sound as the letter(s) in capitals: ';
  const CONS = 'Choose the option that has the same consonant sound as the letter(s) in capitals: ';
  const DIFFC = 'Choose the option that has a DIFFERENT consonant sound from the others.';
  const DIFF = 'Choose the option that has a DIFFERENT stress pattern from the others.';
  const SAMES = 'Choose the option that has the same stress pattern as the given word (stressed syllable in capitals): ';
  const STRESSOF = 'Choose the appropriate stress pattern for the word (the stressed syllable is in capitals): ';
  const FIRST = 'Choose the option that has the stress on the FIRST syllable.';
  const NEAR = 'Choose the option NEAREST in meaning to the word(s) in capitals: ';
  const MEANS = 'Select the option that best explains the information conveyed in the sentence: ';
  const EMPH = 'The word in capitals has emphatic stress. Choose the option that best fits the expression: ';
  const RHYME = 'Choose the option that rhymes with the given word: ';
  const OPP = 'Choose the option OPPOSITE in meaning to the word(s) in capitals: ';

  const flat = [
    q(MEANS + "The team's poor performance at the tournament plumb the depths of horror.", ["The team's performance took them to the next round.", "The team's performance was enjoyed by all.", "The team's performance was full of disappointment.", "The team performed well."], C, "To plumb the depths is to reach the lowest point, so the performance was dreadful and disappointing."),
    q(MEANS + "Tolu and Chinedu live in each other's pockets.", ["They are long-term business partners.", "They steal from each other.", "They blackmail each other.", "They are very close to each other."], D, "People who live in each other's pockets spend nearly all their time together: they are very close."),
    q(MEANS + "As the drama unfolded, Olatinuke was advised to keep her shirt on.", ["She was advised to wear her shirt.", "She was advised to commit herself.", "She was advised to stay calm.", "She was advised to join the club."], C, "'Keep your shirt on' is an informal way of telling someone not to get angry: stay calm."),
    q(MEANS + "He is a clinging child.", ["He is a handsome young man.", "He is possessive.", "He likes to cling with his sister.", "He is a bully."], B, "A clinging child depends too much on someone and will not let them go, i.e. he is possessive."),
    q(MEANS + "Zinana's examination result was not unfavourable.", ["She failed her examination.", "Her examination did not meet her expectation.", "She was successful in her examination.", "Her result could not earn her admission."], C, "'Not unfavourable' is a double negative meaning favourable: she did well."),
    q(MEANS + "You need to brush up on your Spanish.", ["You need to study the history of Spain.", "You need to improve your skills.", "You need a brush from Spain.", "You need to learn to play with a Spaniard."], B, "To brush up on a subject is to improve or refresh your skill in it. (The paper prints 'Spainard' in D.)"),
    q(MEANS + "Amaka would pass for a beauty queen.", ["She would pass the drink to the queen who is sitting next to her.", "She would be accepted by all as a beauty queen.", "She walked past the beauty queen.", "She was acting as a beauty queen."], B, "To pass for something is to be accepted as it: people would take her for a beauty queen."),
    q(MEANS + "'I can't wait to become a mother,' the new bride declared.", ["She sees motherhood as a burden.", "She is excited about motherhood.", "She is not keen on becoming a mother.", "She will be patient as a mother."], B, "'I can't wait' expresses eagerness, not impatience in a bad sense."),
    q(MEANS + "Usman needs to get his acts together if he wants to pass the examination.", ["He needs to put all points down in the examination.", "He needs to organize himself.", "He needs to be fast when writing the examination.", "He needs to put on his stage costume."], B, "To get your act together is to organize yourself and work effectively."),
    q(MEANS + "Ramatu expressed her feelings in no uncertain terms.", ["She expressed it clearly and strongly.", "She expressed it secretly and courageously.", "She expressed it quietly and cautiously.", "She expressed it feebly and sickly."], A, "'In no uncertain terms' means clearly and forcefully. (The paper prints 'Ramatu's expressed'.)"),
    q(OPP + "Chibuzor gave a CURT nod and walked away.", ["gentle", "rude", "polite", "shocking"], C, "A curt nod is abrupt and rude; the opposite is polite."),
    q(OPP + "The girl took a CURSORY glance at the letter and hid it.", ["sententious", "concise", "brief", "lasting"], D, "A cursory glance is quick and hurried; of the options, a lasting (long) glance is the opposite."),
    q(OPP + "The relationship between the couple has been FROSTY.", ["fraudulent", "cordial", "amenable", "frugal"], B, "A frosty relationship is cold and unfriendly; a cordial one is warm and friendly."),
    q(OPP + "The Nobel laureate's activity in the field of science is HEINOUS.", ["indelible", "laudable", "deplorable", "forgettable"], B, "Heinous means wicked and shocking; laudable means deserving praise."),
    q(OPP + "The accused was EVENTUALLY convicted.", ["initially", "consequently", "subsequently", "finally"], A, "Eventually means in the end; initially means at the start."),
    q(OPP + "The PLEBS can be found in every society of the world.", ["masses", "middle class", "elite", "politicians"], C, "The plebs are the ordinary common people; the elite are the privileged few at the top."),
    q(OPP + "Everyone's condition was APPALLING.", ["simple", "cloudy", "pleasant", "complex"], C, "Appalling means shockingly bad; pleasant is its opposite."),
    q(OPP + "The man's MORDANT wit is apparent to the entire village.", ["kind", "scathing", "caustic", "withering"], A, "Mordant wit is biting and sarcastic; scathing, caustic and withering are synonyms, kind is the opposite."),
    q(OPP + "The war against malaria keeps WAXING.", ["happening", "decreasing", "increasing", "wavering"], B, "To wax is to grow; the opposite is to wane, i.e. decrease."),
    q(OPP + "The soldiers tried in their DOGGED defence of the city.", ["indifferent", "strong", "miserable", "classical"], A, "A dogged defence is determined and persistent; indifferent means showing no interest or effort."),
    q(NEAR + "Ayodeji is an ARDENT supporter of education for the girl child.", ["an optimistic", "a cogent", "a passionate", "an ignorant"], C, "Ardent means enthusiastic and passionate."),
    q(NEAR + "The scholars' EPITAPH was demolished.", ["monument", "embodiment", "farmland", "book"], A, "An epitaph is the inscription on a tomb or memorial; since it was 'demolished', the nearest option is monument."),
    q(NEAR + "Mohammed does his work with so much ARDOUR.", ["enthusiasm", "discouragement", "knowledge", "indifference"], A, "Ardour is great enthusiasm or passion."),
    q(NEAR + "The athlete is proud to be in the VANGUARD of sports development.", ["unforgettable position", "leading position", "destructive position", "emerging position"], B, "The vanguard is the front, leading part of an army or movement."),
    q(NEAR + "Nwankwo was on the VERGE of signing a two-year contract with the club.", ["shore", "brink", "summit", "height"], B, "On the verge of = on the brink of: about to do something."),
    q(NEAR + "I am tired of your ETERNAL argument.", ["open", "constant", "strong", "useless"], B, "An eternal argument is one that never stops, i.e. constant."),
    q(NEAR + "The lamb is a FEEBLE little animal.", ["fat", "quiet", "loving", "weak"], D, "Feeble means weak."),
    q(NEAR + "The actress SCREAMED when she noticed an object behind her.", ["wailed", "protested", "waded in", "stormed out"], A, "To scream is to cry out loudly; wailed (cried out loudly) is nearest."),
    q(NEAR + "The EXHIBITION was an eye opener to all.", ["dispatch", "display", "style", "examination"], B, "An exhibition is a public display."),
    q(NEAR + "As a journalist, Bala has always had a NOSE for stories.", ["soft comment", "cynical statement", "an instinct", "a command"], C, "To have a nose for something is to have an instinct for finding it."),
    q(GAP + "The girl says she is averse _____ what others admire.", ["for", "from", "to", "with"], C, "The adjective averse takes the preposition to: averse to something."),
    q(GAP + "Our teacher defined _____ in his introductory.", ["onomatopiea", "onomatopoeia", "onomatopoeia", "onomatopea"], B, "The correct spelling is onomatopoeia (-poeia). The paper prints B and C identically.", { alsoAccept: [C], keyVerdict: 'multiple', keyAnswer: 'B', answerNote: "Options B and C are printed exactly the same, 'onomatopoeia', which is the correct spelling. So C is as right as the key's B, and both are accepted." }),
    q(GAP + "The philanthropist devoted himself _____ the poor.", ["to helping", "in helping", "by helping", "to be helping"], A, "We devote ourselves to something; after the preposition to, the verb takes -ing: devoted himself to helping."),
    q(GAP + "Tinu likes apples _____ she does not like oranges.", ["or", "for", "so", "but"], D, "But joins two contrasting statements: she likes apples but not oranges."),
    q(GAP + "The students had a _____ on Independence Day.", ["march past", "match pass", "march pass", "match past"], A, "A march past is a parade in which people march past a saluting point."),
    q(GAP + "Do you mind _____ another hour or two?", ["to wait", "to have waited", "wait", "waiting"], D, "Mind is followed by the -ing form: do you mind waiting?"),
    q(GAP + "The continuous rain has really _____ the soil.", ["melted up", "mopped up", "satiated", "saturated"], D, "Soil soaked with as much water as it can hold is saturated. Satiated is used for appetite."),
    q(GAP + "The police described the boy as being _____ hand.", ["on by", "up to", "over at", "out of"], D, "Out of hand means out of control."),
    q(GAP + "It was very easy for the two political parties to form a _____ government.", ["co-operative", "colonial", "collusion", "coalition"], D, "A government formed by two or more parties together is a coalition government."),
    q(GAP + "All farmers were encouraged _____ carry out fumigation on their farms.", ["to", "from", "in", "with"], A, "Encourage someone to do something: encouraged to carry out."),
    q(GAP + "There are lots of _____ in the park.", ["luxury buses moving fast", "luxury buses fast moving", "moving fast luxury buses", "fast-moving luxury buses"], D, "Modifiers come before the noun, with a hyphen joining the compound adjective: fast-moving luxury buses."),
    q(GAP + "Yours is to command; _____ is to obey.", ["their", "theirs", "theirs'", "their's"], B, "Like yours, the possessive pronoun theirs stands alone and never takes an apostrophe."),
    q(GAP + "Local governments are authorized to pass _____.", ["bye's-law", "bye-law", "bye-laws", "byes'-laws"], C, "Bye-laws (also spelt by-laws) are local rules; 'pass' a number of them takes the plural bye-laws."),
    q(GAP + "Umar: I have never visited the dentist. Aliyu: _____.", ["neither have I", "I also never", "neither myself", "I myself haven't"], A, "To agree with a negative statement we say 'Neither have I', repeating the auxiliary have."),
    q(GAP + "Usman would have won the race _____.", ["if he had run faster faster", "although he ran faster", "only if he could run fast", "if he had run faster"], D, "Would have won goes with the past perfect: if he had run faster. A as printed repeats 'faster'."),
    q(GAP + "My father told me to take the money from _____ it.", ["ever who offers", "whoever offers", "whomever offers", "whomsoever offer"], B, "Whoever is the subject of 'offers', so the subject form whoever is needed, even after from."),
    q(GAP + "Our teacher defined _____ as the killing of one's mother.", ["patriach", "matricide", "matriarch", "patricide"], B, "Matricide is killing one's mother; patricide is killing one's father."),
    q(GAP + "If you are confused _____ anything, phone my office.", ["about", "for", "of", "with"], A, "We are confused about something."),
    q(GAP + "We have a family mutiny _____ our hands.", ["from", "of", "on", "for"], C, "To have a problem on your hands is to have to deal with it."),
    q(GAP + "We should try to help _____.", ["the less fortunate", "this less fortunate", "the less fortunate", "less fortunate"], A, "'The' + adjective names a whole group of people: the less fortunate. The paper prints A and C identically.", { alsoAccept: [C], keyVerdict: 'multiple', keyAnswer: 'A', answerNote: "Options A and C are printed exactly the same, 'the less fortunate', which is the correct answer. So C is as right as the key's A, and both are accepted." }),
    q(SAMEV + "glAsier", ["gleam", "flat", "feign", "glass"], C, "Glazier (printed 'glasier') is /ˈɡleɪziə/: the a is /eɪ/, as the ei in feign.", { keyVerdict: 'corrected', keyAnswer: 'D', answerNote: "The a in glazier is pronounced /eɪ/, like glaze. Glass has the long /ɑː/, a different sound. Feign /feɪn/ has /eɪ/, so C is correct." }),
    q(SAMEV + "lAUd", ["lavatory", "loud", "lathe", "core"], D, "The au in laud is /ɔː/, the same vowel as in core."),
    q(SAMEV + "cOma", ["colonel", "cogent", "come", "comma"], B, "The o in coma is /əʊ/, as in cogent /ˈkəʊdʒənt/."),
    q(CONS + "loSe", ["mouse", "nurse", "noise", "horse"], C, "The s in lose is /z/, as the s in noise; mouse, nurse and horse end in /s/."),
    q(CONS + "Guitar", ["jam", "strange", "judge", "rogue"], D, "The g in guitar is the hard /ɡ/, as in rogue; the others have /dʒ/."),
    q(CONS + "looSe", ["sell", "fuse", "close", "rouse"], A, "The s in loose is /s/, as in sell; fuse and rouse have /z/, and so does close as a verb (to close a door)."),
    q(RHYME + "rite", ["list", "wit", "wright", "rim"], C, "Rite and wright are both pronounced /raɪt/."),
    q(RHYME + "joys", ["elbow", "pots", "boys", "stays"], C, "Joys /dʒɔɪz/ rhymes with boys /bɔɪz/."),
    q(RHYME + "call", ["wall", "quail", "dull", "slate"], A, "Call /kɔːl/ rhymes with wall /wɔːl/."),
    q(STRESSOF + "dedication", ["dedicaTION", "deDIcation", "dediCAtion", "Dedication"], C, "Words ending in -tion are stressed on the syllable just before it: de-di-CA-tion."),
    q(STRESSOF + "international", ["interNAtional", "internaTIONal", "International", "inTERnational"], A, "International is stressed on the third syllable: in-ter-NA-tion-al."),
    q(STRESSOF + "information", ["inFORmation", "Information", "inforMAtion", "InformatION"], C, "Information is stressed on the syllable before -tion: in-for-MA-tion."),
    q(EMPH + "Adamu is leaving a CAR behind.", ["What is Adamu leaving behind?", "Is Adamu driving the car in front?", "Who is leaving a car behind?", "Where is Adamu leaving a car?"], A, "Stress on CAR answers a question about what he is leaving behind."),
    q(EMPH + "Lambusa TOOK OFF the wig.", ["Who took off the wig?", "What did Lambusa do?", "Did Lambusa take off a wig?", "Did Lambusa take off the ring?"], B, "Stress on the verb TOOK OFF answers a question about the action: what did Lambusa do?"),
    q(EMPH + "The bed is IN the room.", ["Is the bed in the parlour?", "Was the bed in the room?", "What is in the room?", "Where is the bed?"], D, "Stress on IN gives the bed's exact position (inside, not outside, the room), answering a question about where it is."),
  ];

  QUESTION_BANK.english = QUESTION_BANK.english.concat(passages, flat);
})();
