/**
 * JAMB/UTME 2008 — USE OF ENGLISH
 * From the 2008 question paper; answers from the JAMB/UTME English Language
 * answer key 2001–2020, each checked against the paper. Where the key in
 * circulation is wrong (often a printing error) the question carries
 * keyVerdict + keyAnswer + answerNote (see english-2007.js for the scheme).
 * Paper question 1 (paper type) and question 5 (not printed in the paper) are omitted.
 * Loaded after questions.js and before app.js.
 */
(function () {
  const Y = 2008;
  const SRC = 'JAMB UTME 2008';
  const READ = 'Read the passage carefully and answer the questions that follow.';

  const PT0 = "Success is one of the words in the English language that are defined and illustrated in various ways by many. Even though all of those definitions and illustrations are often understood by people, they present various and complex perspectives of people who define them. Considering the definitions of the concept, a wide spectrum of their evaluation may be provided. This provision is from the perspective of people who may be seen as materialistic to that of those seen as spiritual.\n\nOne definition of a successful person is someone who has all that he or she wants in life \u2014 a beautiful wife or a handsome husband, a lovely family with very attractive children, standard education, a well-paid job, a well-furnished house, sufficient money and investments to guarantee a comfortable life even after retirement. All of these possessions and materials are symbolic of a successful person. Another definition of success is the gift of health. The argument is that whatever possession or material things one may have, without good health, they become totally irrelevant and worthless. After all, 'Health is wealth' as the popular adage goes.\n\nAnother point is that no one can really know whether or not he is successful because success is a relative term. By this, the concept of success varies not only from person to person, but also from culture to culture. In other words, what the people from one culture might regard as success may not be so regarded by people from another culture. Furthermore, there is the point of view that in some cultures, material possession is not indicative of real success. There are examples of some rich people in various societies whose tremendous material possessions were squandered by those who inherited them just years after the original owners had died. Most of the material possessions of people in several societies might have been acquired not by hard work but fraudulent means. This cannot be success because success means a true and honest life devoid of any fraudulent practices.\n\nFrom the spiritual dimension, success may mean the fulfilment of divine purpose in one's life. That appears to be a complex statement! One needs, perhaps, a spiritual leader to interpret the relationship between God and success. Whether or not one believes in divine power as a phenomenon should not bother us here. What is certain is that the physical world itself presents to any discerning heart evidence that there must be an unseen hand behind one's success or failure.\n\nAll said and done, true success may be one's ability to be satisfied with one's position in life.";
  const PT1 = "Every human language may be described as a system at each of the four levels of linguistic description, namely morphology, phonology, syntax and semantics. At each of these levels, a linguistic system comprises a number of sub-systems which make up its structure. Thus, a language may also be described as a system of systems. At the level of phonetics and phonology, a language selects, from a general pool of speech sounds, a finite number of vocal sounds which are combined and used for its communicative and other purposes.\n\nLooking at the human vocal organs, it appears that their primary functions are biological. Even though they are also used for breathing, chewing, cutting, swallowing and smelling, they have been adapted for the production of the speech sounds of any human language. But human languages are different in terms of their sound inventories. The point is each language has its own number of sounds which are combined in a number of indefinite patterns according to its own phonological rules. This is what makes each language unique as systematic patterns of structure, and perhaps why English uses forty-four sound segments, French forty, Italian twenty-seven, Yoruba twenty-seven and Hawaiian only thirteen.\n\nThere are four basic approaches to the study of speech sounds. These are articulatory, acoustic, auditory and forensic. Articulatory phonetics studies how speech sounds are made or articulated. Acoustic phonetics studies the physical properties of speech as sound waves in air. Auditory or perceptual phonetics studies the perception of speech sounds via the ears. The forensic phonetics studies speech sounds in the form of recorded utterances used for identifying a particular speaker, especially in a legal case.\n\nThe articulatory approach helps the user of English as a second language to understand how the sounds of English are articulated as well as their basic characteristics. This knowledge may help to improve their pronunciation competence or fluency in the actual use of language. It may also improve the degree of intelligibility of their utterances and therefore their communicative competence.\n\nAccording to Yule in his book Introduction to Language, phonology is concerned with the abstract or theoretical aspect of speech sounds while phonetics is concerned with their actual physical articulation. Thus, by studying the systems and patterns of speech sounds in a language, we are actually studying phonology. It is phonology that explains the underlying design, the blueprint of the sound type, which provides the basis for all the variations in different physical articulations of that sound type in different contexts.";
  const PT2 = "Schizophrenia is a chronic, severe and disabling brain disease. Approximately one per cent of the population develop the disease during their lifetime. Although schizophrenia affects men and women with equal frequency, the disorder often appears earlier in men, usually in the late teens or early twenties, than in women, who are generally affected in the twenties to early thirties. People with the disorder often suffer terrifying symptoms such as hearing internal voices not heard by others or believing that other people are reading their minds, controlling their thoughts or plotting to harm them. These symptoms may leave them fearful and withdrawn. Children over the age of five can develop the disease, but it is very rare before adolescence.\n\nPeople with Schizophrenia may have perceptions of reality that are strikingly different from one seen and shared by others around them. Living in a world distorted by hallucinations and delusions, individuals with the disease may feel frightened, anxious and confused. Hallucinations are perceptions that occur without connection to an appropriate source. Delusions are false personal beliefs that are not subject to reason or contradictory evidence.\n\nSubstance abuse is a common concern of the family and friends of people with Schizophrenia as it can reduce the effectiveness of treatment of the disease. Stimulants such as cocaine and marijuana may cause major problems for patients with Schizophrenia. In fact, some people experience a worsening of the symptoms when they take such drugs. Substance abuse also reduces the likelihood that patients will follow the treatment plans recommended by their doctors.\n\nThe most common form of substance used disorder in people with Schizophrenia is nicotine dependence due to smoking. Quitting smoking may be especially difficult for people with Schizophrenia because the symptoms of nicotine withdrawal may cause a temporary worsening of the disorder symptoms. However, smoking cessation strategies that include nicotine replacement methods may be effective. Doctors should carefully monitor medication dosage and response when patients with the disease either start or stop smoking. The large majority of people with the disease show substantial improvement when treated with antipsychotic drugs. Some patients, however, are not helped very much by the medications and a few do not seem to need them. It is difficult to predict which patients will fall into these two groups. Antipsychotic drugs, like virtually all medications, have unwanted effects along with other symptoms. During the early phases of drug treatment, patients may be troubled by side effects such as drowsiness, restlessness, tremor, dry mouth or blurring of vision. Most of these can be corrected by lowering the dosage or controlled by other medications.";
  const PT3 = "The economic miracle of the so called Asian Tigers was subject to much debate and analyses in the early 1990s among economists. There was basically two schools of ___(16)___. One, that the Asian Tigers' economic miracle was a case of 'miracles beyond the free market' and so to repeat such miracles or something near it, do not leave the ___(17)___ to the invisible hands of the free market with its sometimes profoundly anti-social overtones. There was a place for, and indeed a great virtue in, state ___(18)___. The other group ___(19)___ that it was not so much a miracle that was either beyond the free market or, for that matter, one induced by the equally unpredictable, even if visible, hands of politicians and policy ___(20)___. The Asian ___(21)___ was rather one of a cultural phenomenon blending with good policies to produce a delightfully desirable spectacle of progress and ___(22)___. The concern of the economists was how to safely ___(23)___ and then apply the Asian prescription to replicate such man-made miracles in many other countries of the world enduring the ___(24)___ of unrelenting and ___(25)___ poverty.\n\n(Adapted from the Punch, 7 November, 2005)";

  const P1Q = [
      { question: "From the passage, it can be inferred that", options: ["the writer is not dogmatic about any of the definitions of success", "possessions inherited are fraudulent wealth", "true success will be known to all men in due time", "the writer believes that success is symbolic of good living"], answer: 0, explanation: "The writer sets out several definitions (material, health, cultural, spiritual) without insisting on any one, and ends cautiously with 'true success may be'." },
      { question: "The expression 'success is a relative term' suggests that it", options: ["has one meaning", "has different meanings", "is not comprehensible", "can be defined materially"], answer: 1, explanation: "A relative term has no fixed meaning: success 'varies not only from person to person, but also from culture to culture'." },
      { question: "From the passage, a successful person is described as one who", options: ["believes in divine intervention", "enjoys life after retirement", "has a good family", "is contented with life"], answer: 3, explanation: "The writer's conclusion: 'true success may be one's ability to be satisfied with one's position in life'." },
  ];
  const P2Q = [
      { question: "According to the passage, which of the following describes the perception of speech sound?", options: ["Acoustic", "Auditory", "Articulatory", "Forensic"], answer: 1, explanation: "'Auditory or perceptual phonetics studies the perception of speech sounds via the ears.'" },
      { question: "From the passage, the purpose of describing a language as a system is to show that", options: ["all human languages are the same in every sense", "human languages are different at the phonological level", "every human language has its own separate patterns of structure at all levels", "human languages are too complex to understand at any level"], answer: 2, explanation: "A language is a system at each of the four levels, made up of sub-systems: its own structure at every level, 'a system of systems'." },
      { question: "What distinguishes a language from another, according to the passage, is", options: ["its finite number of sounds", "the indefinite nature of its patterns", "its communicative and other purposes", "its linguistic description at all levels"], answer: 1, explanation: "Each language combines its sounds 'in a number of indefinite patterns according to its own phonological rules. This is what makes each language unique'." },
      { question: "The style of the passage could best be described as", options: ["expository", "descriptive", "narrative", "argumentative"], answer: 0, explanation: "The passage explains and informs about linguistics, phonetics and phonology: expository writing." },
      { question: "The expression 'systematic patterns of structure', as used in the passage, means that language", options: ["is an interconnecting network of structure", "is made up of organized phonetics and phonology", "is an interconnecting and semantics", "comprises similar phonetics, phonology, morphology and semantics"], answer: 0, explanation: "A language is 'a system of systems': sub-systems at different levels linked together into one network." },
  ];
  const P3Q = [
      { question: "One conclusion that can be drawn from the first paragraph is that", options: ["only children suffer Schizophrenia disorder", "the time of occurrence in men and women differs", "women suffer the disorder in their early twenties", "men suffer the disorder in their early thirties"], answer: 1, explanation: "The disorder 'often appears earlier in men, usually in the late teens or early twenties, than in women'." },
      { question: "Which of the following is true according to the passage?", options: ["Schizophrenia disorder affects only the menfolk", "Schizophrenia disorder develops only in the womenfolk", "patients with Schizophrenia like to keep to themselves than stay with others", "children develop the Schizophrenia disorder after adolescence"], answer: 3, explanation: "Children over five can develop it, 'but it is very rare before adolescence', so it usually develops after adolescence." },
      { question: "Which of the following statements is true of the concept of delusions in the second paragraph?", options: ["The belief in distorted claims", "The expressions of personal beliefs", "The evidence of reasoning and contradictions", "The belief in unsubstantiated claims"], answer: 3, explanation: "'Delusions are false personal beliefs that are not subject to reason or contradictory evidence': beliefs in claims with no proof. (The paper prints 'believe' for 'belief' in A and D.)" },
      { question: "From the passage, it can be inferred that", options: ["family members and friends avoid Schizophrenia patients", "cocaine and marijuana are good stimulants for patients", "substance abuse may assist a patient's healing process", "some drugs slow down a patient's healing process"], answer: 3, explanation: "Substance abuse 'can reduce the effectiveness of treatment', and stimulants such as cocaine worsen the symptoms." },
      { question: "The expression 'living in a world distorted by hallucinations' means", options: ["the world of sound and intellectual thought", "the expression of ideas that do not have bases", "a patient's expression of connected ideas", "the world is very unfair to Schizophrenic patients"], answer: 1, explanation: "Hallucinations are perceptions 'without connection to an appropriate source', so the patient lives among ideas that have no basis in reality. (The options are jumbled across lines in the paper; they are given here as they read.)" },
  ];
  const CLOZE = [
      { question: "Gap 16: There was basically two schools of _____.", options: ["reasoning", "ideas", "practice", "thought"], answer: 3, explanation: "The fixed expression is 'school of thought': a group sharing a view." },
      { question: "Gap 17: ...and so to repeat such miracles or something near it, do not leave the _____ to the invisible hands of the free market.", options: ["economy", "structure", "miracle", "analyses"], answer: 0, explanation: "It is the economy that is (or is not) left to the 'invisible hand' of the free market." },
      { question: "Gap 18: There was a place for, and indeed a great virtue in, state _____.", options: ["market", "intervention", "persuasion", "enforcement"], answer: 1, explanation: "The first group rejects pure free-market forces, so it favours state intervention in the economy." },
      { question: "Gap 19: The other group _____ that it was not so much a miracle...", options: ["synthesized", "analysed", "believed", "recommended"], answer: 2, explanation: "The two schools hold views, so the other group 'believed' something; a that-clause of opinion follows." },
      { question: "Gap 20: ...induced by the equally unpredictable, even if visible, hands of politicians and policy _____.", options: ["deciders", "masters", "executors", "markers"], answer: 3, explanation: "The collocation is 'policy makers'; 'markers' is a misprint for 'makers'." },
      { question: "Gap 21: The Asian _____ was rather one of a cultural phenomenon...", options: ["experience", "practice", "logic", "method"], answer: 0, explanation: "What happened in Asia, taken as a whole, is the Asian experience." },
      { question: "Gap 22: ...to produce a delightfully desirable spectacle of progress and _____.", options: ["purpose", "affluence", "prospect", "prosperity"], answer: 3, explanation: "'Progress and prosperity' is the natural pair for economic success." },
      { question: "Gap 23: The concern of the economists was how to safely _____ and then apply the Asian prescription...", options: ["prescribe", "guage", "stimulate", "re-orientate"], answer: 3, explanation: "Economists wanted to adapt (re-orientate) the Asian prescription to other countries before applying it.", alsoAccept: [1], keyVerdict: 'multiple', keyAnswer: 'D', answerNote: "The paper prints 'guage', a misprint for 'gauge' (to assess). 'How to safely gauge and then apply the Asian prescription' makes as much sense as the key's 're-orientate' (adapt) and then apply, so both are marked right." },
      { question: "Gap 24: ...in many other countries of the world enduring the _____ of unrelenting and ...", options: ["anger", "risk", "throes", "punishment"], answer: 2, explanation: "To be in the throes of something is to be struggling through its pains." },
      { question: "Gap 25: ...of unrelenting and _____ poverty.", options: ["momentous", "compelling", "scorching", "aggravating"], answer: 2, explanation: "Scorching poverty is poverty that burns severely, matching 'unrelenting'." },
  ];

  const passages = [
    { passageId: 'eng-2008-p1', passageTitle: 'JAMB 2008 — Passage I', year: Y, instruction: READ, passage: PT0, questions: P1Q },
    { passageId: 'eng-2008-p2', passageTitle: 'JAMB 2008 — Passage II', year: Y, instruction: READ, passage: PT1, questions: P2Q },
    { passageId: 'eng-2008-p3', passageTitle: 'JAMB 2008 — Passage III', year: Y, instruction: READ, passage: PT2, questions: P3Q },
    { passageId: 'eng-2008-p4', passageTitle: 'JAMB 2008 — Passage IV (cloze)', year: Y, instruction: 'The passage has gaps numbered 16 to 25. Choose the most appropriate option for each gap.', passage: PT3, questions: CLOZE },
  ];

  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const GAP = 'Choose the option that best completes the gap(s): ';
  const VOWEL = 'Choose the option that has a DIFFERENT vowel sound from the others.';
  const SAMEV = 'Choose the option that has the same vowel sound as the letter(s) in capitals: ';
  const CONS = 'Choose the option that has the same consonant sound as the letter(s) in capitals: ';
  const DIFFC = 'Choose the option that has a DIFFERENT consonant sound from the others.';
  const DIFF = 'Choose the option that has a DIFFERENT stress pattern from the others.';
  const SAMES = 'Choose the option that has the same stress pattern as the given word (stressed syllable in capitals): ';
  const STRESSOF = 'Choose the appropriate stress pattern for the word (the stressed syllable is in capitals): ';
  const FIRST = 'Choose the option that has the stress on the FIRST syllable.';
  const NEAR = 'Choose the option NEAREST in meaning to the word(s) in capitals: ';
  const MEANS = 'Select the option that best explains the information conveyed in the sentence: ';
  const EMPH = 'The word in capitals has emphatic stress. Choose the option that best fits the expression: ';
  const OPP = 'Choose the option OPPOSITE in meaning to the word(s) in capitals: ';

  const flat = [
    q(MEANS + "The court brought out the fact that the elections were not free and fair.", ["The court said that the elections were not rigged", "The court explained that the elections were marred", "The court made it clear that the elections were not flawless", "The court saw that the elections were properly conducted"], C, "To bring out a fact is to make it clear; elections that were not free and fair were not flawless."),
    q(MEANS + "The computer operator was sacked for incompetence.", ["The computer operator was sacked for his foolishness", "The computer operator was sacked for his laziness", "The computer operator was sacked for lack of skill", "The computer operator was sacked for lateness"], C, "Incompetence means lack of the skill or ability to do a job."),
    q(MEANS + "He was a member of the think tank of the previous administration.", ["As an expert, he criticised government", "He was an expert who gave advice to government", "He was an expert that government did not listen to", "As an expert, government must have taken to his advice"], B, "A think tank is a group of experts who give advice and ideas to a government."),
    q(MEANS + "In spite of various criticisms, Bala sticks to his guns.", ["Bala always goes out with his guns, ready to kill", "people do not like Bala because he is violent", "Bala is criticized because of his bad behaviour towards people", "Bala adheres to his beliefs even when others do not agree with him"], D, "To stick to one's guns is to hold firmly to one's position despite opposition."),
    q(MEANS + "Chike plays to the gallery whenever he meets a group of people.", ["Chike plays well with people at the gallery", "Chike seeks cheap popularity", "Chike shows distrust and hatred to people", "Chike shows distrust and hatred to people"], B, "To play to the gallery is to behave in a showy way to win cheap popularity. (Options C and D are printed identically in the paper.)"),
    q(MEANS + "He kept a stiff upper lip over the accident.", ["He sustained injury on his upper lip", "He endured the misfortune with courage", "He could not talk because of the accident", "His friends deserted him because of the accident"], B, "To keep a stiff upper lip is to bear trouble bravely without showing one's feelings."),
    q(MEANS + "He had travelled the length and breadth of Africa.", ["He must have travelled to some big cities of Africa", "He had travelled to many parts of Africa", "He had travelled to all parts of Africa", "He had travelled to all the villages and towns of Africa"], C, "The length and breadth of a place means every part of it."),
    q(MEANS + "She wriggled out of her wedding gown.", ["She could not take off her gown herself so she was assisted", "Her dress got torn because of the snake-like pattern", "No one could have imagined that her dress was so light", "It took her some time to remove her close-fitting dress"], D, "To wriggle out of a tight dress is to twist and turn slowly to get it off."),
    q(MEANS + "Visitors who are observant do not outstay their welcome.", ["All visitors must be alert so as to know when to leave a place", "Some visitors know when to leave a place so as to make their hosts happy", "Some visitors are unable to know when their hosts do not want them around", "All visitors, except a few, know when to leave a place"], A, "Being observant (alert) is what lets a visitor know when it is time to leave.", { alsoAccept: [1], keyVerdict: 'multiple', keyAnswer: 'A', answerNote: "'Visitors who are observant' refers to some visitors, the observant ones, who know when to leave (B). The key's A (all visitors must be alert) captures the same lesson as advice, so both are marked right." }),
    q(MEANS + "The group had been made a scape goat during the event.", ["Members of the group had been punished for a sin that they did not commit", "Members of the group had been blamed for a sin that they committed", "The group had been punished so that no one would commit the sin again", "The group had been blamed merely to serve as a deterrent to others"], A, "A scapegoat is someone punished or blamed for the wrongs of others."),
    q(OPP + "Sola is APATHETIC about his work.", ["indifferent", "enthusiastic", "half-hearted", "bored"], B, "Apathetic means showing no interest; enthusiastic means full of interest."),
    q(OPP + "The members of the family had a HASTY breakfast before starting out on their journey.", ["hurried", "leisurely", "tasty", "nasty"], B, "Hasty means hurried; the opposite is leisurely. (The paper prints 'nasty' in the question, an obvious misprint for 'hasty'.)"),
    q(OPP + "The POVERTY level among the masses is unbearable.", ["arrogance", "saturation", "affluence", "influence"], C, "Poverty is lack of wealth; affluence is wealth."),
    q(OPP + "The chairman was accused of implementing policies that favoured the ELITE.", ["oppressed", "executives", "jobless", "citizens"], A, "The elite are the privileged few at the top; the oppressed are those kept down."),
    q(OPP + "The manager was impressed by the man's EAGERNESS.", ["impatience", "indifference", "negligence", "calmness"], B, "Eagerness is keen interest; indifference is lack of interest."),
    q(OPP + "He is known for making THREADBARE arguments as a scholar.", ["justifiable", "baseless", "empty", "militant"], A, "A threadbare argument is weak and worn-out; a justifiable one is sound and well supported."),
    q(OPP + "The lecturer's OBSCURE publications counted against him during the promotion exercise.", ["widespread", "closed", "circulated", "restricted"], A, "Obscure publications are little known; widespread ones are widely known."),
    q(OPP + "The man found his wife physically REPELLENT.", ["attractive", "fatuous", "unpleasant", "flamboyant"], A, "Repellent means very unpleasant to look at; the opposite is attractive."),
    q(OPP + "As an ABSOLUTE RULER, Adayi brooks no opposition from his subordinates.", ["a despotic dictator", "a shameless king", "a benevolent leader", "a magnanimous democrat"], D, "An absolute ruler holds all power and allows no opposition; a democrat shares power and accepts opposition.", { alsoAccept: [C], keyVerdict: 'multiple', keyAnswer: 'C', answerNote: "An absolute ruler holds all power and 'brooks no opposition'. A ruler who shares power and accepts opposition, a democrat (D), is the closest opposite. The key's C (a benevolent leader) is the opposite of a despotic ruler (A), which is also defensible, so both C and D are marked right." }),
    q(OPP + "The response to the advertisement has been PHENOMENAL.", ["spiritual", "frightening", "unimpressive", "catastrophic"], C, "Phenomenal means remarkably great; unimpressive is its opposite."),
    q(OPP + "My father lived a SPARTAN life before his death.", ["extravagant", "peaceful", "quiet", "luxurious"], D, "A Spartan life is simple and without comfort; a luxurious life is full of comfort."),
    q(OPP + "Bola's parents went through an ACRIMONIOUS divorce.", ["a bitter", "an acrid", "a sour", "a peaceful"], D, "Acrimonious means bitter and angry; the opposite is peaceful."),
    q(OPP + "Lliya's account of the incident is APPALLING.", ["tasking", "fascinating", "horrifying", "ridiculous"], B, "Appalling means shocking and horrifying; fascinating is its pleasant opposite."),
    q(OPP + "She ENCAPSULATED her view of the nature of life in a poem.", ["summed up", "explained", "expatiated on", "reflected"], C, "To encapsulate is to express briefly; to expatiate on is to speak or write at length."),
    q(OPP + "We were held SPELLBOUND by his eloquence.", ["unimpressed", "freed", "deceived", "unenlightened"], A, "Spellbound means held fascinated; unimpressed is the opposite."),
    q(NEAR + "We were at a loss to understand why Oli should RETRACT his statement before the judge.", ["assert", "repeat", "withdraw", "reiterate"], C, "To retract a statement is to withdraw it."),
    q(NEAR + "The workers hope to appear before the ARBITRATION panel to resolve the lingering dispute.", ["trial", "legislative", "investigative", "reconciliatory"], A, "Arbitration is a hearing in which a neutral panel hears both sides and gives a binding decision, much like a trial."),
    q(NEAR + "He went to the polls in defiance of sound advice and recorded an ABYSMAL performance.", ["surprisingly good", "disappointingly bad", "mediocre", "landslide"], B, "Abysmal means extremely bad."),
    q(NEAR + "He was not able to WITHSTAND the attack from his immediate family.", ["survive", "overcome", "match", "resist"], D, "To withstand an attack is to resist it."),
    q(NEAR + "Your effort to bring peace between us is futile because you are BIASED.", ["convinced", "clever", "prejudiced", "worried"], C, "Biased means unfairly favouring one side, that is, prejudiced."),
    q(NEAR + "Our front door is always kept AJAR.", ["locked", "sealed", "half-closed", "permanently open"], C, "A door that is ajar is slightly open, not fully shut: half-closed."),
    q(NEAR + "His embroidery was an EXACTING task for the tailor.", ["an unwarranted", "an exciting", "a demanding", "a disturbing"], C, "Exacting means demanding great care and effort. (The paper prints 'exciting' in the question, a misprint for 'exacting'.)"),
    q(NEAR + "The student's REMONSTRANCES were rebuffed by the authority.", ["protest", "suggestions", "compliants", "regrets"], A, "A remonstrance is a forceful protest."),
    q(NEAR + "I had to make my way through the THRONG of people in the church.", ["group", "crowd", "gathering", "regrets"], B, "A throng is a large, dense crowd."),
    q(NEAR + "The man's wife has her MISGIVINGS about him.", ["fears for", "distrust of", "hatred for", "love for"], B, "Misgivings are doubts or feelings of distrust."),
    q(NEAR + "Violent crime is only one of the MALADIES afflicting modern society.", ["damages", "illnesses", "wounds", "crises"], B, "A malady is an illness; here used figuratively of society's ills."),
    q(NEAR + "Tade has an AQUILINE nose.", ["a large and curved nose", "a wide and straight nose", "a big and pointed noses", "a small and attractive nose"], A, "Aquiline means like an eagle's beak: hooked or curved."),
    q(NEAR + "Everyone was talking about the CAMARADERIES in the club.", ["companionship", "quarrelsomeness", "commissioning", "disunity"], A, "Camaraderie is friendly companionship among people."),
    q(NEAR + "'You're IMPOSSIBLE', she said to me.", ["unreasonable", "unforgiving", "daft", "strong"], A, "Calling a person impossible means they are very unreasonable and hard to deal with."),
    q(NEAR + "I was being directed by my SIXTH SENSE all through the ordeal.", ["intelligence", "judgement", "intuition", "imagination"], C, "The sixth sense is intuition: knowing something without the five senses or reasoning."),
    q(GAP + "They _____ wet if they had gone out in the rain.", ["would get", "would have got", "will have got", "had got"], B, "A past unreal condition (if + had + past participle) takes 'would have' + past participle in the main clause."),
    q(GAP + "The students are still _____ in the dark regarding the principal's decision.", ["very so", "much too", "very much", "much so"], C, "'Very much in the dark' is the standard way to say completely uninformed."),
    q(GAP + "When I came in, I _____.", ["laid on the floor", "lie on the floor", "lain on the floor", "lay on the floor"], D, "Lie (rest flat) has past tense lay; laid is the past of lay (put something down), which needs an object."),
    q(GAP + "Either the teacher or the students _____ to blame.", ["is", "are", "has being", "are being"], B, "With either...or, the verb agrees with the nearer subject: 'the students are'."),
    q(GAP + "I will pay my debt _____.", ["instalmentally", "by instalmentally", "in instalments", "in instalmentally"], C, "The standard phrase is 'pay in instalments'; 'instalmentally' is not standard English."),
    q(GAP + "You should anticipate and prepare for changes _____ in your office.", ["that has taken place", "which takes place", "taking place", "that would take place"], D, "Anticipate and prepare point to the future, and 'changes' is plural, so 'that would take place' fits."),
    q(GAP + "The scholar examined _____ of the subject.", ["three a part analysis", "a part-three analysis", "a three-part analysis", "a three part analysis"], D, "A number + noun used before a noun forms a compound adjective in the singular: a three-part analysis.", { alsoAccept: [C], keyVerdict: 'multiple', keyAnswer: 'D', answerNote: "C and D are the same phrase; the only difference is the hyphen. Standard British usage hyphenates a compound adjective before a noun (a three-part analysis), so C is also correct, and D is the key's answer." }),
    q(GAP + "The litigants finally opted _____ settlement.", ["by and out of court", "in an out-of-court", "to an out of court", "for an out-of-court"], D, "One opts for something, and 'out-of-court' is hyphenated before the noun."),
    q(GAP + "She refrained _____ smoking.", ["at", "off", "from", "in"], C, "Refrain takes 'from': refrain from doing something."),
    q(GAP + "Birds whistle while bears _____.", ["gibber", "purr", "growl", "bellow"], C, "Bears growl; cats purr, monkeys gibber, and bulls bellow."),
    q(GAP + "I am not surprised that Zali had a road accident, he was always driving too fast, _____?", ["isn't he", "wasn't he", "didn't he", "did he"], B, "A positive statement with 'was' takes the negative tag 'wasn't he'."),
    q(GAP + "Oduma had _____ enough money to pay the fines so he went to jail for distributing libellous _____.", ["no/brochures", "not/circulars", "no/publications", "not/pamphlets"], D, "Before 'enough' we use 'not' (not enough money), never 'no'. Libellous pamphlets fits the sense.", { alsoAccept: [B], keyVerdict: 'corrected', keyAnswer: 'C', answerNote: "'No enough money' is not correct English; it must be 'not enough money', which rules out A and C (the key's answer). B (circulars) and D (pamphlets) both fit 'distributing libellous ...', so both are marked right." }),
    q(GAP + "The principal said he _____ so many visitors that day that he _____ exhausted.", ["had been having/felt", "has been having/feels", "was having/feels", "is having/felt"], A, "Reported speech in the past: the earlier action goes into the past perfect continuous, and 'felt' keeps the past."),
    q(GAP + "His mother always reprimands him for being a _____ reader of cheap novels.", ["vicious", "veracious", "vivacious", "voracious"], D, "A voracious reader reads very eagerly and a great deal."),
    q(GAP + "Femi has been _____ behind in classwork.", ["lacking", "lagging", "larking", "lurking"], B, "To lag behind is to fall behind others."),
    q(GAP + "Judging _____ his face, he is not guilty.", ["at", "through", "with", "by"], D, "The fixed phrase is 'judging by' (or 'judging from')."),
    q(GAP + "What were the _____ served in the restaurant?", ["spices", "desserts", "diets", "condiments"], B, "Desserts are sweet dishes served at the end of a meal; the question is about dishes served."),
    q(GAP + "She _____ her hair _____ in the room before we left.", ["smoothened/off", "Smoothened/on", "smoothened/up", "smoothened/down"], D, "The phrasal verb is 'smooth down' (one's hair, clothes): to press flat and neat."),
    q(GAP + "This is a village where _____ knows _____.", ["everyone/everyone else", "anyone/anyone", "every person/themselves", "someone/someone else"], A, "'Everyone knows everyone else' describes a close community where all are acquainted."),
    q(GAP + "'Did you say that you saw him _____ the road yesterday?", ["crossed", "cross", "to be crossing", "crosses"], B, "After see + object we use the bare infinitive (or -ing): saw him cross."),
    q(SAMEV + "kEY", ["sit", "beat", "seat", "tread"], C, "The ey in key is the long vowel /iː/, as in seat and beat.", { alsoAccept: [B], keyVerdict: 'multiple', keyAnswer: 'C', answerNote: "Both beat (B) and seat (C) have the long /iː/ sound of key, so both are correct. Sit has short /ɪ/ and tread has /e/." }),
    q(SAMEV + "tAUght", ["law", "aunt", "count", "plateau"], A, "The au in taught is /ɔː/, as in law."),
    q(SAMEV + "dUtch", ["lottery", "love", "loud", "lurch"], B, "The u in Dutch is /ʌ/, as the o in love."),
    q(CONS + "boTH", ["bother", "thaw", "the", "there"], B, "The th in both is voiceless /θ/, as in thaw; bother, the and there have voiced /ð/."),
    q(CONS + "bouQUet", ["bucket", "banquet", "liquid", "squeeze"], A, "The qu in bouquet is pronounced /k/ (a French word), like the ck in bucket; the others have /kw/."),
    q(CONS + "houSes", ["rice", "rise", "curse", "course"], B, "The s in houses is /z/, as in rise; rice, curse and course have /s/."),
    q("Choose the option that rhymes with the given word: Say", ["treason", "weigh", "fright", "saw"], B, "Say and weigh both end in /eɪ/."),
    q("Choose the option that rhymes with the given word: Knew", ["tool", "dawn", "night", "queue"], D, "Knew /njuː/ and queue /kjuː/ both end in /uː/."),
    q("Choose the option that rhymes with the given word: Toy", ["torn", "take", "foil", "tour"], C, "Foil has the same /ɔɪ/ vowel as toy; it is the only option with that sound."),
    q(STRESSOF + "Comfortable", ["COMfortable", "comFORtable", "comfortaBLE", "comforTAble"], A, "Comfortable is stressed on the first syllable: COM-for-ta-ble."),
    q(STRESSOF + "Incapacitate", ["inCApacitate", "incaPAcitate", "INcapacitate", "incapaciTATE"], B, "Incapacitate is stressed on the third syllable: in-ca-PA-ci-tate."),
    q(STRESSOF + "Encouragement", ["Encouragement", "enCOUragement", "encouRAgement", "encourageMENT"], B, "Encouragement is stressed on the second syllable: en-COU-rage-ment."),
    q(EMPH + "THEIR children speak better French than English.", ["Do their husbands speak better French than English?", "What language do their children speak better than English?", "Do their children speak better French than English?", "Whose children speak better French than English?"], D, "Stress on THEIR answers a question about whose children."),
    q(EMPH + "They RAN to the playground.", ["Where did they run to?", "Did they walk to the playground?", "Who ran to the playground?", "Did they run from the playground?"], B, "Stress on RAN corrects the manner of movement, answering 'Did they walk?'"),
    q(EMPH + "Timi BOUGHT a new car.", ["Did Timi hire a new car?", "Does Timi deal in cars?", "Has Timi acquired a new car?", "Does Timi have a new car?"], A, "Stress on BOUGHT contrasts buying with another way of getting the car, such as hiring."),
  ];

  QUESTION_BANK.english = QUESTION_BANK.english.concat(passages, flat);
})();
