/**
 * JAMB/UTME 2014 — USE OF ENGLISH
 * From the 2014 question paper; answers from the JAMB/UTME English Language
 * answer key 2001–2020, each checked against the paper. Where the key in
 * circulation is wrong (often a printing error) the question carries
 * keyVerdict + keyAnswer + answerNote (see english-2007.js for the scheme).
 *
 * Loaded after questions.js and before app.js.
 */
(function () {
  const Y = 2014;
  const SRC = 'JAMB UTME 2014';
  const READ = 'Read the passage carefully and answer the questions that follow.';

  const PT0 = "Political change and social transformation in the form of revolutions have radically altered the course of human civilization and history. Today, the world is witnessing political and social changes arising from the desire of people all over the globe for greater freedom and a voice in the way they are governed and a better standard of living. Part of these struggles and processes have become more pronounced in the Third World since the end of East-West Cold War in the late 1980s, and the face of the challenges being posed by the on-going process of globalization.\n\nWhile political and social changes may appear to be distinct phenomena, they are analytically inseparable. Political and social changes refer to alteration or transformations in human behaviour, norms and politico-social institutions. Such changes are often a collective response to the need to change, or as a tacit recognition of a shift in the prevalent power relations in the society. Therefore, the coming to power of new sets of rulers, or the establishment of new structures and processes of governance broadly typifies socio-political changes.\n\nIt is important to note that change can either be positive or negative. In most cases, political and social changes are caused by certain factors or reasons. These push people to collectively organize themselves to struggle for a change in the existing power relations. Another reason is to capture political power, in the hope of making life better for the generality of the people. If politics is defined as who gets what, when and how; it then implies that political change refers to an alteration in the form of power, and the identity of the group or class which controls and wields state power.";
  const PT1 = "Like all reptiles, snakes are cold-blooded, or more correctly, ectodermic- they cannot produce their own body heat; instead, they rely on the sun to heat their bodies. Because they do not rely on energy from food to generate body heat; snakes can survive on an extremely meager diet. Some wait for months between successive meals and a few survive by eating a large meal just once or twice a year. When they do eat, snakes swallow their prey whole rather than biting off small pieces. Many snakes have specialized jaws that enable them to swallow animals that are far larger than their own heads. Although uncommon, some snakes, such as the African rock python, have been observed eating animals as large as an antelope or a small cow.\n\nWith over two thousand five hundred species belonging to more than ten families, snakes are large and successful group. They owe much of this success to their versatility- snakes occupy habitat ranging from underground burrows to the top of the tree, to ocean depths as great as one hundred and fifty meters. They are found on every continent except Antarctica, and although they are most abundant in tropical areas, many survive in regions marked by extreme cold. The only places without snakes are parts of the polar regions and isolated islands, such as the republic of Ireland and New-Zealand as opposed to places in Nigeria like Plateau and Gombe states in the northern parts where there is a large population of snakes.";
  const PT2 = "Setting up a newspaper involves a lot of preparations. The ___(11)___ has to employ a lot of people. Other people working with him are cartographers, editors, typesetters, readers, who work in various ways to produce the text of the newspaper, ___(12)___ who go out and collect stories and items of news, and ___(13)___, who specialize in one kind of topic. Another important person who works closely with the editor-in-chief is the ___(14)___, who has to choose the most important stories ___(15)___ go through stories sent to make necessary adjustments. The Editor-in-chief could determine for instance, whether a particular journalist should write articles daily or weekly in a particular column. Such a journalist is known as ___(16)___. The editorials of the newspaper will be coordinated by ___(17)___. The publisher could decide to establish ___(18)___ which would be on sale weekly, fortnightly or monthly ___(19)___ the eye catching, screaming headlines and captions of newspapers on sale everyday from the ___(20)___.";

  const P1Q = [
      { question: "Which of the following is true according to the passage?", options: ["Change is inimitable", "Change is inestimable", "Change is invaluable", "Change is inevitable"], answer: 3, explanation: "The passage shows the whole world going through political and social change, driven by people's desire for freedom and better living, so change cannot be avoided: it is inevitable.", keyVerdict: 'corrected', keyAnswer: 'A', answerNote: "'Inimitable' means impossible to copy, which the passage never suggests about change. The passage describes change happening all over the globe and being caused by forces people cannot ignore, so 'inevitable' (D) is the true statement. The key's A is probably a printing error." },
      { question: "It can be deduced from the passage that political and social changes are", options: ["intertwined", "antithetical", "independent", "repulsive"], answer: 0, explanation: "The writer says they 'may appear to be distinct phenomena' but 'are analytically inseparable', i.e. intertwined.", keyVerdict: 'corrected', keyAnswer: 'B', answerNote: "'Antithetical' means directly opposed, but the passage says political and social changes are 'analytically inseparable' and treats them together throughout. Things that cannot be separated are intertwined, so A is correct." },
      { question: "A suitable title for this passage is", options: ["Reasons for political change", "The struggle for political power", "Elements of politics", "Social change and political empowerment"], answer: 2, explanation: "The passage explains basic ideas of politics (what political and social change are, why they happen, and a definition of politics), so 'Elements of politics' covers it; A and B fit only parts of the last paragraph." },
      { question: "The word 'alteration', as used in the passage, means", options: ["multiplication", "recognition", "modification", "complication"], answer: 2, explanation: "An alteration is a change or modification; the passage pairs it with 'transformations'." },
  ];
  const P2Q = [
      { question: "It can be inferred from the passage that snakes are", options: ["heterogeneous creatures", "voracious cow eaters", "great insect eaters", "homogeneous reptiles"], answer: 0, explanation: "With 'over two thousand five hundred species belonging to more than ten families', snakes are a very varied (heterogeneous) group." },
      { question: "The most notable thing about snakes, according to the passage, is that they", options: ["abound in Gombe and Plateau state", "are versatile in reproduction", "eat big but seldomly", "exist in families"], answer: 2, explanation: "Paragraph 1 dwells on their feeding: they survive on a meagre diet, wait months between meals and swallow prey larger than their heads." },
      { question: "Which of the following is true according to the passage?", options: ["Snakes are not in the polar regions", "Snakes are endemic on every continent", "There are countless number of snakes in the republic of Ireland", "Snakes are seldom seen at the Antarctica"], answer: 0, explanation: "'The only places without snakes are parts of the polar regions and isolated islands.'" },
      { question: "It can be deduced from the passage that snakes have", options: ["no external auditory organ", "visible internal locomotive organs", "no visual sense of measurement", "large appetite for antelopes"], answer: 1, explanation: "The key gives B, but none of the options can really be deduced from the passage, which says nothing about snakes' ears, organs of movement or sight.", keyVerdict: 'none', keyAnswer: 'B', answerNote: "The passage talks about body heat, diet, jaws, species and habitat, but nothing about ears, organs of movement or eyesight, and it says eating antelopes is 'uncommon'. No option follows from the passage, so B is kept only because it is the key's answer." },
      { question: "A suitable title for this passage is", options: ["Feeding habits of snakes", "Some characteristics of snakes", "Snakes as legless, cold-blooded reptiles", "Species of snakes in Nigeria and other lands"], answer: 1, explanation: "The passage covers body heat, feeding, jaws, species and habitat: several characteristics of snakes. A covers only paragraph 1." },
  ];
  const CLOZE = [
      { question: "Gap 11: The _____ has to employ a lot of people.", options: ["processor", "lithographer", "proprietor", "sub-editor"], answer: 2, explanation: "The proprietor is the owner of the newspaper, the one who employs the staff." },
      { question: "Gap 12: ...to produce the text of the newspaper, _____ who go out and collect stories and items of news", options: ["agents", "reporters", "analysts", "vendors"], answer: 1, explanation: "Reporters go out to gather news." },
      { question: "Gap 13: ...and _____, who specialize in one kind of topic.", options: ["correspondents", "distributors", "listeners", "newscasters"], answer: 0, explanation: "Correspondents report on one subject or area, e.g. a sports or political correspondent." },
      { question: "Gap 14: Another important person who works closely with the editor-in-chief is the _____, who has to choose the most important stories", options: ["announcer", "news editor", "proofreader", "reporter"], answer: 1, explanation: "The news editor decides which stories are most important." },
      { question: "Gap 15: ...the most important stories _____ go through stories sent to make necessary adjustments.", options: ["sub-editors", "writers", "agents", "producers"], answer: 0, explanation: "Sub-editors check and correct stories before publication." },
      { question: "Gap 16: Such a journalist is known as _____.", options: ["a freelancer", "a composer", "a columnist", "an essayist"], answer: 2, explanation: "A journalist who writes regularly in a particular column is a columnist." },
      { question: "Gap 17: The editorials of the newspaper will be coordinated by _____.", options: ["a guild of researchers", "an editorial board", "all readers", "an agent"], answer: 1, explanation: "Editorials are the paper's official opinion, decided by the editorial board." },
      { question: "Gap 18: The publisher could decide to establish _____ which would be on sale weekly, fortnightly or monthly", options: ["an article", "column", "a magazine", "a gazetteer"], answer: 2, explanation: "A publication sold weekly, fortnightly or monthly is a magazine." },
      { question: "Gap 19: ...on sale weekly, fortnightly or monthly _____ the eye catching, screaming headlines...", options: ["a contrast from", "a contrast in", "a contrast to", "a contrast for"], answer: 2, explanation: "The fixed expression is 'in contrast to' / 'a contrast to'." },
      { question: "Gap 20: ...newspapers on sale everyday from the _____.", options: ["readers", "distributors", "pressmen", "salesmen"], answer: 3, explanation: "Newspapers are bought from salesmen (vendors) on the street." },
  ];

  const passages = [
    { passageId: 'eng-2014-p1', passageTitle: 'JAMB 2014 — Passage I', year: Y, instruction: READ, passage: PT0, questions: P1Q },
    { passageId: 'eng-2014-p2', passageTitle: 'JAMB 2014 — Passage II', year: Y, instruction: READ, passage: PT1, questions: P2Q },
    { passageId: 'eng-2014-p3', passageTitle: 'JAMB 2014 — Passage III (cloze)', year: Y, instruction: 'The passage has gaps numbered 11 to 20. Choose the most appropriate option for each gap.', passage: PT2, questions: CLOZE },
  ];

  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const GAP = 'Choose the option that best completes the gap(s): ';
  const VOWEL = 'Choose the option that has a DIFFERENT vowel sound from the others.';
  const SAMEV = 'Choose the option that has the same vowel sound as the letter(s) in capitals: ';
  const CONS = 'Choose the option that has the same consonant sound as the letter(s) in capitals: ';
  const DIFFC = 'Choose the option that has a DIFFERENT consonant sound from the others.';
  const DIFF = 'Choose the option that has a DIFFERENT stress pattern from the others.';
  const SAMES = 'Choose the option that has the same stress pattern as the given word (stressed syllable in capitals): ';
  const STRESSOF = 'Choose the appropriate stress pattern for the word (the stressed syllable is in capitals): ';
  const FIRST = 'Choose the option that has the stress on the FIRST syllable.';
  const NEAR = 'Choose the option NEAREST in meaning to the word(s) in capitals: ';
  const MEANS = 'Select the option that best explains the information conveyed in the sentence: ';
  const EMPH = 'The word in capitals has emphatic stress. Choose the option that best fits the expression: ';
  const OPP = 'Choose the option OPPOSITE in meaning to the word(s) in capitals: ';

  const flat = [
    q(MEANS + "The minister considered the ministry's budget to a drop in the ocean in view of the number of projects in the pipeline.", ["The amount available may be inadequate for projected expenditure", "The minister may be dropped for failing to complete a number of projects", "The money approved cannot compete the pipeline project across the ocean", "The pipeline project across the ocean will be abandoned unless budgetary allocation improves"], A, "A drop in the ocean is an amount far too small for what is needed; 'projects in the pipeline' are planned projects, not an actual pipeline."),
    q(MEANS + "The police are looking for the woman who framed her children out to her neighbours.", ["The woman and her children are in the habit of working in neighbour's farm and the police are not well disposed to this", "The police may arrest the woman for allowing her neighbours to take care of her children", "The woman may be arrested for allowing her children to be a nuisance to her neighbours", "The police wanted remarked for allowing her children to destroy her neighbour's crops"], B, "'Framed' is a misprint for 'farmed': to farm out children is to hand them over to others to look after."),
    q(MEANS + "Jummai's father remarked that pigs would fly before she passed.", ["It would be possible to pass only if she worked harder", "It would never be possible for her to pass", "He would have to bribe her teachers to enable her to pass", "She would have to cheat in order to pass"], B, "'Pigs might fly' is said of something that will never happen. (The paper misprints the name as 'Jurrmai'.)"),
    q(MEANS + "The president said that he found himself between a rock and a hard place when the press said that he had resigned.", ["He dreamt that he was abandoned", "He thought that hard places were unsafe", "He had a hard decision to make", "Hard places are dangerous for the president"], C, "Between a rock and a hard place means facing a difficult choice between two bad options."),
    q(MEANS + "Kunana is like a bear with a sore head.", ["He is a bully", "He is grumpy", "He is ugly", "He is quiet"], B, "Like a bear with a sore head means bad-tempered and irritable."),
    q(MEANS + "Olu gave his brother a bumpy ride.", ["Olu's brother rode on Olu's back to success", "Olu took his brother on a bumpy road", "Olu gave his brother a difficult time", "Olu gave his brother a ride in his car"], C, "To give someone a bumpy ride is to make things difficult for them."),
    q(MEANS + "Adeola doesn't have to go to the farm today.", ["Adeola may go to the farm today if he so wishes", "Adeola ought not to have gone to the farm today", "Adeola must not go to the farm today", "Adeola should not go to the farm today"], A, "'Doesn't have to' means there is no obligation: he is free to go or not to go.", { keyVerdict: 'corrected', keyAnswer: 'D', answerNote: "'Doesn't have to' removes the obligation; it does not forbid. 'Should not go' (D) and 'must not go' (C) tell Adeola not to go, which changes the meaning. A keeps the choice open, so A is correct." }),
    q(MEANS + "My boss asked me to take my eyes off the ball.", ["I should stop paying attention to what is most important", "I should be focused when I am about stay off football", "I should stay off football after sustaining an injury", "I should be focused when playing football"], A, "To keep your eye on the ball is to stay focused on what matters, so taking your eyes off the ball means no longer attending to what is most important."),
    q(MEANS + "The robber was hedged in by the people.", ["The robber was surrounded by the people", "The robber was killed by the people", "The robber was exposed by the people", "The robber was caught by the people"], A, "To be hedged in is to be surrounded and hemmed in."),
    q(MEANS + "Many workers are not happy because they live a hand-to-mouth life.", ["They work hard with their hands", "They are voracious and avaricious", "They are barely surviving", "They have rejected the use of spoons"], C, "A hand-to-mouth life is one where you earn only just enough to survive."),
    q(OPP + "Prolonged strike action DEBILITATED the industry.", ["invigorated", "isolated", "weakened", "destroyed"], A, "Debilitated means weakened; invigorated means strengthened."),
    q(OPP + "One of the students bought a PLAGIARIZED copy of the book.", ["a used", "an original", "a revised", "an annotated"], B, "A plagiarized (copied) work is the opposite of an original."),
    q(OPP + "The young girl was TAKEN ABACK by her father's gift of a car.", ["shocked", "unmoved", "surprised", "nonplussed"], B, "Taken aback means surprised; unmoved means not affected."),
    q(OPP + "Musa is a gifted but ERRATIC player.", ["strong", "regular", "unpredictable", "unstable"], B, "Erratic means inconsistent; regular means consistent."),
    q(OPP + "The lamp shades were TRANSLUCENT.", ["opaque", "interested", "luminous", "transparent"], A, "Translucent lets light through; opaque lets no light through."),
    q(OPP + "My niece has an UNQUENCHABLE thirst for adventure stories.", ["a spurious", "an illegitimate", "a reduced", "an inextinguishable"], C, "Unquenchable means impossible to satisfy or reduce; the opposite is a reduced thirst."),
    q(OPP + "Some of my neighbours have an ANTIPATHY to dogs.", ["enmity towards", "affection for", "acronym for", "alarm for"], B, "Antipathy is strong dislike; affection is liking."),
    q(OPP + "The dressmaker UNPICKED the seam of the shirt.", ["threaded", "sewed up", "picked up", "tore for"], B, "To unpick a seam is to undo its stitches; to sew it up is the reverse."),
    q(OPP + "The testimony of the witness was VAGUE.", ["disturbing", "true", "ambiguous", "clear"], D, "Vague means unclear; the opposite is clear."),
    q(OPP + "As a student, Isa tried COMMUNAL living for a few years.", ["collective", "general", "shared", "private"], D, "Communal means shared by a group; the opposite is private."),
    q(NEAR + "The chairman admires INCESSANT meetings.", ["unusual", "planned", "constant", "irregular"], C, "Incessant means never stopping, i.e. constant."),
    q(NEAR + "Today's weather is FAVOURABLE for a game of tennis.", ["impartial", "abnormal", "encouraging", "disapproving"], C, "Favourable weather is suitable, encouraging weather."),
    q(NEAR + "The candidates looked AGHAST at the first reading of the questions.", ["fulfilled", "dismayed", "satisfied", "relaxed"], B, "Aghast means filled with shock and dismay."),
    q(NEAR + "Joke gave Muhammed a JAUNTY smile.", ["a discouraging", "an inviting", "a frightful", "a cheerful"], D, "Jaunty means lively and cheerful."),
    q(NEAR + "The first round of the tournament was a DODDLE.", ["easy", "balanced", "dodgy", "exasperating"], A, "A doddle is something very easy."),
    q(NEAR + "The lazy man cast a LUSTFUL glance at his neighbour's wife.", ["hateful", "quick", "covetous", "envious"], C, "A lustful glance shows desire for what belongs to someone else: covetous."),
    q(NEAR + "They accused him of FOMENTING political unrest.", ["inciting", "discouraging", "preventing", "guiding"], A, "To foment unrest is to stir it up, i.e. incite it."),
    q(NEAR + "You can LEARN a great deal just from watching other players.", ["invent", "accumulate", "allow", "discover"], D, "To learn here is to find out, i.e. discover."),
    q(NEAR + "All the researchers were asked to GATHER information on the new viral infection.", ["collect", "disseminate", "distort", "give"], A, "To gather information is to collect it."),
    q(NEAR + "The dispute between the two countries has resulted in the SEVERING of diplomatic relations.", ["breaking", "securing", "swapping", "strengthening"], A, "Severing relations means breaking them off."),
    q(GAP + "The House and The Senate will _____ at noon next Wednesday to hear address by the president.", ["convene", "adjourn", "rise", "collude"], A, "To convene is to come together for a meeting; adjourn and rise mean to end a sitting."),
    q(GAP + "At the _____ of the century, many ways of doing things were introduced.", ["turn", "event", "birth", "sight"], A, "The fixed expression is 'the turn of the century', the time when one century ends and the next begins.", { keyVerdict: 'corrected', keyAnswer: 'C', answerNote: "English says 'at the turn of the century', not 'at the birth of the century'. The key's C is not a standard expression, so A is correct." }),
    q(GAP + "You may have the pencil, but you can't have the ballpoint _____.", ["either", "furthermore", "also", "as well"], D, "You may have one but not both: 'you can't have the ballpoint as well' (too). 'Either' adds a second refusal, which clashes with 'you may have the pencil'."),
    q(GAP + "The president said that the country was not out of the _____ yet.", ["forest", "fog", "water", "wood"], D, "To be out of the wood(s) is to be free of danger or difficulty."),
    q(GAP + "He went to the restaurant to enjoy the special _____.", ["suite", "cuisine", "a la carte", "chef"], B, "Cuisine is a style of cooking or food; a restaurant's special cuisine is its special food."),
    q(GAP + "The invigilator _____ to know how long the examination _____ going on.", ["wanted/has been", "wants/had been", "wants/have been", "wanted/had been"], D, "Past 'wanted' needs past perfect 'had been' in the reported part."),
    q(GAP + "The guard spent all the night pacing _____.", ["from and to", "fro and to", "to and from", "to and fro"], D, "To pace to and fro is to walk backwards and forwards."),
    q(GAP + "The woman refused to testify _____ her husband.", ["in", "at", "against", "from"], C, "One testifies against (or for) someone."),
    q(GAP + "Abike must have found the very interesting movies quite _____.", ["absolving", "absorbing", "nauseating", "perverting"], B, "Very interesting films hold your attention: they are absorbing.", { keyVerdict: 'corrected', keyAnswer: 'C', answerNote: "The films are described as 'very interesting', so she would find them absorbing (B), not nauseating (sickening, disgusting). The key's C contradicts the sentence." }),
    q(GAP + "The words _____ divided between the end of one line.", ["have been", "have being", "has been", "has being"], A, "Plural 'words' takes 'have', and the passive needs the past participle 'been'."),
    q(GAP + "Those _____ are very beautiful.", ["flowers of her", "flowers of her's", "our flower", "flowers of ours"], D, "The double possessive uses a possessive pronoun: flowers of ours (of hers). 'Her's' is never correct."),
    q(GAP + "Cooking has never been Jumoke's _____.", ["recital", "purview", "style", "forte"], D, "A forte is something a person is especially good at."),
    q(GAP + "When the strike is over, there will probably be an increase in wages and a _____ increase in prices.", ["sporadic", "concordant", "concurrent", "chronic"], C, "Concurrent means happening at the same time."),
    q(GAP + "My mother was _____ annoyed with me for coming late.", ["very", "neither", "hotly", "just"], A, "'Very' intensifies the adjective annoyed."),
    q(GAP + "The chairman is too much _____ an idealist for this government.", ["from", "about", "of", "with"], C, "The expression is 'too much of a/an ...'."),
    q(GAP + "The clock _____ 12 o'clock two hours ago.", ["strikes", "strike", "struck", "striking"], C, "'Two hours ago' needs the past tense: struck."),
    q(GAP + "What is the jury's _____ the matter.", ["verdict on", "verdict from", "verdict at", "verdict with"], A, "One gives a verdict on a matter."),
    q(GAP + "The unconscious man was _____ after receiving first aid.", ["reawakened", "reformed", "restored", "revived"], D, "An unconscious person is revived (brought back to consciousness)."),
    q(GAP + "The laughter _____ his face for a moment.", ["improved", "controlled", "animated"], C, "Laughter animated (brought life to) his face. (The fourth option is illegible in the scan.)"),
    q(GAP + "She traced her family history _____ matrilineal descent.", ["in", "by", "with", "at"], B, "One traces a family history by (through) a line of descent."),
    q(SAMEV + "cOOl", ["full", "luke", "look", "should"], B, "The oo in cool is long /uː/, as the u in luke. Full, look and should have short /ʊ/."),
    q(SAMEV + "odOUR", ["flow", "sugar", "hold", "floor"], B, "The unstressed -our of odour is the weak vowel /ə/, like the -ar of sugar. Flow and hold have /əʊ/, floor has /ɔː/."),
    q(SAMEV + "pAlm", ["ranch", "florid", "lunch", "plait"], A, "The a in palm is /ɑː/, as in ranch in British English. Plait has /æ/, florid /ɒ/, lunch /ʌ/."),
    q(CONS + "viSion", ["instruction", "mansion", "nation", "enclosure"], D, "The s in vision is /ʒ/, like the s in enclosure. The others have /ʃ/."),
    q(CONS + "GNash", ["forge", "new", "king", "ring"], B, "The gn of gnash is /n/ (the g is silent), as in new. King and ring end in /ŋ/; forge has /dʒ/."),
    q(CONS + "epitaPH", ["pseudo", "fan", "paper", "pneumonia"], B, "The ph of epitaph is /f/, as in fan. The p in pseudo and pneumonia is silent."),
    q(SAMEV + "evER", ["favour", "fever", "never", "heavier"], C, "The -er of ever is the weak vowel /ə/; never rhymes with ever, so C is the key's answer, but favour, fever and heavier also end in /ə/.", { alsoAccept: [A, B, D], keyVerdict: 'multiple', keyAnswer: 'C', answerNote: "The underlined -er in ever is the weak vowel /ə/. All four options end in that same /ə/ (favOUR, fevER, nevER, heaviER), so every option fits. The key's C (never) is the closest match because it rhymes fully with ever." }),
    q(SAMEV + "kEEp", ["reap", "seethe", "threat", "dead"], A, "The ee in keep is long /iː/, as the ea in reap. Threat and dead have short /e/.", { alsoAccept: [B], keyVerdict: 'multiple', keyAnswer: 'A', answerNote: "Seethe (B) is pronounced /siːð/, with the same long /iː/ as keep and reap, so B is also right. Only threat and dead (short /e/) are wrong." }),
    q("Choose the option that has the same sounds as the letters in capitals: tAX", ["box", "lacks", "back", "ask"], B, "The underlined ax in tax is /æks/, exactly the -acks of lacks. Back has /æ/ but no /ks/; ask has /ɑːs/ in British English."),
    q(STRESSOF + "valedictory", ["valeDICtory", "valedicTORY", "VAledictory", "vaLEdictory"], A, "Valedictory is stressed on the third syllable: va-le-DIC-to-ry."),
    q(STRESSOF + "congratulation", ["congraTUlation", "congratuLAtion", "CONgratulation", "conGRAtulation"], B, "Congratulation is stressed on -la-: con-gra-tu-LA-tion."),
    q(STRESSOF + "conspiracy", ["conspiRAcy", "conspiraCY", "consPIracy", "conSPIracy"], D, "Conspiracy is stressed on the second syllable: con-SPI-ra-cy."),
    q(EMPH + "My mother brought a BICYCLE yesterday.", ["What did your mother buy yesterday?", "Whose mother bought a bicycle yesterday?", "Did my mother steal a bicycle yesterday?", "When did my mother buy a bicycle?"], A, "Stress on BICYCLE answers 'what?': what did she buy. ('Brought' in the sentence is a misprint for 'bought'.)"),
    q(EMPH + "AMINA went to Abuja by air.", ["Is Amina going to Abuja by air?", "Who went to Abuja by air?", "Did Amina go to Abuja by road?", "Did Amina go to Jos by air?"], B, "Stress on AMINA answers 'who?'."),
    q(EMPH + "Musa is STAYING in Enugu.", ["Is Musa passing through Enugu?", "Is Musa staying on the outskirt of Enugu?", "Is Audu staying in Enugu?", "Was Musa staying in Enugu?"], A, "Stress on STAYING contrasts it with passing through."),
  ];

  QUESTION_BANK.english = QUESTION_BANK.english.concat(passages, flat);
})();
