/**
 * JAMB/UTME 2004 — USE OF ENGLISH
 * From the 2004 question paper; answers from the JAMB/UTME English Language
 * answer key 2001–2020, each checked against the paper. Where the key in
 * circulation is wrong (often a printing error) the question carries
 * keyVerdict + keyAnswer + answerNote (see english-2007.js for the scheme).
 *
 * Loaded after questions.js and before app.js.
 */
(function () {
  const Y = 2004;
  const SRC = 'JAMB UTME 2004';
  const READ = 'Read the passage carefully and answer the questions that follow.';

  const PT0 = "If, once in a lifetime, you see a blue moon, don't think your eyes are playing tricks on you. It's caused by dust in our upper atmosphere; ice crystals are what make you see rings round the moon.\n\nOver the centuries, magical powers have been attributed to the moon. It has been said to bring on lunacy, affect the growth of plants, eyes of cats, spots of panthers, functions of women and activities of ghosts. France once had a law against cutting timber except during a waning moon. The moon, and to a lesser degree the sun, does cause the ocean tides because of their gravitational pull. But a common mistake of primitive people is to think that everything timed in the same rhythm as the moon is caused by it.\n\nAll the moon gazing, probing and measuring has never solved the big problem: its origin. One theory is that it began as a planet, got too near the more massive earth, was 'captured' and turned into a satellite. Another is that the moon is the result of a giant tidal bulge forming on our earth's surface separating, then spinning off into space. If the latter theory is true, scientists say, there would be two clues: the moon would consist of lighter material than the earth, and the earth would be left with a scar. As a matter of fact, the moon does weigh less. And the Pacific Ocean does have a scar like bottom of basaltic rocks instead of the granite rocks usually found near the earth's surface.\n\nBut the assumption that, if man can get to the moon, he'll find the answer is unfounded. Man has been on the earth hundreds of thousands of years without determining the earth's origin. Scientists, of course, will never give up either quest.\n\nIndeed, for thousands of years the moon has worked a spell of fascination over all the people on its near neighbour, the earth. The ancient worshipped this lamp in the sky and speculated about it endlessly. Modern astronomers continue to explore its mysteries almost every night of the year, and with reason.\n\nAges ago, before artificial light was known, it was important as illumination at night. As everyone knows, the moon has no light of its own; it shines with the cold reflection of the distant sun, but actually the moon is a poor mirror reflecting only a fourteenth of the sun light received. The earth reflects a third of its sunlight providing its satellite with 'earth light' sixty times as bright as the best moonlight. That's why we sometimes see the whole moon faintly when the sun is lighting up only a narrow crescent.";
  const PT1 = "Capitalism is an economic system which is founded on the principle of free enterprise and the private ownership of the means of production and distribution. The ___(6)___ of capitalism claim that its essential characteristic is economic ___(7)___. The producer is free to produce whatever goods he ___(8)___; but the ___(9)___ is equally free to buy what he wants. There is a market mechanism under this system which brings the producer and consumer together and tends to equate the supplies of the one to the demands of the other, and ___(10)___ the whims and caprice of both. It is this same ___(11)___ mechanism which determines what prices the consumers pay to the producers, as well as what share the total ___(12)___, in cash or kind, goes to each of the four recognized ___(13)___ of production \u2013 land, labour, capital and organization. It is further claimed for this system that every person is capable of watching his or her own interest, and that whatever injustice is done by the ___(14)___ of the market mechanism, this mechanism tends to bring about a state of ___(15)___ between the producers and the consumers.";
  const PT2 = "We knew early in our life that the atmosphere in our home was different from that in many other homes, where husbands and wives quarrel and where there was drunkenness, laziness or indifference \u2014 things we never saw in our family. We chafed and grumbled at the strictness of my father's regime. We went to hide whenever we broke the rules too visibly. We knew, nevertheless, that our parents wanted good things for us. Some of these, such as the insistence on our going to school and never missing a day, we accepted readily enough, although, like most other children, we occasionally yielded to the temptation to play truant. However, in other cases such as their effort to keep us out of contact with the difficult life \u2013 the drinking and fighting and beer-brewing and gambling \u2013 their failure was inevitable. They could not keep us insulated. By the time we moved about, we were already seeing things with their eyes and judging things by the standards we had absorbed from them. from them.\n\nIt was borne in on me and my brother at a very early age that our father was an uncommon man. For one thing, in most African families, work around the home was women's work. So we were vastly impressed by the fact that whenever my mother was away, my father could and did do all her jobs \u2013 cooking, cleaning and looking after us. We lived in this way in a community in which housework was regarded as being beneath male dignity. Even in families which, like ours, produced boy after boy \u2013 our sister came fifth \u2013 it simply meant that the mother carried a greater and greater burden of work. In our family, nevertheless, the boys did girl's work and my father did it with us.\n\nOne of the prime chores of life in the family was fetching water from the pump down the street, some two hundred metres from our door. Since the pump was not unlocked until six in the morning and there was always crowding, a system had developed whereby you got out before dawn, placed your twenty-litre tin in line, and then went home, returning later to take your place. Often, of course, tins would be moved back in line and others moved ahead. This could be corrected if none of those in front were too big a challenge.\n\nWhen taps were substituted for the pumps, the first one installed was nearly a kilometre away from our house and we had to make the trek with the water tins balanced on our heads \u2013 an indignity because this was the way girls, not proud males, carried their burdens. All the children in the neighbourhood knew we did women's work and I can still hear their derisive laughter. We did our jobs doggedly, that notwithstanding, because our father and mother expected it of us. Out of choice our father did everything we did, including fetching water on the occasion, and commanded us by sheer force of his example.";
  const PT3 = "A Wolf, seeing a Lamb drinking from a river, wanted to find a pretext for devouring him. He stood higher up the stream and accused the lamb of muddying the water so that he could not drink. The lamb said that he drank only with tip of his tongue, and that in any case he was standing lower down the river, and could not possibly disturb the water higher up. When this excuse failed him, the wolf said: 'Well, last year you insulted my father.' 'I wasn't even born then,' replied the lamb.\n\n'You are good at finding answers, 'said the wolf, 'but what do you mean by taking up so much of the path where I am walking? The lamb, frightened at the wolf's angry tone and terrible aspect, told him, with all due submission, that he could not conceive how his walking on such a wide path could occasion him inconvenience. 'What!' exclaimed the wolf, seemingly in great anger and indignation. 'You are as impudent as your father who seized me by the throat last year, and caused me to be kept in a cage for three months.'\n\n'If you will believe me,' said the lamb, 'my parents are poor simple creatures who live entirely by green stuff; we are none of us hunters of your species.' 'Ah! I see it's no use talking to you, 'said the wolf, drawing up close to him. 'It runs in the blood of your family to hate us wolves, and therefore, as we have come so conveniently together, I'll just pay off a few of your forefathers' scores before we part.' So saying, he leapt at the lamb from behind and garroted him.";

  const P1Q = [
      { question: "The phrase 'near neighbour', as used in the passage, shows that", options: ["moonlight generally shares many characteristics with 'earth light'", "the earth is nearer to the moon than to the sun", "the earth actually shares boundaries with the moon", "moonlight shines brighter on the earth's surface than perhaps elsewhere"], answer: 1, explanation: "Calling the earth the moon's 'near neighbour' stresses how close the two are; the sun is described as 'distant'.", keyVerdict: 'corrected', keyAnswer: 'B/D', answerNote: "The key accepts B or D, but only B follows from 'near neighbour', a phrase about distance: the earth is close to the moon, while the sun is 'distant'. D (moonlight is brighter on earth than elsewhere) is never stated or implied, so only B is marked right." },
      { question: "The passage suggests that 'a blue moon' is a", options: ["rare phenomenon", "regular event", "trick of the moon", "life-long opportunity"], answer: 0, explanation: "'If, once in a lifetime, you see a blue moon' — it is rare, caused by dust in the upper atmosphere." },
      { question: "The sentence 'over the centuries, magical powers have been attributed to the moon' suggests that", options: ["people perform magic with the moon", "it is a common belief that the moon has magical powers", "the moon actually possesses magical powers", "the moon reflects magical powers from the sun's rays"], answer: 1, explanation: "To attribute powers to something is to believe or claim it has them; the writer goes on to call these beliefs mistakes." },
      { question: "The expression 'either quest' refers to the origin of", options: ["the moon or the earth", "neither the moon nor the earth", "the moon", "the earth"], answer: 0, explanation: "The two quests are finding the moon's origin and the earth's origin; scientists will never give up either of them.", keyVerdict: 'corrected', keyAnswer: 'B', answerNote: "'Either quest' means each of the two quests just mentioned: the search for the moon's origin and the search for the earth's origin ('without determining the earth's origin'). So it refers to the origin of the moon or the earth (A). B ('neither') reverses the meaning." },
      { question: "A suitable title for the passage is", options: ["The Magical Powers of the Moon", "Facts about the Moon", "The Lunar Cycle", "Moon-Gazing"], answer: 1, explanation: "The passage covers many facts about the moon: blue moons, tides, theories of its origin and its light. Magic is only one paragraph." },
  ];
  const CLOZE = [
      { question: "Gap 6: The _____ of capitalism claim that its essential characteristic is economic _____ (gap 7).", options: ["attorneys", "determiners", "antagonists", "protagonists"], answer: 3, explanation: "People who 'claim' good things for capitalism are its supporters, i.e. protagonists. Antagonists are opponents." },
      { question: "Gap 7: …its essential characteristic is economic _____.", options: ["freedom", "manoeuvring", "manipulation", "exploitation"], answer: 0, explanation: "The next sentences describe producers and consumers being 'free', so the characteristic is economic freedom." },
      { question: "Gap 8: The producer is free to produce whatever goods he _____.", options: ["manufactures", "buys", "sells", "fancies"], answer: 3, explanation: "Free to produce whatever he fancies (likes or chooses). 'Produce whatever he manufactures' repeats itself." },
      { question: "Gap 9: …but the _____ is equally free to buy what he wants.", options: ["consumer", "customer", "marketer", "controller"], answer: 0, explanation: "The producer is set against the consumer throughout the passage ('brings the producer and consumer together')." },
      { question: "Gap 10: …equate the supplies of the one to the demands of the other, and _____ the whims and caprice of both.", options: ["neutralize", "decide", "harmonize", "settle"], answer: 2, explanation: "The mechanism brings the two sides together, so it harmonizes (brings into agreement) their whims." },
      { question: "Gap 11: It is this same _____ mechanism which determines what prices the consumers pay.", options: ["controlling", "production", "operational", "market"], answer: 3, explanation: "'This same' points back to 'a market mechanism' mentioned earlier." },
      { question: "Gap 12: …as well as what share the total _____, in cash or kind, goes to each of the four recognized factors of production.", options: ["profit", "output", "dividends", "interest"], answer: 1, explanation: "What is shared among land, labour, capital and organization is the total output (product) of the economy.", keyVerdict: 'corrected', keyAnswer: 'C', answerNote: "Dividends are paid only to shareholders (owners of capital), so they can't be shared out among all four factors of production. The total output, paid as rent, wages, interest and profit, is, so B is correct." },
      { question: "Gap 13: …goes to each of the four recognized _____ of production – land, labour, capital and organization.", options: ["factors", "methods", "managers", "agents"], answer: 0, explanation: "Land, labour, capital and organization (entrepreneurship) are the four factors of production." },
      { question: "Gap 14: …whatever injustice is done by the _____ of the market mechanism…", options: ["pricing", "buyers and sellers", "managers", "operations"], answer: 3, explanation: "Injustice done by the mechanism comes from its operations (workings)." },
      { question: "Gap 15: …this mechanism tends to bring about a state of _____ between the producers and the consumers.", options: ["equilibrium", "equidistance", "opprobrium", "conflict"], answer: 0, explanation: "Balancing supply and demand produces equilibrium. Opprobrium means public disgrace." },
  ];
  const P3Q = [
      { question: "By describing his father as 'an uncommon man', the writer means that he is", options: ["amenable", "remarkable", "strict", "kind"], answer: 1, explanation: "Uncommon here means unusual and admirable: unlike most African men of his community, he did housework." },
      { question: "Which of the following describes the father's role in the family?", options: ["Being too hard on the children.", "Usurping his wife's role in the family.", "Serving the children.", "Leading by example."], answer: 3, explanation: "He 'did everything we did... and commanded us by sheer force of his example'." },
      { question: "The word 'atmosphere', as used in the first paragraph of the passage, means", options: ["pattern", "disposition", "preference", "unity"], answer: 0, explanation: "The home's atmosphere is its general pattern of life: other homes had quarrels and drunkenness, while theirs had strict rules." },
      { question: "Which of the following statements captures the family's approach to housework?", options: ["No job was reserved for anyone on the basis of gender.", "Their mother did the cooking and cleaning willingly.", "The boys were not allowed to do girls work.", "The water needed was provided by everyone."], answer: 0, explanation: "'The boys did girl's work and my father did it with us': chores were shared regardless of sex." },
      { question: "A suitable title for the passage is", options: ["A Village Life", "The Unusual Parent", "The Problem of Water", "An Experience in Early life"], answer: 1, explanation: "The passage centres on the father, 'an uncommon man', who did women's work and led by example." },
  ];
  const P4Q = [
      { question: "The charges levelled against the lamb are", options: ["pollution, insolence, obstruction and aggression", "exuberance, pollution, wickedness and stubbornness", "garrulity, loquacity, pride and arrogance", "greed, wandering, insolence and disrespect"], answer: 0, explanation: "Muddying the water (pollution), insulting the wolf's father (insolence), taking up the path (obstruction) and the father seizing the wolf by the throat (aggression)." },
      { question: "From the way the story ended, it can be concluded that the", options: ["wolf and the lamb parted amicably", "lamb did not survive the encounter", "wolf had encountered the lamb's parents", "lamb offended the wolf quite seriously"], answer: 1, explanation: "The wolf 'leapt at the lamb from behind and garroted him' (strangled him)." },
      { question: "Which of the following aptly describes the moral of the story?", options: ["No matter how highly placed he is in society, the unmindful lawbreaker will always meet his nemesis.", "The law is weak in defence of the poor against the rich and mighty.", "The sins of the forefathers are visited upon the children no matter how long it takes.", "If you have made up your mind to hang your dog, any rope will do for the purpose."], answer: 3, explanation: "The wolf had already decided to eat the lamb and grabbed at any excuse; when one failed, he made up another." },
      { question: "The expression 'when this excuse failed him' suggests that the", options: ["lamb was prepared for the charges levelled against him", "wolf was uncertain of the charges levelled against the lamb", "wolf only made up the charges levelled against the lamb", "lamb was more intelligent than the wolf"], answer: 2, explanation: "The charge was an excuse, a made-up pretext; when the lamb disproved it, the wolf simply invented another." },
      { question: "The expression 'angry tone and terrible aspect' refers to the wolf's", options: ["towering size and thunderous voice", "harsh voice and menacing posture", "sonorous voice and overbearing attitude", "loud voice and fretting movement"], answer: 1, explanation: "Tone is the voice (angry → harsh), and aspect is appearance (terrible → menacing)." },
  ];

  const passages = [
    { passageId: 'eng-2004-p1', passageTitle: 'JAMB 2004 — Passage I', year: Y, instruction: READ, passage: PT0, questions: P1Q },
    { passageId: 'eng-2004-p2', passageTitle: 'JAMB 2004 — Passage II (cloze)', year: Y, instruction: 'The passage has gaps numbered 6 to 15. Choose the most appropriate option for each gap.', passage: PT1, questions: CLOZE },
    { passageId: 'eng-2004-p3', passageTitle: 'JAMB 2004 — Passage III', year: Y, instruction: READ, passage: PT2, questions: P3Q },
    { passageId: 'eng-2004-p4', passageTitle: 'JAMB 2004 — Passage IV', year: Y, instruction: READ, passage: PT3, questions: P4Q },
  ];

  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const GAP = 'Choose the option that best completes the gap(s): ';
  const VOWEL = 'Choose the option that has a DIFFERENT vowel sound from the others.';
  const SAMEV = 'Choose the option that has the same vowel sound as the letter(s) in capitals: ';
  const CONS = 'Choose the option that has the same consonant sound as the letter(s) in capitals: ';
  const DIFFC = 'Choose the option that has a DIFFERENT consonant sound from the others.';
  const DIFF = 'Choose the option that has a DIFFERENT stress pattern from the others.';
  const SAMES = 'Choose the option that has the same stress pattern as the given word (stressed syllable in capitals): ';
  const STRESSOF = 'Choose the appropriate stress pattern for the word (the stressed syllable is in capitals): ';
  const FIRST = 'Choose the option that has the stress on the FIRST syllable.';
  const NEAR = 'Choose the option NEAREST in meaning to the word(s) in capitals: ';
  const MEANS = 'Select the option that best explains the information conveyed in the sentence: ';
  const EMPH = 'The word in capitals has emphatic stress. Choose the option that best fits the expression: ';
  const OPP = 'Choose the option OPPOSITE in meaning to the word(s) in capitals: ';

  const flat = [
    q(SAMEV + "bEAr", ["rare", "fear", "beer", "steer"], A, "The ea in bear is /eə/ (as in air), like the a-e in rare. Fear, beer and steer have /ɪə/."),
    q(SAMEV + "nIne", ["click", "gill", "pint", "pin"], C, "The i in nine is /aɪ/, as in pint. Click, gill and pin have the short /ɪ/."),
    q(STRESSOF + "expostulate", ["exPOStulate", "exposTUlate", "expostuLATE", "EXpostulate"], A, "Expostulate (to argue in protest) is stressed on the second syllable: ex-POS-tu-late."),
    q(STRESSOF + "sufficiency", ["sufficienCY", "suffiCIENcy", "sufFIciency", "SUFficiency"], C, "Sufficiency is stressed on the second syllable, like sufficient: suf-FI-cien-cy."),
    q(GAP + "He isn't coming home, is he? _____, he isn't.", ["No", "Why", "Yes", "Now"], A, "In English the reply agrees with the facts: a negative answer ('he isn't') starts with 'No'."),
    q(GAP + "The poor widow who could not buy the clothes was seen _____ her wool into _____ yesterday.", ["making/tailoring", "to spin/yards", "spinning/yarn", "to spill/clothes"], C, "Wool is spun into yarn (thread). After 'was seen' we use the -ing form (or 'to' + verb)."),
    q(GAP + "_____ his illness, Muhammad could not come to school.", ["Referring to", "With reference to", "Due to", "Owing to"], D, "'Owing to' (because of) is the traditional choice at the start of a sentence. 'Due to' is common in modern English and is also accepted. (The paper misprints D as 'Owning to'.)", { alsoAccept: [C], keyVerdict: 'multiple', keyAnswer: 'C', answerNote: "Traditional grammar keeps 'due to' after the verb be ('his absence was due to illness') and uses 'owing to' to begin a sentence, so D (printed 'Owning to', a misprint) is the textbook answer. The key's 'Due to' (C) is widely used and accepted today, so both are marked right." }),
    q(GAP + "You may not have heard the last word on the matter, _____", ["have you?", "may you have?", "haven't you?", "mayn't have you?"], A, "After a negative statement the tag is positive. The key uses the auxiliary 'have': 'have you?'"),
    q(GAP + "Agbo says he is not afraid of _____.", ["no one", "nothing", "nobody", "anybody"], D, "'Not' already makes the sentence negative, so we need 'anybody' (a double negative like 'not... nobody' is wrong)."),
    q(GAP + "The city _____ as a federal capital only _____ the last twenty years.", ["existed/over", "has existed/for", "was existing/from", "is existing/in"], B, "A situation continuing up to now uses the present perfect with 'for' + period: has existed for twenty years."),
    q(GAP + "He not only looked after the children when their parents died, _____ sponsored their education to university.", ["also he", "also", "but also", "but he"], C, "'Not only... but also' is a fixed pair."),
    q(GAP + "After so many trials, the experiment _____.", ["paid up", "paid off", "paid out", "paid for"], B, "To pay off means to succeed or bring good results."),
    q(GAP + "His supporters rallied round him in moments of _____.", ["criticism", "disillusionment", "acrimony", "crisis"], D, "People rally round someone in times of crisis (trouble)."),
    q(GAP + "One needs to exemplify or _____ the aspect of the subject being discussed.", ["declare", "demonstrate", "satisfy", "supply"], B, "To exemplify is to illustrate with an example, i.e. to demonstrate."),
    q(GAP + "Actually, he forgot the one to _____ the job was given.", ["whomever", "who", "whoever", "whom"], D, "After a preposition (to) we use the object form whom: the one to whom the job was given."),
    q(GAP + "The police claim that a number of stolen cars _____ recovered.", ["is being", "has being", "have been", "has been"], C, "'A number of' + plural noun takes a plural verb: a number of cars have been recovered."),
    q(GAP + "The storm _____ havoc on several buildings in the village.", ["did", "wrecked", "made", "wreaked"], D, "The fixed collocation is 'to wreak havoc'; its past is wreaked."),
    q(GAP + "People dislike Mariam because she is _____.", ["trickful", "tricky", "a tricker", "trickish"], B, "The adjective is tricky (crafty, deceitful). Trickful, tricker and trickish are not standard words."),
    q(GAP + "The chairman refused to shake _____ with the secretary.", ["hands", "his hand", "hand", "his hands"], A, "The idiom is 'shake hands with someone'."),
    q(GAP + "Ali goes to the stadium regularly, but he _____ to the church for months.", ["didn't go", "hasn't been", "haven't been", "hadn't been"], B, "'For months' up to now needs the present perfect: he hasn't been (singular 'he' → hasn't)."),
    q(GAP + "No teacher of honour would subject his student to any form of _____.", ["harrassment", "harrasment", "harassement", "harassment"], D, "The spelling is h-a-r-a-s-s-m-e-n-t: one r, double s."),
    q(GAP + "The interpreter was wrong because he gave the congregation a _____ translation of the pastor's statement.", ["unilateral", "literary", "literal", "lateral"], C, "A literal translation is word-for-word, which can distort the meaning."),
    q(GAP + "Each of the houses _____ a new look.", ["have got", "has", "have", "were given"], B, "'Each' is singular, so it takes 'has'."),
    q(GAP + "The reporter said that the Honourable Speaker _____ impeached.", ["is to be", "will have been", "might have been", "may have being"], C, "In reported speech the verb shifts back: 'might have been impeached'. 'Is to be' and 'will have been' don't shift, and 'may have being' is ungrammatical."),
    q(GAP + "It is _____ responsibility to look after their parents in old age.", ["their's", "theirs'", "theirs", "their"], D, "Before a noun we use the possessive determiner 'their' (their responsibility). Possessives never take an apostrophe."),
    q(GAP + "I shall find time for my _____ when I get _____ with this difficult assignment.", ["pastime/through", "pass-time/over", "passtime/through", "past-time/over"], A, "The spelling is pastime (one s, no hyphen), and 'get through with' means finish."),
    q(GAP + "All God's prophets were given the great _____ to preach salvation to people.", ["commition", "comission", "commission", "commision"], C, "The spelling is c-o-m-m-i-s-s-i-o-n: double m, double s."),
    q(GAP + "Each producer is able to place a price on his product by considering its _____.", ["assessment", "choice", "judgement", "worth"], D, "A price reflects the product's worth (value)."),
    q(GAP + "The minister addressed the workers to boost their _____.", ["mural", "morale", "morality", "moral"], B, "Morale is the spirit and confidence of a group; a moral is a lesson."),
    q(CONS + "causED", ["realized", "frost", "released", "chanced"], A, "After a voiced sound (/z/ in cause) -ed is pronounced /d/, as in realized. Released and chanced end in /t/."),
    q(CONS + "misCHief", ["champagne", "Christmas", "brochure", "ritual"], D, "The ch in mischief is /tʃ/. The t in ritual is also /tʃ/ (RICH-oo-al). Champagne and brochure have /ʃ/, Christmas /k/."),
    q(CONS + "Judge", ["pleasure", "camouflage", "spinach", "gear"], C, "J in judge is /dʒ/. The ch in spinach is pronounced /dʒ/ in British English (SPIN-idge). Pleasure and camouflage have /ʒ/, and gear has /g/."),
    q(EMPH + "The student BOUGHT the book.", ["Who bought the book?", "What did the student buy?", "How will the student get the book?", "Did the student steal the book?"], D, "Stressing BOUGHT corrects the action: 'Did the student steal the book?' No, he BOUGHT it."),
    q(EMPH + "The teacher wants MY pen.", ["Does the teacher want your ruler?", "Who wants my pen?", "Does the teacher want his pen?", "What does the teacher want?"], C, "Stressing MY corrects whose pen it is: 'Does the teacher want his pen?' No, MY pen."),
    q(MEANS + "The investigators stated clearly that they had reached a dead end in their scrutiny of suspects in the murder case.", ["The end had come for the suspects in the murder case.", "There was no further progress in the investigation of the murder suspects.", "The investigators did not know what to do with suspects in the murder.", "The investigators had evidence to sentence the suspects to death in the end."], B, "A dead end is a point beyond which no progress can be made."),
    q(MEANS + "In many countries, democracy is ostensibly being practiced.", ["Many countries have effective democracy.", "Democracy is indeed being practiced in many countries.", "Democracy is apparently practiced in many countries.", "Many countries have democracy in practise."], C, "Ostensibly means apparently, seemingly (but perhaps not really)."),
    q(MEANS + "Adamu's father is a key figure in that ministry.", ["Adamu's father's position is essential in the ministry.", "The ministry trusts Adamu's father as a central figure.", "Adamu's father is a figurehead in the ministry.", "Adamu's father keeps the key to the ministry."], A, "A key figure is a very important person whose role is essential. A figurehead has a title but no real power."),
    q(MEANS + "Everyone was ready to play the devil's advocate in the impeachment controversy.", ["Everyone was willing to fight for the defenceless citizens no matter the consequences.", "Everyone was willing to defend an unpopular point of view concerning the impeachment.", "Everyone was willing to speak against the impeachment to encourage discussion on it.", "Everyone was willing to be an evil genius in the controversy."], C, "A devil's advocate argues against a proposal, not out of conviction, but to test it and provoke discussion."),
    q(MEANS + "The government warns that drink-driving is punishable under the law.", ["A drunkard driving can be punished.", "Drinking and driving is an offence.", "Driving while drinking is an offence.", "Driving while drunk is an offence."], D, "Drink-driving means driving after drinking too much alcohol, i.e. driving while drunk."),
    q(DIFF, ["result", "ratify", "taxi", "famous"], A, "reSULT is stressed on the second syllable; RAtify, TAxi and FAmous on the first."),
    q(DIFF, ["orthopaedic", "secondment", "photographic", "oriental"], B, "seCONDment is stressed on the second syllable; orthoPAEdic, photoGRAphic and oriENtal on the third."),
    q(VOWEL, ["pot", "hall", "water", "altar"], A, "Pot has the short /ɒ/; hall, water and altar have the long /ɔː/."),
    q(VOWEL, ["tout", "foe", "foul", "owl"], B, "Foe has /əʊ/; tout, foul and owl have /aʊ/."),
    q(NEAR + "The presence of the captain makes the sailors ILL AT EASE.", ["impatient", "easily ill", "uncomfortable", "sickly"], C, "Ill at ease means uncomfortable or nervous."),
    q(NEAR + "Ibro shows enough LIBERALITY with his meager income.", ["insensitivity", "prodigality", "frugality", "generosity"], D, "Liberality means generosity. Prodigality is wasteful spending."),
    q(NEAR + "It is a MISNOMER to call three thousand naira a living wage.", ["a wrong description", "an incontrovertible assertion", "an appropriate term", "a mishmash"], A, "A misnomer is a wrong or misleading name or description."),
    q(NEAR + "The press described the efforts of the government in PEJORATIVE terms.", ["superlative", "palpable", "critical", "contemptible"], D, "Pejorative words express contempt or disapproval.", { alsoAccept: [C], keyVerdict: 'multiple', keyAnswer: 'D', answerNote: "Pejorative means expressing contempt or disapproval. The key's D carries the idea of contempt, although strictly 'contemptible' means deserving contempt ('contemptuous' would be exact). 'Critical' (C) is also a fair synonym, since pejorative terms are disapproving, so both are marked right." }),
    q(NEAR + "The town was in such a TURMOIL that the dance was called off.", ["state of darkness", "state of confusion", "rainy state", "mourning state"], B, "Turmoil is a state of great confusion and disorder."),
    q(NEAR + "The festivals create in the people a feeling of pride in their cultural HERITAGE.", ["legacy", "possession", "history", "heirloom"], A, "Heritage is what is handed down from the past, i.e. a legacy. An heirloom is a single valued object."),
    q(NEAR + "Okonkwo manages his household WITH A HEAVY HAND.", ["using the cane on every occasion", "without tolerating weaknesses", "like a powerful dictator", "like a heavyweight champion"], C, "To rule with a heavy hand is to be harsh and oppressive, like a dictator."),
    q(NEAR + "In spite of constant financial support from his father, Udenyi treats his studies with considerable LEVITY.", ["lassitude", "wastefulness", "enthusiasm", "seriousness"], A, "Levity means a lack of seriousness. No option means exactly that; lassitude (listless lack of energy) is the closest.", { keyVerdict: 'none', keyAnswer: 'A', answerNote: "Levity means treating serious things lightly, i.e. frivolity. None of the options means that: lassitude is tiredness, wastefulness is waste, enthusiasm is eagerness, and seriousness is the opposite. A is the closest, because a student who treats his studies with levity and one who treats them with lassitude both fail to put in the effort." }),
    q(NEAR + "The school's badge is the INSIGNIA of office for all the prefects in the school.", ["seal", "recognition", "power", "symbol"], D, "Insignia are badges or emblems that symbolize rank or office."),
    q(NEAR + "FUNNILY ENOUGH, the priest prayed for the robber who shot him.", ["timidly", "fearlessly", "unexpectedly", "disappointingly"], C, "'Funnily enough' introduces something surprising or unexpected."),
    q(NEAR + "The MOTTLED skin of a person with HIV indicates an advanced stage of its development.", ["pimply", "scaly", "brown", "spotted"], D, "Mottled means marked with irregular spots or blotches of colour, i.e. spotted.", { keyVerdict: 'corrected', keyAnswer: 'C', answerNote: "Mottled describes a pattern of irregular patches or spots of colour, not a colour, so 'brown' doesn't match. D (spotted) is correct." }),
    q(NEAR + "The prosecutor was fully able to SUBSTANTIATE the charge.", ["expatiate on", "weaken", "prove", "dismiss"], C, "To substantiate is to provide evidence to prove something."),
    q(NEAR + "The manager's knowledge of the strike is of the UTMOST importance.", ["basic", "genuine", "standard", "paramount"], D, "Utmost means greatest, so of the utmost importance = of paramount (supreme) importance."),
    q(NEAR + "There has been A DOWNTURN in the affairs of the company.", ["a turn-around", "a massive increase", "a decline", "little progress"], C, "A downturn is a decline."),
    q(NEAR + "His plans BOOMERANGED on him.", ["catapulted", "backfired", "fell", "bounced"], B, "A plan that boomerangs comes back to hurt its maker, i.e. backfires."),
    q(FIRST, ["condemn", "intact", "afternoon", "bachelor"], D, "BAchelor is stressed on the first syllable; conDEMN and inTACT on the second, and afterNOON on the third."),
    q(FIRST, ["impossible", "criticism", "eleven", "circulation"], B, "CRIticism is stressed on the first syllable; imPOSsible and eLEven on the second, circuLAtion on the third."),
    q(OPP + "The noise of the fans UNNERVED the star player.", ["calmed", "confused", "refreshed", "helped"], A, "To unnerve is to make someone nervous; the opposite is to calm them."),
    q(OPP + "We found a SHADY place for the display.", ["an enclosed", "a stuffy", "an open", "an unsafe"], C, "A shady place is sheltered from the sun; an open place is exposed to it."),
    q(OPP + "The player WRITHED IN PAIN after the fall.", ["cried out", "remained still", "walked out", "shook violently"], B, "To writhe is to twist and turn in pain; the opposite is to remain still."),
    q(OPP + "The ship was IMPERILLED by high winds.", ["saved", "deceived", "destroyed", "piloted"], A, "Imperilled means put in danger; the opposite is saved."),
    q(OPP + "The team got an ECSTATIC welcome from the crowd.", ["a joyous", "an unexpected", "an expected", "a cold"], D, "An ecstatic welcome is wildly joyful; the opposite is a cold one."),
    q(OPP + "Sailors are unusually DAUNTLESS in their exploits.", ["excited", "ruthless", "frightened", "selfless"], C, "Dauntless means fearless; its opposite is frightened."),
    q(OPP + "Beauty queens sometimes wear OUTLANDISH dresses.", ["familiar", "flashy", "beautiful", "attractive"], A, "Outlandish means strange and unfamiliar; the opposite is familiar."),
    q(OPP + "My father's presentation was rather CASUAL.", ["divisive", "vital", "informal", "formal"], D, "Casual means relaxed and informal; the opposite is formal."),
    q(OPP + "The Flying Eagles put up a PLUCKY defence against their opponents.", ["weak", "strong", "careless", "tactful"], A, "Plucky means brave and determined; the opposite here is weak."),
    q(OPP + "The journalist said he was working FREELANCE.", ["satisfactorily", "without a pay", "dependently", "tirelessly"], C, "A freelance worker is self-employed and independent; the opposite is working dependently (as an employee)."),
    q(OPP + "The injured man is determined to GET BACK AT his assailant.", ["visit", "forgive", "identify", "attack"], B, "To get back at someone is to take revenge; the opposite is to forgive."),
    q(OPP + "The dictator wanted TRACTABLE men in his cabinet.", ["tough", "intelligent", "unruly", "reliable"], C, "Tractable means easily controlled; the opposite is unruly."),
    q(OPP + "After the war, the victors became increasingly VINDICTIVE.", ["treacherous", "arrogant", "vociferous", "friendly"], D, "Vindictive means seeking revenge; of the options, friendly is the opposite."),
    q(OPP + "The POTENCY of the drug has been acknowledged.", ["action", "inefficacy", "power", "loss"], B, "Potency is power or effectiveness; inefficacy is ineffectiveness."),
    q(OPP + "The man who scared the girl was a bit DERANGED.", ["crazy", "amorous", "dangerous", "sane"], D, "Deranged means mentally unbalanced; the opposite is sane."),
  ];

  QUESTION_BANK.english = QUESTION_BANK.english.concat(passages, flat);
})();
