/**
 * JAMB/UTME 2011 — USE OF ENGLISH
 * From the 2011 question paper; answers from the JAMB/UTME English Language
 * answer key 2001–2020, each checked against the paper. Where the key in
 * circulation is wrong (often a printing error) the question carries
 * keyVerdict + keyAnswer + answerNote (see english-2007.js for the scheme).
 * Question 1 of the paper (which paper type the candidate is sitting) is left out.
 * Loaded after questions.js and before app.js.
 */
(function () {
  const Y = 2011;
  const SRC = 'JAMB UTME 2011';
  const READ = 'Read the passage carefully and answer the questions that follow.';

  const PT0 = "In 1962, a team of scientists produce a special radio station that had a range of fifteen miles. Even though communication was being accomplished in space at a range of more than a million times this distance, the new radio station caused much excitement among scientist. The reason: its power supply was a 'battery' made of bacteria. For the first time, practical amounts of electricity were being produced by a form of life and put to use.\n\n'Bio cell', the new power supply had a liquid fuel containing tiny forms of life that changed the fuel directly into electric energy; this was far more than an interesting experiment. The bio cell is being develop as producers of electricity for radio, for signal to guide ship, for lighting and other uses. Though the working bio cell is only a few years old, some scientist feels that it will one day produce power cheaply as is now being done by other method, and that the bio cell will use materials that would otherwise be consider a waste. Early bio cells were powered with sugar, but a wide range of fuel can be used. Work is being done using sea water to feed the bacteria.\n\nElectricity from living cells is no new idea. Man experience the strange shock produce by some fish even before electricity was really discovered. Then in time, there were other discoveries. Benjamin Franklin found that lightening in the sky was electricity. Luigi Galvani found some electricity in the muscles and nerves of animals, but the African catfish produce far more electricity than most other living creatures. And other fish, the electric eel, well named, for it has an even greater electric charge. Research works also discovered that even humans produce small amount of electricity in their bodies. Our heart produces a very small amount that can be measured, so do our brain. The bio cell is completely new in the field of power production and as yet, no mass-production models have begun to replace the older type of batteries. It might be wondered, then, what the excitement is all about.";
  const PT1 = "Like a clock with the pendulum in full swing, the mind moves as fast as time flies. But we ought to mind our thoughts for if they turn to be our enemies, they will be too many for us and will drag us down to ruin.\n\nBut some people may say that they cannot help having bad thought even though they sting like vipers. That may be so, but the question is, do they hate them or not? We cannot keep thieves from looking in at our windows, but if we open our doors to them and receive them joyfully, we are as bad as they. We cannot help the birds flying over our head; but we may keep them from building their nests in our hair. Vain thought will knock at the door but we must not open to them. Though bad and evil thought rise in our hearts, they must not be allowed to reign. He who turns a morsel over and over in his mouth does so because he likes the flavour, and he who meditate upon evil, love it, and is ripe to commit it. Think of the devil, and he will appear, turn your thought toward evil and your hands will soon follow. Snails leaves their slime behind them, and so do vain thought. An arrow may fly through the air, and leaves no trace, but an evil thought always leaves a trail like a serpent.\n\nWhere there is much traffic of bad thinking, there will be much mire and dirt. Every wave of wicked thought adds something to the corruption which rots upon the shore of life. It is dreadful to think that a vile imagination, once indulge, gets the key of our minds, and can get in again very easily, whether or not we let it in, and what may follow, no one knows. Nurse evil on the laps of thought, and it will grow into a giant.\n\nTherefore; there is wisdom in watching every day, the thought and imagination of our heart. Good thoughts are blessed guest and should be welcomed, and much sought after, but bad thought must fly out as swiftly as they moved in.";
  const PT2 = "Though assumption is the lowest level of knowledge; it is still a form of knowledge, and knowledge is key. Assumptions are the foundation upon which interpretation and conclusion are built. Everything in life operate under certain assumptions.\n\nWe make management decisions based on the assumptions we hold about how management ought to function and how people ought to be governed. For some of us, we consciously imbibe assumptions and principles about life and consciously decide based on them; for others, it is unconsciously but potent all the same. Our assumptions will either drown us or help us soar through life.\n\nWe have always seen life as an immense mansion with many rooms. Some rooms lead to wealth, others to the opposite. Ultimately, we decide where we end up; and life, thus far, has proved that not everyone of us decides well, we all behave differently where we have different levels of understanding, and behave same the way where our understanding is the same. We eat because we all understand the consequences of not eating. We all wear clothes because each of us comprehends lunacy. The list goes on and on. It is inevitable that some of us will make choices that get and keep us on the lower rung of the ladder by reason of exposure, training or some others variables. Life is about role playing. We choose our roles wisely or foolishly, consciously or unconsciously. Some of us get wiser to new levels of self-awareness enough to redefine our roles, others make no effort to build further capacity and therefore remain where they are.\n\nIt is based on those realities that we draw the conclusion that not everyone will be wealthy in life. We lead, inspire and motivate people to strive and succeed. It is also important that we paint the full and true picture of life so that we can discourage vain pursuits. Balance must be enthroned as a critical component of truth, and people know, for instance, that 'the top' is not a place that all must ascend.\n\nOur greatest consolation lies in our deep conviction that true prosperity is in fulfillment through hard work than in intangible acquisition. There are set roles that some of us have been wired up to play in life but which we are not content enough to play because society esteems such roles to be inferior. Take the almost sacred office of a teacher for instance; there are people who have the natural gifts and inclinations to be school teacher. But teaching profession, as it is, does not appear to be lucrative. So we have people who could have been more fulfilled and effective working as school teacher serving in banks.";
  const PT3 = "Believe it or not, change is to human existence what the blood is to the human body. We live in an era of amazing ___(16)___ change spawned by advancing technology and industrialization. However, man's ___(17)___ promoting and defending change in a deliberate effort to establish ___(18)___ that stimulate advancement for man's concern is proving unfavorable to the climate with threatening ___(19)___. Human-induced climate change has awakened widespread concern across the globe. As a matter of fact, climate change is now ___(20)___ globe issue. It is a major test of Africa's ___(21)___. The Fourth Assessment Report (AR4) of the intergovernmental panel of climate change (IPCC) confirm that human action are changing the earth's climate and creating major disturbance in human ___(22)___ and ecosystems. The IPCC reports that world has warmed by an average of 0.76\u00b0C since pre-industrial times. The rising global ___(23)___ for energy and the adverse changes on earth were commensurate with the level of greenhouse ___(24)___ it spews out, perhaps Africa would have been spared and would probably be just an amused spectator. But as it is, this is not the case. Here again, we see well-meaning global citizen appealing for the rest of the world to take responsibility for the problem of Africa, a strategy that cannot, thus far, be termed ___(25)___.";

  const P1Q = [
      { question: "The writer's posture, as conveyed in the statement 'Electricity from living cells is no new idea', can be described as", options: ["ineffectual", "contentious", "logical", "unguarded"], answer: 2, explanation: "The writer makes a calm claim and backs it with evidence in order (shocks from fish, Franklin, Galvani, the catfish and eel, the human body), so the posture is logical." },
      { question: "Which of the following is true according to the passage?", options: ["Scientists felt that the bio cell would produce very costly energy.", "Bio cells, at the beginning, derived their energy from sugar.", "Sugar and fuel were initially used as source of energy for bio cells.", "Bio cells were forms of power used by the scientists."], answer: 1, explanation: "The passage says 'Early bio cells were powered with sugar', which B restates exactly.", alsoAccept: [2], keyVerdict: 'multiple', keyAnswer: 'C', answerNote: "B is the closest restatement of 'Early bio cells were powered with sugar', so it is marked right. The key's C can also be defended, since the bio cell ran on a liquid fuel and the early ones were powered with sugar, so it is accepted as well. A is false: scientists expected cheap power." },
      { question: "The inventor of the bio cell justified the need for it by saying that it would", options: ["develop ways for changing bio cells into fuel for use", "yield a source of energy without much spending", "produce electricity for all types of machines", "produce signals to guide all ships and other vessels"], answer: 1, explanation: "Scientists felt the bio cell 'will one day produce power cheaply' and use materials that would otherwise be waste: energy without much spending." },
      { question: "According to the passage, electricity was first discovered in", options: ["heart and brains", "muscles of animals", "lightning", "fish"], answer: 3, explanation: "Man felt 'the strange shock produce by some fish even before electricity was really discovered'; Franklin (lightning) and Galvani (muscles) came later." },
  ];
  const P2Q = [
      { question: "Which of the following represents the writer's view in the passage?", options: ["Evil thoughts may come but there is virtue in keeping them out.", "Evil thought will continue to sting us like vipers as long as there are enemies who cause offence.", "Like the pendulum, evil thought will always come to our mind no matter what we do.", "Like most birds, evil thoughts fly swiftly in our minds without perching."], answer: 0, explanation: "We cannot stop birds flying over our heads, but we can stop them nesting in our hair: bad thoughts may come, but we must not let them stay." },
      { question: "Which of the following statements represents the view expressed by the writer in the first paragraph?", options: ["Evil thought will eventually ruin the evil man.", "If we do not stop the pendulum of thought from swinging, our thoughts will soon become our enemies.", "Too many evil thoughts leave fatal consequences.", "It is possible to decide what controls our thoughts."], answer: 2, explanation: "Paragraph 1: if our thoughts become our enemies 'they will be too many for us and will drag us down to ruin'." },
      { question: "From the argument in the second paragraph, it can be concluded that evil thoughts control the lives of people who", options: ["are helpless because they fly out of their minds", "cherish idle and slothful ways", "are thieves with evil instincts", "treasure and ruminate on them"], answer: 3, explanation: "Evil rules those who 'receive them joyfully', who turn the thought over 'like a morsel' and 'meditate upon evil'; that is, who treasure and ruminate on them." },
      { question: "The expression 'Think of the devil, and he will appear', as used in the passage, suggests that", options: ["like the devil, evil thoughts must not reign in our hearts", "evil thoughts are fantasies which exist only in people's minds", "uncontrolled evil thoughts may lead to evil deeds", "the devil gives evil thoughts only to those who invite him in"], answer: 2, explanation: "The writer explains it at once: 'turn your thought toward evil and your hands will soon follow', so evil thoughts lead to evil deeds." },
      { question: "Which of the following statements summarizes the argument of the fourth paragraph?", options: ["Heavy traffic on a miry and dirty road may lead to evil thoughts.", "The more evil we think, the more vile we are likely to become.", "Evil people should not be welcomed as guests in our homes the same way we welcome good people.", "Evil thoughts control the key to the human heart and no one can keep them out."], answer: 1, explanation: "The paragraph on the 'traffic of bad thinking' says every wave of wicked thought adds to our corruption: the more evil we think, the viler we become." },
  ];
  const P3Q = [
      { question: "According to the writer, people lead and motivate others because they want to", options: ["project individual contribution", "encourage selfless service", "make the world a home", "prevent empty search"], answer: 0, explanation: "'We lead, inspire and motivate people to strive and succeed': to bring out each person's own effort and contribution." },
      { question: "According to the passage, balance must be enthroned because it is", options: ["a critical interdependent function", "an amazing help for conscience", "a critical part of fidelity", "a serious way of ensuring success"], answer: 2, explanation: "'Balance must be enthroned as a critical component of truth'; fidelity means faithfulness to the truth, so 'a critical part of fidelity' restates it.", keyVerdict: 'corrected', keyAnswer: 'B', answerNote: "The passage says balance is 'a critical component of truth'. Fidelity means faithfulness or exactness to the truth, so C ('a critical part of fidelity') says the same thing. Nothing in the passage links balance to conscience, so the key's B is not supported." },
      { question: "The word 'inclinations', as used in the passage, means", options: ["creeds", "tendencies", "inhibitions", "power"], answer: 1, explanation: "Natural gifts and inclinations are natural leanings or tendencies towards something, here teaching." },
      { question: "Which of the following statements is true according to the passage?", options: ["Greatness in life emerges when square pegs are put in round holes.", "People do certain things in life because they know the repercussions.", "People agree on all issues and behave the same way for the same reason.", "Understanding life at different levels gives no account of visible acquisition."], answer: 1, explanation: "'We eat because we all understand the consequences of not eating. We all wear clothes because each of us comprehends lunacy.' We act because we know the repercussions.", keyVerdict: 'corrected', keyAnswer: 'D', answerNote: "The passage gives eating and wearing clothes as examples of things we do because we understand the consequences, which is exactly B. D says the opposite of the passage: different levels of understanding are why some end up wealthy and others on the lower rung of the ladder." },
      { question: "From the passage, it can be inferred that", options: ["people insincerely discuss facts that govern their behaviour", "all managerial decisions are based on assumptions", "people make conscious effort to acquire hidden knowledge", "all things in life exist on some beliefs"], answer: 3, explanation: "'Everything in life operate under certain assumptions': assumptions are beliefs taken for granted, so all things in life rest on some beliefs.", alsoAccept: [1], keyVerdict: 'corrected', keyAnswer: 'C', answerNote: "The passage never says people try to acquire hidden knowledge; it says only some of us consciously take in assumptions, while for others it is unconscious. Its main claim is that 'everything in life operate under certain assumptions', which D restates. B (management decisions are based on assumptions) is also stated in the passage, so it is accepted too." },
  ];
  const CLOZE = [
      { question: "Gap 16: We live in an era of amazing _____ change spawned by advancing technology and industrialization.", options: ["well-define", "fast-paced", "favorable", "social"], answer: 1, explanation: "Change driven by advancing technology is amazing because it is rapid: fast-paced change." },
      { question: "Gap 17: However, man's _____ promoting and defending change ... is proving unfavourable to the climate.", options: ["knowledge of", "attitude to", "commitment to", "opinion of"], answer: 2, explanation: "One is committed to doing something (commitment to + -ing): man's commitment to promoting change." },
      { question: "Gap 18: ... in a deliberate effort to establish _____ that stimulate advancement for man's concern.", options: ["customs", "companies", "trade-zone", "variations"], answer: 3, explanation: "The passage is about change; man promotes change to establish variations (new ways of doing things) that stimulate advancement." },
      { question: "Gap 19: ... is proving unfavourable to the climate with threatening _____.", options: ["repercussions", "clouds", "pressure", "implications"], answer: 0, explanation: "Repercussions are the bad after-effects of an action; 'threatening repercussions' fits the damage to the climate." },
      { question: "Gap 20: As a matter of fact, climate change is now _____ globe issue.", options: ["an acceptable", "a foremost", "the only", "the last"], answer: 1, explanation: "Climate change has awakened 'widespread concern across the globe', so it is a foremost (leading) issue." },
      { question: "Gap 21: It is a major test of Africa's _____.", options: ["popularity", "energy", "ingenuity", "incapability"], answer: 2, explanation: "A hard problem tests one's ingenuity (cleverness at finding solutions)." },
      { question: "Gap 22: ... human action are changing the earth's climate and creating major disturbance in human _____ and ecosystems.", options: ["geography", "society", "systems", "life"], answer: 3, explanation: "Climate change disturbs human life and the natural ecosystems.", alsoAccept: [2], keyVerdict: 'multiple', keyAnswer: 'D', answerNote: "The IPCC's own wording is 'human systems and ecosystems', so 'systems' (C) fits as well as the key's 'life' (D). Both are marked right." },
      { question: "Gap 23: The rising global _____ for energy ...", options: ["command", "demand", "warming", "supply"], answer: 1, explanation: "Need for energy is demand for energy; it is the rising demand that drives emissions." },
      { question: "Gap 24: ... commensurate with the level of greenhouse _____ it spews out ...", options: ["structure", "paints", "emulsion", "emissions"], answer: 3, explanation: "Greenhouse emissions are the gases that are spewed out and cause warming." },
      { question: "Gap 25: ... a strategy that cannot, thus far, be termed _____.", options: ["notable", "liable", "credible", "flexible"], answer: 2, explanation: "Asking the rest of the world to take responsibility for Africa's problem is a strategy that cannot be called credible (believable)." },
  ];

  const passages = [
    { passageId: 'eng-2011-p1', passageTitle: 'JAMB 2011 — Passage I', year: Y, instruction: READ, passage: PT0, questions: P1Q },
    { passageId: 'eng-2011-p2', passageTitle: 'JAMB 2011 — Passage II', year: Y, instruction: READ, passage: PT1, questions: P2Q },
    { passageId: 'eng-2011-p3', passageTitle: 'JAMB 2011 — Passage III', year: Y, instruction: READ, passage: PT2, questions: P3Q },
    { passageId: 'eng-2011-p4', passageTitle: 'JAMB 2011 — Passage IV (cloze)', year: Y, instruction: 'The passage has gaps numbered 16 to 25. Choose the most appropriate option for each gap.', passage: PT3, questions: CLOZE },
  ];

  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const GAP = 'Choose the option that best completes the gap(s): ';
  const VOWEL = 'Choose the option that has a DIFFERENT vowel sound from the others.';
  const SAMEV = 'Choose the option that has the same vowel sound as the letter(s) in capitals: ';
  const CONS = 'Choose the option that has the same consonant sound as the letter(s) in capitals: ';
  const DIFFC = 'Choose the option that has a DIFFERENT consonant sound from the others.';
  const DIFF = 'Choose the option that has a DIFFERENT stress pattern from the others.';
  const SAMES = 'Choose the option that has the same stress pattern as the given word (stressed syllable in capitals): ';
  const STRESSOF = 'Choose the appropriate stress pattern for the word (the stressed syllable is in capitals): ';
  const FIRST = 'Choose the option that has the stress on the FIRST syllable.';
  const NEAR = 'Choose the option NEAREST in meaning to the word(s) in capitals: ';
  const MEANS = 'Select the option that best explains the information conveyed in the sentence: ';
  const EMPH = 'The word in capitals has emphatic stress. Choose the option that best fits the expression: ';
  const OPP = 'Choose the option OPPOSITE in meaning to the word(s) in capitals: ';

  const flat = [
    q(MEANS + "If he were here, it could be more fun.", ["He was expected but did not show up to make the occasion lively", "There was no fun because he was not present", "He did not show up and so the occasion lacked much fun", "He was being expected to supply more fun"], C, "'If he were here' is an unreal condition: he is not here, so the occasion is less fun than it could be."),
    q(MEANS + "The secretary said that the postponement of the meeting was due to unforeseen circumstances.", ["The date of the meeting was shifted as a result of unexpected reasons", "The meeting's date was put off for strange reasons", "The meeting was called off as a result of obstacles hitherto unknown", "The meeting broke off as a result of unusual difficulties"], A, "To postpone is to shift to a later date, and unforeseen means unexpected."),
    q(MEANS + "The hunter has a bird's-eye view of the animals.", ["He views the animals from a high position", "He views the bird's eye", "He views the birds on the tree with one eye", "He watches animals and birds closely"], A, "A bird's-eye view is a view from high above, as a flying bird sees things."),
    q(MEANS + "Even though Susan was the last in the examination, her result wasn't too different from what had been expected.", ["Her result was poor", "Her result was a disappointment", "Her result was as expected", "She had not been serious with her studies"], C, "Not too different from what had been expected means roughly as expected."),
    q(MEANS + "Mrs Adasu does all her work with more haste, less speed.", ["She accepts whatever she does with more haste and speed", "She approaches whatever she does hurriedly", "She addresses everything she does very quickly to avoid mistakes", "She does everything carefully to avoid mistakes"], D, "The proverb 'more haste, less speed' means rushing causes mistakes and delay, so she works carefully."),
    q(MEANS + "She stopped her education as her uncle left her in the lurch.", ["Her uncle deceived her", "Her uncle disinherited her", "Her uncle refused to help her", "Her uncle disrespected her"], C, "To leave someone in the lurch is to abandon them when they need help."),
    q(MEANS + "The plan to upgrade the dispensary to a general hospital did not materialize.", ["The plan did not meet the required specifications", "The arrangement did not work out as wished", "It was difficult to obtain the materials", "The materials purchased were not the right ones"], B, "A plan that does not materialize does not happen as hoped."),
    q(MEANS + "Okon's company took a hit last year.", ["His company improved last year", "His company made a huge success last year", "His company was badly damaged last year", "His company was established last year"], C, "To take a hit is to suffer a loss or damage."),
    q(MEANS + "My eldest son, who is in Lagos, is studying English.", ["Only my son is in Lagos studying English", "My only son is in Lagos studying English", "One of my sons is in Lagos studying English", "My sons are in Lagos but only one is studying English"], C, "'Eldest' shows the speaker has several sons; this one is in Lagos studying English."),
    q(MEANS + "If I went to the village, I would visit the king.", ["If I go to the village I will visit the king", "I did not go to the village and I did not visit the king", "All the times I went to the village I also visited the king", "I will visit the king when I go to the village"], B, "The past tense with 'would' marks an unreal condition: the speaker is not going to the village, so there is no visit to the king.", { keyVerdict: 'none', keyAnswer: 'B', answerNote: "Strictly, 'If I went..., I would visit' is about the present or future: the speaker is not (or is unlikely to be) going to the village. B puts it in the past ('did not go'), which is what 'If I had gone..., I would have visited' would mean. But B is the only option that keeps the idea that he does not go and does not visit the king." }),
    q(NEAR + "Since its INCEPTION in 1983, the newspaper has attracted thousands of readers.", ["renaissance", "coming", "commencement", "publication"], C, "Inception means the beginning or start of something: commencement."),
    q(NEAR + "Mrs Asio wanted her sister to stop being so DETACHED.", ["friendly", "careless", "indifferent", "passionate"], C, "Detached means aloof and unconcerned: indifferent."),
    q(NEAR + "Lantana DWELT in a ruined cottage on the hillside.", ["sat", "worked", "slept", "lived"], D, "Dwelt is the past of dwell, to live in a place."),
    q(NEAR + "The mistake brought the show to an IGNOMINIOUS end.", ["a good", "a palatable", "a disgraceful", "a satisfactory"], C, "Ignominious means shameful, disgraceful."),
    q(NEAR + "He COMPLIMENTS me on my way of doing things.", ["complements", "imitates", "disgusts", "praises"], D, "To compliment is to praise. Complement (with an e) means to complete or go well with."),
    q(NEAR + "The girl is angry with her friend who had ENSNARED her into this relationship.", ["tricked", "encouraged", "encouraged", "forced"], A, "To ensnare is to trap someone, as in a snare, by trickery. (Options B and C are printed identically on the paper.)"),
    q(NEAR + "Their new house was roofed with CORRUGATED sheets.", ["folded", "iron", "aluminium", "corrupted"], A, "Corrugated sheets are shaped into folds or ridges; the word describes the shape, not the metal."),
    q(NEAR + "The stockbroker said it was an ASTUTE move to sell the shares then.", ["a bad", "a shrewd", "an unprofitable", "an insincere"], B, "Astute means clever and sharp in judging a situation: shrewd."),
    q(NEAR + "The principal described Oche as the most TACTFUL person he had ever worked with.", ["passionate", "discrete", "hard-working", "innovate"], B, "Tactful means careful not to offend: discreet. The paper prints 'discrete' (meaning separate), a misprint for 'discreet'."),
    q(NEAR + "The old woman is suffering from DEMENTIA.", ["lucidity", "senility", "insanity", "sagacity"], B, "Dementia is loss of memory and reasoning, usually in old age: senility."),
    q(NEAR + "Some drugs have DELETERIOUS effect on a child's development.", ["debilitating", "helpful", "harmful", "healing"], C, "Deleterious means harmful."),
    q(NEAR + "Fila has always been described as BELLIGERENT.", ["beautiful", "attractive", "combative", "innocent"], C, "Belligerent means aggressive and ready to fight: combative."),
    q(NEAR + "Laraba saw a FORLORN little figure sitting outside the class.", ["wise and intelligent", "lonely and unhappy", "smart and healthy", "short and ugly"], B, "Forlorn means sad and lonely."),
    q(NEAR + "The circular SUPERSEDES all previous correspondence on the matter.", ["supports", "displaces", "eliminates", "circumvent"], B, "To supersede is to take the place of something older: displace."),
    q(NEAR + "Her problem was EXACERBATED by the loss of her father.", ["exaggerated", "solved", "aggravated", "infuriated"], C, "To exacerbate is to make worse: aggravate."),
    q(OPP + "The warring communities were COERCED into negotiating a settlement.", ["driven", "compelled", "persuaded", "pressured"], C, "To coerce is to force; the opposite is to persuade (win over without force)."),
    q(OPP + "His father served as a MERCENARY in the army.", ["preacher", "regular", "recruit", "officer"], B, "A mercenary is a hired soldier; a regular is a professional soldier of the country's own army."),
    q(OPP + "Jummai is CRUEL to her husband.", ["harsh", "brutal", "passionate", "ferocious"], C, "Harsh, brutal and ferocious are near-synonyms of cruel; only 'passionate' (probably a misprint for 'compassionate') points the other way."),
    q(OPP + "The teacher who beat the student was treated with MERCY.", ["disrespect", "contempt", "vengeance", "kindness"], C, "Mercy is forgiveness instead of punishment; vengeance is punishment in revenge."),
    q(OPP + "His wife hated his GARRULOUS attitude.", ["outspoken", "unfriendly", "reticent", "thoughtful"], C, "Garrulous means talking too much; reticent means saying little."),
    q(OPP + "'Agoshito is a CALLOW youth,' said the teacher.", ["An ignorant", "An experienced", "An idle", "An organized"], B, "Callow means young and inexperienced; the opposite is experienced."),
    q(OPP + "What you are asking me to do is a HERCULEAN task.", ["a strenuous", "a demanding", "a lovely", "an easy"], D, "A herculean task needs enormous effort; the opposite is an easy one."),
    q(OPP + "Nkechi was a NOVICE when she was first employed.", ["manager", "clerk", "supervisor", "professional"], D, "A novice is a beginner; a professional is skilled and experienced."),
    q(OPP + "'I do not trust him,' he said, in a rare moment of CANDOUR.", ["reproach", "dishonesty", "frankness", "fairness"], B, "Candour is honesty and frankness; the opposite is dishonesty."),
    q(OPP + "Mrs Akunilo looks ANAEMIC today.", ["strange", "sick", "weak", "strong"], D, "Anaemic means pale and weak from lack of blood; the opposite is strong."),
    q(OPP + "It is INCONCEIVABLE that the sun shone in the night.", ["credible", "unthinkable", "impossible", "contestable"], A, "Inconceivable means impossible to believe; the opposite is credible."),
    q(OPP + "She only gives a SUPERFICIAL impression of warmth and friendliness.", ["a strong", "a fake", "a deep", "an unrealistic"], C, "Superficial means on the surface only; the opposite is deep."),
    q(OPP + "As a PRUDENT businessman, Adayi does not leave anything to chance.", ["A frugal", "Shrewd", "careless", "unsuccessful"], C, "Prudent means careful and sensible; the opposite is careless."),
    q(OPP + "His ANTIPATHY affected the growth of his business.", ["hatred", "receptiveness", "loyalty", "hostility"], B, "Antipathy is a strong dislike or hostility; receptiveness (openness and willingness to accept) is the opposite."),
    q(OPP + "Okonkwo's LETHAL right foot did the magic in the football match.", ["Weak", "wicked", "fat", "harmless"], D, "Lethal means deadly; the opposite is harmless."),
    q(GAP + "When his car tyre _____ on the way, he did not know what to do.", ["has burst", "had burst", "bursted", "burst"], D, "The story is in the simple past ('did not know'), and burst is the same in all its forms: burst, burst, burst. 'Bursted' does not exist."),
    q(GAP + "Lami's father _____ as a gardener when he was young, but now he is a driver.", ["had been working", "used to work", "has worked", "use to work"], B, "'Used to' + verb describes a past habit or state that is no longer true."),
    q(GAP + "_____ he switches on the light, the shadow disappears.", ["Whenever", "Except", "Since", "Until"], A, "Whenever means every time: each time he switches on the light, the shadow goes."),
    q(GAP + "It is important that you clear the refuse in front of your house every _____.", ["fourtnight", "fortnight", "fourthnight", "forthnight"], B, "Fortnight (two weeks) is spelt f-o-r-t-n-i-g-h-t."),
    q(GAP + "The policemen became suspicious as the hoodlums _____ in their office.", ["ferreted", "ferreted", "ferreted about", "ferreted about"], D, "To ferret about is to search busily, poking into everything; 'ferret' alone needs an object (ferret out the truth). The paper prints A and B, and C and D, identically.", { alsoAccept: [C], keyVerdict: 'multiple', keyAnswer: 'D', answerNote: "The paper prints the same words twice: A and B are both 'ferreted', and C and D are both 'ferreted about'. 'Ferreted about' is the right form, so C is accepted as well as the key's D." }),
    q(GAP + "Suara needn't come with us, _____?", ["does she", "will she", "can she", "need she"], D, "In 'needn't come', need is a modal auxiliary, so the tag repeats it in the positive: need she?"),
    q(GAP + "Unoka _____ the whole house to find his missing wristwatch.", ["scourged", "scoured", "scored", "scouted"], B, "To scour a place is to search it thoroughly, which fits looking for a missing watch."),
    q(GAP + "Ife asked me _____.", ["what time it was", "what is it by my time", "what time is it", "what time it is"], A, "In reported questions the word order is that of a statement (it was), and the tense moves back after 'asked'."),
    q(GAP + "There are many ways to kill a rat, so we should be _____ in our approach to the task ahead of us.", ["ecletic", "eclectic", "ecleKtic", "eclectiK"], B, "Eclectic (drawing on many different methods) is spelt e-c-l-e-c-t-i-c."),
    q(GAP + "Audu took these actions purely _____ his own career.", ["on furtherance of", "in furtherance of", "to furtherance in", "in furtherance with"], B, "The fixed phrase is 'in furtherance of', meaning to advance something."),
    q(GAP + "Here is Mr Odumusu who teaches English _____ in our school.", ["pronuntiation", "pronounciation", "pronunciation", "pronountiation"], C, "Pronounce keeps its o-u, but the noun drops it: pronunciation."),
    q(GAP + "Instead of _____, she lied.", ["pleading", "her to plead", "her pleading", "plead"], A, "A preposition such as 'instead of' is followed by the -ing form: instead of pleading."),
    q(GAP + "Of the three girls, Uka is the _____.", ["so much notorious", "notorious", "naught", "naughtiest"], D, "Comparing one of three or more needs the superlative: the naughtiest."),
    q(GAP + "I wonder how he will _____ being absent from school for a long time.", ["make in", "make up", "make off", "make out"], B, "To make up (for) something is to compensate for it, here for lost school time."),
    q(GAP + "Please sit on the _____.", ["carier", "career", "carrier", "carrear"], C, "A carrier is the seat or rack at the back of a bicycle; a career is a profession."),
    q(GAP + "I want to _____ his chance to acquaint you with the latest development.", ["size", "seize", "sieze", "cease"], B, "To seize a chance is to grab it. Seize is an exception to 'i before e'."),
    q(GAP + "Getting a well-paid job nowadays is an _____ task.", ["utmost", "upbeat", "uphill", "upfield"], C, "An uphill task is a very difficult one, like climbing a hill. (The paper prints 'on' for 'an'.)"),
    q(GAP + "The secretary has no right to _____ my affairs.", ["spy from", "meddle in", "toy at", "complain into"], B, "To meddle in someone's affairs is to interfere in them."),
    q(GAP + "Bola studiously avoided _____ the question.", ["parrying", "answering", "projecting", "destroying"], B, "Avoiding answering a question means deliberately not answering it."),
    q(GAP + "The school authority dismissed him for _____ but I won't tell you about it yet.", ["certain reason", "a reason", "more reason", "a certain reason"], D, "'A certain reason' refers to a definite reason the speaker chooses not to name, which matches 'I won't tell you about it yet'.", { alsoAccept: [B], keyVerdict: 'multiple', keyAnswer: 'B', answerNote: "'A certain reason' is the usual way to mention a specific reason you are keeping back, so D fits the sentence best. The key's 'a reason' is also grammatical, so it is accepted too. A lacks an article and C makes no sense here." }),
    q(SAMEV + "bUbble", ["guy", "bull", "bumper", "gurgle"], C, "The u in bubble is the short /ʌ/, as in bumper. Bull has /ʊ/ and gurgle /ɜː/."),
    q(SAMEV + "wEIght", ["whale", "while", "wheat", "writhe"], A, "The ei in weight is /eɪ/, as the a in whale."),
    q(SAMEV + "lEAch", ["gear", "cedar", "cheer", "death"], B, "The ea in leach is the long /iː/, as the e in cedar. Gear and cheer have /ɪə/, and death /e/."),
    q(CONS + "menTion", ["that", "machine", "church", "test"], B, "The t in mention (-tion) is /ʃ/, as the ch in machine. Church has /tʃ/."),
    q(CONS + "prestiGe", ["bag", "badge", "reggae", "leisure"], D, "The g in prestige is /ʒ/, as the s in leisure.", { alsoAccept: [1], keyVerdict: 'multiple', keyAnswer: 'B', answerNote: "In British English prestige ends in /ʒ/ (pres-TEEZH), the sound of s in leisure (D). Many speakers, especially in American English, end it with /dʒ/ as in badge (B, the key's answer), so both are marked right." }),
    q(CONS + "KNot", ["cot", "keep", "norm", "king"], C, "The k in kn is silent, so kn in knot is /n/, as in norm."),
    q("Choose the option that rhymes with the given word: fuel", ["cruel", "fool", "rule", "field"], A, "Fuel /ˈfjuːəl/ and cruel /ˈkruːəl/ both end in /uːəl/."),
    q("Choose the option that rhymes with the given word: match", ["harsh", "batch", "such", "watch"], B, "Match and batch share /ætʃ/. Watch has /ɒtʃ/."),
    q("Choose the option that rhymes with the given word: sheer", ["Sheila", "care", "ear", "sherry"], C, "Sheer and ear both end in /ɪə/."),
    q(STRESSOF + "termination", ["terminaTION", "TERmination", "termiNAtion", "terMInation"], C, "Termination is stressed on the syllable before -tion: ter-mi-NA-tion."),
    q(STRESSOF + "meditative", ["meDItative", "mediTAtive", "MEditative", "meditaTIVE"], C, "In British English meditative is stressed on the first syllable: ME-di-ta-tive."),
    q(STRESSOF + "suggestible", ["suggeSTIble", "Suggestible", "suGGEstible", "suggestible"], C, "Suggestible keeps the stress of sugGEST: su-GGES-ti-ble."),
    q(EMPH + "Uche LOVES Toyota cars.", ["Who loves Toyota cars?", "What brand of car does Uche love?", "Does Uche hate Toyota cars?", "Does Uche love bicycles?"], C, "Stressing LOVES corrects a wrong verb: he loves them, he does not hate them."),
    q(EMPH + "The POLICE arrested the suspect.", ["Did the police placate the suspect?", "Who arrested the suspect?", "Who did the police arrest?", "Did the police arrest the suspect?"], B, "Stressing POLICE answers 'who did it?'."),
    q(EMPH + "Maiduguri is the CAPITAL of Borno State.", ["Is Maiduguri the capital of Plateau State?", "Which state is Maiduguri the capital of?", "Is Maiduguri a town in Borno State?", "What is the capital of Borno State?"], C, "Stressing CAPITAL corrects 'a town': it is not just a town in Borno, it is the capital."),
  ];

  QUESTION_BANK.english = QUESTION_BANK.english.concat(passages, flat);
})();
