/**
 * JAMB/UTME 2003 — USE OF ENGLISH
 * From the 2003 question paper; answers from the JAMB/UTME English Language
 * answer key 2001–2020, each checked against the paper. Where the key in
 * circulation is wrong (often a printing error) the question carries
 * keyVerdict + keyAnswer + answerNote (see english-2007.js for the scheme).
 *
 * Loaded after questions.js and before app.js.
 */
(function () {
  const Y = 2003;
  const SRC = 'JAMB UTME 2003';
  const READ = 'Read the passage carefully and answer the questions that follow.';

  const PT0 = "When man evolved a conscience, his basic relationship with the other animals began to change. Until then, they were broadly divided into those which ate him when they got the chance, those which he ate when he got the chance, and a third group which competed with him for food, or was otherwise a nuisance to him in the business of keeping alive.\n\nIn the primitive situation, man was, therefore, basically against Nature but, as the battle was progressively won, conscience crept in; the awareness of responsibility, and a failure to meet it, produced feelings of guilt. Those who live in cities and need no longer do battle against Nature are nowadays most actively for Nature.\n\nAt this time, something like a thousand kinds of animals (vertebrate animals) can be said to be in danger of extinction. A few of them have been reduced to this precarious position by extensive killing but the majority are disappearing only as fast as the particular kind of country they need for existence is itself disappearing: and all this at the hands of man, as often as not by mistake.\n\nThere are three species of turtles whose future survival is menaced by the demand for turtle soup, which would hardly justify the extermination of a giant reptile whose family has existed for 200 million years. Leopards are in jeopardy because of the fashion for their skins. As they get rarer, the prices rise and, as leopard skin coats become more expensive, the demand increases. No species can long survive the price of N60,000 which a half grown baby leopard now carries on its skin. And crocodiles, the longest surviving reptiles, are now dwindling alarmingly as a result of the fashion in crocodile skin for ladies' handbags and men's shoes.\n\nThe human population explosion spreads mankind across the land surfaces of the earth at an alarming rate. There will be twice as many of us before most of us are dead. Does this mean no room for wild animals? Of course not. With ingenuity and forethought, a place can be kept for them. To destroy their habitat is as unnecessary as it would be to pull down a great cathedral in order to grow potatoes on the site. A campaign to save what remains is the concern of a new kind of Noah's Ark \u2013 the World Wildlife Fund. It does not believe that all is lost.";
  const PT1 = "The 2002 World Cup Competition, also called Korea/Japan 2002, kicked off with a match between the defending champions, France, and the Senegalese national team from Africa. Nobody had given the Senegalese any chance against the star studded defending champions but the 1-0 scoreline in favour of Senegal showed that African football can no longer be taken for granted.\n\nThis shocking defeat of France had raised Africa's hopes of going beyond the first round of the tournament. So when the Super Eagles of Nigeria filed out against Argentina on the morning of Sunday, June the second, 2002, many Nigerian football enthusiasts delayed attending church service to watch the match live on television. As expected, the Super Eagles put up strong resistance to the Argentinian challenge and the day would not have ended on a somber note for Nigerians if the momentum had been sustained throughout the match.\n\nThe hope of going beyond the first round, though precarious, was very much alive as the Eagles were expected to defeat their next opponents, Sweden and England. But some shortcomings in the Nigerian national team needed to be rectified to brighten their chances against their next opponents.\n\nFirst, the defence needed to be strengthened to prevent the opponents from incessantly terrorizing the goalkeeper. Then the strikers also needed to improve on their lackluster performance against Argentina, since every Nigerian expected them to overwhelm their next opponents in the opening rounds. Lastly, rather than gamble with unfit players, a more creative use of the reserves would be necessary to smooth the way to the next round.\n\nIf World Cup debutants, Senegal, could nurse the hope of playing in the knock-out stages of the tournament, then the Eagles should soar instead of being intimidated by big names, for no team is invincible.";
  const PT2 = "Attitudes towards the smoking of cigarettes and the consumption of alcohol may be used to illustrate typical African ethics. Apart from the fact that smoking has now been linked with lung cancer disease, the African moralist has always regarded smoking as an indication of moral degradation. A number of people have accepted the moralist idea on smoking. Some have refrained from smoking, and those who could influence others, such as parents and religious leaders, have also exerted their influence to prevent others from smoking. On the other hand, a good many people have remained indifferent to the moralist view and have continued to smoke. The same argument has been applied to the consumption of alcohol. The African moralist, basing his judgment on the behaviour of a few alcoholics, tends to regard the habit of taking alcohol as a sign of wretchedness. The moralist holds the view that anybody who forms the habit of consuming alcohol will never do well in life. While this may be true in respect of a few people in the society, the fear of the moralist has not been justified. However, the economist is primarily interested in the habit of smoking and the consumption of alcohol in so far as they give satisfaction to smokers and drinkers and so generate supply of and demand for tobacco and alcohol. The economist is interested in knowing how many packets of cigarettes are consumed and to what extent an increase or fall in consumption could affect production that is, supply. Similarly, he is interested in how much beer is consumed and how the supply of beer will adjust to the demand for it. He examines the habits and the pressures which can lead to the readjustment of wants and the reallocation of resources to cover the wants.\n\nSome moral principles associated with religion tend to lead on to economic problems. Followers of certain religions are expected not to consume pork, take alcohol or smoke tobacco. Devotees of some religious groups, on the other hand, can eat pork while others are expected to abstain from alcohol and smoking. Strict observance of these moral rules could cripple the breweries, the cigarette factories and some businesses.\n\nHowever, there seems to be a growing number of alcohol consumers and cigarette smokers \u2014 a development which should be of interest to the economist.";
  const PT3 = "A prepared speech is not easy to deliver, especially if it is not written by the presenter. A ___(16)___ delivery is one in which the speech has been written out word for word and is read to ___(17)___. This kind of delivery is usually reserved for very ___(18)___ occasions when exact wording is ___(19)___, such as the State of the Union Address or speeches before the United Nations General ___(20)___. The primary advantage is that the speech may be highly ___(21)___ in terms of word choice, turns of phrase, and development of ideas. The main disadvantage is that this type of delivery is difficult to do well. Reading aloud with meaningful ___(22)___ inflection requires the speaker to be very familiar with the text. If not, the words will come out in a choppy, expressionless way. Such poor delivery could destroy any ___(23)___ effects created by the carefully chosen ___(24)___. Lack of familiarity with the ___(25)___ could also prevent the speaker from maintaining eye contact with people being addressed.";

  const P1Q = [
      { question: "The basic causes of the elimination of certain animals from the earth include", options: ["man's decision to live in cities and the development of large farmlands", "extensive killing of animals and the fast disappearance of their favourable habitats", "man's penchant for meat and the sale of animals for meat and hides", "a deliberate battle against Nature and the quest for leopard skin"], answer: 1, explanation: "Some animals have been reduced 'by extensive killing but the majority are disappearing only as fast as the particular kind of country they need for existence is itself disappearing'." },
      { question: "From the passage, the attitude of the writer can be described as", options: ["partial", "optimistic", "indifferent", "pessimistic"], answer: 1, explanation: "Asked whether there is no room for wild animals, he answers 'Of course not', and says the campaign 'does not believe that all is lost'." },
      { question: "The expression 'when man evolved a conscience' means when", options: ["man developed an awareness of right and wrong", "man's intellect improved tremendously", "man acquired new habits", "man became a critical creature"], answer: 0, explanation: "A conscience is the inner sense of right and wrong; the passage links it to 'the awareness of responsibility' and 'feelings of guilt'." },
      { question: "Which of the following statements is true according to the passage?", options: ["Man kills animals only when he can afford to do so.", "Man cannot spare those animals that eat his kind.", "Man eats all categories of animals.", "Man poses the greatest threat to Nature."], answer: 3, explanation: "Animals are disappearing 'at the hands of man', through killing, fashion and the destruction of their habitats." },
      { question: "The sentence 'There will be twice as many of us before most of us are dead' means", options: ["some increase in human and animal population growth rates", "mankind is fast spreading across the earth", "many of us will die as a result of population explosion", "the population growth rate will double before our death"], answer: 3, explanation: "Within the lifetime of most people alive now, the human population will double." },
  ];
  const P2Q = [
      { question: "Which of the following captures the writer's suggestion on how the Eagles could improve their performance in subsequent matches?", options: ["Better goalkeeping, a better attack and a stronger midfield.", "Replacement of injured players, stronger attackers and a rugged defence.", "Good coaching, more strikers and more defenders.", "Fair officiating, good goalkeeping and fast players."], answer: 1, explanation: "The writer asks for a stronger defence, better strikers, and creative use of the reserves 'rather than gamble with unfit players'." },
      { question: "A suitable title for this passage is", options: ["African Teams in the 2002 World Cup", "The FIFA Korea/Japan 2002", "The Nigerian and the Senegalese Teams", "The Eagles in World Cup 2002"], answer: 3, explanation: "Senegal is mentioned only to set the scene; the passage is mainly about the Super Eagles' performance and chances at the 2002 World Cup." },
      { question: "From the argument in the last paragraph, it can be concluded that the Eagles were", options: ["more experienced than the Senegalese team", "not as strong as the Senegalese team", "more timid and goal-shy than their opponents", "not sure of getting to the next round of the tournament"], answer: 0, explanation: "If 'World Cup debutants, Senegal' could hope to reach the knock-out stages, then the Eagles, who were not debutants, should do even better: they had more experience." },
      { question: "The word 'debutants', as used in the passage, means", options: ["hard-fighters", "under-dogs", "first-timers", "giant killers"], answer: 2, explanation: "A debutant is someone appearing for the first time; 2002 was Senegal's first World Cup." },
      { question: "From the passage, it can be concluded that the writer", options: ["was optimistic about the chances of the Eagles", "did not fancy the Eagles' chances", "was non-committal about the chances of the Eagles", "was certain about the Eagles' chances"], answer: 0, explanation: "He says the hope 'was very much alive' and that the Eagles 'should soar', but he also lists shortcomings, so he is hopeful, not certain." },
  ];
  const P3Q = [
      { question: "The positions maintained by the moralist and the economist can be described as being", options: ["at variance", "very agreeable", "quite indifferent", "very passionate"], answer: 0, explanation: "The moralist condemns smoking and drinking, while the economist values them for the demand and supply they create: their positions differ." },
      { question: "Which of the following statements is true according to the passage?", options: ["People who drink or smoke surely die of cancer.", "Everyone ignores the moralist view on drinking and smoking.", "Smoking and drinking may have positive effects on the economy.", "Total abstinence from drinking and smoking is a religious obligation."], answer: 2, explanation: "They 'generate supply of and demand for tobacco and alcohol', and strict abstinence 'could cripple the breweries, the cigarette factories and some businesses'." },
      { question: "It can be concluded from the passage that morality, religion and economy are", options: ["clearly interconnected", "certainly different", "somewhat interconnected", "certainly unrelated"], answer: 0, alsoAccept: [2], explanation: "'Some moral principles associated with religion tend to lead on to economic problems': the three are linked.", keyVerdict: 'corrected', keyAnswer: 'B', answerNote: "The passage's point is that they are linked: moral principles 'associated with religion' lead on to 'economic problems', and obeying them could cripple breweries and cigarette factories. So they are interconnected (A, or C if you read 'some' and 'tend to' as only partly), not 'certainly different'." },
      { question: "The view expressed by the writer in the last paragraph is that", options: ["the number of alcoholics and smokers is certainly increasing", "more people now abstain from drinking and smoking", "more people appear to take to drinking and smoking", "sales of alcohol and tobacco products have improved tremendously"], answer: 2, explanation: "'There seems to be a growing number of alcohol consumers and cigarette smokers.' 'Seems' matches 'appear'.", keyVerdict: 'corrected', keyAnswer: 'D', answerNote: "The last paragraph says only that 'there seems to be a growing number of alcohol consumers and cigarette smokers'. It says nothing about sales improving 'tremendously'. C restates it, including the hedge ('seems' = 'appear'). A is too certain and says 'alcoholics' rather than consumers." },
      { question: "According to the passage, 'the moralist idea' is that", options: ["it is typically African not to smoke cigarettes", "people should accept a point of view only when they are convinced", "smoking is not good but a little alcohol may be permitted", "the smoking of cigarettes is bad and unacceptable"], answer: 3, explanation: "The moralist 'has always regarded smoking as an indication of moral degradation'." },
  ];
  const CLOZE = [
      { question: "Gap 16: A _____ delivery is one in which the speech has been written out word for word and is read.", options: ["document", "free", "manuscript", "quantum"], answer: 2, explanation: "A speech written out in full and read aloud is a manuscript speech (manuscript delivery)." },
      { question: "Gap 17: …written out word for word and is read to _____.", options: ["a gathering", "a conference", "a congregation", "an audience"], answer: 3, explanation: "The listeners to a speech are its audience. A congregation is a church gathering." },
      { question: "Gap 18: This kind of delivery is usually reserved for very _____ occasions.", options: ["formal", "genuine", "impromptu", "guaranteed"], answer: 0, explanation: "The examples (State of the Union, the UN) are formal occasions. Impromptu means unprepared, the opposite of a manuscript speech." },
      { question: "Gap 19: …occasions when exact wording is _____.", options: ["conclusive", "critical", "reportive", "speculative"], answer: 1, explanation: "On such occasions exact wording is critical (very important), so the speech is read word for word." },
      { question: "Gap 20: …speeches before the United Nations General _____.", options: ["Negotiation", "Organization", "Assembly", "Audience"], answer: 2, explanation: "The body is the United Nations General Assembly." },
      { question: "Gap 21: The primary advantage is that the speech may be highly _____ in terms of word choice, turns of phrase, and development of ideas.", options: ["polished", "advanced", "analogous", "discreet"], answer: 0, explanation: "A speech written out in advance can be carefully refined, i.e. polished." },
      { question: "Gap 22: Reading aloud with meaningful _____ inflection requires the speaker to be very familiar with the text.", options: ["anticipatory", "profuse", "bifocal", "vocal"], answer: 3, explanation: "Inflection of the voice is vocal inflection: the rise and fall of the voice." },
      { question: "Gap 23: Such poor delivery could destroy any _____ effects created by the carefully chosen words.", options: ["interactive", "restrictive", "positive", "decisive"], answer: 2, explanation: "Poor delivery destroys the good (positive) effects the careful wording would have had." },
      { question: "Gap 24: …effects created by the carefully chosen _____.", options: ["language", "slang", "dialect", "rhetoric"], answer: 0, explanation: "The writer has been talking about 'word choice' and 'turns of phrase', i.e. carefully chosen language. Slang and dialect don't suit formal speeches." },
      { question: "Gap 25: Lack of familiarity with the _____ could also prevent the speaker from maintaining eye contact.", options: ["exchange", "text", "note", "context"], answer: 1, explanation: "The passage already said reading well 'requires the speaker to be very familiar with the text'." },
  ];

  const passages = [
    { passageId: 'eng-2003-p1', passageTitle: 'JAMB 2003 — Passage I', year: Y, instruction: READ, passage: PT0, questions: P1Q },
    { passageId: 'eng-2003-p2', passageTitle: 'JAMB 2003 — Passage II', year: Y, instruction: READ, passage: PT1, questions: P2Q },
    { passageId: 'eng-2003-p3', passageTitle: 'JAMB 2003 — Passage III', year: Y, instruction: READ, passage: PT2, questions: P3Q },
    { passageId: 'eng-2003-p4', passageTitle: 'JAMB 2003 — Passage IV (cloze)', year: Y, instruction: 'The passage has gaps numbered 16 to 25. Choose the most appropriate option for each gap.', passage: PT3, questions: CLOZE },
  ];

  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const GAP = 'Choose the option that best completes the gap(s): ';
  const VOWEL = 'Choose the option that has a DIFFERENT vowel sound from the others.';
  const SAMEV = 'Choose the option that has the same vowel sound as the letter(s) in capitals: ';
  const CONS = 'Choose the option that has the same consonant sound as the letter(s) in capitals: ';
  const DIFFC = 'Choose the option that has a DIFFERENT consonant sound from the others.';
  const DIFF = 'Choose the option that has a DIFFERENT stress pattern from the others.';
  const SAMES = 'Choose the option that has the same stress pattern as the given word (stressed syllable in capitals): ';
  const FIRST = 'Choose the option that has the stress on the FIRST syllable.';
  const NEAR = 'Choose the option NEAREST in meaning to the word(s) in capitals: ';
  const MEANS = 'Select the option that best explains the information conveyed in the sentence: ';
  const EMPH = 'The word in capitals has emphatic stress. Choose the option that best fits the expression: ';
  const OPP = 'Choose the option OPPOSITE in meaning to the word(s) in capitals: ';

  const flat = [
    q(MEANS + "In spite of his humble beginning, Audu now throws his weight around.", ["Audu is arrogant despite his simple upbringing.", "Despite his obvious poverty, Audu is a proud man.", "His noble birth notwithstanding, Audu is a corrupt man.", "From his poor background, Audu is now a rich man."], A, "To throw one's weight around is to behave in a bossy, arrogant way; a humble beginning is a simple upbringing."),
    q(MEANS + "Ngozi has always considered her father to be an impassioned man.", ["Her father is a very lively man.", "Her father is an emotional man.", "Her father is a disciplined man.", "Her father is a very strict man."], B, "Impassioned means full of strong feeling, i.e. emotional."),
    q(MEANS + "The elders rebuked Olu for taking issue with his principal.", ["Olu was cautioned for shouting at his principal.", "Olu was scolded for acting in collusion with his principal.", "Olu was reprimanded for arguing with his principal.", "Olu was blamed for issuing a statement denying his principal."], C, "To rebuke is to reprimand, and to take issue with someone is to argue with or challenge them."),
    q(MEANS + "The manager paid us in hard currency.", ["We were paid in new notes.", "We were paid in foreign currency.", "We were paid in dollars and pound sterling.", "We were paid in a strong and stable currency."], D, "Hard currency is money from a strong, stable economy that is widely accepted, not simply any foreign money."),
    q(MEANS + "If he went to London, he would see the Queen.", ["When he goes to London, he will see the Queen.", "He did not go to London and did not see the Queen.", "He did not see the Queen when he went to London.", "He would like to see the Queen when he goes to London."], B, "'If + past, would + verb' describes something unreal: he is not actually going, so he won't see the Queen. B is the closest option.", { keyVerdict: 'none', keyAnswer: 'B', answerNote: "Strictly, 'If he went..., he would see' is about the present or future: he is not (or is unlikely to be) going to London. B puts it in the past ('did not go'), which is what 'If he had gone..., he would have seen' would mean. But B is the only option that keeps the idea that he does not go and does not see the Queen." }),
    q(OPP + "Only those who are GULLIBLE fall victim to his trickery.", ["saucy", "devastated", "courteous", "astute"], D, "Gullible means easily deceived; astute means shrewd and hard to fool."),
    q(OPP + "He is well known for his INORDINATE ambition.", ["excessive", "passionate", "moderate", "sound"], C, "Inordinate means excessive, so its opposite is moderate."),
    q(OPP + "Students could be TIMID.", ["friendly", "bold", "covetous", "pugnacious"], B, "Timid means shy and lacking courage; bold is the opposite."),
    q(OPP + "The witness decided to CONCEAL the evidence.", ["divulge", "hide", "destroy", "pugnacious"], A, "To conceal is to hide; to divulge is to reveal."),
    q(OPP + "The members of the congregation were INSPIRED by the sermon.", ["bewitched", "enthralled", "disenchanted", "disorientated"], C, "Inspired means filled with enthusiasm; disenchanted means disappointed and no longer enthusiastic."),
    q(OPP + "Agbenu was ECSTATIC about her result.", ["dispassionate", "sad", "pessimistic", "mad"], B, "Ecstatic means overjoyed; sad is the opposite."),
    q(OPP + "The labour leader's RECALCITRANT stance was applauded.", ["stubborn", "flexible", "uncompromising", "well informed"], B, "Recalcitrant means stubbornly refusing to obey or cooperate; flexible is the opposite."),
    q(OPP + "A cool bath in a hot weather can be truly INVIGORATING.", ["devastating", "unpalatable", "debilitating", "disgusting"], C, "Invigorating means giving energy; debilitating means draining energy and weakening."),
    q(OPP + "I am LOATH to do the assignment.", ["willing", "unwilling", "waiting", "dying"], A, "Loath means reluctant or unwilling; its opposite is willing."),
    q(OPP + "Toyin is married to AN IMPATIENT, self-centered man.", ["a fretful", "a tolerant", "an edgy", "a tolerable"], B, "An impatient person is easily annoyed; a tolerant one puts up with things calmly. 'Tolerable' means bearable, a different word."),
    q(OPP + "GREGARIOUS animals can be found in the zoo.", ["Various", "Wild", "Lonely", "Tame"], C, "Gregarious animals live in groups; the opposite is solitary, and 'lonely' is the closest option."),
    q(OPP + "The doctor examined the patient PAINSTAKINGLY.", ["perfunctorily", "professionally", "painfully", "carefully"], A, "Painstakingly means with great care; perfunctorily means carelessly, just as a routine."),
    q(OPP + "The company has continued to MONOPOLIZE the distribution of the products.", ["centralize", "specialize", "liberalize", "regularize"], C, "To monopolize is to keep sole control; to liberalize is to open it up to others."),
    q(OPP + "A CONSERVATIVE estimate put the number of missing persons at forty.", ["A rough", "An accurate", "A primitive", "An incorrect"], B, "A conservative estimate is a cautious, approximate figure (deliberately on the low side); its opposite here is an accurate count."),
    q(OPP + "The agency has sworn to deal with all the APOSTLES of confederation.", ["proponents", "protagonists", "apostates", "opponents"], D, "Apostles of an idea are its supporters; the opposite is its opponents."),
    q(NEAR + "The leader has the UNSTINTING support of his party.", ["unsparing", "laudable", "uninspiring", "cautious"], A, "Unstinting means given freely and generously, i.e. unsparing."),
    q(NEAR + "The party supporters VILIFIED the Chairman for the role he played in the crisis that rocked the party.", ["elected", "challenged", "condemned", "impeached"], C, "To vilify is to speak about someone in an abusive, condemning way."),
    q(NEAR + "The company is to SHED three thousand staff this year.", ["demote", "lay off", "throw up", "placate"], B, "A company that sheds staff lays them off (dismisses them)."),
    q(NEAR + "There was A GLUT OF oil on the market.", ["a variety of", "an accumulation of", "an abundance of", "an increase in"], C, "A glut is an excessive supply, more than is needed: an abundance."),
    q(NEAR + "A few years ago, nobody would have believed that the economy would TURN AROUND.", ["deteriorate", "improve", "stagnate", "change"], B, "When an economy turns around, it goes from doing badly to doing well, i.e. improves."),
    q(NEAR + "Before announcing his retirement, Ochima resolved to SETTLE ON ACCOUNT WITH the bank.", ["pay back all he owes", "close his account with", "retire his loans from", "get back at"], A, "To settle an account is to pay what one owes."),
    q(NEAR + "The boys knew that a storm was IMMINENT.", ["possible", "impending", "threatening", "encroaching"], B, "Imminent means about to happen, i.e. impending."),
    q(NEAR + "The nurse was in favour of VOLUNTARY EUTHANASIA.", ["a painless death", "a simple operation", "a sleeping pill", "a major operation"], A, "Euthanasia is ending the life of a suffering patient painlessly ('mercy killing')."),
    q(NEAR + "The CYNICS feared that the nation's nascent democracy would fail.", ["pessimists", "delinquents", "critics", "illusionists"], A, "Cynics expect the worst of people and things, like pessimists."),
    q(NEAR + "The ESSENCE of governance is to seek the good and well-being of the majority of the people.", ["importance", "goal", "characteristic", "secret"], A, "The essence of something is its most important part, what it is fundamentally about."),
    q(NEAR + "From what she said, one may INFER that she does not like the course.", ["suppose", "realize", "deduce", "agree"], C, "To infer is to work something out from evidence, i.e. to deduce."),
    q(NEAR + "He shared his room with a person whose behaviour was quite NAUSEATING.", ["disrespectful", "disgraceful", "discouraging", "disgusting"], D, "Nauseating means sickening, i.e. disgusting."),
    q(NEAR + "The carpenter built a COMMODIOUS wardrobe.", ["gigantic", "small", "spacious", "wide"], C, "Commodious means roomy, i.e. spacious."),
    q(NEAR + "Publishing as a business venture has become A HOT POTATO in Nigeria.", ["unpleasant", "profitable", "unacceptable", "expensive"], A, "A hot potato is a difficult, awkward issue that people would rather not handle. Of the options, unpleasant is the closest."),
    q(NEAR + "The man's story sounded PLAUSIBLE to his audience.", ["fantastic", "credulous", "credible", "entertaining"], C, "Plausible means seeming reasonable and believable, i.e. credible. Credulous means too ready to believe."),
    q(GAP + "'I can't stand people prying into my private life', Ladi said. '_____,' agreed Agbenu.", ["Me neither", "Me too", "I also", "Likewise myself"], A, "Agreeing with a negative statement ('I can't stand') takes 'Me neither' (or 'Neither can I')."),
    q(GAP + "The sergeant spoke to me in a _____ manner.", ["coerce", "coarse", "course", "causal"], B, "Coarse means rough and rude. Course is a route or programme, coerce is a verb (to force), and causal relates to cause."),
    q(GAP + "The reason why he was not offered admission was _____ his results could not be found.", ["because", "that", "when", "owning to"], B, "'The reason... was that...' is correct; 'the reason... was because' repeats the idea of cause."),
    q(GAP + "Adika _____ a message from the club regularly.", ["receive", "receives", "has received", "had received"], B, "'Regularly' signals a habit, which takes the simple present; Adika is singular, so 'receives'."),
    q(GAP + "Three quarters of the people in the village _____ killed but only half of their huts _____ affected.", ["were/was", "were/were", "was/was", "was/were"], B, "With fractions, the verb agrees with the noun after 'of': 'three quarters of the people were', and 'half of their huts were' (huts is plural)."),
    q(GAP + "If you saw the photograph of the man, _____ you be able to identify him?", ["can", "will", "would", "could"], C, "'If + past simple' (saw) pairs with 'would' in the main clause."),
    q(GAP + "It is bad to take _____ property without permission.", ["someone else's", "someone's else", "someone's else's", "someone elses'"], A, "The possessive 's goes at the end of the whole phrase: someone else's."),
    q(GAP + "As Obande does not know anyone in this city, he hopes that some kind _____ will put him up for the night.", ["men", "individuals", "man", "inhabitants"], C, "'Some' with a singular noun means 'an unknown one', and 'will put him up' suggests one person: some kind man."),
    q(GAP + "Be careful not to _____ this money.", ["lose", "loose", "loss", "lost"], A, "Lose (verb) means to misplace. Loose means not tight, loss is a noun, and lost is the past form."),
    q(GAP + "How is the new editor _____ on with his work?", ["pushing", "going", "getting", "moving"], C, "'To get on with' something means to make progress with it."),
    q(GAP + "Nowadays, many graduates are not well disposed to teaching, _____", ["do they?", "they are?", "aren't they?", "are they?"], D, "A negative statement ('are not') takes a positive tag with the same verb: are they?"),
    q(GAP + "The armed robbers went into the house and robbed the three _____.", ["women's occupants", "women occupants", "woman occupants", "woman's occupants"], B, "When man/woman is used before a plural noun, it also becomes plural: women occupants (like women doctors)."),
    q(GAP + "It is often _____ that inflation _____ from too much money chasing very few goods.", ["say/resulted", "said/result", "said/results", "say/result"], C, "Passive 'it is often said', and 'inflation' is singular, so 'results'."),
    q(GAP + "If you would do me this favour, I _____ be very grateful.", ["will", "shall", "would", "should"], B, "'I shall be grateful if you would...' is a standard formal British phrase. 'I would/should be grateful' is also correct.", { alsoAccept: [C, D], keyVerdict: 'multiple', keyAnswer: 'B', answerNote: "The key's 'shall' is right: 'I shall be grateful if you would...' is a standard formal phrase. But 'would' (C) and 'should' (D, the formal British first-person form of 'would') are just as correct after 'If you would...', so all three are marked right. Only 'will' (A) is out." }),
    q(GAP + "I have the _____ of meeting the President.", ["privilege", "priviledge", "privelege", "previlege"], A, "The spelling is p-r-i-v-i-l-e-g-e: privilege (no d)."),
    q(GAP + "My classmate, _____ I haven't seen for years, wrote to me last week.", ["that", "whose", "whom", "which"], C, "'I haven't seen him' → the object form whom. 'That' can't introduce a clause set off by commas."),
    q(GAP + "Four weeks _____ enough for the police to conclude their investigation.", ["has been", "are", "were", "is"], D, "A period of time treated as one amount takes a singular verb: four weeks is enough."),
    q(GAP + "The woman is one of the _____ of the society.", ["elitists", "elites", "elite", "elitist"], B, "'One of the' needs a plural noun: one of the elites. (Elitists are people who believe in rule by an elite.)"),
    q(GAP + "The doctor asked the patient what _____.", ["is the problem", "the problem was", "the problem is", "is your problem"], B, "In reported questions the word order is that of a statement, and the tense shifts back: what the problem was."),
    q(GAP + "He put _____ in a basket.", ["a white dozen eggs", "dozen white eggs", "a dozen white eggs", "white dozen eggs"], C, "Number words come before adjectives: a dozen white eggs."),
    q(GAP + "Idakwo ran _____ miss the train.", ["lest he almost", "lest he will", "lest he should", "lest he may"], C, "'Lest' (for fear that) is followed by 'should' + base verb, or by the bare verb."),
    q(GAP + "Course _____ writers are to reflect local colour.", ["material", "materials", "material's", "materials'"], B, "The writers of course materials are 'course materials writers' (as in 'materials writer'), or 'course material writers'.", { alsoAccept: [A], keyVerdict: 'corrected', keyAnswer: 'D', answerNote: "When one noun describes another (course books, materials writers), no apostrophe is used. 'Materials writers' is the usual term for people who write teaching materials, so B is right, and the singular 'material' (A) is also acceptable. The key's 'materials'' (D) wrongly adds a possessive apostrophe." }),
    q(GAP + "It was a free-for-all and the students were blamed for taking the law _____.", ["into their hands", "in their hands", "into their own hands", "in their own hands"], C, "The idiom is 'to take the law into one's own hands': to punish someone yourself instead of going to the authorities."),
    q(GAP + "Ali plays _____ violin with remarkable skill.", ["their", "some", "a", "the"], D, "We use 'the' with musical instruments: play the violin, play the piano."),
    q(GAP + "The candidate's charisma should be a _____ factor in winning the election.", ["determinable", "determining", "determinant", "determinate"], B, "A determining factor is one that decides the result. Determinable means able to be determined, and determinate means fixed."),
    q(SAMEV + "cOLOnel", ["gaol", "colony", "golden", "girl"], D, "Colonel is pronounced like 'kernel' (/ˈkɜːnəl/): its 'olo' has the /ɜː/ sound of girl."),
    q(SAMEV + "tEnd", ["jeopardy", "turned", "earned", "caned"], A, "The e in tend is the short /e/. The 'eo' in jeopardy (JEP-ardy) is also /e/."),
    q(SAMEV + "markET", ["get", "mortgage", "enter", "bachelor"], B, "The unstressed -et in market is pronounced /ɪt/, with the short /ɪ/ heard in the -age of mortgage (/ˈmɔːɡɪdʒ/)."),
    q(VOWEL, ["dear", "fair", "bear", "there"], A, "Dear has /ɪə/ (as in ear); fair, bear and there all have /eə/ (as in air)."),
    q(VOWEL, ["hope", "cost", "coast", "won't"], B, "Cost has the short /ɒ/; hope, coast and won't have /əʊ/."),
    q(VOWEL, ["naught", "north", "spot", "law"], C, "Spot has the short /ɒ/; naught, north and law have the long /ɔː/."),
    q(CONS + "coNcrete", ["attend", "anxious", "concern", "consider"], B, "Before a /k/ sound, n is pronounced /ŋ/ (as in sing): concrete is /ˈkɒŋkriːt/. Anxious (/ˈæŋkʃəs/) has the same /ŋ/."),
    q(CONS + "CHalet", ["college", "chemical", "chairman", "champagne"], D, "In chalet (a French word), ch is /ʃ/ (sh), as in champagne. In chemical it is /k/, in chairman /tʃ/, and college has no ch."),
    q(CONS + "teeTH", ["though", "taught", "thought", "tank"], C, "The th in teeth is voiceless /θ/, as in thought. The th in though is voiced /ð/."),
    q(DIFFC, ["shoe", "ocean", "chef", "chief"], D, "Chief starts with /tʃ/; shoe, ocean (the c) and chef all have /ʃ/."),
    q(DIFFC, ["laugh", "off", "wife", "of"], D, "The f in 'of' is /v/; laugh, off and wife all end in /f/."),
    q(SAMES + "ceMENT", ["employ (noun)", "interest", "perfect (adjective)", "include"], D, "ceMENT and inCLUDE are stressed on the second syllable. INterest and PERfect (adjective) are stressed on the first. The noun employ ('in his employ') is also stressed on the second syllable, emPLOY.", { alsoAccept: [A], keyVerdict: 'multiple', keyAnswer: 'D', answerNote: "Unlike most noun/verb pairs, 'employ' keeps its stress on the second syllable as a noun too (emPLOY, as in 'in the employ of the bank'), so A matches ceMENT as well as inCLUDE (D)." }),
    q(SAMES + "TYPist", ["rebel (verb)", "superb", "refuse (noun)", "propose"], C, "TYPist is stressed on the first syllable, like the noun REFuse (rubbish). The verb reBEL, suPERB and proPOSE are stressed on the second."),
    q(EMPH + "My MOTHER served rice and fresh fish stew for dinner.", ["What kind of meal did your mother serve for dinner?", "Did your mother serve rice and fresh fish stew for lunch?", "What kind of stew did your mother serve for dinner?", "Who served rice and fresh fish stew for dinner?"], D, "Stressing MOTHER answers the question of who did it: 'Who served rice and fresh fish stew for dinner?'"),
    q(EMPH + "The President SPOKE to the press.", ["Who spoke to the press?", "Are these the pressmen that the president spoke to?", "Did the President speak to the press?", "Did the President write to the press?"], D, "Stressing SPOKE corrects the way he communicated: 'Did the President write to the press?' No, he SPOKE."),
  ];

  QUESTION_BANK.english = QUESTION_BANK.english.concat(passages, flat);
})();
