/**
 * JAMB/UTME 2005 — USE OF ENGLISH
 * From the 2005 question paper; answers from the JAMB/UTME English Language
 * answer key 2001–2020, each checked against the paper. Where the key in
 * circulation is wrong (often a printing error) the question carries
 * keyVerdict + keyAnswer + answerNote (see english-2007.js for the scheme).
 *
 * Loaded after questions.js and before app.js.
 */
(function () {
  const Y = 2005;
  const SRC = 'JAMB UTME 2005';
  const READ = 'Read the passage carefully and answer the questions that follow.';

  const PT0 = "It is not possible to admit that there is life of any sort on the moon, it is a world that is completely and utterly dead, a sterile mountainous waste on which, during the heat of the day, the sun blazes down with relentless fury, but where during the long night the cold is so intense that it far surpasses anything ever experienced on earth.\n\nThese hard facts are conveniently ignored by those who believe that it would be possible to shoot a rocket containing human beings to the moon, from which the human explorers could land and explore some portion of the moon's surface. The explorers would need to be encased in airtight suits and provided with oxygen apparatus to enable them to breathe. Even supposing that they could protect themselves against the great heat by day and extreme cold at night, a worse fate might be in store for them unless their suits were completely bullet-proof. For they would be in danger of being shot by a shooting star. The average shooting star or meteor, which gives so strongly the impression of a star falling from the sky, is a small fragment of matter, usually smaller than a pea and often no longer than a grain of sand. Space is not empty but contains great numbers of such fragments. The earth, in its motion round the sun, meets many of these fragments, which enter the atmosphere at a speed many times greater than that of a rifle bullet. The meteor, rushing through the air, becomes intensely heated by friction and is usually completely vapourised before it penetrates within a distance of twenty miles from the surface of the earth. Many millions of these fragments enter our atmosphere in the course of a day, but the atmosphere protects us from them. On the moon, however, they fall to the surface and so great is their number that the lunar explorers would run a considerable risk of being hit.\n\nThe difficulties that would have to be encountered by anyone who attempted to explore the moon \u2013 assuming that it was possible to get there \u2013 would be incomparably greater than those that have to be faced in the endeavour to reach the summit of Mount Everest. In two respects only would the lunar explorers have the advantage. In the first place, movement would be less fatiguing because gravitational pull of the moon is not very great, the weight of the moon being only about one eightieth of that of the earth. The second advantage the lunar explorer would have over the climbers on Mount Everest would be the absence of strong winds to contend with. The moon having no atmosphere, there can be no wind; nor, of course, can there be any noise, for sound is carried by the air. The moon is a world that is completely still and where utter silence prevails.";
  const PT1 = "The Second World African Festival of Arts and Culture (FESTAC) was staged in Nigeria in 1977. At the colloquium organised during the festival, various issues affecting the development of the black world, including the inability of most independent African nations to make a clean break with the language of colonialism, were discussed by seasoned intellectuals. It was resolved then that each African country should assign important functions to its major indigenous languages in order to facilitate the selection of one of them to replace the colonial language at the national level. This, it was hoped, could bring about the much-needed unity and national integration. Besides, since the different European languages in use were considered to be unsuitable for the expression of African cultural values, African countries were urged to promote their cultures in their local languages.\n\nAs they put it, no language could effectively express an experience that does not occur in that language; therefore, a campaign should be mounted, as a matter of urgency, to give impetus to the promotion of African languages. The media in each country, it was suggested, should spearhead the quest for an indigenous national language by educating, motivating and mobilising their government and people towards the selection of an appropriate local language. This, in itself, was a recognition that the media \u2013 a term usually applied in reference to all the important agencies of mass information and entertainment, like the press, the radio and the television \u2013 wield tremendous and immeasurable power through their ability to mobilise the people and modify their behaviour, particularly towards important national issues. Regrettably, the media in Nigeria are yet to take up such major roles that would facilitate the emergence of an indigenous national language in the country.";
  const PT2 = "One of the most potent elements in body language is eye behaviour. You shift your eyes, meet another person's gaze or fail to meet it \u2013 and produce an effect out of all proportion to the trifling muscular effort you have made. When two people look searchingly into each other's eyes, emotions are heightened and the relationship tipped toward greater intimacy.\n\nIn normal conversation, each eye contact lasts only about a second before one or both individuals look away. Because the longer meeting of the eye is rare, it is weighted with significance when it happens and can generate a special kind of human-to-human awareness. Most of the time, a lingering look is interpreted as a sign of attraction and this should be scrupulously avoided except in appropriate circumstances. A young woman once complained, 'That man makes me so uncomfortable, half the time when I glance at him he's already looking at me \u2013 and he keeps right on looking.'\n\nProper street behaviour requires a balance of attention. You are supposed to look at passer-by just enough to show that you are aware of his presence. If you look too little, you appear haughty or furtive; too much and you are inquisitive. Usually what happens is that people eye each other until they are about eight feet apart, at which point both cast down their eyes.\n\nMuch of eye behaviour is so subtle that we react to it only on the intuitive level. This has been demonstrated in elaborate experiments. Subjects sit and talk in the psychologist's laboratory, innocent of the fact that their eye behaviour is being observed from behind a one-way vision screen. In one fairly typical experiment, subjects were induced to cheat while performing a task, then were interviewed and observed. It was found that those who had cheated met the interviewer's eyes less often than was normal, an indication that 'shifty eyes' can actually be a tip-off to an attempt to deceive.\n\nHowever, none of the 'facts' of eye behaviour are cut and dried, for there are variations between individuals. People use their eyes differently and spend different amounts of time looking at others. Besides, no pattern of eye behaviour is precisely predictable in any normal conversation.";
  const PT3 = "The superiority of democracy over other forms of government has long been established. From its Greek origins the term 'democracy' has been defined as a political ___(16)___ based on fair representation and liberty for the individual. The ___(17)___ of liberty and equitable representation are rooted in the definition given by Aristotle of Greece about 2500 years ago. In the words of Aristotle, 'The basis of a democratic ___(18)___ is liberty'. Aristotle also emphasised the democratic ___(19)___ of 'freedom based on equality'. More than 2000 years after Aristotle, the tenets of liberty, justice and equitable representation continue to ___(20)___.\n\nFrom the time of the Greek city-states to the emergence of the modern nation-states, the fundamentals of democratic rule have remained universal ___(21)___. In the western hemisphere, revolutionary struggles were waged to enthrone democracy over ___(22)___ rule. Among these were the American Revolution of 1776, the French Revolution of 1789 and the Haitian Revolution of 1804, the first of such projects to be ___(23)___ by a black nation.\n\nThe American President, Abraham Lincoln, in the famous Gettysburg Address ___(24)___ the essential features of democratic ___(25)___ when he defined democracy as a 'government of the people, by the people, for the people'.";

  const P1Q = [
      { question: "According to the writer, life on earth is made bearable because of the presence of the", options: ["mountain tops", "meteors", "gravity", "atmosphere"], answer: 3, explanation: "Millions of meteors enter our atmosphere every day, 'but the atmosphere protects us from them'; the moon, with no atmosphere, gets hit." },
      { question: "Which of the following is true according to the passage?", options: ["The moon and the earth are different worlds", "Meteors grow on the surface of the moon like the vegetation on earth", "The moon is a hard surface like the earth", "Like the earth, the moon is not a lifeless world."], answer: 0, explanation: "The moon is 'completely and utterly dead', with no air, wind or sound, quite unlike the earth." },
      { question: "The argument put forward by the writer is that", options: ["the mountains on the moon are incomparably greater than the summit on Mount Everest", "lunar exploration is as difficult as climbing Mount Everest", "it is untenable to claim that life exists on the moon", "life exists on other worlds"], answer: 2, explanation: "The passage opens: 'It is not possible to admit that there is life of any sort on the moon', and everything after supports that. Lunar exploration is called 'incomparably greater' in difficulty than Everest, not 'as difficult as'." },
      { question: "The two advantages lunar explorers are said to have over climbers of Mount Everest are less fatigue and the", options: ["weightless nature of the moon", "absence of severe gravitational pull", "absence of high winds", "absence of atmospheric canopy"], answer: 2, explanation: "First, movement is less tiring because of the moon's weak gravity; second, there are no 'strong winds to contend with'." },
      { question: "From the passage, it can be inferred that", options: ["lunar explorers can only use bullet-proof suits on the moon", "the stars shoot arrows indiscriminately on the moon", "lunar explorers are usually exposed to inexplicable difficulties", "the moon is an unproductive world"], answer: 3, explanation: "The moon is a 'sterile mountainous waste' with no life of any sort: an unproductive world." },
  ];
  const P2Q = [
      { question: "A suitable title for this passage is", options: ["The Media and the Language Problem of Africa", "Africans and FESTAC Colloquium", "The Media and Cultural Expression in Africa and the Black World", "African Intellectuals and Colonialism"], answer: 0, explanation: "The passage is about the search for an indigenous national language and the role the media should play in it." },
      { question: "'This' as used in paragraph one refers to", options: ["each African country", "the media in Africa", "the colonial language", "the indigenous language"], answer: 3, explanation: "'This' points back to the indigenous language selected to replace the colonial one, which 'could bring about the much-needed unity'." },
      { question: "The writer's opinion of the media in Nigeria is that they", options: ["have made little or no attempt to promote the local languages", "favour the use of English instead of a Nigerian language", "cannot facilitate the emergence of a local national language", "lack the power to mobilise the government and people of Nigeria"], answer: 0, explanation: "'Regrettably, the media in Nigeria are yet to take up such major roles'." },
      { question: "Which of the following is true according to the passage?", options: ["Colonial languages are to blame for all the problems of Africa", "National unity and cohesion will be enhanced through an indigenous national language", "The media in Africa can enforce indigenous national languages", "The sole purpose of FESTAC was to discuss the language problems of Africa and the black world"], answer: 1, explanation: "An indigenous national language 'could bring about the much-needed unity and national integration'." },
      { question: "According to the passage, the colonial language is", options: ["superior to African languages", "inadequate for African cultural expression", "effective for national unity and cohesion", "restricted as a result of political independence"], answer: 1, explanation: "European languages 'were considered to be unsuitable for the expression of African cultural values'." },
  ];
  const P3Q = [
      { question: "Which of the following can be concluded from the opening paragraph?", options: ["Eye behaviour is one of the non-verbal ways of communication", "People are always offended by searching eye contact", "The effect of eye contact are always overwhelming", "Eye movement is the most potent means of expressing intimacy"], answer: 0, explanation: "Eye behaviour is one of the elements of 'body language', which communicates without words." },
      { question: "From the expression 'proper street behaviour requires a balance of attention and intention', it can be concluded that", options: ["when intimate groups in the streets, eye contact is usually longer", "there is a balance between those with longer eye contact and those with shorter eye contact", "before walking the streets one must balance one's shifty eyes", "even among strangers, attitudes and purposes can be deduced from eye behaviour"], answer: 3, explanation: "Look too little and you seem haughty or furtive; too much and you seem inquisitive. So strangers read attitudes from our eyes. (The paper prints 'deducted' for 'deduced' in D.)" },
      { question: "The reason given for the non-finality of research results on eye contact is", options: ["that research findings on eye contact have not been subjected to further empirical tests", "that some subjects cheat during experiments, thus invalidating research findings", "lack of uniformity in eye behaviour and the variability of contact situation", "lack of concord and foresight among psychologists who carry out research on eye movement"], answer: 2, explanation: "None of the 'facts' are cut and dried 'for there are variations between individuals', and no pattern is precisely predictable." },
      { question: "From the findings of the research described in the passage, one can reason that", options: ["guilty people make less frequent gazes during interrogation", "innocent people maintain longer eye contact than the guilty ones", "a feeling of guilt is occasioned by 'shifty eyes'", "'shifty eyes' are equally induced by innocence and guilt"], answer: 0, explanation: "Those who had cheated 'met the interviewer's eyes less often than was normal': the guilty look at the questioner less often." },
      { question: "The young woman in the passage was uncomfortable because", options: ["the man's short and sharp gazes would tip the relationship toward greater intimacy", "strangers who made the man's type of eye contact were likely to be dangerous", "she was allergic to eye contact", "the man appeared to be showing interest in her by his prolonged eye contact"], answer: 3, explanation: "'A lingering look is interpreted as a sign of attraction', and the man 'keeps right on looking'." },
  ];
  const CLOZE = [
      { question: "Gap 16: …the term 'democracy' has been defined as a political _____ based on fair representation and liberty for the individual.", options: ["hegemony", "pattern", "system", "influence"], answer: 2, explanation: "Democracy is a political system: an organised way of governing." },
      { question: "Gap 17: The _____ of liberty and equitable representation are rooted in the definition given by Aristotle…", options: ["examples", "principles", "statements", "purposes"], answer: 1, explanation: "Liberty and equitable representation are the basic principles of democracy." },
      { question: "Gap 18: In the words of Aristotle, 'The basis of a democratic _____ is liberty'.", options: ["state", "law", "population", "instinct"], answer: 0, explanation: "A democratic state is a country governed democratically, and its basis is liberty." },
      { question: "Gap 19: Aristotle also emphasised the democratic _____ of 'freedom based on equality'.", options: ["form", "ideal", "issue", "law"], answer: 1, explanation: "'Freedom based on equality' is a goal or value to aim at, i.e. an ideal.", keyVerdict: 'corrected', keyAnswer: 'D', answerNote: "'Freedom based on equality' is a value people aim for, not a rule passed by a lawmaker, so 'the democratic ideal' (B) fits; 'the democratic law of freedom based on equality' is not natural English. The same sentence also uses 'tenets' and 'principles' for these values." },
      { question: "Gap 20: …the tenets of liberty, justice and equitable representation continue to _____.", options: ["swing up", "draw up", "hold sway", "move on"], answer: 2, explanation: "To hold sway is to have great influence or power: these ideas still dominate." },
      { question: "Gap 21: …the fundamentals of democratic rule have remained universal _____.", options: ["subjects", "elections", "practices", "value"], answer: 2, explanation: "The fundamentals (plural) have remained universal practices: things done everywhere. 'Value' is singular and so doesn't agree with 'fundamentals'." },
      { question: "Gap 22: …revolutionary struggles were waged to enthrone democracy over _____ rule.", options: ["autocratic", "liberal", "collective", "individual"], answer: 0, explanation: "Democracy was set up in place of autocratic rule, i.e. rule by one person with absolute power." },
      { question: "Gap 23: …the Haitian Revolution of 1804, the first of such projects to be _____ by a black nation.", options: ["introduced", "practised", "undertaken", "supervised"], answer: 2, explanation: "One undertakes a project or a struggle: the Haitians carried it out." },
      { question: "Gap 24: Abraham Lincoln, in the famous Gettysburg Address _____ the essential features of democratic…", options: ["complicated", "simplified", "multiplied", "delineated"], answer: 1, explanation: "Lincoln reduced democracy to a short, simple formula: 'government of the people, by the people, for the people'." },
      { question: "Gap 25: …the essential features of democratic _____ when he defined democracy as a 'government of the people, by the people, for the people'.", options: ["government", "notion", "motion", "governance"], answer: 0, alsoAccept: [3], explanation: "Lincoln defined democracy as a kind of government, so 'democratic government' fits; 'democratic governance' (the way of governing) also makes good sense.", keyVerdict: 'multiple', keyAnswer: 'A', answerNote: "'Democratic government' (A) and 'democratic governance' (D) are both correct, natural English here, so both are marked right. Notion and motion don't fit." },
  ];

  const passages = [
    { passageId: 'eng-2005-p1', passageTitle: 'JAMB 2005 — Passage I', year: Y, instruction: READ, passage: PT0, questions: P1Q },
    { passageId: 'eng-2005-p2', passageTitle: 'JAMB 2005 — Passage II', year: Y, instruction: READ, passage: PT1, questions: P2Q },
    { passageId: 'eng-2005-p3', passageTitle: 'JAMB 2005 — Passage III', year: Y, instruction: READ, passage: PT2, questions: P3Q },
    { passageId: 'eng-2005-p4', passageTitle: 'JAMB 2005 — Passage IV (cloze)', year: Y, instruction: 'The passage has gaps numbered 16 to 25. Choose the most appropriate option for each gap.', passage: PT3, questions: CLOZE },
  ];

  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const GAP = 'Choose the option that best completes the gap(s): ';
  const VOWEL = 'Choose the option that has a DIFFERENT vowel sound from the others.';
  const SAMEV = 'Choose the option that has the same vowel sound as the letter(s) in capitals: ';
  const CONS = 'Choose the option that has the same consonant sound as the letter(s) in capitals: ';
  const DIFFC = 'Choose the option that has a DIFFERENT consonant sound from the others.';
  const DIFF = 'Choose the option that has a DIFFERENT stress pattern from the others.';
  const SAMES = 'Choose the option that has the same stress pattern as the given word (stressed syllable in capitals): ';
  const STRESSOF = 'Choose the appropriate stress pattern for the word (the stressed syllable is in capitals): ';
  const FIRST = 'Choose the option that has the stress on the FIRST syllable.';
  const NEAR = 'Choose the option NEAREST in meaning to the word(s) in capitals: ';
  const MEANS = 'Select the option that best explains the information conveyed in the sentence: ';
  const EMPH = 'The word in capitals has emphatic stress. Choose the option that best fits the expression: ';
  const OPP = 'Choose the option OPPOSITE in meaning to the word(s) in capitals: ';

  const flat = [
    q(NEAR + "Emeka's painting was so REALISTIC that it could almost have been a photograph.", ["authentic", "lively", "concrete", "picturesque"], A, "A realistic painting is true to life, i.e. authentic; the photograph comparison confirms it."),
    q(NEAR + "That FATEFUL decision changed the company's outlook in many ways.", ["disastrous", "unsuccessful", "wonderful", "uncontrollable"], A, "A fateful decision has far-reaching, usually disastrous, consequences."),
    q(NEAR + "Obi's dog is old but still LIVELY.", ["barking", "frisky", "howling", "attractive"], B, "Frisky means playful and full of energy, i.e. lively."),
    q(NEAR + "No wonder Sikemi later became a detective, she has been very OBSERVANT.", ["inquisitive", "inductive", "curious", "perceptive"], D, "An observant person notices things quickly, i.e. is perceptive."),
    q(NEAR + "The boxer FIZZLED OUT just in the sixth round.", ["became tired but fought on spiritedly", "surrendered rather disappointingly", "knocked out his opponent", "showed off his talents"], B, "To fizzle out is to end weakly and disappointingly."),
    q(NEAR + "The COMMON practice among some media practitioners is to be sensational in their reporting.", ["rampant", "ordinary", "cogent", "prevalent"], D, "A common practice is a widespread one, i.e. prevalent."),
    q(NEAR + "The greatness of the creator of the universe is always INEXPRESSIBLE to many adherents of certain faiths.", ["ineffable", "unbearable", "wonderful", "inevitable"], A, "Ineffable means too great to be expressed in words."),
    q(NEAR + "The accident victim received a SUPERFICIAL wound from the crash.", ["a painless", "a serious", "an external", "an internal"], C, "A superficial wound is on the surface of the body, i.e. external."),
    q(NEAR + "Nigeria has been playing a VITAL role in the political and economic development of Africa.", ["respectable", "creditable", "laudable", "crucial"], D, "Vital means extremely important, i.e. crucial."),
    q(NEAR + "Many people used to live in POVERTY.", ["the slum", "instability", "want", "difficulty"], C, "'Want' as a noun means lack of the necessities of life, i.e. poverty."),
    q(NEAR + "We made A PILE in the business deal.", ["cut corners", "broke even", "earned a lot of money", "lost a lot of money"], C, "To make a pile is to make a lot of money."),
    q(NEAR + "The manager described Mfon as a man of VEHEMENT character.", ["clever and helpful", "troublesome and noisy", "weak and uninterested", "strong and insistent"], D, "Vehement means forceful and passionate, i.e. strong and insistent."),
    q(NEAR + "COURTEOUSLY, Ade stood back to let his teacher go first through the door.", ["calmly", "patiently", "politely", "carefully"], C, "Courteously means politely."),
    q(NEAR + "His TACITURNITY amazed everyone in the court during the legal tussle.", ["sensibility", "pervasiveness", "obliviousness", "reticence"], D, "Taciturnity is the habit of saying very little, i.e. reticence."),
    q(NEAR + "ACCOUNTABILITY is certainly a desirable quality in a politician.", ["responsibility", "respectability", "diligence", "courage"], A, "Accountability is being answerable for one's actions, i.e. responsibility."),
    q(SAMEV + "lUck", ["lack", "turn", "lock", "brother"], D, "The u in luck is the short /ʌ/, as in brother."),
    q(SAMEV + "gUARd", ["guide", "argue", "chat", "gourd"], B, "The uar in guard is the long /ɑː/, as the ar in argue."),
    q(SAMEV + "bEEr", ["fair", "bear", "pier", "pear"], C, "Beer and pier both have the diphthong /ɪə/; fair, bear and pear have /eə/."),
    q(CONS + "healTHy", ["that", "they", "father", "path"], D, "The th in healthy is the voiceless /θ/, as in path; that, they and father have the voiced /ð/."),
    q(CONS + "fiLm", ["walk", "chalk", "salt", "psalm"], C, "The l is pronounced in film and salt; it is silent in walk, chalk and psalm."),
    q(CONS + "eNGlish", ["orange", "ink", "impugn", "single"], D, "The ng in English is /ŋɡ/ (ING-glish), exactly as in single (SING-gl).", { alsoAccept: [B], keyVerdict: 'multiple', keyAnswer: 'B', answerNote: "The underlined ng in English is pronounced /ŋɡ/, and single has exactly the same /ŋɡ/, so D is the closest match. Ink has the /ŋ/ part of that sound (followed by /k/, not /ɡ/), so B is accepted too. Orange has /ndʒ/ and impugn a plain /n/." }),
    q(MEANS + "One thing I will not be complaining about in my new job is a lack of excitement.", ["The job is exciting", "The job is not too exciting", "The job has been previously done", "The job is bad"], A, "If I won't complain of a lack of excitement, the job has plenty of excitement."),
    q(MEANS + "If the trader paid in full, his order was not pruned down.", ["Unless the trader paid in full his order would be rejected.", "The trader who made full payment did not have his order reduced.", "As the trader did not increase his order, he did not need to pay in full", "The trader who made some payment did not have his order delayed"], B, "To prune down is to reduce: full payment meant the order was not cut."),
    q(MEANS + "If I visited England, I might go to Manchester City.", ["I did not go to England and could not go to Manchester City", "I could not visit Manchester City because I did not want to go to England", "Whenever I visit England, I could go to Manchester city", "When I go to England, I could go to Manchester city"], A, "'If + past tense... might' is an unreal (imagined) condition: the speaker is not visiting England, so the trip to Manchester City doesn't happen."),
    q(MEANS + "The men were not pawns in someone else's political game.", ["They loved playing political game", "They were used by someone's political game", "The action they executed was their idea", "The men used someone else's plan."], C, "A pawn is someone used by others; not being pawns, the men acted on their own idea."),
    q(MEANS + "The class was tired of the new boy jawing away all the time.", ["He talked continuously in the class", "He was always making trouble for the class", "He was always chewing in the class", "He bit off people's jaws."], A, "To jaw (away) is to talk on and on."),
    q(MEANS + "The man puts his foot down whenever he is convinced of his action.", ["He makes his mark wherever he goes", "He desires to assert his will in the situation.", "He demonstrates firmness of character", "He demonstrates someone who likes to oppress others around him."], C, "To put one's foot down is to take a firm stand, showing firmness."),
    q(MEANS + "The Governor parried all the questions put to him by the journalist.", ["The Governor evaded all the questions", "The Governor mastered all the questions", "The Governor answered all the questions brilliantly", "The Governor failed all the questions"], A, "To parry a question is to dodge it skilfully, i.e. evade it."),
    q(MEANS + "The new Headmaster hoped that his men would pull together.", ["He was certain that they would resign en masse.", "He was certain that their condition would improve under him", "He expected that the men would cooperate with him", "He thought that the men would compose themselves at work"], C, "To pull together is to work together, i.e. cooperate."),
    q(MEANS + "The crisis ended as suddenly as it began.", ["The crisis stopped almost immediately", "The crisis had suddenly begun", "The crisis will stop immediately", "The crisis will not end suddenly."], A, "It ended abruptly, just as it had started abruptly."),
    q(MEANS + "If the rain hadn't fallen, we wouldn't have missed the match.", ["The rain didn't fall, so we didn't watch the match", "The rain fell, so we watched the match", "The rain is falling, so we will miss the match", "The rain fell, so we didn't watch the match"], D, "A third conditional reverses the facts: the rain did fall, and we did miss the match."),
    q(EMPH + "The EAGLES won the match.", ["What did the Eagles win?", "Did the Eagles lose the match?", "Did the Eagles win the match?", "Who won the match?"], D, "Stress on EAGLES answers 'who?'."),
    q(EMPH + "Your mother CAN cook the meal.", ["Isn't my mother able to cook the meal?", "What can my mother do?", "Can my father cook the meal?", "Who will cook the meal?"], A, "Stress on CAN insists on ability, answering a doubt about whether she is able to."),
    q(DIFF, ["criticism", "impossible", "interpreter", "remarkable"], A, "CRIticism is stressed on the first syllable; imPOSsible, inTERpreter and reMARKable on the second."),
    q(DIFF, ["canoe", "knowledge", "impound", "subject (verb)"], B, "KNOWledge is stressed on the first syllable; caNOE, imPOUND and subJECT (verb) on the second."),
    q(STRESSOF + "Departmentalise", ["departmenTAlise", "DEpartmentalise", "dePARTmentalise", "departMENtalise"], D, "Departmentalise is stressed like departmental: de-part-MEN-tal-ise."),
    q(STRESSOF + "Jurisprudence", ["jurispruDENCE", "jurisPRUdence", "juRISprudence", "JUrisprudence"], B, "Jurisprudence is stressed on the third syllable: ju-ris-PRU-dence."),
    q(STRESSOF + "Suburbanite", ["suBURbanite", "SUburbanite", "suburbaNITE", "suburBAnite"], A, "Suburbanite keeps the stress of suburban: su-BUR-ban-ite."),
    q(SAMES + "REfuse (noun)", ["intact", "obscure", "phantom", "reform"], C, "REFuse (noun) and PHANtom are stressed on the first syllable; inTACT, obSCURE and reFORM on the second."),
    q(SAMES + "DOWNtrodden", ["functional", "internal", "downgrading", "prescribing"], A, "DOWNtrodden and FUNCtional are stressed on the first syllable; inTERnal, downGRADing and preSCRIBing on the second."),
    q(OPP + "After fifty years, he could not find anyone who was CONTEMPORARY WITH him at college.", ["friendly with", "contested against", "strange to", "belonged to"], C, "Contemporary with means of the same time and set as him; of the options, 'strange to' (unconnected with) is furthest from that."),
    q(OPP + "The president can afford to dispense with some of his HENCHMEN.", ["advisers", "detractors", "body guard", "sycophants"], B, "Henchmen are loyal followers; detractors are critics who run a person down."),
    q(OPP + "Many Nigerians are WARY OF the night journeys.", ["unscared of", "worried about", "troubled about", "satisfied with"], A, "To be wary of something is to be cautious or afraid of it; the opposite is unscared of."),
    q(OPP + "Some people consider the leather upholstery and thick rugs a bit SUMPTUOUS.", ["simple", "lavish", "expensive", "desirable"], A, "Sumptuous means splendid and costly-looking; the opposite is simple."),
    q(OPP + "The proprietor accused Uche of silently ACQUIESCING TO the students' demands.", ["adjusting", "resisting", "compromising on", "submitting to"], B, "To acquiesce is to accept without protest; the opposite is to resist."),
    q(OPP + "The teacher recounted two events that were ANALOGOUS WITH each other.", ["advantageous to", "similar with", "different from", "distant from"], C, "Analogous means similar or comparable; the opposite is different from."),
    q(OPP + "The dramatist provided a satisfactory DENOUEMENT to the play.", ["criticism", "introduction", "audition", "climax"], B, "The denouement is the final unravelling of a plot, at its end; the opposite is the introduction, at its beginning."),
    q(OPP + "Idris gives me a SOUR look every time I pass by him.", ["satisfactory", "friendly", "sinister", "bad"], B, "A sour look is bad-tempered and unfriendly; the opposite is friendly."),
    q(OPP + "Asabe bought a GLOSSY pair of shoes.", ["smooth and shining", "rough and gummy", "smooth and shiny", "rough and dull"], D, "Glossy means smooth and shiny; the opposite is rough and dull."),
    q(OPP + "The Principal was filled with SCORN when he gave our reason for coming late.", ["sympathy", "contempt", "pity", "anger"], A, "Scorn is contempt; its opposite is sympathy."),
    q(OPP + "It would be difficult to defeat such a highly MOTIVATED team.", ["very immature", "very demoralised", "highly deluded", "completely disillusioned"], B, "A motivated team is eager and confident; a demoralised one has lost its spirit."),
    q(OPP + "Manu is hard to convince because he is an OPINIONATED person.", ["an imperative", "a discursive", "a subjective", "an objective"], D, "An opinionated person sticks to his own views regardless of the facts; an objective person judges fairly from the facts."),
    q(OPP + "The views of the plateau are in stark contrast to the WORKADAY cottages below.", ["ugly and unfascinating", "ordinary and uninteresting", "beautiful and interesting", "comfortable and fascinating"], C, "Workaday means ordinary and dull; the opposite is beautiful and interesting."),
    q(OPP + "The judge did not grant the request that the witness should appear BY PROXY.", ["be represented by a counsel", "not appear at all", "answer questions by phone", "be present in person"], D, "To act by proxy is to act through someone else; the opposite is to be present in person."),
    q(OPP + "The officer was given an INVIDIOUS task.", ["pleasant", "difficult", "vivid", "cruel"], A, "An invidious task is unpleasant and likely to cause resentment; the opposite is pleasant."),
    q(GAP + "The Bank Manager assured us that there was nothing to worry about _____.", ["with regard to the loan", "as regard to the loan", "with regards to the loan", "in regard of the loan"], A, "The fixed phrase is 'with regard to' (singular regard), meaning concerning."),
    q(GAP + "The train _____ before I arrived.", ["has left", "had left", "would leave", "was leaving"], B, "The past perfect (had left) shows the earlier of two past actions."),
    q(GAP + "I am writing to you for _____ reasons.", ["plenty", "myriad of", "concerned", "several"], D, "'Several reasons' is correct; 'plenty' needs 'of' and 'myriad of' needs 'a'."),
    q(GAP + "Yesterday, my mother asked me _____.", ["if I was tired", "if I am tired", "are you tired?", "whether was I tired?"], A, "Reported questions use statement word order and backshift the tense: if I was tired."),
    q(GAP + "Tsadu always cautions that difficult jobs should be done _____.", ["step by step", "steps by steps", "step from step", "steps after steps"], A, "The fixed expression is 'step by step', in the singular."),
    q(GAP + "By the end of the football match today, we _____ the best player.", ["would have known", "will have known", "could have known", "might have known"], B, "'By the end of... today' points to a future moment, so the future perfect 'will have known' is needed."),
    q(GAP + "The public library has stopped _____ books to readers.", ["lending", "borrowing", "loaning", "renting"], A, "A library lends books to readers; readers borrow from it."),
    q(GAP + "You, who _____ convicted, should appeal.", ["was", "are", "has been", "is"], B, "'Who' takes the verb form of its antecedent 'you', so: you, who are convicted. Was, has been and is are forms for he/she/it."),
    q(GAP + "In spite of Shade's good looks, her hair is always _____.", ["uncared for", "unkept", "unkempt", "unwashed"], C, "Unkempt means untidy, especially of hair. 'Unkept' is not the word."),
    q(GAP + "You can travel on your own, _____?", ["shan't you", "won't you", "isn't it", "can't you"], D, "A positive statement with 'can' takes the negative tag 'can't you?'."),
    q(GAP + "I was often angry _____ Oche since he differed _____ me often.", ["against/from", "with/with", "about/with", "with/to"], B, "We are angry with a person, and to differ with someone is to disagree with them."),
    q(GAP + "A nursery rhyme is used to teach pupils how to spell the word _____.", ["hippoppotemus", "hipopotamus", "hipoppotemus", "hippopotamus"], D, "The correct spelling is hippopotamus: double p, then single p, -tamus."),
    q(GAP + "Is it true that Okoro _____ when the gates were closed?", ["would have returned", "should return", "would return", "had returned"], D, "Returning happened before the gates were closed, so the past perfect 'had returned' is used."),
    q(GAP + "The Secretary-General was shocked at the number of _____.", ["children soldiers", "child's soldiers", "child soldiers", "childish soldiers"], C, "When a noun describes another noun it stays singular: child soldiers."),
    q(GAP + "We won't leave until it _____ raining.", ["stops", "had stopped", "will stop", "stopped"], A, "After 'until' (a time clause) we use the present simple for the future: until it stops."),
    q(GAP + "The man is refurbishing the flat with a view to _____ it.", ["selling", "sell", "be selling", "have sold"], A, "In 'with a view to', 'to' is a preposition, so it is followed by the -ing form: selling."),
    q(GAP + "The first prize was _____ tray.", ["a carved attractive wooden", "an attractive carved wooden", "a carved wooden attractive", "a wooden attractive carved"], B, "Adjective order: opinion (attractive), then type/description (carved), then material (wooden)."),
    q(GAP + "It is African for a younger person to show _____ to elders.", ["satisfaction", "deference", "understanding", "ignorance"], B, "Deference is humble respect, which a younger person shows to elders."),
    q(GAP + "As we sat _____ the silence, my eyes _____ the room.", ["in/roamed", "under/looked", "along/observed", "over/surrounded"], A, "We sit in silence, and eyes roam (wander over) a room."),
    q(GAP + "The _____ event marked the beginning of a new life for the entire cabinet.", ["historic", "history of the", "historicity of the", "historical"], A, "Historic means important or memorable; historical means connected with history or the past."),
  ];

  QUESTION_BANK.english = QUESTION_BANK.english.concat(passages, flat);
})();
