/**
 * JAMB/UTME 2015 — USE OF ENGLISH
 * From the 2015 question paper; answers from the JAMB/UTME English Language
 * answer key 2001–2020, each checked against the paper. Where the key in
 * circulation is wrong (often a printing error) the question carries
 * keyVerdict + keyAnswer + answerNote (see english-2007.js for the scheme).
 * Not included: Q21-35 (questions on the set novel, A. H. Mohammed's The Last Days at Forcados High School; see parts/2015-novel.js).
 *
 * Loaded after questions.js and before app.js.
 */
(function () {
  const Y = 2015;
  const SRC = 'JAMB UTME 2015';
  const READ = 'Read the passage carefully and answer the questions that follow.';

  const PT0 = "By 1910, the motor car was plainly conquering the highway. The private car was now part of every rich man's establishment, although its price made it as yet an impossible luxury for most of the middle class. But for the adventuresome youth, there was the motorcycle, a fearsome invention producing accident and ear-splitting noises. Already, the dignified carriages and smart pony-traps were beginning to disappear from the roads, and coachmen and grooms, unless mechanically minded, were finding it more difficult to make a living.\n\nThe roads which had gone to sleep since the coming of the railway, now awoke to feverish activity. Cars and motorcycles dashed along them at speeds which rivalled those of the express trains, and the lorry began to appear. Therefore, the road system was compelled to adapt itself to a volume and speed of traffic for which it had never been intended. To widen and straighten the roads and get rid of blind corners and every steep gradient were tasks which had scarcely been tackled before 1914. The situation was worse in towns where not only was any large scheme of road widening usually out of the question, but also where crowding and danger were all too frequently increased by the short-sighted eagerness of town authorities to allocate land for residential and other purposes.";
  const PT1 = "Chimpanzees apparently live in troops of between twenty and fifty animals. Within these troops, they form small groups of varying compositions; the basic groups consist of females or males plus offspring. Adult females spending much time together often turn out to be mother and daughter, or sisters. Mother and offspring live consistently, at least for the first four or five years, longer than any other primate except man.\n\nChimpanzees have a varied diet. In the forest, they are predominantly fruit eaters, but in the open woodlands, the males sometimes kill and eat colobus monkeys or bush pigs. Meat is a very choice item in the chimpanzee's diet and is often eaten slowly and deliberately with a mouthful of leaves between each bite. It is sometimes shared out with other chimpanzees, who will beg for pieces. This food-sharing is very unusual among non-human primates; with most other primates, it is everyone for himself. When the season is right, chimpanzees in woodlands also eat termites and they do this by fishing for them. When about to go hunting for termites, a chimpanzee will first carefully select a number of stems or pieces of grass and trim them to the appropriate length. It will tend to ignore any termite hill that is not ready and go on until it finds a mound ripe for fishing. A hole is scratched out with a finger and the prepared stem is inserted. It is withdrawn, covered with termites and passed carefully over the lower lip until every delicious morsel is removed.";
  const PT2 = "Safety devices and safety precautions are everywhere, but they are often ignored by most citizens. For instance ___(11)___ often place higher value on freedom and so, they see safety precautions required in road traffic operations as a ___(12)___ of their personal freedom. The aged tend to value their safety more and perceive safety precautions as a means to ___(13)___ personal safety.\n\nToday, there is a greater interest in ___(14)___ be it to life, property or the environment. The increased attention on safety in the home, industry or on the highway is a further ___(15)___ of man's desire for safety. However, the conquest of disease is quite different from the conquest of an ___(16)___ and unplanned event called 'accident'. The ___(17)___ and ___(18)___ implications of accidents are so great that no effort is too much towards its ___(19)___. Any condition that results in deaths, injuries and destruction of properties should not be treated with levity. Accidents do not just happen, they are ___(20)___.";

  const P1Q = [
      { question: "The word 'eagerness', as used in the passage, means", options: ["keenness", "frankness", "correctness", "calmness"], answer: 0, explanation: "The town authorities were short-sightedly eager, i.e. keen, to allocate land for building." },
      { question: "The expression 'unless mechanically minded', as used in the passage, refers to", options: ["coachmen and grooms adaptable to the new technology", "those amenable to change and development", "coachmen and grooms who choose to become mechanics", "town authorities allocating land"], answer: 0, explanation: "Coachmen and grooms were struggling unless they were mechanically minded, i.e. unless they could adapt to the new motor technology." },
      { question: "The statement 'By 1910, the motor car was plainly conquering the highway', as used in the passage, means that", options: ["by 1910 many people knew how to drive motor cars", "the motor car was invented in 1910", "by 1910 the motor car became a common sight on the highways", "highway codes for the motor cars came into effect in 1910"], answer: 2, explanation: "'Conquering the highway' means taking over the roads, so by 1910 motor cars had become a common sight on them." },
      { question: "The writer seems to suggest that", options: ["there were no roads before the advent of cars and motorcycles and so people had to be mechanically minded", "the volume and speed of traffic on the roads increased with the advent of cars, the motorcycles and lorries", "coachmen and grooms were not mechanically minded", "the roads that existed were dormant"], answer: 1, explanation: "The roads 'awoke to feverish activity' and had to adapt to 'a volume and speed of traffic for which it had never been intended'." },
      { question: "Which of the following statements can be inferred from the passage?", options: ["Insignificant improvement occurred in transport since the advent of the motor cars, the lorries and the motorcycles", "Human society was static without the express speed of cars and motorcycles", "Society would be less chaotic without the increasing volume and speed of motor cars, lorries and motorcycles", "People no longer use trains with the advent of cars and lorries"], answer: 0, explanation: "Improvement of the roads to match the new vehicles had 'scarcely been tackled before 1914'.", alsoAccept: [2], keyVerdict: 'multiple', keyAnswer: 'A', answerNote: "Read as being about the roads, A fits: widening and straightening them had 'scarcely been tackled before 1914', so little improvement had been made. But C can be inferred just as well: the new traffic brought noise, accidents, crowding and danger, so society would be less chaotic without it. Both are marked right." },
  ];
  const P2Q = [
      { question: "According to the passage, which of these characteristics is shared between chimpanzees and man?", options: ["Maintenance of close family ties", "Open rivalry among offspring", "Daughters maintaining closer contact with fathers", "Undue concern for family economic welfare"], answer: 0, explanation: "Mother and offspring stay together for four or five years, 'longer than any other primate except man', so both keep close family ties." },
      { question: "The word 'predominantly', as used in the passage, means", options: ["objectively", "primitively", "chiefly", "carefully"], answer: 2, explanation: "In the forest they are predominantly (mainly, chiefly) fruit eaters." },
      { question: "According to the passage, chimpanzees prefer", options: ["termites and plants", "fruits and plants", "meat and leaves", "meat and crabs"], answer: 1, explanation: "They are 'predominantly fruit eaters' and eat meat with leaves, so their diet is mainly fruits and plants." },
      { question: "From the passage, it can be deduced that chimpanzees", options: ["eats termites when in need of meat", "eat termites when in groups", "eat termites provided by mother and offspring", "eat termites in season"], answer: 3, explanation: "'When the season is right, chimpanzees in woodlands also eat termites.'" },
      { question: "Which of the following is true according to the passage?", options: ["Chimpanzees are meticulous when searching for food.", "Chimpanzees are reactive when in groups.", "Chimpanzees are restless when hungry.", "Chimpanzees are carnivorous and gregarious."], answer: 0, explanation: "They 'carefully select' stems, trim them to 'the appropriate length', ignore hills that are not ready and eat 'slowly and deliberately': meticulous.", alsoAccept: [3], keyVerdict: 'multiple', keyAnswer: 'D', answerNote: "The passage stresses how carefully chimpanzees get their food (selecting and trimming stems, waiting for the right season), so A is well supported. The key's D is partly right too: the males hunt and eat meat, and they share it rather than 'everyone for himself', though 'carnivorous' overstates it, since they are 'predominantly fruit eaters'. Both are marked right." },
  ];
  const CLOZE = [
      { question: "Gap 11: For instance _____ often place higher value on freedom…", options: ["visitors", "youths", "aliens", "government"], answer: 1, explanation: "The next sentence contrasts them with 'the aged', so the group meant is the young: youths." },
      { question: "Gap 12: …they see safety precautions required in road traffic operations as a _____ of their personal freedom.", options: ["clog", "coalition", "violation", "vibration"], answer: 2, explanation: "People who value freedom see rules as a violation (breach) of their personal freedom." },
      { question: "Gap 13: The aged… perceive safety precautions as a means to _____ personal safety.", options: ["warrant", "suppress", "increase", "guarantee"], answer: 3, explanation: "Safety precautions are a means to guarantee (make sure of) personal safety." },
      { question: "Gap 14: Today, there is a greater interest in _____ be it to life, property or the environment.", options: ["security", "management", "procurement", "development"], answer: 0, explanation: "The passage is about safety, so the interest is in security of life, property and the environment." },
      { question: "Gap 15: The increased attention on safety… is a further _____ of man's desire for safety.", options: ["evidence", "ingredient", "confidence", "allusion"], answer: 0, explanation: "The increased attention is further evidence (proof) of man's desire for safety." },
      { question: "Gap 16: …the conquest of disease is quite different from the conquest of an _____ and unplanned event called 'accident'.", options: ["unseen", "unforeseeable", "unfeasible", "unforeseen"], answer: 3, explanation: "An accident is an unforeseen (unexpected) and unplanned event. The paper misprints 'quite' as 'quiet' and B as 'unforeseeeable'." },
      { question: "Gap 17: The _____ and (18) implications of accidents are so great…", options: ["cultural", "natural", "commercial", "economic"], answer: 3, explanation: "Accidents cost money (lost lives, injuries, destroyed property), so they have economic implications." },
      { question: "Gap 18: The (17) and _____ implications of accidents are so great…", options: ["political", "social", "industrial", "religious"], answer: 1, explanation: "Accidents affect families and communities, so they have social implications." },
      { question: "Gap 19: …no effort is too much towards its _____.", options: ["protection", "prevention", "preservation", "presumption"], answer: 1, explanation: "We work towards the prevention of accidents, not their protection or preservation." },
      { question: "Gap 20: Accidents do not just happen, they are _____.", options: ["created", "caused", "cursed", "cost"], answer: 1, explanation: "Accidents have causes: they are caused by unsafe conditions or acts." },
  ];

  const passages = [
    { passageId: 'eng-2015-p1', passageTitle: 'JAMB 2015 — Passage I', year: Y, instruction: READ, passage: PT0, questions: P1Q },
    { passageId: 'eng-2015-p2', passageTitle: 'JAMB 2015 — Passage II', year: Y, instruction: READ, passage: PT1, questions: P2Q },
    { passageId: 'eng-2015-p3', passageTitle: 'JAMB 2015 — Passage III (cloze)', year: Y, instruction: 'The passage has gaps numbered 11 to 20. Choose the most appropriate option for each gap.', passage: PT2, questions: CLOZE },
  ];

  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const GAP = 'Choose the option that best completes the gap(s): ';
  const VOWEL = 'Choose the option that has a DIFFERENT vowel sound from the others.';
  const SAMEV = 'Choose the option that has the same vowel sound as the letter(s) in capitals: ';
  const CONS = 'Choose the option that has the same consonant sound as the letter(s) in capitals: ';
  const DIFFC = 'Choose the option that has a DIFFERENT consonant sound from the others.';
  const DIFF = 'Choose the option that has a DIFFERENT stress pattern from the others.';
  const SAMES = 'Choose the option that has the same stress pattern as the given word (stressed syllable in capitals): ';
  const STRESSOF = 'Choose the appropriate stress pattern for the word (the stressed syllable is in capitals): ';
  const FIRST = 'Choose the option that has the stress on the FIRST syllable.';
  const NEAR = 'Choose the option NEAREST in meaning to the word(s) in capitals: ';
  const MEANS = 'Select the option that best explains the information conveyed in the sentence: ';
  const EMPH = 'The word in capitals has emphatic stress. Choose the option that best fits the expression: ';
  const RHYME = 'Choose the option that rhymes with the given word: ';
  const OPP = 'Choose the option OPPOSITE in meaning to the word(s) in capitals: ';

  const flat = [
    q(MEANS + "Olu began to feel he was really homing in on the answer.", ["He was moving towards nowhere", "He was aiming at the answer", "He was homesick", "He was on his way home"], B, "To home in on something is to move steadily closer to it, i.e. to aim at it."),
    q(MEANS + "Chukwudi often recites the poem off the cuff.", ["He recites it without preparation", "He reads it outside the class", "He reads it under duress", "He recites it standing up"], A, "To do something off the cuff is to do it without preparation."),
    q(MEANS + "Ayo sailed close to the wind.", ["He took a risk by doing something illegal", "He is close to breaking the record", "He is close to getting an award", "He sailed smoothly around the world"], A, "To sail close to the wind is to take a risk by doing something that is nearly or actually illegal."),
    q(MEANS + "Musa is a past-master at the game of deception.", ["He is an expert", "He is a notable player", "He is a referee", "He is a master dribbler"], A, "A past master is an expert, someone very experienced at something."),
    q(MEANS + "People have golden opinions of the teacher.", ["They have very great admiration for him", "They talk about him with caution", "They see him as a dishonest person", "They like him for his plain dealing"], A, "Golden opinions are very high praise or admiration."),
    q(MEANS + "It has been observed that the labour president has his members in his pocket.", ["He puts his members in his pocket", "He is influenced by his members", "He has control over his members", "He is very close to his members"], C, "To have someone in your pocket is to have them under your control."),
    q(MEANS + "If you had not lost your temper, neither of us would be in this trouble.", ["You did not lose your temper so we are not in trouble.", "You did not lose your temper but we are both in trouble", "You are in trouble because you lost your temper but I am not.", "We are both in trouble because you lost your temper"], D, "'If you had not…' describes what did not happen: you did lose your temper, and so we are both in trouble."),
    q(MEANS + "The low income class are now badly off with the fast increasing cost of living.", ["They are badly monetized", "They are at a disadvantage", "They are badly employed", "They are the low income agitators"], B, "To be badly off is to be poor or in a difficult position, i.e. at a disadvantage."),
    q(MEANS + "If Musa should become president, trade with other countries will increase.", ["It is possible that trade will increase with the man's presidency", "This man ought to be president in order to increase trade", "If trade increases, this man should become president."], A, "'If… should' presents a possibility: if he becomes president, trade may increase. (The paper prints only three options here.)"),
    q(MEANS + "When the meeting was going on Aisha had her head in the clouds.", ["Aisha was not sleeping", "Aisha was meditating", "Aisha was not concentrating", "Aisha was making a noise"], C, "To have your head in the clouds is to be daydreaming, not concentrating. (The paper prints 'cloud'.)"),
    q(OPP + "He retired after an ILLUSTRIOUS career in the civil service.", ["untoward", "obscure", "infamous", "enviable"], B, "Illustrious means famous and highly respected; obscure means unknown and unimportant."),
    q(OPP + "The secretary's loyalty to her boss was UNALLOYED.", ["credible", "incredible", "half-hearted", "hypothetical"], C, "Unalloyed means complete and pure; the opposite is half-hearted."),
    q(OPP + "The report of the enquiry showed that the manager was CULPABLE.", ["guilty", "sincere", "innocent", "honest"], C, "Culpable means deserving blame, guilty; the opposite is innocent."),
    q(OPP + "Mrs. Bola is a SUBMISSIVE housewife.", ["a calm", "an assertive", "a sluggish", "an emotional"], B, "Submissive means meekly obedient; assertive means confident and forceful."),
    q(OPP + "The teacher CAUTIOUSLY raised his arm.", ["finally", "slowly", "quickly", "rashly"], D, "Cautiously means carefully; rashly means without care or thought."),
    q(OPP + "I admire Mahmud for his ALTRUISTIC behaviour.", ["benevolent", "selfish", "arrogant", "honest"], B, "Altruistic means unselfishly concerned for others; the opposite is selfish."),
    q(OPP + "The company imported some SOPHISTICATED equipment from Europe.", ["simple", "rural", "heavy", "light"], A, "Sophisticated equipment is complex and advanced; the opposite is simple."),
    q(OPP + "The thought of eating the forbidden meat REPULSED the little girl.", ["disgusted", "fascinated", "helped", "shocked"], B, "To repulse is to disgust and drive away; to fascinate is to attract strongly."),
    q(OPP + "The messenger was ELEVATED for his service to the organisation.", ["dismissed", "transferred", "demoted", "retrenched"], C, "To be elevated is to be promoted; the opposite is demoted."),
    q(OPP + "Mr. Gana is a thoroughly OBNOXIOUS young man.", ["offensive", "pleasant", "fraudulent", "sincere"], B, "Obnoxious means extremely unpleasant; the opposite is pleasant."),
    q(NEAR + "The musician basked in the ADULATION of the crowd.", ["condemnation", "admiration", "expectation", "visitation"], B, "Adulation is excessive praise or admiration."),
    q(NEAR + "The soldiers were arrested for using the ARSENALS unlawfully.", ["weapons", "garrison", "battalion", "infantry"], A, "An arsenal is a store of weapons; here it means the weapons themselves."),
    q(NEAR + "Two rows of trees ARCHED over the bridge on the highway.", ["sped", "passed", "laid", "curved"], D, "To arch is to form a curve over something."),
    q(NEAR + "The old man sat for hours MUSING on the wonders of the world.", ["laughing at", "meditating on", "meditating for", "planning to"], B, "To muse on something is to think deeply about it, to meditate on it."),
    q(NEAR + "The lazy man cast a LUSTFUL glance at his neighbour's wife.", ["covetous", "envious", "hateful", "quick"], A, "A lustful glance shows desire; covetous means wanting what belongs to someone else."),
    q(NEAR + "Her search for the treasure was FRANTIC.", ["rewarding", "chaotic", "hectic", "sudden"], B, "A frantic search is wild, hurried and disordered, i.e. chaotic.", { alsoAccept: [C], keyVerdict: 'multiple', keyAnswer: 'B', answerNote: "Frantic means wild and hurried, carried out in a disordered way. Chaotic (B) captures the disorder and hectic (C) captures the hurry and feverish activity; both are good synonyms, so both are marked right." }),
    q(NEAR + "The nurse HELD UP the operation.", ["delayed", "aggravated", "condemned", "hastened"], A, "To hold something up is to delay it."),
    q(NEAR + "'We must consider all CONTINGENCIES,' said the teacher.", ["hostilities", "irregularities", "possibilities", "proximities"], C, "Contingencies are possible future events that may happen."),
    q(NEAR + "The artiste gave a CREDITABLE performance.", ["realistic", "praiseworthy", "truthful", "bad"], B, "A creditable performance deserves praise."),
    q(NEAR + "It was an AUSPICIOUS moment for the intending couple.", ["a sympathetic", "a dangerous", "an unexpected", "a promising"], D, "Auspicious means showing signs of future success, i.e. promising."),
    q(GAP + "Hisila is _____ clever but not brilliant.", ["quite", "nearly", "hardly more", "very much"], A, "'Quite clever' means fairly clever, which fits 'but not brilliant'."),
    q(GAP + "Sola can't read _____ candle light.", ["at", "to", "by", "as"], C, "We read by a light source: by candlelight, by lamplight."),
    q(GAP + "Dede has left school, _____?", ["didn't he", "isn't it", "hasn't he", "did he"], C, "A positive statement with 'has' takes the negative tag 'hasn't he?'."),
    q(GAP + "The chairman _____ all his authority to ensure that his daughter gained admission to the university.", ["evolved", "asserted", "exerted", "extracted"], B, "To assert authority is to use it forcefully and make others recognise it.", { alsoAccept: [C], keyVerdict: 'multiple', keyAnswer: 'B', answerNote: "Both 'assert one's authority' and 'exert one's authority' are standard English. 'Exerted all his authority to ensure that…' (C) fits the sense of using power to get a result at least as well as B, so both are marked right." }),
    q(GAP + "Asilotu tried to jump over the wall several times but _____.", ["cannot", "would not have", "will not be", "could not"], D, "The sentence is in the past ('tried'), so the matching form is 'could not'."),
    q(GAP + "The poor boy was _____ a darkroom for 48 hours.", ["fortified with", "extricated from", "confused of", "confined to"], D, "To be confined to a place is to be kept in it."),
    q(GAP + "Suana _____ that hexagons had five sides, but later he knew they were six-sided figures.", ["has believed", "believes", "had believed", "would have believed"], C, "The belief came before the later knowing, so the past perfect 'had believed' is needed."),
    q(GAP + "They thought Musa _____ agree if they altered some of the conditions.", ["might", "can", "ought", "may"], A, "After the past 'thought' and the condition 'if they altered', the past modal 'might' is correct."),
    q(GAP + "Kusana _____ in the office, but he has gone fishing instead.", ["will be", "should be", "may be", "must be"], B, "'Should be' expresses where he ought to be, which contrasts with 'but he has gone fishing instead'."),
    q(GAP + "You live in the city now, _____?", ["are you", "don't you", "haven't you", "didn't you"], B, "'You live' is a positive present simple statement, so the tag is 'don't you?'."),
    q(GAP + "The man was given _____ degree despite the fact that he did not attend a university.", ["a ceremonial", "an honorary", "a ceremonious", "an honourable"], B, "A degree given as an honour, without study, is an honorary degree."),
    q(GAP + "The university is a corporate body made _____ different colleges.", ["up of", "in with", "up from", "of with"], A, "To be made up of means to consist of."),
    q(GAP + "Next term we are going to _____ how to draw.", ["learnt", "be taught", "be teaching", "learning"], B, "After 'going to' we need a base form; 'be taught' (passive) fits the sense of learning from a teacher."),
    q(GAP + "Concrete is made of _____.", ["a sand and cement", "sand and cement", "sand and a cement", "sand and a cement"], B, "Sand and cement are uncountable nouns, so they take no article 'a'. (The paper prints C and D identically.)"),
    q(GAP + "The HOD says she considers her degree certificate _____ than as a prize through labour.", ["as a rather gift of God", "rather as a gift of God", "as a gift of rather of God", "rather God as a gift"], B, "'Rather as X than as Y' keeps the two 'as' phrases parallel. (The paper misprints 'through' as 'thought'.)"),
    q(GAP + "I stayed away _____ I was late for the dinner.", ["when", "so", "although", "since"], D, "'Since' here means 'because', giving the reason for staying away."),
    q(GAP + "I _____ her birthday and I _____ how to make it up to her.", ["completely forgot/don't just know", "forgot completely/don't just know", "completely forgot/just don't know", "forgot completely/just don't know"], C, "The adverb goes before the verb ('completely forgot'), and 'just' comes before 'don't know'."),
    q(GAP + "Oloyede always sleeps like a baby, _____?", ["did he", "doesn't he", "could he", "does he"], B, "A positive present simple statement takes the negative tag 'doesn't he?'."),
    q(GAP + "The employer, not the salesmen _____ responsible for the loss.", ["have been", "was", "will be", "were"], B, "The verb agrees with the first subject, 'the employer' (singular); 'not the salesmen' is set aside."),
    q(GAP + "It _____ so hard that all the cars have stopped moving.", ["rains", "is raining", "was raining", "rained"], B, "'Have stopped' is present perfect, so the rain is going on now: 'It is raining so hard that…'."),
    q(SAMEV + "flEE", ["rid", "field", "faith", "skate"], B, "The ee in flee is the long /iː/, as ie in field."),
    q(SAMEV + "wAIter", ["road", "cite", "flavour", "hair"], C, "The ai in waiter is /eɪ/, as the a in flavour."),
    q(SAMEV + "pAlm", ["lunch", "blunt", "ranch", "florid"], C, "The a in palm is the long /ɑː/, as in British ranch /rɑːntʃ/."),
    q(CONS + "THeme", ["then", "the", "their", "theory"], D, "The th in theme is the voiceless /θ/, as in theory; then, the and their have voiced /ð/."),
    q(CONS + "PHantom", ["phew", "party", "physics", "pew"], C, "The ph in phantom is /f/, as in physics.", { alsoAccept: [A], keyVerdict: 'multiple', keyAnswer: 'C', answerNote: "Phew is pronounced /fjuː/, so its ph is also /f/, just like physics (C). Both are marked right; party and pew begin with /p/." }),
    q(CONS + "gaDGet", ["gable", "jet", "rider", "spondee"], B, "The dg in gadget is /dʒ/, as the j in jet."),
    q(RHYME + "weight", ["height", "wedge", "sleigh", "eight"], D, "Weight /weɪt/ rhymes with eight /eɪt/."),
    q(RHYME + "ever", ["never", "heavier", "favour", "fever"], A, "Ever /ˈevə/ rhymes with never /ˈnevə/."),
    q(RHYME + "gold", ["goal", "gaol", "goad", "goat"], C, "Goad /ɡəʊd/ is the closest: it shares the vowel and the final d, though it lacks the l of gold.", { keyVerdict: 'none', keyAnswer: 'C', answerNote: "Gold /ɡəʊld/ ends in /əʊld/, and none of the options does: goal, goad and goat each have only part of that ending, and gaol is /dʒeɪl/. The key's goad (C) is kept as the closest, sharing /əʊ/ and the final d." }),
    q(STRESSOF + "advantages", ["advanTAges", "advantaGES", "ADvantages", "adVANtages"], D, "Advantages is stressed on the second syllable: ad-VAN-ta-ges."),
    q(STRESSOF + "managerial", ["MAnagerial", "manaGErial", "maNAgerial", "manageRIAL"], B, "Words ending in -ial are stressed just before it: ma-na-GE-ri-al."),
    q(DIFF, ["guilty", "guitar", "confuse", "relief"], A, "Guilty is stressed on the first syllable (GUIL-ty); guiTAR, conFUSE and reLIEF on the second. (The paper labels the first two options both '(a)'.)"),
    q(EMPH + "Barkindo's wallet is made of PLASTIC.", ["Whose wallet is made of plastic?", "Is the wallet made of leather?", "Is Barkindo's shirt made of plastic?", "Is Barkindo's wallet made with plastic?"], B, "Stress on PLASTIC corrects the material: not leather but plastic."),
    q(EMPH + "Tolu saw Tade's father YESTERDAY.", ["Who did Tade's father see yesterday?", "Did Tolu see Tade's mother yesterday?", "Was Tade's father seen today?", "Who saw Tade's father yesterday?"], C, "Stress on YESTERDAY corrects the time: not today but yesterday."),
    q(EMPH + "The SOLDIER dances in his new shoes.", ["What does the soldier do in his new shoes?", "Who dances in his new shoes?", "Does the soldier dance in his old shoes?", "In whose new shoes does the soldier dance?"], B, "Stress on SOLDIER answers a question about the person: who dances?"),
  ];

  QUESTION_BANK.english = QUESTION_BANK.english.concat(passages, flat);
})();
