/**
 * JAMB/UTME 2001 — USE OF ENGLISH
 * Transcribed from the 2001 question paper; answers from the JAMB/UTME
 * English Language answer key 2001–2020.
 *
 * Where the key is plainly wrong, the correct answer is used and the
 * question carries `keyAnswer` (the key's letter) plus `answerNote` saying
 * why. Questions 47 and 83 are deliberately left out: 47 has more than one
 * correct option and 83 has none, pending review.
 *
 * Loaded after questions.js and before app.js. app.js flattens the
 * passage entries (see normalizePassageBank).
 */
(function () {
  const Y = 2001;
  const SRC = 'JAMB UTME 2001';

  const P1 = "The emergence of a standard dialect produces the phenomenon known as “accent” which is quite different from dialect. In the process of learning a foreign language, it is normal to transfer the patterns of an indigenous language to those of the foreign language. With time, however, those of form and most of those of orthography and phonology gradually get eliminated. This is because these can easily be identified and corrected. They are easy to correct because they do not involve patterns of muscular movement. It is also necessary to correct them because otherwise they could seriously impair intelligibility.\n\nWith phonetic patterns, on the other hand, there is a great deal of intelligibility tolerance because muscular patterns are involved, thus making corrections difficult when observed. Besides, phonetic patterns do not impair intelligibility much. Hence the transference of phonetic habits from one language to another is both easier to tolerate and more difficult to avoid than transference at the lexico-grammatical level. It follows that a speaker who is learning a second dialect does so with an accent since the muscles of his speech organs would have crystallized in response to the phonetics of his native language which he learnt first. The speaker therefore speaks the second dialect with the phonetic features of his native dialect. The learning of a standard language is simply the learning of a second dialect – that which has been standardized.\n\nMembers of a language community control at least two dialects and use both dialects in different situations. In the rural areas, the native dialect is used in most situations since there is less movement. Therefore, rural dwellers tend to be parochial and maintain the homogeneity of their dialect. In the urban community, on the other hand, there is more demand on the standard dialect than on the rural one. This is because people from different regions converge here. In order to ensure mutual intelligibility resulting from the pressure of communication, a great deal of demand is made on the standard dialect which now becomes the lingua franca amongst them.";

  const P2 = "It is possible to have a glimpse of life after death. Man has always believed in an afterlife, but only today do we have scientific reports of people who seem to have experienced the sensation of dying but lived to tell about it. Ongoing research is documenting hundreds of cases each year of the near-death experience (NDE), and scientists think they are finding a clearly identifiable pattern: usually a man is dying and, as he reaches the point of greatest physical distress, he hears himself pronounced dead by his doctor. He begins to hear an uncomfortable noise, a loud ringing or buzzing, and at the same time feels himself moving very rapidly through a long dark tunnel.\n\nAfter this he suddenly finds himself outside of his own physical body, but still in the immediate physical environment, and he sees his own body from a distance, as though he is a spectator. He watches the resuscitation attempt from this unusual vantage point and is in a state of emotional upheaval. After a while, he collects himself and becomes accustomed to his odd condition. He notices that he still had a 'body', but one of a very different nature and with very different powers from the physical body he has left behind. Soon after, things begin to happen. Others come to meet and to help him. He glimpses the spirits of relatives and friends who have already died, and a loving, warm spirit of a kind he has never encountered before – a being of light – appears before him. This being asks him a question, nonverbally – to make him evaluate his life – and helps him along by showing him a panoramic instantaneous playback of the major events of his life. Then he finds that he must go back to the earth that the time for his death has not yet come. At this point he resists, for by now he is taken up with his experiences in the afterlife and does not want to return. He is overwhelmed by intense feelings of joy, love and peace. Despite his attitude, though, he somehow reunites with his physical body and lives.\n\n(Adapted from Moody, R. A. (1975) Life after Life)";

  const P3 = "Before any detailed analysis begins, the first thing to do with the raw data is to check through the field record books and questionnaires for any ___(11)___, inconsistencies and incompleteness. In some cases, it may be possible to correct any discovered shortcomings. When it is not possible to carry out these ___(12)___, a visit to the field may even be necessary. It should however be realized that it is not very often that a revisit is possible. In most scientific ___(13)___ such revisits are clearly impossible. This is true of many surveys too. A road traffic survey ___(14)___ to find out the amount and frequency of daily traffic between two towns cannot be expected to be ___(15)___. There is no way of going back to check whether the number of vehicles reported for any particular hour is correct or not. With open-ended questions the ___(16)___ have to be classified into relatively small number of groups. The process of classifying answers and of sometimes identifying them by number and letter is called ___(17)___. When closed-ended questions are used, it is possible to code all the possible answers before they are actually received. This is called ___(18)___. What is done, a check through the answers for proper classification, numbering and lettering is still called for at this stage. This whole process of checking through questionnaires and notebooks is called ___(19)___. Collected data will eventually have to be used in drawing ___(20)___ and writing a report about the population from which it came.";

  const P4 = "By 1910, the motorcar was plainly conquering the highway. The private car was now part of every rich man's establishment, although its prices made it as yet an impossible luxury for most of the middle class. But for the adventure, some youth, there was the motorcycle, a fearsome invention producing accidents and ear-splitting noises. Already, the dignified carriages and smart pony-traps were beginning to disappear from the roads, and coachmen and grooms, unless mechanically minded, were finding it more difficult to make a living.\n\nThe roads, which had gone to sleep since the coming of the railway, now awoke to feverish activity. Cars and motorcycles dashed along them at speeds which rivaled those of the express trains, and the lorry began to appear. Therefore, the road system was compelled to adapt itself to a volume and speed of traffic for which it had never been intended. Its complete adaptation was impossible; but the road surface was easily transformed and, during the early years of the century, the dustiness and greasiness of the highways were lessened by tar-spraying. To widen and straighten the roads and get rid of blind corners and every steep gradient were tasks which had scarcely been tackled before 1914. The situation was worst of all in towns where not only was any large scheme of road widening usually out of the question, but also where crowding and danger were all too frequently increased by the short-sighted eagerness of town authorities in laying down tramlines.\n\nYet it was not only the road system that was in need of readjustment; the nervous system of those who used and dwelt by the roads suffered. The noises caused by the conversion of the roads into speedways called for a corresponding tightening up of the nerves; and, especially in the towns, the pedestrians who wished to preserve life and limb was compelled to keep his attention continually on the stretch, to practice himself in estimates of the speed of approaching vehicles and to run or jump for his life if he ventured off the pavement.\n\n(Adapted from Rachel Carson: The Advent of the Motor Car)";

  const passages = [
    { passageId: 'eng-2001-p1', passageTitle: 'JAMB 2001 — Passage I', year: Y, instruction: 'Read the passage carefully and answer the questions that follow.', passage: P1, questions: [
      { question: "Members of a language community control at least two dialects because", options: ["the convergence of people from disparate regions results in the pressure of communication", "there is little demand for the indigenous dialects", "they want a lingua franca which is produced by mutual intelligibility", "they are made up of both rural and urban dwellers"], answer: 0, explanation: "The last paragraph explains that people from different regions converge in towns, and the pressure of communication creates demand for a shared standard dialect alongside each person's native one." },
      { question: "According to the passage,", options: ["a foreign language produces the transference of the correct patterns of dialect features", "speech organs are shaped by indigenous languages", "a lingua franca is the consequence of a standard dialect", "mutual intelligibility is the consequence of the pressure of communication"], answer: 2, explanation: "The passage ends by saying the standard dialect 'now becomes the lingua franca' — the lingua franca grows out of the standard dialect. In D the passage has it the other way round: the pressure of communication creates the NEED for mutual intelligibility." },
      { question: "An appropriate title for this passage is", options: ["The Emergence of a Standard Language", "The Phenomenon of Accent", "The Quest for a Lingua Franca", "Members of a Language Community"], answer: 0, explanation: "The passage covers how a standard dialect emerges, why learners carry an accent into it, and how it becomes the lingua franca. B, C and D each name only one part of it." },
      { question: "The word 'those', as used in the passage (\"those of form and most of those of orthography and phonology\"), refers to", options: ["indigenous languages", "forms of orthography and phonology", "foreign languages", "patterns of an indigenous language"], answer: 3, explanation: "The previous sentence talks about transferring 'the patterns of an indigenous language'. 'Those of form…' means the patterns of form, orthography and phonology carried over from the indigenous language." },
      { question: "Phonetic patterns allow for intelligibility tolerance because", options: ["transference is both difficult to avoid and easy to tolerate", "they are involved and difficult to avoid", "they give rise to the phenomenon of accent which is easy to tolerate", "they involve muscular patterns which later crystallize"], answer: 0, explanation: "The passage says transference of phonetic habits 'is both easier to tolerate and more difficult to avoid' than transference at the lexico-grammatical level — which is why intelligibility tolerance exists." },
    ] },
    { passageId: 'eng-2001-p2', passageTitle: 'JAMB 2001 — Passage II', year: Y, instruction: 'Read the passage carefully and answer the questions that follow.', passage: P2, questions: [
      { question: "The NDE man appears to be a spectator in the flurry of activities around him because", options: ["his new 'body' would not allow him to participate", "he is moving rapidly through a long dark tunnel", "he can only watch as the events unfold", "he is now a dead man"], answer: 0, explanation: "He is outside his physical body with a 'body' of 'a very different nature and with very different powers', so he cannot take part in the resuscitation — he can only look on." },
      { question: "According to the passage, scientific evidence has made it possible", options: ["to make conjectures about what happens after death", "to know a little about what happens in the world of the dead", "for one to experience the sensation of dying and living again", "for the dead to return and tell their experiences"], answer: 0, explanation: "Researchers 'think they are finding a clearly identifiable pattern' — the reports allow informed guesses (conjectures) about death, not real knowledge of the world of the dead. The people involved did not actually die." },
      { question: "The expression 'as he reaches the point of greatest physical distress', as used in the passage, means when", options: ["the man's system finally collapses", "the sick man finally stops breathing", "his doctor is ready to pronounce him dead", "his condition seems to get worse"], answer: 0, explanation: "The point of greatest physical distress is the moment the body gives way completely — right then he 'hears himself pronounced dead'." },
      { question: "A suitable title for the passage is", options: ["A Glimpse into the World of the Dead", "Visions of an Afterlife", "Research into the Lives of the Dead", "The Sensation of Death and the Afterlife"], answer: 0, explanation: "The passage opens with 'It is possible to have a glimpse of life after death' and then describes what the NDE person glimpses. A captures that." },
      { question: "That the man was shown a panoramic instantaneous playback of the major events of his life suggests that", options: ["he needs to be entertained to take his mind away from the noise around him", "he needs to see the difference between his past life and his new life", "there are video machines in the world beyond", "he has to assess his deeds in life"], answer: 3, explanation: "The being of light asks the question 'to make him evaluate his life', and the playback helps him do it — he is reviewing (assessing) what he did in life." },
    ] },
    { passageId: 'eng-2001-p3', passageTitle: 'JAMB 2001 — Passage III (cloze)', year: Y, instruction: 'The passage has gaps numbered 11 to 20. Choose the most appropriate option for each gap.', passage: P3, questions: [
      { question: "Gap 11: …check through the field record books and questionnaires for any _____, inconsistencies and incompleteness.", options: ["mistakes", "events", "records", "odds"], answer: 0, explanation: "The list is of faults to catch while checking raw data: mistakes, inconsistencies and incompleteness." },
      { question: "Gap 12: When it is not possible to carry out these _____, a visit to the field may even be necessary.", options: ["plans", "corrections", "expectations", "possibilities"], answer: 1, explanation: "'These' points back to correcting the discovered shortcomings in the previous sentence — these corrections." },
      { question: "Gap 13: In most scientific _____ such revisits are clearly impossible.", options: ["questionnaires", "data", "experiments", "conclusions"], answer: 2, explanation: "A scientific experiment happens under particular conditions and cannot simply be revisited — the parallel is 'This is true of many surveys too'." },
      { question: "Gap 14: A road traffic survey _____ to find out the amount and frequency of daily traffic between two towns…", options: ["classified", "precoded", "conducted", "experimented"], answer: 2, explanation: "Surveys are conducted (carried out). The other verbs don't collocate with 'survey' in this sense." },
      { question: "Gap 15: …cannot be expected to be _____. There is no way of going back to check whether the number of vehicles reported for any particular hour is correct or not.", options: ["observed", "produced", "undertaken", "reproducible"], answer: 3, keyAnswer: 'C', answerNote: "The answer key gives C (undertaken), but the next sentence — there is no way of going back to check — shows the survey cannot be repeated, i.e. it is not reproducible. 'Cannot be expected to be undertaken' makes no sense for a survey that has just been conducted.", explanation: "The following sentence says there is no going back to check the counts — a one-off traffic survey cannot be repeated, so it is not reproducible." },
      { question: "Gap 16: With open-ended questions the _____ have to be classified into relatively small number of groups.", options: ["method", "responses", "errors", "conclusions"], answer: 1, explanation: "Open-ended questions produce free-form responses (answers), which are then grouped — the next sentence speaks of 'classifying answers'." },
      { question: "Gap 17: The process of classifying answers and of sometimes identifying them by number and letter is called _____.", options: ["encoding", "recording", "coding", "recoding"], answer: 2, explanation: "In survey research, assigning answers to categories with numbers/letters is called coding." },
      { question: "Gap 18: When closed-ended questions are used, it is possible to code all the possible answers before they are actually received. This is called _____.", options: ["recoding", "coding", "precoding", "encoding"], answer: 2, explanation: "Coding done in advance ('before they are actually received') is precoding — 'pre-' means before." },
      { question: "Gap 19: This whole process of checking through questionnaires and notebooks is called _____.", options: ["listing", "posting", "editing", "auditing"], answer: 2, explanation: "Checking completed questionnaires for errors, consistency and correct coding is called editing the data." },
      { question: "Gap 20: Collected data will eventually have to be used in drawing _____ and writing a report about the population from which it came.", options: ["analogies", "examples", "references", "conclusions"], answer: 3, explanation: "Data is used to draw conclusions — the fixed collocation is 'draw conclusions'." },
    ] },
    { passageId: 'eng-2001-p4', passageTitle: 'JAMB 2001 — Passage IV', year: Y, instruction: 'Read the passage carefully and answer the questions that follow.', passage: P4, questions: [
      { question: "The writer seems to suggest that", options: ["the volume and speed of traffic on the roads increased with the advent of cars, motor cycles and lorries", "there were no roads before the advent of cars and motorcycles and so people had to be mechanically minded", "coachmen and grooms were not mechanically minded", "the roads that existed were dormant"], answer: 0, explanation: "The roads 'awoke to feverish activity' and had to adapt 'to a volume and speed of traffic for which it had never been intended' once cars, motorcycles and lorries arrived." },
      { question: "The writer uses the expression 'unless mechanically minded' to refer to", options: ["town authorities laying down tramlines", "coachmen and grooms who chose to become mechanics", "coachmen and grooms adaptable to the new technology", "those amenable to change and development"], answer: 2, explanation: "Only coachmen and grooms who could adapt to the new mechanical technology escaped the difficulty of making a living." },
      { question: "The statement 'By 1910, the motor car was plainly conquering the highway' means that", options: ["highway codes for motor cars came into effect by 1910", "by 1910 motor cars became a common sight on the highways", "the motor car was invented in 1910", "by 1910 many people knew how to drive motorcars"], answer: 1, explanation: "'Conquering the highway' means the car was taking over the roads — becoming the common sight there while carriages and pony-traps disappeared." },
      { question: "From the passage, it is obvious that", options: ["the motorcar and the lorry came to displace the train traffic", "motor cars were mere luxuries which many people tried desperately to acquire", "the motorcar was invented before the express trains", "the train was the fastest means of transport before the motorcar and the lorry"], answer: 3, keyAnswer: 'B', answerNote: "The answer key gives B, but the passage never says people 'tried desperately' to acquire cars — only that they were an impossible luxury for most of the middle class. D is directly supported: cars reached speeds 'which rivaled those of the express trains', and the roads had 'gone to sleep since the coming of the railway'.", explanation: "Cars reached speeds 'which rivaled those of the express trains' — the express train had been the benchmark for speed, i.e. the fastest means of transport before cars and lorries." },
      { question: "One of the following statements can be deduced from the passage.", options: ["Significant improvement occurred in road transport since the advent of motorcars, lorries and motorcycles.", "People no longer used trains with the advent of cars and lorries.", "Society would be better off without the chaotic volume and speed of motor cars, lorries and motorcycles.", "Human society was static without the express speed of cars and motorcycles."], answer: 0, keyAnswer: 'C', answerNote: "The answer key gives C, but that is an opinion the passage never expresses; the writer describes the strain on roads and nerves without saying society would be better off without cars. A is what the passage supports: the roads 'awoke to feverish activity', vehicles reached speeds rivalling express trains, and the road surface was improved by tar-spraying.", explanation: "The passage describes road transport being transformed after cars arrived: busy roads, train-like speeds, and surfaces improved by tar-spraying. B and D are never said, and C is an opinion the writer does not give." },
    ] },
  ];

  // Letters → index
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  const STRESS = 'Identify the word that has a DIFFERENT stress pattern from the others.';
  const VOWEL = 'Choose the word that does NOT have the same vowel sound as the others.';
  const FIRST = 'Identify the word that has the stress on the FIRST syllable.';
  const OPP = 'Choose the option OPPOSITE in meaning to the word(s) in capitals: ';
  const NEAR = 'Choose the option NEAREST in meaning to the word(s) in capitals: ';
  const GAP = 'Fill the gap with the most appropriate option: ';
  const EMPH = 'The word in capitals has emphatic stress. Choose the option that best fits the expression: ';
  const MEANS = 'Select the option that best explains the information conveyed in the sentence: ';

  const flat = [
    q(STRESS, ["administrative", "circulation", "temperamental", "consideration"], A, "adMINistrative is stressed on the 2nd syllable; circuLAtion, temperaMENtal and consideRAtion are stressed on the 3rd."),
    q(STRESS, ["classroom", "programme", "brother", "July"], D, "juLY is stressed on the 2nd syllable; CLASSroom, PROgramme and BROther are stressed on the 1st."),
    q(VOWEL, ["bale", "plait", "saint", "gate"], B, "plait is pronounced /plæt/ with a short 'a'; bale, saint and gate all have the /eɪ/ sound."),
    q(VOWEL, ["rice", "fight", "granite", "die"], C, "granite ends in a short /ɪ/ (GRAN-it); rice, fight and die have /aɪ/."),
    q(VOWEL, ["wind (moving air)", "people", "even", "key"], A, "wind (moving air) has a short /ɪ/; people, even and key have the long /iː/."),
    q(VOWEL, ["enjoy", "log", "toil", "rejoice"], B, "log has the short /ɒ/; enjoy, toil and rejoice have the diphthong /ɔɪ/."),
    q(GAP + "_____ told of his impending arrival, I worked hard to make his short stay very comfortable.", ["Have being", "Having been", "Having being", "Have I been"], B, "A perfect passive participle phrase is needed: 'Having been told…'. 'Having being' and 'Have being' are not English forms."),
    q(GAP + "The weather is probably _____ appealing for people who live in Jos _____ for foreigners.", ["no less / than", "more / as", "as much / as", "at least as / but"], A, "'No less appealing … than …' is the correct comparative pattern. 'As much appealing as' is ungrammatical — with an adjective we say 'as appealing as'.", { keyAnswer: 'C', answerNote: "The answer key gives C (as much/as), but 'as much appealing as' is not grammatical English — 'as much' goes with nouns, not adjectives. A gives the correct comparative: 'no less appealing for people who live in Jos than for foreigners'." }),
    q(GAP + "Ade tried to _____ all memory of his dead father.", ["recall", "obliterate", "eulogize", "obstruct"], B, "To obliterate a memory is to wipe it out completely — the natural collocation with 'all memory of'.", { keyAnswer: 'A', answerNote: "The answer key gives A (recall), but one does not 'recall all memory of' someone; the idiomatic sentence is 'tried to obliterate (wipe out) all memory of his dead father'." }),
    q(GAP + "This imposing edifice _____ a fortune to build.", ["had costed", "costed", "cost", "have cost"], C, "The past tense of 'cost' (meaning to have a price) is 'cost'. 'Costed' is only used for 'estimated the cost of'; 'have cost' does not agree with the singular subject."),
    q(GAP + "Three quarters of the hostel _____ been painted and three quarters of the students _____ moved in.", ["has / has", "have / has", "have / have", "has / have"], D, "With fractions, the verb agrees with the noun after 'of': 'the hostel' (singular) → has; 'the students' (plural) → have."),
    q(GAP + "They let him go in _____ of his age.", ["respect", "regard", "disregard", "consideration"], A, "'In respect of' means 'because of / with reference to'. The other nouns need different prepositions (in regard to, in consideration of)."),
    q(GAP + "_____ you come early to the new house, clean up my flat.", ["While", "By chance", "Should", "Should in case"], C, "Inverted 'Should you come early…' means 'If you come early…'. 'Should in case' is a redundant combination."),
    q(GAP + "These villagers _____ to grow rice.", ["used", "are used", "were used", "use"], A, "'Used to + verb' describes a past habit: they used to grow rice. 'Are/were used to' would need '-ing' (used to growing)."),
    q(GAP + "When Ajike met her _____ husband at the party, she felt like reconciling with him.", ["strange", "loving", "caring", "estranged"], D, "'Reconciling' implies they had separated — an estranged husband is one who no longer lives with or is on good terms with his wife."),
    q(GAP + "He does not seem to know how to solve the problem, _____?", ["does not he", "does he", "does he not", "doesn't he"], B, "A negative statement takes a positive question tag: 'He does not seem…, does he?'"),
    q(GAP + "Some scientists are trying to _____ human beings in their laboratories.", ["imitate", "implicate", "replicate", "fabricate"], C, "To replicate is to make an exact copy — the word used for cloning humans."),
    q(GAP + "A wide range of options _____ made available to the political parties during the recently concluded elections.", ["is", "was", "were", "are"], C, "'A wide range of options' is treated as plural (the options), and 'recently concluded' requires the past tense → were."),
    q(GAP + "The meeting was called to _____ divergent views on the subject of a national conference.", ["re-present", "reconstitute", "reconcile", "recommend"], C, "Divergent (differing) views are reconciled — brought into agreement."),
    q(GAP + "The police came early enough to _____ the bomb planted by the rioters.", ["detonate", "insulate", "diffuse", "defuse"], D, "To defuse a bomb is to remove its fuse so it can't explode. 'Diffuse' means to spread out; 'detonate' means to explode it."),
    q(GAP + "The government which _____ recruiting _____ workers suddenly stopped doing so.", ["is / their", "were / their", "was / its", "are / its"], C, "'The government' here is one body acting as a unit, and 'stopped' is past, so singular past verb and singular pronoun: was … its."),
    q(GAP + "I do not think any sane person would have acted in such a _____ manner.", ["rational", "cruel", "secret", "composed"], B, "'Any sane person would NOT have acted…' — the manner must be one a sane person would avoid: cruel."),
    q(GAP + "Neither Agbo nor his parents _____ the meetings now.", ["has attended", "attend", "attends", "attended"], B, "With 'neither…nor', the verb agrees with the nearer subject, 'his parents' (plural), and 'now' needs the present tense → attend."),
    q(GAP + "Modern dancing has become rather scientific and so requires _____.", ["a rapping voice", "bizarre costuming", "immense instrumentation", "some choreographic skill"], D, "Choreography is the art of designing dance movements — the skill a 'scientific' approach to dancing requires."),
    q(GAP + "Of course, we all saw the culprit _____ and hit the man.", ["approaching", "approaches", "approached", "approach"], D, "After verbs of perception (see, watch, hear) + object, the bare infinitive is used, and it must match the parallel verb 'hit': saw the culprit approach and hit the man.", { keyAnswer: 'C', answerNote: "The answer key gives C (approached), but after 'saw + object' English uses the bare infinitive, parallel with 'hit' in the same sentence: 'we all saw the culprit approach and hit the man'." }),
    q(GAP + "The Company Director showed the contractor a _____ of the proposed office complex.", ["photocopy", "photograph", "prototype", "microfilm"], C, "A building that is only 'proposed' doesn't exist yet, so it can't be photographed or photocopied — only shown as a model (prototype)."),
    q(GAP + "Had he considered his public image carefully, he _____ for his opponent in the election.", ["would have stood down", "might have stood aside", "should have stepped down", "would have stepped aside"], D, "'Had he considered…' is a third conditional, which takes 'would have + past participle', and the idiom for giving way to a rival is 'step aside for'.", { keyAnswer: 'C', answerNote: "The answer key gives C (should have stepped down), but the inverted third conditional 'Had he considered…' requires 'would have', and one steps aside FOR an opponent (one steps down FROM a post)." }),
    q(GAP + "The editor was not happy that the Nigerian press was hemmed _____.", ["up", "across", "in", "over"], C, "To be hemmed in is to be surrounded and restricted — the press's freedom was being curtailed."),
    q(GAP + "More _____ to your elbow as you campaign for press freedom!", ["energy", "power", "effort", "grease"], B, "'More power to your elbow!' is a fixed idiom meaning 'well done / keep it up'.", { keyAnswer: 'C', answerNote: "The answer key gives C (effort), but the fixed English idiom of encouragement is 'More power to your elbow!'. 'More effort to your elbow' is not an expression." }),
    q(GAP + "A child that shows mature characteristics at an early age may be described as _____.", ["precocious", "ingenuous", "premature", "preconceived"], A, "Precocious means developing abilities or maturity unusually early. 'Premature' means happening too soon (e.g. a birth); 'ingenuous' means innocent."),
    q(FIRST, ["misread", "resign", "competent", "compel"], C, "COMpetent is stressed on the 1st syllable; misREAD, reSIGN and comPEL are stressed on the 2nd."),
    q(FIRST, ["resist", "intact", "confirm", "salon"], D, "SAlon is stressed on the 1st syllable; reSIST, inTACT and conFIRM are stressed on the 2nd."),
    q("Choose the word that has the same consonant sound as the letter 't' in PAST.", ["pasture", "castle", "wrestle", "preached"], D, "The 't' in past is /t/. The '-ed' in preached is also pronounced /t/. In pasture it is /tʃ/, and in castle and wrestle the 't' is silent."),
    q("Choose the word that has the same consonant sound as the letters 'ch' in CHURCH.", ["feature", "chauffeur", "ocean", "machine"], A, "'Ch' in church is /tʃ/, the same sound as 't' in feature. Chauffeur, ocean and machine all have /ʃ/."),
    q("Choose the word that has the same consonant sound as the letter 's' in SURE.", ["charlatan", "church", "cheer", "cheap"], A, "The 's' in sure is /ʃ/, the same as 'ch' in charlatan (a French-origin word). Church, cheer and cheap have /tʃ/."),
    q("Choose the word that has the same consonant sound as the letters 'th' in THANK.", ["Thomas", "though", "Thames", "thought"], D, "'Th' in thank is the voiceless /θ/, as in thought. In Thomas and Thames 'th' is /t/; in though it is the voiced /ð/."),
    q(OPP + "Amina's performance in the examination SURPASSED MY EXPECTATIONS.", ["amazed everyone", "lacked merit", "was extraordinarily good", "was disappointing"], D, "To surpass expectations is to do better than expected; the opposite is to fall short of them — to be disappointing."),
    q(OPP + "As these boys never act in public, the police are now worried about their COVERT activities.", ["evil", "open", "cryptic", "ignoble"], B, "Covert means hidden or secret; its opposite is open (overt)."),
    q(OPP + "The town was all AGOG at his unexpected return.", ["unexcited", "excited", "on fire", "surprised"], A, "Agog means very eager and excited; the opposite is unexcited."),
    q(OPP + "Some equatorial areas have a SULTRY climate.", ["a hot", "an inclement", "a temperate", "a stable"], B, "Sultry weather is hot and humid. Inclement weather is cold, wet or stormy, the opposite extreme. 'A hot' is a synonym; 'temperate' is merely mild, and 'stable' is unrelated to heat."),
    q(OPP + "The journalist's write-up contained a PLETHORA of detail.", ["simplicity", "shortage", "complexity", "spectrum"], B, "A plethora is an excess or overabundance; the opposite is a shortage."),
    q(OPP + "In the latter part of his life, the famous soldier showed signs of YOUTHFULNESS.", ["bravery", "vitality", "energy", "senility"], D, "Youthfulness is the quality of being young and vigorous; senility is the mental and physical decline of old age."),
    q(OPP + "It is INCONCEIVABLE that the rat devoured the cat.", ["contestable", "credible", "incomprehensible", "unimaginable"], B, "Inconceivable means impossible to believe or imagine; the opposite is credible (believable)."),
    q(OPP + "Ali wondered why the principal was AMBIVALENT about the students' future.", ["inconsiderate", "decisive", "anxious", "ambitious"], B, "Ambivalent means having mixed feelings or being unable to decide; the opposite is decisive."),
    q(OPP + "The teacher taught the RUDIMENTS of Chemistry to the first grade.", ["elements", "fundamentals", "basics", "theories"], D, "Rudiments are the basic elements of a subject; elements, fundamentals and basics are all synonyms. 'Theories' is the only option pointing to advanced, abstract knowledge rather than the basics."),
    q(OPP + "In his NAIVETY, he believed all the stories his friend told him.", ["artlessness", "friendliness", "incredulity", "stupidity"], C, "Naivety is a readiness to believe things; incredulity is an unwillingness to believe."),
    q(OPP + "Updating the Board's brochure is an ARDUOUS task.", ["a regular", "an annual", "a difficult", "an easy"], D, "Arduous means demanding great effort; the opposite is easy."),
    q(OPP + "The lecture seemed INTERMINABLE.", ["brief", "interesting", "boring", "unending"], A, "Interminable means seemingly endless; the opposite is brief."),
    q(OPP + "Had I known about their plan much earlier, I would have NIPPED IT IN THE BUD.", ["promoted it", "squashed it", "initiated it", "stopped it"], A, "To nip something in the bud is to stop it at an early stage; the opposite is to encourage its growth, i.e. promote it. Squashed and stopped are synonyms.", { keyAnswer: 'C', answerNote: "The answer key gives C (initiated it), but the plan was theirs and already existed, so the speaker could not have initiated it. The opposite of stopping something early is helping it grow, i.e. promoting it. Put back into the sentence, only 'I would have promoted it' makes sense." }),
    q(OPP + "What a HARMLESS thought he has!", ["pleasant", "perfect", "pernicious", "pertinent"], C, "Pernicious means harmful or destructive, especially in a gradual or subtle way — the opposite of harmless."),
    q(OPP + "There is much APATHY towards reading among students nowadays.", ["indecision", "enthusiasm", "indifference", "disinclination"], B, "Apathy is a lack of interest or enthusiasm; the opposite is enthusiasm."),
    q(EMPH + "YOUR sister should come with us tomorrow.", ["Should your brother come with us tomorrow?", "Should our brother come with us tomorrow?", "Should Ado's sister come with us tomorrow?", "Should my sister come with us tomorrow?"], D, "Stressing YOUR corrects a question about whose sister: the speaker is answering 'Should MY sister come…?'."),
    q(EMPH + "They FLEW to Abuja.", ["Where did they fly to?", "Did they go to Abuja by road?", "How will they get to Abuja?", "Did they fly to Jos?"], B, "Stressing FLEW corrects the means of travel — it answers 'Did they go by road?'. D would put stress on Abuja; C is in the future tense."),
    q(EMPH + "My neighbour BRUISED his thigh while playing football.", ["Did your neighbour fracture his thigh while playing football?", "Did your neighbour break his leg while playing tennis?", "Did your neighbour play football yesterday?", "Was your neighbour involved in an accident?"], A, "Stressing BRUISED corrects only the injury — it answers 'Did he FRACTURE his thigh?'. B changes several details, so the stress would fall elsewhere."),
    q(MEANS + "Adawo is an imp.", ["Adawo behaves badly.", "Adawo behaves decently.", "Adawo behaves differently.", "Adawo behaves queerly."], A, "An imp is a mischievous child or person — someone who misbehaves."),
    q(MEANS + "The solution lies in choosing between various negative alternatives.", ["The solution lies in choosing between the positive and the negative.", "The solutions are many.", "The solution can be found in one of the negative options.", "The solution is a negative one."], C, "All the alternatives are negative, and the answer is to pick one of them — i.e. the solution is found in one of the negative options."),
    q(MEANS + "The man reasoned that there ought to be a limit to sycophancy.", ["Sycophants need not talk all the time.", "There can be no favour beyond a reasonable point.", "Sycophants should know when to grant people's request.", "People should know when not to use flattery."], D, "Sycophancy is flattering people to gain advantage; a limit to it means people should know when to stop flattering."),
    q(MEANS + "Oche's chief idiosyncrasy is a passion for pounded yam.", ["Oche hates pounded yam.", "Oche's chief hates pounded yam.", "Oche's chief likes pounded yam.", "Oche has a penchant for pounded yam."], D, "An idiosyncrasy is a personal peculiarity; 'chief' here means main, not a chief. A passion = a penchant (strong liking)."),
    q(NEAR + "The professor discussed a number of ABSTRUSE topics.", ["irrelevant", "useful", "esoteric", "relevant"], C, "Abstruse means difficult to understand, obscure; esoteric means understood only by a small, specialised group."),
    q(NEAR + "Tade became TIMOROUS when she was asked to give the valedictory speech.", ["excited", "aggressive", "nervous", "happy"], C, "Timorous means showing nervousness or fear."),
    q(NEAR + "The men were TARDY in offering help.", ["generous", "quick", "brave", "slow"], D, "Tardy means slow or late."),
    q(NEAR + "Ugo has often been described as BELLIGERENT.", ["attractive", "combative", "innocent", "patient"], B, "Belligerent means hostile and eager to fight — combative."),
    q(NEAR + "The COALESCENCE of the groups created additional problems.", ["union", "fighting", "proscription", "disbandment"], A, "Coalescence is the coming together of separate parts into one — a union."),
    q(NEAR + "Funmi is just being FACETIOUS about her marrying a soldier.", ["unfaithful", "serious", "crazy", "unserious"], D, "Facetious means treating a serious matter with inappropriate humour — being unserious."),
    q(NEAR + "The village girl wore SUMPTUOUS clothes.", ["loose-fitting", "cheap", "faded-looking", "expensive"], D, "Sumptuous means splendid and expensive-looking."),
    q(NEAR + "Any chief executive of an organization would find RADICAL CHANGES blocked at every turn.", ["ideas", "innovations", "developments", "suggestions"], B, "Radical changes are new, fundamental changes to how things are done — innovations."),
    q(NEAR + "I cannot understand why Ali should serve in that MORIBUND administration.", ["crumbling", "purposeless", "prodigal", "oppressive"], A, "Moribund means at the point of death or in terminal decline — crumbling."),
    q(NEAR + "Bose was angry because her friend called her a PILFERER.", ["liar", "hypocrite", "criminal", "thief"], D, "A pilferer is someone who steals things of small value — a petty thief."),
    q(NEAR + "While the hooligans exchanged blows, we looked on COMPLACENTLY.", ["questioningly", "sorrowfully", "dejectedly", "contentedly"], D, "Complacently means in a self-satisfied, unconcerned way — contentedly."),
    q(NEAR + "The player kept on GAMELY to the end of the match.", ["courageously", "skillfully", "amateurishly", "stubbornly"], A, "Gamely means bravely and willingly, despite difficulty — courageously."),
    q(NEAR + "Art lies in cherishing the initiative and CREATIVE POWER of each person.", ["gift", "strength", "potential", "mind"], C, "Creative power here is each person's capacity to create — their potential."),
    q(NEAR + "As the triumphant rebels were returning to their base, they met with a SERIOUS REVERSE.", ["an enemy", "an army", "a victory", "a defeat"], D, "A reverse is a setback in fortune; for triumphant rebels, a serious reverse is a defeat."),
    q(NEAR + "The Conference Centre caters for TRANSIENTS only.", ["permanent guests", "professionals", "novices", "temporary guests"], D, "Transients are people who stay only briefly — temporary guests."),
  ];

  QUESTION_BANK.english = QUESTION_BANK.english.concat(passages, flat);
})();
