/**
 * JAMB/UTME 2012 — GOVERNMENT
 * From the 2012 question paper (questions 2–50; Q1 only asked for the paper type); answers from the
 * JAMB/UTME Government answer key 2001–2020, each checked independently.
 */
(function () {
  const Y = 2012;
  const SRC = 'JAMB UTME 2012';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  QUESTION_BANK.government = QUESTION_BANK.government.concat([
    // paper 2–11
    q("The distinctive attribute of a state is the monopoly of",
      ["control", "power", "violence", "justice"], C,
      "Following Max Weber, the state is the only body that successfully claims the monopoly of the legitimate use of physical force (violence) within its territory; other groups may have power, but only the state may lawfully use force."),
    q("State as a political entity refers to",
      ["an organized group within a definite territory", "an association of men in a given society", "a branch of a nation", "a geographical location"], A,
      "A state is a politically organised group of people living within a definite territory under a government that is sovereign: population, territory, government and sovereignty."),
    q("Political values are acquired in any given society through",
      ["political re-orientation", "political campaign", "political socialization", "political indoctrination"], C,
      "Political socialisation is the lifelong process by which people learn the political values, beliefs and attitudes of their society, through the family, school, peers, religion and the mass media."),
    q("In a democratic government, political sovereignty is vested in the",
      ["legislature", "elite", "executive", "electorate"], D,
      "Legal sovereignty lies with the body that makes law, but political sovereignty in a democracy lies with the electorate, the voters who choose and can remove those who govern."),
    q("One judicial function performed by the executive is",
      ["granting of amnesty", "implementing judicial orders", "ensuring obedience to the law", "appointing judges"], A,
      "Through the prerogative of mercy (s.175 and s.212 of the 1999 Constitution) the President or a Governor can pardon, grant amnesty or reduce a sentence, which alters the outcome of the judicial process."),
    q("A governmental system in which constitutional supremacy resides in the center is",
      ["federal", "confederal", "unitary", "parliamentary"], C,
      "In a unitary system supreme constitutional authority is concentrated in the central government, which creates the local units and can change or abolish them.",
      { keyVerdict: 'corrected', keyAnswer: 'A',
        answerNote: "The answer key gives A (federal). In a federation the constitution is supreme, but power is shared between the centre and the federating units, so supremacy does not reside in the centre. Where supreme authority is concentrated at the centre, the system is unitary, so C is the better answer." }),
    q("A political system which empowers the leader with the ultimate responsibility to execute laws is",
      ["autocracy", "presidentialism", "parliamentarianism", "dictatorship"], B,
      "In a presidential system executive power is vested in one person, the president, who is both head of state and head of government and bears final responsibility for executing the laws."),
    q("A bill is a draft which is awaiting the consideration of the",
      ["executive", "party caucus", "legislature", "judiciary"], C,
      "A bill is a proposed law placed before the legislature; it becomes an Act only after the legislature passes it and the executive assents."),
    q("The private ownership of the means of production is a feature of",
      ["capitalism", "socialism", "communalism", "communism"], A,
      "Capitalism rests on private ownership of land, factories and capital, with production for profit in a free market."),
    q("In a feudal system, the two major classes are the serfs and the",
      ["masses", "vassals", "lords", "elite"], C,
      "Feudalism divided society into land-owning lords and the serfs who were tied to the lord's land and worked it in return for protection."),
    // paper 12–21
    q("An example of a country with a flexible constitution is",
      ["South Africa", "Britain", "Benin Republic", "the United States of America"], B,
      "Britain's constitution is flexible: it is largely unwritten and can be changed by an ordinary Act of Parliament, with no special amendment procedure."),
    q("The rule of law is negation of",
      ["equality before the law", "supremacy of the law", "limited power", "absolute power"], D,
      "The rule of law means everyone, including the government, is subject to the law; it is therefore the opposite of absolute or arbitrary power."),
    q("To ensure the rights and freedom of citizens, the powers of the arms of government must be",
      ["fused", "incorporated", "separated", "rotated"], C,
      "Montesquieu argued that liberty is safe only when legislative, executive and judicial powers are held by separate organs, so no one body can make, enforce and judge the law."),
    q("Delegated legislation is made by bodies other than the",
      ["president", "governor", "parliament", "judiciary"], C,
      "Delegated legislation is law made by ministers, local councils, public corporations or other bodies under powers given to them by an Act of parliament, the body that normally makes law."),
    q("The bringing of a session of a parliament to an end through royal proclamation is known as",
      ["political impasse", "dissolution of parliament", "vote of no confidence", "prorogation of parliament"], D,
      "Prorogation ends a session of parliament by royal proclamation without ending the parliament itself; the same members return for the next session."),
    q("The right of citizens to participate in the affairs of government of their country is called",
      ["economic right", "civil right", "political right", "social right"], C,
      "Political rights are the rights to take part in government: to vote, to be voted for, to join parties and to hold public office."),
    q("The commission charged with the conduct of federal elections in Nigeria is",
      ["NEC", "FEDECO", "INEC", "NECON"], C,
      "The Independent National Electoral Commission (INEC), set up in 1998, conducts federal elections in Nigeria; FEDECO, NEC and NECON were its earlier forms."),
    q("An electoral system in which parties are assigned seats in the parliament commensurate to the number of votes polled is",
      ["absolute majority", "simple majority", "proportional representation", "indirect election"], C,
      "Under proportional representation each party receives a share of seats in proportion to its share of the votes."),
    q("An intra-party activity for the selection of candidates for elective positions is known as",
      ["primary election", "general election", "mid-term election", "bye-election"], A,
      "A primary election is held within a party to choose the candidate who will carry its flag at the general election."),
    q("The primary aim of pressure groups is to",
      ["attract people's attention", "protect the interest of members", "capture political power", "fight corrupt officials"], B,
      "Pressure groups influence government policy to protect and promote their members' interests; unlike parties, they do not seek to capture power."),
    // paper 22–31
    q("Which of the following is used in gauging public opinion?",
      ["Constitution", "Educational institution", "Mass media", "Electoral college"], C,
      "Newspapers, radio, television and opinion polls carried in the media reveal and measure what the public thinks about issues and leaders."),
    q("A permanent structure that facilitates continuity and guarantees orderly conduct in governance is",
      ["bureaucracy", "public corporation", "ombudsman", "political party"], A,
      "The bureaucracy (civil service) is permanent: politicians come and go, but career officials stay, keep records and carry on government business in an orderly way."),
    q("In the Hausa pre-colonial political system, a district was headed by",
      ["Hakimi", "Dagaci", "Alkali", "Waziri"], A,
      "In the Hausa-Fulani emirates districts were run by the Hakimi (district head), villages by the Dagaci (village head); the Alkali was a judge and the Waziri the chief adviser."),
    q("Which of the following ensured the practice of democracy in the pre-colonial Yoruba political system?",
      ["Checks and balances", "Fusion of power", "Individual responsibility", "The rule of law"], A,
      "The Yoruba system checked the Oba (Alaafin) through the Oyo Mesi, the Ogboni and the Aare Ona Kakanfo, so no one could rule absolutely."),
    q("Colonization of Africa was mainly motivated by",
      ["security considerations", "economic reasons", "religious reasons", "cultural factors"], B,
      "European powers colonised Africa mainly for raw materials, markets for their manufactured goods and outlets for investment after the Industrial Revolution."),
    q("The French colonial system was underlined by the policy of",
      ["assimilation", "paternalism", "socialism", "indirect rule"], A,
      "France's policy of assimilation aimed to turn Africans into French citizens in language, culture and law; indirect rule was the British method."),
    q("Radical nationalism in Nigeria is generally attributed to the influence of",
      ["Aminu Kano", "Herbert Macaulay", "Nnamdi Azikiwe", "Mbonu Ojike"], C,
      "After returning from the Gold Coast in 1937, Nnamdi Azikiwe used the West African Pilot and the Nigerian Youth Movement to spread a militant, mass-based nationalism, later carried on by the Zikist Movement.",
      { keyVerdict: 'corrected', keyAnswer: 'B',
        answerNote: "The answer key gives B (Herbert Macaulay). Macaulay is called the father of Nigerian nationalism, but the radical, mass-based phase of nationalism is generally credited to Nnamdi Azikiwe after his return from the Gold Coast in 1937, through the West African Pilot, the Nigerian Youth Movement and later the Zikist Movement. So C is the better answer." }),
    q("Two foreigners that directly aroused nationalist feelings among Nigerians are",
      ["Edward Blyden and Payne Jackson", "Casely Hayford and James Horton", "W.E.B. Du Bois and H.O. Davies", "Marcus Garvey and Casely Hayford"], A,
      "Edward Wilmot Blyden and John Payne Jackson, both from Liberia, lived and worked in Lagos, where Blyden's lectures and Jackson's Lagos Weekly Record directly stirred African pride and opposition to colonial rule."),
    q("Members of the Senate in Nigeria's First Republic were",
      ["elected directly by the people", "elected by electoral college", "nominated by regional and federal governments", "nominated by the president of the house"], C,
      "First Republic senators were not elected by the people: most were chosen through the regional governments and legislatures (12 per region), with a few for Lagos and four appointed on the Prime Minister's advice."),
    q("In Nigeria, the agency mainly responsible for the maintenance of internal peace and security is the",
      ["Army", "Navy", "Civil Defence Corps", "Police"], D,
      "The Nigeria Police Force is the main agency for internal security, law and order; the armed forces mainly defend the country against external attack."),
    // paper 32–41
    q("The National Assembly in Nigeria is primarily responsible for",
      ["executing laws", "interpreting laws", "ratifying appointments", "making laws"], D,
      "The National Assembly (Senate and House of Representatives) is Nigeria's federal legislature; its primary function is law-making (s.4, 1999 Constitution)."),
    q("The major factor militating against the efficient operation of electoral commissions in Nigeria is",
      ["inadequate public support", "population size", "inadequate skilled manpower", "excessive political interference"], D,
      "Nigerian electoral commissions have been weakened mainly by interference from governments and politicians, through appointments, funding and pressure on officials."),
    q("A major objective of the Public Complaints Commission is",
      ["training and promotion of public servants", "settlement of disputes among individuals", "addressing the grievances of individuals and groups", "fighting corruption and indiscipline"], C,
      "The Public Complaints Commission, Nigeria's ombudsman (set up in 1975), investigates complaints by individuals and groups against public officials and agencies."),
    q("The three registered political parties at the inception of Nigeria's Fourth Republic were",
      ["PDP, DPP and PPA", "PDP, AD and APP", "PDP, AD and PPA", "PDP, APP and AC"], B,
      "For the 1998–99 transition elections only three parties were registered: the Peoples Democratic Party (PDP), the Alliance for Democracy (AD) and the All People's Party (APP)."),
    q("The Sharia legal system was first introduced in the Fourth Republic in",
      ["Kano State", "Katsina State", "Zamfara State", "Sokoto State"], C,
      "Zamfara State under Governor Ahmed Sani Yerima was the first to extend Sharia to criminal law, announcing it in October 1999 with effect from January 2000; other northern states followed."),
    q("Quota system and federal character principles were entrenched in the 1979 constitution to ensure",
      ["loyalty", "economic empowerment", "equity", "even development"], C,
      "The quota system and federal character spread appointments and opportunities fairly among the states and groups, so that no section dominates; their aim is equity.",
      { keyVerdict: 'multiple', alsoAccept: [A], keyAnswer: 'C',
        answerNote: "Option A is also correct. Section 14(3) of the 1979 Constitution says federal character is applied to promote national unity and also to command national loyalty, by making sure no few states or groups dominate. So both equity and loyalty are aims stated or implied by the constitution." }),
    q("Workers in the public corporations are known as",
      ["civil servants", "private employees", "public servants", "professional employees"], C,
      "Staff of public corporations are public servants; civil servants are those who work in government ministries and departments."),
    q("The central objective of privatization in Nigeria is to",
      ["reduce the retrenchment of workers", "encourage prompt payment of salaries", "improve standard of living", "improve the efficiency of enterprises"], D,
      "Privatisation sells government-owned enterprises to private investors mainly to make them efficient and profitable and to end the drain on public funds."),
    q("Military intervention in Nigeria arose from",
      ["perceived incapability of civilians to govern", "international pressure for change", "the desire for a military government", "civilians' desire to relinquish power"], A,
      "Coup plotters (1966, 1983 and others) justified their seizures of power by pointing to civilian corruption, rigged elections and crises, that is, the civilians' perceived failure to govern."),
    q("The first institution introduced by the military to exercise legislative power was the",
      ["Supreme Military Council", "Armed Forces Ruling Council", "Federal Executive Council", "Provisional Ruling Council"], A,
      "After the January 1966 coup, Ironsi's Decree No. 1 vested law-making power in the Supreme Military Council; the AFRC (1985) and PRC (1993) came later."),
    // paper 42–50
    q("The main focus of Nigeria's foreign policy since independence centers on",
      ["South-South cooperation", "sub-regionalism", "globalism", "Afrocentrism"], D,
      "Since 1960 Africa has been the centrepiece of Nigeria's foreign policy: African unity, decolonisation, the fight against apartheid and the welfare of Africans."),
    q("The country that championed decolonization in Africa was",
      ["Nigeria", "South Africa", "Ghana", "Kenya"], C,
      "Ghana under Kwame Nkrumah, the first black African colony south of the Sahara to win independence (1957), led the call for the total liberation of Africa.",
      { keyVerdict: 'multiple', alsoAccept: [A], keyAnswer: 'C',
        answerNote: "Option A is also correct. Ghana under Kwame Nkrumah led the call for Africa's total liberation from 1957, and Nigeria made decolonisation and the end of apartheid the centrepiece of its foreign policy, backing liberation movements in Angola, Zimbabwe, Namibia and South Africa." }),
    q("A major drawback to the NEPAD initiative is its",
      ["articulation by few African leaders", "affiliation by few African union", "inability to empower the youth", "reliance on Western donors for funds"], D,
      "NEPAD (2001) depends heavily on aid and investment from Western donors and the G8, which limits African ownership of its programmes."),
    q("The structures of the African Union include",
      ["the court of justice, pan African congress and people's Assembly", "pan African parliament, the court of justice and the peace and security council", "specialized Technical commission, the court of justice and humanitarian board", "people's Assembly, Humanitarian Board and the peace and security council"], B,
      "The African Union's organs include the Assembly, the Executive Council, the Commission, the Pan-African Parliament, the Court of Justice and the Peace and Security Council."),
    q("ECOMOG at the initial stage of its intervention in Liberia was perceived as",
      ["neutral", "incompetent", "partisan", "invaders"], D,
      "When ECOMOG landed in Liberia in August 1990, Charles Taylor's NPFL, which held most of the country, rejected it as a foreign invading force and fought it."),
    q("One of the programmes binding members of the Commonwealth is the",
      ["food and aid programme", "cultural programme", "agenda for peace", "scholarship scheme"], D,
      "The Commonwealth Scholarship and Fellowship Plan (1959) lets citizens of member countries study in other member countries; it is one of the Commonwealth's best-known joint programmes."),
    q("The African leader mostly credited for spearheading the formation of the African Union is",
      ["Muammar Ghaddafi", "Abdelaziz Bouteflika", "Abdoulaye Wade", "Thabo Mbeki"], A,
      "Libya's Muammar Gaddafi called the 1999 OAU summit at Sirte, whose Sirte Declaration (9 September 1999) launched the African Union, formally born in Durban in 2002."),
    q("As part of the reforms in the UN, two slots were proposed in the Security Council for",
      ["Asia", "Africa", "America", "Europe"], B,
      "In UN reform debates Africa, through the Ezulwini Consensus (2005), demands two permanent seats with veto power on the Security Council, plus extra non-permanent seats. No reform has yet been adopted."),
    q("The founding members of OPEC are",
      ["Algeria, Iran, Iraq, Saudi Arabia and Kuwait", "Nigeria, Libya, Iraq and Saudi Arabia", "Venezuela, Nigeria, Libya, Iran and Iraq", "Saudi Arabia, Iran, Iraq, Kuwait and Venezuela"], D,
      "OPEC was founded in Baghdad in September 1960 by Iran, Iraq, Kuwait, Saudi Arabia and Venezuela; Nigeria joined in 1971."),
  ]);
})();
