/**
 * JAMB/UTME 2016 — GOVERNMENT
 * From the 2016 question paper (questions 1–50); answers from the JAMB/UTME Government answer key
 * 2001–2020, each checked independently. Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2016;
  const SRC = 'JAMB UTME 2016';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  QUESTION_BANK.government = QUESTION_BANK.government.concat([
    // paper 1–10
    q("A major opposition party at the national level in Nigeria's Second Republic was",
      ["NPP", "UPN", "PRP", "GNPP"], B,
      "In the Second Republic (1979–83) the NPN of Shehu Shagari formed the federal government, and Obafemi Awolowo's Unity Party of Nigeria (UPN), which came second in the 1979 presidential election, led the opposition."),
    q("The exclusion of Africans from colonial administration is associated with",
      ["policy of assimilation", "indirect rule system", "policy of association", "indigénat policy"], A,
      "Under the French policy of assimilation only Africans who had become French citizens (the évolués) could take part in administration; the great majority, treated as 'subjects', were shut out of it."),
    q("During the 1964 federal election in Nigeria, the United Progressive Grand Alliance comprised the",
      ["NNDP, NPC and NDC", "NPC, UMBC and BYM", "UMBC, AG, NEPU and NCNC", "UMBC, BYM, NEPU and NPC"], C,
      "For the 1964 federal election the NCNC and the Action Group allied with their northern partners NEPU and the UMBC to form the UPGA; it faced the NPC-led Nigerian National Alliance (NNA)."),
    q("Which of the following binds Commonwealth nations together?",
      ["Uniform political system", "Common currency", "Common language", "Common colonial history"], D,
      "The Commonwealth is a voluntary association of states that, with few exceptions, were once part of the British Empire; their shared colonial history under Britain is what binds them."),
    q("A structure of government in which power is shared between the centre and the units is",
      ["confederal", "oligarchic", "unitary", "federalism"], D,
      "Federalism divides governmental power by the constitution between a central government and component units (states or regions), each supreme in its own sphere."),
    q("Which of the following performs oversight functions?",
      ["Judiciary", "Civil Service", "Executive", "Legislature"], D,
      "The legislature oversees the executive: its committees investigate ministries and agencies, scrutinise spending and summon officials, to make sure laws and budgets are carried out properly."),
    q("Foreign policy refers to",
      ["a policy made by a country when it is at war", "the general principles of a state's international behaviour", "a policy made by a foreign country", "a policy made by a country for foreigners"], B,
      "Foreign policy is the set of principles, goals and strategies that guide a state's dealings with other states and international organisations."),
    q("\"From each according to his ability, to each according to his needs\" is the principle of",
      ["communism", "socialism", "capitalism", "communalism"], A,
      "Karl Marx used this slogan for the final stage of society, communism, where goods are so plentiful that everyone works as he can and takes what he needs; socialism's rule is 'to each according to his work'."),
    q("The maintenance of law and order is a function of the",
      ["legislature", "military", "judiciary", "executive"], D,
      "The executive implements laws and keeps law and order, mainly through the police and other security agencies under its control."),
    q("The development of attitudes and beliefs about a political system is known as",
      ["political orientation", "political apathy", "political culture", "political socialization"], D,
      "Political socialisation is the process through which people develop and acquire political attitudes, beliefs and values, through the family, school, peers, religion, the media and parties."),
    // paper 11–20
    q("A nation could be identified through its",
      ["military strength", "common language and culture", "population", "constitution"], B,
      "A nation is a group of people bound by a common language, culture, history or descent and a feeling of oneness."),
    q("A network of groups of people in an institution expressing human association is",
      ["community", "society", "nation", "state"], B,
      "A society is the whole network of groups and relationships through which people live and associate together: families, clubs, churches, mosques, unions and so on."),
    q("The Commission of Mediation, Conciliation and Arbitration is an organ of",
      ["the United Nations", "the Commonwealth", "the Organisation of Petroleum Exporting Countries", "the African Union"], D,
      "The Commission of Mediation, Conciliation and Arbitration was set up in 1964 as one of the main organs of the OAU, the body the African Union replaced; today the AU handles disputes through its Peace and Security Council."),
    q("The policy of assimilation was the colonial policy of the",
      ["French", "British", "Portuguese", "German"], A,
      "France's policy of assimilation aimed to turn Africans into Frenchmen in language, culture and law, so that assimilated Africans could become French citizens."),
    q("The appointment, promotion and discipline of civil servants is the responsibility of the",
      ["Civil Service Commission", "Public Complaints Commission", "Judicial Service Commission", "Public Service Institute of Nigeria"], A,
      "The Civil Service Commission (federal or state) appoints, promotes and disciplines civil servants, keeping these decisions out of the hands of politicians."),
    q("A country is said to operate an unwritten constitution if the",
      ["constitution is not contained in a single document", "constitution cannot be written down", "existing constitution can be suspended at will", "country does not have a printed constitution"], A,
      "An unwritten constitution, like Britain's, is not gathered in one document; its rules are scattered in statutes, court decisions, conventions and the writings of authorities."),
    q("The form of government headed by a king is",
      ["monarchy", "presidentialism", "fascism", "republicanism"], A,
      "A monarchy is headed by a king or queen who usually inherits the throne; a republic is headed by an elected or appointed president."),
    q("Citizens exercise their sovereignty by",
      ["attending political rallies", "voting at elections", "registration to vote", "their right to sue the state"], B,
      "In a democracy sovereignty belongs to the people, and they exercise it mainly by voting at elections to choose, renew or remove those who govern them."),
    q("Which of these is an attribute of government?",
      ["Political power", "Sovereignty", "Constitution", "Definite territory"], A,
      "Government is the machinery through which the state's will is carried out, and what marks it is the political power to make, enforce and interpret laws; sovereignty and a definite territory are attributes of the state."),
    q("The Nigerian judiciary is headed by the",
      ["Attorney-General and Minister of Justice", "Solicitor-General of the Federation", "Chief Justice of the Federation", "President, Court of Appeal"], C,
      "The head of the Nigerian judiciary is the Chief Justice (officially the Chief Justice of Nigeria), who heads the Supreme Court and chairs the National Judicial Council."),
    // paper 21–30
    q("The modern theory of sovereignty was popularised by",
      ["John Locke", "Thomas Hobbes", "Jean Bodin", "Baron de Montesquieu"], C,
      "The French jurist Jean Bodin set out the modern theory of sovereignty in his Six Books of the Commonwealth (1576), defining it as the absolute and perpetual power of a state."),
    q("Public opinion is commonly referred to as the composite reaction of the citizenry on",
      ["matters relating to association", "legal rights of foreigners", "matters affecting government", "key issues that affect them"], D,
      "Public opinion is the combined view of a large part of the citizens on important public issues that affect them, expressed through the media, polls, protests and votes."),
    q("In order to assist fellow developing countries, Nigeria initiated the",
      ["New Partnership for African Development", "Economic Community of West African States", "Concert of Medium Powers", "Technical Aid Corps Scheme"], D,
      "The Technical Aid Corps, started in 1987 under Babangida on Bolaji Akinyemi's proposal, sends young Nigerian professionals (doctors, teachers, engineers) to serve in other African, Caribbean and Pacific countries."),
    q("In the Igbo traditional system, the highest democratic institution is the",
      ["Umunna", "Oha-na-eze", "Umuada", "Ofo title holders"], B,
      "The Oha-na-eze, the general assembly of the village in which every adult male could speak, was the highest decision-making body of the pre-colonial Igbo and the clearest sign of their democracy."),
    q("Separation of powers as an ingredient of the presidential system implies the",
      ["distinction of governmental power", "demarcation of levels of government", "distinction between head of state and head of government", "sharing of governmental powers"], D,
      "Separation of powers means that the powers of government are shared out among three separate organs, the legislature, the executive and the judiciary, each with its own functions and personnel."),
    q("The major objective of a pressure group is to",
      ["change government", "form government", "influence government", "fund elections"], C,
      "A pressure group seeks to influence government policy in favour of its members' interests; unlike a party, it does not seek to win elections or form a government."),
    q("The foreign policy principle that informed Nigeria's position in the liberation of African states is",
      ["economic diplomacy", "Afrocentrism", "non-alignment", "non-interference"], B,
      "Afrocentrism, making Africa the centrepiece of Nigeria's foreign policy, led Nigeria to support liberation movements in Angola, Mozambique, Zimbabwe, Namibia and South Africa."),
    q("A type of political association that brings the rich and the poor together is a",
      ["broker party", "charismatic party", "elite party", "mass party"], A,
      "A broker party draws its members from all classes, rich and poor alike, and tries to reconcile their different interests by bargaining and compromise."),
    q("In Nigeria, the foundations of federalism were laid by the",
      ["Macpherson Constitution", "Lyttelton Constitution", "Clifford Constitution", "Richards Constitution"], D,
      "The Richards Constitution of 1946 divided Nigeria into three regions (North, West and East) with regional houses of assembly, laying the foundation on which the Lyttelton Constitution of 1954 built a full federation."),
    q("Which of the following is a form of delegated legislation?",
      ["Case law", "Convention", "Edict", "Acts"], C,
      "Under military rule, state military governors made edicts only under powers given to them by the federal military government's decrees, so an edict was law made by a subordinate authority under delegated power; Acts are made by the legislature itself, and case law comes from the courts."),
    // paper 31–40
    q("Franchise can be described as the right to",
      ["vote at elections", "form political parties", "vote and be voted for", "contest in elections"], C,
      "Franchise is the right to take part in elections; Nigerian textbooks usually define it as the right of qualified citizens to vote and be voted for, while in the narrow sense it is simply the right to vote.",
      { keyVerdict: 'multiple', alsoAccept: [A], keyAnswer: 'C',
        answerNote: "A is also accepted. In its strict sense franchise (suffrage) means the right to vote at elections (A); many Nigerian textbooks widen it to the right to vote and be voted for (C). Both describe franchise correctly." }),
    q("A major factor that necessitated the adoption of federalism in Nigeria was the",
      ["intention of creating states", "diversity of culture and language", "abundance of natural resources", "low level of literacy"], B,
      "Nigeria's many ethnic groups, languages, religions and cultures made federalism the natural choice: it allows unity at the centre while each group keeps some self-rule."),
    q("The office of the Prime Minister in Nigeria was created in",
      ["1951", "1954", "1959", "1957"], D,
      "The office of Prime Minister of the Federation was created in 1957, after the London constitutional conference of that year, and Alhaji Abubakar Tafawa Balewa became Nigeria's first Prime Minister on 30 August 1957."),
    q("The Nigeria Police is an agency of the",
      ["judicial arm of government", "Ministry of Defence", "executive arm of government", "Ministry of Interior"], C,
      "The police enforce laws and keep order, which is the work of the executive; the Nigeria Police is under the President, the Inspector-General of Police and the Police Service Commission."),
    q("The legislature checks the excesses of the executive through",
      ["appointment of civil servants", "screening of governors", "scrutiny of the budget", "nomination of judges"], C,
      "The executive cannot spend public money without the legislature's approval, so by scrutinising and passing (or cutting) the budget, the legislature controls the executive's plans and spending."),
    q("Government by the best citizens is referred to as",
      ["aristocracy", "democracy", "oligarchy", "plutocracy"], A,
      "Aristocracy (from the Greek aristos, 'best') is rule by the few best or noblest citizens, governing for the good of all."),
    q("The charter establishing the AU was signed in",
      ["Togo", "Libya", "South Africa", "Ethiopia"], A,
      "The Constitutive Act of the African Union was adopted and signed at Lomé, Togo, on 11 July 2000; the idea came from the Sirte Declaration in Libya (1999), and the AU was launched in Durban, South Africa, in July 2002."),
    q("In Nigeria, items in the exclusive list are under the jurisdiction of the",
      ["regional government", "central government", "local government", "state government"], B,
      "Matters on the Exclusive Legislative List, such as defence, foreign affairs, currency and the police, can be handled only by the central (federal) government."),
    q("Which of these factors motivated colonialism in Africa?",
      ["Cultural superiority", "Scientific superiority", "Humanitarianism", "Economic interest"], D,
      "Europe colonised Africa mainly for economic reasons: raw materials for its factories after the Industrial Revolution, markets for its goods and outlets for its capital."),
    q("The responsibility of giving policy guidelines to the board of a corporation rests with the",
      ["Board of Directors", "Minister", "Chairman", "Permanent Secretary"], B,
      "A public corporation runs its daily affairs under its board, but the supervising minister gives the board general policy directions in the public interest and answers for the corporation to the legislature."),
    // paper 41–50
    q("Which of these institutions makes bye-laws?",
      ["Council of State", "National Assembly", "Local Government Council", "State House of Assembly"], C,
      "Bye-laws are laws made by local government councils for their own areas, such as rules on markets, motor parks and sanitation, under powers given by state law."),
    q("Which of the following commissions was established by the 1979 Constitution?",
      ["Economic and Financial Crimes Commission", "Federal Character Commission", "Federal Road Safety Commission", "Federal Electoral Commission"], D,
      "The 1979 Constitution listed the Federal Electoral Commission (FEDECO) among the federal executive bodies; FEDECO conducted the 1979 and 1983 elections and was later replaced, finally by INEC under the 1999 Constitution."),
    q("Federal and state governments legislate on items in the",
      ["residual list", "legislative list", "exclusive list", "concurrent list"], D,
      "The Concurrent Legislative List holds matters on which both the federal and state governments can make laws, though federal law prevails if the two conflict."),
    q("In Nigeria, public corporations are established by",
      ["executive order", "a bye-law", "an act of parliament", "military decree"], C,
      "A public corporation is a body set up by an Act of the legislature (statute), which defines its functions, powers, board and relationship with its supervising ministry."),
    q("In the Hausa pre-colonial political system, the spiritual and political powers were vested in the",
      ["Emir", "Madawaki", "Galadima", "Waziri"], A,
      "In the Hausa-Fulani emirates the Emir was both the political head and the religious leader under Islam, holding executive, legislative, judicial and spiritual authority."),
    q("Which of the following approves the annual budget of the UN?",
      ["The General Assembly", "The Secretariat", "The Security Council", "The Trusteeship Council"], A,
      "Under Article 17 of the UN Charter, the General Assembly considers and approves the UN's budget and shares out the expenses among member states."),
    q("Lagos was annexed in",
      ["1861", "1971", "1814", "1853"], A,
      "Britain annexed Lagos in August 1861, when Oba Dosunmu was made to sign the treaty of cession; Lagos became a British colony in 1862."),
    q("A disadvantage of the one-party system is that it",
      ["is costly to operate", "does not tolerate opposition", "does not care about the feelings of the masses", "discourages periodic elections"], B,
      "A one-party state allows only one legal party, so organised opposition is banned and voters have no real alternative; this can lead to dictatorship."),
    q("At the formation of the OAU, Nigeria belonged to the",
      ["Monrovia group", "Casablanca group", "Lagos group", "Brazzaville group"], A,
      "Before 1963 Africa was split between the radical Casablanca group (led by Ghana's Nkrumah), which wanted immediate political union, and the moderate Monrovia group, which Nigeria belonged to and which favoured gradual cooperation among sovereign states."),
    q("The ECOWAS Monitoring Group began its operation in",
      ["Sierra Leone", "Guinea", "Gambia", "Liberia"], D,
      "ECOMOG, the ECOWAS Ceasefire Monitoring Group, was formed in 1990 and first deployed to Liberia in August 1990 to end the civil war there; it later served in Sierra Leone and Guinea-Bissau."),
  ]);
})();
