/**
 * JAMB/UTME 2002 — GOVERNMENT
 * From the 2002 question paper (all 50 questions); answers from the JAMB/UTME Government answer key
 * 2001–2020, each checked independently. Printing errors carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2002;
  const SRC = 'JAMB UTME 2002';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  QUESTION_BANK.government = QUESTION_BANK.government.concat([
    // paper 1–10
    q("Delegated legislation becomes unavoidable when",
      ["legislators cannot reach a consensus", "issues under consideration are personal", "issues under consideration are technical", "legislators have to proceed on a recess"], C,
      "Legislators are not experts in every field, so technical details (for example on health, transport or engineering standards) are left to ministries and agencies to make as regulations under a parent act."),
    q("One major disadvantage of public opinion is that",
      ["the critics of government policies are always harassed", "a vocal minority claims to represent the majority", "gossip and rumours thrive", "leaders are unnecessarily criticized"], B,
      "Public opinion is hard to measure, so a small but loud group can claim to speak for the majority and mislead government."),
    q("Citizenship in a modern state expresses the status of a person who possesses",
      ["full political rights", "some religious rights", "social rights only", "exclusive economic rights"], A,
      "A citizen is a full member of the state, enjoying the full political rights (to vote, be voted for and hold public office) that aliens do not have."),
    q("Communism is a system which recognizes",
      ["class stratification", "the existence of the state", "the existence of the individual", "the ability of the individual"], D,
      "The communist principle is \"from each according to his ability, to each according to his needs\": everyone works according to his ability in a classless, stateless society.",
      { keyVerdict: 'corrected', keyAnswer: 'C',
        answerNote: "Option D is the better answer. Every system recognizes that individuals exist, so C tells us nothing about communism; what marks communism out is Marx's rule \"from each according to his ability, to each according to his needs\", which is about the ability of the individual. A and B are what communism seeks to abolish (classes and, in the end, the state)." }),
    q("The delineation of constituencies is a major duty of the",
      ["national assembly", "political parties", "boundary commission", "electoral commission"], D,
      "In Nigeria the electoral commission (INEC today) divides the country into constituencies, reviewing them after each census; some countries give the job to a separate boundary commission.",
      { keyVerdict: 'multiple', alsoAccept: [C], keyAnswer: 'D',
        answerNote: "Option C is also correct. In Nigeria the electoral commission draws constituency boundaries (as in D), but in many countries, such as Britain, and in Nigeria before 1960 (the Constituency Delimitation Commission), a boundary commission does the same job. The question does not say which country, so either is accepted." }),
    q("The structure of the civil service is based on",
      ["lateral organization", "merit system", "patronage system", "hierarchical organization"], D,
      "The civil service is arranged as a hierarchy: a chain of grades from the Permanent Secretary at the top down to the lowest officer, each answerable to the one above."),
    q("A common feature of a multi-party system is that government is formed by",
      ["the major political parties", "all the registered political parties", "a coalition of political parties", "the party with the highest votes"], C,
      "With many parties, no single party often wins a majority, so two or more parties must join together in a coalition to form a government."),
    q("To qualify for absorption into the administrative cadre of the civil service in Nigeria, an applicant must be",
      ["knowledgeable in civil service rules", "holder of a first university degree", "specifically trained in public administration", "a senior civil servant"], B,
      "Entry into the administrative (policy-making) cadre of the Nigerian civil service requires at least a first university degree or its equivalent, in any discipline."),
    q("The final interpretation of the provisions of a federal constitution is vested in the",
      ["head of state", "council of state", "highest legislative body", "highest court of the land"], D,
      "In a federation the highest court (Nigeria's Supreme Court) is the final interpreter of the constitution and settles disputes between the centre and the units."),
    q("A major issue that distinguishes pressure groups from political parties is",
      ["membership drive", "the objective", "the voting pattern", "ideology"], B,
      "Their objectives differ: a party aims to win elections and control government, while a pressure group only seeks to influence government policy in its members' interest."),
    // paper 11–20
    q("Proportional representation is a system of allocating seats in the legislature based on",
      ["gender participation in politics", "an area's involvement in politics", "contribution to the national economy", "total votes in an election"], D,
      "Under proportional representation each party gets seats in proportion to its share of the total votes cast."),
    q("The application of the principle of separation of powers seems impracticable because power is",
      ["delegated", "centralized", "fused", "separated"], C,
      "In practice the organs overlap (most clearly in the parliamentary system, where ministers sit in the legislature), so power is fused and a strict separation cannot be achieved."),
    q("One major factor that differentiates the presidential from the parliamentary system is",
      ["separation of powers", "judicial independence", "passage of bills", "party system"], A,
      "The presidential system rests on separation of powers (an executive that is not part of the legislature); the parliamentary system rests on fusion of powers."),
    q("A major consequence of proportional representation is that it",
      ["reduces the chances of political instability", "favours the developments of a two-party system", "discourages voting along ethnic lines", "encourages the proliferation of parties"], D,
      "Because even small parties win seats with a modest share of votes, proportional representation encourages many parties to form."),
    q("Oligarchy is a form of government which",
      ["enhances the interest of the ruling few", "enhances the electoral chances of the majority", "disregards the views of the minority", "protects the interest of the common people"], A,
      "Oligarchy is rule by a small group who govern mainly in their own interest."),
    q("The absence of the rule of law in government will bring about",
      ["human rights abuse", "treasonable offences", "corrupt practices", "political apathy"], A,
      "Without the rule of law, rulers act arbitrarily, so citizens' rights are abused: arrest without trial, detention, denial of fair hearing."),
    q("Centralization of power is the basic feature of",
      ["federalism", "a confederation", "a presidential system", "a unitary government"], D,
      "In a unitary state all governmental power is concentrated in one central government, which may delegate some of it to local units."),
    q("A law passed by the legislature and assented to by the executive is",
      ["an act", "a presidential proclamation", "a decree", "a legislative order"], A,
      "A bill becomes an act (a law) once the legislature passes it and the executive assents to it."),
    q("One of the features of a sovereign state is that it",
      ["has the capacity to defend itself from external aggression", "has a large number of soldiers", "practices the presidential system of government", "is not indebted to other countries"], A,
      "A sovereign state is independent of outside control, which means it must be able to defend its territory and independence against external attack."),
    q("A major way of maintaining confidence in the electoral process is by ensuring that",
      ["electoral officers are regularly trained", "elections are conducted in a free and fair atmosphere", "unlimited franchise is observed", "elections are conducted as and when due"], B,
      "People trust an electoral process when voting is free (without intimidation) and fair (without rigging), so results reflect their choice."),
    // paper 21–30
    q("The principle of checks and balances reinforces separation of power in order to",
      ["protect the powers of the executive", "make the legislature more powerful", "prevent an unconstitutional change of government", "prevent the emergence of dictatorship"], D,
      "Checks and balances let each organ restrain the others, so no single person or organ can gather all power and become a dictator."),
    q("Legislative control of public corporations in Nigeria is effected through",
      ["the dissolution of their managements", "the reorganization of their boards", "acts of the National Assembly", "bye-laws"], C,
      "Public corporations are created by acts of the legislature, which can amend those acts, approve their funds and investigate them."),
    q("The Ibadan Conference of 1950 was convened to discuss the provision of the",
      ["Macpherson Constitution", "Clifford Constitution", "Lyttleton Constitution", "Richards Constitution"], A,
      "The General Conference at Ibadan (January 1950) reviewed the Richards Constitution and agreed the proposals that became the Macpherson Constitution of 1951."),
    q("The fees collected by local governments at motor parks represent",
      ["levies", "fines", "income tax", "user charge"], A,
      "Motor park fees are levies: the Taxes and Levies (Approved List for Collection) Act lists \"motor park levies\" among the charges local governments may collect."),
    q("The first Nigerian constitution to provide for the fundamental objectives and directive principles of state policy was the",
      ["1979 Constitution", "1989 Constitution", "1999 Constitution", "1960 Constitution"], A,
      "The 1979 Constitution (Chapter II) was the first to set out the Fundamental Objectives and Directive Principles of State Policy; the 1989 and 1999 constitutions copied it.",
      { keyVerdict: 'misprint',
        answerNote: "The paper printed \"derivative principles\"; the correct name is \"directive principles\" of state policy. The answer is unchanged." }),
    q("Under the 1999 Constitution of Nigeria, the power to create local government is vested in the",
      ["state assembly", "office of the deputy governor", "presidency", "national assembly"], A,
      "Section 8(3) of the 1999 Constitution lets a State House of Assembly pass a law to create a new local government area (the National Assembly must then list it)."),
    q("The body set up to review the revenue allocation formula in 1980 was the",
      ["Udoji Commission", "Okigbo Commission", "Dina Commission", "Adebo Commission"], B,
      "The Okigbo Commission (1979–1980), headed by Pius Okigbo, reviewed revenue allocation under the Second Republic."),
    q("In pre-colonial Igbo society, decisions on public issues were reached mainly through",
      ["the oracles", "consensus", "imposition", "majority votes"], B,
      "Igbo society was acephalous (no central king); public matters were discussed openly by the village assembly and elders until everyone agreed, so decisions were by consensus."),
    q("The main duty of the Local Government Service Commission is to",
      ["supervise and manage the affairs of the local governments", "create job opportunities at the local level", "handle requests for the creation of more local governments", "conduct elections into local councils"], A,
      "The Local Government Service Commission manages the local government service: appointing, promoting and disciplining its senior staff, and so overseeing how councils are run."),
    q("The constitution that introduced restricted franchise into Nigerian politics was the",
      ["Independence Constitution", "Lyttleton Constitution", "Richards Constitution", "Clifford Constitution"], D,
      "The Clifford Constitution of 1922 introduced the elective principle, but only adult males in Lagos and Calabar earning at least £100 a year could vote: a restricted franchise."),
    // paper 31–40
    q("In Nigeria, the Council of State was first created by",
      ["General Murtala Muhammed", "General Olusegun Obasanjo", "Major-General Aguiyi Ironsi", "General Yakubu Gowon"], A,
      "The Murtala Muhammed regime set up the National Council of States (the state military governors) in 1975, alongside the Supreme Military Council and the Federal Executive Council."),
    q("The leading agent in the expansion of British influence in Northern Nigeria in the 1890s was the",
      ["British Consul in Calabar", "Royal West African Frontier Force", "British Consul in Lagos", "Royal Niger Company"], D,
      "Goldie's Royal Niger Company (chartered 1886) made treaties with northern rulers and governed the Niger–Benue area until its charter was revoked in 1899–1900."),
    q("The two military coups that toppled civilian regimes in Nigeria were those of",
      ["January 1966 and December 1983", "July 1966 and August 1985", "January 1966 and July 1975", "February 1966 and December 1983"], A,
      "The January 1966 coup ended the First Republic (Balewa) and the December 1983 coup ended the Second Republic (Shagari); the others overthrew military governments."),
    q("The main function of the Code of Conduct Bureau is to",
      ["ensure accountability in government business", "give the judiciary more power to discipline erring judges", "protect public officers from the press", "give the police more powers to make arrests"], A,
      "The Code of Conduct Bureau enforces the code of conduct for public officers (for example, asset declaration) to ensure honesty and accountability in public life."),
    q("The emirate system of administration can be likened to a",
      ["confederal system of government", "unitary system of government", "federal system of government", "constitutional monarchy"], B,
      "Power in an emirate was centralised in the emir, who appointed and removed the officials and district heads under him, much like a unitary system."),
    q("The abolition of the state ministries of local government in 1989 entails that local governments",
      ["are equal to the states", "have more control over their funds", "no longer have anything to do with state governments", "are no longer subordinate to state governments"], D,
      "Abolishing the state ministries that supervised them was meant to free local governments from state control, making them a tier of government in their own right. Today states again have ministries of local government, though a 2024 Supreme Court ruling requires federal allocations to be paid to councils directly."),
    q("The main legislative body in Nigeria between 1966 and 1975 was the",
      ["Supreme Military Council", "Armed Forces Ruling Council", "Provisional Ruling Council", "National Security Council"], A,
      "Under Ironsi and Gowon (1966–1975) the Supreme Military Council made laws by decree; the AFRC (1985–1993) and PRC (1993–1999) came later."),
    q("Nigeria formally became a federation in",
      ["1954", "1963", "1914", "1946"], A,
      "The Lyttleton Constitution of 1954 made Nigeria a federation of three regions (North, East, West) with the Federal Territory of Lagos."),
    q("The United Nations charter is an instrument that",
      ["sets out the rights and obligations of member states", "provides for funding of member states", "facilitates the resolution of disputes among member states", "determines the admission of member states"], A,
      "The UN Charter (1945) is the treaty that sets out the purposes and organs of the UN and the rights and obligations of its member states."),
    q("The most active organ of the Economic Community of West African States is the",
      ["Tribunal of the Community", "Technical and Specialized Commissions", "Authority of Heads of State and Government", "Council of Ministers"], C,
      "The Authority of Heads of State and Government is ECOWAS's supreme organ: it directs the Community and takes all major decisions.",
      { keyVerdict: 'misprint',
        answerNote: "The paper printed option B as \"Technical and Specialized Community\"; the ECOWAS bodies are called Technical and Specialized Commissions. The answer is unchanged." }),
    // paper 41–50
    q("The group of states that conceived the idea of the United Nations Organization included",
      ["the USSR, Italy, the UK and China", "Italy, the UK, France and Japan", "the USA, the USSR, the UK and China", "France, the USA, Canada and Japan"], C,
      "The USA, the USSR, the UK and China (the Moscow Declaration of 1943 and the Dumbarton Oaks talks of 1944) planned the UN, founded in 1945."),
    q("The impact of the Commonwealth of Nations is felt most in the area of",
      ["diplomatic cooperation", "economic cooperation", "cultural cooperation", "military cooperation"], B,
      "The Commonwealth's main practical benefits to members have been economic: trade preferences, aid and technical assistance through bodies such as the Commonwealth Fund for Technical Co-operation."),
    q("The greatest criticism of the Security Council of the UNO is that it",
      ["has no standing army", "is not representative enough", "undermines the General Assembly", "has exclusive veto power"], D,
      "The veto held only by the five permanent members (USA, UK, France, Russia, China) lets any one of them block action, which is the Council's most criticised feature."),
    q("Which of the following is a founding member of OPEC?",
      ["Nigeria", "Indonesia", "Venezuela", "Algeria"], C,
      "OPEC was founded in Baghdad in September 1960 by Iran, Iraq, Kuwait, Saudi Arabia and Venezuela; Nigeria joined in 1971."),
    q("Professor Ibrahim Gambari is the Special Assistant to the United Nations Secretary-General on",
      ["African affairs", "political and social matters", "the Economic Commission of Africa", "security matters"], A,
      "When the paper was set, Gambari was the UN Under-Secretary-General and Special Adviser on Africa; he later held other UN posts and was Nigeria's Chief of Staff to the President (2020–2023)."),
    q("Who among the following served as Secretary-General of OPEC?",
      ["Jibril Aminu", "Aret Adams", "Dan Etete", "Rilwanu Lukman"], D,
      "Rilwanu Lukman was OPEC Secretary-General from 1995 to 2000 (Mohammed Barkindo, another Nigerian, held the post later, 2016–2022)."),
    q("Nigeria's active role in the liberation of some countries in Southern Africa earned her",
      ["Chairmanship of the Eminent Persons", "Membership of SADC", "Giant of Africa", "the status of the frontline state"], D,
      "Although far from Southern Africa, Nigeria gave so much support to liberation movements and against apartheid that it was treated as an honorary frontline state."),
    q("Which of these international finance agencies is Nigeria a member of?",
      ["London Club", "The Infrastructural Development Fund", "The Paris Club", "The International Monetary Fund"], D,
      "Nigeria has been a member of the IMF since 1961; the London and Paris Clubs are groups of creditors to whom Nigeria owed debts, not bodies it belongs to."),
    q("Nigeria's membership of the ECOWAS is informed by her desire to",
      ["develop a market in the sub-region", "form sub-regional high command", "become a sub-regional power", "promote economic integration"], D,
      "ECOWAS (Treaty of Lagos, 1975) was founded, with Nigeria leading, to promote economic integration and cooperation among West African states."),
    q("An attribute that Nigeria shares with most nonaligned countries is",
      ["her large population", "the state of her economy", "her heterogeneous population", "her large size"], B,
      "Most members of the Non-Aligned Movement, like Nigeria, are developing countries with economies dependent on primary products."),
  ]);
})();
