/**
 * JAMB/UTME 2001 — GOVERNMENT
 * From the 2001 question paper (49 of 50 questions; paper Q45 left out, see REPORT.md); answers from
 * the JAMB/UTME Government answer key 2001–2020, each checked independently. Printing errors carry
 * keyVerdict/answerNote.
 */
(function () {
  const Y = 2001;
  const SRC = 'JAMB UTME 2001';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  QUESTION_BANK.government = QUESTION_BANK.government.concat([
    // paper 1–10
    q("Power differs from influence in that it is",
      ["persuasive while influence is directive", "coercive while influence is harmful", "coercive while influence is persuasive", "arrogant while influence is corruptible"], C,
      "Power is the ability to make others obey, backed by sanctions or force; influence only persuades, with no threat of punishment."),
    q("The standing committee of legislature is one",
      ["whose members stand while deliberating", "that has statutory responsibilities", "that performs ad hoc functions", "that has all legislators as members"], B,
      "A standing committee is a permanent committee set up under the rules of the house to handle a fixed area of business for the whole life of the legislature."),
    q("Where the constitution is supreme, unconstitutional acts of the executive and the legislature can be checked by the courts through",
      ["recall", "judicial review", "vote of no confidence", "impeachment"], B,
      "Judicial review is the power of the courts to declare laws or executive acts null and void when they conflict with the constitution."),
    q("The central decision-making organ of a confederation is made up of",
      ["technocrats appointed by the units", "politicians elected from the confederal constituencies", "politicians nominated by governments of member states", "representatives of pressure groups"], C,
      "In a confederation the sovereign member states keep control, so the central organ is made up of delegates nominated by, and answerable to, the member governments."),
    q("Which of the following is true of a parliamentary system of government?",
      ["Clear separation of government organs", "Strict operation of bicameral legislature", "Removal of government by impeachment", "Adherence to majority rule"], D,
      "In a parliamentary system the party (or coalition) with a majority in parliament forms the government and stays in office only while it keeps that majority."),
    q("A major feature of authoritarianism is that government is",
      ["consensual", "personalized", "centralized", "decentralized"], B,
      "Authoritarian rule revolves around one leader or a small clique whose personal will replaces laws and institutions, so government becomes personalized."),
    q("The central point of capitalism, as expounded by Karl Marx, is that",
      ["capitalists' profit is the surplus value obtained from workers' labour", "workers are inherently incapable of being owners of their labour", "capitalists shall always increase workers' earning capacity through wages", "capitalists shall always readily consent to workers' welfare demands"], A,
      "Marx argued that workers produce more value than they are paid in wages; the capitalist keeps this surplus value as profit, which is the basis of exploitation."),
    q("A constitution that requires a plebiscite or a referendum to be amended is",
      ["rigid", "unwritten", "flexible", "written"], A,
      "A rigid constitution can be amended only by a special procedure, such as a referendum or special majorities, not by an ordinary act of the legislature."),
    q("An important function of a constitution is that it",
      ["provides a framework for the study of government", "facilitates cross-fertilization of ideas of governance", "serves as the fountainhead of authority for the exercise of power", "promotes citizen participation in government and administration"], C,
      "A constitution is the source of all legal authority in the state: every organ of government draws its powers from it and must act within it."),
    q("When a bill passed by the legislature is vetoed by the executive, the action underscores the principle of",
      ["probity and accountability", "separation of power", "collective responsibility", "checks and balances"], D,
      "The executive veto is a check on the legislature (which can in turn override it), an example of each organ restraining the others."),
    // paper 11–20
    q("In the legislative process, a bill is a",
      ["motion accepted for debate", "motion rejected after debate", "proposal before the legislature", "law passed by the legislature"], C,
      "A bill is a draft law placed before the legislature for consideration; it becomes an act (a law) only after it is passed and assented to."),
    q("One of the advantages of bicameral over unicameral legislature is that it",
      ["is cheap to maintain", "promotes social equality", "takes less time for bills to be passed", "prevents the passage of ill-considered bills"], D,
      "With two chambers, each bill is examined twice, so the second house can catch and stop hasty or poorly considered legislation."),
    q("The fundamental rights of citizens include rights to",
      ["free education, employment and freedom of thought", "life, speech and association", "life, liberty and property", "association, property and social security"], C,
      "Life, liberty and property are the classic fundamental rights; free education, employment and social security are only state policy goals, not enforceable rights.",
      { keyVerdict: 'multiple', alsoAccept: [B], keyAnswer: 'C',
        answerNote: "Option B is also correct: the rights to life, freedom of expression (speech) and freedom of association are all fundamental rights in the Nigerian constitution. Both B and C list only fundamental rights, so either is accepted." }),
    q("The manipulation of boundaries of constituencies in order to win more seats is called",
      ["devolution", "rigging", "gerrymandering", "delimitation"], C,
      "Gerrymandering is drawing constituency boundaries unfairly to give one party an advantage; delimitation is the neutral, lawful drawing of boundaries."),
    q("One argument against a multi-party system is the",
      ["encouragement of opposition and instability", "banning of interest groups", "inability to attract foreign assistance", "high cost of conducting elections"], D,
      "Many parties mean many candidates, campaigns, ballots and run-offs, which makes elections in a multi-party system very expensive to organise."),
    q("Associational interest groups are organized to",
      ["further the interests of members", "specifically lobby the government", "support the government", "achieve goals affecting other associations"], A,
      "Associational groups (such as trade unions and professional bodies) are formally organised to promote the specific interests of their members."),
    q("Public opinion is view that is",
      ["held by the majority", "active in the public realm", "widely publicized", "no longer a secret"], A,
      "Public opinion is the view held by the majority of people in a society on a public issue at a given time."),
    q("The political neutrality of civil servants implies that they",
      ["are not allowed to join any organization or group", "have no dealings with politicians", "are not allowed to be involved in partisan politics", "are not allowed to vote"], C,
      "Neutrality means civil servants serve any government in power and may not take part in partisan politics, though they may still vote."),
    q("The idea of making the civil service permanent, neutral and anonymous is to",
      ["enhance efficiency in administration", "ensure loyalty and support", "prevent opposition to government", "make civil servants a functional elite"], A,
      "Permanence keeps experience in the service, neutrality lets it serve any government, and anonymity shields officials from public attack, all to make administration efficient."),
    q("The western zone of the Sokoto caliphate was administered from",
      ["Kebbi", "Ilorin", "Bida", "Gwandu"], D,
      "Usman dan Fodio split the caliphate: the eastern part went to his son Muhammad Bello at Sokoto and the western part to his brother Abdullahi at Gwandu."),
    // paper 21–30
    q("Some pre-colonial Nigerian societies are described as stateless because",
      ["they had no formal governmental institutions", "they had no definite political boundaries", "their population was too small", "they were not independent"], A,
      "Stateless (acephalous) societies, like most pre-colonial Igbo communities, had no king or central government; authority was shared among elders, age grades and assemblies."),
    q("The method used by the British to facilitate the administration of Southern Nigeria was",
      ["persuasion", "dialogue", "divide and rule", "trade concession"], C,
      "The British ruled the South by playing groups and areas against one another and treating them separately, so that they did not unite against colonial rule."),
    q("A major function of the Warrant chiefs was to",
      ["prevent tribal wars", "supervise native courts and markets", "stop ritual killings", "take charge of local administration"], D,
      "Warrant chiefs were men given a warrant by the British to run local administration in Eastern Nigeria under indirect rule: collecting taxes, keeping order and sitting in native courts."),
    q("After 1945, the demand of African nationalists changed from reform to independence because",
      ["colonial rule became less oppressive", "colonial rule was in disarray", "the second world war boosted their morale", "the second world war enhanced colonial rule"], C,
      "African soldiers who fought in the Second World War saw that Europeans could be beaten, and the war's talk of freedom (the Atlantic Charter) gave nationalists new confidence."),
    q("When Nigeria achieved independence in 1960, the Head of State was the",
      ["President", "Prime Minister", "Governor-General", "Queen of England"], D,
      "Under the 1960 independence constitution the British Queen, Elizabeth II, remained Nigeria's Head of State, represented in Nigeria by the Governor-General."),
    q("The central legislature of Nigeria became bicameral in",
      ["1963", "1951", "1959", "1960"], D,
      "The Senate, provided for at the end of 1959, first sat in January 1960 (Azikiwe was its first President), so the federal Parliament of 1960 had two houses."),
    q("Which of these constitutions recognized local government as a third tier of government in Nigeria?",
      ["1946 constitution", "1960 constitution", "1963 constitution", "1979 constitution"], D,
      "The 1979 constitution (section 7) entrenched elected local government councils as the third tier, following the 1976 local government reform."),
    q("Under the 1963 constitution, items not listed in the exclusive and concurrent lists were within the exclusive competence of the",
      ["Executive", "Federal parliament", "Regional legislatures", "Judiciary"], C,
      "Matters on neither list were residual matters, and under the 1960 and 1963 constitutions only the regional legislatures could make laws on them."),
    q("Before Nigeria became a republic, the highest body charged with the administration of justice was the",
      ["Privy Council", "High Court", "Supreme Court", "Court of Appeal"], A,
      "Until Nigeria became a republic in 1963, final appeals went from the Federal Supreme Court to the Judicial Committee of the Privy Council in London."),
    q("The equivalent of a commissioner at the local government level is the",
      ["executive chairman", "secretary", "councillor", "supervisory councillor"], D,
      "A supervisory councillor heads a department of the local government for the chairman, just as a commissioner heads a ministry for the state governor."),
    // paper 31–40
    q("The Independent National Electoral Commission has the power to prepare and maintain the register of",
      ["political parties", "constituencies", "voters", "electoral candidates"], C,
      "INEC compiles, updates and keeps the register of voters; only people on it can vote in an election."),
    q("The President of Nigeria is advised on the sovereignty and territorial integrity of the country by the",
      ["National Security Council", "National Defence Council", "Council of State", "Federal Executive Council"], B,
      "The constitution gives the National Defence Council the duty of advising the President on the defence of Nigeria's sovereignty and territorial integrity."),
    q("The Nigerian Youth Movement collapsed as a result of",
      ["its failure to win election", "shortage of funds to run its affairs", "the harassments of its leadership by government", "the breakup of its leadership"], D,
      "The NYM split in 1941 over the choice of Ernest Ikoli instead of Samuel Akisanya for a Legislative Council seat; Azikiwe and his Igbo supporters walked out and the movement declined."),
    q("The first restructuring of the Nigeria Federation took place with the",
      ["creation of the Mid-West Region in 1963", "abolition of federalism in 1966", "military counter-coup of 1966", "creation of states in 1967"], A,
      "The Mid-West Region, carved out of the Western Region in 1963, was the first change to the units of the federation, turning three regions into four.",
      { keyVerdict: 'corrected', keyAnswer: 'D',
        answerNote: "The creation of 12 states in 1967 was the biggest restructuring, but it was not the first: the Mid-West Region was created four years earlier, in 1963, changing the federation from three regions to four. So A is the better answer." }),
    q("The land use decree of 1978 vested the ownership of land in Nigeria in the",
      ["local chiefs", "local governments", "state governments", "federal government"], C,
      "The Land Use Decree vested all land in each state in the state Governor, to hold in trust for the people. It remains in force today as the Land Use Act."),
    q("The main source of financing local government in Nigeria is",
      ["internal revenue generation", "statutory revenue allocation", "special state grants", "grants-in-aid"], B,
      "Most local government money comes from its constitutional share of the Federation Account (statutory allocation), not from local rates and fees."),
    q("The most remarkable legacy of the 1976 Local Government Reform in Nigeria was the introduction of",
      ["the office of sole administrators", "caretaker management committees", "uniformity in structure and functions", "the third tier of government"], C,
      "The 1976 reform replaced the many different local systems in the country with one uniform, single-tier, multi-purpose local government system.",
      { keyVerdict: 'multiple', alsoAccept: [D], keyAnswer: 'C',
        answerNote: "Option D is also accepted: the 1976 reform guidelines also first described local government as the third tier of government, an idea the 1979 constitution then entrenched. Both C and D are legacies of the reform." }),
    q("The Murtala/Obasanjo regime in Nigeria increased the number of states from",
      ["4 to 12", "12 to 19", "19 to 21", "30 to 36"], B,
      "In February 1976 the Murtala Muhammed government created seven new states, raising the number from 12 to 19. Nigeria has had 36 states since 1996."),
    q("A major factor that influenced the formulation of Nigeria's foreign policy in the First Republic was",
      ["geographical location", "the colonial legacy", "economic consideration", "the parliamentary system"], B,
      "Ties inherited from British rule (the Anglo-Nigerian Defence Pact, Commonwealth links, trade with Britain) made Balewa's foreign policy cautious and pro-West."),
    q("Nigeria's departure from pro-west policy during the Murtala Muhammed regime was as a result of",
      ["the economic interests of the west in Nigeria", "Nigeria's increased international influence", "the growing trade between Nigeria and the East", "Nigeria's concern for decolonization in Africa"], D,
      "Murtala's government broke with the West, most famously over Angola in 1975, because it put the liberation of Africa from colonial and white-minority rule first."),
    // paper 41–50 (45 left out)
    q("During the Civil War, the major power that expressed moral support for Biafra's self-determination was",
      ["France", "China", "the United States", "Great Britain"], A,
      "France under de Gaulle openly expressed sympathy for Biafra's right to self-determination and sent it help, mostly through Gabon and Côte d'Ivoire."),
    q("The Barclays Bank and the British Petroleum Company in Nigeria were nationalized in the late 1970s for transacting business with",
      ["France", "South Africa", "Portugal", "Libya"], B,
      "Nigeria took over Barclays' shares (1978) and BP's assets (1979) because both firms were doing business with apartheid South Africa."),
    q("South-South cooperation is a major policy plan on which Nigeria bases her relations with",
      ["developed countries", "countries of the southern hemisphere", "developing countries", "member countries of OAU"], C,
      "'South' is a name for the developing countries of Africa, Asia and Latin America, so South-South cooperation means cooperation among developing countries."),
    q("Nigeria's recognition of the Popular Movement for the Liberation of Angola to lead the country was made under",
      ["General Yakubu Gowon", "General Murtala Muhammed", "General Muhammadu Buhari", "General Ibrahim Babangida"], B,
      "In November 1975 the Murtala Muhammed government recognised the MPLA as Angola's government, against strong American pressure."),
    q("The first Nigerian Permanent Representative to the United Nations was", ["Alhaji Yusuf Maitama Sule", "General Joseph Garba", "Professor Ibrahim Gambari", "Jaja Wachuku"], D,
      "Jaja Wachuku was Nigeria's first Permanent Representative to the UN (1960–1961), right after independence; he later became Minister of Foreign Affairs.",
      { keyVerdict: 'misprint', answerNote: "On the original paper none of the four options was right: Yusuf Maitama Sule, Joseph Garba and Ibrahim Gambari all held the post from 1979 onward, and option D printed \"Chief Samuel Adebo\" (Simeon Adebo served 1962–1967, after Wachuku). We rebuilt option D with the correct answer, Jaja Wachuku." }),
    q("In 1981, Nigeria participated in an Organization of African Unity peace-keeping force to replace Libyan force in",
      ["Somalia", "Chad", "Ethiopia", "Zaire"], B,
      "After Libyan troops left Chad in late 1981, the OAU sent an Inter-African Force to Chad, with Nigeria providing the largest contingent."),
    q("Nigeria's withdrawal from the Edinburgh Commonwealth Games in July 1986 was in protest against British",
      ["support to UNITA rebels in Angola", "supply of arms to Rhodesia", "failure to impose sanctions on South Africa", "negative utterances on Nigeria"], C,
      "Nigeria led a boycott of the 1986 Commonwealth Games because Margaret Thatcher's government refused to impose economic sanctions on apartheid South Africa."),
    q("The major demand of the Third World countries on the United Nations in recent times is the",
      ["expansion of the permanent membership of the Security Council", "post of the Secretary-General of the organization", "withdrawal of the veto power from the Security Council", "enforcement of resolutions on the superpowers"], A,
      "Developing countries want more permanent seats on the Security Council so that Africa, Latin America and more of Asia are represented. Today the permanent five are still unchanged."),
    q("Which of the following is the function of the Council of Ministers of the O.A.U.?",
      ["Co-ordinating the general policy of the organization", "Directing the finances of the organization", "Preparing the agenda of the organization's meetings", "Reviewing the functions and activities of other organs of the organization"], C,
      "The OAU Council of Foreign Ministers prepared the conferences (and agenda) of the Assembly of Heads of State. The OAU became the African Union in 2002, where the Executive Council does this work."),
    q("The Economic Community of West African States has made impressive progress in the area of",
      ["free movement of persons and right of residence", "increased trade among members", "political integration of the region", "providing financial aid to its members"], A,
      "ECOWAS's 1979 Protocol on Free Movement of Persons, Right of Residence and Establishment lets citizens of member states travel within the region without a visa: its best-known success.",
      { keyVerdict: 'corrected', keyAnswer: 'B',
        answerNote: "Trade among ECOWAS members has stayed low (only about a tenth of their total trade), while the 1979 Protocol on free movement and residence, which removed visas for ECOWAS citizens, is the community's clearest achievement. So A is the better answer." })
  ]);
})();
