/**
 * JAMB/UTME 2020 — GOVERNMENT
 * From the 2020 question paper (questions 1–40); answers from the JAMB/UTME Government answer key
 * 2001–2020, each checked independently. Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2020;
  const SRC = 'JAMB UTME 2020';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  QUESTION_BANK.government = QUESTION_BANK.government.concat([
    // paper 1–10
    q("In a feudal system, the two major classes are the serfs and the",
      ["masses", "vassals", "lords", "elite"], C,
      "Feudalism divided society into the land-owning lords and the serfs, who were tied to the lord's land and worked it in return for protection."),
    q("In the pre-colonial Yoruba political system, the council of chiefs constituted the",
      ["ombudsman", "executive", "judicial arm", "legislative arm"], D,
      "In Oyo the Oyo Mesi, the council of seven chiefs led by the Bashorun, made laws with the Alaafin and could even ask him to commit suicide, so it acted as the legislature."),
    q("One basic feature of a monarchical form of government is that",
      ["the ruler has fixed tenure and power is absolute", "separation of powers is absolute", "members of the executive are elected", "succession is through heredity"], D,
      "In a monarchy the throne passes by heredity within a royal family, usually to the eldest son or nearest heir, and the monarch normally reigns for life."),
    q("The tenet of non-alignment connotes",
      ["military alliance", "political neutrality", "political instability", "political non-participation"], B,
      "Non-alignment means refusing to take sides with either power bloc (the US-led West or the Soviet-led East in the Cold War) while still taking an active part in world affairs."),
    q("The right of a state is known as",
      ["authority", "power", "sovereignty", "legitimacy"], C,
      "Sovereignty is the supreme legal right of a state to make and enforce laws within its territory and to run its affairs free from outside control."),
    q("Government by the best men is referred to as",
      ["democratic", "autocratic", "aristocratic", "totalitarianism"], C,
      "Aristocracy (from the Greek aristos, 'best') is government by a few of the best or noblest men in society."),
    q("Laws made by military governments at the state level are called ____ while laws made by local governments are called ____.",
      ["acts; decrees", "decrees; edicts", "bye-laws; decrees", "edicts; bye-laws"], D,
      "Under military rule the federal government made decrees and the state military governors made edicts; local government councils make bye-laws."),
    q("Which of the following emphasizes the rule of law and human rights protection?",
      ["Constitutionalism", "Delegated legislation", "Decentralisation", "Centralisation"], A,
      "Constitutionalism means government limited by a constitution: rulers act only within the law, and citizens' rights are protected."),
    q("The totality of Nigeria's participation in the international system is known as",
      ["international policy", "foreign policy", "economic policy", "social policy"], B,
      "Foreign policy is the whole set of principles, goals and actions that guide a country's dealings with other states and international organisations."),
    q("Under whose regime were Akwa Ibom and Katsina States created in 1987?",
      ["Gen. Murtala Muhammed", "Gen. Ibrahim Babangida", "Gen. Sani Abacha", "Gen. Yakubu Gowon"], B,
      "General Ibrahim Babangida created Akwa Ibom (from Cross River) and Katsina (from Kaduna) on 23 September 1987, raising the number of states from 19 to 21."),
    // paper 11–20
    q("Public opinion is NOT formed through",
      ["mass media", "symposia and lectures", "documentary", "advertisement"], D,
      "Public opinion on public issues is shaped by the mass media, lectures, symposia and documentaries; advertisement mainly aims to sell goods and services, not to form opinion on public affairs."),
    q("A major feature of monarchy is that it is",
      ["headed by a king", "hereditary", "headed by a queen", "headed by the richest citizen"], B,
      "In a monarchy the throne passes by heredity within a royal family; the monarch may be a king or a queen."),
    q("The emergence of nationalism was essentially the result of the ills of",
      ["imperialism", "independence", "slavery", "colonialism"], D,
      "Nationalism grew out of the grievances of colonial rule: racial discrimination, exclusion of Africans from government and senior posts, economic exploitation and the humiliation of foreign domination."),
    q("A country is said to operate an unwritten constitution if the",
      ["constitution is not contained in a single document", "constitution cannot be written down", "existing constitution can be suspended at will", "country does not have a printed constitution"], A,
      "An unwritten constitution, like Britain's, is not gathered in one document; its rules are scattered in statutes, court decisions, conventions and the writings of authorities."),
    q("In fascism, the leader is",
      ["supreme", "democratic", "rich", "religious"], A,
      "Fascism (Mussolini's Italy, Hitler's Germany) glorifies the state and a single leader whose authority is supreme and cannot be questioned."),
    q("To facilitate the effective achievement of its objectives, ECOWAS is operationally structured in",
      ["councils", "panels", "committees", "commissions"], D,
      "The 1975 ECOWAS Treaty set up specialised commissions (Trade, Customs, Immigration, Monetary and Payments; Industry, Agriculture and Natural Resources; Transport, Communications and Energy; Social and Cultural Affairs) to carry out its work; since 2007 its secretariat has also been called the ECOWAS Commission."),
    q("Which of these is the first political party in Nigeria?",
      ["NYM", "NNDP", "NCNC", "NPC"], B,
      "Herbert Macaulay founded the Nigerian National Democratic Party (NNDP) on 24 June 1923 to contest the Lagos elective seats created by the Clifford Constitution."),
    q("In the pre-colonial system, checks and balances were prominent in the",
      ["Igbo system", "Tiv system", "Yoruba system", "Hausa-Fulani system"], C,
      "In the Old Oyo (Yoruba) system the Alaafin's power was checked by the Oyo Mesi, the Oyo Mesi was checked by the Ogboni, and the Are-Ona-Kakanfo led the army, so power was balanced among several institutions."),
    q("The main function of the legislature is",
      ["law review", "law making", "law implementation", "law interpretation"], B,
      "The legislature (in Nigeria, the National Assembly) exists chiefly to make laws; the executive implements them and the judiciary interprets them."),
    q("The number of permanent members of the UN Security Council is",
      ["seven", "eight", "five", "six"], C,
      "The Security Council has five permanent members with veto power: the United States, Russia, China, the United Kingdom and France."),
    // paper 21–30
    q("Activities of pressure groups that influence governmental decisions are hampered by",
      ["its size", "its leadership", "its affiliation", "the economy"], B,
      "A pressure group is only as effective as its leaders: weak, divided, corrupt or co-opted leadership is the commonest reason a group fails to influence government."),
    q("A nation could be identified through its",
      ["military strength", "common language and culture", "population", "constitution"], B,
      "A nation is a group of people bound by a common language, culture, history or descent and a feeling of oneness."),
    q("In the Hausa/Fulani political systems, the administrative functions were carried out by the",
      ["Madawaki", "Hakimi", "Dogari", "Waziri"], D,
      "The Waziri was the Emir's chief adviser and head of administration, much like a prime minister, who coordinated the work of the other officials."),
    q("What differentiates a public corporation from a private enterprise?",
      ["Financing", "Proclamation", "Ownership", "Membership"], C,
      "A public corporation is owned by the government on behalf of the public, while a private enterprise is owned by private individuals or shareholders."),
    q("The development of attitudes and beliefs about a political system is known as",
      ["political orientation", "political apathy", "political culture", "political socialization"], D,
      "Political socialisation is the process through which people develop and acquire political attitudes, beliefs and values, through the family, school, peers, religion, the media and parties."),
    q("One of the major problems of ECOWAS is",
      ["lack of military force", "the presence of CEAO as a competitor", "overlapping functions of her agencies", "political instability in the region"], D,
      "Coups, civil wars and unstable governments in member states (Liberia, Sierra Leone, Guinea-Bissau, Mali and others) have repeatedly disrupted ECOWAS's programmes for economic integration."),
    q("The form of government headed by a king is",
      ["monarchy", "presidentialism", "fascism", "republicanism"], A,
      "A monarchy is headed by a hereditary ruler, a king or queen, who usually reigns for life."),
    q("Checks and balances guarantee",
      ["superiority of the legislature", "balance of the three arms", "superiority of the executive", "subordination of the judiciary"], B,
      "Under checks and balances each arm of government (legislature, executive and judiciary) can limit the others, so no arm becomes dominant and the three stay in balance."),
    q("The primary reason for the establishment of political parties is to",
      ["attain political power", "protect political interest", "make laws", "lobby the government"], A,
      "A political party is an organised group that seeks to win elections and so capture and control the government; this aim to attain power is what sets it apart from a pressure group."),
    q("An attribute that makes a state to be recognized as independent is",
      ["government", "population", "sovereignty", "territory"], C,
      "Sovereignty, supreme authority at home and freedom from outside control, is what marks a state as independent."),
    // paper 31–40
    q("Universal suffrage or franchise can be described as the right to",
      ["vote at elections", "form political parties", "vote and be voted for", "contest in elections"], C,
      "Franchise is the right to take part in elections; Nigerian textbooks usually define it as the right of qualified citizens to vote and be voted for, while in the narrow sense it is simply the right to vote.",
      { keyVerdict: 'multiple', alsoAccept: [A], keyAnswer: 'C',
        answerNote: "A is also accepted. In its strict sense franchise (suffrage) means the right to vote at elections (A); many Nigerian textbooks widen it to the right to vote and be voted for (C). Both describe franchise correctly." }),
    q("Government by the best citizens is referred to as",
      ["aristocracy", "democracy", "oligarchy", "plutocracy"], A,
      "Aristocracy comes from the Greek aristos ('best'): rule by a few of the best or noblest citizens."),
    q("A type of constitution that is difficult to amend is described as",
      ["written and flexible", "rigid and written", "unwritten and rigid", "flexible and rigid"], B,
      "A rigid constitution needs a special procedure (such as two-thirds majorities and approval by the states) to amend it, and rigid constitutions are almost always written, like Nigeria's and the USA's."),
    q("The Northern and Southern protectorates were made provinces under the",
      ["Macpherson Constitution", "Richards Constitution", "Clifford Constitution", "Lyttelton Constitution"], C,
      "After the 1914 amalgamation the two protectorates were run as the Northern Provinces and the Southern Provinces, and the 1922 Clifford Constitution was built on that arrangement: its Legislative Council made laws for Lagos and the Southern Provinces, while the governor legislated for the Northern Provinces."),
    q("The highest and most powerful organ of OPEC is the",
      ["Conference", "Secretariat", "Council of Ministers", "Board of Governors"], A,
      "The OPEC Conference, made up of the oil ministers of member countries, is the supreme authority that decides OPEC's policies."),
    q("Disputes among member states of ECOWAS are settled by",
      ["the technical and specialized commission", "the board of trustees", "the Community Tribunal", "the Council of Ministers"], C,
      "The 1975 ECOWAS Treaty set up a Community Tribunal to settle disputes between member states; under the revised treaty of 1993 it is now the ECOWAS Community Court of Justice in Abuja."),
    q("Which of the following countries is a founding member of the Commonwealth?",
      ["India", "Ghana", "South Africa", "Zimbabwe"], C,
      "South Africa was one of the self-governing dominions that formed the British Commonwealth under the Statute of Westminster (1931), and it was again among the eight members that founded the modern Commonwealth in 1949; Ghana joined only in 1957 and Zimbabwe in 1980.",
      { keyVerdict: 'multiple', alsoAccept: [A], keyAnswer: 'C',
        answerNote: "A is also accepted. The modern Commonwealth was founded by the London Declaration of 1949, and its eight founding members were Britain, Canada, Australia, New Zealand, South Africa, India, Pakistan and Ceylon (Sri Lanka). South Africa was also a member of the older British Commonwealth from 1931, so C fits either date, but India is a founding member of today's Commonwealth too." }),
    q("A flexible constitution is one which is",
      ["written by the parliament", "easily amended", "popular with the legislators", "known to all the citizens"], B,
      "A flexible constitution can be amended by the ordinary law-making procedure, with a simple majority in the legislature, as in Britain."),
    q("Which of the following nationalists was the founder of Nigeria's first political party, NNDP, in 1923?",
      ["Herbert Macaulay", "Abubakar Tafawa Balewa", "Ahmadu Bello", "Nnamdi Azikiwe"], A,
      "Herbert Macaulay founded the Nigerian National Democratic Party (NNDP) in 1923 to contest the Lagos seats created by the Clifford Constitution; it was Nigeria's first political party."),
    q("The military regime abolished the state ministries of local government in Nigeria in",
      ["1985", "1957", "1990", "1989"], D,
      "The Babangida regime abolished the state ministries of local government (1989) so that councils dealt more directly with the federal government and got their allocations directly. Today most states again have ministries of local government affairs."),
  ]);
})();
