/**
 * JAMB/UTME 2018 — GOVERNMENT
 * From the 2018 question paper (questions 1–40); answers from the JAMB/UTME Government answer key
 * 2001–2020, each checked independently. Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2018;
  const SRC = 'JAMB UTME 2018';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  QUESTION_BANK.government = QUESTION_BANK.government.concat([
    // paper 1–10
    q("Which of the following is the foremost right of a citizen?",
      ["Religious right", "Academic right", "Right to life", "Private life"], C,
      "The right to life is the most basic of all rights, because no other right can be enjoyed by a person who is not alive; it is the first fundamental right in Chapter IV of the 1999 Constitution (section 33)."),
    q("Which of the following is a merit of aristocracy?",
      ["Leaders must have military experience", "The best citizens are in control of government", "The organised few control the government", "The majority control the government"], B,
      "Aristocracy means rule by the best (from the Greek aristos), so its claimed merit is that government is in the hands of the ablest, most cultured and experienced citizens."),
    q("Which of the following is a strategy of foreign policy implementation?",
      ["Cultural integration", "Democratic elections", "Political representation", "Propaganda"], D,
      "States carry out their foreign policy through diplomacy, propaganda, economic aid and sanctions, alliances and, as a last resort, war; propaganda spreads ideas abroad to win support for a country's position."),
    q("The Structural Adjustment Programme was introduced under the",
      ["Babangida Regime", "Obasanjo Regime", "Buhari Regime", "Abacha Regime"], A,
      "General Ibrahim Babangida's military government introduced the Structural Adjustment Programme (SAP) in July 1986 to restructure the economy through devaluation, deregulation, privatisation and the removal of subsidies."),
    q("To facilitate the effective achievement of its objectives, ECOWAS is operationally structured in",
      ["councils", "panels", "committees", "commissions"], D,
      "The 1975 ECOWAS Treaty set up specialised commissions (Trade, Customs, Immigration, Monetary and Payments; Industry, Agriculture and Natural Resources; Transport, Communications and Energy; Social and Cultural Affairs) to carry out its work; since 2007 its secretariat has also been called the ECOWAS Commission."),
    q("Shortage of trained personnel is a major problem of the",
      ["Federal Government", "State Government", "Regional Government", "Local Government"], D,
      "Local governments in Nigeria cannot pay attractive salaries or offer good career prospects, so they find it hard to attract and keep qualified and skilled staff."),
    q("The right of a state is known as",
      ["authority", "power", "sovereignty", "legitimacy"], C,
      "Sovereignty is the supreme legal right of a state to make and enforce laws within its territory and to run its affairs free from outside control."),
    q("The popularity of a political party in a given democracy rests on its",
      ["constitution", "manifesto", "ideology", "number of branches"], B,
      "A party's manifesto sets out the programmes and promises it offers the electorate; voters judge and support parties mainly by how attractive and believable their manifestos are."),
    q("A system of local council that allows for rotational leadership is known as",
      ["single executive", "dual executive", "multi executive", "collegiate executive"], D,
      "In a collegiate (plural) executive a council of equals governs together and its chairmanship rotates among the members, as in the Swiss Federal Council."),
    q("A type of constitution that is difficult to amend is described as",
      ["written and flexible", "rigid and written", "unwritten and rigid", "flexible and rigid"], B,
      "A rigid constitution needs a special procedure (such as two-thirds majorities and approval by the states) to amend it, and rigid constitutions are almost always written, like Nigeria's and the USA's."),
    // paper 11–20
    q("The political achievement of the UN is the promotion of",
      ["economic development", "educational development", "international peace and security", "democratic institutions"], C,
      "The UN's main political purpose, set out in Article 1 of its Charter, is to maintain international peace and security; through the Security Council, peacekeeping and mediation it has helped prevent another world war."),
    q("The elective principle in Nigeria was first introduced by the",
      ["Richards Constitution", "Macpherson Constitution", "Lyttelton Constitution", "Clifford Constitution"], D,
      "The 1922 Clifford Constitution first allowed Nigerians to elect members to the Legislative Council: three for Lagos and one for Calabar."),
    q("The three major political parties of the First Republic can be said to have had",
      ["national outlook", "regional and ethnic undertones", "government funding", "religious and sectional appeals"], B,
      "The NPC (North, Hausa-Fulani), the Action Group (West, Yoruba) and the NCNC (East, Igbo) each drew its main support from one region and its dominant ethnic group."),
    q("Development of the Civil Service relies on all of the following except",
      ["impartiality", "anonymity", "promotability", "neutrality"], C,
      "Impartiality, anonymity and political neutrality are recognised principles of the civil service; \"promotability\" is not one of them."),
    q("The chief executive system is associated with",
      ["federalism", "presidentialism", "parliamentarism", "unitarianism"], B,
      "In the presidential system one person, the executive president, is both head of state and head of government, so all executive power rests in a single chief executive."),
    q("Public corporations are mainly funded through",
      ["foreign aid", "shareholders' funds", "internally generated funds", "government subventions"], D,
      "Public corporations are owned by government, which provides their initial capital and regular grants (subventions), although they also earn some revenue from their services."),
    q("Which of the following is the oldest public corporation in Nigeria?",
      ["Power Distribution Company of Nigeria", "Nigeria Mining Corporation", "Nigerian Railway Corporation", "Nigerian Postal Services"], C,
      "The Nigerian Railway Corporation was set up in 1955 to take over the railway built from 1898; the Nigerian Mining Corporation came in 1972, NIPOST in 1985 and the power distribution companies only in 2005–2013."),
    q("In 1987, Nigeria attained a federation of",
      ["19 states", "12 states", "21 states", "30 states"], C,
      "On 23 September 1987 Babangida created Akwa Ibom and Katsina States, raising the number of states from 19 to 21. Nigeria has had 36 states since 1996."),
    q("The ombudsman aims at",
      ["offering qualitative educational services", "rendering alternative dispute resolution services", "providing qualitative job opportunities", "entertaining complaints on abuse of public office"], D,
      "The ombudsman (in Nigeria the Public Complaints Commission, 1975) receives and investigates citizens' complaints against injustice and abuse of office by public officials."),
    q("The apex body under the military regime of Yakubu Gowon was the",
      ["Supreme Military Council", "Federal Executive Council", "Armed Forces Ruling Council", "National Council of State"], A,
      "Under Gowon (1966–75), as under Murtala and Obasanjo after him, the highest ruling body was the Supreme Military Council; Babangida renamed it the Armed Forces Ruling Council in 1985."),
    // paper 21–30
    q("One of the problems of the Commonwealth of Nations is lack of",
      ["finance", "administrative structures", "cultural heterogeneity", "capacity to enforce decisions"], D,
      "The Commonwealth is a voluntary association with no army and no binding powers, so it cannot force members to obey its decisions; at most it can suspend a member, as it did Nigeria in 1995."),
    q("A major objective of the Public Complaints Commission is",
      ["creating fair opportunities for all government employees", "training and promotion of public servants", "addressing grievances of individuals and groups", "creating an efficient work environment"], C,
      "The Public Complaints Commission, Nigeria's ombudsman set up in 1975, investigates and seeks redress for complaints by individuals and groups against government bodies and officials."),
    q("The right of a state is known as",
      ["authority", "power", "sovereignty", "legitimacy"], C,
      "Sovereignty is the supreme legal right of a state to make and enforce laws within its territory and to run its affairs free from outside control."),
    q("Which of the following is a major feature of democracy?",
      ["Capacity to influence people", "Existence of political office holders", "Decision making", "Consent of the people"], D,
      "Democracy is government by the consent of the governed: the people choose their rulers in free elections and can remove them."),
    q("The struggle for self-government from foreign rule is known as",
      ["imperialism", "nationalism", "patriotism", "neo-colonialism"], B,
      "Nationalism is the feeling of oneness among a people and the organised struggle to free their country from foreign (colonial) rule and govern themselves."),
    q("Territorial defence in the Yoruba pre-colonial system was the responsibility of the",
      ["Bashorun", "Oyomesi", "Aremo", "Are-Ona-Kakanfo"], D,
      "In the Old Oyo Empire the Are-Ona-Kakanfo was the generalissimo (field commander) of the army, responsible for defending the empire and leading its wars."),
    q("An effective means of measuring public opinion is",
      ["referendum", "radio interview", "letters to government", "telephone calls"], A,
      "In a referendum the whole electorate votes directly on an issue, so it measures public opinion far more reliably than a few interviews, letters or calls."),
    q("Universal Adult Suffrage permits all",
      ["citizens to vote", "qualified males to vote", "qualified citizens to vote", "females to vote"], C,
      "Universal adult suffrage gives the vote to every citizen who meets the basic conditions (in Nigeria, aged 18 and above, registered and of sound mind), regardless of sex, wealth or education."),
    q("In the pre-colonial emirate system, the Emir of Gwandu controlled the",
      ["Central section", "Southern section", "Eastern section", "Western section"], D,
      "After the jihad, Usman dan Fodio divided the Sokoto Caliphate: his son Muhammad Bello at Sokoto ruled the eastern emirates and his brother Abdullahi at Gwandu the western emirates."),
    q("Both federal and state governments derive power from the",
      ["residual list", "concurrent list", "Exclusive list", "regional list"], B,
      "The concurrent list contains matters on which both the federal and state governments can make laws; federal law prevails where the two conflict."),
    // paper 31–40
    q("A social group consisting of two or more people who interact and identify with one another is a",
      ["nation", "society", "government", "state"], B,
      "A society is any group of people who live together, interact and share a sense of belonging to one another; it is the broadest of these groupings."),
    q("Which of the following Nigerian presidents initiated and facilitated the creation of NEPAD?",
      ["Goodluck Jonathan", "Olusegun Obasanjo", "Umaru Musa Yar'Adua", "Muhammadu Buhari"], B,
      "President Olusegun Obasanjo, with Presidents Mbeki of South Africa, Bouteflika of Algeria and Wade of Senegal, launched the New Partnership for Africa's Development in 2001. Since 2018 NEPAD has been the AU Development Agency (AUDA-NEPAD)."),
    q("Nigeria became a Republic with the",
      ["1979 Constitution", "1989 Constitution", "1960 Constitution", "1963 Constitution"], D,
      "The Republican Constitution of 1 October 1963 removed the British Queen as head of state; Dr Nnamdi Azikiwe became the first President and the Supreme Court replaced the Privy Council as the final court of appeal."),
    q("Which of the following is a function of the Civil Service Commission?",
      ["Enforcement of law and order", "Payment of civil servants' salaries", "Discipline of erring civil servants", "Protection of lives and properties"], C,
      "The Civil Service Commission appoints, promotes, transfers and disciplines civil servants, which keeps these matters free from political interference."),
    q("The concentration of power in the units is a merit of the",
      ["quasi-federal system", "confederal system", "federal system", "unitary system"], B,
      "In a confederation the member states keep most of the power and the central body has only what they choose to give it, so each unit keeps its sovereignty and identity."),
    q("In fascism, the leader is",
      ["supreme", "democratic", "rich", "religious"], A,
      "Fascism (Mussolini's Italy, Hitler's Germany) glorifies the state and a single leader whose authority is supreme and cannot be questioned."),
    q("Delegated legislation is the",
      ["limitation of responsibilities to agencies", "transfer of responsibilities to agencies", "deterring of responsibilities to agencies", "facilitation of responsibilities of agencies"], B,
      "Delegated legislation is law made by bodies other than the legislature (ministers, local councils, public corporations) under powers transferred to them by an Act of the legislature."),
    q("Which of the following countries significantly contributed to the formation of ECOMOG?",
      ["Ghana", "Gambia", "Liberia", "Nigeria"], D,
      "When ECOWAS formed ECOMOG in 1990 to intervene in the Liberian civil war, Nigeria led the initiative and provided most of its troops, funds and commanders."),
    q("An important element of the doctrine of separation of powers is",
      ["delegation of power", "checks and balances", "rule of law", "concentration of powers"], B,
      "Separation of powers divides government among the legislature, executive and judiciary; checks and balances let each organ limit the others so that none abuses its power."),
    q("Nigeria's actions towards the external environment are embedded in her",
      ["state policy", "party policy", "government policy", "foreign policy"], D,
      "Foreign policy is the set of principles and actions that guide a country's relations with other states and international organisations, that is, with its external environment."),
  ]);
})();
