/**
 * JAMB/UTME 2013 — GOVERNMENT
 * From the 2013 question paper (questions 2–50; Q1 only asked for the paper type); answers from the
 * JAMB/UTME Government answer key 2001–2020, each checked independently. Answer checks carry
 * keyVerdict/answerNote.
 */
(function () {
  const Y = 2013;
  const SRC = 'JAMB UTME 2013';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  QUESTION_BANK.government = QUESTION_BANK.government.concat([
    // paper 2–11
    q("Power that is delegated is exercised",
      ["by devolution", "directly", "by coercion", "indirectly"], D,
      "Delegated power belongs to one authority but is exercised on its behalf by another (an agent, a minister, a council), so the original holder exercises it indirectly, through someone else.",
      { keyVerdict: 'corrected', keyAnswer: 'A',
        answerNote: "The answer key gives A (by devolution), but devolution is a way of transferring power to lower units, not a way of exercising it. Power that is delegated is used by someone acting for the real holder, so it is exercised indirectly (D)." }),
    q("De jure sovereign is acquired through",
      ["law", "grant", "treaty", "force"], A,
      "De jure ('by law') sovereignty is the legal right to rule, held by the authority the law and constitution recognise; de facto sovereignty is power held in fact, often by force."),
    q("A group of people who live together under a common law within a definite territory is a",
      ["community", "nation-state", "nation", "state"], D,
      "A state is a people living in a definite territory under a government that makes and enforces common laws, with sovereignty; its four elements are population, territory, government and sovereignty."),
    q("Political socialization is associated with",
      ["military take-over of civilian government", "the transmission of political values", "political transition", "free choice of party programmes"], B,
      "Political socialisation is the process by which political values, attitudes and beliefs are passed on from one generation to the next, through family, school, peers, religion, the media and parties."),
    q("According to Aristotle, a form of government in which the few rule for the benefit of all is",
      ["diarchy", "aristocracy", "autocracy", "polyarchy"], B,
      "Aristotle classed governments by who rules and for whose benefit: rule by the few for the good of all is aristocracy; its corrupt form, rule by the few for themselves, is oligarchy."),
    q("Rule by the old people is known as",
      ["monarchy", "gerontocracy", "feudalism", "theocracy"], B,
      "Gerontocracy (from the Greek geron, old man) is government by elders, as in the pre-colonial Igbo system where councils of elders (ndichie) ruled."),
    q("As an executive, the commissioner is charged with the responsibility of",
      ["implementing laws", "writing laws", "giving loans", "making laws"], A,
      "A state commissioner is a member of the state executive council, and the executive's main job is to implement (execute) the laws made by the legislature."),
    q("Rules adjudication is a primary function of the",
      ["judiciary", "executive", "government", "legislature"], A,
      "Rule adjudication, interpreting laws and applying them to settle disputes, is the work of the courts: the judiciary. Rule making belongs to the legislature and rule application to the executive."),
    q("The judiciary controls the executive in a federal state through",
      ["delegated legislation", "judicial overview", "judicial review", "motions"], C,
      "Judicial review is the power of the courts to declare executive actions and laws null and void when they go against the constitution; it is the judiciary's main check on the executive."),
    q("One major advantage of the unitary system is that it tends to make government",
      ["free of controversy", "distant from the people", "popular among the masses", "strong and stable"], D,
      "In a unitary state all power is held by one central government, so decisions are quick and uniform and there is no clash between levels of government; this makes government strong and stable."),
    // paper 12–21
    q("The presidential system differs from the parliamentary system of government in that",
      ["the principle of collective responsibility applies", "executive and legislative powers are fused", "powers of the three arms of government are merged", "the tenure of office of the president is limited"], D,
      "A president is elected for a fixed term and can serve only a limited number of terms; a prime minister has no fixed tenure and stays in office as long as he keeps the majority in parliament."),
    q("Which of the following advocates equitable distribution of wealth?",
      ["Capitalism", "Aristocracy", "Socialism", "Plutocracy"], C,
      "Socialism puts the main means of production under public ownership so that wealth is shared fairly among all citizens, instead of being concentrated in private hands."),
    q("A constitution that is difficult to amend is",
      ["rigid", "written", "unwritten", "flexible"], A,
      "A rigid constitution can be amended only by a special procedure (for example two-thirds majorities in the legislature plus approval by the states), so it is difficult to change."),
    q("Which of the following constitutions is more suitable for centralization of political power?",
      ["Unwritten constitution", "Rigid constitution", "Written constitution", "Flexible constitution"], D,
      "A flexible constitution can be changed by an ordinary act of the legislature, so the central government can easily gather power to itself; this is why unitary states usually have flexible constitutions, while federations need rigid ones."),
    q("The act of transferring autonomous powers to subordinate agencies is",
      ["concentration", "deconcentration", "delegation", "devolution"], D,
      "Devolution transfers powers from the central government to subordinate units (regions, local councils), which then exercise them with a measure of autonomy; in delegation the subordinate merely acts on behalf of the superior.",
      { keyVerdict: 'corrected', keyAnswer: 'C',
        answerNote: "The answer key gives C (delegation), but the word 'autonomous' points to devolution. In delegation, the person or body given power still acts for, and answers to, the one who delegated it; only in devolution do the lower units exercise the powers in their own right." }),
    q("Which of the following types of citizenship cannot be withdrawn?",
      ["Citizenship by conquest", "Citizenship by birth", "Honorary citizenship", "Citizenship by naturalization"], B,
      "Citizenship by birth comes from being born to citizen parents (or in the country), so it cannot be taken away; citizenship by naturalisation or registration can be withdrawn, for example for disloyalty or fraud."),
    q("The right of citizens to vote is",
      ["universal suffrage", "nationality suffrage", "electoral suffrage", "adult suffrage"], A,
      "Suffrage (franchise) is the right to vote; universal suffrage gives that right to all qualified citizens, without restrictions of sex, wealth, religion or education."),
    q("A political party is different from a pressure group in its",
      ["objective", "organization", "strategy", "source of finance"], A,
      "The key difference is the aim: a political party seeks to win elections and control government, while a pressure group only seeks to influence government policy in its members' interest."),
    q("One of the functions of pressure groups is to",
      ["nominate the president", "prepare the budget", "articulate the opinion of their members", "contest elections to serve the people"], C,
      "Pressure groups gather and express (articulate) the views and interests of their members and press them on government; they do not contest elections or take over government."),
    q("Public opinion refers to the",
      ["aggregate views of groups on particular government activities", "views held by the president of a country", "views of the chief justice of a country", "aggregate of attitudes held by members of the national assembly"], A,
      "Public opinion is the sum (aggregate) of the views held by the people or groups in society on public issues and government actions at a particular time, not the views of a few office holders."),
    // paper 22–31
    q("The class that oversees the implementation of government decisions and policies is the",
      ["executive", "clerical", "technical", "administrative"], A,
      "In the civil service the executive class carries out government decisions and policies and supervises the day-to-day work of putting them into effect, below the administrative class, which advises on and formulates policy."),
    q("The performance of ritual rites in the Yoruba empire is the responsibility of the",
      ["Aare-Ona-Kakanfo", "Oba", "Ogboni", "Oyo-Mesi"], C,
      "The Ogboni, a powerful cult of elders tied to the earth deity, handled religious and ritual matters in Oyo and acted as a check on both the Alaafin and the Oyo Mesi."),
    q("Under the emirate system, the commander of the army is the",
      ["Hakimi", "Sarkin Fada", "Madawaki", "Alkali"], C,
      "In the Hausa-Fulani emirate the Madawaki was the commander of the army; the Hakimi were district heads, the Sarkin Fada was in charge of the palace and the Alkali was the Islamic judge."),
    q("The indirect rule system of administration was more successful in Northern Nigeria because",
      ["of the existence of an organized structure in the area", "the Europeans ensured that the farmlands", "the natives showed little or no resistance", "the people were mainly interested in being governed indirectly"], A,
      "The emirates already had a centralised system of government, with emirs, officials, taxation (zakat) and courts (Alkali), so the British could simply rule through the emirs."),
    q("The earliest nationalist activities in Nigeria were spearheaded by",
      ["trade unions", "traditional rulers", "political parties", "educated elite"], B,
      "The earliest resistance to British rule came from traditional rulers defending their independence, such as Jaja of Opobo, Nana of Itsekiri and Ovonramwen of Benin, before the educated elite led organised nationalism in the 20th century."),
    q("The first notable nationalist movement in West Africa was the",
      ["West African Students' Union", "Nigerian Youth Movement", "Aborigines' Rights Protection Society", "National Congress of British West Africa"], D,
      "The National Congress of British West Africa, founded in Accra in 1920 by J. E. Casely Hayford and others, was the first notable nationalist movement covering the whole of British West Africa; its demands led to the elective principle in the 1922 Clifford Constitution."),
    q("In Nigeria's first republic, the prime minister was both the",
      ["head of state and commander-in-chief of the armed forces", "commander-in-chief of the armed forces and party leader", "head of state and party leader", "head of government and a lawmaker"], D,
      "Under the parliamentary system of the First Republic, Prime Minister Tafawa Balewa was head of government and also a member of the House of Representatives (a lawmaker); the head of state was the Governor-General, later the President (Nnamdi Azikiwe)."),
    q("Under the 1979 Constitution, statutory allocation of revenue to local government councils is the responsibility of the",
      ["House of Assembly", "National Economic Council", "Federal Legislature", "Council of State"], A,
      "Section 7(6) of the 1979 Constitution made the House of Assembly of each state responsible for statutory allocation of public revenue to the local government councils within the state; the National Assembly provided for their allocation from federal revenue.",
      { keyVerdict: 'multiple', alsoAccept: [C], keyAnswer: 'A',
        answerNote: "Option C is also correct. Section 7(6) of the 1979 Constitution gives the duty to both legislatures: the National Assembly (Federal Legislature) provides for statutory allocation of public revenue to local government councils in the federation, and each state House of Assembly provides for allocation to the councils within its state." }),
    q("Under Nigeria's Second Republic, the Senate was under the leadership of",
      ["J. S. Tarka", "Joseph Wayas", "Edwin Ume-Ezeoke", "John Wash Pam"], B,
      "Joseph Wayas (NPN) was President of the Senate from 1979 to 1983; John Wash Pam was his deputy, and Edwin Ume-Ezeoke was Speaker of the House of Representatives."),
    q("The Revenue Mobilization, Allocation and Fiscal Commission is statutorily empowered to determine the remuneration of",
      ["only elected representatives", "political office holders", "employees of public corporations", "all civil servants"], B,
      "The 1999 Constitution (Third Schedule) empowers RMAFC to determine the remuneration of political office holders, such as the President, governors, legislators, ministers and judges; civil servants' pay is set by other bodies."),
    // paper 32–41
    q("The primary function of the Code of Conduct Bureau is to",
      ["ensure minimum standard of morality", "retain custody of declarations", "receive declaration of assets", "ensure due process by public officers"], C,
      "The Code of Conduct Bureau's first duty under the Constitution is to receive the asset declarations of public officers, examine them and refer breaches of the Code of Conduct to the Code of Conduct Tribunal."),
    q("The party system practised in Nigeria's Third Republic was",
      ["two-party", "zero-party", "one-party", "multi-party"], A,
      "In 1989 the Babangida regime created two parties, the Social Democratic Party (SDP) and the National Republican Convention (NRC), as the only parties for the Third Republic."),
    q("Nigeria adopted the federal system of government because of",
      ["uneven development", "the availability of limited resources", "the adoption of a state religion", "the fear of domination of minorities"], D,
      "Federalism was chosen for Nigeria's many ethnic groups so that each area could manage its own affairs; it guards minorities against fear of domination by the larger groups."),
    q("The highest policy-making body under the Gowon regime was the",
      ["Armed Forces Ruling Council", "Provisional Ruling Council", "Supreme Military Council", "Federal Executive Council"], C,
      "Under Gowon (1966–1975), as under Murtala and Obasanjo, the highest ruling body was the Supreme Military Council (SMC); Babangida later renamed it the Armed Forces Ruling Council, and Abacha used the Provisional Ruling Council."),
    q("Nigeria became a federation of thirty-six states during the era of",
      ["Abdulsalami Abubakar", "Yakubu Gowon", "Ibrahim Babangida", "Sani Abacha"], D,
      "On 1 October 1996 General Sani Abacha created six new states, raising the number from 30 to 36, as it still is today."),
    q("Which of the following headed the committee that recommended the suitability of Abuja as a new federal capital city?",
      ["Justice Baba Ardo", "Justice Atanda Fatai Williams", "Justice Udo Udoma", "Justice Akinola Aguda"], D,
      "In 1975 the Murtala Mohammed regime set up a panel headed by Justice Akinola Aguda, which recommended Abuja as the new federal capital; Decree No. 6 of 1976 then created the Federal Capital Territory."),
    q("A public corporation is managed by",
      ["a minister", "a general manager", "the board of governors", "the board of directors"], D,
      "A public corporation is run by a board of directors appointed by the government, which sets its policy; the general manager or managing director handles day-to-day management under the board, and the minister only supervises."),
    q("A major source of revenue in the post-1976 local government in Nigeria is",
      ["internally generated revenue", "the federation account", "grants and loans", "the joint state-local government account"], B,
      "Since the 1976 reform made local government a third tier, councils have received a statutory share of the Federation Account, which is by far their largest source of revenue."),
    q("The Provisional Ruling Council was the highest ruling body during the regime of",
      ["Muhammadu Buhari", "Ibrahim Babangida", "Murtala Muhammed", "Sani Abacha"], D,
      "General Sani Abacha (1993–1998) ruled through the Provisional Ruling Council (PRC), kept by Abdulsalami Abubakar; Buhari had the Supreme Military Council and Babangida the Armed Forces Ruling Council."),
    q("Nigeria's non-alignment policy in the sixties lacked real substance because of her",
      ["Afrocentric policy", "poor economic potential", "partnership with Asian countries", "close ties with Britain"], D,
      "Although the Balewa government declared non-alignment, it kept very close ties with Britain and the West, such as the Anglo-Nigerian Defence Pact (1960–1962), so its non-alignment was not real."),
    // paper 42–50
    q("Under the Technical Aid Corps, Nigerian experts are deployed to",
      ["Africa, the Pacific and the Caribbean", "Europe, South America and Asia", "the Pacific, the Caribbean and Europe", "Asia, Africa and the Pacific"], A,
      "The Technical Aid Corps, set up in 1987, sends Nigerian professionals such as doctors, teachers and engineers to serve in African, Caribbean and Pacific (ACP) countries."),
    q("The centre-piece of Nigeria's foreign policy covers only",
      ["Europe", "Africa", "Latin America", "Asia"], B,
      "Since independence Africa has been the centre-piece of Nigeria's foreign policy: decolonisation, the fight against apartheid, African unity and peace-keeping in Africa."),
    q("Which of the following countries pioneered the establishment of ECOWAS alongside Nigeria?",
      ["Ghana", "Togo", "Algeria", "Cameroun"], B,
      "ECOWAS was founded by the Treaty of Lagos on 28 May 1975 after a joint drive by General Yakubu Gowon of Nigeria and General Gnassingbé Eyadéma of Togo."),
    q("Nigeria's role in the African Union was most prominent during the regime of",
      ["President Olusegun Obasanjo", "President Shehu Shagari", "President Umaru Yar'adua", "President Ibrahim Babangida"], A,
      "The African Union was launched in 2002, and President Obasanjo was one of its chief architects and its Chairman from 2004 to 2006; Shagari and Babangida ruled in the era of the OAU."),
    q("A representative of a Commonwealth country in another member state is known as",
      ["Consul-General", "Ambassador", "Attaché", "High Commissioner"], D,
      "Commonwealth countries exchange High Commissioners, not ambassadors, with one another; a High Commissioner has the same rank and functions as an ambassador."),
    q("The organ of UN that promotes voluntary co-operation among member states in diverse areas is the",
      ["International Court of Justice", "General Assembly", "Economic and Social Council", "Security Council"], B,
      "The General Assembly, where every member has one vote, discusses any matter within the Charter and makes recommendations (which members follow voluntarily) to promote co-operation in political, economic, social, cultural, educational and health fields."),
    q("The main representative body of the United Nations is the",
      ["Security Council", "General Assembly", "Trusteeship Council", "Secretariat"], B,
      "The General Assembly is the only UN organ in which every member state is represented with an equal vote, so it is the UN's main representative and deliberative body."),
    q("The AU differs from the OAU in having",
      ["more effective tools for decision enforcement", "no permanent headquarters", "a minimum of divergent viewpoints", "no assembly of Heads of State"], A,
      "The AU (2002) has stronger enforcement tools than the OAU had: it can intervene in a member state in grave cases such as genocide, suspend governments that take power unconstitutionally and impose sanctions, through organs like the Peace and Security Council."),
    q("OPEC has strong influence with the",
      ["EU", "ADB", "AU", "IMF"], D,
      "Oil prices set by OPEC shape the balance of payments of almost every country, and OPEC members' large oil earnings made them major lenders to the IMF (as in its 1974 and 1975 oil facilities), giving OPEC states strong influence in the Fund.")
  ]);
})();
