/**
 * JAMB/UTME 2009 — GOVERNMENT
 * From the 2009 question paper (all 50 questions); answers from the JAMB/UTME Government answer key
 * 2001–2020, each checked independently. Printing errors carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2009;
  const SRC = 'JAMB UTME 2009';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  QUESTION_BANK.government = QUESTION_BANK.government.concat([
    // paper 1–10
    q("The Inspector General of Police is appointed by the executive on the advice of the",
      ["Nigeria Police Council", "Police Service Commission", "House of Representatives", "Senate of the Federal Republic"], A,
      "Section 215(1)(a) of the 1999 Constitution says the Inspector-General of Police is appointed by the President on the advice of the Nigeria Police Council, from among serving police officers."),
    q("A major problem associated with the Nigerian federalism is",
      ["ethnic conflicts", "environmental pollution", "boundary disputes", "fiscal allocation"], D,
      "How federally collected revenue (mostly oil money) is shared among the federal, state and local governments has been the most persistent quarrel in Nigerian federalism; no formula has ever satisfied everyone."),
    q("The six African members of the Nigerian Council were nominated by the",
      ["Queen", "district officers", "natives", "governors"], D,
      "Lugard's Nigerian Council (1914) was a purely advisory body; its six African members (traditional rulers and others) were nominated by the Governor-General, not elected."),
    q("In the Second Republic, the total membership of each House of Assembly was determined by the",
      ["electoral commission", "political parties", "constitution", "electorate"], C,
      "The 1979 Constitution fixed the size of each State House of Assembly at three times the number of seats the state had in the federal House of Representatives."),
    q("Privatization and commercialization programmes in Nigeria have",
      ["increased public utilities", "de-emphasized government ownership", "reduced government revenue", "encouraged corruption"], B,
      "Privatization sells government shares in public enterprises to private investors, and commercialization makes the remaining ones run for profit; both reduce the role of government ownership in the economy."),
    q("The fear of domination in the public service led to the",
      ["adoption of population as a formula for revenue allocation", "establishment of the Civil Service Commission", "introduction of rotational presidency", "establishment of the Federal Character Commission"], D,
      "To stop any group from dominating public jobs, the federal character principle (1979 Constitution) required a fair spread of posts among states; the Federal Character Commission was set up in 1996 to enforce it."),
    q("In the Igbo political system, the most senior member of the council of elders is the",
      ["okpara", "obi", "eze", "ofo"], A,
      "The okpara is the eldest man of an Igbo lineage; he holds the ofo staff and is the senior member of the council of elders."),
    q("The immediate cause of the 1966 military coup d'etat in Nigeria was",
      ["nepotism", "political instability", "military ambition", "corruption"], B,
      "The violence after the rigged 1965 Western Region election (\"Operation Wetie\") and the 1964 federal election crisis created the political instability that triggered the coup of 15 January 1966."),
    q("The exclusive list is reserved for legislation by the",
      ["regional government", "state government", "local government", "federal government"], D,
      "Only the federal legislature (National Assembly) can make laws on items in the Exclusive Legislative List, such as defence, currency and foreign affairs."),
    q("The participation of Nigerians in the Second World War created in the nationalists the awareness that the",
      ["Africans were superior", "Africans were more qualified to rule", "Europeans were not superior", "Europeans were less tactful in warfare"], C,
      "Nigerian soldiers fought beside Europeans in Burma and East Africa and saw them suffer, fear and die like anyone else, which destroyed the myth of white superiority and strengthened nationalism."),
    // paper 11–20
    q("Which of the following mostly militates against the efficiency and productivity of public corporations in Nigeria?",
      ["Incessant interference by government", "The management teams are always appointed at will", "Boards are often non-professionals", "Members of the management team are always at loggerheads"], A,
      "Constant political interference (in appointments, contracts, pricing and staffing) is the main reason Nigerian public corporations have been inefficient and unprofitable."),
    q("The power to nominate members of the judiciary at the federal level under the 1999 Constitution is vested in the",
      ["Federal Judicial Service Commission", "Supreme Court", "National Judicial Council", "Nigerian Bar Association"], C,
      "Under the Third Schedule of the 1999 Constitution, the National Judicial Council recommends persons to the President for appointment as federal judges; the Federal Judicial Service Commission only advises it and supplies a shortlist."),
    q("Prior to 1976, the local government system practised in Northern Nigeria was",
      ["chief-and-council", "chief-in-council", "prefectorial", "council"], B,
      "Before the 1976 reform, the North kept the native authority system in which the emir or chief ruled with a council (chief-in-council), with the chief having the final word."),
    q("In the segmented Tiv society, governance was usually confined to the",
      ["age grade", "chiefdom", "family", "clan"], C,
      "The Tiv had no chiefs or central government; each family (lineage segment) governed itself under its eldest man, and larger groups came together only for war or serious disputes."),
    q("Which of the following influenced nationalist activities in Nigeria?",
      ["Indian Congress Party", "Negro Diaspora Congress", "Pan-African Congress", "National Congress of British West Africa"], D,
      "The National Congress of British West Africa (1920) demanded elected African representation; its pressure led to the elective principle in the 1922 Clifford Constitution and the rise of political parties in Nigeria."),
    q("The party that did not control any state in the Second Republic was",
      ["NAP", "PRP", "NPP", "GNPP"], A,
      "The Nigeria Advance Party (NAP) of Tunji Braithwaite was registered only for the 1983 elections and won no state; the PRP, NPP and GNPP all controlled states after 1979."),
    q("'Pacification' refers to a process through which some areas in Nigeria were acquired by",
      ["military conquest", "gunboat diplomacy", "signing of treaties", "peaceful negotiation"], A,
      "\"Pacification\" was the colonial word for subduing resistant peoples by force: punitive expeditions such as the Aro Expedition (1901–02) and the conquest of the Sokoto Caliphate (1903) brought areas under British rule."),
    q("Counter-trade was introduced by the government led by",
      ["Abdulsalami Abubakar", "Olusegun Obasanjo", "Muhammadu Buhari", "Ibrahim Babangida"], C,
      "Short of foreign exchange, the Buhari regime (1984–85) bartered Nigerian crude oil directly for goods and equipment from countries such as Brazil, France and Austria; this was called counter-trade."),
    q("A major limitation of the Commonwealth is that it lacks",
      ["the power to set formal rules to govern the affairs of member-nations", "an organizational structure and a definite identity", "enough funds to run its affairs", "the power to compel member-nations to comply with its decisions"], D,
      "The Commonwealth is a voluntary association with no binding charter or enforcement machinery; its strongest sanction is suspension, so it cannot force members to obey its decisions."),
    q("Which of the following countries has withdrawn her membership of the ECOWAS?",
      ["Senegal", "Mauritania", "Guinea Bissau", "Burkina Faso"], B,
      "Mauritania, a founding member, left ECOWAS in 2000. When this paper was set (2009) it was the only country to have left; since 29 January 2025 Burkina Faso, Mali and Niger have also left.",
      { keyVerdict: 'multiple', alsoAccept: [D], keyAnswer: 'B',
        answerNote: "Option D is also correct today: Burkina Faso withdrew from ECOWAS in January 2025, together with Mali and Niger. In 2009 only Mauritania (B) had left, so both are accepted." }),
    // paper 21–30
    q("Which of the following is a major threat to OPEC?",
      ["Persistence of war in the Middle East", "The discovery of crude oil in more countries", "Antagonism by the major world powers", "Development of viable alternatives to crude oil"], D,
      "OPEC's power depends on the world's need for crude oil; viable alternatives (nuclear, solar, wind, biofuels, electric vehicles) reduce that need and so threaten its long-term existence."),
    q("The AU's right to intervene in a member country in crisis portrays it as",
      ["an international organization", "a regional organization", "a supranational organization", "a continental organization"], C,
      "Article 4(h) of the AU Constitutive Act lets the Union intervene in a member state in cases of war crimes, genocide and crimes against humanity; power above member states' sovereignty is what makes a body supranational."),
    q("The permanent membership of the UN Security Council is",
      ["ten", "fifteen", "five", "eleven"], C,
      "The Security Council has five permanent members with the veto (USA, Russia, China, Britain and France) and ten non-permanent members elected for two years, making fifteen in all."),
    q("An advantage of flexible constitution is that it allows for",
      ["political awareness", "constitutional stability", "reduction of ambiguities", "ease of amendment"], D,
      "A flexible constitution can be amended by the ordinary law-making process (as in Britain), so it adapts easily to new situations."),
    q("Power refers to the",
      ["ability to impose one's will upon others", "legal nature of a constitution", "duties political parties demand of their registered members", "duties an individual imposes on himself"], A,
      "Power is the ability to make others act as one wishes, by persuasion, reward or force, even against their will."),
    q("Prorogation is the bringing of a session of a parliament to an end through",
      ["royal proclamation", "final reading", "guillotine", "impeachment"], A,
      "In the British (Westminster) system, the monarch ends a session of Parliament by proclamation on the Prime Minister's advice; Parliament still exists and meets again in a new session."),
    q("The right of all eligible citizens to vote and be voted for is referred to as",
      ["gender equality", "political mandate", "restricted franchise", "universal suffrage"], D,
      "Universal (adult) suffrage gives every qualified adult citizen the vote, whatever their sex, wealth, education or religion."),
    q("Values, beliefs and orientation of a political system are internalized through",
      ["political culture", "political socialization", "political development", "political power"], B,
      "Political socialization is the process (through family, school, peers, religion, media and parties) by which people learn and absorb the political culture of their society."),
    q("Occupational pressure groups pursue their objectives mainly by",
      ["issuing ultimatums and embarking on strikes", "alienating the government", "embarking on guerrilla warfare", "contesting elections"], A,
      "Trade unions and professional associations such as the NLC, ASUU and NMA press their demands by issuing ultimatums and going on strike, not by fighting or contesting elections."),
    q("In a cabinet system, the legislature comprises the",
      ["prime minister and members of the parliament", "prime minister and members of the jury", "prime minister and ministers", "president and ministers"], A,
      "In a parliamentary (cabinet) system the prime minister and the other ministers are themselves members of parliament, so the legislature is made up of the prime minister and all members of parliament."),
    // paper 31–40
    q("The committee that scrutinizes budget proposals in the legislature is the",
      ["Rules and Business Committee", "Public Accounts Committee", "Finance Committee", "Appropriation Committee"], D,
      "The Appropriation (Appropriations) Committee examines the executive's budget proposals (the Appropriation Bill) before they are passed; the Public Accounts Committee checks how money was spent afterwards."),
    q("Democracy is a system of government that is",
      ["constituted by the will of the majority of the citizens", "imposed on the majority of the citizens", "designed to favour the elite", "put in place to favour the party caucus"], A,
      "Democracy is government of the people, by the people, for the people: those who govern are chosen by, and rule with the consent of, the majority of citizens."),
    q("Collective ownership of property is associated with",
      ["feudalism", "communism", "mercantilism", "capitalism"], B,
      "Communism (Marx and Engels) calls for the means of production to be owned collectively by the community, abolishing private ownership and classes."),
    q("The agency responsible for investigating allegations of maladministration in the civil service is the",
      ["Federal Civil Service Commission", "Code of Conduct Bureau", "Public Complaints Commission", "Federal Character Commission"], C,
      "The Public Complaints Commission, Nigeria's ombudsman set up in 1975, investigates complaints of injustice and maladministration by public officers and agencies."),
    q("A political entity that possesses independence is a",
      ["community", "nation", "society", "state"], D,
      "A state has population, territory, government and sovereignty (independence); a nation, community or society is a group of people who need not be independent."),
    q("The principle that advocates strict adherence to the fundamental laws of a country is",
      ["constitutionalism", "individual responsibility", "absolutism", "collective responsibility"], A,
      "Constitutionalism means that government and citizens alike obey the constitution (the fundamental law) and that the powers of government are limited by it."),
    q("One advantage of the unitary system over the federal system is its",
      ["bureaucratic nature", "cost effectiveness", "small membership", "ratification of appointments"], B,
      "A unitary state has one central government instead of many tiers of governors, legislatures and ministries, so it is cheaper to run than a federation."),
    q("Which of the following is a duty of an electoral commission?",
      ["Registration of political parties", "Creation of political parties", "Establishment of electoral tribunals", "Inauguration of the parliament"], A,
      "Electoral bodies such as INEC register political parties, voters and candidates and conduct elections; they do not form parties or set up tribunals."),
    q("A form of government in which the nobles rule for the benefit of all is",
      ["monarchy", "gerontocracy", "aristocracy", "plutocracy"], C,
      "Aristocracy (Greek: \"rule of the best\") is government by a few noble or able people for the good of all; when the few rule for themselves, Aristotle called it oligarchy."),
    q("Fascism as an ideology facilitates",
      ["totalitarianism", "socialism", "communalism", "liberalism"], A,
      "Fascism (Mussolini's Italy, 1922–43) exalts the state and a single leader and allows no opposition, so the state controls every part of life: totalitarianism."),
    // paper 41–50
    q("A prominent feature of a presidential system of government is",
      ["dual executive", "vote of no confidence", "the rule of law", "separation of powers"], D,
      "In a presidential system the executive, legislature and judiciary are separate in personnel and powers; dual executive and votes of no confidence belong to the parliamentary system."),
    q("The executive checks the excesses of the legislature through",
      ["assent to bills", "the use of veto power", "the ratification of treaties", "issuance of orders"], B,
      "The executive can refuse to sign (veto) a bill it considers bad, which the legislature can override only by a two-thirds majority."),
    q("The consciousness of a common identity of a people is called",
      ["nationalism", "integration", "indoctrination", "emancipation"], A,
      "Nationalism is a people's feeling of belonging together as one nation, often expressed in the desire to govern themselves."),
    q("Citizenship of a state by descent requires that",
      ["one is born and bred in the state", "one's mother was born in the state", "one's grandparents were citizens of that state", "one is domiciled in that state"], C,
      "Citizenship by descent comes through blood ties: under s.25 of the 1999 Constitution a person is a Nigerian by birth if a parent or grandparent is a Nigerian citizen, wherever the person was born."),
    q("In order to dispense justice impartially, the judiciary primarily needs",
      ["discipline", "logistics", "motivation", "independence"], D,
      "Judges can decide cases without fear or favour only if they are free from control by the executive, the legislature or any other interest; that is judicial independence."),
    q("A state with a hegemonic political party is one in which",
      ["there is one dominant party", "there is no opposition party", "there is only one party", "other parties are officially recognized"], A,
      "In a dominant (hegemonic) party system, other parties exist legally but one party wins election after election and dominates government."),
    q("Nigeria's commitment to the liberation of Africa could best be seen in her policy towards",
      ["Namibia and Mozambique", "The Congo and Zimbabwe", "Sierra Leone and Chad", "South Africa and Angola"], D,
      "Nigeria recognised the MPLA government of Angola in 1975 and fought apartheid South Africa through sanctions, boycotts and support for the ANC; these two cases defined its African liberation policy."),
    q("The set of policies on the basis of which countries interact with one another is called",
      ["constructive engagement policy", "socio-economic policy", "national policy", "foreign policy"], D,
      "Foreign policy is the set of goals and principles that guide a country's dealings with other countries and international organisations."),
    q("Nigeria's membership of the UN complements her foreign policy in the area of",
      ["bilateral diplomacy", "regional diplomacy", "sub-regional diplomacy", "multilateral diplomacy"], D,
      "The UN is a world body of 193 states, so working through it is multilateral diplomacy; dealings with one country are bilateral, the AU is regional and ECOWAS is sub-regional."),
    q("Nigeria teamed up with other developing countries to assert a neutral posture under the platform of",
      ["Nationalist Movement", "Pan-African Movement", "Non-aligned Movement", "Negritude Movement"], C,
      "The Non-Aligned Movement (Belgrade, 1961) brought together developing countries that refused to join either the Western or the Soviet bloc in the Cold War; Nigeria joined it in the early 1960s."),
  ]);
})();
