/**
 * JAMB/UTME 2004 — GOVERNMENT
 * From the 2004 question paper (all 50 questions); answers from the JAMB/UTME Government answer key
 * 2001–2020, each checked independently. Printing errors carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2004;
  const SRC = 'JAMB UTME 2004';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  QUESTION_BANK.government = QUESTION_BANK.government.concat([
    // paper 1–10
    q("In a democracy, sovereign authority is exercised by the",
      ["people", "executive", "electorate", "legislature"], C,
      "Sovereignty belongs to the people, but it is exercised in practice by the electorate: the citizens qualified to vote, who choose and remove those who govern."),
    q("The agent through which the state undertakes political socialization is the",
      ["school", "family", "peer group", "pressure group"], A,
      "The state controls schools (curriculum, civic education, the anthem and pledge), so the school is the agent through which the state itself shapes political values."),
    q("Unicameral legislature is a common feature of",
      ["presidentialism", "parliamentarism", "unitarism", "federalism"], C,
      "A unitary state has no federating units to represent equally, so a single chamber is common there; federations usually need a second chamber to represent the states."),
    q("Independence of the judiciary is pertinent because it accords the judiciary the power to",
      ["determine a fixed term of office for the judges", "dismiss any judge who has breached the judicial code of conduct", "enable the judge to try and decide cases without bias", "determine a fixed salary for judges"], C,
      "Judicial independence exists so that judges can try and decide cases impartially, without fear of or favour from the executive, the legislature or anyone else."),
    q("In a unitary system of government, power is concentrated at the centre",
      ["without devolution", "with devolution", "with residual functions", "without residual functions"], C,
      "In a unitary state the central government holds all power, including the residual functions; any local units exist only by its will and exercise only what it delegates."),
    q("In a confederation, the constituency that a member of legislature represents is a",
      ["senatorial district", "parliamentary constituency", "nation-state", "region"], C,
      "A confederation is a union of sovereign states, so each member of the common legislature (assembly or congress) is a delegate of a member nation-state."),
    q("In a constitutional monarchy, the authority to remove the head of state is exercised by the",
      ["legislature", "head of government", "cabinet", "prime minister"], A,
      "The monarch's position rests on law made by parliament, so only the legislature can change the succession or remove a monarch, as the British Parliament did in the Abdication Act of 1936."),
    q("In a parliamentary system of government, a vote of no confidence leads to the resignation of",
      ["the entire cabinet", "an individual minister", "the entire parliament", "the prime minister"], A,
      "Because of collective responsibility, a successful vote of no confidence against the government forces the prime minister and the whole cabinet to resign (or call an election)."),
    q("In a presidential system of government, the president checks the legislature through",
      ["executive order", "executive review", "exercise of veto", "legislative order"], C,
      "The president can refuse assent to (veto) bills passed by the legislature; this is the executive's main check on the legislature."),
    q("The economic basis of feudalism is",
      ["capital", "agriculture", "slavery", "trade"], B,
      "Feudalism rested on land: lords granted land (fiefs) to vassals and serfs who farmed it in return for service and produce, so agriculture was its economic base."),
    // paper 11–20
    q("The creation of a classless society is the ultimate aim of",
      ["communism", "capitalism", "socialism", "fascism"], A,
      "Marx saw communism as the final stage of history: a classless, stateless society in which the means of production are owned in common."),
    q("One of the sources of a constitution is",
      ["constitutional law", "common law", "corporate law", "statutory law"], B,
      "Common law (judge-made rules and precedents) is a classic source of a constitution, especially Britain's; statutes passed by the legislature are another.",
      { keyVerdict: 'multiple', alsoAccept: [D], keyAnswer: 'B',
        answerNote: "Option D is also correct. Statutes (acts of parliament such as the Bill of Rights 1689 or the Parliament Acts) are a standard source of a constitution, just as common law is. Constitutional law is the constitution itself, not a source of it, and corporate law deals with companies." }),
    q("The fundamental assumption on which the idea of the rule of law is based is",
      ["rationality of human beings", "equality of human beings", "love for social justice", "supremacy of the constitution"], D,
      "The rule of law assumes that the law (in a written-constitution country, the constitution) is supreme over every person and every organ of government."),
    q("The principle of separation of powers was made popular by",
      ["John Locke", "Baron de Montesquieu", "Thomas Hobbes", "Niccolo Machiavelli"], B,
      "The French writer Baron de Montesquieu popularised the separation of powers in The Spirit of the Laws (1748)."),
    q("Delegated legislation refers to the laws made by",
      ["the legislature", "military governments", "civilian governments", "non-legislative bodies"], D,
      "Delegated legislation is law made by bodies other than the legislature (ministers, agencies, local councils) under powers delegated to them by an act of the legislature."),
    q("Laws made by state governments are known as",
      ["edicts", "acts", "decrees", "bye-laws"], A,
      "Under military rule, state military governors made laws called edicts (the federal government made decrees). Today, under civilian rule, state Houses of Assembly pass laws called \"Laws\" of the state."),
    q("The law of libel limits a citizen's right to freedom of",
      ["association", "movement", "worship", "expression"], D,
      "Libel is a false written or published statement that damages a person's reputation; the law of libel therefore limits freedom of expression and of the press."),
    q("The first franchise in the history of the democratic process is",
      ["female franchise", "male franchise", "universal franchise", "property franchise"], B,
      "The vote was first given to men only (as in ancient Athens and early Britain); women and the poor were added much later, ending in universal adult suffrage.",
      { keyVerdict: 'multiple', alsoAccept: [D], keyAnswer: 'B',
        answerNote: "Option D is also correct. The earliest franchises were limited both by sex and by property: only men could vote, and usually only men who owned property or earned a set income (for example, Nigeria's first elections under the 1922 Clifford Constitution were open only to adult males earning at least £100 a year)." }),
    q("An interest group that admits members and conducts its affairs according to stated rules is described as",
      ["institutional", "organizational", "associational", "non-associational"], C,
      "Associational interest groups (trade unions, professional bodies such as the NBA or NMA) are formally organised, with stated rules, open membership and officers."),
    q("A major influence on the formulation of public opinion is",
      ["public journals", "peer groups", "the family", "the mass media"], D,
      "Radio, television, newspapers and today the internet reach millions at once, so the mass media are the major influence on public opinion."),
    // paper 21–30
    q("The highest grade in the civil service is known as the",
      ["technical cadre", "administrative cadre", "executive cadre", "clerical cadre"], B,
      "The administrative cadre, headed by permanent secretaries, is the top class of the civil service: it advises ministers and formulates policy."),
    q("The pre-colonial Yoruba political system as a whole can best be described as a",
      ["confederation of monarchies and chiefdoms", "federation of chiefdoms and localities", "highly centralized kingdom", "confederation of chiefdoms and localities"], A,
      "Yorubaland was made up of many kingdoms (Oyo, Ife, Ijebu, Egba and others), each with its own oba, loosely linked by common descent from Oduduwa: a confederation of monarchies and chiefdoms."),
    q("The major motivation of British colonization of Nigeria was to",
      ["spread religion", "satisfy British economic interests", "westernize Nigerians", "protect Nigeria from external attack"], B,
      "Britain colonised Nigeria above all for economic reasons: raw materials (palm oil, cocoa, groundnuts, tin), markets for British goods and protection of British trade."),
    q("The Native Authority system was most effective and successful in",
      ["Western Nigeria", "Mid-Western Nigeria", "Northern Nigeria", "Eastern Nigeria"], C,
      "Indirect rule through Native Authorities worked best in the North, where Lugard found centralised emirates with established emirs, taxation and courts."),
    q("The process of nationalism was accelerated by",
      ["rapid economic development", "the coming of Christian missionaries", "the signing of the Atlantic Charter", "improvement in warfare tactics"], C,
      "The Atlantic Charter (August 1941) declared the right of all peoples to choose their own government; nationalists used it to demand self-rule after the Second World War."),
    q("A common feature of the earlier political parties in Nigeria was that they",
      ["started as socio-cultural organizations", "were formed by the government", "were non-elitist in nature", "were backed by the colonialists"], A,
      "The Action Group grew out of Egbe Omo Oduduwa and the NPC out of Jam'iyyar Mutanen Arewa: early Nigerian parties began as socio-cultural associations."),
    q("Under the 1999 Constitution, the power to declare war is vested in the",
      ["legislature", "executive", "National Council of States", "National Security Council"], B,
      "Section 5(4) of the 1999 Constitution lets the President (the executive) declare a state of war, but only with the sanction of a resolution of both Houses of the National Assembly in joint session."),
    q("A distinguishing feature of the 1979 Constitution was the",
      ["departure from the parliamentary to the presidential system", "preservation and entrenchment of republicanism", "introduction of unicameralism into Nigeria", "introduction of a federal structure"], A,
      "The 1979 Constitution replaced the Westminster parliamentary system of 1960–66 with an American-style executive presidency."),
    q("The two chambers of elected national representatives in Nigeria are called",
      ["the parliament", "the senate", "House of Assembly", "the National Assembly"], D,
      "Nigeria's federal legislature, the National Assembly, has two chambers: the Senate (109 members) and the House of Representatives (360 members)."),
    q("Judicial administration in respect of the national code of conduct lies with the",
      ["Judicial Service Commission", "Code of Conduct Tribunal", "Public Complaints Commission", "Code of Conduct Bureau"], B,
      "The Code of Conduct Tribunal is the court that tries public officers who breach the Code of Conduct; the Bureau only receives asset declarations and refers breaches to the Tribunal."),
    // paper 31–40
    q("In the Second Republic, the ruling National Party of Nigeria formed an alliance with the",
      ["Unity Party of Nigeria", "Nigeria People's Party", "Great Nigeria People's Party", "Nigeria Advance Party"], B,
      "In 1979 the NPN formed an accord with Azikiwe's Nigeria People's Party (NPP) to secure a working majority in the National Assembly; the accord broke down in 1981."),
    q("The relationship between the tiers of government in Nigeria can be described as one of",
      ["independent co-existence", "coordinate and independent jurisdiction", "voluntary subordination", "superior-subordinate co-existence"], D,
      "In practice the federal government dominates the states, and local governments are under the states, so Nigeria's tiers co-exist in a superior-subordinate relationship.",
      { keyVerdict: 'multiple', alsoAccept: [B], keyAnswer: 'D',
        answerNote: "Option B is also correct. In federal theory, and in the constitution's division of powers into exclusive and concurrent lists, the federal and state governments are coordinate and independent, each supreme in its own sphere (K. C. Wheare's definition of federalism). D describes Nigeria's practice, with a dominant centre and local governments under the states." }),
    q("The 1976 Local Government Reforms in Nigeria transformed the relationship between states and local government into one of",
      ["master and servant", "partnership and cooperation", "equality", "subordination"], B,
      "The 1976 reform made local government a third tier with its own functions and a statutory share of revenue, so that states and councils would work as partners rather than master and servant."),
    q("Government-owned companies operating in the economic sector are referred to as",
      ["public utilities", "public enterprises", "public investments", "public services"], B,
      "Public enterprises are businesses owned by government that produce goods and services for sale, such as the NNPC; public utilities are one kind of them (water, power)."),
    q("The difference between commercialized and privatized companies is that in the former",
      ["private ownership is dominant", "public ownership is dominant", "government subsidizes costs", "profit motive is recessive"], B,
      "A commercialised company stays government-owned but must run at a profit; a privatised company has been sold to private owners."),
    q("The body responsible for running the personnel affairs of senior local government staff in Nigeria is the",
      ["Local Government Council", "State Civil Service Commission", "Senior Staff Commission", "Local Government Service Commission"], D,
      "Each state's Local Government Service Commission appoints, promotes and disciplines senior local government staff; the councils handle junior staff."),
    q("The immediate cause of the January 15, 1966 military coup in Nigeria was the",
      ["Kano Riots", "Tiv Riots", "election crisis in the Western Region", "crisis over the population census"], C,
      "The rigged Western Region election of October 1965 led to widespread violence (\"Operation Wetie\"), which the majors cited as they struck on 15 January 1966."),
    q("Nigeria demonstrated her commitment to the policy of non-alignment during the regime of",
      ["Muhammadu Buhari", "Johnson Aguiyi-Ironsi", "Murtala Muhammed", "Ibrahim Babangida"], C,
      "In 1975 Murtala Muhammed recognised the MPLA government of Angola in defiance of the United States, declaring that \"Africa has come of age\": a bold show of independence from both blocs."),
    q("Nigeria's support for the South-South Cooperation is based on her desire to",
      ["promote economic understanding in the Third World", "counter the political and military domination by major powers", "assert her leadership role in Africa", "promote her non-aligned policy"], A,
      "South-South Cooperation is economic and technical cooperation among developing countries, so Nigeria's support for it aims at economic understanding within the Third World."),
    q("Nigeria's relation with black political communities outside Africa is built on",
      ["economic considerations", "shared political aspirations", "perceived cultural affinities", "expectations of political support from them"], C,
      "Nigeria's ties with black people in the Caribbean, the Americas and elsewhere rest on shared African descent and culture, shown for example in hosting FESTAC '77."),
    // paper 41–50
    q("The one-time president of the United Nations General Assembly was",
      ["Maitama Sule", "Joseph Garba", "Ibrahim Gambari", "Arthur Mbanefo"], B,
      "Major-General Joseph Garba presided over the 44th UN General Assembly (1989–1990). Since the paper, a second Nigerian, Tijjani Muhammad-Bande, has held the post (2019–2020)."),
    q("The leaders who spearheaded the transformation of the Organization of African Unity into the African Union are from",
      ["South Africa, Libya and Zambia", "Nigeria, Libya and South Africa", "Nigeria, Liberia and Kenya", "Algeria, Libya and Morocco"], B,
      "Muammar Gaddafi of Libya, Olusegun Obasanjo of Nigeria and Thabo Mbeki of South Africa drove the change from the OAU to the AU (Sirte Declaration 1999; AU launched in 2002)."),
    q("The countries in which Nigeria participated in the ECOMOG peace-keeping operations were",
      ["Liberia and Guinea", "Sierra Leone and Cote d'Ivoire", "Senegal and Cote d'Ivoire", "Liberia and Sierra Leone"], D,
      "Nigeria led and largely paid for ECOMOG in Liberia (from 1990) and Sierra Leone (from 1997)."),
    q("The permanent members of the Security Council of the United Nations are",
      ["Britain, Japan, Australia, Germany and the United States", "Germany, France, Poland, Hungary and China", "the United States, Russia, France, Britain and China", "the United States, Russia, France, Britain and Japan"], C,
      "The five permanent, veto-holding members are the USA, Russia, France, Britain and China; this is still true today."),
    q("A specialized agency of the United Nations Organization is the",
      ["World Health Organization", "General Assembly", "International Court of Justice", "International Olympic Committee"], A,
      "The WHO is a specialised agency linked to the UN by agreement; the General Assembly and the ICJ are principal organs, and the IOC is not part of the UN at all."),
    q("With the admission of Asian and African countries to the Commonwealth, the Queen of England became the",
      ["head of state of these countries", "head of government of these countries", "patron of the Commonwealth", "head of the Commonwealth"], D,
      "When republics such as India joined (London Declaration, 1949), the Queen became the symbolic Head of the Commonwealth rather than head of state of every member. King Charles III has been Head of the Commonwealth since 2022."),
    q("A major problem of the defunct Organization of African Unity was",
      ["ideological differences", "language barrier", "inadequate resources", "cultural diversity"], A,
      "The OAU was weakened by ideological splits among its members (radical Casablanca versus moderate Monrovia groups, pro-East versus pro-West states), which blocked common action."),
    q("The Lagos Treaty of May 28th 1975 led to the formation of the",
      ["Economic Commission for Africa", "Economic Community of West African States", "Lagos Plan of Action", "African Economic Summit"], B,
      "ECOWAS was founded by the Treaty of Lagos, signed by 15 West African states on 28 May 1975."),
    q("The current Executive Secretary of the ECOWAS is",
      ["Lansana Kouyate", "Abubakar Ouattara", "Mohammed Ibn Chambas", "Abass Bundu"], C,
      "Mohamed Ibn Chambas of Ghana was Executive Secretary from 2002, when the paper was set. Since 2007 the post has been President of the ECOWAS Commission, held from 2022 by Omar Alieu Touray of The Gambia."),
    q("The responsibility for admitting new members to the OPEC rests with the",
      ["Board of Governors", "Conference", "Secretariat", "Summit"], B,
      "The OPEC Conference of oil ministers is the supreme authority; it admits new members by a three-fourths majority including all five founder members."),
  ]);
})();
