/**
 * JAMB/UTME 2017 — GOVERNMENT
 * From the 2017 question paper (questions 1–40); answers from the JAMB/UTME Government answer key
 * 2001–2020, each checked independently. Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2017;
  const SRC = 'JAMB UTME 2017';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  QUESTION_BANK.government = QUESTION_BANK.government.concat([
    // paper 1–10
    q("The Northern and Southern protectorates were made provinces under the",
      ["Macpherson Constitution", "Richards Constitution", "Clifford Constitution", "Lyttelton Constitution"], C,
      "After the 1914 amalgamation the two protectorates were run as the Northern Provinces and the Southern Provinces, and the 1922 Clifford Constitution was built on that arrangement: its Legislative Council made laws for Lagos and the Southern Provinces, while the governor legislated for the Northern Provinces."),
    q("The legal right to exercise power in a state is referred to as",
      ["authority", "sovereignty", "coercion", "influence"], A,
      "Authority is power that is legal and accepted as rightful: the recognised right to give orders and be obeyed."),
    q("The primary reason for the establishment of political parties is to",
      ["attain political power", "protect political interest", "make laws", "lobby the government"], A,
      "A political party is an organised group that seeks to win elections and so capture and control the government; this aim to attain power is what sets it apart from a pressure group."),
    q("The head of government under the 1979 Constitution is the",
      ["President", "Prime Minister", "Speaker of the House of Representatives", "Senate President"], A,
      "The 1979 Constitution introduced the presidential system, in which the executive President is both head of state and head of government."),
    q("A system of government in which an individual rules with absolute power is",
      ["theocracy", "democracy", "autocracy", "aristocracy"], C,
      "Autocracy is rule by one person who holds absolute, unchecked power."),
    q("One of the demerits of the privatisation of public corporations in Nigeria is",
      ["scarcity of goods and services", "higher cost of goods and services", "creation of unemployment", "inefficient service delivery"], B,
      "Private owners run former public corporations for profit and remove subsidies, so the prices of their goods and services (fuel, power, telephone) usually rise."),
    q("In which of the following does the state have absolute control of all aspects of citizens' life?",
      ["Autocracy", "Democracy", "Communalism", "Totalitarianism"], D,
      "A totalitarian state (Nazi Germany, Stalin's Soviet Union) seeks to control every aspect of citizens' lives: politics, economy, education, religion, the media and even private life."),
    q("Early nationalist activities manifested in the form of",
      ["discrimination", "resistance", "participation", "disagreement"], B,
      "The earliest nationalism in West Africa took the form of resistance: traditional rulers and peoples opposed British conquest by arms (Jaja of Opobo, Nana of Itsekiri, Oba Ovonramwen of Benin), followed by protests against colonial measures."),
    q("One major merit of the unitary system of government is that it",
      ["is not democratic", "is cheaper to operate", "eradicates corruption", "eliminates tyranny"], B,
      "A unitary state has only one central government with one set of institutions, so it is cheaper to run than a federation with many governments, legislatures and civil services."),
    q("Successive population figures have been contested in Nigeria because of",
      ["gender consideration", "religious consideration", "geographical disparity", "political consideration"], D,
      "Population figures decide the sharing of seats in the legislature, revenue allocation and the siting of amenities, so each region and group has a political interest in a high count; that is why censuses (1962/63, 1973, 1991, 2006) were disputed."),
    // paper 11–20
    q("Akwa Ibom and Katsina States were created in",
      ["1987", "1985", "1988", "1990"], A,
      "General Ibrahim Babangida created Akwa Ibom (from Cross River) and Katsina (from Kaduna) on 23 September 1987, raising the number of states from 19 to 21."),
    q("The African country that was not colonized is",
      ["Sudan", "Botswana", "Gambia", "Ethiopia"], D,
      "Ethiopia defeated Italy at Adwa in 1896 and kept its independence; apart from the brief Italian occupation of 1936–41 it was never a colony. Sudan, Botswana and The Gambia were all British territories."),
    q("One of the major sources of a constitution is",
      ["party system", "conventions", "political structure", "political party"], B,
      "Sources of a constitution include statutes, judicial precedents, conventions, customs, historical documents and the works of learned writers; conventions are unwritten rules of political practice that are obeyed as if they were law."),
    q("Absence of a charter has been a problem of",
      ["ECOWAS", "UNO", "OAU", "Commonwealth"], D,
      "The UN and the OAU were each founded on a charter and ECOWAS on its treaty, but for most of its history the Commonwealth had no founding charter, only declarations such as London (1949), Singapore (1971) and Harare (1991). It has had a Charter of the Commonwealth since 2013."),
    q("One of the duties and obligations of the state to the citizens is",
      ["loyalty", "payment of wages", "protection of property", "assistance"], C,
      "The state owes its citizens protection of their lives and property, the maintenance of law and order and the provision of welfare; loyalty is a duty the citizen owes the state."),
    q("The appointment and dissolution of the Board of Directors of public corporations fall under",
      ["ministerial control", "legislative control", "political control", "judicial control"], A,
      "Under ministerial control the supervising minister appoints and can dissolve the board of a public corporation, gives it general policy directions and approves major decisions."),
    q("Which of the following is a process of military disengagement from Nigerian politics?",
      ["Increase in military budget", "Conduct of free and fair elections", "Appointment of army officers into political posts", "Strengthening the army"], B,
      "The military withdraws from politics by organising a transition programme that ends in free and fair elections and the handover of power to elected civilians, as in 1979 and 1999."),
    q("Which of the following is an advantage of the presidential system of government?",
      ["Checks and balances", "Absence of opposition", "Cost effectiveness", "Less red-tapism"], A,
      "The presidential system separates the executive, legislature and judiciary and lets each check the others (veto, impeachment, confirmation of appointments, judicial review), which guards against abuse of power."),
    q("The chairman of the 1976 Constitution Drafting Committee was",
      ["Udo Udoma", "Ademola Adetokunbo", "Rotimi Williams", "Niki Tobi"], C,
      "The 49-member Constitution Drafting Committee (1975–76) that drafted the 1979 Constitution was chaired by Chief F.R.A. (Rotimi) Williams."),
    q("The totality of Nigeria's participation in the international system is known as",
      ["international policy", "foreign policy", "economic policy", "social policy"], B,
      "Foreign policy is the sum of the principles, goals and actions that guide a country's dealings with other states and international organisations."),
    // paper 21–30
    q("The organ of the UN that served as custodian of some African countries prior to their independence is",
      ["the International Court of Justice", "the Security Council", "the Trusteeship Council", "the General Assembly"], C,
      "The UN Trusteeship Council supervised trust territories such as Tanganyika, Togoland, the Cameroons, Ruanda-Urundi and Somaliland until they became independent; it has been inactive since 1994."),
    q("Grants received by the local government councils in Nigeria are from",
      ["National Revenue Allocation Commission", "federal and state governments", "federal government only", "state government only"], B,
      "Since the 1976 reform local governments have received statutory allocations and grants from both the federal government (through the Federation Account) and their state government."),
    q("Disputes among member states of ECOWAS are settled by",
      ["the technical and specialized commission", "the board of trustees", "the Community Tribunal", "the Council of Ministers"], C,
      "The 1975 ECOWAS Treaty set up a Community Tribunal to settle disputes between member states; under the revised treaty of 1993 it is now the ECOWAS Community Court of Justice in Abuja."),
    q("Ensuring that appointments into federal establishments in Nigeria reflect geographical spread is the sole function of the",
      ["Revenue Mobilization Allocation and Fiscal Commission", "Civil Service Commission", "Federal Character Commission", "Public Complaints Commission"], C,
      "The Federal Character Commission, set up in 1996 and backed by the 1999 Constitution, monitors appointments in federal establishments so that they reflect the federal character (spread of states and zones) of Nigeria."),
    q("A major difference between a pressure group and a political party is that whereas the latter aims at winning power, the former",
      ["executes government policies", "aims at winning elections", "influences government policies", "nominates potential leaders for government"], C,
      "A pressure group does not seek to take over government; it only tries to influence government policies in its members' favour, whereas a party seeks to win elections and govern."),
    q("The quorum in the OPEC Conference is formed with the attendance of",
      ["one third of member states", "half of member states", "two thirds of member states", "three quarters of member states"], D,
      "The OPEC Statute provides that a quorum of three-quarters of the full members is needed to hold a meeting of the Conference, the organisation's supreme authority."),
    q("The characteristic of the civil service which prevents its officers from addressing the press unless directed is known as",
      ["immorality", "neutrality", "anonymity", "impersonality"], C,
      "Anonymity means civil servants work in the background: they do not take public credit or blame and do not speak to the press unless authorised; the minister answers publicly for the ministry."),
    q("Which of the following emphasizes the rule of law and human rights protection?",
      ["Constitutionalism", "Delegated legislation", "Decentralisation", "Centralisation"], A,
      "Constitutionalism is the principle that government is limited by and must operate within the constitution, which means respect for the rule of law and protection of fundamental human rights."),
    q("The needs of the citizens are made known to the government through",
      ["judiciary", "political party", "civil service", "public opinion"], D,
      "Public opinion is the collective view of citizens on public issues, expressed through the media, polls, protests, letters and elections; it tells the government what the people need and want."),
    q("The tenet of non-alignment connotes",
      ["political instability", "political neutrality", "political alliance", "political non-participation"], B,
      "Non-alignment meant not taking sides with either power bloc in the Cold War (the US-led West or the Soviet-led East): a position of political neutrality, not of withdrawal from world affairs."),
    // paper 31–40
    q("Smaller parties have little chance of winning elections in a",
      ["alternative voting system", "proportional representation system", "absolute majority system", "pluralist system"], D,
      "Under the plurality (first-past-the-post) system the candidate with the most votes in each constituency wins, so small parties with scattered support win few or no seats."),
    q("The head of the palace in the pre-colonial Hausa system is",
      ["Sarkin Dawaki", "Sarkin Gida", "Sarkin Fada", "Sarkin Ruwa"], C,
      "In the Hausa-Fulani emirate the Sarkin Fada was the head of palace officials and workers, and the link between the emir and the other officials."),
    q("The main function of the legislature is",
      ["law review", "law making", "law implementation", "law interpretation"], B,
      "The primary function of the legislature is to make laws; the executive implements them and the judiciary interprets them."),
    q("One of the demerits of the 1979 Constitution in Nigeria was that of",
      ["concentration of power at the centre", "impeachment procedure", "separation of powers", "cost of governance"], D,
      "The 1979 Constitution's American-style presidential system, with an executive president, a two-chamber National Assembly and large executives and assemblies in 19 states, was very costly to run."),
    q("A major feature of monarchy is that it is",
      ["headed by a king", "hereditary", "headed by a queen", "headed by the richest citizen"], B,
      "In a monarchy the throne passes by heredity within a royal family; the monarch may be a king or a queen."),
    q("The New Partnership for Africa's Development was an attempt to overcome",
      ["civil wars in Africa", "diseases in Africa", "obstacles to African development", "coups in Africa"], C,
      "NEPAD (2001), promoted by Presidents Obasanjo, Mbeki, Bouteflika and Wade and adopted by the African Union, is a programme to remove the obstacles to Africa's development: poverty, poor governance, weak infrastructure and debt."),
    q("One important agent of political socialisation is the",
      ["political party structure", "political party", "party constitution", "party manifesto"], B,
      "Agents of political socialisation are the institutions that pass on political values and attitudes: the family, school, peer groups, religious bodies, the mass media and political parties."),
    q("Bye-laws are made by the",
      ["judiciary", "legislature", "local government", "executive"], C,
      "Bye-laws are rules made by a local government council for its own area, such as on markets, sanitation and motor parks; they are a form of delegated legislation."),
    q("In the AU, which of the following organs prepares the agenda for meetings?",
      ["The Council of Ministers", "General Secretariat", "The Liberation Committee", "The Assembly of Heads of State and Government"], A,
      "The council of ministers (in the AU called the Executive Council, as in the OAU's Council of Ministers before it) prepares the meetings and draws up the provisional agenda of the Assembly of Heads of State and Government."),
    q("Which of these is an economic programme designed by the military?",
      ["National Youth Service Corps", "War Against Indiscipline", "Directorate of Food, Roads and Rural Infrastructure", "Mass Mobilization for Social Justice"], C,
      "The Directorate of Food, Roads and Rural Infrastructure (DFRRI) was set up by Babangida's military government in 1986 to build rural roads, water supply and food production, an economic programme; NYSC, WAI and MAMSER were social programmes."),
  ]);
})();
