/**
 * JAMB/UTME 2019 — GOVERNMENT
 * From the 2019 question paper (questions 1–40); answers from the JAMB/UTME Government answer key
 * 2001–2020, each checked independently. Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2019;
  const SRC = 'JAMB UTME 2019';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  QUESTION_BANK.government = QUESTION_BANK.government.concat([
    // paper 1–10
    q("Fusion of power is an attribute of a",
      ["democratic society", "presidential government", "monarchical state", "parliamentary state"], D,
      "In the parliamentary system the executive (Prime Minister and cabinet) is drawn from and sits in the legislature, so executive and legislative powers are fused rather than separated."),
    q("In the pre-colonial system, checks and balances were prominent in the",
      ["Igbo system", "Tiv system", "Yoruba system", "Hausa-Fulani system"], C,
      "In the Old Oyo (Yoruba) system the Alaafin's power was checked by the Oyo Mesi, the Oyo Mesi was checked by the Ogboni, and the Are-Ona-Kakanfo led the army, so power was balanced among several institutions."),
    q("Foreign policy is relevant because it",
      ["encourages rivalry among nations", "encourages interference in other countries' domestic policy", "makes foreign countries aggressive", "helps to foster good relationship between nations"], D,
      "A sound foreign policy guides how a state deals with other states, helping it to promote friendship, cooperation and good relations while protecting its national interest."),
    q("Emirate system is associated with",
      ["Yoruba pre-colonial system", "Hausa-Fulani pre-colonial system", "Igbo pre-colonial system", "Tiv pre-colonial system"], B,
      "After Usman dan Fodio's jihad (from 1804) the Hausa states became emirates, each ruled by an Emir under the Sokoto Caliphate."),
    q("The major reason against open balloting is that it",
      ["is costly", "is crude", "can lead to intimidation", "is simple to operate"], C,
      "In open balloting (queuing or show of hands) everyone can see how each person votes, so voters can be intimidated, victimised or bribed; the secret ballot was designed to prevent this."),
    q("The first aborted coup in Nigeria was staged by",
      ["Gen Olusegun Obasanjo", "Gen Murtala Mohammed", "Lt. Col Buka Suka Dimka", "Gen Tunde Idiagbon"], C,
      "On 13 February 1976 Lt. Col. Buka Suka Dimka led a coup attempt in which General Murtala Mohammed was killed, but the coup failed and Obasanjo took over; Dimka was later executed."),
    q("Political parties are expected to",
      ["control the government", "dictate to government", "manipulate public officials", "control public officials"], A,
      "The aim of a political party is to win elections and so take control of the government and run it according to its programme."),
    q("The lapses of the Clifford Constitution necessitated its replacement with the",
      ["Lyttelton Constitution", "Richards Constitution", "Macpherson Constitution", "Lugard Constitution"], B,
      "The Clifford Constitution of 1922 was replaced by the Richards Constitution of 1946 (in force 1947), which brought the North into the central legislature and created three regions."),
    q("In the Hausa/Fulani political systems, the administrative functions were carried out by the",
      ["Madawaki", "Hakimi", "Dogari", "Waziri"], D,
      "The Waziri was the Emir's chief adviser and head of administration, much like a prime minister, who coordinated the work of the other officials."),
    q("What differentiates a public corporation from a private enterprise?",
      ["Financing", "Proclamation", "Ownership", "Membership"], C,
      "A public corporation is owned by the government on behalf of the public, while a private enterprise is owned by private individuals or shareholders."),
    // paper 11–20
    q("One of the major problems of ECOWAS is",
      ["lack of military force", "the presence of CEAO as a competitor", "overlapping functions of her agencies", "political instability in the region"], D,
      "Coups, civil wars and unstable governments in member states (Liberia, Sierra Leone, Guinea-Bissau, Mali and others) have repeatedly disrupted ECOWAS's programmes for economic integration."),
    q("A public corporation becomes commercialised when",
      ["it is expected to make profit", "the edict for its establishment is repealed", "its board of directors is statutorily constituted", "it no longer provides essential services"], A,
      "Commercialisation means the government still owns the corporation but requires it to run on business lines, cover its costs and make a profit instead of depending on subsidies."),
    q("In the presidential system, the executive council comprises the president and the",
      ["ministers", "head of service", "ambassadors", "special advisers"], A,
      "The executive council (in Nigeria the Federal Executive Council) is made up of the President, the Vice-President and the ministers appointed by the President."),
    q("Delegated legislation becomes expedient because of the need",
      ["to control appointees", "for parliamentary control", "for judicial control", "for convenience"], D,
      "Parliament lacks the time and technical knowledge to make every detailed rule, so for convenience it passes the main law and lets ministers, agencies and local authorities make the detailed regulations."),
    q("The reason for the first military intervention in Nigeria includes which of the following?",
      ["Kano riot", "Western Region election crisis", "Hatred for the politicians", "Dispute over census result"], B,
      "The rigged Western Region election of October 1965 led to widespread violence ('Operation Wetie') and was one of the main reasons the soldiers gave for the coup of 15 January 1966.",
      { keyVerdict: 'multiple', alsoAccept: [D], keyAnswer: 'B',
        answerNote: "Option D is also correct: the disputed 1962–63 census, which the regions fought over bitterly, is one of the standard causes listed for the January 1966 coup, alongside the Western Region election crisis. Both are accepted." }),
    q("The capacity to affect another person's behaviour by the threat of sanction is",
      ["authority", "power", "sovereignty", "legitimacy"], B,
      "Power is the ability to make others act as you want, backed by the threat of sanctions (punishment) if they do not."),
    q("The judicial administration of issues bothering on the code of conduct is the responsibility of the",
      ["Code of Conduct Tribunal", "Code of Conduct Service", "Code of Conduct Commission", "Code of Conduct Bureau"], A,
      "The Code of Conduct Tribunal is the court that tries public officers accused of breaching the code of conduct; the Code of Conduct Bureau only receives asset declarations and refers breaches to the Tribunal."),
    q("Nigeria's membership of ECOWAS has been beneficial to her because it",
      ["ensured Nigeria's return to democratic rule in 1999", "has assisted in the fight against Boko Haram insurgency", "has helped to eliminate obstacles to free movement of persons", "has tied Nigeria's economic fortunes to West Africa"], C,
      "The ECOWAS Protocol on Free Movement of Persons (1979) lets Nigerians and other West Africans travel, live and work in member states without visas."),
    q("Nigeria's foreign policy implementation is the exclusive responsibility of the",
      ["Ministry of Budget and Planning", "Department of Immigration", "Ministry of External Affairs", "Nigerian Institute of International Affairs"], C,
      "The Ministry of External Affairs (today called the Ministry of Foreign Affairs) carries out Nigeria's foreign policy through its embassies and high commissions abroad."),
    q("Bourgeoisie is a class in",
      ["socialism", "communism", "capitalism", "feudalism"], C,
      "In Marxist terms the bourgeoisie is the capitalist class that owns the means of production, as opposed to the proletariat (workers) who sell their labour."),
    // paper 21–30
    q("In appointing the chairman of the Independent National Electoral Commission, the president must consult with the",
      ["National Council of State", "state governors", "National Assembly", "National Judicial Council"], A,
      "Section 154(3) of the 1999 Constitution requires the President to consult the Council of State before appointing the INEC chairman and members; the appointment is then confirmed by the Senate."),
    q("Checks and balances guarantee",
      ["superiority of the legislature", "balance of the three arms", "superiority of the executive", "subordination of the judiciary"], B,
      "Under checks and balances each arm of government (legislature, executive and judiciary) can limit the others, so no arm becomes dominant and the three stay in balance."),
    q("A popular technique employed by pressure groups to achieve their objectives is",
      ["gerrymandering", "campaign", "coercion", "protests"], D,
      "Pressure groups commonly use protests and demonstrations (as well as lobbying, strikes and petitions) to draw attention to their demands and press the government."),
    q("The Unity Party of Nigeria in its manifesto emphasised",
      ["class struggle", "mixed economy", "dictatorship of the proletariat", "socialist principles"], D,
      "The UPN, led by Chief Obafemi Awolowo in the Second Republic, preached democratic socialism, with free education, free health care, integrated rural development and full employment."),
    q("Monarchy remains a natural institution that believes in",
      ["rulership by the people", "rulership of a kingdom", "competitive selection of leaders", "equitable power distribution"], B,
      "A monarchy is a kingdom ruled by a king or queen who usually inherits the throne; it is not based on rule by the people or on competitive selection of leaders."),
    q("The 1999 Constitution of Nigeria is said to be supreme because",
      ["its provisions must be respected by all and sundry", "the president has sovereign immunity", "the Supreme Court retained the power of judicial review", "it enhances fundamental human rights"], A,
      "Section 1(1) of the 1999 Constitution declares it supreme and binding on all authorities and persons throughout Nigeria, and any law inconsistent with it is void."),
    q("The armed forces are classified as",
      ["public servants", "federal civil servants", "civil servants", "political appointees"], A,
      "Members of the armed forces serve the state and are paid from public funds, so they are public servants; they are not civil servants, who work in government ministries and departments."),
    q("Statutory age is a requirement for obtaining citizenship through",
      ["naturalisation", "duality", "marriage", "birth"], A,
      "To become a citizen by naturalisation a person must be of full age (18 and above under the 1999 Constitution), among other conditions such as residence and good character."),
    q("\"Africa as the centrepiece of Nigeria's foreign policy\" could be traced back to the administration of",
      ["Sir Ahmadu Bello", "Alhaji Shehu Shagari", "Sir Abubakar Tafawa Balewa", "Gen Yakubu Gowon"], C,
      "From independence in 1960, Prime Minister Sir Abubakar Tafawa Balewa made Africa the cornerstone of Nigeria's foreign policy; the Adedeji panel restated it as the 'centrepiece' in 1976."),
    q("A president of a state performs a judicial function through",
      ["dismissal of judges", "assent to bills", "prerogative of mercy", "appointment of judges"], C,
      "Through the prerogative of mercy the President can pardon convicts, commute or reduce sentences and grant reprieves, which is a judicial-type function exercised by the executive."),
    // paper 31–40
    q("The highest and most powerful organ of OPEC is the",
      ["Conference", "Secretariat", "Council of Ministers", "Board of Governors"], A,
      "The OPEC Conference, made up of the oil ministers of member countries, is the supreme authority that decides OPEC's policies."),
    q("Which of these is the first political party in Nigeria?",
      ["NYM", "NNDP", "NCNC", "NPC"], B,
      "Herbert Macaulay founded the Nigerian National Democratic Party (NNDP) on 24 June 1923 to contest the Lagos elective seats created by the Clifford Constitution."),
    q("The military regime abolished the state ministries of local government in Nigeria in",
      ["1985", "1957", "1990", "1989"], D,
      "The Babangida regime abolished the state ministries of local government (1989) so that councils dealt more directly with the federal government and got their allocations directly."),
    q("Government by the best men is referred to as",
      ["democratic", "autocratic", "aristocratic", "totalitarianism"], C,
      "Aristocracy (from the Greek aristos, 'best') is government by a few of the best or noblest men in society."),
    q("Human rights are usually enshrined in a constitution with a view to",
      ["avoid tenure elongation", "promote peaceful co-existence", "protect political office holders", "protect the rights of individuals in a state"], D,
      "Fundamental human rights are written into a constitution (Chapter IV of the 1999 Constitution) so that they are protected by law and can be enforced in court against anyone, including the government."),
    q("The political culture that has to do with the loyalty of the people towards the government is",
      ["evaluative orientation", "cognitive orientation", "societal orientation", "affective orientation"], D,
      "In Almond and Verba's scheme, affective orientation concerns people's feelings towards the political system, such as attachment, loyalty or alienation."),
    q("The existence of the OAU was seriously threatened in 1982–1983 because of a conflict which led to the departure of",
      ["Rwanda and Angola", "Namibia and South Africa", "Morocco", "Somalia and Ethiopia"], C,
      "The admission of the Sahrawi Arab Democratic Republic (Western Sahara) in 1982 split the OAU, its summits failed to form a quorum, and Morocco left the organisation in 1984; Morocco rejoined the AU in 2017."),
    q("A factor that can cause hindrance to the effectiveness of the civil service in Nigeria is",
      ["executive control", "low incentive", "legal control", "registration of civil servants"], B,
      "Poor pay, poor conditions of service and few rewards for good work leave civil servants unmotivated, which lowers efficiency and encourages corruption."),
    q("Which of the following commissions is responsible for sharing revenue based on an agreed formula in Nigeria?",
      ["Revenue Mobilisation Allocation and Fiscal Commission", "National Planning Commission", "National Human Rights Commission", "Federal Civil Service Commission"], A,
      "The Revenue Mobilisation Allocation and Fiscal Commission (RMAFC) monitors what goes into and comes out of the Federation Account and applies and reviews the formula for sharing revenue among the tiers of government."),
    q("Public opinion is NOT formed through",
      ["mass media", "symposia and lectures", "documentary", "advertisement"], D,
      "Public opinion on public issues is shaped by the mass media, lectures, symposia and documentaries; advertisement mainly aims to sell goods and services, not to form opinion on public affairs."),
  ]);
})();
