/**
 * JAMB/UTME 2011 — GOVERNMENT
 * From the 2011 question paper (questions 2–50; Q1 only asked for the paper type); answers from the
 * JAMB/UTME Government answer key 2001–2020, each checked independently. Answer checks carry
 * keyVerdict/answerNote.
 */
(function () {
  const Y = 2011;
  const SRC = 'JAMB UTME 2011';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  QUESTION_BANK.government = QUESTION_BANK.government.concat([
    // paper 2–11
    q("The development of attitudes and beliefs about a political system is",
      ["political emancipation", "political socialization", "political participation", "political orientation"], B,
      "Political socialisation is the lifelong process (through family, school, peer groups, religion, mass media and parties) by which people acquire their political attitudes, beliefs and values."),
    q("Political behaviour is governed by",
      ["political socialization", "political ideology", "political economy", "political culture"], D,
      "Political culture is the society's shared beliefs, attitudes and values about politics; it sets the norms that shape how people behave politically (voting, protest, obedience)."),
    q("In a nation, sovereignty is vested in the",
      ["community", "state", "elite", "electorate"], D,
      "In a democratic nation political (popular) sovereignty rests with the people, expressed through the electorate, who choose and can remove those who govern them."),
    q("Which of the following is a feature of democracy?",
      ["Interdependence of states", "State responsibilities to society", "Power vested in minority parties", "Popular consultation"], D,
      "Democracy is government by consent: the people are consulted through regular free elections, referendums and public debate before power is given or major decisions are made."),
    q("Private ownership of the means of production is central to",
      ["fascism", "feudalism", "capitalism", "communism"], C,
      "Capitalism rests on private ownership of land, factories and capital, with production for profit in a free market."),
    q("A system based on hierarchies of land ownership is",
      ["feudalism", "totalitarianism", "communism", "fascism"], A,
      "Feudalism (medieval Europe) was a hierarchy built on land: the king granted land to lords, lords to vassals, and serfs worked the land in return for protection."),
    q("Which of the following performs quasi-legislative functions?",
      ["The Judiciary", "The Traditional Institutions", "The Civil Service", "The Executive"], D,
      "The executive makes law-like rules without being the legislature: regulations, orders and statutory instruments under delegated powers, and decrees or executive orders, so its law-making is quasi-legislative."),
    q("A major weakness of confederation is",
      ["over-concentration of authority", "tendency towards secession", "lack of local independence", "lack of common currency"], B,
      "In a confederation the member states keep their sovereignty and the centre is weak, so a dissatisfied member can easily pull out; the union is unstable and prone to secession."),
    q("Members of a parliament are required to report the proceedings of the house to their",
      ["constituencies", "local government chairmen", "traditional rulers", "political parties"], A,
      "A legislator represents the people of a constituency, so he or she should keep them informed of what the house is doing and take their views back to it."),
    q("Which of the following countries is a unitary state?",
      ["Nigeria", "India", "United States of America", "Ghana"], D,
      "Ghana has a unitary constitution: all power comes from the central government, and its regions and districts exercise only what the centre gives them. Nigeria, India and the USA are federations."),
    // paper 12–21
    q("Ending a session of parliament by royal proclamation means the",
      ["expiration of parliament", "prorogation of parliament", "adjournment of parliament", "dissolution of parliament"], B,
      "Prorogation is the ending of a session of parliament by royal proclamation; parliament still exists and meets again in a new session. Dissolution ends the life of the parliament itself and leads to a general election."),
    q("A main feature of the parliamentary system is that",
      ["the executive consists of all-party members", "judges are drawn from the ruling party", "electoral commissioners leave at the end of their tenure", "the executive is appointed by the legislature"], D,
      "In a parliamentary system the executive (prime minister and cabinet) comes out of the legislature: the leader of the majority in parliament forms the government, which stays in office only while it keeps parliament's confidence."),
    q("In a socialist economy, private accumulation of wealth is",
      ["prohibited", "regulated", "limited", "encouraged"], A,
      "Socialism puts the means of production under public (state) ownership and aims at equal distribution, so private accumulation of wealth through owning the means of production is not allowed."),
    q("The earliest classification of constitutions was the work of",
      ["Aristotle", "J.J. Rousseau", "K.C. Wheare", "Plato"], A,
      "Aristotle (384–322 BC) studied the constitutions of about 158 Greek city-states and classified them by who rules (one, few, many) and in whose interest, the first systematic classification."),
    q("Constitutionalism refers to",
      ["the process of drafting a constitution", "amendment of an existing constitution", "the process of operating a constitution", "strict adherence to a constitution"], D,
      "Constitutionalism means government limited by and conducted strictly according to the constitution: rulers and citizens alike obey its provisions."),
    q("An advantage of delegated legislation is that",
      ["much time is saved in the process", "technical issues are handled by experts", "ministers and lawmakers work together", "it hastens the implementation of policy"], B,
      "Delegated legislation lets ministries, agencies and councils make detailed rules under an Act, so technical matters are handled by experts who know them; it also saves parliament's time and lets rules be made quickly.",
      { keyVerdict: 'multiple', alsoAccept: [A, D], keyAnswer: 'B',
        answerNote: "Options A and D are also correct. Textbooks list three main advantages of delegated legislation: it saves the legislature's time (A), it lets experts handle technical details (B), and rules can be made quickly so policy is put into effect faster (D). Only C is not an advantage." }),
    q("One essential duty of a citizen to his state is to",
      ["support the government in power", "recite the pledge", "pay his tax", "encourage other citizens"], C,
      "Paying taxes is a basic civic duty, alongside obeying the law, voting and defending the country; tax funds the services the state provides."),
    q("Franchise in an electoral process means the",
      ["right to vote", "ownership of means of production", "sovereignty of a nation", "rights and duties of a citizen"], A,
      "Franchise (suffrage) is the right to vote in elections."),
    q("The type of party system in practice is defined by the",
      ["relationship between the parties and electorate", "structure of the political parties", "manner in which the parties operate", "number of political parties in a country"], D,
      "Party systems are classified by the number of parties that effectively compete for power: one-party, two-party or multi-party."),
    q("Pressure groups harmonize different individual concerns through",
      ["interest formulation", "interest manipulation", "interest mobilisation", "interest aggregation"], D,
      "Interest aggregation is the combining of many separate individual demands into a few common demands that the group can present to government with one voice."),
    // paper 22–31
    q("Opinion polls are organized to find out the",
      ["benefits derived by people from government", "people's thought about a particular government policy", "people's expectations from the government", "feelings of people about particular issues and policies"], D,
      "An opinion poll samples a cross-section of people to measure public opinion: how people feel about current issues, policies, candidates and parties."),
    q("In pre-colonial Igbo-land, autocratic rule was made difficult by the",
      ["fear of dethronement", "absence of a centralized system of authority", "pressure from age grades", "activities of cult societies"], B,
      "Most Igbo communities were acephalous: power was spread among the elders (Ofo holders), the village assembly, age grades and title societies, so no single ruler could become a dictator."),
    q("The Yoruba traditional system of government was",
      ["republican", "democratic", "monarchical", "egalitarian"], C,
      "Pre-colonial Yoruba kingdoms such as Oyo were headed by an Oba (the Alaafin in Oyo), a monarchy whose power was checked by the Oyomesi, the Ogboni and the Are-Ona-Kakanfo: a constitutional monarchy."),
    q("Under the pre-colonial Sokoto Caliphate system, the next in command to the Sultan was the",
      ["Alkali", "Galadima", "Madaki", "Waziri"], D,
      "In the Hausa-Fulani emirate system the Waziri was the chief adviser and head of administration, the most senior official after the Sultan or Emir."),
    q("Which of the following societies was classified as acephalous?",
      ["Benin", "Ibibio", "Igbo", "Ijaw"], C,
      "The Igbo are the classic acephalous (\"headless\") society in Nigeria: they had no centralised kingdom, and authority was spread among village councils of elders, age grades and title holders."),
    q("Indirect rule encouraged",
      ["communal integration", "exploitation and oppression", "inter-communal cooperation", "the rise of nationalism"], B,
      "Indirect rule made traditional rulers (and, in the East, the British-made warrant chiefs) agents of colonial power, backed by British force and answerable to the British rather than their people; many used this to extort and oppress, which led to protests such as the Aba Women's Riot of 1929."),
    q("The main achievement of the nationalists in Nigeria was",
      ["registration of political parties", "economic liberation of the nation", "political liberation of the nation", "building the nation"], C,
      "The nationalist movement's great success was winning political independence from Britain on 1 October 1960."),
    q("The major external factor that promoted nationalism in Nigeria was",
      ["Pan-Africanism", "the Yom-Kippur War", "the Second World War", "Anti-apartheid Movement"], C,
      "The Second World War (1939–45) exposed the myth of white superiority, gave Nigerian ex-servicemen new ideas, and produced the Atlantic Charter's promise of self-determination, all of which sharpened demands for independence."),
    q("The presidential system of government was introduced in Nigeria with the Constitution of",
      ["1989", "1999", "1960", "1979"], D,
      "The 1979 Constitution replaced the Westminster parliamentary system with an American-style executive presidency; Shehu Shagari became the first executive president on 1 October 1979."),
    q("The Action Group crisis of 1963 led to the formation of",
      ["UPP", "NEPU", "NPC", "NCNC"], A,
      "The Action Group split over the quarrel between Obafemi Awolowo and S.L. Akintola, which erupted in May 1962; Akintola's faction formed the United People's Party (UPP), while the NPC and NCNC already existed and NEPU dated from 1950."),
    q("Under the 1963 Republican Constitution, the power of judicial review was vested in the",
      ["President", "Chief Justice", "Supreme Court", "Parliament"], C,
      "The 1963 Constitution made the Supreme Court of Nigeria the final court of appeal (ending appeals to the Privy Council) with power to declare laws and actions unconstitutional, which is judicial review."),
    q("The rules and regulations of the civil service are called",
      ["General Order", "Bureaucratic Order", "Service Order", "Administrative Order"], A,
      "The General Orders are the rulebook of the Nigerian civil service, covering appointment, discipline, promotion, leave and conduct (now issued as the Public Service Rules)."),
    q("The Code of Conduct Bureau was essentially established to",
      ["reduce corruption in public life", "protect the rights of public servants", "enhance probity and accountability in public service", "ensure the independence of the public service"], C,
      "The Code of Conduct Bureau (set up under the 1979 Constitution and kept in the 1999 Constitution) enforces the Code of Conduct for public officers, such as asset declaration, to establish and maintain a high standard of morality, probity and accountability in public life."),
    q("Which of the following political parties was the first to be formed when the ban on politics was lifted in 1978?",
      ["NPP", "PRP", "NPN", "UPN"], D,
      "When the military lifted the ban on party politics on 21 September 1978, Obafemi Awolowo announced the Unity Party of Nigeria (UPN) the very next day, 22 September 1978, before the NPN, NPP, PRP and GNPP were launched.",
      { keyVerdict: 'corrected', keyAnswer: 'C',
        answerNote: "The answer key gives C (NPN), but the UPN was the first party launched: Awolowo announced it on 22 September 1978, a day after the ban was lifted. The NPN grew out of groups formed in the Constituent Assembly, but it was launched as a party only later that month." }),
    q("The principle of federal character was adopted in order to promote equitable allocation of",
      ["positions and appointments among people of various regions", "appointments between the North and the South", "opportunities between the males and females", "revenue between groups in the country"], A,
      "Federal character, written into the 1979 Constitution and kept in 1999, requires that appointments and positions in government and its agencies reflect the diversity of the country, so that no state or ethnic group dominates."),
    // paper 37–46
    q("The component units of the Nigerian Federation comprise",
      ["national assembly, military, police and civil service", "constituency, ward, emirate and chiefdom", "federal, state, local government and federal capital territory", "federal capital territory, national assembly, supreme court and civil service"], C,
      "Nigeria's federation is made up of the federal government, the 36 states, the 774 local government areas and the Federal Capital Territory, Abuja."),
    q("In Nigeria, privatization and commercialization policies were introduced to",
      ["hand over the control of commercial ventures to citizens", "increase the asset base of government", "divest government major control of commercial ventures", "allow government control of the private sector"], C,
      "Privatisation and commercialisation (begun under Babangida's Structural Adjustment Programme, with a 1988 decree) aimed to reduce government's stake in loss-making public enterprises by selling shares to private investors and making the rest run commercially."),
    q("An example of a public corporation in Nigeria is",
      ["National Universities Commission", "Nigerian Television Authority", "National Population Commission", "First Bank of Nigeria"], B,
      "A public corporation is a government-owned body set up by statute to provide a service on business lines; the Nigerian Television Authority (NTA) is one. The NUC is a regulatory agency, the National Population Commission is a constitutional commission, and First Bank is a private company."),
    q("Following the reform of the Native Authority system in Northern Nigeria, traditional rulers became",
      ["Council", "Chief-and-Council", "Prefects", "Chief-in-Council"], B,
      "The reforms of the 1950s ended the emirs' role as sole native authorities and tied them to councils; under the Chief-and-Council arrangement the ruler had to act on the decisions of his council.",
      { keyVerdict: 'multiple', alsoAccept: [D], keyAnswer: 'B',
        answerNote: "Option D is also correct. The Native Authority Law of 1954 replaced the sole native authorities with two forms: Chief-in-Council, where the ruler presided and could overrule his council (the form most large emirates took), and Chief-and-Council, where he had to follow the council's majority. Both came out of the reform, so B and D are accepted." }),
    q("Under whose regime were Akwa-Ibom and Katsina States created?",
      ["Gen Murtala Muhammed", "Gen Ibrahim Babangida", "Gen Sani Abacha", "Gen Yakubu Gowon"], B,
      "Babangida created Akwa Ibom and Katsina on 23 September 1987, raising the number of states from 19 to 21."),
    q("Under the 1999 Constitution of the Federal Republic of Nigeria, the appointment and posting of members of election tribunals on the elections conducted by INEC is the responsibility of the",
      ["Chairman, Independent National Electoral Commission", "President of Nigeria", "Chief Justice of Nigeria", "President, Court of Appeal"], D,
      "The Sixth Schedule of the 1999 Constitution says the chairmen and members of election petition tribunals are appointed by the President of the Court of Appeal (in consultation with the Chief Judge of the state for state tribunals)."),
    q("Rhodesia was the former name of",
      ["Zimbabwe", "Swaziland", "Zambia", "Namibia"], A,
      "Southern Rhodesia, known simply as Rhodesia after the white-minority UDI of 1965, became independent as Zimbabwe on 18 April 1980; Zambia was Northern Rhodesia."),
    q("The adoption of non-alignment as a principle of Nigeria's foreign policy was aimed at",
      ["promoting Nigeria's leadership aspiration in Africa", "attaining equal status with the world powers", "fulfilling a basic requirement for acceptance in the UN Security Council", "insulating Nigeria against having to take sides in the Cold War"], D,
      "Non-alignment meant Nigeria would not join either the Western (US-led) or Eastern (Soviet-led) bloc, so it kept out of the Cold War and judged each issue on its merits."),
    q("In 1979, the non-aligned member states were",
      ["21", "117", "37", "19"], B,
      "The Non-Aligned Movement was founded in Belgrade in 1961 by 25 states and grew steadily; by its 1979 Havana summit it had just over 90 members, and today it has about 120.",
      { keyVerdict: 'none', keyAnswer: 'B',
        answerNote: "None of the options is exactly right. At the Havana summit in September 1979 the Non-Aligned Movement had just over 90 member states, not 117; 117 is close to its size in the 2000s (it now has about 120). B is marked because it is the expected answer and the only figure near the Movement's real size; 21, 37 and 19 are far too small." }),
    q("Which of the following was the secretary-general of OPEC?",
      ["Jibril Aminu", "Aret Adams", "Dalhatu Bayero", "Rilwan Lukman"], D,
      "Rilwanu Lukman, Nigeria's former petroleum minister, was Secretary General of OPEC from 1995 to 2000 (he had earlier been President of the OPEC Conference)."),
    // paper 47–50
    q("Which of the following countries pioneered the idea of ECOWAS alongside Nigeria?",
      ["Liberia", "Togo", "Cote d'Ivoire", "Mali"], B,
      "General Yakubu Gowon of Nigeria and General Gnassingbé Eyadéma of Togo launched the idea of a West African economic community in 1972; ECOWAS was founded by the Treaty of Lagos on 28 May 1975."),
    q("Which of the following international organizations were in existence before the Second World War?",
      ["The UNO", "The OAU", "The League of Nations", "The ECOWAS"], C,
      "The League of Nations was set up in 1920 after the First World War; the UN dates from 1945, the OAU from 1963 and ECOWAS from 1975."),
    q("The organ of the United Nations responsible for the approval of its annual budget is the",
      ["Secretariat", "Security Council", "General Assembly", "Economic and Social Council"], C,
      "Under Article 17 of the UN Charter the General Assembly, in which every member state has a seat, considers and approves the UN budget and shares the costs among members."),
    q("Each member state is represented on the Board of Governors of OPEC for a period of",
      ["2 years", "3 years", "4 years", "1 year"], A,
      "Each OPEC member nominates one Governor to the Board of Governors, who holds office for a term of two years under the OPEC Statute.")
  ]);
})();
