/**
 * JAMB/UTME 2006 — GOVERNMENT
 * From the 2006 question paper (all 50 questions); answers from the JAMB/UTME Government answer key
 * 2001–2020, each checked independently. Printing errors carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2006;
  const SRC = 'JAMB UTME 2006';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  QUESTION_BANK.government = QUESTION_BANK.government.concat([
    // paper 1–10
    q("Galadima in the emirate system refers to",
      ["a village head", "the officer in charge of the army", "the administrator of the capital city", "a judge"], C,
      "In the Hausa-Fulani emirate the Galadima was the official who administered the capital city; the army was under the Madawaki and justice under the Alkali."),
    q("After the defeat of Germany in World War I, her former colonies were administered under the League of Nations as",
      ["occupied territories", "protectorates", "crown colonies", "mandated territories"], D,
      "The League of Nations placed Germany's former colonies (such as the Cameroons, Togoland and Tanganyika) under the mandate system, with Britain, France and others administering them as mandated territories."),
    q("Under the 1963 Republican Constitution, the president exercised",
      ["judicial powers", "nominal powers", "concurrent powers", "executive powers"], B,
      "The 1963 Constitution kept the parliamentary system: the President (Dr Nnamdi Azikiwe) was a ceremonial head of state, while real executive power lay with the Prime Minister and cabinet."),
    q("A major feature of the policy of deregulation in Nigeria is the",
      ["proliferation of public corporations", "phenomenal increase in direct foreign investment", "enthronement of market forces mechanism", "increasing dominance of the economy by the state"], C,
      "Deregulation removes government controls on prices, exchange rates and entry into business, so that supply and demand (market forces) decide them."),
    q("At its inception in 1919, the National Congress of British West Africa was led by",
      ["Marcus Garvey", "Nnamdi Azikiwe", "Casely Hayford", "William Du Bois"], C,
      "J. E. Casely Hayford, a Gold Coast lawyer, founded and led the National Congress of British West Africa, whose first conference met in Accra in 1920."),
    q("The main reason for the poor performance of the Public Complaints Commission in Nigeria is that",
      ["its activities are interfered with", "it lacks adequate funds to play its roles", "people have not been lodging complaints", "it lacks the powers to prosecute offenders"], D,
      "The Public Complaints Commission (Nigeria's ombudsman, set up in 1975) can only investigate and recommend; it cannot prosecute or enforce its findings, so many of its recommendations are ignored."),
    q("The signing of protectorate treaty was used by the Europeans to penetrate",
      ["the Niger Delta", "Eastern Nigeria", "Northern Nigeria", "Western Nigeria"], C,
      "The Royal Niger Company signed hundreds of treaties of protection with northern rulers (including Sokoto and Gwandu in 1885) to claim the North; in the Niger Delta, Consul Hewett's 1884 treaties likewise created the Oil Rivers Protectorate.",
      { keyVerdict: 'multiple', alsoAccept: [A], keyAnswer: 'C',
        answerNote: "Option A is also correct. Treaties of protection were used in both regions: the Royal Niger Company's treaties with northern emirs, and Consul Edward Hewett's 1884 treaties with the Niger Delta chiefs, which led to the Oil Rivers Protectorate in 1885." }),
    q("The chairman of the National Defence Council as provided in the 1999 Constitution is the",
      ["Chief of Army Staff", "Chief of Defence Staff", "President", "Minister of Defence"], C,
      "The 1999 Constitution (section 153 and the Third Schedule) makes the President, as Commander-in-Chief, the chairman of the National Defence Council."),
    q("Constitutional matters in which the Nigerian federal and state governments exercise joint authority are on the",
      ["concurrent list", "reserved list", "residual list", "exclusive list"], A,
      "The concurrent list contains matters on which both the federal and state governments can make laws; where they conflict, the federal law prevails."),
    q("Under colonial administration, what was the status of the inhabitants of the Lagos Crown Colony?",
      ["British servants", "British citizens", "British settlers", "British subjects"], D,
      "Lagos was annexed in 1861 and became a crown colony, British territory, so its people were British subjects; people of the protectorates were only British protected persons."),
    // paper 11–20
    q("In 1999, the Alliance for Democracy won the governorship election in",
      ["four states", "five states", "seven states", "six states"], D,
      "In 1999 the AD won all six South-West states: Lagos, Ogun, Oyo, Osun, Ondo and Ekiti. The AD no longer exists: most of it went into the Action Congress (2006), which joined the APC in 2013."),
    q("The 1960 Independence Constitution of Nigeria provided for the",
      ["Queen as head of state", "Governor-General as head of state", "Governor-General as head of government", "President as head of government"], A,
      "At independence the British Queen remained Nigeria's head of state, represented by the Governor-General (Dr Nnamdi Azikiwe), while the Prime Minister headed the government."),
    q("During colonial administration, the office of the warrant chief was introduced in",
      ["Western Nigeria", "Northern Nigeria", "the Lagos Territory", "Eastern Nigeria"], D,
      "The Igbo and their neighbours had no kings to rule through, so the British created warrant chiefs in Eastern Nigeria, men given a warrant to sit in the native courts."),
    q("In the pre-colonial Yoruba political system, the council of chiefs constituted the",
      ["ombudsman", "executive", "judicial arm", "legislative arm"], D,
      "In Oyo the Oyo Mesi, the council of seven chiefs led by the Bashorun, made laws with the Alaafin and could ask him to commit suicide, so it acted as the legislature."),
    q("A major merit of privatization is that it increases",
      ["industrial harmony", "activities on the stock exchange", "public fiscal resources", "labour turnover"], B,
      "Privatization sells government shares in public enterprises to private investors, often through the stock exchange, so it widens share ownership and stock-market activity."),
    q("The highest decision-making body under the Gowon Regime was the",
      ["Provisional Ruling Council", "Supreme Military Council", "Armed Forces Ruling Council", "Federal Executive Council"], B,
      "Gowon (1966–1975) ruled through the Supreme Military Council; the AFRC belonged to Babangida and the PRC to Abacha and Abubakar."),
    q("In pre-colonial governance, women played prominent roles in the",
      ["Tiv society", "Igbo society", "Yoruba Kingdom", "Jukun Kingdom"], B,
      "In Igbo society the umuada (daughters of the lineage) and women's associations settled disputes, enforced rules and could sanction men, and in some Igbo towns the Omu ruled over women's affairs.",
      { keyVerdict: 'multiple', alsoAccept: [C], keyAnswer: 'B',
        answerNote: "Option C is also correct. Yoruba women held important titles: the Iyalode represented women in the council of chiefs, and palace officials such as the Iya Oba and Iyakere had real power in Oyo." }),
    q("Before the 1976 reforms, the three-tier local government system was practised by",
      ["Mid-Western and Eastern Nigeria", "Western and Northern Nigeria", "Eastern and Western Nigeria", "Northern and Eastern Nigeria"], C,
      "The English-style three-tier council system was introduced in the East (1950 Ordinance: county, district and local councils) and the West (1952 Law: divisional, district and local councils); the North kept its Native Authorities.",
      { keyVerdict: 'corrected', keyAnswer: 'B',
        answerNote: "The answer key gives B (Western and Northern Nigeria). The three-tier councils copied from England were set up in the Eastern Region (1950) and the Western Region (1952), while the North kept the emir-based Native Authority system until 1976, so C fits the facts better." }),
    q("In Nigeria, military regimes returned power to civilians through",
      ["negotiations", "impositions", "transition programmes", "constitutional conferences"], C,
      "Each hand-over (Obasanjo in 1979, Abubakar in 1999, and Babangida's unfinished programme) followed a timetabled transition programme of constitution-making, party registration and elections."),
    q("The ECOWAS Tribunal is responsible for",
      ["interpreting ECOWAS treaties", "ratifying international treaties for member states", "trying erring member states of ECOWAS", "ensuring compliance with global treaties"], A,
      "The ECOWAS Tribunal, now the ECOWAS Community Court of Justice (Abuja), interprets and applies the ECOWAS Treaty and protocols; since 2005 it also hears human-rights cases."),
    // paper 21–30
    q("Judges of the World Court are appointed to serve for",
      ["nine years", "four years", "ten years", "five years"], A,
      "The 15 judges of the International Court of Justice are elected by the UN General Assembly and Security Council for nine-year terms, with a third elected every three years."),
    q("The highest decision-making organ of OPEC is the",
      ["Special Fund", "Board of Governors", "Secretariat", "Conference"], D,
      "The OPEC Conference, made up of the oil ministers of member states, is the supreme authority; the Board of Governors and the Secretariat (Vienna) carry out its decisions."),
    q("The transformation of the OAU to AU is essentially to",
      ["enhance Africa's economic development", "accelerate Africa's political development", "accelerate Africa's technological development", "promote Africa's socio-culture advancement"], A,
      "The African Union (launched in 2002) was meant to speed up Africa's economic integration and development, building on the 1991 Abuja Treaty for an African Economic Community."),
    q("Diplomatic missions among the Commonwealth member states are referred to as",
      ["high commission", "legations", "embassies", "consulates"], A,
      "Commonwealth countries exchange high commissions headed by high commissioners, not embassies headed by ambassadors."),
    q("The chairman of the UN Security Council emerges through",
      ["rotation", "consensus", "election", "selection"], A,
      "The presidency of the Security Council rotates monthly among its 15 members in English alphabetical order."),
    q("A written constitution is distinguished by its",
      ["dependence on ordinary amendment procedures", "cumbersome and complex amendment procedure", "codification process", "reliance on case laws"], C,
      "A written constitution is one that is codified, collected in one formal document; how hard it is to amend is a separate question of rigidity.",
      { keyVerdict: 'corrected', keyAnswer: 'B',
        answerNote: "The answer key gives B (cumbersome amendment procedure). That describes a rigid constitution. Most written constitutions are rigid, but not all are, so what sets a written constitution apart is that it is codified in one document: C." }),
    q("One of the most essential characteristics of the state is",
      ["sovereignty", "the rule of law", "legitimacy", "the civil service"], A,
      "The state has four essential features: population, territory, government and sovereignty; without sovereignty a territory is not a state."),
    q("Fascism originated from",
      ["Italy", "Greece", "Germany", "China"], A,
      "Fascism began in Italy, where Benito Mussolini founded the movement in 1919 and took power in 1922; German Nazism came later."),
    q("The principle of separation of powers is intimately related to",
      ["checks and balances", "the bureaucratic process", "democratic rule", "the rule of law"], A,
      "Separating powers among legislature, executive and judiciary works with checks and balances, by which each organ limits the others."),
    q("Vote of confidence is basically a feature of",
      ["a coalition government", "the parliamentary system", "an aristocratic government", "the presidential system"], B,
      "In a parliamentary system the cabinet stays in office only while it keeps the confidence of parliament, tested by votes of confidence or no confidence."),
    // paper 31–40
    q("One of the greatest advocates of socialism was",
      ["Baron de Montesquieu", "Karl Marx", "A.V. Dicey", "Adam Smith"], B,
      "Karl Marx (with Friedrich Engels) wrote the Communist Manifesto (1848) and Das Kapital, the founding texts of scientific socialism."),
    q("Public opinion helps a government to",
      ["develop the country in line with the people's aspirations", "monitor its socio-cultural policy", "monitor the economic situation in the country", "identify those that are opposed to its policies"], A,
      "Public opinion tells a government what the people want and how they judge its policies, so it can govern in line with their aspirations."),
    q("The type of government in which an individual wields absolute power is called",
      ["theocracy", "autocracy", "oligarchy", "plutocracy"], B,
      "Autocracy is rule by one person with unlimited power."),
    q("A distinctive feature of the presidential system of government is the",
      ["existence of two political parties", "fusion of legislative and executive powers", "existence of a ceremonial head of state", "fusion of ceremonial and executive powers"], D,
      "In a presidential system one person, the president, is both ceremonial head of state and executive head of government."),
    q("Individual as opposed to collective responsibility is a basic feature of the",
      ["presidential system of government", "socialist system of government", "monarchical system of government", "parliamentary system of government"], A,
      "In a presidential system ministers are answerable individually to the president who appointed them; collective cabinet responsibility belongs to the parliamentary system."),
    q("A right enjoyed by citizens but denied non-citizens is the right to",
      ["equality before the law", "vote and be voted for", "life, liberty and security", "freedom of worship"], B,
      "Political rights, voting and standing for election, belong only to citizens; civil rights such as life, liberty and freedom of worship protect everyone in the country."),
    q("In a federal system, the essence of specifying the constitutional relationship between the centre and the constituent units is to",
      ["ensure the superiority of the centre", "diffuse political power", "guarantee political autonomy", "avoid functional conflicts"], D,
      "By listing in the constitution which functions belong to the centre and which to the units, a federation prevents the two levels from clashing over the same functions.",
      { keyVerdict: 'multiple', alsoAccept: [C], keyAnswer: 'D',
        answerNote: "Option C is also correct. The written division of powers also guarantees each level of government its autonomy within its own sphere, which is K. C. Wheare's definition of federalism." }),
    q("In a dominant one-party system, there is",
      ["one party that controls the political parties", "only one political party recognized by law", "one among many parties that always wins elections", "one party which embraces all the citizens"], C,
      "In a dominant-party system several parties exist and compete legally, but one party keeps winning, as the ANC has done in South Africa."),
    q("One of the ways the executive performs legislative functions is through",
      ["administrative review", "extrajudicial decision", "judicial review", "delegated legislation"], D,
      "Delegated legislation is law made by the executive (ministers, agencies, councils) under powers given by an act of the legislature, e.g. regulations and bye-laws."),
    q("The form of government in which the powers of the hereditary ruler are limited is",
      ["constitutional monarchy", "aristocracy", "absolute monarchy", "totalitarianism"], A,
      "In a constitutional monarchy, as in Britain, the hereditary monarch reigns but rules within limits set by the constitution and parliament."),
    // paper 41–50
    q("As a component of the state, the civil service is important because it ensures",
      ["gender equality", "effective cost-benefit analysis", "continuity in governance", "equality among professions"], C,
      "Civil servants are permanent and politically neutral, so they keep the government running as politicians and regimes come and go."),
    q("A bill could become law without the president's assent if",
      ["overruled by the Supreme Court", "supported by a two-thirds majority of the legislature", "necessitated by a state of emergency", "assented to by the Chief Justice"], B,
      "If the president withholds assent, the National Assembly can pass the bill again by a two-thirds majority in each house and it becomes law without assent (section 58(5), 1999 Constitution)."),
    q("A crucial requirement for the successful conduct of elections is",
      ["the existence of organized political parties", "an independent electoral commission", "a highly mobilized electorate", "the adequate funding of political parties"], B,
      "Free and fair elections depend above all on an electoral body that is independent of the government and the parties, and so can conduct the vote impartially."),
    q("One major determinant of Nigeria's foreign policy is",
      ["commitment to world peace", "cooperation among African states", "non-alignment in world affairs", "external influences"], D,
      "Determinants are the factors that shape a foreign policy, such as history, economy, size, leadership and pressures from outside powers and the world system (external influences).",
      { keyVerdict: 'corrected', keyAnswer: 'B',
        answerNote: "The answer key gives B (cooperation among African states). Cooperation among African states, world peace and non-alignment are principles or objectives of Nigeria's foreign policy, things the policy aims at. A determinant is a factor that shapes the policy, and of these options only external influences is one." }),
    q("The Technical Aid Corps programme was initiated by Nigeria to contribute to the socio-economic development of",
      ["developing countries", "West Africa", "The Third World", "Africa"], D,
      "The Technical Aid Corps, set up in 1987 under Babangida on the idea of Foreign Minister Bolaji Akinyemi, sends Nigerian professionals to serve in African, Caribbean and Pacific countries, with Africa as its main focus.",
      { keyVerdict: 'multiple', alsoAccept: [A, C], keyAnswer: 'D',
        answerNote: "Options A and C are also correct. The scheme serves African, Caribbean and Pacific (ACP) countries, all of them developing or Third World countries, so 'developing countries' and 'the Third World' describe it as well as 'Africa', its main focus." }),
    q("Nigeria became a frontline state in the Southern African liberation struggle because of her",
      ["influence on African proxy wars", "commitment to end colonialism", "anti-apartheid stance", "connection with South Africa"], C,
      "Although far from Southern Africa, Nigeria was treated as a frontline state because of its strong stand against apartheid: funds, scholarships and diplomatic campaigns against white-minority rule.",
      { keyVerdict: 'multiple', alsoAccept: [B], keyAnswer: 'C',
        answerNote: "Option B is also correct. The struggle included ending colonial and settler rule in Angola, Mozambique, Zimbabwe and Namibia, and Nigeria's support for those liberation movements was part of what earned it the frontline title." }),
    q("The New Partnership for Africa's Development was mainly promoted by",
      ["Ghana, Sierra Leone and Nigeria", "Kenya, South Africa and Senegal", "Nigeria, Senegal and South Africa", "Tanzania, Burkina Faso and Egypt"], C,
      "NEPAD (2001) was driven by Obasanjo of Nigeria, Mbeki of South Africa and Wade of Senegal, with Algeria and Egypt; in 2018 it became the AU Development Agency (AUDA-NEPAD)."),
    q("Nigeria's first participation in a United Nations peace-keeping operation was in",
      ["Congo", "Lebanon", "Angola", "Chad"], A,
      "Weeks after independence, in November 1960, Nigerian troops joined the UN operation in the Congo (ONUC)."),
    q("Nigeria's concern for decolonization in Africa was responsible for her abandonment of pro-West policy during the",
      ["Shonekan administration", "Shagari administration", "Aguiyi-Ironsi regime", "Murtala regime"], D,
      "The Murtala Mohammed regime (1975–76) defied the USA and recognised the MPLA government of Angola in November 1975, marking a bold, independent foreign policy."),
    q("The first Nigerian leader to become chairman of the Organisation of African Unity was",
      ["Murtala Muhammed", "Yakubu Gowon", "Johnson Aguiyi-Ironsi", "Tafawa Balewa"], B,
      "General Yakubu Gowon was OAU chairman in 1973–74. The OAU was replaced by the African Union in 2002."),
  ]);
})();
