/**
 * JAMB/UTME 2008 — GOVERNMENT
 * From the 2008 question paper (all 50 questions); answers from the JAMB/UTME Government answer key
 * 2001–2020, each checked independently. Printing errors carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2008;
  const SRC = 'JAMB UTME 2008';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  QUESTION_BANK.government = QUESTION_BANK.government.concat([
    // paper 1–10
    q("A member of the Commonwealth that was not colonized by Britain is",
      ["Malaysia", "Uganda", "Mozambique", "Jamaica"], C,
      "Mozambique was a Portuguese colony; in 1995 it became the first Commonwealth member never ruled by Britain. Today Rwanda (2009), Gabon and Togo (2022) have also joined without a British colonial past."),
    q("The Organization of Petroleum Exporting Countries came into existence at a conference held in",
      ["Tripoli", "Caracas", "Riyadh", "Baghdad"], D,
      "OPEC was founded at the Baghdad Conference of 10–14 September 1960 by Iran, Iraq, Kuwait, Saudi Arabia and Venezuela; Nigeria joined in 1971."),
    q("ECOWAS main achievement in recent years has been in the area of",
      ["infrastructural development", "cultural integration", "security and defence", "political unity"], C,
      "Through its ceasefire monitoring group, ECOMOG, ECOWAS restored order in Liberia (from 1990), Sierra Leone and Guinea-Bissau: its most visible recent achievement."),
    q("In which of the following countries has the UN carried out peacekeeping operations?",
      ["Cyprus, Singapore and South Africa", "Lebanon, the Congo and Mexico", "Cyprus, Somalia and Yugoslavia", "Nigeria, Botswana and the Congo"], C,
      "The UN has kept peace in Cyprus (UNFICYP, since 1964), Somalia (UNOSOM, 1992–1995) and the former Yugoslavia (UNPROFOR, 1992–1995); each other option names at least one country with no UN peacekeeping mission."),
    q("Which of the following was the main organ of the defunct OAU?",
      ["The Liberation Committee", "The Council of Ministers", "The Commission for Mediation, Conciliation and Arbitration", "The Assembly of Heads of State and Government"], D,
      "The Assembly of Heads of State and Government was the OAU's supreme organ, meeting yearly to decide policy. The OAU (1963) was replaced by the African Union in 2002, whose Assembly is still its supreme organ."),
    q("A key characteristic of the civil service is",
      ["transparency", "patriotism", "merit system", "quota system"], C,
      "Civil servants are recruited and promoted on merit (examinations, qualifications), alongside the features of permanence, neutrality and anonymity."),
    q("Democracy is a perverted form of which of the following?",
      ["Feudalism", "Republicanism", "Monarchy", "Oligarchy"], B,
      "In Aristotle's classification, rule by the many for the common good is 'polity' (often translated 'republic'); its perverted form, rule by the many for themselves, he called democracy."),
    q("An example of a state with an unwritten constitution is",
      ["Canada", "India", "Britain", "France"], C,
      "Britain's constitution is not gathered in one document: it rests on statutes, case law, conventions and works of authority."),
    q("A characteristic of a fascist state is the existence of a",
      ["zero-party system", "two-party system", "one-party system", "multi-party system"], C,
      "Fascist states (Mussolini's Italy, Hitler's Germany) allowed only the ruling party and banned all opposition."),
    q("The right that enables citizens to express their electoral preferences is",
      ["franchise", "suffrage", "coat-tails", "referendum"], A,
      "Franchise is the right to vote, by which citizens express their choice in elections.",
      { keyVerdict: 'multiple', alsoAccept: [B], keyAnswer: 'A',
        answerNote: "Option B is also correct: 'suffrage' means exactly the same thing as 'franchise' (the right to vote), as in 'universal adult suffrage'. Either is accepted." }),
    // paper 11–20
    q("Membership of a society is",
      ["reserved", "voluntary", "mandatory", "honorary"], B,
      "A society or association (a club, union, church) is joined by choice; membership of the state, by contrast, is compulsory."),
    q("Equality before the law is a component of",
      ["separation of powers", "checks and balances", "the rule of law", "constitutional law"], C,
      "A.V. Dicey's rule of law has three parts: supremacy of the law, equality before the law, and protection of rights by the ordinary courts."),
    q("An example of promotional pressure group is the",
      ["Supreme Council for Islamic Affairs", "Nigerian Medical Association", "Civil Liberties Organization", "Manufacturers Association of Nigeria"], C,
      "A promotional (cause) group campaigns for a cause that benefits society at large, not its own members' interests; the Civil Liberties Organisation (1987) campaigns for human rights."),
    q("An example of a country that operates a bicameral legislature is",
      ["Nigeria", "Sierra Leone", "Kenya", "Libya"], A,
      "Nigeria's National Assembly has two chambers, the Senate and the House of Representatives. In 2008 the other three had one chamber; Kenya has since become bicameral, adding a Senate under its 2010 constitution (first elected 2013)."),
    q("An institution that transforms a myriad of demands into a more manageable proposal is the",
      ["executive", "legislature", "government", "political party"], D,
      "This is interest aggregation: political parties gather the many demands of different groups and combine them into a few manageable programmes and policy proposals.",
      { keyVerdict: 'corrected', keyAnswer: 'C',
        answerNote: "Government turns demands into binding decisions and policies, but the function described here, combining many scattered demands into a few manageable proposals, is interest aggregation, which political science textbooks assign to political parties. So D is the better answer." }),
    q("Government exercises political power on behalf of the",
      ["elite", "citizens", "party caucus", "vocal few"], B,
      "Government holds power in trust for the people: it governs on behalf of the citizens, from whom (in a democracy) its authority comes."),
    q("A major characteristic of a confederal state is that",
      ["there is supremacy of the constitution", "the citizens often owe allegiance to the centre", "political stability is usually low", "the centre overrides the regions"], C,
      "In a confederation the member states keep their sovereignty and the centre is weak, so members can withdraw or ignore it, making the union unstable."),
    q("The citizenship of a country can be acquired by an alien through",
      ["habitation", "assimilation", "association", "naturalization"], D,
      "An alien (foreigner) becomes a citizen by naturalisation: applying after years of lawful residence and meeting conditions such as good character."),
    q("An advantage of delegated legislation is",
      ["supremacy", "convenience", "effectiveness", "efficiency"], D,
      "Delegated legislation makes law-making more efficient: parliament passes the broad law and leaves detailed rules to ministers and agencies with expert knowledge, saving its time."),
    q("A system of government that promotes the rights and freedom of the citizens is called",
      ["oligarchy", "plutocracy", "autocracy", "democracy"], D,
      "Democracy is government by the people, and it protects citizens' rights and freedoms such as speech, association and the vote."),
    // paper 21–30
    q("In the presidential system of government, the leader is basically the head of the state and",
      ["government", "the police", "the military", "the judiciary"], A,
      "A president is both head of state (ceremonial) and head of government (chief executive), unlike the parliamentary system, which separates the two."),
    q("An economic system that encourages even distribution of wealth in the society is",
      ["liberalism", "socialism", "mercantilism", "capitalism"], B,
      "Socialism places the main means of production under public ownership so that wealth is shared fairly among all."),
    q("An attribute that makes a state to be recognized as independent is",
      ["government", "population", "sovereignty", "territory"], C,
      "Sovereignty, supreme authority at home and freedom from outside control, is what marks a state as independent."),
    q("The act of denying an eligible person the right to vote in an election is",
      ["gerrymandering", "disenfranchisement", "filibustering", "restricted franchise"], B,
      "Disenfranchisement means taking away or denying a qualified person's right to vote."),
    q("In the monarchical system of government, sovereignty is vested in the",
      ["people", "royalty", "legislature", "military"], B,
      "In a monarchy supreme authority belongs to the royal ruler (king or queen), who inherits the throne."),
    q("One merit of a written constitution is its",
      ["legibility", "total flexibility", "rigidity", "ease of reference"], D,
      "Because a written constitution is set out in one document, citizens, courts and officials can easily consult it."),
    q("A human community that is usually cohesive and homogeneous is a",
      ["state", "kinship", "nation", "clan"], C,
      "A nation is a group of people bound together by common descent, language, culture and history, which makes it cohesive and homogeneous."),
    q("In the process of implementing laws, the executive sometimes performs",
      ["judicial function", "bureaucratic function", "oversight function", "legislative function"], A,
      "The executive sometimes acts judicially, for example through administrative tribunals and the prerogative of mercy.",
      { keyVerdict: 'multiple', alsoAccept: [D], keyAnswer: 'A',
        answerNote: "Option D is also correct: while implementing laws the executive also makes rules and regulations under delegated legislation (and, under military rule, decrees), which is a legislative function. Both A and D are accepted." }),
    q("Which of the following justifies the Afro-centric foreign policy of Nigeria?",
      ["Her location in the West African sub-region", "Her colonization by a foreign power", "Her physical size, population and resource endowments", "Her ability to contribute to peace keeping missions"], C,
      "Nigeria's large size, population (the largest in Africa) and oil wealth give her the weight and the duty to lead Africa, which justifies making Africa the centrepiece of her foreign policy."),
    q("A virile foreign policy is one characterized by",
      ["a vibrant press, vibrant public opinion and a dynamic civil society", "propaganda, espionage and economic embargoes", "a stable polity, buoyant economy and visionary leadership", "the nature and dynamics of the international system"], C,
      "A strong (virile) foreign policy rests on strength at home: political stability, a buoyant economy and visionary leadership."),
    // paper 31–40
    q("Nigeria hosted the Commonwealth conference which eventually led to the independence of",
      ["Mozambique", "Malawi", "Namibia", "Zimbabwe"], D,
      "In January 1966 Lagos hosted a special Commonwealth Prime Ministers' conference on Rhodesia's illegal declaration of independence; the struggle it began ended with Zimbabwe's independence in 1980."),
    q("Multilateralism in Nigeria's foreign policy entails her",
      ["stand on Africa as the centrepiece of her policy", "non-aligned posture in the international system", "quest for a permanent seat in the UN security council", "membership of international organizations"], D,
      "Multilateralism means pursuing foreign policy through many-member international organisations: Nigeria belongs to the UN, AU, ECOWAS, the Commonwealth and OPEC."),
    q("The first military coup in Nigeria toppled the government of",
      ["General Yakubu Gowon", "Dr. Nnamdi Azikiwe", "Alhaji Abubakar Tafawa Balewa", "Major General Aguiyi-Ironsi"], C,
      "The coup of 15 January 1966 overthrew the First Republic government of Prime Minister Sir Abubakar Tafawa Balewa, who was killed."),
    q("Adjudication of conflict between the federal and regional governments in the first Republic was reserved for",
      ["National industrial court", "Supreme Court", "Federal Court of Appeal", "Federal High court"], B,
      "The Supreme Court had original jurisdiction over disputes between the federal government and a region, or between regions."),
    q("The officer in charge of the administration of the palace in the Yoruba political structure is the",
      ["ba'ale", "oluwo", "ilari", "iwefa"], D,
      "In Old Oyo the palace was run by the iwefa (eunuchs), led by the Ona Efa, Otun Efa and Osi Efa, who handled justice, religion and palace affairs for the Alaafin."),
    q("Prior to 1966, the system of local government in western region was based on the three-tier structure of",
      ["native authority, division and district councils", "district, local and area councils", "division, district and local councils", "province, district and local council"], C,
      "The Western Region Local Government Law of 1952 set up a three-tier system of divisional, district and local councils."),
    q("A major shortcoming of the Lyttelton Constitution was that",
      ["it did not provide for a second chamber at the federal level", "the Governor-General continued to head the government", "no provision was made for the office of the prime minister", "it failed to provide for the office of a premier"], C,
      "The 1954 Lyttelton Constitution created regional premiers but no federal prime minister; that office came only in 1957, filled by Tafawa Balewa."),
    q("The option A-4 voting system was introduced into the political process in Nigeria during the",
      ["Third Republic", "fourth Republic", "First Republic", "Second Republic"], A,
      "Option A4, in which voters queued openly behind their candidate's picture, was used in the elections of Babangida's Third Republic transition (1990–1993)."),
    q("In orientation, early nationalism in Nigeria was essentially",
      ["revolutionary", "reformist", "reactionary", "radical"], B,
      "Early nationalists such as Herbert Macaulay's NNDP (1923) asked for reforms within colonial rule (more representation, better jobs and services), not for immediate independence."),
    q("Which of the following in the Sokoto Caliphate performed functions similar to that of the Bashorun in Oyo Kingdom?",
      ["Waziri", "Galadima", "Ma'aji", "Alkali"], A,
      "The Bashorun led the Oyo Mesi and acted like a prime minister; in the Sokoto Caliphate the Waziri was the chief adviser and head of administration."),
    // paper 41–50
    q("Problems arising from population census in Nigeria are mainly caused by",
      ["public opinions of the people", "unreliable census figures", "political manipulation by the elite", "the registration of the under-aged people"], B,
      "Because population decides seats and revenue, census figures have often been inflated and disputed; unreliable figures have made censuses (1962, 1963, 1973, 1991, 2006) controversial."),
    q("Which of the following formalized colonial penetration into Africa?",
      ["Paris Treaty", "Treaty of Westphalia", "Berlin Conference", "Treaty of Versailles"], C,
      "The Berlin Conference of 1884–85 laid down the rules for European powers to claim African territory, formalising the scramble for Africa."),
    q("The 1989 Nigerian Constitution provided for a",
      ["multi-party system", "zero-party system", "two-party system", "one-party system"], C,
      "The 1989 Constitution allowed only two parties; the Babangida government created them, the SDP and the NRC."),
    q("The Nigerian federalism is a",
      ["four-tier system", "three-tier system", "two-tier system", "one-tier system"], B,
      "Nigeria has three tiers of government: federal, state and local government."),
    q("The arm of government mainly responsible for the implementation of law in Nigeria is the",
      ["judiciary", "police", "legislature", "executive"], D,
      "The executive carries out (implements) laws; the legislature makes them and the judiciary interprets them."),
    q("The British colonial rule in Nigeria brought about",
      ["a stagnation in social formations", "the pampering of traditional rulers", "a change in the mode of production", "stabilization in the price of raw materials"], C,
      "Colonial rule brought a money economy, cash crops for export, wage labour and private property, changing the mode of production from subsistence towards capitalism.",
      { keyVerdict: 'corrected', keyAnswer: 'A',
        answerNote: "Some writers argue that colonialism held back Africa's development, but Nigeria's social formations did not stand still: colonial rule created new classes of wage workers, traders and an educated elite, and turned the economy towards cash crops and money. A change in the mode of production is the standard description, so C is the better answer." }),
    q("A primary objective of the privatization policy in Nigeria is",
      ["probity", "responsiveness", "transparency", "accountability"], D,
      "Privatisation transfers loss-making public enterprises to private owners, who answer to shareholders, making management more accountable and efficient."),
    q("Which of the following is saddled with the conduct of general elections in Nigeria's Fourth Republic?",
      ["National Electoral Commission of Nigeria", "Independent National Electoral Commission", "National Electoral Commission", "Federal Electoral Commission"], B,
      "INEC, set up in 1998, has conducted every general election of the Fourth Republic from 1999."),
    q("Public corporations are established to",
      ["reduce government spending", "boost government revenue", "improve provision of social amenities", "create vacancies for political appointments"], C,
      "Public corporations such as power, water and rail corporations are set up mainly to provide essential services and amenities to the public at affordable cost."),
    q("The political structure of Nigeria under the first military regime was",
      ["confederal", "quasi-federal", "federal", "unitary"], D,
      "Ironsi's Unification Decree No. 34 of May 1966 abolished the regions and made Nigeria a unitary state.")
  ]);
})();
