/**
 * JAMB/UTME 2014 — GOVERNMENT
 * From the 2014 question paper (questions 2–50; Q1 only asked for the paper type); answers from the
 * JAMB/UTME Government answer key 2001–2020, each checked independently. Answer checks carry
 * keyVerdict/answerNote.
 */
(function () {
  const Y = 2014;
  const SRC = 'JAMB UTME 2014';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  QUESTION_BANK.government = QUESTION_BANK.government.concat([
    // paper 2–11
    q("The necessary attributes of a state are",
      ["police, army, sovereignty and custom", "resources, population, sovereignty and government", "sovereignty, police, army and immigration", "definite territory, population, sovereignty and government"], D,
      "Every state must have four essential elements: a people (population), a defined territory, a government that rules them, and sovereignty (supreme power, free from outside control)."),
    q("The process of taking part in political and public affairs can be termed political",
      ["socialization", "recognition", "culture", "participation"], D,
      "Political participation is the involvement of citizens in public affairs: voting, standing for office, joining parties or pressure groups, attending rallies and debating public issues."),
    q("Membership of a society is",
      ["constitutional", "conventional", "mandatory", "voluntary"], D,
      "A society (an association such as a club, union, church or professional body) is joined by choice, and a member may leave it; membership of the state, by contrast, is compulsory."),
    q("In a democratic political system, the political sovereign is usually the",
      ["legislature", "constitution", "political parties", "electorate"], D,
      "Legal sovereignty lies with the body that makes the final law, but political sovereignty, the power behind it, lies with the people, exercised through the electorate at elections."),
    q("One basic feature of a monarchical form of government is that",
      ["the ruler has fixed tenure and power is absolute", "separation of powers is absolute", "members of the executive are elected", "succession is through heredity"], D,
      "In a monarchy the throne passes by heredity within a royal family, usually to the eldest son or nearest heir, and the monarch normally reigns for life."),
    q("One main advantage of the bicameral legislature is that it",
      ["is not easy to manipulate bills", "makes for quick deliberation during emergencies", "makes passage of bills easy", "is less cumbersome to pass bills"], A,
      "With two chambers, every bill must pass both houses, so one house checks the other; hasty or manipulated legislation is harder to push through."),
    q("The court that has the ultimate power to interpret the constitution is the",
      ["Court of Appeal", "Supreme Court", "Magistrate Court", "High Court"], B,
      "The Supreme Court is the highest court in Nigeria; its interpretation of the constitution is final and binds all other courts."),
    q("The unitary system of government is more suitable to a country",
      ["with a relatively small area and a homogeneous population", "that is sparsely populated", "that possesses a strong and modern army", "with a robust and dynamic economy"], A,
      "A unitary system, with all power at the centre, works best where the country is small and its people share one language and culture, so there is little need for regional self-rule."),
    q("An example of a country ruled by a constitutional monarch is",
      ["Libya", "Uganda", "Morocco", "Italy"], C,
      "Morocco is a kingdom whose king reigns under a written constitution with an elected parliament and prime minister; Libya, Uganda and Italy are republics."),
    q("The development of a classless society is the goal of",
      ["Marxism", "conservation", "feudalism", "liberalism"], A,
      "Karl Marx taught that class struggle would end with the workers overthrowing capitalism, leading through socialism to communism, a classless and stateless society."),
    // paper 12–21
    q("A flexible constitution is one which is",
      ["written by the parliament", "easily amended", "popular with the legislators", "known to all the citizens"], B,
      "A flexible constitution can be amended by the ordinary law-making process (a simple majority of the legislature), as in Britain; a rigid one needs a special procedure."),
    q("Which of the following is a feature of checks and balances?",
      ["Code of conduct", "Judicial precedent", "Judicial immunity", "Judicial review"], D,
      "Judicial review is the power of the courts to declare laws or executive acts unconstitutional and void; it is the judiciary's main check on the other two arms."),
    q("Laws made by military governments at the state level are called",
      ["acts", "decrees", "bye-laws", "edicts"], D,
      "Under military rule the federal government made decrees and state military governors made edicts; acts are made by legislatures and bye-laws by local councils."),
    q("Citizenship is acquired by an alien through",
      ["naturalization", "registration", "birth", "conferment"], A,
      "Naturalisation is the usual way a foreigner becomes a citizen: after living in the country for the required years and showing good character, he or she applies and takes the oath of allegiance."),
    q("The officer responsible for announcing the result of an election is known as",
      ["electoral officer", "ballot officer", "presiding officer", "returning officer"], D,
      "The returning officer collates the results of a constituency or election and formally declares (returns) the winner."),
    q("The ultimate aim of political parties is to",
      ["formulate and implement policies", "implement people-oriented programmes", "acquire and exercise power", "increase the political awareness of the electorate"], C,
      "A political party is an organised group that seeks to win elections so as to control and use the power of government; this is what sets it apart from a pressure group."),
    q("The main objective of pressure groups is to",
      ["serve as opposition to the government", "promote the interest of political parties", "influence legislation for the benefit of their members", "protect the interest of the country against foreigners"], C,
      "Pressure groups do not seek to form a government; they try to influence government policy and laws so as to protect and advance their members' interests."),
    q("Which of the following is not a dimension of public opinion?",
      ["Substance", "Polling", "Orientation", "Intensity"], B,
      "Public opinion is described by its dimensions: its substance (what it is about), its orientation or direction (for or against) and its intensity (how strongly it is held). Polling is a method of measuring public opinion, not a dimension of it.",
      { keyVerdict: 'corrected', keyAnswer: 'A',
        answerNote: "The answer key gives A (Substance), but substance, the content of an opinion (what people hold views about), is normally counted with orientation and intensity as a dimension of public opinion. Polling is a way of measuring public opinion, so it is the option that is not a dimension." }),
    q("The body that is responsible for the appointment, discipline, promotion and dismissal of civil servants is the",
      ["Ministry of Labour and Productivity", "Ministry of Establishment", "Bureau for Public Service Reforms", "Civil Service Commission"], D,
      "The Civil Service Commission (the Federal Civil Service Commission at the centre, state commissions in the states) appoints, promotes, disciplines and dismisses civil servants, keeping these decisions away from politicians."),
    // paper 21–30
    q("In the pre-colonial Hausa political system, the Madawaki performed the function of",
      ["Minister of Works", "Minister of Education", "Minister of Defence", "Minister of Interior"], C,
      "The Madawaki was the commander-in-chief of the emir's army, so his role was like that of a Minister of Defence."),
    q("In the Old Oyo Empire, the Ajele",
      ["ensured the safety of all trade routes", "ensured good governance of the districts", "mobilized the army", "was the head of the army"], B,
      "The Ajele were the Alaafin's resident representatives in the subject towns and districts of the empire; they watched over the local rulers, collected tribute and reported back to Oyo."),
    q("The General Strike of 1945 was caused primarily by the",
      ["disparity in the criteria for employment", "harshness in trade laws as it concerns the Africans", "government's rejection of a demand for an increase of 50 percent in the cost of living allowance", "persistent implementation of discriminatory laws"], C,
      "In June 1945 Nigerian workers, led by Michael Imoudu, struck for about six weeks after the colonial government refused their demand for a 50 per cent rise in the cost of living allowance."),
    q("Before 1945, the component units of Nigeria were",
      ["regions", "districts", "provinces", "states"], C,
      "From the 1914 amalgamation Nigeria was run as the Northern and Southern Provinces (the South was split into Eastern and Western Provinces in 1939); regions came only with the Richards Constitution of 1946."),
    q("National agitation began in Nigeria with the",
      ["formation of West African Youth League", "Lagos protest against water rate in 1908", "introduction of indirect rule", "annexation of Lagos in 1861"], B,
      "The first organised political agitation in Nigeria was the 1908 Lagos protest against the colonial water rate, when the People's Union was formed and Herbert Macaulay entered public life."),
    q("The emergence of nationalism was essentially the result of the ills of",
      ["imperialism", "independence", "slavery", "colonialism"], D,
      "Nationalism grew out of the grievances of colonial rule: racial discrimination, exclusion of Africans from government and senior posts, economic exploitation and the humiliation of foreign domination."),
    q("Which of the following nationalists was the founder of Nigeria's first political party?",
      ["Herbert Macaulay", "Abubakar Tafawa Balewa", "Ahmadu Bello", "Nnamdi Azikiwe"], A,
      "Herbert Macaulay founded the Nigerian National Democratic Party (NNDP) in 1923 to contest the Lagos seats created by the Clifford Constitution; it was Nigeria's first political party."),
    q("The division of powers between the federal and regional governments into exclusive, concurrent and residual lists was done by the",
      ["1979 Constitution", "1999 Constitution", "Independence Constitution", "1954 Constitution"], D,
      "The Lyttelton Constitution of 1954 made Nigeria a federation and first shared powers into an exclusive list (federal only), a concurrent list (both levels) and residual matters (the regions)."),
    q("The Nigerian Independence Constitution was modified by the",
      ["1979 Constitution", "1963 Constitution", "1999 Constitution", "1989 Constitution"], B,
      "The Republican Constitution of 1 October 1963 replaced the 1960 Independence Constitution, keeping most of it but making Nigeria a republic with a President in place of the Queen."),
    q("The President of Nigeria was indirectly elected through secret ballot for a period of five years by the senate in",
      ["1979", "1983", "1960", "1963"], D,
      "Under the 1963 Republican Constitution the ceremonial President was elected by secret ballot by the members of Parliament (the Senate and House of Representatives sitting together) for five years; Nnamdi Azikiwe was the first."),
    // paper 31–40
    q("The main function of the Federal Character Commission in Nigeria is",
      ["providing free social services to the citizens", "ensuring fair representation of all states in the public service", "reviewing unfair administrative decisions", "settling disputes among societies"], B,
      "The Federal Character Commission, set up in 1996 and in the 1999 Constitution, makes sure that jobs and posts in the public service are shared fairly among the states and local governments."),
    q("The power of appointing the chairman of the Independent National Electoral Commission is vested in the",
      ["Senate", "Judicial Council", "Council of State", "President"], D,
      "Under the 1999 Constitution the President appoints the INEC chairman, after consulting the Council of State and subject to confirmation by the Senate."),
    q("The NCNC and the NPC facilitated the creation of the",
      ["Eastern Region", "Mid-West Region", "Northern Region", "Western Region"], B,
      "The NPC–NCNC coalition at the centre carved the Mid-Western Region out of the Western Region (the Action Group's base) in 1963, making it Nigeria's fourth region."),
    q("One of the major problems of Nigerian federalism is",
      ["pre-colonial administrative structure among the units of federation", "lack of revenue to cater for the demands of the federation", "inadequate manpower to fill vacancies of the federation", "imbalance in the structure and sizes of units of federation"], D,
      "Nigeria's federation began lopsided: the Northern Region was bigger in area and population than the other regions put together, which bred fear of domination and agitation for new states."),
    q("Which of the following was done during the Gowon administration to reduce regional structural imbalance in the federation?",
      ["Formation of political parties", "Appointment of ministers", "Creation of states", "Increase in revenue allocation"], C,
      "On 27 May 1967 General Yakubu Gowon replaced the four regions with twelve states, breaking up the large Northern Region and easing the imbalance in the federation."),
    q("A problem of public corporations in Nigeria is",
      ["wastage of resources", "choice of leadership", "public control", "emphasis on subsidies"], A,
      "Nigerian public corporations have been plagued by waste: overstaffing, mismanagement, corruption and losses that must be covered from public funds."),
    q("One feature of public corporations that was weakened by privatization is",
      ["government control", "social control", "national integration", "social harmony"], A,
      "Privatisation sells government shares in public enterprises to private investors, so the government no longer owns or controls them."),
    q("One of the main duties of the Local Government Service Commission is to",
      ["handle requests for the creation of more local governments", "supervise and manage the personnel of local governments", "conduct elections into Local Council", "create an enabling working environment for council workers"], B,
      "The Local Government Service Commission in each state appoints, promotes, disciplines and manages the senior staff of the local governments, as the Civil Service Commission does for the civil service."),
    q("The Option A4 model was used in the conduct of the",
      ["1999 elections", "2007 elections", "1983 elections", "1993 elections"], D,
      "Option A4 was the open-ballot system of the Babangida transition: voters queued openly behind the picture of their candidate. It was used in the 12 June 1993 presidential election."),
    q("The review of Nigerian foreign policy under the Murtala-Obasanjo regime was done by",
      ["Phillips Commission", "Udoji Committee", "Aboyade Committee", "Adedeji Committee"], D,
      "In 1975 the Murtala–Obasanjo government set up a panel headed by Professor Adebayo Adedeji to review Nigeria's foreign policy; its 1976 report confirmed Africa as the centrepiece of that policy."),
    // paper 41–50
    q("Which of the following is a guiding principle of Nigeria's foreign policy?",
      ["Decolonisation of all African states", "Total opposition to the Cold War", "Posting of only career diplomats as envoys", "Interference in the affairs of African countries"], A,
      "From independence Nigeria committed itself to the total liberation of Africa from colonial rule and apartheid, alongside non-alignment and non-interference in other states' affairs."),
    q("The Technical Aid Corps was established during the regime of",
      ["Muhammadu Buhari", "Olusegun Obasanjo", "Sani Abacha", "Ibrahim Babangida"], D,
      "The Technical Aid Corps, which sends Nigerian professionals to serve in other African, Caribbean and Pacific countries, was set up in 1987 under Babangida, on the proposal of Foreign Minister Bolaji Akinyemi."),
    q("The granting of asylum to Charles Taylor by Nigeria was to",
      ["control Liberia", "protect Nigerians in Liberia", "promote peace in Liberia", "defy the Western powers"], C,
      "In August 2003 Nigeria gave Liberian President Charles Taylor asylum in Calabar so that he would step down and the Liberian civil war could end. (He was later handed over in 2006 and convicted of war crimes by the Special Court for Sierra Leone in 2012.)"),
    q("Nigeria is regarded as a frontline state because she",
      ["sent troops for peacekeeping in Somalia", "sent policemen for peacekeeping in Namibia", "assisted the liberation struggle in Southern Africa", "assisted ECOMOG troops in Liberia"], C,
      "Though far from Southern Africa, Nigeria gave so much money, diplomatic support and help to liberation movements in Angola, Zimbabwe, Namibia and South Africa that it was treated as an honorary frontline state."),
    q("The reason behind Nigeria's suspension from the Commonwealth in 1995 was",
      ["socio-cultural", "legal", "political", "economic"], C,
      "Nigeria was suspended in November 1995 for political reasons: Abacha's military rule and the execution of Ken Saro-Wiwa and eight other Ogoni activists breached the Commonwealth's democratic principles (Harare Declaration). It was readmitted in 1999."),
    q("Commonwealth nations are represented in other member nations by",
      ["attachés", "chargés d'affaires", "ambassadors", "high commissioners"], D,
      "Commonwealth countries exchange high commissioners, not ambassadors, with one another; ambassadors are sent to non-Commonwealth countries."),
    q("The UN succeeded the",
      ["League of Nations", "Warsaw Pact", "NATO", "SEATO"], A,
      "The United Nations, founded in 1945, replaced the League of Nations (1920), which had failed to prevent the Second World War and was formally dissolved in 1946."),
    q("The number of permanent members of the UN Security Council is",
      ["seven", "eight", "five", "six"], C,
      "The Security Council has five permanent members with the veto (USA, Russia, China, Britain and France) and ten non-permanent members elected for two years."),
    q("The Secretary-General of the OAU holds office for a renewable period of",
      ["five years", "six years", "three years", "four years"], D,
      "The OAU Secretary-General was appointed by the Assembly of Heads of State for a four-year term that could be renewed; Salim Ahmed Salim, for example, served three terms from 1989 to 2001. The OAU became the African Union in 2002, whose Commission chairperson also serves four years, renewable once."),
    q("Former colonies of Britain belong to the association known as",
      ["Commonwealth", "OECD", "NATO", "European Union"], A,
      "The Commonwealth is a voluntary association of Britain and mostly its former colonies; Nigeria joined at independence in 1960. Today it has 56 members, including a few (such as Mozambique and Rwanda) that were never British colonies."),
  ]);
})();
