/**
 * JAMB/UTME 2015 — GOVERNMENT
 * From the 2015 question paper (questions 1–50); answers from the JAMB/UTME Government answer key
 * 2001–2020, each checked independently. Answer checks carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2015;
  const SRC = 'JAMB UTME 2015';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  QUESTION_BANK.government = QUESTION_BANK.government.concat([
    // paper 1–10
    q("Which of the following countries is a founding member of the Commonwealth?",
      ["India", "Ghana", "South Africa", "Zimbabwe"], C,
      "South Africa was one of the self-governing dominions that formed the British Commonwealth under the Statute of Westminster (1931), and it was again among the eight members that founded the modern Commonwealth in 1949; Ghana joined only in 1957 and Zimbabwe in 1980.",
      { keyVerdict: 'multiple', alsoAccept: [A], keyAnswer: 'C',
        answerNote: "A is also accepted. The modern Commonwealth was founded by the London Declaration of 1949, and its eight founding members were Britain, Canada, Australia, New Zealand, South Africa, India, Pakistan and Ceylon (Sri Lanka). South Africa was also a member of the older British Commonwealth from 1931, so C fits either date, but India is a founding member of today's Commonwealth too." }),
    q("Which of the following is an achievement of OPEC?",
      ["Regulation of oil production and price", "The issue of quota", "Protection of member states", "Oil storage"], A,
      "OPEC's main achievement has been to coordinate its members' oil policies so as to regulate world oil production and stabilise prices; production quotas are simply the tool it uses to do this."),
    q("A political authority which maintains sovereign power over a specific geographical area is a",
      ["state", "nation", "country", "community"], A,
      "A state is a sovereign political organisation with a defined territory, a population and a government; sovereignty is what sets it apart from a nation, which is a people bound by culture and history."),
    q("The head of a crown colony under British rule was the",
      ["Secretary of Native Affairs", "Governor", "Secretary of State", "Governor-General"], B,
      "A British crown colony was administered by a Governor appointed by the Crown, who answered to the Secretary of State for the Colonies in London; Lagos, for example, was a crown colony under a Governor from 1862."),
    q("Nigeria spear-headed the formation and operation of ECOMOG in",
      ["Sudan", "Liberia", "Congo", "Egypt"], B,
      "ECOMOG, the ECOWAS Ceasefire Monitoring Group, was created in 1990 largely on Nigeria's initiative and first deployed to Liberia in August 1990 to end its civil war; Nigeria supplied most of its troops and money."),
    q("NEPAD came into existence in",
      ["2004", "2001", "2003", "2002"], B,
      "The New Partnership for Africa's Development (NEPAD) was adopted by African leaders in 2001: the OAU summit at Lusaka endorsed the plan in July 2001 and its framework was finalised in Abuja in October 2001."),
    q("The highest organ of the Commonwealth is the",
      ["Secretariat", "Fund", "Conference of Prime Ministers", "Trusteeship Council"], C,
      "The Commonwealth's highest decision-making body is the meeting of its heads of government, formerly the Conference of Prime Ministers and, since 1971, the Commonwealth Heads of Government Meeting (CHOGM)."),
    q("In which system of government are ceremonial and executive powers fused?",
      ["Federal", "Parliamentary", "Unitary", "Presidential"], D,
      "In the presidential system one person, the president, is both head of state (ceremonial) and head of government (executive); the parliamentary system separates the two roles."),
    q("In the Old Oyo Empire, the Oyomesi was headed by the",
      ["Baale", "Alaafin", "Bashorun", "Kakanfo"], C,
      "The Oyomesi was the council of seven kingmakers in Old Oyo, and its head was the Bashorun, who could order the Alaafin to commit suicide if the council rejected him."),
    q("The principle of non-alignment in Nigeria's foreign policy implies that",
      ["Nigeria will be objective during international crises", "Nigeria pledges neutrality in international trade relations", "Nigeria's foreign policy formulation process must not be influenced", "Nigeria is neither committed to the West nor the East"], D,
      "Non-alignment meant Nigeria would not join either the Western bloc led by the USA or the Eastern bloc led by the Soviet Union during the Cold War."),
    // paper 11–20
    q("Which of the following formulates and implements policies?",
      ["Police", "Judiciary", "Executive", "Legislature"], C,
      "The executive (the president or prime minister, ministers and the civil service) formulates government policy and carries it out; the legislature makes laws and the judiciary interprets them."),
    q("In pre-colonial Nigeria, centralised political administration did not exist among the",
      ["Kanuri", "Igbo", "Yoruba", "Hausa"], B,
      "Traditional Igbo society was acephalous (stateless): power was spread among the family heads (ofo holders), the council of elders, age grades and title societies in each village, with no central ruler."),
    q("The Economic and Social Council of the United Nations is made up of",
      ["28 members", "26 members", "25 members", "27 members"], D,
      "ECOSOC began in 1945 with 18 members, was enlarged to 27 in 1965 and to 54 in 1973; it has had 54 members ever since.",
      { keyVerdict: 'none', keyAnswer: 'D',
        answerNote: "None of the options is right for 2015 or today: ECOSOC has had 54 members since 1973. The question was set when ECOSOC had 27 members (1965–1973), so D is marked as the expected answer; 25, 26 and 28 were never its size." }),
    q("One of the agencies established by the military to promote national integration was the",
      ["Directorate of Mass Mobilization for Social and Economic Reconstruction", "Directorate of Food, Roads and Rural Infrastructure", "National Youth Service Corps", "National Directorate of Employment"], C,
      "General Gowon's government set up the National Youth Service Corps in 1973, after the civil war, to promote national unity and integration by posting young graduates to serve in states other than their own."),
    q("The French policy of assimilation in West Africa was a form of",
      ["monarchy", "indirect rule", "democratic rule", "direct rule"], D,
      "Under assimilation France ruled its colonies directly through French officials, aiming to turn Africans into Frenchmen; traditional rulers were reduced to junior agents of the administration."),
    q("The international organisation that formed NEPAD is",
      ["the Commonwealth", "ECOWAS", "the UN", "the AU"], D,
      "NEPAD was adopted in 2001 by African leaders under the OAU, which became the African Union in 2002; it is a programme of the AU, now run as the AU Development Agency (AUDA-NEPAD)."),
    q("An appropriation bill is",
      ["an impeachment bill", "a private member bill", "a money bill", "a state creation bill"], C,
      "An appropriation bill authorises government to spend public money for stated purposes, so it is a money bill; the annual budget is passed as an Appropriation Act."),
    q("An electoral college refers to",
      ["direct election", "indirect election", "the process of educating the electorate", "where public opinion is formed"], B,
      "An electoral college is a body of chosen electors who in turn elect an official, as in the election of the US president, so it is a form of indirect election."),
    q("Government by the few for the interest of the few is known as",
      ["autocracy", "monarchy", "oligarchy", "plutocracy"], C,
      "Aristotle called rule by a few in their own selfish interest oligarchy, the corrupt form of aristocracy (rule by the best few for the common good)."),
    q("Which of the following best describes Nigeria's foreign policy between 1960 and 1966?",
      ["Truly non-aligned", "Total dependence on the eastern bloc", "Dynamic and active", "Cautious and inactive"], D,
      "Under Prime Minister Tafawa Balewa (1960–66) Nigeria's foreign policy was conservative, cautious and pro-Western; the dynamic, active style came under Murtala Mohammed in 1975–76."),
    // paper 21–30
    q("Adjudication is the responsibility of",
      ["police", "bureaucracy", "judiciary", "executive"], C,
      "Adjudication means hearing and settling disputes by applying the law, which is the work of the courts, that is, the judiciary."),
    q("Citizenship can be acquired by",
      ["naturalisation", "indigenization", "education", "wealth"], A,
      "Citizenship is acquired by birth, by registration or by naturalisation; a foreigner who has lived in a country for the required period and meets its conditions can be naturalised."),
    q("The major interest for the penetration of Africa by the Europeans was",
      ["economic", "social", "political", "religious"], A,
      "Europe's main motive in Africa was economic: raw materials for its factories, markets for its manufactured goods and outlets for investment, especially after the Industrial Revolution."),
    q("The extent to which citizens accept institutions, officials and activities of government is known as",
      ["legitimacy", "authority", "power", "sovereignty"], A,
      "Legitimacy is the acceptance by the governed that the government and its institutions and officials have the right to rule."),
    q("The twelve-state structure was attained in Nigeria in",
      ["1974", "1965", "1967", "1966"], C,
      "General Gowon replaced the four regions with twelve states by decree on 27 May 1967, just before the civil war began."),
    q("One of the major defects of the 1999 Constitution was that it was",
      ["conceived by the military", "influenced by foreign powers", "drafted by the state Houses of Assembly", "drafted by the National Assembly"], A,
      "The 1999 Constitution was prepared under General Abdulsalami Abubakar's military government and promulgated by Decree No. 24 of 1999, so critics say it lacks the people's mandate even though it opens with 'We the people'."),
    q("Local government reforms in Nigeria were carried out in",
      ["1979", "1966", "1976", "1967"], C,
      "The 1976 Local Government Reform under the Murtala/Obasanjo regime introduced a uniform, single-tier system of local government throughout Nigeria."),
    q("The constitution that first introduced bicameral legislature in Nigeria was the",
      ["1960 Constitution", "1989 Constitution", "1963 Constitution", "1979 Constitution"], A,
      "The 1960 Independence Constitution created Nigeria's first two-chamber federal Parliament, a Senate and a House of Representatives; the 1979 and 1989 constitutions came much later."),
    q("The hallmark of capitalism is",
      ["restrictive economic policies", "private ownership", "even development", "state ownership"], B,
      "Capitalism rests on private ownership of the means of production, with prices and output decided by the free market and the profit motive."),
    q("Nationalism in Africa led to",
      ["the formation of economic blocs", "decolonization", "the formation of a continental army", "the creation of new states"], B,
      "African nationalist movements demanded and won self-government, so their main result was decolonisation: the end of colonial rule and independence, beginning with Ghana in 1957."),
    // paper 31–40
    q("A government which has the ability to compel its citizens to be obedient is exercising",
      ["legitimacy", "coercion", "right", "authority"], D,
      "Authority is the recognised right to give commands and have them obeyed; a government with authority can compel obedience because its power is backed by law and accepted by the citizens."),
    q("The newspaper founded by Herbert Macaulay that aided the independence struggle in Nigeria was the",
      ["Comet", "West African Pilot", "Lagos Daily News", "Daily Times"], C,
      "Herbert Macaulay founded the Lagos Daily News in 1925 and used it to attack colonial policies and support his Nigerian National Democratic Party."),
    q("The major aim of the United Nations is to",
      ["stabilize the price of oil in the world market", "co-ordinate and supervise the activities of specialized agencies", "maintain international peace and security", "promote sports among member nations"], C,
      "Article 1 of the UN Charter puts first among its purposes 'to maintain international peace and security'; the UN was founded in 1945 to save later generations from war."),
    q("A unitary system of government ensures cohesion because there is",
      ["rule of law", "concentration of power", "separation of power", "understanding and harmony"], B,
      "In a unitary system all governmental power is concentrated in one central government, which gives uniform policies and a strong, united direction."),
    q("Checks and balances violates the principle of",
      ["individual responsibility", "rule of law", "collective responsibility", "separation of powers"], D,
      "Checks and balances lets each organ interfere in the work of the others (the veto, impeachment, confirmation of appointments, judicial review), so it departs from a strict separation of powers in which each organ keeps entirely to its own work."),
    q("The Northern People's Congress was established in",
      ["1978", "1944", "1977", "1951"], D,
      "The NPC grew out of the cultural association Jam'iyyar Mutanen Arewa (1949) and became a political party in 1951, led by Sir Ahmadu Bello, the Sardauna of Sokoto."),
    q("A key characteristic of public opinion is that it is",
      ["often reliable", "dynamic", "not specific", "election"], B,
      "Public opinion is dynamic: the views of the public on an issue change over time as events, information and circumstances change."),
    q("Under monarchy, rulership is attained through",
      ["appointment", "competition", "hereditary", "election"], C,
      "In a monarchy the throne passes by heredity, usually from the ruler to a son or other close relative of the royal family."),
    q("Which of the following is an advantage of the federal system?",
      ["Fusion of power", "Integration of different groups", "Collective responsibility", "Rigid constitution"], B,
      "Federalism lets peoples of different languages, cultures and religions live together under one government while each unit keeps some self-rule, so it integrates diverse groups."),
    q("Under which of these constitutions did the Queen of England cease to be Nigeria's Head of State?",
      ["1989 Constitution", "1960 Constitution", "1963 Constitution", "1979 Constitution"], C,
      "The Republican Constitution of 1 October 1963 replaced the Queen with a Nigerian President, Dr Nnamdi Azikiwe, as ceremonial Head of State."),
    // paper 41–50
    q("The foreign policy of Nigeria is mainly determined by her",
      ["military strength", "national interest", "population", "geographical location"], B,
      "Every state's foreign policy is shaped above all by its national interest: its security, economic well-being, territorial integrity and the welfare of its citizens."),
    q("One merit of a one-party system is that it",
      ["gives room for opposition to thrive", "de-emphasizes the differences among party members", "pools together available talents into government", "prevents many members from defection"], B,
      "With only one party, rival ethnic, regional and ideological camps sit inside the same organisation, so differences among its members are played down for the sake of unity and stability."),
    q("A form of government in which political power is exercised by a dictator is",
      ["plutocracy", "fascism", "oligarchy", "feudalism"], B,
      "Fascism, as under Mussolini in Italy, concentrates all power in one dictator who leads a single party and controls every part of national life."),
    q("Which of the following does not operate a written constitution?",
      ["Britain", "Nigeria", "Ghana", "United States"], A,
      "Britain's constitution is not contained in one written document; it is found in Acts of Parliament, court decisions, conventions and works of authority."),
    q("A characteristic of a pressure group is that members",
      ["are in the same labour union", "oppose the government", "have similar interest", "do not believe in dialogue"], C,
      "A pressure group is an association of people who share a common interest and try to influence government policy in favour of that interest, without seeking to form the government."),
    q("The Public Complaints Commission is empowered to investigate complaints and",
      ["refer complaints to state governments", "refer findings to traditional rulers", "report findings to appropriate authorities", "prosecute offenders"], C,
      "Nigeria's ombudsman, the Public Complaints Commission (1975), investigates complaints of maladministration and reports its findings and recommendations to the appropriate authorities; it cannot prosecute anyone."),
    q("Which of the following is a major feature of the 1963 Constitution?",
      ["Accountability to the parliament", "Removal of judges", "Introduction of the republican form of government", "Introduction of national parliament"], C,
      "The 1963 Constitution made Nigeria a republic: the British monarch ceased to be Head of State and the final appeal to the Privy Council in London was abolished."),
    q("An attribute of a state is",
      ["technological advancement", "informed citizenry", "well-equipped army", "defined territory"], D,
      "The essential attributes of a state are a population, a defined territory, a government and sovereignty."),
    q("One of the first actions of military governments after a take-over is to",
      ["appoint new ministers", "detain all politicians", "give bonus to workers", "suspend the constitution"], D,
      "Soldiers who seize power usually suspend (or partly suspend) the constitution at once and rule by decrees, as happened in Nigeria in January 1966."),
    q("The equivalent of the prime minister under the Hausa pre-colonial system was the",
      ["Waziri", "Dogari", "Galadima", "Madawaki"], A,
      "In the Hausa-Fulani emirates the Waziri was the Emir's chief adviser and head of administration, the equivalent of a prime minister."),
  ]);
})();
