/**
 * JAMB/UTME 2005 — GOVERNMENT
 * From the 2005 question paper (all 50 questions); answers from the JAMB/UTME Government answer key
 * 2001–2020, each checked independently. Printing errors carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2005;
  const SRC = 'JAMB UTME 2005';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  QUESTION_BANK.government = QUESTION_BANK.government.concat([
    // paper 1–10
    q("The ultimate authority in a state is",
      ["legitimacy", "influence", "power", "sovereignty"], D,
      "Sovereignty is the supreme and final legal authority of the state: there is no higher authority within its territory, and it is independent of outside control."),
    q("The study of government essentially facilitates the understanding of the",
      ["organization of the executive arm of government", "observance of fundamental human rights", "functioning of the entire social formation", "governance of human societies"], D,
      "Government as a subject studies how human societies are governed: the state, its institutions, how power is gained and used, and how rulers and citizens relate."),
    q("The most important aspect of political participation in a democracy is",
      ["registration with a political party", "the observance of electoral processes", "voting in elections", "attending political rallies"], C,
      "Voting is the basic and most widespread form of participation: it is how citizens actually choose and change their rulers in a democracy."),
    q("A major flaw in a liberal democracy is",
      ["its emphasis on political rights over economic rights", "its emphasis on collective ownership", "the limitation of the freedom of expression", "that it promotes political instability"], A,
      "Liberal democracy guarantees political and civil rights (vote, speech, association) but leaves wealth to the free market, so critics say formal political equality sits beside deep economic inequality."),
    q("A non-monarchical state can best be described as a",
      ["confederation", "republic", "federation", "nation"], B,
      "A republic is a state whose head of state is not a hereditary monarch but is elected or appointed for a fixed term, as in Nigeria."),
    q("An elected legislator in a presidential system can lose his seat by",
      ["cross-carpeting", "recall", "impeachment", "a vote of no confidence"], B,
      "Recall lets the voters of a constituency remove their own representative before his term ends; Nigeria's 1999 Constitution provides for it in section 69."),
    q("In judicial administration, the term 'the bench' refers to the",
      ["judges", "lawyers", "litigants", "registrars"], A,
      "'The bench' means the judges or magistrates who sit to hear cases; lawyers are 'the bar'."),
    q("One of the foremost theorists of federalism was",
      ["K.C. Wheare", "Baron de Montesquieu", "A.V. Dicey", "Karl Marx"], A,
      "K.C. Wheare's book 'Federal Government' (1946) gave the classic definition of federalism: central and regional governments each independent and coordinate within their own spheres."),
    q("How does the president relieve a minister of his appointment in a presidential system of government?",
      ["By unilateral action", "In consultation with the legislature", "After serving a full tenure", "In consultation with the judiciary"], A,
      "In a presidential system ministers serve at the president's pleasure: the Senate confirms their appointment, but the president can dismiss them on his own."),
    q("Under a parliamentary system of government, the cabinet holds office at the pleasure of the",
      ["electorate", "legislature", "opposition", "head of state"], B,
      "The cabinet is drawn from and responsible to parliament; it stays in office only while it keeps the confidence of the legislature, and a vote of no confidence removes it."),
    // paper 11–20
    q("Serfs are the dominated class under",
      ["fascism", "capitalism", "feudalism", "socialism"], C,
      "Under feudalism the lords owned the land and the serfs were bound to it, working the lord's land in return for protection and a plot of their own."),
    q("An unwritten constitution is",
      ["partially written and based on convention", "completely unwritten and based on convention", "entirely based on case laws", "completely sourced from parliamentary law"], A,
      "An 'unwritten' constitution, like Britain's, is not collected in one document: parts are written (statutes, charters, case law) and parts rest on conventions."),
    q("The principle of checks and balances empowers the judiciary to",
      ["administer the criminal justice system", "apply the law", "invalidate the actions of the other arms", "abrogate the law"], C,
      "Through judicial review the courts check the legislature and executive by declaring their laws or actions void (ultra vires) when they go against the constitution."),
    q("The final stage in the process of enacting legislation is",
      ["guillotine", "notification", "assent", "final reading"], C,
      "After a bill passes its readings in the legislature, it becomes law only when the head of state (in Nigeria, the president or a governor) gives assent."),
    q("Citizenship acquired through marriage is referred to as",
      ["naturalization", "registration", "honorary", "nationalization"], B,
      "A foreign woman married to a Nigerian man can become a citizen by registration (section 26 of the 1999 Constitution)."),
    q("In a first-past-the-post electoral system, a candidate is declared elected when he",
      ["obtains a two-thirds majority of the votes cast", "records the highest number of the votes cast", "scores the aggregate of the opponents' votes", "obtains one-third of the votes cast"], B,
      "First-past-the-post (simple majority) elects whoever has the most votes, even if that is less than half of all votes cast."),
    q("On the basis of its structure, a political party can be classified as indirect if",
      ["it campaigns for votes through agents", "its membership is acquired through other groups", "it controls government indirectly", "it contests elections by proxy"], B,
      "An indirect party (Duverger's term) has members who join through affiliated bodies such as trade unions or cooperatives, as the British Labour Party did, not as individuals."),
    q("The pressure group that resorts to unconventional methods to achieve its objectives is called",
      ["promotional group", "interest group", "anomic group", "institutional group"], C,
      "Anomic groups are spontaneous, unorganised groups that use riots, violent demonstrations and other unconventional methods (Almond's classification)."),
    q("The method used to determine the possible outcome of an electoral contest is",
      ["opinion poll", "referendum", "plebiscite", "press review"], A,
      "An opinion poll asks a sample of voters about their intentions, so it can forecast the likely result of an election before it is held."),
    q("The major function of the civil service is",
      ["advising government and implementing its policies", "promoting the interest of civil servants", "providing relevant information on government", "keeping records of the activities of government"], A,
      "The civil service advises ministers when policies are made and then carries those policies out; keeping records and giving information are smaller parts of that work."),
    // paper 21–30
    q("Under the emirate system, legislative functions were performed by the",
      ["Ulama", "Khadi", "Emir", "Hakimi"], C,
      "In the Hausa-Fulani emirate the Emir was the supreme authority: he made laws (within Islamic law), ran the administration and was the final court of appeal."),
    q("The pre-colonial Tiv society can best be described as",
      ["monarchical", "republican", "aristocratic", "feudalistic"], B,
      "The Tiv, like the Igbo, were acephalous (without a central king): power was spread among lineage elders and family heads, a republican, segmentary system."),
    q("The failure of the assimilation policy necessitated the introduction of",
      ["indirect rule", "direct rule", "association", "paternalism"], C,
      "France's policy of assimilation (turning Africans into Frenchmen) failed, so France switched to association, which respected local cultures while keeping French control."),
    q("The political party formed in 1923 by Herbert Macaulay was",
      ["National Council of Nigeria and the Cameroons", "Nigerian National Democratic Party", "Nigerian Youth Movement", "United National Independent Party"], B,
      "Herbert Macaulay founded the Nigerian National Democratic Party (NNDP) in 1923 to contest the Lagos seats created by the Clifford Constitution; it was Nigeria's first political party."),
    q("In the First Republic, the official opposition party was the",
      ["Northern People's Congress", "Northern Elements Progressive Union", "National Council of Nigeria and the Cameroons", "Action Group"], D,
      "After the 1959 election the NPC and NCNC formed the federal coalition, so Chief Obafemi Awolowo's Action Group became the official opposition, with Awolowo as Leader of the Opposition."),
    q("The first federal constitution in Nigeria was the",
      ["Clifford Constitution", "Macpherson Constitution", "Lyttleton Constitution", "Independence Constitution"], C,
      "The Lyttleton Constitution of 1954 made Nigeria a true federation, sharing powers between the centre and the three regions (exclusive, concurrent and residual lists)."),
    q("A distinctive feature of the Richards Constitution was its provision for",
      ["official members in the Legislative Council", "unofficial members in the Legislative Council", "a Legislative Council for the whole of Nigeria", "the establishment of local councils"], C,
      "The Richards Constitution (1946) created a Legislative Council for the whole country, bringing the North into central law-making for the first time, plus regional Houses of Assembly."),
    q("Under the 1999 Constitution, the appointment of ministers and ambassadors must be ratified by the",
      ["House of Representatives", "Senate", "Presidency", "National Council of States"], B,
      "The president nominates ministers and ambassadors, but the Senate must confirm (approve) them before they take office."),
    q("The legislature in Nigeria under the 1999 Constitution is composed of",
      ["100 senators and 250 members of the House of Representatives", "108 senators and 350 members of the House of Representatives", "109 senators and 360 members of the House of Representatives", "109 senators and 350 members of the House of Representatives"], C,
      "The National Assembly has 109 senators (three for each of the 36 states plus one for the FCT) and 360 members of the House of Representatives."),
    q("The head of the Nigerian judiciary is the",
      ["Attorney-General and Minister of Justice", "Chief Justice of the Federation", "President of the Court of Appeal", "Solicitor-General of the Federation"], B,
      "The Chief Justice of Nigeria (of the Federation) heads the Supreme Court and the whole judiciary, and chairs the National Judicial Council."),
    // paper 31–40
    q("The commission established to handle the electoral activities in the Second Republic of Nigeria was",
      ["INEC", "NECON", "FEDECO", "NEC"], C,
      "The Federal Electoral Commission (FEDECO), set up in 1976, conducted the 1979 and 1983 elections of the Second Republic. Today elections are run by INEC (since 1998)."),
    q("A major function of the State Independent Electoral Commissions in Nigeria is the",
      ["conduct of gubernatorial elections", "delineation of electoral constituencies", "registration of political parties", "conduct of elections into local government offices"], D,
      "Each state's SIEC organises elections into local government councils (chairmen and councillors); governorship elections and party registration belong to INEC."),
    q("In Nigeria, promotion of judges is the responsibility of the",
      ["Council of Legal Education", "Attorney-General and Minister of Justice", "Judicial Service Commission", "Chief Justice of the Federation"], C,
      "Judicial Service Commissions (with the National Judicial Council at the federal level) handle the appointment, promotion and discipline of judges, keeping these out of politicians' hands."),
    q("During the Second Republic, the Great Nigeria People's Party won the governorship election in",
      ["Borno and Kaduna States", "Gongola and Sokoto States", "Borno and Gongola States", "Sokoto and Bauchi States"], C,
      "In 1979 Alhaji Waziri Ibrahim's GNPP won two states: Borno (Mohammed Goni) and Gongola (Abubakar Barde)."),
    q("In local government administration, Chief-and-Council implies that",
      ["all members of the local council are appointed and controlled by the chief", "the chief is a member of the local council but he does not exercise veto power", "the council operates independently of the chief's authority", "members of the local council appoint the chief to office"], B,
      "Under Chief-and-Council the chief sits as a member of the council and is bound by its majority decision; he has no veto, unlike under Chief-in-Council."),
    q("In the present local government structure, traditional rulers play",
      ["a judicial role", "an advisory role", "a legislative role", "an executive role"], B,
      "Since the 1976 reform, elected councils run local government and traditional rulers sit on traditional councils that only advise."),
    q("The first successful disengagement of the military from politics in Nigeria was carried out by the government of",
      ["Murtala/Obasanjo", "Buhari/Idiagbon", "Ibrahim Babangida", "Abdulsalami Abubakar"], A,
      "The Murtala/Obasanjo regime carried out its transition programme and handed power to the elected President Shehu Shagari on 1 October 1979."),
    q("The atomic bomb tests carried out around the Sahara Desert made Nigeria sever relations with",
      ["France", "Canada", "The United States", "Germany"], A,
      "France tested atomic bombs in the Algerian Sahara from 1960; in January 1961 the Balewa government broke diplomatic relations with France in protest."),
    q("Nigeria supports the South-South cooperation as a foreign policy objective for mutual understanding among",
      ["sub-Saharan African countries", "developing countries", "Asian and sub-Saharan African countries", "nations south of the equator"], B,
      "'South-South' cooperation means cooperation among developing countries of Africa, Asia and Latin America (the global South), as opposed to North-South relations with rich industrial nations."),
    q("An indication that Africa is still the centre-piece of Nigeria's foreign policy was the creation of the",
      ["Nigerian Institute of International Affairs", "Ministry of Integration and Cooperation in Africa", "Nigeria Institute of Policy and Strategic Studies", "Ministry of Foreign Affairs"], B,
      "A whole ministry devoted to integration and cooperation in Africa showed that African affairs remained Nigeria's top foreign policy concern."),
    // paper 41–50
    q("The Nigeria-Cameroun crisis over the Bakassi peninsula occurred owing to the interpretation of the treaty of 1913 and the",
      ["Maroua Accord", "resolution of the OAU", "decision of the International Court of Justice", "decision of the ECOWAS Tribunal"], A,
      "The dispute arose from the 1913 Anglo-German treaty and the 1975 Maroua Accord (Gowon and Ahidjo), which Nigeria later refused to accept. The ICJ ruled for Cameroon in 2002 and Nigeria handed Bakassi over in 2008."),
    q("Nigeria's voting at the United Nations is guided primarily by",
      ["world peace", "the cold war", "her concern for Africa", "her national interests"], D,
      "Like every state, Nigeria votes at the UN mainly to protect and advance its own national interest; concern for Africa and world peace are part of how it defines that interest."),
    q("Under the umbrella of the OAU, Nigeria mediated in the dispute between",
      ["Kenya and Somalia", "Tunisia and Morocco", "Ethiopia and Somalia", "Zimbabwe and Tanzania"], C,
      "Nigeria led the OAU's Good Offices (mediation) Committee on the Ethiopia-Somalia border dispute over the Ogaden region."),
    q("Nigeria is rated in the Organization of Petroleum Exporting Countries as the",
      ["third largest oil producer", "fifth largest oil producer", "sixth largest oil producer", "seventh largest oil producer"], C,
      "When the paper was set, Nigeria was rated the sixth largest producer in OPEC. Rankings change with output each year; Nigeria remains one of Africa's biggest producers."),
    q("Which of the following served as the Secretary-General of the United Nations?",
      ["Javier Perez de Cuellar", "Mohamed El-Baradei", "Ibrahim Gambari", "Joseph Garba"], A,
      "Javier Perez de Cuellar of Peru was UN Secretary-General from 1982 to 1991."),
    q("A Security Council resolution requires the concurrence of",
      ["3 of the 5 permanent members", "1 of the 5 permanent members", "all of the 5 permanent members", "9 of the 15 council members"], C,
      "Under Article 27 of the UN Charter a substantive resolution needs nine votes including the concurring votes of all five permanent members, so any one of them can veto it.",
      { keyVerdict: 'multiple', alsoAccept: [3], keyAnswer: 'C', answerNote: "Under Article 27 of the UN Charter a substantive resolution needs nine of the fifteen votes, including the concurring votes of all five permanent members. Both conditions are required, so C (the key's answer) and D are both accepted." }),
    q("A member of the Commonwealth that still recognizes the British monarch as its Head of State is",
      ["Ghana", "India", "Australia", "Singapore"], C,
      "Australia is a Commonwealth realm with the British monarch as head of state (Queen Elizabeth II then; King Charles III since September 2022); Ghana, India and Singapore are republics."),
    q("A major achievement of the OAU was the",
      ["decolonization of Africa", "promotion of development", "eradication of poverty", "establishment of democracy in Africa"], A,
      "Through its Liberation Committee the OAU (1963–2002) helped free the remaining colonies and end apartheid. The African Union replaced it in 2002."),
    q("The power to exercise overall control of the executive functions of ECOWAS is vested in the",
      ["Technical and Special Commissions", "Council of Ministers", "Authority of Heads of State and Government", "Secretary-General"], C,
      "The Authority of Heads of State and Government is ECOWAS's supreme organ: it directs and controls the community's executive functions. (The Secretariat became the ECOWAS Commission in 2007.)"),
    q("One of the organizational weaknesses of the Organization of Petroleum Exporting Countries is its inability to",
      ["collect membership dues promptly", "punish erring members", "assist poor countries", "monitor global oil consumption"], B,
      "OPEC sets production quotas but has no power to sanction members that produce above them, so quota-breaking weakens it."),
  ]);
})();
