/**
 * JAMB/UTME 2010 — GOVERNMENT
 * From the 2010 question paper (questions 2–50; Q1 only asked for the paper type); answers from the
 * JAMB/UTME Government answer key 2001–2020, each checked independently. Printing errors carry
 * keyVerdict/answerNote.
 */
(function () {
  const Y = 2010;
  const SRC = 'JAMB UTME 2010';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  QUESTION_BANK.government = QUESTION_BANK.government.concat([
    // paper 2–11
    q("Nation-state is synonymous with",
      ["self-actualization", "sovereignty", "liberation", "nationalism"], B,
      "A nation-state is an independent, sovereign state whose people largely share one national identity; being a nation-state means having sovereignty, supreme power over its own territory and affairs."),
    q("A fundamental component of political culture is",
      ["social values", "family values", "community structure", "economic values"], A,
      "Political culture is the set of shared beliefs, attitudes and values a society holds about politics and government, so its building blocks are the society's values."),
    q("A form of oligarchy in which gifted people are at the helm of affairs is",
      ["aristocracy", "theocracy", "plutocracy", "gerontocracy"], A,
      "Aristocracy (Greek aristos, 'best') is rule by a few people considered the best: the most gifted, talented or noble. It is a form of oligarchy (rule by the few)."),
    q("A state that is ruled by an elected citizen is",
      ["a monarchy", "a plutocracy", "a republic", "an empire"], C,
      "In a republic the head of state is an ordinary citizen elected (directly or indirectly) for a fixed term, not a hereditary monarch."),
    q("A true democracy in the modern sense exists where the",
      ["elected representatives rule", "majority of the people rule", "majority of the people vote", "elite rules"], A,
      "Modern states are too large for direct democracy, so democracy today is representative: the people elect representatives who govern on their behalf and answer to them at the next election."),
    q("In a parliamentary system, when the legislature passes a vote of no confidence on the executive, it means that the",
      ["executive is expected to go on suspension", "legislature ceases to trust the executive", "executive is required to resign", "legislature commences legal proceeding against the executive"], C,
      "In a parliamentary system the cabinet stays in office only while it keeps the confidence of parliament; if a vote of no confidence is passed, the prime minister and cabinet must resign (or ask for parliament to be dissolved for a fresh election)."),
    q("The legislative body of the United States of America is the",
      ["Parliament", "National Assembly", "Congress", "Council"], C,
      "The US legislature is Congress, made up of the Senate (two senators per state) and the House of Representatives."),
    q("Unicameralism is a feature of the legislature in",
      ["Israel", "the United States", "the United Kingdom", "Gambia"], A,
      "Israel's legislature, the Knesset, has a single chamber of 120 members. The Gambia's National Assembly is also a single chamber, while the USA and UK have two-chamber legislatures.",
      { keyVerdict: 'multiple', alsoAccept: [D], keyAnswer: 'A',
        answerNote: "Option D is also correct. The Gambia's National Assembly has a single chamber and has done so since independence in 1965, so Gambia's legislature is unicameral just like Israel's Knesset. Only the United States (Congress) and the United Kingdom (Parliament) have two chambers." }),
    q("The upper house in most federal systems is created to",
      ["ensure equality of federating units", "prevent excesses of the executive", "oversee and check the lower house", "enable experienced elders make inputs to governance"], A,
      "In federations the upper house usually gives each federating unit equal representation (for example 2 senators per US state; 3 per Nigerian state plus 1 for the FCT), so small units are not swamped by large ones."),
    q("In which of the following systems is the power of the component units more than that of the central government?",
      ["Monarchical", "Federal", "Unitary", "Confederal"], D,
      "In a confederation sovereign member states keep most power and create a weak centre that depends on them; they can even leave the union."),
    // paper 12–21
    q("One of the general tenets of fascist doctrine is that the leader is",
      ["supreme relative to the constitution", "weak relative to the constitution", "subordinate to the laws of the state", "subordinate to the norms of the society"], A,
      "Fascism (Mussolini's Italy, Hitler's Germany) glorifies the leader as the embodiment of the nation; his will stands above the constitution and the law."),
    q("In a cabinet system of government, executive power is exercised by the",
      ["head of government", "monarch", "president", "dominant party"], A,
      "In a cabinet (parliamentary) system the head of state, such as a monarch, is ceremonial; real executive power is exercised by the head of government, the prime minister, with the cabinet."),
    q("The principle of separation of powers is best practised in the",
      ["presidential system", "parliamentary system", "monarchical system", "feudal system"], A,
      "In a presidential system (USA, Nigeria) the executive is elected separately from the legislature and its members may not sit in it, so the three organs are kept apart; in a parliamentary system the executive and legislature are fused."),
    q("A typical form of delegated legislation is",
      ["an act", "a bill", "a decree", "a bye-law"], D,
      "Delegated legislation is law made by a body other than the legislature under powers the legislature gives it; bye-laws made by local governments and statutory bodies are the typical example."),
    q("The rights of a citizen can be withdrawn by the state if the person",
      ["opposes the government violently", "leaves the country permanently", "is convicted of a serious crime", "is pronounced dead"], C,
      "Rights such as liberty, and in some countries voting, can lawfully be taken away only through due process, when a court convicts the person of a serious crime."),
    q("An electoral process in which candidates are selected for elective offices by party members is",
      ["primary election", "electoral college", "bye election", "general election"], A,
      "A primary election is held within a party so that its members choose the candidate who will carry the party's flag at the general election."),
    q("In theory one major advantage of the one-party system is that it",
      ["eliminates intra-party conflict", "serves as an instrument of national integration", "promotes greater mass participation in government", "guarantees social justice"], B,
      "Supporters of one-party states (such as Nyerere's Tanzania and Nkrumah's Ghana) argued that a single party unites people of all ethnic groups and regions and so promotes national integration."),
    q("A tactic employed by pressure groups to achieve their objectives is",
      ["memorandum", "electioneering", "propaganda", "lobbying"], D,
      "Lobbying, making direct contact with legislators and officials to persuade them, is the classic pressure-group tactic; electioneering to win office is what political parties do."),
    q("Public opinion can be measured through",
      ["negotiation", "referendum", "strike action", "rumour"], B,
      "A referendum puts a question directly to the voters, so its result measures what the public thinks on that issue (opinion polls do the same informally)."),
    q("Which of the following is the main function of the civil service?",
      ["Implementing government policies", "Allocating resources to the federating units", "Supporting the party in power", "Mobilizing grass root support for government"], A,
      "The civil service is the permanent body of officials who advise ministers and carry out (implement) the policies of the government of the day, whatever party is in power."),
    // paper 22–31
    q("Who was the political head of the Old Oyo Empire?",
      ["Bashorun", "Oyomesi", "Aremo", "Alaafin"], D,
      "The Alaafin was the king and political head of the Old Oyo Empire; the Oyo Mesi, led by the Bashorun, were the council of kingmakers who checked him."),
    q("The Igbo political system was based on",
      ["age grades", "Umunna", "family ties", "Umuada"], C,
      "Pre-colonial Igbo society was acephalous (without a central king); the basic political unit was the family and lineage, each led by its eldest man (the Okpara), so the system rested on family (kinship) ties."),
    q("The Aro system in Igboland was",
      ["a religious organization", "a political organization", "a commercial organization", "an imperial organization"], A,
      "The Aro system was built on the Ibini Ukpabi ('Long Juju') oracle at Arochukwu, consulted across Igboland as a final court of appeal, so it was essentially a religious organization."),
    q("France introduced the policy of assimilation in her colonies primarily to",
      ["teach them the art of leadership", "give them a sound education", "change their way of life", "discourage them from ritual killings"], C,
      "Assimilation aimed to turn Africans into 'black Frenchmen' by replacing their culture, language, law and way of life with French ones."),
    q("The foremost British trading company on the West African coast was",
      ["Royal Niger Company", "United African Company", "Lever Brothers", "John Holt and Sons"], B,
      "The United African Company (UAC), formed in 1929 by merging the African and Eastern Trade Corporation with the Niger Company (a Lever Brothers subsidiary), became the largest British trading firm on the West African coast."),
    q("Which of these rulers resisted colonial rule and was deported to Calabar?",
      ["King Kosoko", "King Dosunmu", "Oba Ovonramwen", "King Jaja"], C,
      "After the British conquest of Benin in 1897, Oba Ovonramwen Nogbaisi was deported to Calabar, where he died in 1914."),
    q("Nigerian nationalism was described as two-phased by",
      ["John Payne Jackson", "Edward Wilmot Blyden", "James S. Coleman", "David Ricardo"], C,
      "The American political scientist James S. Coleman, in 'Nigeria: Background to Nationalism' (1958), divided Nigerian nationalism into two phases: early traditional (resistance) nationalism and modern nationalism."),
    q("One major weakness of the Independence Constitution is that it",
      ["failed to provide the country with full sovereignty", "gave total independence to Nigeria", "gave full powers to the Supreme Court in Nigeria", "empowered Britain to continue to rule"], A,
      "Under the 1960 Constitution the British monarch remained Nigeria's Head of State (represented by the Governor-General) and the Judicial Committee of the Privy Council in London remained the final court of appeal, so sovereignty was not complete."),
    q("The first law-making body in Nigeria after amalgamation was",
      ["Nigerian Council", "National Assembly", "Legislative Council", "Regional Assembly"], C,
      "Lugard's Nigerian Council (1914) was only an advisory body with no power to make laws; the Legislative Council, especially the one set up under the Clifford Constitution of 1922, was the law-making body."),
    q("The designation of ministers as chief executives and accounting officers was recommended by a commission headed by",
      ["Jerome Udoji", "S.J. Cookey", "Simeon Adebo", "Dotun Phillips"], D,
      "The Dotun Phillips panel (1985), put into effect by Decree No. 43 of 1988, made ministers the chief executives and accounting officers of their ministries and renamed the Permanent Secretary Director-General."),
    // paper 32–41
    q("A major shortcoming of the Ombudsman is",
      ["lack of adequate resources", "lack of clear-cut mandate", "its inability to restrain bureaucratic excesses", "lack of executive power to enforce decisions"], D,
      "The Ombudsman (in Nigeria, the Public Complaints Commission, set up in 1975) can investigate complaints and recommend remedies, but it cannot enforce its decisions; it depends on others to act."),
    q("One of the strong points of the multi-party Nigeria's Fourth Republic is",
      ["the provision for a bicameral legislature", "wider political participation", "government interference", "wider anti-democracy campaign"], B,
      "With many registered parties competing since 1999, more groups and citizens can organise, contest and vote, so the multi-party system widens political participation."),
    q("In which of the following is the ceremonial and executive powers fused?",
      ["Presidential system of government", "Parliamentary system of government", "Federal system of government", "Unitary system of government"], A,
      "In a presidential system one person, the president, is both head of state (ceremonial) and head of government (executive); in a parliamentary system the two roles are held by different people."),
    q("A major contentious issue confronting Nigerian federalism is",
      ["poverty", "education", "health care delivery", "revenue allocation"], D,
      "How federally collected revenue (mainly oil money) is shared among the federal, state and local governments, and by what principles such as derivation, has been disputed since the Phillipson Commission of 1946."),
    q("The main purpose of establishing public enterprises in Nigeria is to",
      ["increase government revenue", "provide essential services", "enrich the elite", "compete with the private sector"], B,
      "Public enterprises (such as NEPA, NITEL and the Nigerian Railway Corporation) were set up mainly to provide essential services that private firms could not or would not provide at affordable cost."),
    q("Parastatals are established to",
      ["enhance entrepreneurial skills", "maximize government profits", "expand business transactions", "render social services"], D,
      "Parastatals (public corporations and agencies) exist mainly to render services to the public, such as power, water and transport, rather than to make profit."),
    q("The General-Purpose Committee of the local government is the",
      ["cabinet of the local government", "local government public relations unit", "body responsible for supervising self-help projects", "body for awarding contracts"], A,
      "Under the 1976 Local Government Reform the General Purpose Committee, chaired by the chairman and made up of supervisory councillors and the secretary, acted as the executive arm, the cabinet, of the local government."),
    q("The highest organ of the state during the Babangida Regime was the",
      ["Provisional Ruling Council", "Supreme Military Council", "Armed Forces Ruling Council", "Federal Executive Council"], C,
      "Babangida (1985–1993) replaced the Supreme Military Council with the Armed Forces Ruling Council (AFRC) as the highest ruling body."),
    q("Decree 34 of 1966 was unacceptable to many Nigerians because it was",
      ["seen as an instrument of impoverishment", "perceived to abolish the federal system", "promulgated without consultation with the people", "considered as alien"], B,
      "Aguiyi-Ironsi's Unification Decree No. 34 (May 1966) abolished the regions and made Nigeria a unitary state; many, especially in the North, saw it as the end of federalism, and it helped trigger the July 1966 counter-coup."),
    q("Nigeria broke diplomatic relations with France in 1961 because of",
      ["France's atomic test in the Sahara Desert", "General de-Gaulle's negative attitude towards her", "her poor relations with the Francophone countries", "France's diplomatic relations with Israel"], A,
      "France carried out atomic tests in the Sahara (from February 1960); after a third test in December 1960, Balewa's government broke diplomatic relations with France in January 1961."),
    // paper 42–50
    q("An attribute that Nigeria shares with most non-aligned countries is",
      ["the state of her economy", "her heterogeneous population", "her large population", "her large size"], A,
      "Most non-aligned countries, like Nigeria, are developing countries: former colonies with economies dependent on exporting raw materials. Nigeria's very large population and size are unusual among them."),
    q("Nigeria spearheaded the formation of ECOWAS during the regime of",
      ["Olusegun Obasanjo", "Yakubu Gowon", "Murtala Muhammed", "Ibrahim Babangida"], B,
      "ECOWAS was founded by the Treaty of Lagos on 28 May 1975, under General Yakubu Gowon, who worked with Togo's Eyadema to bring it about."),
    q("Nigeria was classified as a frontline state for",
      ["participating in peacekeeping in the Congo", "supporting the liberation efforts in Southern Africa", "spearheading the formation of the African Union", "helping to end the crisis in Liberia"], B,
      "Though far from Southern Africa, Nigeria was treated as an honorary 'frontline state' because of its strong support (money, arms, diplomacy) for liberation movements in Angola, Mozambique, Zimbabwe, Namibia and South Africa."),
    q("The prominent role Nigeria played in the UN in the 70's earned her",
      ["non-permanent membership position", "membership of the Security Council", "permanent representation at the UN", "chairmanship of the General Assembly"], B,
      "Nigeria's active role at the UN, especially against apartheid, won her election as a member of the Security Council (a non-permanent seat) for 1978–1979.",
      { keyVerdict: 'multiple', alsoAccept: [A], keyAnswer: 'B',
        answerNote: "Option A is also correct: the seat Nigeria won was a non-permanent membership of the Security Council, so A and B describe the same achievement and both are accepted." }),
    q("The head of Nigeria's foreign mission in a Commonwealth nation is known as",
      ["high commissioner", "charge d'affaires", "ambassador", "attaché"], A,
      "Commonwealth countries exchange High Commissioners instead of ambassadors; Nigeria's envoy in London or Accra is a High Commissioner."),
    q("One major function of the Authority of Heads of State and Government of ECOWAS is",
      ["organizing international conferences", "appointing the Executive Secretary", "appointing staff of the Secretariat", "preparing the budget of the Community"], B,
      "Under the 1975 ECOWAS Treaty the Authority, the supreme organ, appointed the Executive Secretary. Since 2007 the Executive Secretariat has been replaced by the ECOWAS Commission, whose President the Authority appoints."),
    q("The tenure of non-permanent members of the Security Council is",
      ["5 years", "2 years", "4 years", "6 years"], B,
      "The ten non-permanent members of the UN Security Council are elected by the General Assembly for two-year terms, five seats changing each year."),
    q("The Secretary-General of the United Nations is appointed by the",
      ["Security Council acting alone", "General Assembly on the recommendation of the Security Council", "Permanent members of the Security Council on the recommendation of the General Assembly", "General Assembly in plenary session"], B,
      "Under Article 97 of the UN Charter the Secretary-General is appointed by the General Assembly upon the recommendation of the Security Council (where the veto applies)."),
    q("The approval of treaties and agreements of the Economic Community of West African States is the responsibility of the",
      ["secretariat", "ECOWAS Tribunal", "Council of Ministers", "Assembly of Heads of State and Government"], D,
      "The Authority (Assembly) of Heads of State and Government is the supreme organ of ECOWAS; it takes final decisions, including approving the Community's treaties and agreements.")
  ]);
})();
