/**
 * JAMB/UTME 2007 — GOVERNMENT
 * From the 2007 question paper (all 50 questions); answers from the JAMB/UTME Government answer key
 * 2001–2020, each checked independently. Printing errors carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2007;
  const SRC = 'JAMB UTME 2007';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  QUESTION_BANK.government = QUESTION_BANK.government.concat([
    // paper 1–10
    q("Which of the following is a hindrance to the democratization of the United Nations?",
      ["Resistance of the big powers", "Proliferation of weapons of mass destruction", "The multiplicity of official languages", "Delayed payment of annual dues by members"], A,
      "The five permanent members of the Security Council hold the veto and resist reforms (such as enlarging the Council or removing the veto) that would share power more equally among member states."),
    q("An essential principle that guides the activities of the United Nations is",
      ["the regulation of international trade", "the protection of the United States of America against terrorism", "respect for the sovereign equality of member states", "the transfer of technology to developing countries"], C,
      "Article 2(1) of the UN Charter states that the UN is based on the principle of the sovereign equality of all its members: each state, large or small, has one vote in the General Assembly."),
    q("The African Union was established to",
      ["form an African High Command", "promote global economic dominance by Africa", "address current international developments affecting Africa", "consolidate Africa's position in global politics"], D,
      "The AU (launched in Durban in 2002 to replace the OAU) was set up to unite Africa more closely and enable the continent to play its rightful role in the global economy and in international affairs."),
    q("A principal defect of the Commonwealth is",
      ["lack of commitment by member states", "lack of quorum at annual summits", "poverty among member states", "lack of a democratic head"], D,
      "The Head of the Commonwealth is the British monarch, who holds the position by heredity and is not elected by the member states; critics see this as undemocratic. King Charles III has been Head since 2022."),
    q("Nigeria declared that she would not attend the OAU summit in Tripoli in 1982 unless",
      ["Colonel Gaddafi resigned as the Libyan Head of State", "Libya withdrew her troops from Chad", "President Shehu Shagari became the chairman of OAU", "Cameroun was suspended for killing Nigerian soldiers at Bakassi"], B,
      "Libya's military intervention in Chad threatened Nigeria's neighbourhood; Nigeria insisted that Libyan troops leave Chad, and the 1982 Tripoli summit collapsed for lack of a quorum."),
    q("Nigeria's non-aligned policy was criticized because of the",
      ["ECOWAS Treaty", "Nuclear Test Ban Treaty", "Anglo-Nigerian Defence Pact", "Non-proliferation Treaty"], C,
      "The Anglo-Nigerian Defence Pact (1960) tied Nigeria militarily to Britain, a Western power, so critics said Nigeria was not truly non-aligned; protests forced its abrogation in January 1962."),
    q("NEPAD was adopted during the OAU summit held in",
      ["Tunis", "Lusaka", "Cairo", "Abuja"], B,
      "The 37th OAU summit in Lusaka, Zambia (July 2001) adopted the New African Initiative, which was renamed NEPAD (New Partnership for Africa's Development) in Abuja in October 2001."),
    q("Nigeria's interest in teaming up with other developing countries in the world is predicated on",
      ["her desire to consume more manufactured goods", "her desire to produce more raw materials", "preserving her independence and promoting development", "getting a permanent seat in the United Nations Security Council"], C,
      "Through groups such as the Non-Aligned Movement and the Group of 77, Nigeria works with other developing countries to protect their independence and push for fairer terms of trade and development."),
    q("Which of the following was once Nigeria's permanent representative at the United Nations?",
      ["Professor Bolaji Akinyemi", "Major General Ike Nwachukwu", "Professor Jubril Aminu", "Major General Joseph Garba"], D,
      "Major General Joseph Garba was Nigeria's Permanent Representative to the UN (1984–1989) and was elected President of the UN General Assembly in 1989."),
    q("Ethics and accountability in government can be guaranteed through",
      ["legislative cooperation", "executive and judicial immunity", "due process and transparency", "administrative reforms"], C,
      "When officials follow laid-down procedures (due process) and act openly (transparency), their conduct can be checked and they can be held to account."),
    // paper 11–20
    q("The process of law-making by the legislature begins with",
      ["initiating a bill", "commencing debate", "a public hearing", "the first reading"], D,
      "A bill formally enters the legislature at its first reading, when its title is read and it is published; debate on its principles follows at the second reading."),
    q("A non-permanent feature of a state is",
      ["society", "population", "territory", "government"], D,
      "Population, territory and sovereignty are lasting elements of a state, but governments come and go through elections, coups or resignations while the state continues."),
    q("The ancient Greeks practised",
      ["direct democracy", "representative democracy", "liberal democracy", "benevolent dictatorship"], A,
      "In Greek city-states such as Athens, the small number of citizens met in the assembly (ecclesia) and made laws themselves, without electing representatives."),
    q("The formation of confederations is based primarily on",
      ["hegemonic considerations", "historical reasons", "security considerations", "geographical factors"], C,
      "Sovereign states usually join a confederation for common defence and security against outside threats, as the American states did under the Articles of Confederation (1781)."),
    q("The declaration of election results is the exclusive duty of",
      ["political party chairmen", "electoral commissions", "chief justices", "election petition tribunals"], B,
      "Only the electoral body (in Nigeria today, INEC through its returning officers) can declare results; tribunals can later nullify an election, but they do not declare results in the first place."),
    q("The traditions of a people that shape their government and politics represent their",
      ["political culture", "political ideology", "political acculturation", "political socialization"], A,
      "Political culture is the set of attitudes, beliefs, values and traditions a people hold about government and politics."),
    q("According to Karl Marx, the mode of production that precedes capitalism is",
      ["mercantilism", "feudalism", "socialism", "communalism"], B,
      "Marx's stages of history are primitive communalism, slavery, feudalism, capitalism, socialism and communism, so feudalism comes just before capitalism."),
    q("The executive is mainly concerned with the",
      ["confirmation of appointments", "approval of treaties", "approval of budgets", "implementation of policies"], D,
      "The executive arm carries out (implements) laws and policies; confirming appointments, approving budgets and ratifying treaties are legislative checks."),
    q("A distinguishing feature of a federal state is",
      ["a written constitution", "resource control", "separation of powers", "cultural diversity"], A,
      "Every federation needs a written (and usually rigid) constitution that divides powers between the central and regional governments and protects that division.",
      { keyVerdict: 'corrected', keyAnswer: 'D',
        answerNote: "The answer key gives D (cultural diversity). Diversity is a common reason why countries ADOPT federalism, but it is not a feature of the federal structure itself: many unitary states are diverse, and some federations (such as Germany or Austria) are not. A written constitution is on every textbook list of the features of a federation, because the division of powers must be written down and protected, so A is the better answer." }),
    q("The recognition and general acceptance of the right to rule in a country based on laid-down regulations is known as",
      ["traditional authority", "constitutional authority", "sovereign authority", "legitimate authority"], D,
      "When the people recognise and accept a ruler's right to rule, that authority is legitimate; legitimacy is what turns power into authority."),
    // paper 21–30
    q("A political ideology that advocates extreme nationalism and suppression of individual liberties is",
      ["socialism", "communism", "feudalism", "fascism"], D,
      "Fascism, as in Mussolini's Italy (from 1922) and Hitler's Nazi Germany, glorifies the nation and the all-powerful state, suppresses opposition and individual freedoms, and rules through a single leader."),
    q("In a democracy, a major setback in the judicial process is",
      ["political neutrality", "lack of professionalism", "freedom from punishment", "inadequate material resources"], B,
      "Justice depends on competent, ethical judges and lawyers; incompetence, corruption and delay (lack of professionalism) undermine fair and speedy trials."),
    q("A vote taken by the citizenry on an important political issue is a",
      ["recall", "general election", "bye-election", "referendum"], D,
      "In a referendum the whole electorate votes directly on a specific issue, such as a constitutional change, rather than choosing representatives."),
    q("A constitution is classified as rigid if",
      ["it requires special procedures to amend", "its core provisions are made by decree", "its provisions cannot be amended", "any of its provisions can be amended"], A,
      "A rigid constitution can be amended only by a special procedure harder than ordinary law-making, such as two-thirds majorities in the legislature plus approval by the states."),
    q("An exception to the mandate of the legislature is the",
      ["enactment of laws", "oversight of the executive", "representation of the citizenry", "conduct of external relations"], D,
      "Making laws, checking the executive and representing the people are legislative jobs; conducting foreign relations is the work of the executive (the president and the foreign ministry)."),
    q("One of the obligations of a citizen is",
      ["obedience to the laws of the land", "active participation in partisan politics", "sticking to his beliefs", "loyalty to the ruling party"], A,
      "Every citizen has a duty to obey the laws of the land; joining party politics is a right, not an obligation, and loyalty is owed to the country, not to a party."),
    q("One of the objectives of a multiparty system is to",
      ["prevent rigging", "provide alternatives", "avoid ethnicity", "eliminate corruption"], B,
      "With several parties competing, voters have a real choice between alternative candidates, programmes and governments."),
    q("A constitution formulated and imposed on a country without popular participation is said to be created by",
      ["fiat", "directives", "command", "decree"], C,
      "A constitution handed down by a ruler or regime without the people taking part (through a constituent assembly or referendum) is said to be made by command, that is, imposed from above.",
      { keyVerdict: 'multiple', alsoAccept: [A], keyAnswer: 'C',
        answerNote: "Option A is also correct. \"Fiat\" means an authoritative order or command, so a constitution imposed without popular participation is equally said to be made \"by fiat\"; the two words mean the same thing here." }),
    q("In a parliamentary system, the term shadow cabinet is often used to refer to the",
      ["back-benchers in the house", "deputy prime ministers and assistant ministers", "rebellious members of the ruling party", "portfolio designates of the party in opposition"], D,
      "The shadow cabinet is the team of senior opposition members, each assigned to watch ('shadow') a particular minister and ready to take that post if the opposition wins power."),
    q("Which of the following made the earliest contact with the Nigerian society?",
      ["The Portuguese", "The Germans", "The British", "The French"], A,
      "Portuguese explorers and traders reached the Benin kingdom in the late fifteenth century (about 1472–1486), long before British contact."),
    // paper 31–40
    q("The adoption of a federal system of government in Nigeria under colonial rule was necessitated mainly by",
      ["geographical proximity", "administrative convenience", "cultural diversity", "vast economic resources"], C,
      "Nigeria's many ethnic, linguistic and religious groups wanted unity without losing their identity, so federalism (from the 1954 Lyttelton Constitution) let each region manage its own affairs."),
    q("Public corporations are established mainly to",
      ["offer free services", "make profit for government", "provide jobs for the unemployed", "provide services at subsidized rates"], D,
      "Public corporations (such as power, water and railway corporations) provide essential services to the public at affordable, often subsidised, rates rather than chiefly for profit."),
    q("Indirect rule as a British colonial policy was first introduced in",
      ["India", "Uganda", "Ghana", "Nigeria"], A,
      "Britain ruled the Indian princely states through their own rulers long before Africa was colonised; Lord Lugard later developed and made indirect rule famous in Northern Nigeria from 1900."),
    q("Following the 1976 Local Government Reforms in Nigeria, the local governments were empowered to",
      ["promulgate edicts", "promulgate and enforce bye-laws", "appoint and dismiss chairmen", "appoint and dismiss directors"], B,
      "The 1976 reform made local government the third tier of government, with power to make and enforce bye-laws on local matters within their areas."),
    q("In the Nigerian Constitution, the powers to create local governments lie with the",
      ["state governors", "National Assembly", "Presidency", "state houses of assembly"], D,
      "Under section 8(3) of the 1999 Constitution, a request for a new local government area must be passed by the State House of Assembly; the National Assembly then amends the constitution's list of LGAs."),
    q("The pre-colonial Igbo political system was largely",
      ["republican", "dictatorial", "monarchical", "authoritarian"], A,
      "Most Igbo communities had no kings: power was spread among the family heads (Ofo holders), the council of elders, age grades and the village assembly, so the system was decentralised and republican."),
    q("Which of the following states were created in 1996?",
      ["Akwa Ibom and Kogi", "Gombe and Zamfara", "Adamawa and Ekiti", "Ebonyi and Osun"], B,
      "On 1 October 1996 the Abacha regime created six states: Bayelsa, Ebonyi, Ekiti, Gombe, Nasarawa and Zamfara, bringing the total to 36, which is still the number today."),
    q("Acculturation in colonial administration is associated with the",
      ["French policy of assimilation", "British policy of direct rule", "French policy of association", "British indirect rule system"], A,
      "Assimilation aimed to turn Africans into Frenchmen by teaching them French language, culture and law, so that they absorbed the colonial culture (acculturation)."),
    q("Military disengagement from politics is always preceded by",
      ["the retirement of military personnel", "the making of a new constitution", "an increase in workers' salaries", "the establishment of more universities"], B,
      "Before handing over power, military regimes in Nigeria prepared a new constitution for the civilian government: the 1979 Constitution in 1979, and the 1999 Constitution in 1999."),
    q("The principle of federal character was first enunciated in the",
      ["1989 Constitution", "1963 Constitution", "1999 Constitution", "1979 Constitution"], D,
      "The 1979 Constitution (section 14(3)) first required that appointments and the composition of government reflect the federal character of Nigeria, so that no state or ethnic group dominates."),
    // paper 41–50
    q("The final court of appeal in Nigeria during the colonial era was the",
      ["privy council", "high court", "supreme court", "appeal court"], A,
      "The Judicial Committee of the Privy Council in London heard final appeals from Nigeria during colonial rule and until 1963, when Nigeria became a republic and its Supreme Court became the final court."),
    q("The Native Authority system of local administration was introduced by the British in Nigeria to",
      ["introduce Western education", "ensure the administration of justice", "empower traditional rulers", "facilitate tax collection"], D,
      "The Native Authorities, built on indirect rule, used traditional rulers to collect taxes (through native treasuries) and keep order, so the colony could be run cheaply."),
    q("The major objective of the manifesto of the People's Redemption Party in the Second Republic was",
      ["housing for all", "welfare of the nation", "emancipation of the masses", "free education"], C,
      "The PRP, led by Mallam Aminu Kano, set out to emancipate the common people (the talakawa) from social and economic oppression."),
    q("The privatization of public corporations in Nigeria is undertaken by the",
      ["Bureau of Public Enterprises", "Nigerian Stock Exchange", "Federal Civil Service Commission", "Federal Executive Council"], A,
      "The Bureau of Public Enterprises (BPE), the secretariat of the National Council on Privatisation, carries out the sale of government-owned enterprises."),
    q("The main goal of the NNDP was to",
      ["agitate for Nigeria's independence", "achieve franchise for Nigerians", "secure limited autonomy for the natives", "secure independence for Nigeria"], C,
      "Herbert Macaulay's NNDP (1923) sought greater African participation in government and self-government for Lagos within colonial rule; it did not demand independence.",
      { keyVerdict: 'corrected', keyAnswer: 'A',
        answerNote: "The answer key gives A (agitate for Nigeria's independence). The NNDP, formed in 1923 to contest the Lagos seats created by the Clifford Constitution, worked for municipal self-government for Lagos and a bigger African role in government under British rule. Demands for full independence came later, in the 1940s and 1950s. A and D both say \"independence\", so neither can be the single answer; C matches the NNDP's actual aims." }),
    q("The Structural Adjustment Programme was introduced by the",
      ["Babangida regime", "Abacha regime", "Murtala/Obasanjo regime", "Buhari regime"], A,
      "General Ibrahim Babangida's regime introduced SAP in July 1986 to restructure the economy: devaluing the naira, removing subsidies, deregulating and privatising."),
    q("The Ogboni cult in the pre-colonial Yoruba political system played the role of the",
      ["judiciary", "executive", "police", "legislature"], A,
      "The Ogboni, a powerful secret society of elders, judged serious cases such as those involving bloodshed and settled disputes between the Alaafin and the Oyo Mesi, so it acted as the judiciary.",
      { keyVerdict: 'misprint',
        answerNote: "The paper printed option C as \"policy\", which makes no sense among the arms of government listed; it is shown as \"police\". The answer is unchanged." }),
    q("The head of the electoral body that conducted the June 12, 1993 election was",
      ["Humphrey Nwosu", "Ovie-Whiskey", "Eme Awa", "Dagogo-Jack"], A,
      "Professor Humphrey Nwosu chaired the National Electoral Commission (NEC) that conducted the 12 June 1993 presidential election, later annulled by Babangida. Elections are now run by INEC, set up in 1998."),
    q("Deregulation as an economic policy borders on",
      ["the removal of subsidies on public utilities", "the removal of restrictions and extension of competition", "privatization", "commercialization"], B,
      "Deregulation means removing government controls and restrictions on an industry so that more private firms can enter and compete."),
    q("Ethnic politics in Nigeria can be traced to the",
      ["Macpherson Constitution", "Lyttelton Constitution", "Clifford Constitution", "Richards Constitution"], D,
      "The Richards Constitution (1946) divided Nigeria into three regions (North, West, East), each dominated by one major ethnic group, laying the foundation of regionalism and ethnic politics.")
  ]);
})();
