/**
 * JAMB/UTME 2003 — GOVERNMENT
 * From the 2003 question paper (all 50 questions); answers from the JAMB/UTME Government answer key
 * 2001–2020, each checked independently. Printing errors carry keyVerdict/answerNote.
 */
(function () {
  const Y = 2003;
  const SRC = 'JAMB UTME 2003';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});

  QUESTION_BANK.government = QUESTION_BANK.government.concat([
    // paper 1–10
    q("One of the duties of the legislature is to",
      ["exercise oversight", "implement laws", "promulgate decrees", "adjudicate disputes"], A,
      "Besides making laws, the legislature oversees the executive: it checks how laws are carried out and how public money is spent, through committees, questions and investigations."),
    q("The best form of government for a heterogeneous society is a",
      ["quasi-federal system", "confederal system", "unitary system", "federal system"], D,
      "Federalism lets peoples of different languages, cultures and religions keep their own regional governments while sharing one central government, so it suits a diverse society like Nigeria."),
    q("Removal by impeachment applies to the position of a",
      ["chief judge", "president", "Prime Minister", "cabinet minister"], B,
      "Impeachment is the legislature's procedure for removing an executive president (or governor) for gross misconduct; a Prime Minister is removed by a vote of no confidence instead."),
    q("Government by the wealthy is known as",
      ["oligarchy", "aristocracy", "plutocracy", "democracy"], C,
      "Plutocracy (Greek ploutos, wealth) is rule by the rich."),
    q("The independence of the judiciary can be undermined through the",
      ["payment of the salaries of judicial officers by government", "appointment of the minister of justice as the Attorney-General", "politicization of the appointments of judges", "confirmation of the appointment of judges by the legislature"], C,
      "When judges are appointed for party or political loyalty rather than merit, they may feel they owe the politicians, so their impartiality and independence suffer."),
    q("The unrestrained power of the state over its citizens is underlined by",
      ["self-determination", "patriotism", "sovereignty", "nationalism"], C,
      "Sovereignty is the supreme, final and unlimited power of the state to make and enforce laws over everyone within its territory."),
    q("In a parliamentary system, the functions of the head of state and the head of government are vested in",
      ["the ministerial council", "an individual", "the inner cabinet", "two different individuals"], D,
      "A parliamentary system has a dual executive: a ceremonial head of state (monarch or president) and a separate head of government (the Prime Minister)."),
    q("A collegial executive is a government in which power is vested in a",
      ["committee", "monarch", "parliament", "president"], A,
      "A collegial (plural) executive is a committee of equals who hold executive power jointly, as in Switzerland's seven-member Federal Council."),
    q("A common feature of government is",
      ["the making of public policy", "the separation of powers", "the independence of the judiciary", "a written constitution"], A,
      "Every government, whatever its form, makes and carries out public policy; the other options are found in some systems but not in all."),
    q("A meeting of the legislature is usually brought to an end with",
      ["a prorogation", "a dissolution", "suspension", "an adjournment"], D,
      "Each sitting of the legislature ends with an adjournment to a later date; prorogation ends a whole session and dissolution ends the life of the legislature."),
    // paper 11–20
    q("The civil service embraces all workers in",
      ["public and private companies", "all private corporations", "public corporations", "government ministries"], D,
      "The civil service is the body of permanent, non-political officials who work in government ministries and departments."),
    q("The citizenship of a country could be acquired through",
      ["registration and arbitration", "presidential proclamation", "birth and naturalization", "parliamentary legislation"], C,
      "Citizenship is acquired by birth, by registration or by naturalization; option C names two of these recognised ways."),
    q("What distinguishes a political party from other social institutions is the desire to",
      ["promote the interest of party members", "influence the international community on local issues", "influence government policies in certain directions", "win elections and form a government"], D,
      "A political party aims to capture power by winning elections and forming the government; pressure groups only try to influence government."),
    q("Capitalism is a system of economic organization based on",
      ["very fair distribution of the means of production", "a mixed economy that takes all interest into consideration", "trading among people who own and control their items of trade", "individual ownership of the means of production"], D,
      "Capitalism rests on private (individual) ownership of the means of production, with production for profit in a free market."),
    q("Socialism is a mode of production based on",
      ["national ownership of the means of production", "mixed ownership of the means of production", "state ownership of the means of production", "collective ownership of the means of production"], C,
      "Under socialism the main means of production are taken out of private hands and owned by the state on behalf of society.",
      { keyVerdict: 'multiple', alsoAccept: [D], keyAnswer: 'C',
        answerNote: "Option D is also accepted: socialism is defined in standard textbooks as collective or state ownership of the means of production, so both C and D describe it." }),
    q("Constitutional disputes in states with written constitutions are resolved by the",
      ["legislature", "ombudsman", "electorate", "judiciary"], D,
      "The courts interpret a written constitution and settle disputes over its meaning, for example between the federal and state governments."),
    q("Election as a political process is significant because it",
      ["facilitates constitutional change of government", "is associated with campaigns for public office", "facilitates the recall process", "enables citizens to vote"], A,
      "Elections allow governments to be changed peacefully and lawfully, by the votes of the people instead of by force."),
    q("Public opinion becomes politically relevant when it",
      ["aggregates views and interests", "is in support of government", "influences the decision of government", "criticizes people in power"], C,
      "Public opinion matters politically only when it actually shapes what government decides."),
    q("The operation of the rule of law is undermined by the",
      ["conspiracy by the two houses of the legislature to impeach the president", "inability of the press to discharge its responsibilities", "unfriendly attitude of pressure groups", "existence of administrative tribunals and special immunities"], D,
      "Administrative tribunals and immunities (for example, for the president or diplomats) mean some cases skip the ordinary courts and some people cannot be sued, which breaks equality before the law."),
    q("Associations whose main interest is to influence public policies without having to capture power are",
      ["political parties", "communal groups", "pressure groups", "trade unions"], C,
      "Pressure (interest) groups try to influence government policy but do not seek to win elections or form a government."),
    // paper 21–30
    q("One of the legacies of pre-colonial Nigeria destroyed by the British was the",
      ["peace and harmony in the land", "nation's farmland", "education of the local people", "indigenous cultures of the people"], D,
      "Colonial rule weakened indigenous cultures: traditional religion, institutions, languages and values gave way to Western ones."),
    q("The smooth operation of the civil service in Nigeria is mostly hampered by",
      ["debt burden and redundancy", "poor infrastructure", "inadequate training of personnel", "corruption and inefficiency"], D,
      "Corruption and inefficiency are the most widely cited problems of the Nigerian civil service, slowing down and distorting public business."),
    q("The type of government operated in Nigeria between October 1st 1979 and December 31st 1983 is called",
      ["presidential system of government", "collegial system of government", "unitary system of government", "parliamentary system of government"], A,
      "The Second Republic (1 October 1979 to 31 December 1983) under the 1979 Constitution used an American-style presidential system, with Shehu Shagari as Executive President."),
    q("In the pre-colonial Igbo society, the maintenance of peace and order was the function of the",
      ["assembly of Ezes", "age-grades", "assembly of title holders", "clan elders"], B,
      "In the Igbo village, age-grades acted as the police and labour force: they kept order, enforced decisions and did public works."),
    q("The expenditure of public funds by the executive in Nigeria is controlled by the",
      ["president", "ministry of finance", "judiciary", "legislature"], D,
      "The legislature controls public money: it passes the appropriation (budget) act, approves extra spending and checks accounts through its public accounts committees."),
    q("The 1979 Constitution established the",
      ["Federal Civil Defence Corps", "National Human Rights Commission", "Federal Road Safety Commission", "National Population Commission"], D,
      "The National Population Commission was one of the federal executive bodies created by the 1979 Constitution; the other bodies were set up later by decrees or acts."),
    q("The Eastern and Western regions of Nigeria achieved the status of self-government in",
      ["1959", "1950", "1955", "1957"], D,
      "The Western and Eastern Regions became self-governing in 1957; the Northern Region followed in 1959."),
    q("The Arthur Richards Constitution was designed to last for",
      ["six years", "twelve years", "five years", "nine years"], D,
      "The Richards Constitution (in force 1947) was meant to last nine years, with reviews every three years, but it was replaced by the Macpherson Constitution in 1951."),
    q("The 1976 reforms have been most beneficial to the",
      ["Nigeria Police", "civil service", "federal government", "local government"], D,
      "The 1976 Local Government Reform created a uniform, single-tier local government system across Nigeria and recognised it as the third tier of government."),
    q("A problem of Nigerian federalism that was resolved by the Supreme Court between the federal government and the littoral states centred on resource",
      ["maximization", "control", "derivation", "generation"], B,
      "In April 2002 the Supreme Court ruled on the resource control (onshore/offshore) suit, holding that oil from the offshore seabed belongs to the federal government, not the coastal (littoral) states."),
    // paper 31–40
    q("One of the reasons advanced for the overthrow of the Gowon Regime was its failure to",
      ["promote some officers of the armed forces", "honour the promise to hand over power", "create new states", "try politicians in detention"], B,
      "In October 1974 Gowon said his promised 1976 return to civil rule was unrealistic; this broken promise was a key reason given for his overthrow on 29 July 1975."),
    q("In the first republic, politics in the Northern region was dominated by the",
      ["NPC", "NCNC", "NEPU", "UMBC"], A,
      "The Northern People's Congress (NPC), led by Sir Ahmadu Bello, the Sardauna of Sokoto, controlled the Northern Region throughout the First Republic."),
    q("The Bureau for Public Enterprises is charged with the responsibility for",
      ["eradicating poverty", "generating opportunities", "providing employment opportunities", "privatization and commercialization"], D,
      "The Bureau of Public Enterprises (BPE) carries out the federal government's privatization and commercialization of public enterprises."),
    q("The military head of state during the Third Republic was",
      ["General Ibrahim Babangida", "General Murtala Muhammed", "General Sani Abacha", "General Olusegun Obasanjo"], A,
      "The Third Republic (elected governors and a National Assembly under the 1989 Constitution, 1992–93) was set up under General Ibrahim Babangida's transition programme."),
    q("The most important challenge facing the Fourth Republic is",
      ["the need to develop Nigeria", "how to develop Nigeria's social institution", "how to deal with the military", "the successful conduct of the 2003 elections"], D,
      "When the paper was set, the big test of the Fourth Republic (begun 29 May 1999) was holding the 2003 elections successfully, the first civilian-to-civilian transition attempt since 1983."),
    q("Financial allocation to local government by the federal or the state government to supplement the cost of a project is called",
      ["revenue allocation", "matching grant", "statutory allocation", "reimbursement"], B,
      "A matching grant is money a higher government gives to match or supplement what the local government itself puts into a particular project."),
    q("Nigeria's influence in OPEC is determined by the",
      ["sizes of her refineries", "accessibility of her oil fields", "low sulphur content of her crude", "volume of her oil revenue"], D,
      "A member's weight in OPEC depends on how much oil it produces and earns from; as Africa's largest producer, Nigeria's large oil output and revenue give it influence."),
    q("The activities of Nigeria in the international community are primarily influenced by",
      ["military power", "diplomacy", "propaganda", "national interest"], D,
      "Every country's foreign policy is driven first by its national interest: its security, economic well-being and prestige."),
    q("The dispute between Nigeria and Cameroon is over",
      ["trade", "exploration rights", "fishing rights", "territory"], D,
      "The dispute was over territory, chiefly the oil-rich Bakassi Peninsula; the International Court of Justice gave it to Cameroon in October 2002 and Nigeria completed the handover in August 2008."),
    q("Nigeria's high standing in the UN General Assembly is underscored by her",
      ["financial contribution", "military strength", "successes in UN elective offices", "contribution to global peace"], D,
      "Nigeria is respected at the UN mainly for its contribution to world peace, above all its many peacekeeping troops, from the Congo in 1960 onwards."),
    // paper 41–50
    q("Nigeria's Non-Alignment policy is constrained by her",
      ["membership of the UNO", "Afrocentric posture", "membership of ECOWAS", "strong ties with Western powers"], D,
      "Nigeria claimed to be non-aligned, but its strong economic, colonial and military ties with Britain and the West made true neutrality between East and West hard."),
    q("The main constraint on Nigeria–Francophone West African cooperation is",
      ["ideological differences", "cultural differences", "poor road network", "economic dependence"], D,
      "The French-speaking states are tied to France by the CFA franc, aid, trade and defence agreements; this economic dependence on France limits how closely they work with Nigeria.",
      { keyVerdict: 'corrected', keyAnswer: 'A',
        answerNote: "Nigeria and its French-speaking neighbours were not divided by ideology (both were broadly pro-Western). What held them apart was the neighbours' economic dependence on France, through the CFA franc, aid and defence pacts. So D is the better answer." }),
    q("Nigeria's relations with Britain were at a very low ebb under the",
      ["Buhari Regime", "Gowon Regime", "Shagari Regime", "Babangida Regime"], A,
      "Under Buhari, the 1984 attempt to kidnap ex-minister Umaru Dikko from London in a crate led both countries to expel diplomats and withdraw their High Commissioners."),
    q("The ECOWAS Treaty was reviewed in 1991 to",
      ["accommodate the interest of France", "mobilize ECOMOG", "accommodate extra sub-regional interest", "make it responsive to new challenges"], D,
      "The 1991 review (which led to the Revised Treaty signed at Cotonou in 1993) updated the 1975 Treaty of Lagos to meet new challenges such as regional security and deeper economic integration."),
    q("The headquarters of the International Court of Justice is in",
      ["Paris", "The Hague", "London", "Washington DC"], B,
      "The International Court of Justice, the UN's principal judicial organ, sits at the Peace Palace in The Hague, Netherlands."),
    q("The independent African countries that did not sign the OAU Charter on May 25, 1963 were",
      ["Morocco and Angola", "Togo and Sierra Leone", "Chad and the Gambia", "Togo and Morocco"], D,
      "Of the 32 independent states, 30 signed the Charter in Addis Ababa on 25 May 1963; Togo and Morocco signed later that year."),
    q("The tenure of the President of the UN Security Council is",
      ["two years", "one year", "one month", "six months"], C,
      "The presidency of the Security Council rotates every month among its 15 members, in English alphabetical order."),
    q("The majority of the OPEC members are from",
      ["Asia", "Latin America", "the Middle East", "Africa"], C,
      "In 2003, 6 of OPEC's 11 members (Iran, Iraq, Kuwait, Qatar, Saudi Arabia, UAE) were in the Middle East. Today the African members (6 of 12) outnumber the Middle Eastern ones (5)."),
    q("The non-British colony which is a member of the Commonwealth is",
      ["Guinea-Bissau", "Mozambique", "Rwanda", "Eritrea"], B,
      "Mozambique, a former Portuguese colony, joined the Commonwealth in 1995. Today Rwanda (joined 2009), Gabon and Togo (2022) are also non-British members.",
      { keyVerdict: 'multiple', alsoAccept: [C], keyAnswer: 'B',
        answerNote: "Option C is also correct today: Rwanda, a former Belgian territory, joined the Commonwealth in 2009. When this paper was set only Mozambique (B) had joined, so both are accepted." }),
    q("The major problem of the ECOWAS is lack of",
      ["a common Customs Union", "a common currency", "uniform ideology", "commitment by members"], B,
      "ECOWAS members use several currencies (the CFA franc, naira, cedi and others), which makes trade and payments between them difficult; the planned single currency (the Eco) has still not been launched.")
  ]);
})();
