/**
 * JAMB/UTME 2004 — MATHEMATICS
 * From the 2004 question paper; answers from the JAMB/UTME Mathematics answer key 2001–2020,
 * each verified by working the question. Key errors carry keyVerdict/keyAnswer/answerNote.
 * Paper question 18 (cumulative frequency graph) is left out: the graph is unreadable in the scan.
 */
(function () {
  const Y = 2004;
  const SRC = 'JAMB UTME 2004';
  const A = 0, B = 1, C = 2, D = 3;
  const q = (question, options, answer, explanation, extra) =>
    Object.assign({ question, options, answer, explanation, year: Y, source: SRC }, extra || {});
  const IMG = f => `<img src="past-questions/img/${f}" alt="Diagram for this question" loading="lazy">`;

  QUESTION_BANK.mathematics = QUESTION_BANK.mathematics.concat([
    // 1–10
    q("An arc of a circle of length 22 cm subtends an angle of 3x° at the centre of the circle. Find the value of x if the diameter of the circle is 14 cm. [Take π = 22/7]", ["60°", "120°", "180°", "30°"], A,
      "Circumference = (22/7) × 14 = 44 cm, so the arc is 22/44 = ½ of the circle: 3x = 180°, x = 60°."),
    q("Find the value of α² + β² if α + β = 2 and the distance between the points (1, α) and (β, 1) is 3 units.", ["14", "3", "5", "11"], D,
      "(β − 1)² + (1 − α)² = 9 gives α² + β² − 2(α + β) + 2 = 9, so α² + β² − 4 + 2 = 9 and α² + β² = 11."),
    q("The sum of the interior angles of a pentagon is 6x + 6y. Find y in terms of x.", ["y = 90 − x", "y = 150 − x", "y = 60 − x", "y = 120 − x"], A,
      "Angle sum of a pentagon = (5 − 2) × 180° = 540°. 6x + 6y = 540, so x + y = 90 and y = 90 − x."),
    q("In the diagram, PQ = 4 cm and TS = 6 cm. If the area of parallelogram PQTU is 32 cm², find the area of the trapezium PQRU. (U is the unlabelled bottom-left corner.)", ["60 cm²", "72 cm²", "48 cm²", "24 cm²"], B,
      "PQTU and PQRS are parallelograms, so UT = SR = 4 cm and UR = 4 + 6 + 4 = 14 cm. Height = 32 ÷ 4 = 8 cm. Area = ½(4 + 14) × 8 = 72 cm².",
      { diagram: IMG('maths-2004-q4.png') }),
    q("Find the midpoint of the line joining P(−3, 5) and Q(5, −3).", ["(1, 1)", "(2, 2)", "(4, 4)", "(4, −4)"], A,
      "Midpoint = ((−3 + 5)/2, (5 + (−3))/2) = (2/2, 2/2) = (1, 1)."),
    q("PQRSTV is a regular polygon of side 7 cm inscribed in a circle. Find the circumference of the circle PQRSTV. [π = 22/7]", ["56 cm", "22 cm", "42 cm", "44 cm"], D,
      "A regular hexagon inscribed in a circle has side = radius, so r = 7 cm. Circumference = 2 × 22/7 × 7 = 44 cm."),
    q("Determine the locus of a point inside a square PQRS which is equidistant from PQ and QR.", ["The diagonal QS", "The perpendicular bisector of PQ", "The diagonal PR", "Side SR"], A,
      "Points equidistant from two meeting lines lie on the bisector of the angle between them. PQ and QR meet at Q, and the bisector of angle Q in a square is the diagonal QS."),
    q("Find the value of x in the figure.", ["15√6", "20√6", "3√6", "5√6"], D,
      "Sine rule: x/sin 45° = 15/sin 60°, so x = 15 × (√2/2) ÷ (√3/2) = 15√2/√3 = 15√6/3 = 5√6.",
      { diagram: IMG('maths-2004-q8.png') }),
    q("P, R and S lie on a circle centre O as shown, while Q lies outside the circle. Find ∠PSO.", ["45°", "55°", "35°", "40°"], C,
      "In △PQR the exterior angle ∠PRS = 35° + 20° = 55°. The angle at the centre ∠POS = 2 × 55° = 110°. △POS is isosceles (OP = OS), so ∠PSO = (180° − 110°)/2 = 35°.",
      { diagram: IMG('maths-2004-q9.png') }),
    q("The shadow of a pole 5√3 m high is 5 m. Find the angle of elevation of the sun.", ["45°", "75°", "30°", "60°"], D,
      "tan θ = height/shadow = 5√3/5 = √3, so θ = 60°."),
    // 11–20 (paper question 18 left out)
    q("The locus of a point which is 5 cm from the line LM is a", ["line distance 10 cm from LM and parallel to LM", "pair of lines on opposite sides of LM and parallel to it, each distance 5 cm from LM", "line parallel to LM and 5 cm from LM", "pair of parallel lines on one side of LM and parallel to LM"], B,
      "Points 5 cm from a line lie on both sides of it: two lines parallel to LM, one on each side, each 5 cm away."),
    q("If y = 3 cos (x/3), find dy/dx when x = 3π/2.", ["1", "−3", "2", "−1"], D,
      "dy/dx = 3 × (−sin (x/3)) × 1/3 = −sin (x/3). At x = 3π/2: −sin (π/2) = −1."),
    q("Find the derivative of (2 + 3x)(1 − x) with respect to x.", ["6", "−3", "1 − 6x", "6x − 1"], C,
      "(2 + 3x)(1 − x) = 2 + x − 3x², so the derivative is 1 − 6x."),
    q("What is the rate of change of the volume v of a hemisphere with respect to its radius r when r = 2?", ["8π", "16π", "2π", "4π"], A,
      "v = ⅔πr³, so dv/dr = 2πr². At r = 2: 2π × 4 = 8π."),
    q("Find the derivative of the function y = 2x²(2x − 1) at the point x = −1.", ["18", "16", "−4", "−6"], B,
      "y = 4x³ − 2x², dy/dx = 12x² − 4x. At x = −1: 12 + 4 = 16."),
    q("Evaluate ∫_{1}^{3} (x² − 1) dx.", ["2/3", "−2/3", "−6 2/3", "6 2/3"], D,
      "∫(x² − 1) dx = x³/3 − x. [9 − 3] − [1/3 − 1] = 6 + 2/3 = 6 2/3."),
    q("Some white balls were put in a basket containing twelve red balls and sixteen black balls. If the probability of picking a white ball from the basket is 3/7, how many white balls were introduced?", ["12", "21", "28", "32"], B,
      "With w white balls, w/(w + 28) = 3/7, so 7w = 3w + 84 and w = 21."),
    q("The graph above shows the cumulative frequency curve of the distribution of marks in a class test. What percentage of the students scored more than 20 marks?", ["28%", "68%", "8%", "17%"], A,
      "The curve levels off at 25 students. At 20 marks it reads about 18, so about 25 − 18 = 7 students scored more than 20: 7/25 × 100 = 28%.",
      { diagram: IMG('maths-2004-q18.png') }),
    q("Find the mean deviation of 1, 2, 3 and 4.", ["2.5", "2.0", "1.0", "1.5"], C,
      "Mean = 10/4 = 2.5. Deviations: 1.5, 0.5, 0.5, 1.5, total 4. Mean deviation = 4/4 = 1.0."),
    q("An unbiased die is rolled 100 times and the outcome is tabulated as follows: Number 1, 2, 3, 4, 5, 6 with frequencies 13, 15, 22, 14, 20, 16 respectively. What is the probability of obtaining 5?", ["1/5", "1/2", "1/6", "1/4"], A,
      "From the table, 5 came up 20 times out of 100: probability = 20/100 = 1/5."),
    // 21–30
    q("The pie chart shows the distribution of the crops harvested from a farmland in a year. If 3000 tonnes of millet is harvested, what amount of beans is harvested?", ["6000 tonnes", "1500 tonnes", "1200 tonnes", "9000 tonnes"], C,
      "Millet 150° = 3000 t, so 1° = 20 t. Beans = 360° − 150° − 90° − 60° = 60°, so beans = 60 × 20 = 1200 tonnes.",
      { diagram: IMG('maths-2004-q21.png') }),
    q("In how many ways can 2 students be selected from a group of 5 students in a debating competition?", ["25 ways", "10 ways", "15 ways", "20 ways"], B,
      "Order does not matter: ⁵C₂ = (5 × 4)/2 = 10 ways."),
    q("The mean age of a group of students is 15 years. When the age of a teacher, 45 years old, is added to the ages of the students, the mean of their ages becomes 18 years. Find the number of students in the group.", ["9", "7", "42", "15"], A,
      "With n students: (15n + 45)/(n + 1) = 18, so 15n + 45 = 18n + 18, 3n = 27, n = 9."),
    q("A container has 30 gold medals, 22 silver medals and 18 bronze medals. If one medal is selected at random from the container, what is the probability that it is not a gold medal?", ["9/35", "11/35", "4/7", "3/7"], C,
      "Total = 70 medals; not gold = 22 + 18 = 40. Probability = 40/70 = 4/7."),
    q("A committee of six is to be formed by a state governor from nine state commissioners and three members of the state house of assembly. In how many ways can the members of the committee be chosen so as to include one member of the house of assembly?", ["378 ways", "462 ways", "840 ways", "924 ways"], A,
      "Choose 1 of the 3 assembly members and 5 of the 9 commissioners: ³C₁ × ⁹C₅ = 3 × 126 = 378."),
    q("The weights of 10 pupils in a class are 15 kg, 16 kg, 17 kg, 18 kg, 16 kg, 17 kg, 17 kg, 18 kg and 16 kg. What is the range of this distribution?", ["4", "3", "1", "2"], B,
      "Range = highest − lowest = 18 − 15 = 3. (Only nine weights are printed, but the range is the same.)"),
    q("I. Rectangular bars of equal width; II. The height of each rectangular bar is proportional to the frequency of the corresponding class interval; III. Rectangular bars have common sides with no gaps in between. A histogram is described completely by", ["I, II and III", "I and II", "II and III", "I and III"], A,
      "For equal class intervals, a histogram has bars of equal width (I), heights proportional to the frequencies (II), and adjacent bars touching with no gaps (III)."),
    q("y is inversely proportional to x and y = 4 when x = ½. Find x when y = 10.", ["2", "10", "1/5", "1/10"], C,
      "y = k/x, so k = 4 × ½ = 2. When y = 10: x = 2/10 = 1/5."),
    q("What are the integral values of x which satisfy the inequality −1 < 3 − 2x ≤ 5?", ["−1, 0, 1, 2", "−2, 1, 0, −1", "0, 1, 2", "−1, 0, 1"], D,
      "Subtract 3: −4 < −2x ≤ 2. Divide by −2 and reverse: 2 > x ≥ −1. Integers: −1, 0, 1."),
    q("The inverse of the matrix [[2, 1], [1, 1]] is", ["[[1, 1], [1, 2]]", "[[1, 1], [−1, 2]]", "[[1, −1], [−1, 2]]", "[[1, −1], [−1, 2]]"], D,
      "Determinant = 2 × 1 − 1 × 1 = 1. Swap the leading diagonal and change the signs of the others: [[1, −1], [−1, 2]]. (Options C and D are printed the same, so both are right.)",
      { keyVerdict: 'multiple', alsoAccept: [C], keyAnswer: 'D', answerNote: "The inverse is [[1, −1], [−1, 2]] (determinant 1). The paper prints this same matrix as both option C and option D, so C is accepted as well as the key's D." }),
    // 31–40
    q("Find the values of x where the curve y = x³ + 2x² − 5x − 6 crosses the x-axis.", ["−2, 1 and −3", "2, −1 and −3", "2, 1 and 3", "−2, −1 and 3"], B,
      "x = −1 gives −1 + 2 + 5 − 6 = 0, so (x + 1) is a factor: x³ + 2x² − 5x − 6 = (x + 1)(x − 2)(x + 3). Roots: 2, −1, −3."),
    q("Given that the first and fourth terms of a G.P. are 6 and 162 respectively, find the sum of the first three terms of the progression.", ["27", "8", "78", "48"], C,
      "ar³ = 162 and a = 6, so r³ = 27 and r = 3. First three terms: 6 + 18 + 54 = 78."),
    q("The shaded area in the diagram is represented by (the boundary line passes through (0, 6) and (2, 0))", ["{(x, y): y − 3 < −6}", "{(x, y): y + 3x < 6}", "{(x, y): y + 3x < −6}", "{(x, y): y − 3x < 6}"], B,
      "The line through (0, 6) and (2, 0) has gradient −3: y = 6 − 3x, i.e. y + 3x = 6. The shading is below the line (it contains the origin, 0 < 6), so y + 3x < 6.",
      { diagram: IMG('maths-2004-q33.png') }),
    q("If the operation * in the set of integers is defined by p * q = √(pq), find the value of 4 * (8 * 32).", ["8", "3", "16", "4"], A,
      "8 * 32 = √256 = 16. Then 4 * 16 = √64 = 8."),
    q("Find the remainder when 3x³ + 5x² − 11x + 4 is divided by x + 3.", ["−4", "4", "1", "−1"], C,
      "Remainder theorem: f(−3) = 3(−27) + 5(9) − 11(−3) + 4 = −81 + 45 + 33 + 4 = 1."),
    q("The nth terms of two sequences are Q_{n} = 3 · 2^{n−2} and U_{m} = 3 · 2^{2m−3}. Find the product of Q_{2} and U_{2}.", ["18", "12", "6", "3"], A,
      "Q_{2} = 3 · 2^{0} = 3 and U_{2} = 3 · 2^{1} = 6. Product = 18."),
    q("If P = [[1, 0, −1], [3, 4, 5], [−1, 0, 1]], then |P| is", ["4", "8", "−8", "0"], D,
      "Expand along the top row: |P| = 1 × (4 × 1 − 5 × 0) − 0 + (−1) × (3 × 0 − 4 × (−1)) = 4 − 4 = 0."),
    q("Factorize completely ac − 2bc − a² + 4b².", ["(a − 2b)(c − a − 2b)", "(a − 2b)(c + a + 2b)", "(a − 2b)(c + a + 2b)", "(a − 2b)(c + a − 2b)"], A,
      "Group: c(a − 2b) − (a² − 4b²) = c(a − 2b) − (a − 2b)(a + 2b) = (a − 2b)(c − a − 2b)."),
    q("Find the sum to infinity of the series ½, 1/6, 1/18, …", ["2/3", "1/3", "3/4", "1"], C,
      "a = ½, r = (1/6) ÷ (½) = 1/3. S∞ = a/(1 − r) = ½ ÷ ⅔ = 3/4."),
    q("The length L of a simple pendulum varies directly as the square root of its period T. If a pendulum with period 4 sec is 64 cm long, find the length of a pendulum whose period is 9 seconds.", ["96 cm", "324 cm", "36 cm", "324 cm"], A,
      "L = k√T: 64 = k × 2, so k = 32. When T = 9: L = 32 × 3 = 96 cm."),
    // 41–50
    q("Find x and y respectively in the subtraction 4243 − 13x4 = y344, carried out in base 5 (x and y are single digits).", ["4, 2", "2, 4", "4, 3", "3, 2"], A,
      "Units: 3 − 4 needs a borrow: 8 − 4 = 4. Fives: 4 − 1 = 3, and 3 − x = 4 needs a borrow: 8 − x = 4, x = 4. Twenty-fives: 2 − 1 = 1, borrow: 6 − 3 = 3. Last: 4 − 1 − 1 = 2 = y."),
    q("Three teachers shared a packet of chalk. The first teacher got 2/5 of the chalk and the second teacher received 2/15 of the remainder. What fraction did the third teacher receive?", ["8/15", "11/25", "12/25", "13/25"], D,
      "Remainder after the first = 3/5. Second gets 2/15 × 3/5 = 2/25. Third = 3/5 − 2/25 = 15/25 − 2/25 = 13/25."),
    q("If 6 log_{x} 2 − 3 log_{x} 3 = 3 log_{5} 0.2, find x.", ["8/3", "4/3", "3/4", "3/8"], C,
      "Right side: log_{5} 0.2 = log_{5} 5^{−1} = −1, so it is −3. Left side: log_{x} (2^{6}/3^{3}) = log_{x} (64/27). So x^{−3} = 64/27, x³ = 27/64, x = 3/4."),
    q("Find p, if 451_{6} − p_{7} = 305_{6}.", ["62_{7}", "116_{7}", "611_{7}", "142_{7}"], B,
      "451_{6} = 144 + 30 + 1 = 175 and 305_{6} = 108 + 0 + 5 = 113, so p = 62 in base ten. 62 = 1 × 49 + 1 × 7 + 6 = 116_{7}."),
    q("In a class of 40 students, each student offers at least one of Physics and Chemistry. If the number of students that offer Physics is three times the number that offers both subjects and the number that offers Chemistry is twice the number that offers Physics, find the number of students that offer Physics only.", ["15", "25", "5", "10"], D,
      "Let both = b: Physics = 3b, Chemistry = 6b. 3b + 6b − b = 40, so b = 5 and Physics = 15. Physics only = 15 − 5 = 10."),
    q("Given that ∛(4^{2x}) = 16, find the value of x.", ["4", "6", "3", "2"], C,
      "4^{2x/3} = 16 = 4², so 2x/3 = 2 and x = 3."),
    q("Evaluate (1/10 × 2/3 + 1/4)/(1/2 ÷ 3/5 − 1/4).", ["7/12", "19/35", "2/25", "19/60"], B,
      "Numerator: 1/15 + 1/4 = 19/60. Denominator: 5/6 − 1/4 = 7/12. (19/60) ÷ (7/12) = 19/60 × 12/7 = 19/35."),
    q("The shaded region in the Venn diagram is", ["P^{c} ∪ (Q ∩ R)", "P^{c} ∩ (Q ∪ R)", "P ∩ Q", "P^{c} ∩ (Q ∩ R)"], D,
      "The shaded part lies inside both Q and R but outside P: P^{c} ∩ (Q ∩ R).",
      { diagram: IMG('maths-2004-q48.png') }),
    q("Simplify 1/(√3 + 2) in the form a + b√3.", ["2 − √3", "−2 − √3", "2 + √3", "−2 + √3"], A,
      "Multiply top and bottom by 2 − √3: (2 − √3)/(4 − 3) = 2 − √3."),
    q("A farmer planted 5,000 grains of maize and harvested 5,000 cobs, each bearing 500 grains. What is the ratio of the number of grains sowed to the number harvested?", ["1 : 250,000", "1 : 25,000", "1 : 500", "1 : 5,000"], C,
      "Harvested = 5,000 × 500 = 2,500,000 grains. Ratio = 5,000 : 2,500,000 = 1 : 500."),
  ]);
})();
