#!/usr/bin/env python3
"""Rebuild imported-questions.js from every approved paper.

    python3 tools/paper-import/add_to_bank.py

Reads imports/approved/*.json (written by the review page's Approve button)
and regenerates imported-questions.js, which index.html loads right after
questions.js. Re-approving a paper replaces it; deleting its approved file
and re-running this removes it from the app.
"""

import glob
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..'))
OUT = os.path.join(REPO, 'imported-questions.js')


def check(q, where):
    ok = (isinstance(q.get('question'), str) and q['question'].strip()
          and isinstance(q.get('options'), list) and len(q['options']) >= 2
          and isinstance(q.get('answer'), int) and 0 <= q['answer'] < len(q['options']))
    if not ok:
        sys.exit(f'{where}: question {q.get("number")} is incomplete — re-open the review page and approve again.')


def main():
    files = sorted(glob.glob(os.path.join(REPO, 'imports', 'approved', '*.json')))
    by_subject, total = {}, 0
    for path in files:
        paper = json.load(open(path))
        subject, year = paper['subject'], paper['year']
        entries = []
        for k, b in enumerate(paper['blocks'], 1):
            if b['type'] == 'passage':
                for q in b['questions']:
                    check(q, os.path.basename(path))
                entries.append({
                    'passageId': f'{subject}-{year}-{re.sub(r"[^a-z0-9]+", "", b["title"].lower()) or "p"}-{k}',
                    'passageTitle': b['title'], 'instruction': b.get('instruction', ''),
                    'year': year, 'passage': b['text'],
                    'questions': [{'question': q['question'], 'options': q['options'], 'answer': q['answer'],
                                   'explanation': '', 'year': year} for q in b['questions']],
                })
                total += len(b['questions'])
            else:
                q = b['question']
                check(q, os.path.basename(path))
                entries.append({'question': q['question'], 'options': q['options'], 'answer': q['answer'],
                                'explanation': '', 'year': year})
                total += 1
        by_subject.setdefault(subject, []).extend(entries)
        print(f'  {os.path.basename(path)}: {len(entries)} entries')

    body = json.dumps(by_subject, ensure_ascii=False, indent=1)
    with open(OUT, 'w') as f:
        f.write('/* AUTO-GENERATED by tools/paper-import/add_to_bank.py from imports/approved/*.json.\n'
                '   Do not edit by hand — fix the paper on the review page and re-run the script.\n'
                '   Adds reviewed, imported past papers to QUESTION_BANK (loaded after questions.js). */\n'
                '(function (bank, add) {\n'
                '  Object.keys(add).forEach(function (s) { bank[s] = (bank[s] || []).concat(add[s]); });\n'
                f'}})(QUESTION_BANK, {body});\n')
    print(f'imported-questions.js rebuilt: {total} questions from {len(files)} paper(s).')
    print('Next: commit and push (git add -A && git commit -m "Add imported papers" && git push),\n'
          'then run the "Generate Teach Me explanations" workflow to explain the new questions.')


if __name__ == '__main__':
    main()
