/**
 * Topic lessons for mathematics ("Learn the topic" under Teach Me), written in
 * advance like the Teach Me explanations: instant, offline, free. 'of' maps
 * each question (passageId|question|options) to its lesson.
 */
(window.TEACH_TOPICS = window.TEACH_TOPICS || {})["mathematics"] = {
 "lessons": {
  "number-bases": {
   "title": "Number bases: converting and calculating",
   "body": "JAMB tests converting between bases and doing simple arithmetic in a base.\n\nConverting TO base ten: multiply each digit by the base raised to its place value, then add.\n• 1011_{2} = 1×2^{3} + 0×2^{2} + 1×2^{1} + 1×2^{0} = 8 + 0 + 2 + 1 = 11.\n• 214_{5} = 2×25 + 1×5 + 4 = 59.\n\nConverting FROM base ten: divide repeatedly by the new base and read the remainders from the bottom up.\n• 59 in base 5: 59 ÷ 5 = 11 r 4, 11 ÷ 5 = 2 r 1, 2 ÷ 5 = 0 r 2 → 214_{5}.\n\nBetween two bases that are not ten, go through base ten.\n\nFinding an unknown base: if 25_{x} = 17_{10}, then 2x + 5 = 17, so x = 6.\n\nArithmetic in a base: work as usual, but \"carry\" when you reach the base. In base 5, 4 + 3 = 7 = 1×5 + 2, so write 2, carry 1.\n\nCommon traps:\n• A digit can never equal or exceed the base (no 5 in base 5). Use this to rule out options fast.\n• The right-hand digit has place value base^{0} = 1, not the base.\n\nMemory tip: \"multiply and add\" to get into base ten; \"divide and read remainders upwards\" to get out."
  },
  "fractions-decimals": {
   "title": "Fractions, decimals and approximation",
   "body": "Fractions: to add or subtract, use a common denominator; to multiply, multiply tops and bottoms; to divide, multiply by the reciprocal. Simplify mixed numbers into improper fractions first.\n\nDecimal places (d.p.) count digits after the point; significant figures (s.f.) count from the first non-zero digit.\n• 0.012856 to 3 s.f. = 0.0129; to 4 d.p. = 0.0129.\n• 52 461 to 2 s.f. = 52 000.\nRounding rule: look at the next digit; 5 or more rounds up.\n\nStandard form: A × 10^{n} with 1 ≤ A < 10. 0.00054 = 5.4 × 10^{-4}; 37 000 = 3.7 × 10^{4}.\n\nLong calculations without tables: write each number in standard form, group the powers of ten, and cancel before multiplying.\n\nPercentage error = (error ÷ actual value) × 100%.\n\nCommon traps:\n• Counting leading zeros as significant figures (they are not).\n• Rounding in the middle of a calculation; round only at the end.\n\nMemory tip: significant figures start at the first non-zero digit; decimal places start at the point."
  },
  "indices": {
   "title": "Laws of indices",
   "body": "The laws (same base a):\n• a^{m} × a^{n} = a^{m+n}\n• a^{m} ÷ a^{n} = a^{m−n}\n• (a^{m})^{n} = a^{mn}\n• a^{0} = 1\n• a^{−n} = 1/a^{n}\n• a^{1/n} = ⁿ√a, and a^{m/n} = (ⁿ√a)^{m}\n\nEvaluating: take the root first, then the power. 27^{2/3} = (∛27)^{2} = 3^{2} = 9. 16^{−3/4} = 1/(⁴√16)^{3} = 1/8.\n\nSolving index equations: make the bases the same, then equate the powers.\n• 2^{x+1} = 32 = 2^{5} → x + 1 = 5 → x = 4.\n• 9^{x} = 27 → 3^{2x} = 3^{3} → x = 3/2.\nIf two different bases appear, write both as powers of a common prime (4 = 2^{2}, 8 = 2^{3}, 9 = 3^{2}, 27 = 3^{3}).\n\nCommon traps:\n• a^{m} + a^{n} is NOT a^{m+n}; only multiplication adds powers.\n• A negative power gives a reciprocal, not a negative number: 2^{−3} = 1/8.\n\nMemory tip: \"root first, then power\" for fractional indices; \"same base, then equate powers\" for equations."
  },
  "logarithms": {
   "title": "Logarithms",
   "body": "Definition: log_{a} b = c means a^{c} = b. So log_{2} 8 = 3, log_{10} 0.01 = −2, log_{a} a = 1, log_{a} 1 = 0.\n\nLaws (same base):\n• log x + log y = log (xy)\n• log x − log y = log (x/y)\n• log x^{n} = n log x\n• Change of base: log_{a} b = log b / log a\n\nSimplifying: collect logs into a single log, then evaluate.\n• log_{3} 18 − log_{3} 2 = log_{3} 9 = 2.\n• 2 log 5 + log 4 = log 25 + log 4 = log 100 = 2 (base 10).\n\nSolving log equations: combine into one log, convert to index form, then CHECK the answer makes every original log defined (the inside of a log must be positive).\n• log_{2} x + log_{2} (x − 2) = 3 → x(x − 2) = 8 → x = 4 (reject x = −2).\n\nUsing tables/characteristics (older papers): the characteristic is the power of ten in standard form; a bar shows a negative characteristic, e.g. log 0.05 = 2̄.6990.\n\nCommon traps:\n• log (x + y) is NOT log x + log y.\n• Forgetting to reject solutions that make a log of a negative number.\n\nMemory tip: a log is just \"what power?\" — log_{a} b asks \"a to what power gives b?\""
  },
  "surds": {
   "title": "Surds",
   "body": "A surd is a root that cannot be simplified to a whole number, like √2.\n\nSimplify by taking out square factors: √72 = √(36 × 2) = 6√2. √48 = 4√3.\n\nAdd and subtract only like surds: 3√2 + 5√2 = 8√2. First simplify: √50 + √18 = 5√2 + 3√2 = 8√2.\n\nMultiply: √a × √b = √(ab); (√a)^{2} = a. Expand brackets as in algebra, e.g. (√3 + √5)(√3 − √5) = 3 − 5 = −2.\n\nRationalise the denominator:\n• 1/√2 = √2/2.\n• For a + √b, multiply top and bottom by its conjugate a − √b: 1/(2 + √3) = (2 − √3)/(4 − 3) = 2 − √3.\n\nCommon traps:\n• √a + √b is NOT √(a + b).\n• Forgetting that (√a + √b)^{2} = a + b + 2√(ab), not just a + b.\n\nMemory tip: to clear a surd from the bottom, multiply by its \"partner with the opposite sign\"."
  },
  "commercial": {
   "title": "Percentages, profit and loss, interest and ratio",
   "body": "Percentage of: 15% of ₦4,000 = 0.15 × 4000 = ₦600.\nPercentage change = (change ÷ original) × 100%.\n\nProfit and loss are percentages of the COST price:\n• Profit % = (SP − CP)/CP × 100%. Selling at a 25% loss means SP = 75% of CP.\n• To find CP from SP: CP = SP × 100/(100 ± %). E.g. SP ₦180,000 at a 25% loss → CP = 180000 × 100/75 = ₦240,000.\n\nSimple interest: I = PRT/100. Amount = P + I.\nCompound interest: A = P(1 + r/100)^{n}. Depreciation: A = P(1 − r/100)^{n}.\n\nRatio and sharing: to share ₦600 in the ratio 2 : 3, total parts = 5, so shares are 240 and 360.\nProportion: if 5 men take 45 days, then (inverse) 25 men take 45 × 5/25 = 9 days.\n\nShares and dividends, commission and discount use the same idea: a percentage of the right base amount.\n\nCommon traps:\n• Taking profit or loss as a percentage of the selling price.\n• Adding percentages that apply one after another; a 10% rise then a 10% fall is a 1% fall overall.\n\nMemory tip: always ask \"percentage OF WHAT?\" — the original amount is the base."
  },
  "variation": {
   "title": "Variation",
   "body": "• Direct: y ∝ x → y = kx. If x doubles, y doubles.\n• Inverse: y ∝ 1/x → y = k/x. If x doubles, y halves.\n• Joint: y ∝ xz → y = kxz.\n• Partial: y is partly constant and partly varies with x → y = a + bx (two unknowns, so you need two pairs of values).\nPowers and roots: \"y varies as the square of x\" → y = kx^{2}; \"inversely as the square root of x\" → y = k/√x.\n\nMethod (always the same):\n1. Write the equation with k.\n2. Use the given pair of values to find k.\n3. Use k to find the unknown.\n\nExample: y varies inversely as x^{2}; y = 4 when x = 3. Then 4 = k/9, k = 36. When x = 6, y = 36/36 = 1.\n\nCommon traps:\n• Mixing up direct and inverse.\n• For partial variation, forgetting the constant term.\n\nMemory tip: \"find k first\" — every variation question is solved by finding the constant."
  },
  "sets": {
   "title": "Sets and Venn diagrams",
   "body": "Notation: ∪ union (in either), ∩ intersection (in both), A′ complement (not in A), ⊂ subset, ∅ empty set, n(A) number of elements.\n\nTwo sets: n(A ∪ B) = n(A) + n(B) − n(A ∩ B).\nExample: 220 students take Biology or Maths; 125 take Biology and 110 take Maths. Both = 125 + 110 − 220 = 15, so Biology only = 125 − 15 = 110.\n\nThree sets: draw a Venn diagram and fill it from the CENTRE outwards: first all three, then each pair (minus the centre), then each \"only\" region. Use x for the unknown region and form one equation from the total.\n\nNumber of subsets of a set with n elements = 2^{n} (including ∅ and the set itself); proper subsets = 2^{n} − 1.\n\nCommon traps:\n• Forgetting to subtract the overlap, so elements in both sets are counted twice.\n• Confusing \"only A\" with \"A\".\n\nMemory tip: in Venn questions, fill the middle first and work outwards."
  },
  "algebra": {
   "title": "Algebraic expressions and functions",
   "body": "Expanding: (a + b)^{2} = a^{2} + 2ab + b^{2}; (a − b)^{2} = a^{2} − 2ab + b^{2}; (a + b)(a − b) = a^{2} − b^{2}.\n\nFactorising: take out common factors first; spot the difference of two squares; for ax^{2} + bx + c, find two numbers with product ac and sum b.\n\nAlgebraic fractions: factorise top and bottom, then cancel common FACTORS (never terms). Add with a common denominator.\n\nChange of subject: undo the operations around the required letter in reverse order, doing the same to both sides.\n• From T = 2π√(l/g): T/(2π) = √(l/g) → T^{2}/(4π^{2}) = l/g → l = gT^{2}/(4π^{2}).\n\nFunctions: f(x) = 2x + 3 means f(4) = 11. Composite f(g(x)): put g(x) into f. Inverse f^{−1}: swap x and y and solve for y.\n\nRemainder and factor theorems: the remainder when f(x) is divided by (x − a) is f(a); (x − a) is a factor if f(a) = 0.\n\nCommon traps:\n• Cancelling terms instead of factors: (x + 2)/2 is not x + 1.\n• Sign errors when expanding a minus outside a bracket.\n\nMemory tip: factorise before you cancel, and substitute to check."
  },
  "equations": {
   "title": "Linear and simultaneous equations",
   "body": "Linear: collect x-terms on one side and numbers on the other. With fractions, multiply every term by the LCM of the denominators first.\n\nSimultaneous equations:\n• Elimination: make the coefficients of one letter equal, then add or subtract the equations.\n• Substitution: make one letter the subject of one equation and substitute into the other.\nExample: 2x + y = 7 and x − y = 2 → adding gives 3x = 9, x = 3, y = 1.\n\nWord problems: let x be the unknown, write the equation from the words, solve, and answer the question asked.\n\nChecking: substitute your answers into BOTH original equations. In a JAMB question you can also test each option.\n\nCommon traps:\n• Multiplying only some terms by the LCM.\n• Answering x when the question asks for y, or for x + y.\n\nMemory tip: with four options, substituting each option back is often the fastest method."
  },
  "quadratics": {
   "title": "Quadratic equations",
   "body": "Standard form: ax^{2} + bx + c = 0.\n\nSolving:\n• Factorisation: x^{2} − 5x + 6 = 0 → (x − 2)(x − 3) = 0 → x = 2 or 3.\n• Formula: x = [−b ± √(b^{2} − 4ac)]/(2a).\n• Completing the square.\n\nRoots α and β: α + β = −b/a, αβ = c/a. The equation with roots α and β is x^{2} − (α + β)x + αβ = 0.\nExample: roots 2 and −3 → x^{2} + x − 6 = 0.\nUseful: α^{2} + β^{2} = (α + β)^{2} − 2αβ.\n\nThe discriminant b^{2} − 4ac: positive → two real roots; zero → equal roots; negative → no real roots.\n\nCubics in JAMB: find one root by testing small numbers (f(1), f(−1), …), then factorise. For x^{3} − 5x^{2} − x + 5 = 0, f(1) = 0, f(−1) = 0, f(5) = 0, so x = 1, −1 or 5.\n\nCommon traps:\n• Sign of the sum: α + β = −b/a (note the minus).\n• Dividing both sides by x and losing the root x = 0.\n\nMemory tip: \"sum = −b/a, product = c/a\"."
  },
  "inequalities": {
   "title": "Inequalities and linear programming",
   "body": "Solve like equations, EXCEPT: multiplying or dividing by a negative number reverses the sign.\n• −3x > 6 → x < −2.\n\nDouble inequalities: do the same to all three parts. −1 < 2x + 3 ≤ 7 → −4 < 2x ≤ 4 → −2 < x ≤ 2.\n\nQuadratic inequalities: find the roots, then test a value in each region. (x − 1)(x − 4) < 0 → 1 < x < 4.\n\nOn a number line or graph: an open circle or dotted line = strict (< or >); a closed circle or solid line = ≤ or ≥.\n\nLinear programming: graph each inequality, find the region satisfying all of them, then test the corners of that region in the objective (e.g. maximise P = 3x + 2y). The maximum or minimum is always at a corner.\n\nTo find an inequality from a shaded graph: get the line's equation from two points, then test a point inside the region (like (0, 0)) to choose the sign.\n\nCommon traps:\n• Forgetting to flip the sign when dividing by a negative.\n• Testing a point that lies on the boundary line.\n\nMemory tip: negative multiplier → flip the sign; in linear programming, the answer lives at a corner."
  },
  "sequences": {
   "title": "Sequences: AP and GP",
   "body": "Arithmetic progression (AP): constant difference d.\n• nth term: T_{n} = a + (n − 1)d\n• Sum: S_{n} = n/2 [2a + (n − 1)d] = n/2 (first + last)\n\nGeometric progression (GP): constant ratio r.\n• nth term: T_{n} = ar^{n−1}\n• Sum: S_{n} = a(r^{n} − 1)/(r − 1)\n• Sum to infinity (only when −1 < r < 1): S_{∞} = a/(1 − r)\n\nFrom a sum formula: T_{n} = S_{n} − S_{n−1}.\nMeans: the arithmetic mean of a and b is (a + b)/2; the geometric mean is √(ab).\n\nFinding a and d (or r): turn the two facts into two equations. E.g. T_{3} = 7 and T_{7} = 19 → 4d = 12, d = 3, a = 1.\n\nCommon traps:\n• Using n instead of (n − 1) in the nth-term formula.\n• Using the sum to infinity when |r| ≥ 1.\n\nMemory tip: AP = adding the same number; GP = multiplying by the same number."
  },
  "matrices": {
   "title": "Matrices and determinants",
   "body": "Adding and subtracting: matrices must be the same size; combine matching entries.\n\nMultiplying: row × column. A (2 × 3) times a (3 × 2) gives a 2 × 2. The number of columns of the first must equal the number of rows of the second. In general AB ≠ BA.\n\n2 × 2 matrix with rows (a, b) and (c, d):\n• Determinant = ad − bc.\n• Inverse = 1/(ad − bc) × [rows (d, −b) and (−c, a)]. Swap a and d, negate b and c, divide by the determinant.\n• A matrix with determinant 0 is singular and has no inverse.\n\n3 × 3 determinant: expand along the top row with alternating signs + − +, using the 2 × 2 determinants of the minors.\n\nSolving simultaneous equations with matrices: X = A^{−1}B, or use Cramer's rule.\n\nCommon traps:\n• Sign errors in the alternating + − + pattern.\n• Assuming AB = BA.\n\nMemory tip: inverse of a 2 × 2 is \"swap the diagonal, negate the others, divide by the determinant\"."
  },
  "binary-operations": {
   "title": "Binary operations",
   "body": "A binary operation * combines two elements using a given rule, e.g. a * b = a + b + 2ab.\n\nEvaluating: substitute carefully. With that rule, 2 * 3 = 2 + 3 + 12 = 17. Work out brackets first: (1 * 2) * 3.\n\nProperties:\n• Closure: the result is always in the set.\n• Commutative: a * b = b * a for all a, b.\n• Associative: (a * b) * c = a * (b * c).\n• Identity e: a * e = a for every a. Solve a * e = a for e.\n• Inverse of a: the element a^{−1} with a * a^{−1} = e.\n\nExample: for a * b = a + b + 2ab, a * e = a gives e + 2ae = 0, so e = 0. The inverse of a satisfies a + x + 2ax = 0, so x = −a/(1 + 2a).\n\nTables: the identity's row repeats the header row; check symmetry about the main diagonal for commutativity.\n\nCommon traps:\n• Treating * as ordinary multiplication.\n• Finding the inverse before finding the identity.\n\nMemory tip: identity first (a * e = a), then inverse (a * x = e)."
  },
  "geometry": {
   "title": "Angles, polygons, triangles and circles",
   "body": "Angles: on a straight line add to 180°; at a point add to 360°; vertically opposite angles are equal. With parallel lines: corresponding angles are equal, alternate angles are equal, co-interior angles add to 180°.\n\nTriangles: angles add to 180°; an exterior angle equals the sum of the two interior opposite angles. Isosceles: base angles are equal. Similar triangles: corresponding sides are in the same ratio.\n\nPolygons (n sides): interior angles add to (n − 2) × 180°; exterior angles add to 360°. Each exterior angle of a regular polygon = 360°/n.\n\nCircle theorems:\n• The angle at the centre is twice the angle at the circumference on the same arc.\n• Angles in the same segment are equal.\n• The angle in a semicircle is 90°.\n• Opposite angles of a cyclic quadrilateral add to 180°.\n• A tangent is perpendicular to the radius at the point of contact; two tangents from a point are equal.\n• Alternate segment theorem: the angle between a tangent and a chord equals the angle in the alternate segment.\n\nLoci: points a fixed distance from a point form a circle; equidistant from two points form the perpendicular bisector; equidistant from two lines form the angle bisector.\n\nMemory tip: in circle questions, mark the centre and radii first; most answers come from isosceles triangles and \"centre = 2 × circumference\"."
  },
  "mensuration": {
   "title": "Lengths, areas and volumes",
   "body": "Plane shapes:\n• Rectangle A = lb; triangle A = ½bh = ½ab sin C; parallelogram A = bh; trapezium A = ½(a + b)h.\n• Circle: C = 2πr, A = πr^{2}.\n• Arc length = (θ/360) × 2πr; sector area = (θ/360) × πr^{2}.\n\nSolids:\n• Cuboid V = lbh; cylinder V = πr^{2}h, curved surface = 2πrh.\n• Cone V = ⅓πr^{2}h, curved surface = πrl (l = slant height, l^{2} = r^{2} + h^{2}).\n• Sphere V = 4/3 πr^{3}, surface = 4πr^{2}. Pyramid V = ⅓ × base area × height.\n• Frustum = big cone − small cone.\n\nA sector folded into a cone: the arc length becomes the base circumference, and the sector radius becomes the slant height.\n\nSimilar shapes: if lengths scale by k, areas scale by k^{2} and volumes by k^{3}.\n\nCommon traps:\n• Using the diameter instead of the radius.\n• Mixing units (cm and m) in one calculation.\n\nMemory tip: check units: length (cm), area (cm²), volume (cm³). The answer's unit tells you which formula family you need."
  },
  "coordinate": {
   "title": "Coordinate geometry of straight lines",
   "body": "For points (x_{1}, y_{1}) and (x_{2}, y_{2}):\n• Gradient m = (y_{2} − y_{1})/(x_{2} − x_{1}).\n• Distance = √[(x_{2} − x_{1})^{2} + (y_{2} − y_{1})^{2}].\n• Midpoint = ((x_{1} + x_{2})/2, (y_{1} + y_{2})/2).\n\nEquation of a line: y = mx + c (c = y-intercept), or y − y_{1} = m(x − x_{1}).\nFrom ax + by + c = 0, the gradient is −a/b.\n\nParallel lines have equal gradients. Perpendicular lines: m_{1} × m_{2} = −1.\n\nGradient of a curve at a point = gradient of the tangent there (use differentiation).\n\nIntercepts: put x = 0 to find the y-intercept; put y = 0 to find the x-intercept.\n\nCommon traps:\n• Subtracting coordinates in different orders on the top and bottom of the gradient.\n• Forgetting the minus sign in −a/b.\n\nMemory tip: gradient = \"rise over run\"; perpendicular = \"flip and change the sign\"."
  },
  "trigonometry": {
   "title": "Trigonometry",
   "body": "Right-angled triangles: SOH CAH TOA. sin θ = opposite/hypotenuse, cos θ = adjacent/hypotenuse, tan θ = opposite/adjacent.\n\nSpecial angles: sin 30° = ½, cos 30° = √3/2, tan 30° = 1/√3; sin 45° = cos 45° = 1/√2, tan 45° = 1; sin 60° = √3/2, cos 60° = ½, tan 60° = √3.\n\nSigns by quadrant (All, Sin, Tan, Cos for quadrants 1–4): only sin is positive between 90° and 180°, so sin 150° = sin 30° = ½ but cos 150° = −√3/2.\n\nIdentities: sin^{2} θ + cos^{2} θ = 1; tan θ = sin θ/cos θ. If sin θ = 3/5 (acute), draw a 3-4-5 triangle: cos θ = 4/5, tan θ = 3/4.\n\nAny triangle: sine rule a/sin A = b/sin B; cosine rule a^{2} = b^{2} + c^{2} − 2bc cos A; area = ½ab sin C.\n\nBearings are measured clockwise from north, written with three figures (e.g. 060°). Angles of elevation and depression are measured from the horizontal.\n\nCommon traps:\n• Calculator in the wrong mode, or forgetting the quadrant sign.\n• Measuring a bearing from the wrong point.\n\nMemory tip: draw the triangle; for an acute angle given as a fraction, use a Pythagorean triple (3-4-5, 5-12-13)."
  },
  "differentiation": {
   "title": "Differentiation",
   "body": "Power rule: d/dx (x^{n}) = nx^{n−1}. Constants differentiate to 0.\n• y = 3x^{2} − 2x + 5 → dy/dx = 6x − 2.\n\nStandard results: d/dx (sin x) = cos x; d/dx (cos x) = −sin x; d/dx (e^{x}) = e^{x}; d/dx (ln x) = 1/x.\n\nRules:\n• Chain rule: d/dx f(g(x)) = f′(g(x)) × g′(x). E.g. y = sin^{2} 5x → dy/dx = 2 sin 5x × cos 5x × 5 = 10 sin 5x cos 5x.\n• Product rule: (uv)′ = u′v + uv′. Quotient rule: (u/v)′ = (u′v − uv′)/v^{2}.\n\nUses:\n• The gradient of the tangent at a point = dy/dx at that x.\n• Turning points: dy/dx = 0; the second derivative tells max (negative) or min (positive).\n• Rates of change: dA/dt = dA/dr × dr/dt. E.g. A = πr^{2}, r = 5, dr/dt = 0.2 → dA/dt = 2π(5)(0.2) = 2π.\n\nCommon traps:\n• Forgetting the \"inner derivative\" in the chain rule.\n• Writing d/dx(cos x) = sin x (it is −sin x).\n\nMemory tip: \"power down in front, reduce the power by one\", then multiply by the inside's derivative."
  },
  "integration": {
   "title": "Integration",
   "body": "Integration reverses differentiation.\n\nPower rule: ∫ x^{n} dx = x^{n+1}/(n + 1) + C (n ≠ −1). ∫ 1/x dx = ln x + C.\nStandard results: ∫ sin x dx = −cos x + C; ∫ cos x dx = sin x + C; ∫ e^{x} dx = e^{x} + C.\nWith ax inside: ∫ sin 3x dx = −⅓ cos 3x + C (divide by the coefficient of x).\n\nDefinite integrals: ∫_{a}^{b} f(x) dx = F(b) − F(a). No + C is needed.\n• ∫_{0}^{2} 3x^{2} dx = [x^{3}] from 0 to 2 = 8.\n\nArea under a curve between x = a and x = b = ∫_{a}^{b} y dx. A region below the x-axis gives a negative value; take its size.\n\nFinding y from dy/dx: integrate, then use the given point to find C.\n\nCommon traps:\n• Dividing by n instead of n + 1.\n• Forgetting the minus sign in ∫ sin x dx = −cos x.\n\nMemory tip: to check an integral, differentiate your answer; you should get back the original."
  },
  "statistics": {
   "title": "Statistics",
   "body": "Measures of central tendency:\n• Mean = Σx/n; for a frequency table, mean = Σfx/Σf.\n• Median: the middle value when the data are arranged in order (average the two middle values for an even count).\n• Mode: the most frequent value.\n\nSpread:\n• Range = highest − lowest.\n• Variance = Σ(x − x̄)^{2}/n; standard deviation = √variance.\n• Mean deviation = Σ|x − x̄|/n.\n\nGrouped data: use class mid-points as x. Cumulative frequency curves (ogives) give the median (at n/2) and quartiles (at n/4 and 3n/4); interquartile range = Q_{3} − Q_{1}.\n\nCharts: in a pie chart, a sector angle = (frequency/total) × 360°. Histograms use areas; for equal class widths, bar heights show frequencies.\n\nCommon traps:\n• Forgetting to sort the data before finding the median.\n• Using Σx/n instead of Σfx/Σf for a frequency table.\n\nMemory tip: the mean uses every value; the median uses position; the mode uses frequency."
  },
  "probability": {
   "title": "Probability",
   "body": "P(event) = number of favourable outcomes ÷ total number of equally likely outcomes. 0 ≤ P ≤ 1, and P(not A) = 1 − P(A).\n\nAND (independent events): multiply. P(two heads) = ½ × ½ = ¼.\nOR (mutually exclusive events): add. P(a 2 or a 5 on a die) = 1/6 + 1/6 = 1/3.\nIn general, P(A or B) = P(A) + P(B) − P(A and B).\n\nWithout replacement, the second probability changes: from 5 red and 3 blue, P(two reds) = 5/8 × 4/7 = 5/14.\n\nTwo dice: there are 36 outcomes. List them in a 6 × 6 table for sums and differences (a sum of 7 occurs 6 times, so P = 1/6).\n\n\"At least one\": P(at least one) = 1 − P(none).\n\nCommon traps:\n• Adding when you should multiply (AND = multiply).\n• Forgetting to reduce the totals when items are not replaced.\n\nMemory tip: AND → ×, OR → +, \"at least one\" → 1 − none."
  },
  "permutations": {
   "title": "Permutations and combinations",
   "body": "Factorial: n! = n × (n − 1) × … × 1; 0! = 1.\n\nPermutations (order matters): ⁿP_{r} = n!/(n − r)!. The ways to arrange 3 of 5 books on a shelf = 5 × 4 × 3 = 60.\nCombinations (order does not matter): ⁿC_{r} = n!/[r!(n − r)!]. The ways to choose 3 of 5 students = 10.\n\nArranging letters with repeats: divide by the factorial of each repeat. In \"ADDED\", 5!/(3!) = 20 (three Ds).\n\nCommittees with conditions: multiply the choices from each group. 2 men from 5 and 1 woman from 4 = ⁵C_{2} × ⁴C_{1} = 10 × 4 = 40.\n\nCircular arrangements of n objects: (n − 1)!.\n\nCommon traps:\n• Using permutations when the order does not matter (committees and selections are combinations).\n• Forgetting to divide for repeated letters.\n\nMemory tip: \"arrange → permutation; choose → combination\"."
  }
 },
 "of": {
  "|Simplify: (√3 + √5)(√3 − √5)|−2|2|−8|8": "surds",
  "|If 2^(x+1) = 32, find x.|3|4|5|6": "indices",
  "|Factorize completely: 6x² + 7x − 3|(3x − 1)(2x + 3)|(6x − 1)(x + 3)|(3x + 1)(2x − 3)|(2x + 3)(3x − 1)": "algebra",
  "|If the mean of 3, 7, x, 12, and 15 is 9, find x.|6|7|8|9": "statistics",
  "|Find the area of a circle with circumference 44 cm. (Take π = 22/7)|77 cm²|154 cm²|308 cm²|616 cm²": "mensuration",
  "|In the diagram, the interior angles of a triangle are 2x°, 3x° and 4x°. Find x.|10°|20°|30°|40°": "geometry",
  "|Evaluate: ³√(−27) + ⁴√16|−1|1|5|−5": "indices",
  "|If P = {1, 2, 3, 4, 5} and Q = {2, 4, 6, 8}, find P ∪ Q.|{1,2,3,4,5,6,8}|{2,4}|{1,3,5}|{1,2,3,4,5,6,7,8}": "sets",
  "|A fair die is thrown once. Find the probability of getting a prime number.|1/6|1/3|1/2|2/3": "probability",
  "|Find the gradient of the line joining (−2, 3) and (4, −9).|2|−2|3|−3": "coordinate",
  "|Simplify: (2x²y³)³ ÷ (4x³y²)|2x³y⁷|2x³y⁵|x³y⁷|2xy⁷": "indices",
  "|The bar chart shows the sales of oranges over 4 days. If Monday = 30, Tuesday = 50, Wednesday = 40, Thursday = 20, find the mean daily sales.|30|35|40|45": "statistics",
  "|If y = 3x² − 2x + 5, find dy/dx.|6x − 2|3x − 2|6x + 5|x² − 2": "differentiation",
  "|Solve: |2x − 3| = 7|x = 5 or x = −2|x = 5 or x = 2|x = −5 or x = 2|x = 5 only": "equations",
  "|A man travels 10 km due north and then 24 km due east. Find the shortest distance from his starting point.|26 km|34 km|14 km|22 km": "trigonometry",
  "|Find the angle subtended at the centre of a circle of radius 6 cm by an arc of length 3π cm.|30°|45°|90°|60°": "mensuration",
  "|If the roots of 2x² + kx + 3 = 0 are equal, find k.|2√6|4√6|√6|3√6": "quadratics",
  "|Evaluate: ∫₀² (3x² − 2x) dx|4|6|8|12": "integration",
  "|A student's score in six tests are: 60, 72, 54, 80, 66, 68. Find the median.|67|68|69|70": "statistics",
  "|From a point 150 m from the base of a tower, the angle of elevation of the top is 30°. Find the height of the tower.|50√3 m|75 m|150√3 m|50 m": "trigonometry",
  "|How many ways can the letters of the word 'GREAT' be arranged?|24|60|120|240": "permutations",
  "|Find the value of x if: (1/3)^x = 27|3|−3|9|−9": "indices",
  "|If sin θ = 3/5 and θ is acute, find tan θ.|3/4|4/3|3/5|5/3": "trigonometry",
  "|Simplify: log 8 + log 5 − log 2 (using base 10)|log 20|log 15|log 40|log 10": "logarithms",
  "|The graph of y = x² − 4 cuts the x-axis at:|x = ±2|x = 4 only|x = ±4|x = 2 only": "quadratics",
  "|The pie chart shows how a family spends its monthly income. If the total income is ₦120,000 and the rent sector is 90°, how much is spent on rent?|₦30,000|₦40,000|₦45,000|₦60,000": "statistics",
  "|Find the sum to infinity of the GP: 1 + 1/3 + 1/9 + ...|3/2|2/3|1/2|3": "sequences",
  "|If the quadratic equation x² − 5x + k = 0 has one root as 3, find k.|6|8|12|15": "quadratics",
  "|Find the remainder when x³ − 5x² + 7x − 2 is divided by (x − 2).|0|2|4|6": "algebra",
  "|Solve simultaneously: 2x + 3y = 12 and x − y = 1|x=3, y=2|x=2, y=3|x=4, y=1|x=1, y=4": "equations",
  "|If f(x) = 2x² + 3x − 1, find f(−2).|−3|1|−1|3": "algebra",
  "|A box contains 5 red, 3 blue and 2 green balls. A ball is picked at random. What is the probability of picking a blue or green ball?|1/2|3/10|2/10|5/10": "probability",
  "|What is the locus of a point equidistant from two fixed points A and B?|The perpendicular bisector of AB|The bisector of angle A|A circle through A and B|A line through A": "geometry",
  "|Given matrix M = [[2,1],[3,4]], find its determinant.|5|8|11|14": "matrices",
  "|Simplify: (x² − 4)/(x − 2)|x + 2|x − 2|x² + 2x|x − 4": "algebra",
  "|Find the value of angle x in a triangle where the exterior angle is 110° and one non-adjacent interior angle is 65°.|45°|55°|70°|75°": "geometry",
  "|The histogram shows frequency distribution. If the bars represent frequencies 4, 7, 10, 6, 3 for intervals 1-5, 6-10, 11-15, 16-20, 21-25 respectively, what is the modal class?|6-10|11-15|1-5|16-20": "statistics",
  "|Express 0.000372 in standard form.|3.72 × 10⁻⁴|3.72 × 10⁻³|37.2 × 10⁻⁵|0.372 × 10⁻³": "fractions-decimals",
  "|Evaluate: 2⁵ × 4⁻² ÷ 8¹|1/4|1/2|1|2": "indices",
  "|The nth term of a sequence is given by Tₙ = 3n − 1. Find the sum of the first 10 terms.|155|175|145|165": "sequences",
  "|If x varies directly as y² and x = 12 when y = 2, find x when y = 5.|60|75|90|100": "variation",
  "|Expand (2a − b)⁴ and find the coefficient of a²b².|12|24|16|48": "algebra",
  "|A straight line passes through (0, 3) and has gradient −2. Find the x-intercept.|3/2|2/3|−3/2|6": "coordinate",
  "|Convert 11011₂ to base 10.|25|27|29|31": "number-bases",
  "|The ages of students in a class have a standard deviation of 0. This means:|All students have different ages|All students have the same age|The ages are normally distributed|Half are above and half below the mean": "statistics",
  "|A cone has base radius 6 cm and height 8 cm. Find its volume. (π = 22/7)|301.7 cm³|302.3 cm³|150.86 cm³|96π cm³": "mensuration",
  "|Which of the following sets is a subset of {1, 2, 3, 4, 5}?|{1, 6}|{2, 4, 6}|{3, 5}|{0, 2, 4}": "sets",
  "|The interior angle of a regular polygon is 150°. How many sides does it have?|10|12|15|8": "geometry",
  "|Solve: log₂(x + 3) + log₂(x − 1) = 5|x = 5|x = 6|x = 3|x = 4": "logarithms",
  "|If P and Q are two events and P(P) = 0.4, P(Q) = 0.3, P(P∩Q) = 0.1, find P(P∪Q).|0.6|0.7|0.5|0.8": "probability",
  "|Evaluate 21.05347 − 1.6324 × 0.43 to 3 decimal places.|20.980|20.351|20.981|20.352": "fractions-decimals",
  "|Simplify (∛(64a³))^{−1}.|4a|1/(8a)|8a|1/(4a)": "indices",
  "|Given that p = 1 + √2 and q = 1 − √2, evaluate (p² − q²)/(2pq).|2(2 + √2)|−2(2 + √2)|2√2|−2√2": "surds",
  "|A car dealer bought a second-hand car for ₦250,000 and spent ₦70,000 refurbishing it. He then sold the car for ₦400,000. What is the percentage gain?|60%|32%|25%|20%": "commercial",
  "|If y/2 = x, evaluate (x³/y³ + 1/2) ÷ (1/2 − x²/y²).|5/8|5/2|5/4|5/16": "algebra",
  "|Find the principal which amounts to ₦5,500 at simple interest in 5 years at 2% per annum.|₦4,900|₦5,000|₦4,700|₦4,800": "commercial",
  "|Evaluate ((0.14)² × 0.275)/(7(0.02)) correct to 3 decimal places.|0.039|0.358|0.03|0.308": "fractions-decimals",
  "|Divide a^{3x} − 26a^{2x} + 156a^{x} − 216 by a^{2x} − 24a^{x} + 108.|a^{x} − 2|a^{x} + 2|a^{x} − 18|a^{x} − 6": "algebra",
  "|Triangle SPT is the solution of the linear inequalities|2y − x − 2 ≤ 0, y + 2x + 2 ≥ 0, −2 ≤ x ≤ −1|−2 ≤ x ≤ 2, y ≥ 0, y + 2x + 2 ≤ 0, x ≤ 0|2y − x − 2 ≤ 0, y + 2x + 2 ≤ 0, y ≥ 0, x ≤ 0|2y − x − 2 ≥ 0, y + 2x + 2 ≤ 0, x ≤ 0": "inequalities",
  "|The table defines an operation ⊕ on {K, L, M} (row element ⊕ column element). Row K: K⊕K = L, K⊕L = M, K⊕M = K. Row L: L⊕K = M, L⊕L = K, L⊕M = L. Row M: M⊕K = K, M⊕L = L, M⊕M = M. The identity element with respect to the operation shown in the table above is|O|M|L|K": "binary-operations",
  "|A man saves ₦100.00 in the first year of work and each year saves ₦20.00 more than in the preceding year. In how many years will he save ₦5,800.00?|100 years|58 years|29 years|20 years": "sequences",
  "|If P = [[3, −2, 4], [5, 0, 6], [7, 5, −1]], then −2P is|[[−6, 4, −8], [−10, 0, −12], [−14, −10, 2]]|[[−6, −4, 2], [−10, −2, −12], [−14, −10, 3]]|[[−6, 4, −8], [−10, 0, 6], [−14, 5, −1]]|[[−6, 4, −8], [5, 0, 6], [7, 5, −1]]": "matrices",
  "|Given the matrix K = [[2, 1], [3, 4]], the matrix K² + K + I, where I is the 2 × 2 identity matrix, is|[[7, 2], [17, 21]]|[[6, 3], [13, 20]]|[[9, 8], [22, 23]]|[[10, 7], [21, 24]]": "matrices",
  "|If two graphs y = px² + q and y = 2x² − 1 intercept at x = 2, find the value of p in terms of q.|(q − 8)/7|(7 − q)/4|(8 − q)/2|(7 − q)/8": "algebra",
  "|Find the integral values of x and y satisfying the inequality 3y + 5x ≤ 15, given that y > 0, y < 3 and x > 0.|(1, 1), (1, 2), (1, 3)|(1, 1), (2, 1), (1, 3)|(1, 1), (3, 1), (2, 2)|(1, 1), (1, 2), (2, 1)": "inequalities",
  "|Evaluate the determinant |[−1, −1, −1], [3, 1, −1], [1, 2, 1]|.|−12|−4|4|−2": "matrices",
  "|Solve the equations m² + n² = 29, m + n = 7.|(2, 3) and (3, 5)|(2, 5) and (5, 2)|(5, 2) and (5, 3)|(5, 3) and (3, 5)": "equations",
  "|An operation * is defined on the set of real numbers by a * b = a + b + 1. If the identity element is −1, find the inverse of the element 2 under *.|4|0|−2|−4": "binary-operations",
  "|The sixth term of an arithmetical progression is half of its twelfth term. The first term is equal to|zero|half of the common difference|double the common difference|the common difference": "sequences",
  "|Factorize 4x² − 9y² + 20x + 25.|(2x − 3y + 5)(2x − 3y − 5)|(2x − 3y)(2x + 3y)|(2x − 3y + 5)(2x + 3y + 5)|(2x + 5)(2x − 9y − 5)": "algebra",
  "|A sector of a circle of radius 7.2 cm which subtends an angle of 300° at the centre is used to form a cone. What is the radius of the base of the cone?|8 cm|6 cm|9 cm|7 cm": "mensuration",
  "|A point P moves such that it is equidistant from points Q and R. Find QR when PR = 8 cm and ∠PRQ = 30°.|4√3 cm|8 cm|8√3 cm|4 cm": "geometry",
  "|Find the value of θ in the diagram above.|100°|120°|30°|60°": "trigonometry",
  "|A straight line makes an angle of 30° with the positive x-axis and cuts the y-axis at y = 5. Find the equation of the straight line.|y = x/10 + 5|y = x + 5|√3y = −x + 5√3|√3y = x + 5√3": "coordinate",
  "|Find the value of p if the line joining (p, 4) and (6, −2) is perpendicular to the line joining (2, p) and (−1, 3).|4|6|3|0": "coordinate",
  "|Find the number of sides of a regular polygon whose interior angle is twice the exterior angle.|6|2|3|8": "geometry",
  "|P(−6, 1) and Q(6, 6) are the two ends of the diameter of a given circle. Calculate the radius.|6.5 units|13.0 units|3.5 units|7.0 units": "coordinate",
  "|The bearings of P and Q from a common point N are 020° and 300° respectively. If P and Q are also equidistant from N, find the bearing of P from Q.|040°|070°|280°|320°": "trigonometry",
  "|A cylindrical tank has a capacity of 3080 m³. What is the depth of the tank if the diameter of its base is 14 m?|23 m|25 m|20 m|22 m": "mensuration",
  "|Find the locus of a point which moves such that its distance from the line y = 4 is a constant, k.|y = k ± 4|y = 4 ± k|y = 4 + k|y = k − 4": "geometry",
  "|The chord ST of a circle is equal to the radius, r, of the circle. Find the length of arc ST.|πr/6|πr/2|πr/12|πr/3": "mensuration",
  "|In the figure above, PQR is a straight line segment, PQ = QT. Triangle PQT is an isosceles triangle, ∠SRQ is 75° and ∠QPT is 25°. Calculate the value of ∠RST.|45°|55°|25°|50°": "geometry",
  "|If the gradient of the curve y = 2kx² + x + 1 at x = 1 is 9, find k.|4|3|2|1": "differentiation",
  "|Evaluate ∫(2x − 3)^{2/3} dx.|3/10 (2x − 3)^{5/3} + k|6/5 (2x − 3)^{5/3} + k|2x − 3 + k|2(2x − 3) + k": "integration",
  "|Differentiate (2x + 5)²(x − 4) with respect to x.|4(2x + 5)(x − 4)|4(2x + 5)(4x − 3)|(2x + 5)(2x − 13)|(2x + 5)(6x − 11)": "differentiation",
  "|Find the area bounded by the curves y = 4 − x² and y = 2x + 1.|20 1/3 sq units|20 2/3 sq units|10 2/3 sq units|10 1/3 sq units": "integration",
  "|Find the rate of change of the volume V of a sphere with respect to its radius r when r = 1.|12π|4π|24π|8π": "differentiation",
  "|If y = x sin x, find dy/dx when x = π/2.|−π/2|−1|1|π/2": "differentiation",
  "|Find the dimensions of the rectangle of greatest area which has a fixed perimeter P.|square of sides P|square of sides 2P|square of sides P/2|square of sides P/4": "differentiation",
  "|Score: 4, 7, 8, 11, 13, 6 with frequencies 3, 5, 2, 7, 2, 1 respectively. Find the square of the mode.|49|121|25|64": "statistics",
  "|Score: 4, 7, 8, 11, 13, 6 with frequencies 3, 5, 2, 7, 2, 1 respectively. The mean score is|70|8.6|9.5|11.0": "statistics",
  "|Teams P and Q are involved in a game of football. What is the probability that the game ends in a draw?|2/3|1/2|1/3|1/4": "probability",
  "|If ^{6}P_{r} = 6, find the value of ^{6}P_{r+1}.|30|33|35|15": "permutations",
  "|The graph above shows the cumulative frequency of the distribution of masses of fertilizer for 48 workers in one institution. Which of the following gives the interquartile range?|Q_{3} − Q_{2}|½(Q_{3} − Q_{1})|Q_{3} − Q_{1}|Q_{2} − Q_{1}": "statistics",
  "|The histogram above shows the distribution of passengers in taxis at a certain motor park. How many taxis have more than 4 passengers?|16|17|14|15": "statistics",
  "|The distribution of colours of beads in a bowl is given in the table: Blue 1, Black 2, Yellow 4, White 5, Brown 3. What is the probability that a bead selected at random will be blue or white?|7/15|2/5|1/3|1/15": "probability",
  "|Find the variance of 2, 6, 8, 6, 2 and 6.|6|5|√6|√5": "statistics",
  "|The bar chart above shows different colours of cars passing a particular point of a certain street in minutes. What fraction of the total number of cars is yellow?|3/25|2/25|1/5|4/5": "statistics",
  "|Find the number of ways of selecting 8 subjects from 12 subjects for an examination.|490|495|496|498": "permutations",
  "|Find the range of 1/6, 1/3, 3/2, 2/3, 8/9 and 4/3.|3/4|5/6|7/6|4/3": "statistics",
  "|Without using tables, evaluate (343)^{1/3} × (0.14)^{-1} × (25)^{-1/2}.|10|12|8|7": "indices",
  "|In a school, 220 students offer Biology or Mathematics or both, 125 offer Biology and 110 offer Mathematics. How many offer Biology but not Mathematics?|95|80|125|110": "sets",
  "|Simplify 52.4 − 5.7 − 3.45 − 1.75.|41.4|41.5|42.1|42.2": "fractions-decimals",
  "|Simplify (√0.7 + √70)^{2}.|84.7|70.7|217.7|168.7": "fractions-decimals",
  "|Evaluate (0.21 × 0.072 × 0.00054)/(0.006 × 1.68 × 0.063), correct to four significant figures.|0.01286|0.01285|0.1286|0.1285": "fractions-decimals",
  "|A trader bought goats for ₦4,000 each. He sold them for ₦180,000 at a loss of 25%. How many goats did he buy?|60|50|45|36": "commercial",
  "|If dy/dx = 2x − 3 and y = 3 when x = 0, find y in terms of x.|2x^{2} − 3x|x^{2} − 3x|x^{2} − 3x − 3|x^{2} − 3x + 3": "integration",
  "|Find the derivative of y = sin^{2}(5x) with respect to x.|10 sin 5x cos 5x|5 sin 5x cos 5x|2 sin 5x cos 5x|15 sin 5x cos 5x": "differentiation",
  "|The slope of the tangent to the curve y = 3x^{2} − 2x + 5 at the point (1, 6) is|4|1|6|5": "differentiation",
  "|Evaluate ∫ sin 3x dx.|(2/3) cos 3x + C|(1/2) cos 3x + C|−(1/3) cos 3x + C|−(2/3) cos 3x + C": "integration",
  "|A circle with a radius 5 cm has its radius increasing at the rate of 0.2 cm s^{-1}. What will be the corresponding increase in the area?|2π|5π|π|4π": "differentiation",
  "|If y = x^{2} − 1/x, find dy/dx.|2x − 1/x^{2}|2x + x^{2}|2x − x^{2}|2x + 1/x^{2}": "differentiation",
  "|Use the graph above (the boundary line passes through (−4, 0) and (0, 2), and the shaded region contains the origin) to find the value of p and q if px + qy ≤ 4.|p = 2, q = 1|p = 2, q = −1|p = 1, q = 2|p = −1, q = 2": "inequalities",
  "|Solve for x in the equation x^{3} − 5x^{2} − x + 5 = 0.|1, −1 or 5|1, 1 or −5|−1, 1 or −5|1, 1 or 5": "quadratics",
  "|The time taken to do a piece of work is inversely proportional to the number of men employed. If it takes 45 men to do a piece of work in 5 days, how long will it take 25 men?|15 days|12 days|5 days|9 days": "variation",
  "|If P = [[2, 1], [−3, 0]] and I is a 2 × 2 unit matrix, evaluate P^{2} − 2P + 4I.|[[9, 4], [−12, 1]]|[[−3, 0], [0, −4]]|[[1, 0], [0, 1]]|[[1, 4], [4, 1]]": "matrices",
  "|Find the range of values of x for which (x + 2)/4 − (2x − 3)/3 < 4.|x > −6|x > −3|x < 8|x < 4": "inequalities",
  "|Find the maximum value of y in the equation y = 1 − 2x − 3x^{2}.|5/4|5/3|3/4|4/3": "differentiation",
  "|If the 9th term of an A.P. is five times the 5th term, find the relationship between a and d.|2a + d = 0|3a + 5d = 0|a + 3d = 0|a + 2d = 0": "sequences",
  "|Make r the subject of the formula x/(r + a) = a/r.|a^{2}/(x − a)|a^{2}/(x + a)|a/(x − a)|a/(x + a)": "algebra",
  "|The inverse of the function f(x) = 3x + 4 is|(1/3)(x − 4)|(1/5)(x − 5)|(1/4)(x + 3)|(1/3)(x + 4)": "algebra",
  "|If −2 is the solution of the equation 2x + 1 − 3c = 2c + 3x − 7, find the value of c.|4|3|2|1": "equations",
  "|The binary operation * is defined on the set of integers p and q by p * q = pq + p + q. Find 2 * (3 * 4).|59|19|67|38": "binary-operations",
  "|If N = [[3, 5, −4], [6, −3, −5], [−2, 2, 1]], find |N|.|17|23|65|91": "matrices",
  "|The sum to infinity of the series 1 + 1/3 + 1/9 + 1/27 + … is|11/3|10/3|5/2|3/2": "sequences",
  "|If x varies directly as √n and x = 9 when n = 9, find x when n = 17/9.|4|27|√3|√17": "variation",
  "|In the diagram above, PST is a straight line, PQ = QS = RS. If ∠RST = 72°, find x.|36°|18°|72°|24°": "geometry",
  "|A chord of a circle subtends an angle of 120° at the centre of a circle of diameter 4√3 cm. Calculate the area of the major sector.|4π cm²|32π cm²|16π cm²|8π cm²": "mensuration",
  "|Find the equation of the set of points which are equidistant from the parallel lines x = 1 and x = 7.|y = 3|x = 3|x = 4|y = 4": "geometry",
  "|In the diagram above, XZ is the diameter of the circle XYZW, with centre O and radius 15/2 cm. If XY = 12 cm, find the area of the triangle XYZ.|54 cm²|45 cm²|27 cm²|75 cm²": "geometry",
  "|If tan θ = 4/3, calculate sin^{2} θ − cos^{2} θ.|16/25|24/25|7/25|9/25": "trigonometry",
  "|In the diagram above are two concentric circles of radii r and R respectively with centre O. If r = (2/5)R, express the area of the shaded portion in terms of π and R.|(21/25)πR^{2}|(9/25)πR^{2}|(21/23)πR^{2}|(5/9)πR^{2}": "mensuration",
  "|A bucket is 12 cm in diameter at the top, 8 cm in diameter at the bottom and 4 cm deep. Calculate its volume.|(304/3)π cm³|144π cm³|(128/3)π cm³|72π cm³": "mensuration",
  "|In the diagram above, a cylinder is surmounted by a hemispherical bowl. Calculate the volume of the solid.|180π cm³|162π cm³|216π cm³|198π cm³": "mensuration",
  "|The sum of the interior angles of a polygon is 20 right angles. How many sides does the polygon have?|12|20|40|10": "geometry",
  "|Find the coordinate of the midpoint of the x and y intercepts of the line 2y = 4x − 8.|(2, 0)|(1, −2)|(−1, −2)|(1, 2)": "coordinate",
  "|A hunter 1.6 m tall views a bird on top of a tree at an angle of 45°. If the distance between the hunter and the tree is 10.4 m, find the height of the tree.|9.0 m|12.0 m|8.8 m|10.4 m": "trigonometry",
  "|A solid hemisphere has radius 7 cm. Find the total surface area. [π = 22/7]|400 m²|462 cm²|66 cm²|308 cm²": "mensuration",
  "|Find the value of α if the line 2y − αx + 4 = 0 is perpendicular to the line y + (1/4)x − 7 = 0.|−4|4|8|−8": "coordinate",
  "|The triangle PQR above is|an obtuse-angled triangle|a scalene triangle|an isosceles triangle|an equilateral triangle": "geometry",
  "|The locus of a point P which is equidistant from two given points S and T is|the perpendicular bisector of ST|the angle bisector of PS and ST|a perpendicular to ST|a line parallel to ST": "geometry",
  "|Find the mean of the data 7, −3, 4, −2, 5, −9, 4, 8, −6, 12.|3|4|1|2": "statistics",
  "|The Venn diagram above shows the number of students offering Music and History in a class of 80 students. If a student is picked at random from the class, what is the probability that he offers Music only?|0.38|0.13|0.50|0.25": "probability",
  "|The range of the data k + 2, k − 3, k + 4, k − 2, k − 5, k + 3, k − 1 and k + 6 is|10|11|6|8": "statistics",
  "|The probability of a student passing any examination is 2/3. If the student takes three examinations, what is the probability that he will not pass any of them?|2/3|4/9|8/27|1/27": "probability",
  "|The acres for rice, pineapple, cassava, cocoa and palm oil in a certain district are given respectively as 2, 5, 3, 11 and 9. What is the angle of the sector for cassava in a pie chart?|100°|180°|36°|60°": "statistics",
  "|How many three-digit numbers can be formed from 32564 without any digit being repeated?|120|10|20|60": "permutations",
  "|The mean of a set of six numbers is 60. If the mean of the first five is 50, find the sixth number in the set.|105|100|95|110": "statistics",
  "|Calculate the mean deviation of the set of numbers 7, 3, 14, 9, 7 and 8.|21/6|2½|11/6|2⅓": "statistics",
  "|No. of days: 1, 2, 3, 4, 5, 6; No. of students: 20, x, 50, 40, 2x, 60. The distribution above shows the number of days a group of 260 students were absent from school in a particular term. How many students were absent from school for at least four days in the term?|210|40|120|160": "statistics",
  "|Evaluate log_{√2} 4 + log_{1/2} 16 − log_{4} 32.|−5.5|−2.5|2.5|5.5": "logarithms",
  "|Simplify 213_{4} × 23_{4}.|10311_{4}|10321_{4}|12231_{4}|13211_{4}": "number-bases",
  "|In a class of 40 students, 32 offer Mathematics, 24 offer Physics and 4 offer neither Mathematics nor Physics. How many offer both Mathematics and Physics?|20|16|8|4": "sets",
  "|Find (1/0.06 ÷ 1/0.042)^{−1}, correct to two decimal places.|1.43|1.53|3.14|4.42": "fractions-decimals",
  "|A woman buys 270 oranges for ₦1800.00 and sells at 5 for ₦40.00. What is her profit?|₦216.00|₦1620.00|₦630.00|₦360.00": "commercial",
  "|Simplify 1 − (2⅓ × 1¼) + 3/5.|−1 1/15|−1 19/60|−2 7/15|−2 31/60": "fractions-decimals",
  "|Simplify (√98 − √50)/√32.|3|1|½|¼": "surds",
  "|A cinema hall contains a certain number of people. If 22½% are children, 47½% are men and 84 are women, find the number of men in the hall.|63|84|113|133": "commercial",
  "|If 9^{2x−1}/27^{x+1} = 1, find the value of x.|8|5|3|2": "indices",
  "|The sum of four numbers is 1214_{5}. What is the average expressed in base five?|114|141|401|411": "number-bases",
  "|Given U = {Even numbers between 0 and 30}, P = {Multiples of 6 between 0 and 30}, Q = {Multiples of 4 between 0 and 30}, find (P ∪ Q)'.|{2, 10, 14, 22, 26}|{0, 10, 14, 22, 26}|{2, 4, 14, 18, 26}|{0, 2, 6, 22, 26}": "sets",
  "|x varies directly as the product of u and v and inversely as their sum. If x = 3 when u = 3 and v = 1, what is the value of x if u = 3 and v = 3?|3|4|6|9": "variation",
  "|Find the range of values of x satisfying the inequalities 5 + x ≤ 8 and 13 + x ≥ 7.|−3 ≤ x ≤ 3|3 ≤ x ≤ 6|−6 ≤ x ≤ 3|−6 ≤ x ≤ −3": "inequalities",
  "|If det[[−x, 2], [4x, 1]] = det[[3, 3x], [4, −5]], find the value of x.|5|2|−2|−5": "matrices",
  "|The graphs of the function y = x² + 4 and a straight line PQ are drawn to solve the equation x² − 3x + 2 = 0. What is the equation of PQ?|y = 3x − 2|y = 3x + 2|y = 3x − 4|y = 3x + 4": "quadratics",
  "|The length a person can jump is inversely proportional to his weight. If a 20 kg person can jump 1.5 m, find the constant of proportionality.|60|30|20|15": "variation",
  "|Find the value of x and y respectively if 3x − 5y + 5 = 0 and 4x − 7y + 8 = 0.|−5, −4|−4, −5|4, 5|5, 4": "equations",
  "|Three consecutive terms of a geometric progression are given as n − 2, n and n + 3. Find the common ratio.|¼|½|2/3|3/2": "sequences",
  "|Triangle OPQ above is the solution of the inequalities|x + 1 ≥ 0, y + x ≤ 0, y − x ≥ 0|y + x ≤ 0, y − x ≥ 0, x − 1 ≥ 0|x − 1 ≤ 0, y − x ≥ 0, y + x ≥ 0|x − 1 ≤ 0, y + x ≥ 0, y − x ≤ 0": "inequalities",
  "|Factorize completely 4abx − 2axy − 12b²x + 6bxy.|2x(a − 3b)(2b − y)|2x(3b − a)(2b − y)|2x(a − 3b)(y − 2b)|2x(2b − a)(3b − y)": "algebra",
  "|A matrix P has an inverse P^{−1} = [[1, −3], [0, 1]]. Find P.|[[−1, 3], [0, −1]]|[[1, 3], [0, −1]]|[[1, −3], [0, −1]]|[[1, 3], [0, 1]]": "matrices",
  "|The sum of the first n terms of an arithmetic progression is 252. If the first term is −16 and the last term is 72, find the number of terms in the series.|6|7|8|9": "sequences",
  "|An arc of a circle subtends an angle of 30° on the circumference of a circle of radius 21 cm. Find the length of the arc. [π = 22/7]|11 cm|22 cm|44 cm|66 cm": "mensuration",
  "|Find the equation of the locus of a point P(x, y) which is equidistant from Q(0, 0) and R(2, 1).|4x + 2y = 5|4x − 2y = 5|2x + 2y = 5|2x + y = 5": "coordinate",
  "|In the diagram above, PQ is parallel to RS. What is the value of α + β + γ?|360°|200°|180°|90°": "geometry",
  "|A trapezium has two parallel sides of length 5 cm and 9 cm. If the area is 21 cm², find the distance between the parallel sides.|3 cm|4 cm|6 cm|7 cm": "mensuration",
  "|Which of the following is the graph of sin θ for −π/2 ≤ θ ≤ 3π/2?|Graph A|Graph B|Graph C|Graph D": "trigonometry",
  "|In the diagram above, O is the centre of the circle. POM is a diameter and ∠MNQ = 42°. Calculate ∠QMP.|42°|48°|132°|138°": "geometry",
  "|Find the value of p, if the line which passes through (−1, −p) and (−2p, 2) is parallel to the line 2y + 8x − 17 = 0.|7/6|6/7|−2/7|−6/7": "coordinate",
  "|An aeroplane flies due north from airport P to Q and then flies due east to R. If Q is equidistant from P and R, find the bearing of P from R.|090°|135°|225°|270°": "trigonometry",
  "|The locus of a point P which moves on one side only of a straight line XY so that ∠XPY = 90° is|a circle|a semicircle|an arc of a circle through X, Y|the perpendicular bisector of XY": "geometry",
  "|If π/2 ≤ θ ≤ 2π, find the maximum value of f(θ) = 4/(6 + 2 cos θ).|4|1|2/3|½": "trigonometry",
  "|XYZ is a circle centre O and radius 7 cm. Find the area of the shaded region.|84 cm²|77 cm²|38 cm²|14 cm²": "mensuration",
  "|A triangle has vertices P(−1, 6), Q(−3, −4) and R(1, −4). Find the midpoints of PQ and QR respectively.|(0, −2) and (−1, −4)|(−1, 0) and (−1, −1)|(−2, 1) and (0, 1)|(−2, 1) and (−1, −4)": "coordinate",
  "|In the diagram above, PQR is a straight line and PS is a tangent to the circle QRS with |PS| = |SR| and ∠SPR = 40°. Find ∠PSQ.|40°|30°|20°|10°": "geometry",
  "|Find the slope of the curve y = 2x² + 5x − 3 at (1, 4).|4|6|7|9": "differentiation",
  "|Evaluate ∫_{2}^{3} (x² − 2x) dx.|4|2|4/3|1/3": "integration",
  "|If y = 3 sin(−4x), dy/dx is|12x cos(4x)|−12x cos(−4x)|−12 cos(−4x)|−12 sin(−4x)": "differentiation",
  "|Determine the maximum value of y = 3x² − x³.|0|2|4|6": "differentiation",
  "|By how much is the mean of 30, 56, 31, 55, 43 and 44 less than the median?|0.75|0.50|0.33|0.17": "statistics",
  "|The range of 4, 3, 11, 9, 6, 15, 19, 23, 27, 24, 21 and 16 is|16|21|23|24": "statistics",
  "|Number: 0, 1, 2, 3, 4. Frequency: 1, 2, 2, 1, 9. Find the mean of the distribution above.|1|2|3|4": "statistics",
  "|On a pie chart, there are four sectors of which three angles are 45°, 90° and 135°. If the smallest sector represents ₦28.00, how much is the largest sector?|₦84.00|₦42.00|₦48.00|₦96.00": "statistics",
  "|Two dice are thrown. What is the probability that the sum of the numbers is divisible by 3?|2/3|½|1/3|¼": "probability",
  "|If ^{n}P_{3} − 6(^{n}C_{4}) = 0, find the value of n.|5|6|7|8": "permutations",
  "|Find the number of committees of three that can be formed consisting of two men and one woman from four men and three women.|3|6|18|24": "permutations",
  "|The mean of the numbers 3, 6, 4, x and 7 is 5. Find the standard deviation.|√2|√3|2|3": "statistics",
  "|A bag contains 5 black balls and 3 red balls. Two balls are picked at random without replacement. What is the probability that a black and a red ball are picked?|15/28|13/28|5/14|3/14": "probability",
  "|The histogram above shows the ages of the victims of a pollution. How many people were involved in the pollution?|15|18|20|21": "statistics",
  "|Number: 1, 2, 3, 4, 5, 6. Frequency: 12, 20, x, 21, x − 1, 28. The result of tossing a fair die 120 times is summarized above. Find the value of x.|19|20|21|22": "statistics",
  "|An arc of a circle of length 22 cm subtends an angle of 3x° at the centre of the circle. Find the value of x if the diameter of the circle is 14 cm. [Take π = 22/7]|60°|120°|180°|30°": "mensuration",
  "|Find the value of α² + β² if α + β = 2 and the distance between the points (1, α) and (β, 1) is 3 units.|14|3|5|11": "coordinate",
  "|The sum of the interior angles of a pentagon is 6x + 6y. Find y in terms of x.|y = 90 − x|y = 150 − x|y = 60 − x|y = 120 − x": "geometry",
  "|In the diagram, PQ = 4 cm and TS = 6 cm. If the area of parallelogram PQTU is 32 cm², find the area of the trapezium PQRU. (U is the unlabelled bottom-left corner.)|60 cm²|72 cm²|48 cm²|24 cm²": "mensuration",
  "|Find the midpoint of the line joining P(−3, 5) and Q(5, −3).|(1, 1)|(2, 2)|(4, 4)|(4, −4)": "coordinate",
  "|PQRSTV is a regular polygon of side 7 cm inscribed in a circle. Find the circumference of the circle PQRSTV. [π = 22/7]|56 cm|22 cm|42 cm|44 cm": "mensuration",
  "|Determine the locus of a point inside a square PQRS which is equidistant from PQ and QR.|The diagonal QS|The perpendicular bisector of PQ|The diagonal PR|Side SR": "geometry",
  "|Find the value of x in the figure.|15√6|20√6|3√6|5√6": "trigonometry",
  "|P, R and S lie on a circle centre O as shown, while Q lies outside the circle. Find ∠PSO.|45°|55°|35°|40°": "geometry",
  "|The shadow of a pole 5√3 m high is 5 m. Find the angle of elevation of the sun.|45°|75°|30°|60°": "trigonometry",
  "|The locus of a point which is 5 cm from the line LM is a|line distance 10 cm from LM and parallel to LM|pair of lines on opposite sides of LM and parallel to it, each distance 5 cm from LM|line parallel to LM and 5 cm from LM|pair of parallel lines on one side of LM and parallel to LM": "geometry",
  "|If y = 3 cos (x/3), find dy/dx when x = 3π/2.|1|−3|2|−1": "differentiation",
  "|Find the derivative of (2 + 3x)(1 − x) with respect to x.|6|−3|1 − 6x|6x − 1": "differentiation",
  "|What is the rate of change of the volume v of a hemisphere with respect to its radius r when r = 2?|8π|16π|2π|4π": "differentiation",
  "|Find the derivative of the function y = 2x²(2x − 1) at the point x = −1.|18|16|−4|−6": "differentiation",
  "|Evaluate ∫_{1}^{3} (x² − 1) dx.|2/3|−2/3|−6 2/3|6 2/3": "integration",
  "|Some white balls were put in a basket containing twelve red balls and sixteen black balls. If the probability of picking a white ball from the basket is 3/7, how many white balls were introduced?|12|21|28|32": "probability",
  "|The graph above shows the cumulative frequency curve of the distribution of marks in a class test. What percentage of the students scored more than 20 marks?|28%|68%|8%|17%": "statistics",
  "|Find the mean deviation of 1, 2, 3 and 4.|2.5|2.0|1.0|1.5": "statistics",
  "|An unbiased die is rolled 100 times and the outcome is tabulated as follows: Number 1, 2, 3, 4, 5, 6 with frequencies 13, 15, 22, 14, 20, 16 respectively. What is the probability of obtaining 5?|1/5|1/2|1/6|1/4": "probability",
  "|The pie chart shows the distribution of the crops harvested from a farmland in a year. If 3000 tonnes of millet is harvested, what amount of beans is harvested?|6000 tonnes|1500 tonnes|1200 tonnes|9000 tonnes": "statistics",
  "|In how many ways can 2 students be selected from a group of 5 students in a debating competition?|25 ways|10 ways|15 ways|20 ways": "permutations",
  "|The mean age of a group of students is 15 years. When the age of a teacher, 45 years old, is added to the ages of the students, the mean of their ages becomes 18 years. Find the number of students in the group.|9|7|42|15": "statistics",
  "|A container has 30 gold medals, 22 silver medals and 18 bronze medals. If one medal is selected at random from the container, what is the probability that it is not a gold medal?|9/35|11/35|4/7|3/7": "probability",
  "|A committee of six is to be formed by a state governor from nine state commissioners and three members of the state house of assembly. In how many ways can the members of the committee be chosen so as to include one member of the house of assembly?|378 ways|462 ways|840 ways|924 ways": "permutations",
  "|The weights of 10 pupils in a class are 15 kg, 16 kg, 17 kg, 18 kg, 16 kg, 17 kg, 17 kg, 18 kg and 16 kg. What is the range of this distribution?|4|3|1|2": "statistics",
  "|I. Rectangular bars of equal width; II. The height of each rectangular bar is proportional to the frequency of the corresponding class interval; III. Rectangular bars have common sides with no gaps in between. A histogram is described completely by|I, II and III|I and II|II and III|I and III": "statistics",
  "|y is inversely proportional to x and y = 4 when x = ½. Find x when y = 10.|2|10|1/5|1/10": "variation",
  "|What are the integral values of x which satisfy the inequality −1 < 3 − 2x ≤ 5?|−1, 0, 1, 2|−2, 1, 0, −1|0, 1, 2|−1, 0, 1": "inequalities",
  "|The inverse of the matrix [[2, 1], [1, 1]] is|[[1, 1], [1, 2]]|[[1, 1], [−1, 2]]|[[1, −1], [−1, 2]]|[[1, −1], [−1, 2]]": "matrices",
  "|Find the values of x where the curve y = x³ + 2x² − 5x − 6 crosses the x-axis.|−2, 1 and −3|2, −1 and −3|2, 1 and 3|−2, −1 and 3": "quadratics",
  "|Given that the first and fourth terms of a G.P. are 6 and 162 respectively, find the sum of the first three terms of the progression.|27|8|78|48": "sequences",
  "|The shaded area in the diagram is represented by (the boundary line passes through (0, 6) and (2, 0))|{(x, y): y − 3 < −6}|{(x, y): y + 3x < 6}|{(x, y): y + 3x < −6}|{(x, y): y − 3x < 6}": "inequalities",
  "|If the operation * in the set of integers is defined by p * q = √(pq), find the value of 4 * (8 * 32).|8|3|16|4": "binary-operations",
  "|Find the remainder when 3x³ + 5x² − 11x + 4 is divided by x + 3.|−4|4|1|−1": "quadratics",
  "|The nth terms of two sequences are Q_{n} = 3 · 2^{n−2} and U_{m} = 3 · 2^{2m−3}. Find the product of Q_{2} and U_{2}.|18|12|6|3": "sequences",
  "|If P = [[1, 0, −1], [3, 4, 5], [−1, 0, 1]], then |P| is|4|8|−8|0": "matrices",
  "|Factorize completely ac − 2bc − a² + 4b².|(a − 2b)(c − a − 2b)|(a − 2b)(c + a + 2b)|(a − 2b)(c + a + 2b)|(a − 2b)(c + a − 2b)": "algebra",
  "|Find the sum to infinity of the series ½, 1/6, 1/18, …|2/3|1/3|3/4|1": "sequences",
  "|The length L of a simple pendulum varies directly as the square root of its period T. If a pendulum with period 4 sec is 64 cm long, find the length of a pendulum whose period is 9 seconds.|96 cm|324 cm|36 cm|324 cm": "variation",
  "|Find x and y respectively in the subtraction 4243 − 13x4 = y344, carried out in base 5 (x and y are single digits).|4, 2|2, 4|4, 3|3, 2": "number-bases",
  "|Three teachers shared a packet of chalk. The first teacher got 2/5 of the chalk and the second teacher received 2/15 of the remainder. What fraction did the third teacher receive?|8/15|11/25|12/25|13/25": "fractions-decimals",
  "|If 6 log_{x} 2 − 3 log_{x} 3 = 3 log_{5} 0.2, find x.|8/3|4/3|3/4|3/8": "logarithms",
  "|Find p, if 451_{6} − p_{7} = 305_{6}.|62_{7}|116_{7}|611_{7}|142_{7}": "number-bases",
  "|In a class of 40 students, each student offers at least one of Physics and Chemistry. If the number of students that offer Physics is three times the number that offers both subjects and the number that offers Chemistry is twice the number that offers Physics, find the number of students that offer Physics only.|15|25|5|10": "sets",
  "|Given that ∛(4^{2x}) = 16, find the value of x.|4|6|3|2": "indices",
  "|Evaluate (1/10 × 2/3 + 1/4)/(1/2 ÷ 3/5 − 1/4).|7/12|19/35|2/25|19/60": "fractions-decimals",
  "|The shaded region in the Venn diagram is|P^{c} ∪ (Q ∩ R)|P^{c} ∩ (Q ∪ R)|P ∩ Q|P^{c} ∩ (Q ∩ R)": "sets",
  "|Simplify 1/(√3 + 2) in the form a + b√3.|2 − √3|−2 − √3|2 + √3|−2 + √3": "surds",
  "|A farmer planted 5,000 grains of maize and harvested 5,000 cobs, each bearing 500 grains. What is the ratio of the number of grains sowed to the number harvested?|1 : 250,000|1 : 25,000|1 : 500|1 : 5,000": "commercial",
  "|If y = (1 − 2x)³, find the value of dy/dx at x = −1.|−6|57|−54|27": "differentiation",
  "|Find the area of the figure bounded by the given pair of curves y = x² − x + 3 and y = 3.|7/6 sq. units|17/6 sq. units|1/6 sq. units|5/6 sq. units": "integration",
  "|The radius r of a circular disc is increasing at the rate of 0.5 cm/sec. At what rate is the area of the disc increasing when its radius is 6 cm?|3π cm²/sec|36π cm²/sec|18π cm²/sec|6π cm²/sec": "differentiation",
  "|Evaluate ∫₀^{π/2} sin 2x dx.|−1/2|1|−1|0": "integration",
  "|The maximum value of the function f(x) = 2x + x − x² is|3/2|1/2|9/4|7/4": "differentiation",
  "|Find the derivative of y = sin(2x³ + 3x − 4).|−cos(2x³ + 3x − 4)|−(6x² + 3)cos(2x³ + 3x − 4)|cos(2x³ + 3x − 4)|(6x² + 3)cos(2x³ + 3x − 4)": "differentiation",
  "|The sum of the interior angles of a regular polygon is 1800°. Calculate the size of one exterior angle of the polygon.|12°|18°|30°|24°": "geometry",
  "|Two lines PQ and ST intersect at 75°. The locus of points equidistant from PQ and ST lies on the|bisector of the angles between lines PQ and ST|bisector of the angles between lines PT and QS|perpendicular bisector of ST|perpendicular bisector of PQ": "geometry",
  "|A chord of a circle subtends an angle of 60° at the centre of a circle of radius 14 cm. Find the length of the chord.|21 cm|7 cm|28 cm|14 cm": "mensuration",
  "|From the diagram above, find the bearing of R from S.|224°|136°|134°|226°": "trigonometry",
  "|Find the coordinates of the midpoint of the line joining (3, −4) and (−1, 10).|(2, 3)|(1, 3)|(3, 2)|(1, 2)": "coordinate",
  "|In the diagram above, O is the centre of the circle, ∠UOT = 70° and ∠QST = 100°. Calculate ∠QUO.|50°|20°|80°|25°": "geometry",
  "|Find the equation of the perpendicular at point (4, 3) to the line y + 2x − 5 = 0.|2y − x = 2|2y − x = 4|y + 2x = 3|y + 2x = 5": "coordinate",
  "|A sector of a circle has an area of 55 cm². If the radius of the circle is 10 cm, calculate the angle of the sector. [π = 22/7]|90°|75°|63°|45°": "mensuration",
  "|If sin θ = −½ for 0 < θ < 360°, the value of θ is|210° and 330°|150° and 33°|150° and 210°|30° and 150°": "trigonometry",
  "|Three straight lines EF, GH and LK intersect at O as shown above. If ∠KOF = 52° and ∠LOH = 85°, calculate the size of ∠EOG.|26°|43°|53°|85°": "geometry",
  "|Find the curved surface area of a cone with circular base diameter 10 cm and height 12 cm.|25π cm²|120π cm²|156π cm²|65π cm²": "mensuration",
  "|In the diagram above, calculate the value of x.|120°|60°|140°|100°": "geometry",
  "|Three boys shared some oranges. The first received ⅓ of the oranges and the second received ⅔ of the remainder. If the third boy received the remaining 12 oranges, how many oranges did they share?|42|48|54|60": "fractions-decimals",
  "|Simplify (√12 − √3)/(√12 + √3).|1/3|1|0|3/5": "surds",
  "|If the interest on ₦150.00 for 2½ years is ₦4.50, find the interest on ₦250.00 for 6 months at the same rate.|₦15.00|₦1.50|₦18.00|₦7.50": "commercial",
  "|If 321_{4} is divided by 23_{4} and leaves a remainder r, what is the value of r?|2|0|3|1": "number-bases",
  "|The Venn diagram above shows a class of 40 students with the games they play. How many of the students play two games only?|16|4|19|15": "sets",
  "|Evaluate (81^{3/4} − 27^{1/3})/(3 × 2³).|1|1/8|0|3/5": "indices",
  "|Find the value of m if 13_{m} + 24_{m} = 41_{m}.|5|2|6|8": "number-bases",
  "|If U = {x : x is a positive integer less than 10} and P = {x : x is a prime factor of 30}, find the complement of P.|{1, 4, 7, 8, 9}|{1, 2, 4, 7, 8, 9}|{1, 2, 4, 6, 7, 8, 9}|{1, 4, 6, 7, 8, 9}": "sets",
  "|A father decided to give 20% of his monthly income to his three children as their monthly allowance. The eldest child got 45% of the allowance and the youngest got 25%. How much was the father's monthly income if the second child got ₦3000?|₦50,000|₦33,000|₦60,000|₦45,000": "commercial",
  "|If log_{10} 2 = 0.3010 and log_{10} 3 = 0.4771, evaluate log_{10} 4.5.|0.4771|0.3010|0.6532|0.9542": "logarithms",
  "|Simplify 3½ − (2⅓ × 1¼) + 3/5.|1 11/60|1 1/60|2 11/60|2 1/60": "fractions-decimals",
  "|In how many ways can 6 coloured chalks be arranged if 2 are of the same colour?|120|240|360|60": "permutations",
  "|Scores: 1, 2, 3, 4, 5, 6. No. of students: 1, 4, 5, 6, x, 2. The table above shows the scores of a group of students in a test. If the average score is 3.5, find the value of x.|2|4|1|3": "statistics",
  "|A box contains 5 blue balls, 3 red balls and 2 white balls. Two balls are selected from the box with replacement. Find the probability of obtaining two blue or two red balls.|3/250|1/50|17/50|3/25": "probability",
  "|Find the value of t if the standard deviation of 2t, 3t, 4t, 5t and 6t is √2.|3|1|4|2": "statistics",
  "|The grades of 36 students in a test are shown in the pie chart above. How many students had excellent?|12|7|8|9": "statistics",
  "|What is the probability that an integer x (1 ≤ x ≤ 20) chosen at random is divisible by both 2 and 3?|3/20|7/10|1/20|1/3": "probability",
  "|The modal height and range of heights 1.35, 1.25, 1.35, 1.40, 1.35, 1.45, 1.50, 1.35, 1.40 and 1.20 are m and r respectively. Find m + 2r.|3.00|1.95|1.65|1.35": "statistics",
  "|How many possible ways are there of seating seven people P, Q, R, S, T, U and V at a circular table?|720|5040|360|2520": "permutations",
  "|The histogram above shows the distribution of the monthly incomes of the workers in a company. How many workers earn more than ₦700.00?|8|16|6|12": "statistics",
  "|Divide 6x² − 13x + 5 by 2x − 1.|5x + 3|5x − 3|3x + 5|3x − 5": "algebra",
  "|The diagram above is the graph of the function f(x). Determine the range of values of x for which f(x) ≤ 0.|0 ≤ x ≤ 2|x ≤ 2|x ≤ −2, 0 ≤ x ≤ 2|−2 ≤ x ≤ 0, x ≥ 2": "inequalities",
  "|The time taken to do a piece of work is inversely proportional to the number of men employed. If it takes 30 men to do a piece of work in 6 days, how many men are required to do the work in 4 days?|35|60|20|45": "variation",
  "|Find the sum of the first 20 terms of the series 8, 12, 16, …, 96.|1040|960|920|1400": "sequences",
  "|The weight W kg of a metal bar varies jointly as its length L metres and the square of its diameter d metres. If W = 140 when d = 4⅔ and L = 54, find d in terms of W and L.|42W/(5L)|√(42W/(5L))|5L/(42W)|√(5L/(42W))": "variation",
  "|If the 7th term of an AP is twice the third term and the sum of the first four terms is 42, find the common difference.|1|2|3|6": "sequences",
  "|An operation * is defined on the set of real numbers by a * b = ab + 2(a + b + 1). Find the identity element.|−2|−1|2|1": "binary-operations",
  "|Find the range of values of x for which 7x − 3 > 25 + 3x.|x < −7|x > −7|x < 7|x > 7": "inequalities",
  "|If m = 3, p = −3, q = 7 and r = 5/2, evaluate m(p + q + r).|18.95|19.50|18.05|19.15": "algebra",
  "|If p = [[1, 3, 2], [4, 5, −1], [−3, 2, 0]], find the determinant of matrix p.|−75|−57|57|75": "matrices",
  "|A polynomial in x whose zeros are −2, −1 and 3 is|x³ + 7x + 6|x³ − 7x + 6|x³ − 7x − 6|x³ + 7x − 6": "quadratics",
  "|If M and N are two matrices defined by M = [[1, 3, 2], [4, 5, −1], [−3, 2, 0]] and N = [[1, −2, 3], [4, −1, 5], [2, −3, −1]], evaluate 2M − 3N.|[[−1, 12, −5], [−4, 13, −17], [−12, 13, 3]]|[[−1, 12, 5], [4, 7, 13], [0, 12, −5]]|[[−1, 0, −5], [−4, 7, −17], [0, −5, 3]]|[[−1, 12, −5], [−4, 13, −17], [−12, 13, 3]]": "matrices",
  "|The gradient of a curve is 2x + 7 and the curve passes through the point (2, 0). Find the equation of the curve.|y = x² + 14x + 11|y = x² + 7x + 9|y = x² + 7x − 18|y = x² + 7x + 18": "integration",
  "|Evaluate ∫_{−4}^{0} (1 − 2x) dx.|−16|20|−20|10": "integration",
  "|Differentiate (x² − 1/x)² with respect to x.|4x^{3} − 2 − 2/x^{3}|4x^{3} − 2 + 2/x^{3}|4x^{3} − 3x + 2/x|4x^{3} − 4x − 2/x": "differentiation",
  "|Find the value of x for which the function 3x^{3} − 9x² is minimum.|3|5|0|2": "differentiation",
  "|If dy/dx = x + cos x, find y.|x²/x^{3} − sin x + c|x² − sin x + c|x²/2 + sin x + c|x² + sin x + c": "integration",
  "|Differentiate (cos θ − sin θ)² with respect to θ.|−2 sin 2θ|−2 cos 2θ|1 − 2 cos 2θ|x² + sin x + c": "differentiation",
  "|What is the locus of points equidistant from the line ax + by + c = 0?|A line ax + by + q = 0|A line ax − by + q = 0|A line bx − ay + q = 0|A line bx + ay + q = 0": "geometry",
  "|In the diagram above, POQ is a diameter of the circle PQRS. If ∠PSR = 145°, find x°.|45°|25°|55°|35°": "geometry",
  "|If tan θ = 5/4, find sin²θ − cos²θ.|41/9|9/41|1|5/4": "trigonometry",
  "|In the diagram above, |QR| is the diameter of the semicircle QR. Find the area of the figure to the nearest whole number.|80 cm²|70 cm²|90 cm²|89 cm²": "mensuration",
  "|PQRSTW is a regular hexagon and QS intersects RT at V. Calculate ∠TVS.|60°|90°|12°|30°": "geometry",
  "|If the locus of the points which are equidistant from point P and Q meets line PQ at point N, then PN equals|½NQ|2NQ|¼NQ|NQ": "geometry",
  "|In the diagram above, PQ = 10 cm, PS = 8 cm and ∠PSR is 60° while ∠SRQ is a right angle. Find SR.|14√3 cm|14 cm|10√3 cm|10 cm": "trigonometry",
  "|PQ and RS are two parallel lines. If the coordinates of P, Q, R, S are (1, q), (3, 2), (3, 4), (5, 2q) respectively, find the value of q.|4|1|2|3": "coordinate",
  "|In the diagram above, find the value of x.|45°|55°|40°|50°": "geometry",
  "|In triangle XYZ, ∠XYZ = 15°, ∠XZY = 45° and |XY| = 7 cm. Find |YZ|.|7√2 cm|7 cm|14√2 cm|(7/2)√6 cm": "trigonometry",
  "|Score: 1, 2, 3, 4, 5, 6, 7, 8. Frequency: 2, 3, 5, 12, 10, 6, 4, 1. The table above shows the scores of a group of students in a Physics test. If the mode is m and the number of students who scored 4 or more is n, what is (n, m)?|(33, 12)|(33, 4)|(22, 4)|(12, 4)": "statistics",
  "|For what value of n is ^{n+1}C_{3} = 4(^{n}C_{3})?|4|6|3|5": "permutations",
  "|The response of 160 pupils in a school asked to indicate their favourite subjects is given in the bar chart above. What percentage of the pupils has English and Health Education as their favourite subjects?|52%|55%|36%|22%": "statistics",
  "|A bag contains 5 black, 4 white and x red marbles. If the probability of picking a red marble is 2/5, find the value of x.|6|10|4|8": "probability",
  "|GSM operators: GTN, PLO, QTel, CMOB. Number of recharge cards: 5, 6, 3, 6. The table above shows the distribution of recharge cards of four major GSM operators. What is the probability that a recharge card selected at random will be GTN or QTel?|2/5|3/4|3/20|1/4": "probability",
  "|The pie chart above shows the expenditure of a family whose income is ₦30,000. If the expenditure on food is twice that on housing and that on school fees is twice that on transport, how much does the family spend on food?|₦28,000|₦25,000|₦12,500|₦28,000": "statistics",
  "|Find the variance of 2x, 2x − 1 and 2x + 1.|√(2/3)|2|1|2/3": "statistics",
  "|If the mean of five consecutive integers is 30, find the largest of the numbers.|30|28|34|32": "statistics",
  "|A final examination requires that a student answer any 4 out of 6 questions. In how many ways can this be done?|30|20|15|45": "permutations",
  "|The cost of renovating a 6m square room is ₦540. What is the cost of renovating a 9m square room?|₦720|₦810|₦1,620|₦1,215": "commercial",
  "|How many terms of the series 3, −6, +12, −24, + … are needed to make a total of 1 − 2^{8}?|9|12|8|10": "sequences",
  "|The solution set of the shaded area above is|y + x ≥ 4, y ≤ x|y ≤ x, y + x ≤ 4 and y ≥ 0|y ≥ 0, y ≥ x and y + x ≤ 4|y ≤ x, y + x ≤ 4": "inequalities",
  "|Find the value of k if the expression kx^{3} + x² − 5x − 2 leaves a remainder 2 when it is divided by 2x + 1.|8|−10|10|−8": "quadratics",
  "|Solve the inequality for which (x + 4)/3 − (x − 3)/2 < 4.|x > 7|x < 7|x < −7|x > −7": "inequalities",
  "|If x = [[1, 0, 1], [2, −1, 0], [−1, 0, 1]] and y = [[−1, 1, 2], [0, −1, −1], [2, −1, 1]], find 2x − y.|[[3, −1, 0], [4, 1, 1], [−1, 0, 1]]|[[3, −1, 0], [2, −1, 0], [−1, 0, 1]]|[[3, −1, 0], [4, −3, 1], [−4, 1, 1]]|[[3, −1, 0], [4, −1, 1], [−4, 1, 1]]": "matrices",
  "|Find the roots of x^{3} − 2x² − 5x + 6 = 0.|1, 2, −3|1, −2, 3|−1, 2, −3|−1, −2, 3": "quadratics",
  "|If y = x² − x − 12, find the range of values of x for which y ≥ 0.|x ≤ −3 or x ≥ 4|x < −3 or x > 4|−3 ≤ x ≤ 4|−3 < x ≤ 4": "quadratics",
  "|A binary operation * on the set of rational numbers is defined as x * y = (x² − y²)/(2xy). Find −5 * 3.|17/15|−17/15|8/15|−8/15": "binary-operations",
  "|If T = 2π√(l/g), make g the subject of the formula.|4πl²/T|4πl²/T^{3}|2π√l/T|4π²l/T²": "algebra",
  "|The sum of the first n positive integers is|n(n − 1)|n(n + 1)|½n(n + 1)|½n(n − 1)": "sequences",
  "|Find p, q for which [[2p, 8], [3, −5q]] × [[1], [2]] = [[24], [−17]].|(−4, −2)|(−4, 2)|(4, 2)|(4, −2)": "matrices",
  "|If p varies inversely as the cube of q and q varies directly as the square of r, what is the relationship between p and r?|p varies inversely as r^{6}|p varies directly as r^{6}|p varies directly as r^{3}|p varies inversely as 6√r": "variation",
  "|A binary operation * defined on the set of real numbers is such that x * y = xy/6 for all x, y ∈ R. Find the inverse of 20 under this operation when the identity element is 6.|10/3|9/5|1/20|1/12": "binary-operations",
  "|If m : n = 13 : 11, find m² − n² : (m + n)².|1 : 12|1 : 10|1 : 13|1 : 11": "commercial",
  "|Convert 2232_{4} to a number in base 6.|540_{6}|254_{6}|553_{6}|450_{6}": "number-bases",
  "|Calculate the logarithm to base 9 of 3^{−4} × 9² × (81)^{−1}.|0|2|−4|−2": "logarithms",
  "|Find the tax on an income of ₦20,000 if no tax is paid on the first ₦10,000 and tax is paid at ₦50 in ₦1,000 on the next ₦5,000 and at ₦55 in ₦1,000 on the remainder.|₦525|₦552|₦255|₦500": "commercial",
  "|Simplify (25)^{−1/2} × (27)^{1/3} + (121)^{−1/2} × (625)^{−1/4}.|14/5|9/11|3/275|34/55": "indices",
  "|Compute 110011_{2} + 11111_{2}.|1010010_{2}|1001010_{2}|1000110_{2}|1000100_{2}": "number-bases",
  "|If E ⊆ G ⊆ U, where U is the universal set, then the shaded Venn diagram representing U − E or E' is|A|B|C|D": "sets",
  "|Simplify (7/9 − 2/3) ÷ (1/3 + 2/5 ÷ 4/5).|11/12|5/6|2/15|74/45": "fractions-decimals",
  "|In a small village of 500 people, 350 speak the local language while 200 speak Pidgin English. What percentage of the population speaks both?|30%|50%|10%|14%": "sets",
  "|If (K2)_{6} × 3_{6} = 3_{5}(K4)_{5}, what is the value of K?|2|4|1|3": "number-bases",
  "|Rationalize 2/(6 − 5√3).|12/39 + 10√3/39|12/39 − 10√3/39|−12/39 − 10√3/39|12/39 + 10√3/39": "surds",
  "|Evaluate (1011_{2})² − (101_{2})².|110_{2}|11000_{2}|110000_{2}|1100000_{2}": "number-bases",
  "|If x_{10} = 1214_{5}, find x.|184|180|124|121": "number-bases",
  "|Simplify 3/5 ÷ (2/7 × 4/3 ÷ 4/9).|21/6|6/7|4/5|7/10": "fractions-decimals",
  "|Evaluate ((0.5625)² − (0.4375)²)/0.04, correct to 3 significant figures.|3.13|3.12|3.11|0.313": "fractions-decimals",
  "|A man made a profit of 5% when he sold an article for ₦60,000.00. How much would he have to sell the article to make a profit of 26%?|₦72,000|₦70,000|₦68,000|₦65,000": "commercial",
  "|The sum of the ages of Musa and Lawal is 28 years. After sharing a certain sum of money in the ratio of their ages, Musa gets ₦600 and Lawal ₦800. How old is Lawal?|12 years|14 years|16 years|20 years": "commercial",
  "|Find the value of x for which 2(3^{2x−1}) = 162.|1/2|2/5|3/2|5/2": "indices",
  "|If log_{10} 2 = x, express log_{10} 12.5 in terms of x.|2 + 3x|2 − 3x|2(1 + x)|2(1 − x)": "logarithms",
  "|Find y, if √12 − √147 + y√3 = 0.|1|3|5|7": "surds",
  "|Given that P = {1, 3, 5, 7, 9, 11} and Q = {2, 4, 6, 8, 10, 12}, determine the relationship between P and Q.|P ∩ Q|Q ⊃ P|P = Q|P ∩ Q = Φ": "sets",
  "|If X = {all perfect squares less than 40} and Y = {all odd numbers from 1 to 15}, find X ∩ Y.|{9}|{1, 9}|{3, 9}|{9, 25}": "sets",
  "|Make L the subject of the formula if d = √(42W/(5L)).|42/(5dW)|√(42W/(5d))|42W/(5d²)|(1/d)√(42W/5)": "algebra",
  "|Factorize 2t² + t − 15.|(t + 3)(t − 5)|(2t − 3)(t + 5)|(2t + 3)(t − 5)|(t + 3)(2t − 5)": "algebra",
  "|The graph above is represented by|y = x³ − 4x + 2|y = x³ − 3x − 2|y = x³ + 2x² − x − 2|y = x³ − 4x² + 5x − 2": "algebra",
  "|W ∝ L² and W = 6 when L = 4. If L = √17, find W.|5 1/3|6 3/8|5 5/8|6 7/8": "variation",
  "|The solution of the quadratic inequality x² + x − 12 ≥ 0 is|x ≤ −12 or x ≤ −4|x ≥ 3 or x ≤ −4|x ≥ −3 or x ≤ 4|x ≥ 3 or x ≥ −4": "inequalities",
  "|Solve the inequality −3(x − 2) < −2(x + 3).|x < −12|x > −12|x < 12|x > 12": "inequalities",
  "|The nth term of the sequence 3/2, 3, 7, 16, 35, 74, … is|(3/2)n|3 × 2^{n−2}|5 × 2^{n−2−n+½}|5 × 2^{n−2} − n": "sequences",
  "|Find the sum to infinity of the series 2 + 3/2 + 9/8 + 27/32 + …|1|2|4|8": "sequences",
  "|A binary operation ⊕ on real numbers is defined by x ⊕ y = xy + x + y for any two real numbers x and y. The value of (−3/4) ⊕ 6 is|−9/2|−3/4|3/4|45/4": "binary-operations",
  "|A binary operation Δ is defined by a Δ b = a + b + 1 for any real numbers a and b. Find the inverse of the real number 7 under the operation Δ, if the identity element is −1.|9|5|−7|−9": "binary-operations",
  "|Evaluate [[3, −2], [−7, 5]] + 2[[−2, 4], [3, −1]].|[[3, 4], [2, 6]]|[[−1, 6], [1, 3]]|[[4, 3], [−2, 6]]|[[−1, 6], [−1, 3]]": "matrices",
  "|If f(x) = 3x − 2, P = [[2, 1], [−1, 0]] and I is the 2 × 2 identity matrix, evaluate f(P).|[[8, 3], [−3, 2]]|[[6, 3], [−3, 0]]|[[4, 3], [−3, −2]]|[[2, 0], [0, −2]]": "matrices",
  "|If the lines 2y − kx + 2 = 0 and y + x − k/2 = 0 intersect at (1, −2), find the value of k.|−1|−2|−3|−4": "coordinate",
  "|Find the size of each exterior angle of a regular octagon.|36°|40°|45°|51°": "geometry",
  "|In the parallelogram PQRS above, find angle SQR.|30°|50°|80°|100°": "geometry",
  "|The area of a square is 144 cm². Find the length of the diagonal.|11√3 cm|12 cm|12√2 cm|13 cm": "mensuration",
  "|Calculate the length of an arc of a circle of diameter 14 cm that subtends an angle of 90° at the centre of the circle.|7π/4|7π/2|7π|14π": "mensuration",
  "|The volume of a hemispherical bowl is 718⅔ cm³. Find its radius.|3.8 cm|4.0 cm|5.6 cm|7.0 cm": "mensuration",
  "|Find the locus of points equidistant from two straight lines y − 5 = 0 and y − 3 = 0.|y − 1 = 0|y − 2 = 0|y − 3 = 0|y − 4 = 0": "geometry",
  "|A particle P moves between points S and T such that angle SPT is always constant. Find the locus of P.|It is a perpendicular bisector of ST|It is a straight line perpendicular to ST|It is a semi-circle with ST as diameter|It is a quadrant of a circle with ST as diameter": "geometry",
  "|What is the value of k if the mid-point of the line joining (1 − k, −4) and (2, k + 1) is (−k, k)?|−1|−2|−3|−4": "coordinate",
  "|If the lines 3y = 4x − 1 and qy = x + 3 are parallel to each other, the value of q is|4/3|3/4|−4/3|−3/4": "coordinate",
  "|Find the value of (tan 60° − tan 30°)/(tan 60° + tan 30°).|2/3|4/3|1/2|1": "trigonometry",
  "|A man 40 m from the foot of a tower observes the angle of elevation of the tower to be 30°. Determine the height of the tower.|40√3 m|40√3/3 m|40 m|20 m": "trigonometry",
  "|If y = x cos x, find dy/dx.|cos x + x sin x|cos x − x sin x|sin x − x cos x|sin x + x cos x": "differentiation",
  "|If y = (1 + x)², find dy/dx.|2 + 2x|1 + 2x|2x − 1|x − 1": "differentiation",
  "|Find the value of x for which the function f(x) = 2x³ − x² − 4x + 4 has a maximum value.|−1|−2/3|1|2/3": "differentiation",
  "|Integrate (x² − √x)/x with respect to x.|2(x² − √x)/(3x) + K|(x² − √x)/x²|x²/2 − 2√x + K|x²/x − √x + K": "integration",
  "|Determine the value of ∫_{0}^{π/2} (−2 cos x) dx.|−3|−2|−3/2|−1/2": "integration",
  "|Mark: 3, 4, 5, 6, 7, 8. Frequency: 5, y − 1, y, 9, 4, 1. The table gives the frequency distribution of marks obtained by a group of students in a test. If the total mark scored is 200, calculate the value of y.|9|11|13|15": "statistics",
  "|The histogram above represents the weight of students who travelled out of their school for an examination. How many people made the trip?|29|38|69|78": "statistics",
  "|The pie chart above illustrates the amount of private time a student spends in a week studying various subjects (Maths 105°, Science 75°, Social Studies 2k, English 3k, Others k). Find the value of k.|15°|30°|60°|90°": "statistics",
  "|The cumulative frequency for 5 ≤ x ≤ 12 from the distribution above is|72|46|40|22": "statistics",
  "|If 5, 8, 6 and 2 occur with frequencies 3, 2, 4 and 1 respectively, find the product of the modal and the median number.|48|40|36|30": "statistics",
  "|What is the mean deviation of 3, 5, 8, 11, 12 and 21?|60|10|4.7|3.7": "statistics",
  "|A senatorial candidate had planned to visit seven cities prior to a primary election. However, he could only visit four of the cities. How many different itineraries could be considered?|520|640|720|840": "permutations",
  "|In how many ways can 6 subjects be selected from 10 subjects for an examination?|210|215|216|218": "permutations",
  "|In a basket, there are 6 grapes, 11 bananas and 13 oranges. If one fruit is chosen at random, what is the probability that the fruit is either a grape or a banana?|17/30|11/20|6/30|5/30": "probability",
  "|Age in years: 10, 11, 12. No. of pupils: 6, 27, 7. The table shows the number of pupils in each age group in a class. What is the probability that a pupil chosen at random is at least 11 years old?|17/20|33/40|27/40|3/30": "probability",
  "|Add 1101_{2}, 10111_{2} and 111_{2}.|111011_{2}|110110_{2}|101011_{2}|101010_{2}": "number-bases",
  "|If 125_{x} = 20_{10}, find x.|¼|3|½|1": "number-bases",
  "|Evaluate (3/8 ÷ 1/2 − 1/3)/(1/8 × 2/3 + 1/3).|¼|1/3|½|1": "fractions-decimals",
  "|Express 123456 to 3 significant figures.|123000|124000|125000|126000": "fractions-decimals",
  "|Calculate the simple interest on ₦7,500 for 8 years at 5% per annum.|₦3000|₦600|₦300|₦150": "commercial",
  "|The cost of kerosene per litre increases from ₦60 to ₦85. What is the percentage rate of increase?|42%|41%|40%|25%": "commercial",
  "|Simplify 16^{−1/2} × 4^{−1/2} × 27^{1/3}.|3/8|2/3|3/4|3/2": "indices",
  "|If log_{x^{1/2}} 64 = 3, find the value of x.|4|16|32|64": "logarithms",
  "|If (1 + √2)/(1 − √2) is expressed in the form x + y√2, find the values of x and y.|(−3, −2)|(−2, 3)|(3, 2)|(2, −3)": "surds",
  "|If X = {n² + 1 : n = 0, 2, 3} and Y = {n + 1 : n = 2, 3, 5}, find X ∩ Y.|{1, 3}|{5, 10}|∅|{2, 1}": "sets",
  "|A bookseller sells Mathematics and English books. If 30 customers buy Mathematics books, 20 customers buy English books and 10 customers buy the two books, how many customers has he altogether?|30|40|50|60": "sets",
  "|Make Q the subject of the formula L = (4/3)M√(PQ).|9L²/(16M²P)|3L/(4√P)|√(3L)/(4MP)|3L²/(16M²P)": "algebra",
  "|If 2x² − kx − 12 is divisible by x − 4, find the value of k.|4|6|5|7": "quadratics",
  "|Factorize completely (4x + 3y)² − (3x − 2y)².|(x + 5y)(7x + y)|(x + 5y)(7x − y)|(x − 5y)(7x + y)|(x − 5y)(7x − y)": "algebra",
  "|If x − 3 is directly proportional to the square of y and x = 5 when y = 2, find x when y = 6.|30|21|16|12": "variation",
  "|If p varies inversely as the square of q and p = 8 when q = 4, find q when p = 32.|±16|±8|±4|±2": "variation",
  "|Find the range of values of x which satisfy the inequalities 4x − 7 ≤ 3x and 3x − 4 ≤ 4x.|−4 ≤ x ≤ 7|−7 ≤ x ≤ 4|x ≥ −7|−7 ≤ x ≤ 6": "inequalities",
  "|Solve the quadratic inequality x² − 5x + 6 ≥ 0.|x ≤ 2, x ≥ 3|x ≤ x, x > 2|x ≤ −2, x ≥ −3|x ≤ −3, x ≥ 2": "quadratics",
  "|The shaded area that gives the solution set for the inequalities x + y ≤ 3, x − y ≤ 3, is|A|B|C|D": "inequalities",
  "|The fifth term of an A.P. is 24 and the eleventh term is 96. Find the first term.|12|4|−12|−24": "sequences",
  "|A binary operation * defined on the set of positive integers is such that x * y = 2x − 3y + 2 for all positive integers x and y. The binary operation is|commutative and closed on the set of positive integers|neither commutative nor closed on the set of positive integers|commutative but not closed on the set of positive integers|not commutative but closed on the set of positive integers": "binary-operations",
  "|A binary operation on the set of real numbers excluding −1 is such that for all m, n ∈ R, m Δ n = m + n + mn. Find the identity element of the operation.|1|0|−½|−1": "binary-operations",
  "|Find the values of x and y respectively if [[1, 0], [−1, −1], [2, 2]] + [[x, 1], [−1, 0], [y, −2]] = [[−2, 1], [−2, −1], [−3, 0]].|−3, −2|−5, −3|−2, −5|−3, −5": "matrices",
  "|If [[−2, 1], [2, 3]] [[p, q], [r, s]] = [[1, 0], [0, 1]], what is the value of r?|−3/8|3/8|5/8|1/4": "matrices",
  "|In the diagram above, PQ // RS. The size of the angle marked x is|100°|80°|50°|30°": "geometry",
  "|Find the exterior angle of a 12-sided regular polygon.|12°|24°|25°|30°": "geometry",
  "|In the diagram above, ∠OPQ is|90°|53°|36°|26°": "geometry",
  "|Find the area of the figure below.|12.5 cm²|75.0 cm²|78.5 cm²|84.8 cm²": "mensuration",
  "|Find the angle subtended at the centre of a circle by a chord which is equal in length to the radius of the circle.|30°|45°|60°|90°": "geometry",
  "|Find the capacity in litres of a cylindrical well of radius 1 metre and depth 14 metres. [π = 22/7]|44000 litres|440 litres|44 litres": "mensuration",
  "|The locus of a point equidistant from two points P(6, 2) and R(4, 2) is a perpendicular bisector of PR passing through|(2, 5)|(5, 2)|(1, 0)|(0, 1)": "geometry",
  "|Find the gradient of a line which is perpendicular to the line with the equation 3x + 2y + 1 = 0.|3/2|2/3|−2/3|−3/2": "coordinate",
  "|Calculate the distance between points L(−1, −6) and M(−3, −5).|√5|2√5|20|√53": "coordinate",
  "|If sin θ = 3/5, find tan θ.|3/4|3/5|2/5|1/4": "trigonometry",
  "|A student sitting on a tower 68 metres high observes his principal's car at an angle of depression of 20°. How far is the car from the bottom of the tower to the nearest metre?|184 m|185 m|186 m|187 m": "trigonometry",
  "|Find the derivative of y = (x^{7} − x^{5})/x^{4}.|x(x² − 1)|3x(x² − 1)|3x² − 1|7x^{6} − 5x^{4}": "differentiation",
  "|Differentiate sin x − x cos x.|x cos x|x sin x|−x cos x|−x sin x": "differentiation",
  "|Find the minimum value of the function y = x(1 + x).|−1/4|−1/2|1/4|1/2": "differentiation",
  "|Evaluate ∫_{1}^{2} (6x² − 2x) dx.|16|13|12|11": "integration",
  "|Evaluate ∫_{−π/2}^{π/2} cos x dx.|0|1|2|3": "integration",
  "|On a pie chart, there are six sectors of which four angles are 30°, 45°, 60°, 90° and the remaining two angles are in the ratio 2 : 1. Find the smaller of the remaining two angles.|15°|30°|45°|60°": "statistics",
  "|The bar chart above shows the number of times the words a, and, in, it, the, to appear in a paragraph in a book. What is the ratio of the least frequent word to that of the most frequent word?|1/6|1/3|2/3|3/4": "statistics",
  "|What is the mean of the data t, 2t − 1, t − 2, 2t − 1, 4t and 2t + 2?|2t|2t − 1|(2t/3)t + 1|2t − 1/3": "statistics",
  "|Find the median of 4, 1, 4, 1, 0, 4, 4, 2 and 0.|0|1|2|4": "statistics",
  "|If x > 0, find the range of the numbers x − 3, 3x + 2, x − 1, 4x, 2x − 1, x − 2, 2x − 2, 3x and 3x + 1.|3x + 3|3x + 1|2x + 5|2x + 1": "statistics",
  "|Find the mean deviation of 2, 4, 5 and 9.|1|2|5|7": "statistics",
  "|In how many ways can the letters of the word ACCEPTANCE be arranged?|10!/(2!2!3!)|10!/(2!3!)|10!/(2!2!)|10!": "permutations",
  "|Find the number of ways of selecting 6 out of 10 subjects for an examination.|218|216|215|210": "permutations",
  "|The probability of picking a letter T from the word OBSTRUCTION is|1/11|2/11|3/11|4/11": "probability",
  "|The result of rolling a fair die 150 times is as summarized in the table below. No. on die: 1, 2, 3, 4, 5, 6; No. of occurrence: 12, 18, x, 30, 2x, 45. What is the probability of obtaining a 5?|3/5|1/5|1/6|1/10": "probability",
  "|Subtract 16418_{9} from 18630_{9}.|1121_{9}|2112_{9}|2113_{9}|2211_{9}": "number-bases",
  "|If 55_{x} + 52_{x} = 77_{10}, find x.|5|6|7|10": "number-bases",
  "|Simplify 7 1/12 − 4 3/4 + 2 1/2.|4|4 1/6|4 5/6|5 1/6": "fractions-decimals",
  "|Evaluate (81.81 + 99.44)/(20.09 + 36.16) correct to 3 significant figures.|6.21|3.22|3.22|2.13": "fractions-decimals",
  "|A man bought a second-hand photocopying machine for ₦34,000. He serviced it at a cost of ₦2,000 and then sold it at a profit of 15%. What was the selling price?|₦37,550|₦40,000|₦41,400|₦42,400": "commercial",
  "|A student spent 1/5 of his allowance on books, 1/3 of the remainder on food and kept the rest for contingencies. What fraction was kept?|7/15|8/15|2/3|4/5": "commercial",
  "|Solve 5^{2(x − 1)} × 5^{x + 1} = 0.04.|1/3|1/4|−1/5|−1/3": "indices",
  "|If log_{10} 2 = 0.3010 and log_{10} 7 = 0.8451, evaluate log_{10} 280.|0.4471|2.4471|1.2271|1.1071": "logarithms",
  "|Simplify (5 + √7)/(3 + √7).|4 + √7|4 − √7|15 + √7|7 − √7": "surds",
  "|If X = {n² + 1 : n is a positive integer and 1 ≤ n ≤ 5} and Y = {5n : n is a positive integer and 1 ≤ n ≤ 5}, find X ∩ Y.|{5, 10}|{5, 10, 15}|{2, 10}|{2, 5}": "sets",
  "|I. S ∩ T ∩ W = S   II. S ∪ T ∪ W = W   III. T ∩ W = S. If S ⊂ T ⊂ W, which of the above statements are true?|I and II|I and III|II and III|I, II and III": "sets",
  "|If P = √(rs³/t), express r in terms of P, s and t.|P²t/s³|P³t/s³|P²t/s²|Pt/3": "algebra",
  "|A polynomial in x whose roots are 4/3 and −3/5 is|15x² − 11x − 12|15x² + 11x − 12|12x² − x − 12|12x² + 11x − 15": "quadratics",
  "|Which of the following equations represents the graph above?|y = 2 + 7x + 4x²|y = 2 − 7x + 4x²|y = 2 + 7x − 4x²|y = 2 − 7x − 4x²": "quadratics",
  "|W is directly proportional to U. If W = 5 when U = 3, find U when W = 2/7.|6/35|10/21|21/10|35/6": "variation",
  "|Determine the values of x for which (x² − 1) > 0.|x < −1 or x > 1|−1 < x < 1|x > 0|x < −1": "inequalities",
  "|Find the range of values of x for which 3x − 7 ≤ 0 and x + 5 > 0.|15 < x < 7/3|−5 ≤ x ≤ 7/3|−5 < x ≤ 7/3|−5 ≤ x < 7/3": "inequalities",
  "|The sum of the first n terms of the arithmetic progression 5, 11, 17, 23, 29, 35, … is|n(3n − 0.5)|n(3n + 2)|n(3n + 2.5)|n(3n + 5)": "sequences",
  "|Find, to infinity, the sum of the sequence 1, 9/10, (9/10)², (9/10)³, …|10|9|10/9|9/10": "sequences",
  "|If m * n = n − (m + 2) for any real numbers m and n, find the value of 3 * (−5).|−6|−8|−10|−12": "binary-operations",
  "|A binary operation ⊕ defined on the set of integers is such that m ⊕ n = m + n + mn for all integers m and n. Find the inverse of −5 under this operation, if the identity element is 0.|−5/4|−5/6|0|5": "binary-operations",
  "|If Q = [[9, −2], [−7, 4]], then |Q| is|−50|−22|22|50": "matrices",
  "|If P = [[x + 3, x + 2], [x + 1, x − 1]], evaluate x if |P| = −10.|−5|−2|2|5": "matrices",
  "|Find the acute angle between the straight lines y = x and y = √3 x.|15°|30°|45°|60°": "coordinate",
  "|A regular polygon has 150° as the size of each interior angle. How many sides does it have?|12|10|9|8": "geometry",
  "|In the figure above, TS ∥ XY and XY = TY, ∠STZ = 34°, ∠TXY = 47°. Find the angle marked n.|47°|52°|56°|99°": "geometry",
  "|If the hypotenuse of a right-angled isosceles triangle is 2 cm, what is the area of the triangle?|1/√2 cm²|1 cm²|√2 cm²|2√2 cm²": "mensuration",
  "|A chord is drawn 5 cm away from the centre of a circle of radius 13 cm. Calculate the length of the chord.|7 cm|9 cm|12 cm|24 cm": "geometry",
  "|Find the radius of a sphere whose surface area is 154 cm².|7.00 cm|3.50 cm|3.00 cm|1.75 cm": "mensuration",
  "|Find the locus of a particle which moves in the first quadrant so that it is equidistant from the lines x = 0 and y = 0 (where k is a constant).|x + y = 0|x − y = 0|x + y + k = 0|x − y − k = 0": "geometry",
  "|What is the locus of the mid-points of all chords of length 6 cm within a circle of radius 5 cm and with centre O?|A circle of radius 5 cm and with centre O|The perpendicular bisector of the chords|A straight line passing through centre O|A circle of radius 4 cm and with centre O": "geometry",
  "|What is the value of p if the gradient of the line joining (−1, p) and (p, 4) is 2/3?|−2|−1|1|2": "coordinate",
  "|What is the value of r if the distance between the points (4, 2) and (1, r) is 3 units?|1|2|3|4": "coordinate",
  "|Find the value of sin 45° − cos 30°.|(2 + √6)/2|(√2 + √3)/4|(√2 + √3)/2|(√2 − √3)/2": "trigonometry",
  "|A cliff on the bank of a river is 300 metres high. If the angle of depression of a point on the opposite side of the river is 60°, find the width of the river.|100 m|75√3 m|100√3 m|200√3 m": "trigonometry",
  "|If y = 3 cos 4x, dy/dx equals|6 sin 8x|−24 sin 4x|12 sin 4x|−12 sin 4x": "differentiation",
  "|If s = (2 + 3t)(5t − 4), find ds/dt when t = 4/5 sec.|0 units per sec|15 units per sec|22 units per sec|26 units per sec": "differentiation",
  "|What value of x will make the function x(4 − x) a maximum?|4|3|2|1": "differentiation",
  "|The distance travelled by a particle from a fixed point is given as s = (t³ − t² − t + 5) cm. Find the minimum distance that the particle can cover from the fixed point.|2.3 cm|4.0 cm|5.2 cm|6.0 cm": "differentiation",
  "|Evaluate ∫ sec² θ dθ.|sec θ tan θ + k|tan θ + k|2 sec θ + k|sec θ + k": "integration",
  "|No. of days: 1, 2, 3, 4, 5, 6. No. of students: 20, 2x, 60, 40, x, 50. The distribution above shows the number of days a group of 260 students were absent from school in a particular term. How many students were absent for at least four days in the term?|180|120|110|40": "statistics",
  "|The histogram above represents the number of candidates that sat for a mathematics examination in a school. How many candidates scored more than 50 marks?|80|95|100|115": "statistics",
  "|The pie chart above represents 400 fruits on display in a grocery store. How many apples are in the store?|45|50|60|70": "statistics",
  "|5, 8, 6 and k occur with frequencies 3, 2, 4 and 1 respectively and have a mean of 5.7. Find the value of k.|4|3|2|1": "statistics",
  "|What is the mean deviation of x, 2x, x + 1 and 3x, if their mean is 2?|0.5|1.0|1.5|2.0": "statistics",
  "|In how many ways can a delegation of 3 be chosen from 5 men and 3 women, if at least 1 man and 1 woman must be included?|15|28|30|45": "permutations",
  "|In how many ways can 9 people be seated if 3 chairs are available?|720|504|336|210": "permutations",
  "|No. of marks: 2, 3, 4, 5, 6, 7, 8, 9. No. of students: 3, 4, 1, 0, 4, 5, 2, 1. The table above shows the distribution of marks of students in a test. Find the probability of passing the test if the pass mark is 5.|3/5|2/5|7/20|1/5": "probability"
 }
};
